import type { AmbientDialogue } from "./ambient-dialogues";
import type { ChoiceData, DialogueLine, Effects, StatKey } from "./game-data";

/*
 * Moments libres de Bellirith (spec §38–41).
 * Plus d’exercices de « bonne séduction » ni de travail sur soi : elle observe,
 * parie, provoque, négocie, s’ennuie, organise des jeux, raconte des histoires
 * orientées sur Valurn et, parfois seulement, propose une heure volée.
 * Une seule banque : l’historique (jamais / déjà / beaucoup de refus / favori)
 * passe par des variantes d’ouverture et des choix conditionnés aux flags.
 * Toute proposition intime est acceptée explicitement par le joueur (le choix
 * qui porte `launchesIntimacy`) ; un refus reste un refus.
 */

const SLEPT = "bellirith-has-slept";
const FAVORITE = "bellirith-favorite";
const RESISTED = "bellirith-has-resisted";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const B = (text: string, mood = "smirk"): DialogueLine => ({ speaker: "Bellirith", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });

type ChoiceOptions = { requiresFlags?: string[]; excludesFlags?: string[]; launchesIntimacy?: string };
const Q = (id: string, text: string, stat: StatKey, response: DialogueLine[], effects: Effects, options: ChoiceOptions = {}): ChoiceData => ({
  id, text, stat, response, effects: { ...effects, stats: { [stat]: 1 } }, ...options,
});
const S = (id: string, title: string, prompt: string, choices: ChoiceData[], options: Partial<AmbientDialogue> = {}): AmbientDialogue => ({
  id, title, prompt, choices, mood: "smirk", ...options,
});
const V = (prompt: string, requiresFlags?: string[], excludesFlags?: string[]) => ({ prompt, requiresFlags, excludesFlags });

/*
 * Chaque proposition libre ouvre sa propre heure volée (bellirith-heure-*.ts).
 * L’ancien identifiant générique « bellirith-free » n’est plus émis.
 */
export const BELLIRITH_FREE_PROPOSALS = {
  ennui: "bellirith-free-ennui",
  matin: "bellirith-free-matin",
  couloir: "bellirith-free-couloir",
} as const;

export const BELLIRITH_AMBIENT_LINES: AmbientDialogue[] = [
  S("bellirith-ecoute", "Ce que chacun veut vraiment", "Bellirith s’est installée derrière un pilier, une coupe à la main, et écoute sans vergogne trois courtisans qui parlent d’un mariage. « Le premier veut la dot. La deuxième veut le marié. Le troisième veut la deuxième. Aucun des trois ne le dira avant l’hiver. Parie contre moi, si tu l’oses. »", [
    Q("bel-ecoute-l", "Écouter à votre tour et trouver ce qu’elle a manqué.", "lucidite", [N("Vous tendez l’oreille. Le troisième courtisan fixe les mains du premier, chaque fois qu’il parle de la dot."), P("Le troisième veut surtout que le premier perde."), B("…Une vengeance. J’ai pris une rancune pour une envie. Elles se ressemblent tellement quand on les regarde de dos.", "thoughtful"), B("Je te dois une coupe. Je déteste devoir quelque chose.", "smirk")], { trust: 3, desire: 2 }),
    Q("bel-ecoute-a", "Parier qu’elle a tort, sans même écouter.", "audace", [B("Tu paries contre moi à l’aveugle ? C’est soit très courageux, soit très mal élevé.", "teasing"), P("Les deux. Je parie surtout que tu vas passer la soirée à vérifier."), N("Elle éclate de rire, assez fort pour que les trois courtisans se retournent et que la conversation meure sur place."), B("Voilà. Pari annulé, preuves détruites. Tu as triché par procuration. J’adore.", "seductive")], { affection: 3, desire: 2 }),
    Q("bel-ecoute-r", "Lui demander ce qu’elle entend chez vous.", "resonance", [B("Chez toi ?", "thoughtful"), N("Elle vous examine de la tête aux pieds, lentement, comme on lit une partition."), B("Tu veux qu’on te laisse finir ce que tu as commencé. Et tu veux savoir si tu as raison de me parler. Le deuxième point, je ne te le dirai pas.", "smirk")], { trust: 2, affection: 2 }),
  ], { promptVariants: [
    V("Bellirith s’est installée derrière un pilier et écoute sans vergogne trois courtisans. Elle vous fait signe d’approcher, et sa main reste sur votre hanche une seconde de trop. « Le premier veut la dot. La deuxième veut le marié. Le troisième veut la deuxième. Toi, je sais déjà ce que tu veux : je t’ai entendu·e le dire. Parie contre moi, si tu l’oses. »", [SLEPT]),
    V("Bellirith s’est installée derrière un pilier et écoute sans vergogne trois courtisans. « Le premier veut la dot. La deuxième veut le marié. Le troisième veut la deuxième. Toi, en revanche, tu restes illisible. C’est très agaçant, et j’ai décidé d’en faire un passe-temps. Parie contre moi. »", [RESISTED], [SLEPT]),
  ] }),

  S("bellirith-figues", "Qui cédera le premier", "Une coupe de figues confites a été oubliée sur un guéridon. Bellirith la pose entre vous deux avec une gravité de duelliste. « Pari. Le premier qui en mange une a perdu. Pas d’aura, pas de main sur la coupe, pas de regard prolongé sur les figues. Le perdant obéit au gagnant pendant une heure. »", [
    Q("bel-figues-s", "Accepter et tenir, quoi qu’elle fasse.", "sangFroid", [N("Elle ne touche pas aux figues. Elle parle d’elles. De leur peau fendue, du sucre qui colle aux doigts, de la façon dont on les mange quand personne ne regarde. Au bout d’un quart d’heure, c’est elle qui avale sa salive."), B("Tu ne bouges pas. Tu ne bouges absolument pas.", "angry"), P("Tu as faim, Bellirith."), N("Elle prend une figue, la croque d’un coup et vous la pointe sous le nez."), B("J’ai perdu exprès. Une heure d’obéissance : je veux que tu me dises comment tu fais.", "teasing")], { trust: 2, desire: 5 }),
    Q("bel-figues-a", "En manger une tout de suite, pour lui voler son jeu.", "audace", [N("Vous prenez une figue avant même qu’elle ait fini d’énoncer les règles. Elle vous regarde la manger, bouche entrouverte d’indignation."), B("Tu… as perdu. En une seconde. Sans te battre.", "angry"), P("J’ai surtout gagné une heure où tu vas devoir trouver quoi me faire faire."), B("…C’est diabolique. C’est censé être mon métier.", "smirk")], { affection: 4, desire: 1 }),
    Q("bel-figues-l", "Renégocier l’enjeu avant d’accepter.", "lucidite", [P("Une heure d’obéissance, c’est vague. Je veux une liste."), B("Une liste. Tu veux rédiger un contrat pour des figues.", "teasing"), P("Je veux surtout savoir ce que tu comptais me demander."), N("Elle se tait. Pour la première fois de la journée, elle a l’air prise en faute."), B("Pas de liste. Tu as gagné sans jouer. Je te hais un peu.", "seductive")], { trust: 3, affection: 1, desire: 2 }),
  ], { minStage: 1 }),

  S("bellirith-tenue", "Ce qu’une robe fait à une salle", "Une baronne vient d’entrer dans une robe d’un vert presque insolent. Bellirith la suit des yeux avec un plaisir de connaisseuse. « Oublie la robe et regarde la salle. Les hommes se redressent, deux femmes ont changé de place, le chambellan a oublié sa phrase. Un tissu bien coupé, c’est une armée qui entre sans tambour. »", [
    Q("bel-tenue-l", "Repérer qui la robe dérange vraiment.", "lucidite", [P("Le chambellan a perdu sa phrase parce qu’il a reconnu le tissu : c’est le même que celui des tentures de l’ambassade."), B("…La baronne porte un message. Et je la regardais comme une robe.", "thoughtful"), B("Tu viens de me gâcher le plus joli spectacle de la soirée en le rendant intéressant. Continue.", "smirk")], { trust: 4 }),
    Q("bel-tenue-a", "Lui demander ce que sa propre tenue fait à la salle, ce soir.", "audace", [B("La mienne ?", "seductive"), N("Elle pivote lentement, une seule fois. Trois conversations s’interrompent à la fois."), B("Elle fait ça. Mais la question intéressante, c’est ce qu’elle te fait à toi. Et tu viens de détourner les yeux.", "teasing")], { affection: 2, desire: 2 }),
    Q("bel-tenue-s", "Juger la robe vous-même, sans flatter personne.", "sangFroid", [P("Belle coupe. Mauvaise couleur pour une femme qui veut qu’on l’écoute."), B("Cruel. Exact. Elle veut qu’on la regarde et se moque bien qu’on l’écoute. Tu as raison, elle aurait dû choisir.", "smirk"), B("J’aime qu’on ne me laisse pas avoir le dernier mot sur le goût.", "thoughtful")], { trust: 2, affection: 2 }),
  ], { locations: ["algratal", "akuhn"], mood: "thoughtful" }),

  S("bellirith-marche", "Négocier pour rien", "Au marché, Bellirith s’est arrêtée devant un étal de rubans dont elle n’a aucun besoin. « Le jeu : on achète le même ruban, chacun de son côté. Celui qui le paie le moins cher a gagné. Interdiction de mentir sur son nom, autorisation de mentir sur tout le reste. »", [
    Q("bel-marche-a", "Négocier avec un aplomb scandaleux.", "audace", [N("Vous inventez une cousine malade, une guilde des rubaniers qui n’existe pas et une rumeur de taxe impériale. Le marchand finit par vous donner le ruban en vous remerciant."), B("Il t’a remercié·e. Il t’a donné le ruban et il t’a remercié·e.", "angry"), B("Moi, je l’ai payé deux sous. Je viens de perdre contre un mensonge plus grand que le mien. C’est délicieux.", "seductive")], { affection: 4, desire: 1 }),
    Q("bel-marche-l", "Observer d’abord ce qui fait céder le marchand.", "lucidite", [N("Vous la regardez faire en premier. Elle flatte, elle s’indigne, elle s’en va pour revenir. Le marchand ne cède qu’une fois : quand elle mentionne sa fille."), P("Il cède pour sa fille. Pas pour toi."), B("Tu m’as utilisée comme éclaireuse.", "cold"), N("Vous obtenez le ruban pour un sou en lui demandant simplement quelle couleur plairait à sa fille."), B("Je suis vexée. Je suis aussi très impressionnée. Ne me demande pas lequel l’emporte.", "smirk")], { trust: 3, desire: 2 }),
    Q("bel-marche-s", "Payer le prix demandé, sans négocier.", "sangFroid", [B("Tu… paies ?", "cold"), P("C’est un bon ruban."), B("Tu sais que tu viens de déclarer forfait dans le seul jeu honnête de la journée ?", "teasing"), N("Elle vous noue le ruban au poignet, d’un geste sec, puis le regarde un moment."), B("Garde-le. Il te rappellera que tu ne sais pas t’amuser.", "smirk")], { affection: 3, trust: 1 }),
  ], { locations: ["algratal"], periods: ["matin", "apres-midi"] }),

  S("bellirith-musicien", "Provoquer l’orchestre", "Un violoniste joue une gigue avec une prudence de fonctionnaire. Bellirith pose une pièce d’or sur son pupitre. « Deux fois plus vite. » Puis une deuxième pièce. « Trois fois. » Elle se tourne vers vous. « Je parie qu’il casse une corde avant la fin. Et toi ? »", [
    Q("bel-musicien-a", "Monter les enchères en dansant devant lui.", "audace", [N("Vous vous lancez seul·e sur la piste. Le violoniste, piqué au vif, accélère. Bellirith vous rejoint en riant, et pendant trois minutes la gigue devient une course."), N("La corde casse à la dernière mesure. Le musicien s’incline, ruisselant et ravi."), B("Personne n’a gagné. Tout le monde a gagné. C’est une très mauvaise façon de parier. Recommence.", "seductive")], { affection: 4, desire: 2 }),
    Q("bel-musicien-r", "Parier qu’il ne cassera rien, parce qu’il est meilleur qu’il ne le montre.", "resonance", [P("Il joue prudemment parce qu’on le paie pour ne pas déranger. Laisse-le jouer pour lui."), N("Le violoniste vous a entendu·e. Il ferme les yeux. La gigue change de nature : plus rapide, mais d’une netteté parfaite. Aucune corde ne casse."), B("Tu as parié sur le talent d’un inconnu plutôt que sur mon or.", "thoughtful"), B("Je perds deux pièces et un pari. Je gagne un musicien. Je garde le musicien.", "smirk")], { trust: 3, affection: 2 }),
    Q("bel-musicien-s", "Récupérer discrètement les pièces avant qu’elle ne surenchérisse.", "sangFroid", [N("Vous glissez les deux pièces dans la poche du violoniste au lieu de les laisser sur le pupitre."), B("Tu viens de lui retirer toute raison de jouer plus vite.", "cold"), P("Et toute raison de te détester demain."), B("…Ce garçon aurait pu me haïr de façon tout à fait divertissante. Tu as une conscience très encombrante.", "teasing")], { trust: 3, desire: 1 }),
  ], { periods: ["soirée"] }),

  S("bellirith-rumeur", "Tester une rumeur", "Bellirith vous attrape par la manche. « On raconte que le ministre des Greniers a une peur bleue des chats. Je propose une expérience scientifique : un chat, une audience, et nous deux au premier rang. »", [
    Q("bel-rumeur-a", "Fournir le chat.", "audace", [N("Le chat des cuisines, gros et dédaigneux, entre dans la salle d’audience sous votre bras. Le ministre ne bronche pas. Il le gratte même derrière les oreilles."), B("Fausse rumeur. Quelle déception.", "cold"), N("Puis le chat éternue, et le ministre fait un bond qui renverse son encrier."), B("Ah. Ce sont les éternuements qui le terrifient. Il faut que je le note.", "teasing")], { affection: 4, desire: 1 }),
    Q("bel-rumeur-l", "Chercher d’abord qui a lancé la rumeur.", "lucidite", [P("Qui t’a raconté ça ?"), B("Un secrétaire. Le sien.", "smirk"), P("Un secrétaire qui veut voir son ministre ridiculisé en audience, devant toi. Ta rumeur ressemble furieusement à une commande."), B("…Et j’allais l’exécuter gratuitement.", "angry"), B("Très bien. On ne fait rien au ministre. On fait quelque chose au secrétaire.", "seductive")], { trust: 4 }),
    Q("bel-rumeur-s", "Refuser l’expérience, mais parier sur le résultat.", "sangFroid", [P("Je ne participe pas. Mais je parie que c’est faux."), B("Tu veux le plaisir du pari sans le risque du chat.", "teasing"), P("Exactement comme toi avec la plupart des gens."), N("Elle reste interdite une seconde, puis rit, bas."), B("Touché. Je teste quand même. Tu viendras regarder, j’en suis sûre.", "smirk")], { trust: 2, desire: 3 }),
  ], { locations: ["algratal"] }),

  S("bellirith-valurn", "L’histoire d’un vieil ami", "Bellirith fait tourner son verre. « Je connais un homme très grand, très sérieux, qui tient son verre comme on tient une épée. Il a perdu un jour un pari contre moi et a dû chanter devant toute une taverne. Il chantait faux. Il chantait faux avec une dignité admirable. Je ne dirai pas son nom. »", [
    Q("bel-valurn-l", "« Valurn. »", "lucidite", [B("Je n’ai rien dit.", "smirk"), P("Tu as dit « très grand, très sérieux », et tu as souri en le disant."), N("Le sourire reste, mais ses yeux quittent les vôtres, juste un instant."), B("Il chantait une chanson de marins. Il ne savait pas les paroles. Il a inventé la fin.", "thoughtful"), B("Ne lui répète jamais ça. Ou répète-le devant moi.", "teasing")], { trust: 4, affection: 1 }),
    Q("bel-valurn-a", "Lui demander ce qu’elle aurait chanté, elle, si elle avait perdu.", "audace", [B("Moi, perdre ?", "teasing"), P("Hypothèse."), B("Quelque chose d’indécent. Avec des gestes. Il aurait dû détourner les yeux pendant tout le deuxième couplet, et il l’aurait fait. C’était tout le plaisir.", "seductive")], { affection: 3, desire: 2 }),
    Q("bel-valurn-r", "Remarquer qu’elle raconte cette histoire chaque fois qu’il est dans la pièce.", "resonance", [N("Vous désignez du menton une silhouette au fond de la salle, qui fait semblant de ne pas écouter."), B("Pure coïncidence.", "cold"), P("Il t’entend."), B("C’est le but. Un homme qui chante faux mérite qu’on le lui rappelle pendant quelques siècles.", "smirk")], { trust: 2, affection: 2 }),
  ], { minStage: 1, mood: "teasing" }),

  S("bellirith-regard", "Tu regardais", "Bellirith se glisse à côté de vous sans bruit. « Tu regardais quelque chose. Depuis deux minutes. Tu avais l’air de quelqu’un qui a faim et qui a été très bien élevé. Je veux savoir quoi. »", [
    Q("bel-regard-a", "« Toi. »", "audace", [B("Mensonge. J’étais derrière toi.", "teasing"), P("Dans le miroir."), N("Elle se retourne. Il y a bien un miroir, au fond de la salle. Elle y croise son propre reflet, puis le vôtre, à côté."), B("…Tu as une réponse pour tout, et celle-ci était parfaite. Je la garde.", "seductive")], { affection: 3, desire: 3 }),
    Q("bel-regard-l", "Lui retourner la question : depuis quand vous observe-t-elle ?", "lucidite", [P("Deux minutes, tu dis. Donc tu me regardais depuis au moins deux minutes."), B("…", "angry"), B("Trois. Je voulais voir si tu finirais par aller le chercher, ce que tu regardais. Tu ne l’as pas fait. C’est la chose la plus frustrante que j’aie vue de la semaine.", "smirk")], { trust: 3, desire: 2 }),
    Q("bel-regard-s", "Lui laisser deviner, sans rien confirmer.", "sangFroid", [B("Le buffet. Non. La porte. Non. Quelqu’un… non, tu ne regardes pas les gens comme ça.", "thoughtful"), P("Continue."), B("Tu me fais jouer à ton jeu. Je n’aime pas qu’on me fasse jouer. J’adore qu’on me fasse jouer.", "teasing")], { trust: 2, desire: 3 }),
  ], { promptVariants: [
    V("Bellirith se glisse contre votre flanc, sans bruit, assez près pour que vous sentiez le miel brûlé avant de l’entendre. « Tu regardais quelque chose. Tu avais exactement la tête que tu fais avant de me demander de continuer. Je veux savoir quoi. »", [SLEPT]),
  ] }),

  S("bellirith-refus", "Pourquoi non ?", "Bellirith vous coince entre une colonne et un vase trop grand pour être honnête. Elle ne vous touche pas. « J’ai une question, et je veux une vraie réponse. L’autre fois. Pourquoi non ? Pas de politesse. Je veux comprendre comment tu fais. »", [
    Q("bel-refus-l", "Lui donner la vraie raison : vous aviez quelque chose à faire.", "lucidite", [P("Parce qu’on m’attendait. Et que j’avais envie, et que les deux étaient vrais en même temps."), B("Les deux étaient vrais.", "thoughtful"), P("Tu fais comme si l’envie décidait de tout. Elle décide de beaucoup. Pas de tout."), B("…Je vais réfléchir à ça. Et je vais te le faire payer, probablement le même soir.", "smirk")], { trust: 4, desire: 4 }),
    Q("bel-refus-a", "« Parce que tu aurais été trop contente. »", "audace", [B("Pardon ?", "angry"), P("Tu aurais gagné. Tu aurais eu ce petit sourire. Je voulais voir l’autre."), B("L’autre quoi ?", "cold"), P("Celui-ci."), N("Elle se rend compte qu’elle sourit. Elle se rend compte que ce sourire-là est nouveau."), B("Tu es une calamité.", "seductive")], { affection: 2, desire: 6 }),
    Q("bel-refus-s", "Ne pas se justifier.", "sangFroid", [P("Parce que non."), B("C’est tout ?", "cold"), P("C’est assez."), N("Elle vous regarde longtemps, sans se moquer, et finit par reculer d’un pas pour vous laisser passer."), B("C’est la réponse la plus irritante qu’on puisse me faire. Je l’ai déjà entendue dans ma tête trois fois.", "thoughtful")], { trust: 3, desire: 4 }),
  ], { requiresFlags: [RESISTED], mood: "thoughtful" }),

  S("bellirith-info", "Une information gratuite", "Bellirith s’assoit à côté de vous et regarde ailleurs. « Je vais te dire quelque chose d’utile, uniquement parce que j’adore ce que ça va provoquer. Saidin doit une bouteille à Lineva depuis un pari perdu, et il prétend qu’il l’a oublié. Lineva, elle, ne l’a pas oublié. »", [
    Q("bel-info-a", "Aller raconter tout ça à Lineva, devant Saidin.", "audace", [N("Vous traversez la salle. Vous dites deux phrases. Saidin devient très pâle ; Lineva, très souriante. Une bouteille change de mains avant la fin de la soirée."), B("Tu l’as fait. Tu l’as vraiment fait.", "teasing"), B("Je savais que tu ferais quelque chose. Je ne savais pas que ce serait aussi rapide. Je vais devoir te donner des informations plus dangereuses.", "seductive")], { affection: 4, desire: 1 }),
    Q("bel-info-l", "Lui demander ce qu’elle y gagne vraiment.", "lucidite", [B("Rien du tout.", "smirk"), P("Tu ne racontes jamais rien pour rien."), B("Saidin m’évite depuis une semaine parce qu’il croit que je lis dans ses pensées. Je ne lis pas ses pensées. Mais s’il croit que c’est toi qui le dénonces, il me reparlera.", "thoughtful"), P("Tu veux qu’il te reparle."), B("Je veux qu’il arrête de me fuir dans les couloirs. C’est vexant, d’être fuie par un homme qui se cogne aux portes.", "cold")], { trust: 4 }),
    Q("bel-info-s", "Garder l’information pour plus tard.", "sangFroid", [P("Merci. Je la garde."), B("Tu… la gardes ?", "cold"), P("Une information, c’est une pièce. On ne la dépense pas à la première foire."), B("Tu viens de me priver du spectacle pour lequel je t’avais tout raconté. Je n’aurais jamais dû te choisir comme instrument. Tu es un instrument qui pense.", "smirk")], { trust: 3, desire: 2 }),
  ], { minStage: 1 }),

  S("bellirith-ennui", "Elle s’ennuie", "Bellirith est allongée en travers d’une banquette, les pieds sur l’accoudoir, une main sur les yeux. « Je m’ennuie. Je m’ennuie à un point où je pourrais devenir vertueuse. Trouve-moi quelque chose d’indécent, d’absurde ou de spectaculaire. Tu as dix secondes. »", [
    Q("bel-ennui-a", "Lui proposer de voler le dessert du banquet officiel.", "audace", [N("Une demi-heure plus tard, vous êtes tous les deux cachés sous l’escalier des cuisines avec un gâteau de trois étages qui ne vous appartient pas, et deux cuillères."), B("C’est absurde, c’est spectaculaire, c’est légèrement indécent. Tu as coché les trois cases avec un gâteau.", "teasing"), B("On ne le finira jamais. On va essayer quand même.", "seductive")], { affection: 5 }),
    Q("bel-ennui-l", "Lui proposer de deviner, ensemble, qui s’ennuie autant qu’elle dans la salle.", "lucidite", [N("Vous vous installez sur la banquette et vous dressez la liste. Le garde de la porte. La comtesse qui compte les chandelles. Le serviteur qui essuie la même coupe depuis dix minutes."), B("Le serviteur, c’est un espion. Il essuie la même coupe parce qu’il écoute la table d’à côté.", "thoughtful"), P("Tu ne t’ennuies plus."), B("Non. Tu as transformé une salle mortelle en devinette. C’est presque de la sorcellerie.", "smirk")], { trust: 3, affection: 2 }),
    Q("bel-ennui-p", "« Ou bien on s’ennuie à deux, ailleurs. »", "audace", [B("Ailleurs.", "seductive"), N("Elle soulève la main de ses yeux et vous regarde par en dessous, très lentement."), B("Tu sais exactement ce que tu viens de dire, n’est-ce pas ? Très bien. Viens. Si tu changes d’avis en chemin, je te le reprocherai pendant un siècle, mais je te laisserai partir.", "smirk")], { affection: 2, desire: 1 }, { requiresFlags: [SLEPT], launchesIntimacy: BELLIRITH_FREE_PROPOSALS.ennui }),
    Q("bel-ennui-s", "Ne rien proposer et vous allonger sur la banquette d’en face.", "sangFroid", [N("Vous vous allongez à votre tour, les pieds sur l’accoudoir, une main sur les yeux. Elle vous regarde faire, outrée."), B("Tu m’imites.", "angry"), P("Je m’ennuie avec toi. C’est mieux que de s’ennuyer seule."), N("Il se passe un long moment. Puis elle rit, sous sa main, sans pouvoir s’arrêter."), B("C’est la chose la plus stupide que j’aie faite cette année. Ne bouge pas.", "teasing")], { affection: 3, trust: 2 }, { excludesFlags: [SLEPT] }),
  ], { minStage: 2, mood: "teasing" }),

  S("bellirith-defi", "Le défi de la salle", "Bellirith désigne le doyen des magistrats, raide comme une colonne au milieu du salon. « Défi. Le premier de nous deux qui le fait rire a gagné. Pas d’aura, pas de chatouilles, pas d’argent. Uniquement des mots. »", [
    Q("bel-defi-a", "Y aller franchement, avec la pire plaisanterie que vous connaissiez.", "audace", [N("Vous lui racontez une histoire de chèvre, de juge et de testament qui n’a ni queue ni tête. Le doyen ne rit pas. Mais Bellirith, à trois pas, s’étouffe dans sa coupe."), B("Il n’a pas ri. Moi, si. Je ne sais pas qui a gagné.", "teasing"), B("Je déclare que tu as gagné le mauvais concours. C’est encore mieux.", "seductive")], { affection: 4, desire: 1 }),
    Q("bel-defi-l", "Lui parler de son petit-fils, dont il porte le portrait.", "lucidite", [N("Vous avez remarqué le médaillon. Vous posez une question. Le doyen parle, se détend, et finit par rire franchement d’une bêtise de l’enfant."), B("Tu as triché avec un petit-fils.", "angry"), P("Uniquement des mots. Les siens."), B("…C’est exactement le genre d’argument que je ferais. Je suis dégoûtée. Je suis charmée. Ne me demande pas l’ordre.", "smirk")], { trust: 3, affection: 2 }),
    Q("bel-defi-s", "La laisser passer en premier et observer.", "sangFroid", [N("Elle s’approche du doyen, lui murmure trois mots. Il devient écarlate. Il ne rit pas, mais il tousse si fort qu’on lui apporte de l’eau."), P("Qu’est-ce que tu lui as dit ?"), B("Le nom de la chanteuse qu’il allait écouter en cachette il y a quarante ans. Il ne rit pas, mais je l’ai fait rajeunir.", "teasing"), P("Ça ne compte pas."), B("Tout compte quand c’est moi qui joue.", "seductive")], { trust: 2, desire: 3 }),
  ], { locations: ["algratal", "akuhn"], periods: ["soirée", "apres-midi"] }),

  S("bellirith-regles", "Le jeu aux règles changeantes", "Bellirith étale un jeu de cartes sur une table basse. « Ce jeu n’a pas de nom. Les règles changent chaque fois que l’un de nous réagit. Si tu souris, les cœurs valent double. Si tu fronces les sourcils, je pioche deux fois. Si tu rougis… je verrai. Distribue. »", [
    Q("bel-regles-s", "Jouer sans la moindre expression.", "sangFroid", [N("Vous jouez comme une statue. Elle change les règles quatre fois, invente des cartes, déclare que le valet de pique est désormais un roi en exil. Vous ne bronchez pas."), B("Tu ne réagis à rien. Les règles ne bougent plus. Je joue à un jeu normal.", "angry"), B("C’est la chose la plus inquiétante qui me soit arrivée depuis longtemps. Souris, que je puisse tricher.", "teasing")], { trust: 2, desire: 4 }),
    Q("bel-regles-a", "Inventer vos propres règles à votre tour.", "audace", [P("Nouvelle règle : quand tu mens, tu bois."), B("Il n’existe pas de telle règle.", "cold"), P("Tu viens de mentir."), N("Elle boit. Elle invente une règle. Vous en inventez deux. Au bout d’une heure, le jeu est devenu une constitution, une guerre et un traité de paix."), B("Personne ne comprendra jamais ce qu’on vient de jouer. C’est le meilleur jeu du monde.", "seductive")], { affection: 4, desire: 2 }),
    Q("bel-regles-l", "Repérer quelle règle la fait réagir, elle.", "lucidite", [N("Vous la regardez, elle, plutôt que les cartes. Chaque fois que vous hésitez avant de jouer, ses doigts se crispent sur le paquet."), P("Nouvelle règle : quand tu attends, tu perds un point."), B("…Tu as trouvé ça où ?", "thoughtful"), P("Dans tes mains."), B("Je vais devoir apprendre à jouer avec des gants. Ou avec toi. C’est pareil, au fond : quelque chose qui m’empêche de tricher.", "smirk")], { trust: 3, desire: 2 }),
  ], { minStage: 1, periods: ["soirée", "apres-midi"] }),

  S("bellirith-aura", "Un jeu choisi", "Bellirith pose deux doigts sur la table, entre vos mains. « Je vais te proposer quelque chose, et tu peux dire non. J’ai envie d’utiliser mon aura sur toi, et sur toi seul. Une minute. Juste pour voir combien de temps tu tiens. Tu décides, et si tu dis oui, tu pourras m’arrêter d’un mot. »", [
    Q("bel-aura-s", "Accepter, et tenir la minute entière.", "sangFroid", [N("Elle laisse venir l’aura. La pièce s’adoucit, se resserre, sent le miel brûlé et le jasmin. Chacun de ses gestes devient une suggestion. Vous comptez. Trente. Quarante. Cinquante."), N("À soixante, vous n’avez pas bougé. Elle retire l’aura d’un coup, comme on souffle une bougie, et elle a le souffle aussi court que vous."), B("Une minute. Tu as tenu une minute. Personne ne tient une minute.", "seductive"), B("Je ne sais pas si je suis vexée ou si j’ai envie de recommencer. Les deux. Clairement les deux.", "teasing")], { trust: 3, desire: 6 }),
    Q("bel-aura-a", "Accepter, et lui retourner le jeu en vous approchant pendant la minute.", "audace", [N("L’aura monte. Au lieu de lutter, vous avancez, lentement, jusqu’à ce que son visage soit à un souffle du vôtre. Puis vous vous arrêtez. Et vous attendez qu’elle avance."), N("Elle n’avance pas. Elle reste suspendue, prise dans son propre piège, jusqu’à ce que la minute s’achève."), B("Tu… as utilisé mon aura contre moi.", "angry"), P("J’ai seulement attendu."), B("C’est pire.", "seductive")], { affection: 2, desire: 5 }),
    Q("bel-aura-l", "Refuser, et lui demander à quoi ressemble la pièce quand elle ne l’utilise pas.", "lucidite", [P("Non. Mais dis-moi comment tu vois la salle quand tu n’y touches pas."), B("Ennuyeuse.", "cold"), P("Vraiment ?"), N("Elle regarde autour d’elle, longtemps. Un couple se dispute à voix basse, un garde bâille, une enfant vole un macaron."), B("…Non. Pas vraiment. Elle est seulement moins docile. Tu me fais regarder des choses que je n’ai pas besoin de regarder.", "thoughtful")], { trust: 4, desire: 2 }),
  ], { minStage: 2, mood: "seductive" }),

  S("bellirith-cerises", "Rien du tout", "Bellirith a volé un panier de cerises et s’est assise sur le rebord d’une fenêtre. Elle crache les noyaux dans la cour, avec une précision militaire. « Je ne fais rien. Je ne prépare rien. Je ne séduis personne. Assieds-toi si tu veux, mais ne t’attends à rien d’intéressant. »", [
    Q("bel-cerises-a", "Concourir au crachat de noyaux.", "audace", [N("Vous visez la fontaine. Vous la ratez. Elle la touche trois fois de suite, puis fait mine de ne pas avoir visé."), B("Pur hasard.", "smirk"), N("Le panier y passe. Personne ne dit rien d’important. Le soleil tourne sur la cour.")], { affection: 4 }),
    Q("bel-cerises-r", "Vous asseoir et ne rien dire.", "resonance", [N("Vous vous asseyez sur le rebord. Elle vous tend le panier sans un mot. Les cerises sont tièdes de soleil."), N("Elle ne fait rien de spectaculaire. Elle mange des cerises, elle regarde les pigeons se disputer, elle dit une fois : « Celui-là va gagner. » Il gagne.")], { affection: 3, trust: 2 }),
    Q("bel-cerises-l", "Lui demander d’où viennent les cerises.", "lucidite", [B("Du verger du chancelier.", "teasing"), P("Volées."), B("Empruntées sans intention de rendre. C’est une nuance juridique.", "smirk"), N("Vous en mangez quand même. Elles ont meilleur goût de ne pas être à vous.")], { affection: 2, trust: 2 }),
  ], { periods: ["apres-midi", "matin"], mood: "teasing" }),

  S("bellirith-matin", "Le matin d’après", "Bellirith est encore dans vos draps, ou vous dans les siens ; la question reste ouverte. Elle trace du doigt une ligne sur votre épaule, paresseusement. « Je connais un endroit, juste là, qui te fait retenir ton souffle. Je le sais depuis la dernière fois. Je voulais vérifier qu’il n’avait pas bougé. »", [
    Q("bel-matin-p", "« Vérifie encore. »", "audace", [B("Encore. Avant même le petit déjeuner.", "seductive"), N("Elle se redresse sur un coude, ravie, et sa main descend d’un cran."), B("Je te préviens : ce matin, c’est moi qui choisis le rythme. Tu pourras protester. Je t’écouterai peut-être.", "teasing")], { affection: 3, desire: 1 }, { launchesIntimacy: BELLIRITH_FREE_PROPOSALS.matin }),
    Q("bel-matin-l", "Lui rendre la pareille : vous aussi, vous connaissez un endroit.", "lucidite", [N("Vous effleurez du bout des doigts le creux sous son oreille. Elle se fige, un quart de seconde."), B("…Ça ne compte pas. Tu as eu de la chance.", "angry"), P("Deux fois, maintenant."), B("Je vais devoir trouver un endroit plus difficile. Je vais chercher longtemps.", "smirk")], { trust: 3, desire: 3 }),
    Q("bel-matin-s", "Vous lever : vous avez à faire.", "sangFroid", [P("Pas ce matin. On m’attend."), B("On t’attend. Toujours quelqu’un qui t’attend.", "cold"), N("Elle se laisse retomber dans les oreillers, les bras en croix, avec une indignation qui n’est qu’à moitié jouée."), B("Va. Mais je garde le côté chaud du lit, et je ne te rendrai pas ta chemise.", "teasing")], { trust: 2, desire: 3 }),
  ], { requiresFlags: [SLEPT], periods: ["matin"], mood: "seductive" }),

  S("bellirith-proposition", "La proposition du couloir", "Bellirith vous arrête dans un couloir désert, une main posée à plat sur le mur à côté de votre tête. « Je vais être directe, pour une fois. J’ai envie de toi. Maintenant, pas ce soir. Il y a une porte à dix pas qui ferme à clé. Tu peux dire oui, tu peux dire non, et tu peux dire non d’une façon qui me donnera envie de recommencer demain. »", [
    Q("bel-prop-p", "Dire oui.", "audace", [P("Oui."), N("Elle répète le mot, comme on goûte un vin, puis vous prend la main sans hâte et compte les dix pas à voix basse."), B("Je savais que tu dirais oui. Non, c’est faux. J’espérais.", "teasing")], { affection: 3, desire: 1 }, { launchesIntimacy: BELLIRITH_FREE_PROPOSALS.couloir }),
    Q("bel-prop-a", "Dire non, en la provoquant.", "audace", [P("Non. Mais tu peux me redemander demain, avec une meilleure porte."), B("Une meilleure porte.", "angry"), P("Celle-ci grince."), N("Elle retire sa main du mur. Elle recule. Elle vous regarde comme on regarde une citadelle qu’on vient de décider d’assiéger personnellement."), B("Demain. Une porte qui ne grince pas. Tu viens de signer quelque chose, et tu ne sais même pas quoi.", "seductive")], { affection: 1, desire: 7 }),
    Q("bel-prop-s", "Dire non, calmement.", "sangFroid", [P("Non. Pas maintenant."), B("Pas maintenant, ou pas avec moi ?", "cold"), P("Pas maintenant."), N("Elle hoche la tête, une seule fois, et vous laisse passer. Elle ne vous suit pas. Mais quand vous vous retournez au bout du couloir, elle est toujours là, à vous regarder partir avec une sorte d’intérêt professionnel."), B("Pas maintenant. Je note l’heure.", "thoughtful")], { trust: 3, desire: 5 }),
  ], { minStage: 3, mood: "seductive", promptVariants: [
    V("Bellirith vous arrête dans un couloir désert, une main posée à plat sur le mur à côté de votre tête, et ses lèvres frôlent votre oreille avant même qu’elle parle. « Tu connais le chemin de ma chambre. Moi, je connais une porte à dix pas qui ferme à clé, et je n’ai pas envie d’attendre d’y arriver. Oui, non, ou non d’une façon qui me donnera envie de recommencer demain ? »", [SLEPT]),
    V("Bellirith vous arrête dans un couloir désert. Elle ne vous touche pas, cette fois. Elle se contente de se placer en travers du passage. « J’ai essayé les bains, les miroirs, les toits et les heures impossibles. Tu as dit non à presque tout. Alors j’essaie la chose la plus bête : te demander. J’ai envie de toi. Il y a une porte à dix pas. Réponds-moi. »", [RESISTED], [SLEPT]),
  ] }),

  S("bellirith-favori", "Le titre de favori", "Bellirith vous présente à une ambassadrice comme on présente un pur-sang. « Mon favori. Oui, celui-là. Non, il n’y a pas de concours. Oui, j’en ai eu d’autres. Non, ils n’avaient pas cette façon de lever les yeux au ciel. »", [
    Q("bel-favori-a", "Jouer le jeu avec une révérence exagérée.", "audace", [N("Vous vous inclinez jusqu’au sol, la main sur le cœur. L’ambassadrice rit. Bellirith vous regarde avec la fierté d’une propriétaire d’écurie dont le cheval vient de faire une révérence."), B("Tu vois ? Dressé·e à la perfection.", "teasing"), P("C’est moi qui te laisse croire ça."), B("…Il ou elle répond, en plus. Excellent pedigree.", "seductive")], { affection: 4, desire: 1 }),
    Q("bel-favori-l", "Lui demander, plus tard, ce que « favori » veut dire pour elle.", "lucidite", [B("Ça veut dire que je te choisis en premier quand j’ai le choix.", "thoughtful"), P("Et quand tu n’as pas le choix ?"), B("Je n’ai pas encore trouvé de situation où je n’ai pas le choix.", "smirk"), N("Elle dit ça vite. Un peu trop vite. Puis elle vous vole votre coupe et la vide pour clore le sujet.")], { trust: 4 }),
    Q("bel-favori-s", "La corriger devant l’ambassadrice : c’est elle, votre favorite.", "sangFroid", [P("Elle se trompe dans les rôles. C’est elle, ma favorite. Je l’ai choisie parmi beaucoup de démones."), B("Parmi beaucoup de…", "angry"), N("L’ambassadrice éclate de rire. Bellirith, pour la première fois de la soirée, n’a aucune réplique."), B("Tu me paieras ça. Ce soir. Très cher.", "seductive")], { affection: 3, desire: 3 }),
  ], { requiresFlags: [FAVORITE], locations: ["algratal", "akuhn"] }),

  S("bellirith-conseil", "Le conseil des ennuyeux", "Bellirith a assisté à une séance du conseil et en ressort avec l’air d’avoir vu une pièce de théâtre très mal jouée. « Trois traîtres, deux lâches et un honnête homme qui va le payer. Veux-tu que je te dise lesquels, ou préfères-tu deviner ? »", [
    Q("bel-conseil-l", "Deviner, et lui expliquer pourquoi.", "lucidite", [P("L’honnête homme, c’est celui qui a voté contre son propre intérêt. Les traîtres, ce sont ceux qui ont voté trop vite."), B("Deux sur trois. Le troisième traître a voté lentement, exprès. C’est le plus intelligent des trois.", "thoughtful"), B("Tu ferais une conseillère redoutable. Ou un conseiller. Ou quelque chose de pire. J’aimerais voir.", "smirk")], { trust: 4 }),
    Q("bel-conseil-a", "Lui demander lequel elle aurait séduit pour faire basculer le vote.", "audace", [B("Aucun. Un traître, on lui offre une meilleure raison de trahir quelqu’un d’autre.", "cold"), P("C’est plus froid que ce que je pensais."), B("La politique, c’est froid. Le reste, je le garde chaud pour ceux qui le méritent.", "seductive")], { affection: 2, desire: 2 }),
    Q("bel-conseil-s", "Lui demander ce qu’elle compte faire de ce qu’elle a vu.", "sangFroid", [B("Rien.", "smirk"), P("Rien ?"), B("Pour l’instant. Une information qu’on utilise tout de suite ne vaut qu’un coup. Une information qu’on garde vaut toute une partie.", "thoughtful"), P("Tu viens de me la donner."), B("Je viens de te la prêter. Avec intérêts.", "teasing")], { trust: 3, desire: 1 }),
  ], { locations: ["algratal", "akuhn"], periods: ["apres-midi", "soirée"], mood: "thoughtful" }),
];
