import type { ChoiceData, DialogueLine, Effects, PeriodKey, StatKey } from "./game-data";

export type DateOutcome = "great" | "good" | "awkward";
export type PlayerSex = "femme" | "homme" | "intersexe";
export type IntimacyMode = "tendre" | "suggestif" | "explicite" | "ellipse";

export type DateScene = {
  id: string;
  character: string;
  title: string;
  type: string;
  description: string;
  location: string;
  spot: string;
  period: PeriodKey;
  unlockStage: number;
  minAffection: number;
  minTrust: number;
  /** Seuil vérifié uniquement après le rendez-vous pour proposer l’intimité. */
  minDesire?: number;
  mood: string;
  intro: DialogueLine[];
  choices: ChoiceData[];
  intimacySetting: {
    opening: string[];
    closing: string[];
    /** Le rendez-vous possède une continuité intime complète et ne reçoit pas le prologue générique du personnage. */
    replaceProfile?: boolean;
  };
};

const line = (speaker: string, text: string, mood?: string): DialogueLine => ({ speaker, text, mood });
const dateChoice = (
  id: string,
  text: string,
  stat: StatKey,
  response: DialogueLine[],
  outcome: DateOutcome,
  effects: Effects,
): ChoiceData => ({
  id,
  text,
  stat,
  response,
  dateOutcome: outcome,
  effects: { ...effects, stats: { ...(effects.stats || {}), [stat]: 1 } },
});

export const DATE_SCENES: DateScene[] = [
  {
    id: "date-hylee-forestier", character: "hylee", title: "La table près de l’ancienne cheminée", type: "Dîner à l’auberge", description: "Retourner à l’Auberge du Forestier, là où l’histoire d’Hylee avait recommencé bien avant votre arrivée.", location: "forestier", spot: "forestier-inn", period: "soirée", unlockStage: 3, minAffection: 26, minTrust: 24, mood: "soft",
    intro: [
      line("Narration", "L’Auberge du Forestier a changé de tenancier, mais pas de cheminée. Hylee choisit la table d’où l’on voit à la fois la porte, l’escalier et les premières lueurs de la route."),
      line("Hylee", "J’ai vécu ici en essayant de prendre le moins de place possible. Revenir pour un rendez-vous… c’est presque une provocation adressée à la fille que j’étais.", "soft"),
      line("Narration", "Elle commande deux parts de tarte avant de vous demander votre avis, s’en aperçoit et rougit jusqu’aux oreilles."),
      line("Hylee", "On peut recommencer correctement. Qu’est-ce que tu voudrais faire de cette soirée — écouter mes souvenirs, en fabriquer un nouveau, ou un peu des deux ?", "teasing"),
    ],
    choices: [
      dateChoice("dhf-l", "Lui demander de raconter un souvenir, puis lui confier quelque chose que vous n’avez encore dit à personne.", "lucidite", [line("Hylee", "Tu ne me demandes pas de rouvrir une blessure pour satisfaire ta curiosité. Tu poses quelque chose de toi à côté… Ça change tout."), line("Narration", "La tarte refroidit pendant que vos confidences occupent lentement la table entière.")], "great", { affection: 8, trust: 8, desire: 3 }),
      dateChoice("dhf-a", "Lever votre verre à la personne qu’elle est devenue et entraîner Hylee dans une chanson de taverne.", "audace", [line("Hylee", "Je refuse de chanter seule. Et si tu inventes encore un couplet sur les tartes héroïques, je te couvre de givre."), line("Narration", "Elle rit trop fort, oublie de surveiller la porte et garde sa main dans la vôtre sous la table.")], "great", { affection: 10, trust: 5, desire: 4 }),
      dateChoice("dhf-s", "Lui proposer de partir si revenir ici devient trop lourd.", "sangFroid", [line("Hylee", "Merci. Je ne veux pas partir, mais savoir que je peux le faire rend l’endroit beaucoup moins étroit."), line("Narration", "Vous restez près de la sortie. Le rendez-vous demeure doux, encore prudent, mais entièrement choisi.")], "good", { affection: 5, trust: 7, desire: 1 }),
    ],
    intimacySetting: {
      opening: ["Lorsque la salle se vide, Hylee loue l’ancienne chambre sous les combles. Le bois craque comme autrefois, mais elle monte l’escalier en tenant votre main au lieu de longer le mur.", "Dans la chambre, elle ouvre elle-même les rideaux et laisse la porte déverrouillée. La route, la cheminée et le passé restent derrière vous ; aucun d’eux ne décide de la suite."],
      closing: ["Bien plus tard, vous redescendez chercher la dernière part de tarte. Hylee la partage sur les marches, cheveux défaits et sourire tranquille, heureuse d’avoir remplacé un souvenir de survie par un souvenir de désir libre."],
    },
  },
  {
    id: "date-hylee-glade", character: "hylee", title: "Un pique-nique sous la neige d’été", type: "Pique-nique arcanique", description: "Laisser Hylee inventer une neige qui ne protège, n’attaque et n’emprisonne personne.", location: "miraldas", spot: "miraldas-hylee-glade", period: "apres-midi", unlockStage: 3, minAffection: 28, minTrust: 25, mood: "teasing",
    intro: [
      line("Narration", "Au centre de la clairière, Hylee a étendu une couverture trop petite et préparé une neige légère qui fond avant de toucher les plats."),
      line("Hylee", "C’est mon premier rendez-vous avec une météo sur invitation. Si tu préfères du soleil, je peux arrêter. Je ne le prendrai même pas personnellement… longtemps.", "teasing"),
      line("Narration", "Elle vous montre trois sculptures de glace : une chouette, une couronne de travers et une forme abstraite qu’elle refuse de nommer."),
      line("Hylee", "Choisis celle qu’on terminera ensemble. Je veux voir ce que ma magie devient quand elle n’a rien à prouver.", "soft"),
    ],
    choices: [
      dateChoice("dhg-r", "Accorder votre Résonance à la sculpture abstraite sans prendre le contrôle de sa magie.", "resonance", [line("Narration", "La forme devient deux silhouettes distinctes reliées par un arc de givre qui reste souple sous vos doigts."), line("Hylee", "Tu n’as pas essayé de finir mon idée. Tu lui as donné assez de place pour qu’elle te réponde.")], "great", { affection: 8, trust: 8, desire: 4, confluence: 2 }),
      dateChoice("dhg-a", "Transformer la couronne en chapeau ridicule et défier Hylee de le porter.", "audace", [line("Hylee", "Seulement si tu portes la chouette. Oui, sur ta tête. Nous allons être majestueux·ses."), line("Narration", "Le duel dégénère en bataille de neige parfaitement inoffensive et en baiser essoufflé sur la couverture.")], "great", { affection: 10, trust: 4, desire: 5 }),
      dateChoice("dhg-s", "Observer ses gestes, puis prolonger seulement la branche de givre qu’elle laisse ouverte.", "sangFroid", [line("Hylee", "Tu as vu l’endroit où je m’étais arrêtée… Je ne savais même pas que j’attendais quelqu’un pour le continuer."), line("Narration", "La sculpture avance lentement, attentive, et vos doigts finissent par se rejoindre dans la glace.")], "good", { affection: 5, trust: 7, desire: 2 }),
    ],
    intimacySetting: {
      opening: ["Hylee dresse autour de la couverture une coupole de givre translucide. Mir’Aldas se diffracte dans ses parois et la clairière devient un petit monde bleuté.", "La neige d’été se change en vapeur sur vos peaux. Le sort réagit à ses frissons : des fleurs de glace s’ouvrent au-dessus de vous chaque fois que son désir gagne en intensité."],
      closing: ["La coupole fond au rythme de vos souffles retrouvés. Lorsque la clairière réapparaît, Hylee reste étendue contre vous, amusée de voir sa magie raconter tout ce qu’elle avait essayé de taire."],
    },
  },
  {
    id: "date-remerii-observatory", character: "remerii", title: "Une constellation sans correction", type: "Observation des étoiles", description: "Passer une nuit à l’observatoire de Mir’Aldas sans transformer le ciel en exercice académique.", location: "miraldas", spot: "miraldas-observatory", period: "soirée", unlockStage: 3, minAffection: 25, minTrust: 28, mood: "calm",
    intro: [
      line("Narration", "Remerii a préparé deux fauteuils, trois cartes du ciel et une liste intitulée « sujets à ne surtout pas enseigner pendant le rendez-vous »."),
      line("Remerii", "J’ai ajouté la liste à la liste, ce qui constitue probablement un échec méthodologique. Vous êtes prié·e de ne pas sourire aussi visiblement.", "strict"),
      line("Narration", "Elle éteint l’instrument principal et ouvre simplement la coupole. Le ciel apparaît sans annotation ni mesure."),
      line("Remerii", "Choisissez une étoile. Nous lui inventerons une histoire fausse, inutile et impossible à publier.", "smirk"),
    ],
    choices: [
      dateChoice("dro-a", "Inventer une romance scandaleuse entre deux étoiles que tout sépare.", "audace", [line("Remerii", "Votre mécanique céleste est absurde. Rapprochez votre fauteuil : il nous faut manifestement davantage de données compromettantes."), line("Narration", "Son épaule rejoint la vôtre bien avant que l’histoire trouve une fin.")], "great", { affection: 9, trust: 5, desire: 5 }),
      dateChoice("dro-l", "Choisir l’étoile que Remerii évite de regarder et lui demander ce qu’elle évoque.", "lucidite", [line("Remerii", "Hylee était inconsciente la première fois que je l’ai observée toute une nuit. Je craignais que l’aube arrive sans elle."), line("Narration", "Vous ne cherchez pas à réparer le souvenir. Remerii finit par regarder l’étoile avec vous.")], "great", { affection: 7, trust: 10, desire: 3 }),
      dateChoice("dro-s", "Ranger les cartes et partager un silence sans objectif.", "sangFroid", [line("Remerii", "Vous avez compris que mon véritable exercice était de ne rien produire. C’est irritant et… reposant."), line("Narration", "Le silence devient intime, quoique Remerii conserve encore une petite distance entre vos mains.")], "good", { affection: 5, trust: 8, desire: 2 }),
    ],
    intimacySetting: {
      opening: ["Remerii verrouille les instruments fragiles mais laisse la coupole ouverte. Sous les étoiles, elle tente d’expliquer pourquoi cette précaution est parfaitement raisonnable, puis abandonne son exposé au milieu d’une phrase.", "Elle retire ses bijoux un à un sur la table d’observation. Le dernier reste de travers ; Remerii remarque l’erreur et choisit, avec un sourire troublé, de la laisser exister."],
      closing: ["À l’aube, aucune donnée n’a été relevée. Remerii inscrit pourtant la nuit dans le registre de l’observatoire sous le titre : « phénomène non reproductible, valeur considérable »."],
    },
  },
  {
    id: "date-remerii-music", character: "remerii", title: "La mesure laissée ouverte", type: "Duo musical", description: "Jouer avec Remerii dans le salon de musique, avec le droit de manquer une note et de continuer.", location: "algratal", spot: "algratal-music-room", period: "soirée", unlockStage: 3, minAffection: 28, minTrust: 26, mood: "smirk",
    intro: [line("Narration", "Remerii a choisi une pièce facile et couvert la partition de corrections. À votre arrivée, elle retourne pourtant les pages face contre table."), line("Remerii", "Nous jouerons de mémoire. La mienne est excellente ; la décision reste donc objectivement mauvaise."), line("Narration", "Elle vous cède la première note, puis attend sans battre la mesure à votre place."), line("Remerii", "Commencez quand vous le souhaitez. Je vous rejoindrai au lieu de vous ramener vers moi.", "calm")],
    choices: [
      dateChoice("drm-r", "Improviser une phrase simple et laisser sa magie harmoniser sans diriger.", "resonance", [line("Remerii", "Vous m’obligez à écouter plutôt qu’à prévoir. Recommencez cette mesure — non pour la corriger, pour la prolonger."), line("Narration", "Le duo gagne en assurance jusqu’à devenir une conversation où vos mains se frôlent entre deux accords.")], "great", { affection: 8, trust: 8, desire: 4, confluence: 2 }),
      dateChoice("drm-a", "Introduire volontairement une note insolente et soutenir son regard.", "audace", [line("Remerii", "Provocation harmonique caractérisée. La réponse pédagogique appropriée consiste apparemment à vous embrasser avant le prochain accord."), line("Narration", "Elle applique sa nouvelle méthode avec un sérieux qui ne trompe personne.")], "great", { affection: 9, trust: 5, desire: 6 }),
      dateChoice("drm-s", "Admettre que vous êtes nerveux·se et demander de ralentir.", "sangFroid", [line("Remerii", "Merci de ne pas déguiser votre inconfort en incompétence. Nous reprendrons à votre rythme."), line("Narration", "Le morceau reste prudent, mais sa main demeure sur la vôtre après la dernière note.")], "good", { affection: 5, trust: 8, desire: 2 }),
    ],
    intimacySetting: { opening: ["La dernière note continue de vibrer lorsque Remerii ferme le clavier. Elle reste assise une seconde, les doigts posés sur le bois, puis rapproche son banc du vôtre d’un mouvement qui manque volontairement de mesure.", "Le salon demeure éclairé par les runes de la partition. À chaque frôlement, une note répond et transforme peu à peu votre proximité en musique imprévisible."], closing: ["Quand vous rejouez enfin, vos rythmes ont changé. Remerii manque une note, rit contre votre bouche et refuse catégoriquement de la corriger."] },
  },
  {
    id: "date-iriana-market", character: "iriana", title: "Une pièce qui n’appartient pas à l’Empire", type: "Promenade incognito", description: "Arpenter le Grand Marché sans escorte visible et laisser Iriana choisir quelque chose qui ne soit utile à personne.", location: "algratal", spot: "algratal-market", period: "matin", unlockStage: 3, minAffection: 26, minTrust: 26, mood: "smirk",
    intro: [line("Narration", "Iriana porte une cape simple et une bourse contenant exactement trois pièces. Deux gardes très peu discrets prétendent examiner des étoffes à distance."), line("Iriana", "J’ai une mission : dépenser une pièce pour quelque chose qui ne serve ni l’Empire, ni la diplomatie, ni ma réputation."), line("Narration", "Elle s’arrête devant des rubans, des pâtisseries puis un petit oiseau mécanique, incapable de traiter le désir comme un critère suffisant."), line("Iriana", "Aidez-moi, mais ne décidez pas à ma place. C’est apparemment la difficulté centrale de cette sortie.")],
    choices: [
      dateChoice("dim-l", "Lui demander devant quel objet elle a ralenti sans s’en apercevoir.", "lucidite", [line("Iriana", "L’oiseau. Il ne porte aucun blason et chante faux… Je le veux donc pour des raisons irréfutables."), line("Narration", "Elle l’achète, le fait chanter trois fois et rit comme si aucun chroniqueur ne pouvait l’entendre.")], "great", { affection: 8, trust: 8, desire: 3 }),
      dateChoice("dim-a", "Acheter deux pâtisseries et décréter une dégustation clandestine.", "audace", [line("Iriana", "Vous détournez une mission impériale au profit d’un crime pâtissier. Je confisque la seconde tarte comme preuve."), line("Narration", "Vous partagez le butin dans une ruelle, épaule contre épaule, sous le regard désespéré des gardes.")], "great", { affection: 10, trust: 4, desire: 4 }),
      dateChoice("dim-s", "Lui laisser tout le temps nécessaire, même si elle ne choisit rien.", "sangFroid", [line("Iriana", "Ne rien acheter serait encore une décision acceptable… Merci de ne pas transformer ma liberté en nouvel exercice à réussir."), line("Narration", "Elle finit par choisir un ruban modeste. Le moment reste tendre, mais encore très contrôlé.")], "good", { affection: 5, trust: 8, desire: 1 }),
    ],
    intimacySetting: { opening: ["Iriana loue sous un faux nom une chambre au-dessus d’une maison de thé. Pour la première fois de la matinée, aucun garde ne se trouve dans la pièce voisine.", "Elle pose le petit achat du marché sur la table, retire sa cape et vous fait répéter son prénom une seule fois. Le titre reste avec le vêtement lorsqu’elle vient vous embrasser."], closing: ["Vous quittez la chambre séparément pour préserver l’incognito, puis vous retrouvez au coin de la rue. Iriana glisse sa main dans la vôtre en plein marché : ce geste-là, finalement, elle refuse de le cacher."] },
  },
  {
    id: "date-iriana-ballroom", character: "iriana", title: "Une danse sans spectateurs", type: "Bal privé", description: "Ouvrir la salle de bal après le départ de la cour et laisser la musique n’appartenir qu’à vous.", location: "algratal", spot: "algratal-ballroom", period: "soirée", unlockStage: 4, minAffection: 34, minTrust: 30, mood: "calm",
    intro: [line("Narration", "La salle de bal est vide. Iriana a renvoyé les musiciens et déposé son diadème sur un siège, mais une valse mécanique joue encore dans les murs."), line("Iriana", "Je connais chaque pas qu’une princesse doit offrir à la cour. Aucun ne dit comment Iriana souhaite danser quand personne ne regarde."), line("Narration", "Elle vous tend la main, paume vers le haut, sans donner d’ordre ni dissimuler son appréhension."), line("Iriana", "Menez, suivez ou refusez la danse. Je veux que notre premier mouvement soit une décision partagée.")],
    choices: [
      dateChoice("dib-s", "Commencer à distance et lui demander à chaque changement si elle veut se rapprocher.", "sangFroid", [line("Iriana", "Vous rendez la lenteur aussi claire qu’un protocole, mais infiniment plus douce."), line("Narration", "La distance disparaît par étapes choisies jusqu’à ce que son front repose contre le vôtre.")], "great", { affection: 9, trust: 9, desire: 5 }),
      dateChoice("dib-a", "L’inviter à mener une danse qu’aucun maître de cérémonie n’approuverait.", "audace", [line("Iriana", "Alors préparez-vous à un incident diplomatique majeur."), line("Narration", "Elle rit, vous fait tourner trop vite et termine la danse contre un pilier, lèvres à quelques centimètres des vôtres.")], "great", { affection: 10, trust: 5, desire: 7 }),
      dateChoice("dib-l", "Lui demander quel geste elle a toujours voulu accomplir sans en avoir le droit.", "lucidite", [line("Iriana", "Poser ma tête sur l’épaule de quelqu’un avant la fin de la musique."), line("Narration", "Vous lui offrez cette place. Le rendez-vous devient profondément intime, même si vous lui laissez décider de la suite.")], "great", { affection: 8, trust: 10, desire: 4 }),
    ],
    intimacySetting: { opening: ["Lorsque la valse s’achève, Iriana ne remet pas la couronne. Elle vous conduit derrière les lourds rideaux où les alcôves accueillaient autrefois les négociations secrètes.", "Cette fois, aucun traité ne se conclut. Le velours étouffe vos voix tandis qu’Iriana formule ses envies sans pluriel de majesté et écoute les vôtres avec la même attention."], closing: ["Vous regagnez le parquet avant l’aube. Iriana remet sa couronne, puis vous accorde une dernière danse lente dont aucun invité ne connaîtra jamais les pas."] },
  },
  {
    id: "date-valurn-forestier", character: "valurn", title: "Le pari qui ne rapporte rien", type: "Jeux et confidences", description: "Partager une table, quelques cartes et la possibilité rare que Valurn reste sans enjeu caché.", location: "forestier", spot: "forestier-inn", period: "soirée", unlockStage: 3, minAffection: 25, minTrust: 25, mood: "charming",
    intro: [line("Narration", "Valurn a réservé la table la plus proche de la porte et placé entre vous un jeu dont il a retiré toutes les cartes marquées."), line("Valurn", "Règle unique : la personne qui gagne pose une question. La personne qui perd peut refuser d’y répondre. Oui, ce jeu est économiquement désastreux."), line("Narration", "Il perd la première manche avec un naturel beaucoup trop parfait, puis admet avoir hésité à tricher."), line("Valurn", "À vous. Une question, une plaisanterie ou la destruction complète de mes règles ?")],
    choices: [
      dateChoice("dvf-l", "Lui demander pourquoi il a choisi cette auberge plutôt qu’un palais.", "lucidite", [line("Valurn", "Parce qu’ici, partir n’impressionne personne. Rester non plus. Je voulais découvrir lequel des deux je choisirais près de vous."), line("Narration", "Il ne regarde plus la porte pendant les trois manches suivantes.")], "great", { affection: 7, trust: 10, desire: 3 }),
      dateChoice("dvf-a", "Mélanger toutes les cartes et transformer le jeu en vérités absurdes.", "audace", [line("Valurn", "Je dois donc avouer un crime culinaire, un désir inavouable et mon opinion sur les chapeaux impériaux ? Vous êtes impitoyable."), line("Narration", "Les aveux deviennent plus tendres à mesure que le vin baisse dans les verres.")], "great", { affection: 10, trust: 5, desire: 5 }),
      dateChoice("dvf-s", "Refuser le jeu et proposer de parler sans gagner le droit de le faire.", "sangFroid", [line("Valurn", "Aucune mise, aucune victoire… vous retirez mes défenses avec une brutalité très polie."), line("Narration", "La conversation devient honnête, quoique Valurn conserve encore une plaisanterie prête à couvrir chaque silence.")], "good", { affection: 5, trust: 8, desire: 2 }),
    ],
    intimacySetting: { opening: ["Valurn dépose la clé de la chambre au milieu du dernier pli, face contre table, comme une mise qu’il refuse cette fois de reprendre. Vous montez sans annoncer lequel de vous a gagné.", "À l’intérieur, ses armes et ses sceaux rejoignent le rebord de la fenêtre. Débarrassé de ses tours, Valurn paraît moins assuré et infiniment plus proche."], closing: ["Au matin, Valurn prétend avoir perdu le pari qui consistait à partir avant l’aube. La clé demeure dans votre main et son sourire, sans pacte ni clause, admet qu’il espérait cette défaite."] },
  },
  {
    id: "date-valurn-river", character: "valurn", title: "Un feu sans pacte", type: "Halte sous les étoiles", description: "Allumer un feu ordinaire au bord du Fleuve bleu et passer une nuit sans contrat ni destination urgente.", location: "river-halt", spot: "river-halt", period: "soirée", unlockStage: 3, minAffection: 28, minTrust: 28, mood: "away",
    intro: [line("Narration", "Valurn s’obstine à allumer le feu avec du silex. Trois flammes de pacte parfaitement efficaces dansent au bout de ses doigts, volontairement ignorées."), line("Valurn", "Je souhaite prouver que je peux produire de la chaleur sans engager mon âme, mon sang ou les droits d’exploitation d’un futur enfant."), line("Narration", "Le feu prend enfin. Il vous tend sa couverture sans demander ce que ce geste lui rapportera."), line("Valurn", "Racontez-moi quelque chose de votre présent. Votre passé est absent et mon avenir trop bruyant ; il nous reste cette rive.")],
    choices: [
      dateChoice("dvr-s", "Partager la couverture et décrire simplement ce que vous ressentez ici.", "sangFroid", [line("Valurn", "Une réponse qui ne réclame ni origine ni destination. Je comprends pourquoi elle semble plus chaude que mon feu."), line("Narration", "Il s’adosse contre vous, d’abord prêt à bouger, puis réellement installé.")], "great", { affection: 8, trust: 9, desire: 4 }),
      dateChoice("dvr-r", "Écouter les résidus de pactes dans ses mains sans chercher à les retirer.", "resonance", [line("Valurn", "Vous sentez les chaînes et vous ne tirez pas dessus. Merci de ne pas appeler délivrance une douleur supplémentaire."), line("Narration", "Il vous laisse prendre sa main, paume contre paume, jusqu’à ce que les flammes sombres s’apaisent.")], "great", { affection: 7, trust: 10, desire: 3, confluence: 2 }),
      dateChoice("dvr-a", "Jeter ses cartes de voyage en l’air et choisir l’étape de demain au hasard.", "audace", [line("Valurn", "Une navigation irresponsable, imprévisible et peut-être merveilleuse. Vous savez véritablement parler à mon cœur."), line("Narration", "Il rit et vous embrasse avant que la carte retombe, mais l’incertitude le rend encore un peu nerveux.")], "good", { affection: 8, trust: 4, desire: 5 }),
    ],
    intimacySetting: { opening: ["Valurn étend une seconde couverture derrière le paravent improvisé du camp. Le fleuve masque vos voix, le feu ordinaire réchauffe vos vêtements abandonnés sans aucune intervention du Chaos.", "Il s’allonge près de vous, contemple les étoiles une dernière seconde et admet d’un sourire nerveux qu’aucune d’elles ne lui a préparé la suite."], closing: ["Vous vous rhabillez devant les braises. Valurn rallume le feu d’un simple souffle, fier de cette magie minuscule, puis choisit avec vous la route du lendemain sans tirer aucune carte."] },
  },
  {
    id: "date-naiah-sanctuary", character: "naiah", title: "Le goûter sans illusion", type: "Pique-nique dans la brume", description: "Partager avec Naïah un goûter où ses illusions deviennent un jeu visible plutôt qu’un masque.", location: "forbidden", spot: "forbidden-sanctuary", period: "apres-midi", unlockStage: 3, minAffection: 27, minTrust: 28, mood: "thinking",
    intro: [line("Narration", "Naïah a préparé des fruits parfaitement ordinaires et placé autour de la clairière de petits fanions indiquant chaque illusion active."), line("Naïah", "J’ai étiqueté la brume, les lucioles et le coussin qui prétend être plus moelleux qu’il ne l’est. La dignité de cette forêt ne s’en remettra pas."), line("Narration", "Elle vous remet un ruban violet dont l’extrémité serpente entre les fanions. Chaque nœud commande un petit morceau du décor."), line("Naïah", "Tu peux changer mon ciel, déplacer les lucioles ou rendre au coussin son honnête inconfort. Fais seulement quelque chose d’intéressant.")],
    choices: [
      dateChoice("dns-s", "Défaire un seul nœud et lui demander quel souvenir se cachait dans cette illusion.", "sangFroid", [line("Naïah", "Une cuisine, un orage, et Allenna qui prétendait ne pas avoir volé les pâtisseries. Tu as choisi la partie dangereusement tendre."), line("Narration", "La clairière prend un instant l’odeur de la pluie sur la pierre tandis qu’elle vous raconte le reste.")], "great", { affection: 8, trust: 10, desire: 4 }),
      dateChoice("dns-r", "Proposer une illusion commune que chacun peut modifier ou arrêter.", "resonance", [line("Naïah", "Une création qui ne m’obéit pas entièrement… terrifiant. Faisons apparaître un ciel, mais choisis la première étoile."), line("Narration", "Votre paysage partagé change au rythme de vos questions, sans jamais couvrir la vraie clairière.")], "great", { affection: 9, trust: 8, desire: 4, confluence: 2 }),
      dateChoice("dns-a", "Croquer le fruit le plus suspect et déclarer la confiance officiellement délicieuse.", "audace", [line("Naïah", "C’était une prune. Tu viens de risquer ta vie contre une prune."), line("Narration", "Elle rit, vous vole le noyau du bout des doigts et remplace sa victoire par un baiser spontané.")], "good", { affection: 9, trust: 5, desire: 5 }),
    ],
    intimacySetting: { opening: ["Naïah tire elle-même sur le ruban. La brume décorative, les lucioles et le coussin mensonger disparaissent ; il ne reste que la clairière réelle et ses joues beaucoup plus rouges qu’elle ne l’aurait souhaité.", "Son pouvoir frémit autour de vous sans intervenir. Chaque changement de couleur trahit une émotion qu’elle aurait autrefois cachée derrière trois plaisanteries et un tour de magie."], closing: ["Quand les illusions reviennent, elles ne cachent rien : elles dessinent seulement des lucioles au-dessus de vos mains jointes. L’une d’elles se pose sur votre épaule et Naïah prétend aussitôt que ce n’était absolument pas prévu."] },
  },
  {
    id: "date-naiah-akuhn", character: "naiah", title: "Le belvédère qui ne la retient pas", type: "Veille à la frontière", description: "Contempler les lueurs d’Akuhn’Nabad depuis les ruines sans demander à Naïah de franchir son bannissement.", location: "forbidden", spot: "forbidden-ruins", period: "soirée", unlockStage: 4, minAffection: 34, minTrust: 32, mood: "sad",
    intro: [line("Narration", "Les cristaux verts d’Akuhn’Nabad brillent au loin, entre les troncs. Naïah reste sur le vieux parapet des ruines, du côté de la forêt où personne ne peut lui contester le droit d’être là."), line("Naïah", "Cette ville sait fabriquer des cages magnifiques. Même de loin, elle essaie encore de faire croire que la vue lui appartient."), line("Narration", "Elle vous montre deux coupes, l’une impériale et l’autre ébréchée, sauvée avant son exil."), line("Naïah", "Je veux regarder sans rentrer. Aide-moi à décider ce que je peux reprendre sans leur rendre le reste.")],
    choices: [
      dateChoice("dna-l", "Lui demander quels souvenirs lui appartiennent avant de parler des symboles.", "lucidite", [line("Naïah", "Une chanson, l’odeur de la pierre après la pluie et le rire d’une servante qui trichait aux dés. Je garde ceux-là."), line("Narration", "Elle boit dans la tasse ébréchée et raconte la ville depuis les personnes qu’elle a aimées.")], "great", { affection: 8, trust: 10, desire: 3 }),
      dateChoice("dna-a", "Poser la coupe impériale à l’envers et en faire un siège pour une luciole.", "audace", [line("Naïah", "Voilà enfin une fonction politique raisonnable. La luciole accepte la couronne et abdique immédiatement."), line("Narration", "Son rire traverse les ruines, libre, puis se perd bien avant les murailles de la cité.")], "great", { affection: 10, trust: 6, desire: 5 }),
      dateChoice("dna-s", "Rester près du sentier et lui rappeler qu’elle peut repartir à tout instant.", "sangFroid", [line("Naïah", "Tu ne me demandes pas d’aimer cet endroit pour prouver que je l’ai dépassé. Merci."), line("Narration", "Elle se détend contre le vieux parapet. Les lumières de la cité gardent leur poids, mais plus aucune porte ne se referme autour d’elle.")], "good", { affection: 6, trust: 9, desire: 2 }),
    ],
    intimacySetting: { opening: ["Naïah dresse dans les ruines un abri de brume ouvert sur trois côtés. Elle en marque elle-même les limites, visibles et fragiles, puis vérifie que le sentier vers la forêt reste libre.", "Sous la lueur lointaine des cristaux, elle ôte les bijoux de sa famille et ne garde que la tasse ébréchée près de vos vêtements. Chaque caresse devient une décision qui lui appartient plutôt qu’un héritage à reprendre."], closing: ["La brume se dissipe avant l’aube. Naïah quitte le belvédère avec vous sans se retourner vers la cité, emportant la vieille tasse et le souvenir d’une nuit qu’Akuhn’Nabad n’a pas commandée."] },
  },
  {
    id: "date-lineva-ramparts", character: "lineva", title: "Forthaven à elle", type: "Quais, ragoût et vieux fanal", description: "Suivre Lineva dans les endroits du port qu’elle choisit lorsqu’aucune ronde ne fixe le trajet.", location: "forthaven", spot: "forthaven-harbor", period: "soirée", unlockStage: 5, minAffection: 34, minTrust: 36, minDesire: 22, mood: "smirk",
    intro: [
      line("Narration", "Lineva vous attend au marché du quai dans un pantalon de toile, des bottes usées et un lourd manteau sans insigne. Elle tient deux bols de ragoût de poisson dont la vapeur lui brouille le visage."),
      line("Lineva", "Règle de la soirée : si quelqu’un m’appelle Commandante, nous ne l’entendons pas. S’il crie au feu, nous vérifions quand même. J’aime cette ville, pas au point de la laisser brûler pour une règle."),
      line("Narration", "Elle vous donne le bol le plus rempli et entraîne la marche entre les étals. Trois vendeuses la saluent par son prénom ; une quatrième lui réclame l’argent perdu aux dés la semaine précédente."),
      line("Lineva", "Dette contestée. Elle a lancé les dés avant la fin de la chanson."),
      line("La vendeuse", "Tu chantais faux pour distraire la table."),
      line("Lineva", "Technique navale reconnue."),
      line("Narration", "Plus loin, Lineva vous montre les marques de marée gravées dans les pilotis, un atelier où elle a appris à calfater une coque et la proue d’un bateau qu’elle a réparée à quinze ans."),
      line("Lineva", "Il a coulé deux mois plus tard. Pas ma partie. Je précise parce que Draven raconte très mal cette histoire."),
      line("Narration", "Votre promenade se termine devant le vieux fanal du bassin ouest. Sa roue d’orientation est bloquée ; Lineva pose déjà son bol vide et retrousse ses manches."),
      line("Lineva", "Cette saleté grince depuis mon enfance et j’ai envie de gagner. Vous mettez les mains avec moi ou vous fournissez des commentaires inutiles ?"),
    ],
    choices: [
      dateChoice("dlr-l", "Démonter la roue avec elle et repérer la dent faussée plutôt que forcer le mécanisme.", "lucidite", [line("Narration", "Vous retirez la plaque, alignez les pièces sur le manteau de Lineva et découvrez une dent de bronze tordue par le sel."), line("Lineva", "Voilà la coupable. Trente ans à faire croire que toute la tour était mal conçue."), line("{player}", "Vous semblez déçue. Vous vouliez frapper quelque chose."), line("Lineva", "Je peux encore frapper la dent."), line("Narration", "Elle la redresse sur une enclume de quai, vous la fait tenir pendant qu’elle ajuste l’axe, puis tourne la roue d’un seul mouvement fluide."), line("Lineva", "Vous venez de réparer le bruit de mon enfance. J’ignore si je dois vous embrasser ou demander des dommages pour altération du patrimoine."), line("{player}", "Commencez par la solution la moins administrative."), line("Narration", "Elle choisit votre bouche, les doigts encore noirs de graisse.")], "great", { affection: 8, trust: 10, desire: 6 }),
      dateChoice("dlr-a", "Parier une bouteille que vous pouvez décoincer la roue avant la fin du prochain refrain de marins.", "audace", [line("Lineva", "Marché conclu. Si vous perdez, vous chantez le couplet du tonneau devant tout le quai."), line("Narration", "Le refrain commence au cabaret voisin. Vous poussez ensemble ; la roue résiste, puis cède brutalement et vous précipite contre Lineva."), line("Lineva", "Encore deux vers. Techniquement, vous avez gagné."), line("{player}", "Vous avez amorti ma victoire."), line("Lineva", "Je facture ce service une bouteille et un baiser."), line("Narration", "Vous payez d’abord la seconde dette. Les marins ajoutent aussitôt un couplet obscène que Lineva accompagne en frappant le rythme du talon."), line("Lineva", "Ne prenez pas cet air. La culture de Forthaven est un désastre collectif, pas ma responsabilité personnelle."), line("Narration", "Elle ne s’écarte pas lorsque le refrain recommence.")], "great", { affection: 11, trust: 5, desire: 8 }),
      dateChoice("dlr-s", "Laisser la roue tranquille et rejoindre la partie de dés que la vendeuse vient d’ouvrir sur une caisse.", "sangFroid", [line("{player}", "Le fanal grinçait avant nous. La table de dés, elle, réclame une revanche."), line("Lineva", "Enfin une décision stratégique digne de ce nom."), line("Narration", "Vous jouez sur une caisse renversée avec deux dockeuses, un pêcheur et la vendeuse. Lineva triche une fois, se fait prendre immédiatement et accuse le poisson du ragoût d’avoir compromis son jugement."), line("La vendeuse", "Même excuse que ta mère."), line("Narration", "Lineva secoue la tête, sourit et relance sans quitter la partie."), line("Lineva", "Elle cachait mieux les dés. Moi, je mise mieux."), line("Narration", "Elle pose la clé du fanal, gagne votre dernière pièce, puis vous la rend contre un baiser derrière sa main comme deux adolescent·es trop visibles."), line("Lineva", "Le fanal attendra demain. La revanche aussi, si vous avez le courage de revenir avec de vraies mises.")], "great", { affection: 9, trust: 8, desire: 6 }),
    ],
    intimacySetting: {
      replaceProfile: true,
      opening: ["Après le dernier jeu, Lineva vous conduit dans la chambre du vieux fanal, au-dessus du bassin ouest. Son bol, la clé gagnée aux dés et le manteau taché de graisse restent sur l’établi du rez-de-chaussée ; elle monte en chemise retroussée, pantalon de toile et bottes.", "Elle ferme la trappe, pose son couteau et les clés du port sur une étagère, puis vient reprendre le baiser interrompu sous les rires du quai. La roue réparée tourne derrière elle avec un petit grondement régulier."],
      closing: ["Le vieux fanal poursuit sa rotation au-dessus du bassin. Lineva reste étendue contre vous sur les couvertures de veille, trace du doigt une marque de graisse sur votre hanche et décide que la réparation pourra attendre avant d’être officiellement déclarée."],
    },
  },
  {
    id: "date-lineva-quarters", character: "lineva", title: "Une soirée qui ne sert à rien", type: "Repas, cartes et danse de quai", description: "Partager dans les quartiers de Lineva un repas du port, une partie de cartes et la musique qu’elle garde pour elle.", location: "forthaven", spot: "forthaven-quarters", period: "soirée", unlockStage: 5, minAffection: 36, minTrust: 34, minDesire: 22, mood: "smirk",
    intro: [
      line("Narration", "Lineva ouvre la porte de ses quartiers avec une bouteille sous un bras et un paquet encore chaud de la taverne du quai sous l’autre."),
      line("Lineva", "J’ai acheté le repas à des professionnels. Cela protège la soirée et probablement le bâtiment."),
      line("Narration", "Sur la table, deux portions de poisson épicé, du pain noir et une bouteille de vin tiennent compagnie à un paquet de cartes fermé."),
      line("{player}", "Quel était le plan ?"),
      line("Lineva", "Manger. Boire. Vous battre aux cartes. Danser si le vin détruit suffisamment notre jugement."),
      line("Narration", "Elle ouvre le paquet, vous laisse le morceau de pain le moins brûlé par le four de la taverne et remplit les deux verres."),
      line("Lineva", "Vous pouvez encore fuir avant la première donne. Après, votre dignité reste en garantie."),
      line("Narration", "Un vieux phonographe de marine attend près de la fenêtre avec trois cylindres : une chanson de rame, une danse de quai et un enregistrement où Draven, plus jeune, essaie manifestement de chanter."),
      line("Lineva", "Le troisième est une arme. On ne l’utilise qu’en cas de défaite majeure."),
      line("Narration", "Elle pose les cartes, vous regarde et ajoute avec beaucoup moins d’assurance :"),
      line("Lineva", "Le programme peut rater. Vous restez quand même assez longtemps pour savoir où ?"),
    ],
    choices: [
      dateChoice("dlq-a", "Choisir un cylindre au hasard et porter un toast à la première conséquence.", "audace", [line("Narration", "Vous fermez les yeux et prenez le cylindre que Lineva gardait derrière les deux autres."), line("Lineva", "Vous venez de sortir l’arme. Je décline toute responsabilité diplomatique."), line("Narration", "La voix plus jeune de Draven attaque une chanson de rame et perd la mesure dès le second vers."), line("{player}", "À son courage."), line("Lineva", "À notre silence absolu sur ce qui va suivre."), line("Narration", "Vous trinquez. Lineva tente de couvrir le refrain, chante volontairement plus faux encore, puis s’interrompt contre votre rire."), line("Lineva", "Vous trouvez cela séduisant ? Votre jugement est déjà détruit."), line("Narration", "Elle vérifie ce diagnostic en vous embrassant, un doigt encore posé sur le phonographe.")], "great", { affection: 10, trust: 6, desire: 8 }),
      dateChoice("dlq-l", "Ouvrir les cartes et miser des anecdotes ordinaires plutôt que de l’argent.", "lucidite", [line("Lineva", "Dangereux. J’ai davantage d’argent que d’anecdotes convenables."), line("Narration", "La première manche vous coûte l’histoire d’une chute ridicule. La seconde oblige Lineva à raconter le jour où sa mère a fait peindre des yeux sur la proue de Draven pendant son sommeil."), line("{player}", "Il les a gardés ?"), line("Lineva", "Trois ans. Il prétendait que c’était pour la visibilité dans le brouillard."), line("Narration", "Lineva perd la troisième manche et doit révéler son cylindre préféré. Elle choisit la danse de quai, pas l’enregistrement compromettant."), line("Lineva", "Je conserve une réserve stratégique pour notre prochaine partie."), line("{player}", "Vous supposez déjà une revanche."), line("Lineva", "Je viens de vous laisser gagner chez moi. Évidemment qu’il y aura une revanche."), line("Narration", "Son pied vient emprisonner le vôtre sous la table, sans rapport avec les cartes.")], "great", { affection: 8, trust: 10, desire: 6 }),
      dateChoice("dlq-s", "Lancer la danse de quai et apprendre ses pas avant que le repas refroidisse davantage.", "sangFroid", [line("Narration", "Le cylindre craque, puis un violon rapide remplit la pièce. Lineva repousse la table d’une hanche et vous montre le premier pas."), line("Lineva", "Le talon ici, la main là. Si vous comptez à voix haute, je vous mets dehors."), line("{player}", "Vous comptez dans votre tête."), line("Lineva", "C’est mon logement. J’y ai des privilèges."), line("Narration", "La danse est faite pour un quai bondé : peu d’espace, beaucoup d’épaules, un tour brusque qui vous ramène poitrine contre poitrine. Vous ratez le second et Lineva vous rattrape par la taille."), line("Lineva", "La tradition exige maintenant que je me moque."), line("{player}", "La tradition peut attendre."), line("Narration", "Vous reprenez le pas plus lentement. Au troisième tour, elle cesse de compter et laisse la musique décider du temps du baiser."), line("Lineva", "Le repas refroidit. La soirée, moins.")], "great", { affection: 9, trust: 8, desire: 7 }),
    ],
    intimacySetting: {
      replaceProfile: true,
      opening: ["Le cylindre achève sa dernière mesure pendant que Lineva verrouille la porte. La table reste repoussée, les cartes ouvertes et les assiettes oubliées ; ses bottes sont déjà près du phonographe, son ceinturon sur le dossier d’une chaise et les manches de sa chemise roulées au-dessus des coudes.", "Elle revient pieds nus, prend votre main et la pose contre sa taille sans discours. Le premier baiser est encore joueur ; le suivant dure jusqu’à faire tomber l’as resté dans sa manche."],
      closing: ["La chanson de rame tourne à très faible volume tandis que Lineva demeure près de vous dans les draps tombés au pied de la table. Elle récupère une carte collée à votre épaule, constate qu’il s’agit d’un as et l’accuse d’avoir triché à votre place."],
    },
  },
  {
    id: "date-saidin-observatory", character: "saidin", title: "L’étoile qu’il n’avait pas regardée", type: "Nuit imprévisible", description: "Choisir avec Saidin une direction du ciel qu’il s’interdit d’avoir consultée.", location: "miraldas", spot: "miraldas-observatory", period: "soirée", unlockStage: 3, minAffection: 26, minTrust: 28, mood: "mysterious",
    intro: [line("Narration", "Saidin a couvert la moitié des lentilles de l’observatoire et tourné les horloges contre le mur."), line("Saidin", "J’ai vu cent versions de cette nuit. J’ai ensuite choisi l’angle mort commun à toutes : ce petit morceau de ciel derrière la coupole."), line("Narration", "Il vous laisse actionner le mécanisme. Une étoile rouge apparaît, inconnue non parce qu’elle est nouvelle, mais parce qu’il avait décidé de ne pas la prévoir."), line("Saidin", "Que faisons-nous d’une découverte dont je ne connais pas encore la conséquence ?")],
    choices: [
      dateChoice("dso-a", "Lui donner immédiatement un nom absurde et porter un toast à l’erreur.", "audace", [line("Saidin", "« L’Étoile de la Chaussette Perdue » survivra donc dans au moins un catalogue. Le futur est enfin puni."), line("Narration", "Son rire devient un baiser spontané qu’aucune vision ne lui avait permis de répéter.")], "great", { affection: 10, trust: 5, desire: 5 }),
      dateChoice("dso-s", "Observer sans nommer, mesurer ni décider ce que l’étoile signifie.", "sangFroid", [line("Saidin", "Nous la laissons exister avant de l’utiliser. J’aimerais que davantage de personnes m’aient offert cette patience."), line("Narration", "Il pose sa tête contre la vôtre et regarde longtemps sans chercher le lendemain.")], "great", { affection: 7, trust: 10, desire: 3 }),
      dateChoice("dso-l", "Lui demander ce qu’il espère ressentir plutôt que ce qui va arriver.", "lucidite", [line("Saidin", "De la surprise. Puis l’envie de la partager avec vous. La première est déjà là."), line("Narration", "La réponse l’ancre, quoique son regard tente encore parfois de suivre les futurs possibles.")], "good", { affection: 7, trust: 8, desire: 3 }),
    ],
    intimacySetting: { opening: ["Saidin ferme entièrement l’observatoire aux visions mais laisse le toit ouvert sur l’étoile inconnue. Privées d’avenir, ses mains hésitent une seconde avant que la curiosité ne l’emporte.", "Les coussins de la coupole deviennent votre lit. Le ciel poursuit sa course sans ralentir, accélérer ni répéter le moindre mouvement pour vous faciliter la nuit."], closing: ["À l’aube, l’étoile disparaît derrière le dôme. Saidin refuse de calculer quand elle reviendra : il préfère vous demander, au présent, si vous accepterez une autre nuit."] },
  },
  {
    id: "date-saidin-workshop", character: "saidin", title: "La machine aux futurs inutiles", type: "Expérience tzekarii", description: "Construire à Tzekarun une machine qui prédit seulement des détails sans importance.", location: "tzekarun", spot: "tzekarun-workshop", period: "apres-midi", unlockStage: 3, minAffection: 28, minTrust: 28, mood: "thinking",
    intro: [line("Narration", "L’atelier vous a confié des engrenages déclassés. Saidin propose une machine capable de prédire le prochain éternuement, la chute d’une vis ou le goût d’une poire."), line("Saidin", "Une prophétie qui ne peut sauver ni condamner personne. J’ignore si c’est une plaisanterie ou un idéal politique."), line("Narration", "Le mécanisme grésille et imprime : « Dans neuf minutes, deux personnes oublieront pourquoi elles voulaient terminer cette machine. »"), line("Saidin", "Nous pourrions vérifier la prédiction. Ou la saboter ensemble.")],
    choices: [
      dateChoice("dsw-r", "Dérégler la Résonance pour que le résultat demeure réellement imprévisible.", "resonance", [line("Saidin", "Vous venez de fabriquer un angle mort volontaire. Il est petit, bruyant et merveilleusement nôtre."), line("Narration", "La machine imprime une ligne vide. Saidin vous embrasse comme s’il venait de recevoir la plus belle réponse.")], "great", { affection: 9, trust: 9, desire: 4, confluence: 2 }),
      dateChoice("dsw-a", "Abandonner l’atelier exactement neuf minutes plus tard pour aller boire.", "audace", [line("Saidin", "Nous accomplissons donc la prophétie par pure insolence. J’approuve cette causalité."), line("Narration", "Vous partez en riant, couverts de graisse, et transformez la sortie en rendez-vous improvisé.")], "great", { affection: 10, trust: 5, desire: 4 }),
      dateChoice("dsw-l", "Chercher pourquoi il désire parfois des futurs sans responsabilité.", "lucidite", [line("Saidin", "Parce qu’un éternuement ne me demandera jamais pourquoi je ne l’ai pas empêché. Merci de comprendre sans glorifier ma fatigue."), line("Narration", "La confidence rapproche vos mains, mais Saidin conserve le besoin de terminer proprement l’expérience.")], "good", { affection: 6, trust: 9, desire: 2 }),
    ],
    intimacySetting: { opening: ["Vous fermez l’atelier et laissez la machine imprimer ses prophéties inutiles derrière un paravent. Saidin refuse de lire les bandelettes qui tombent au sol.", "Sur la grande table débarrassée de ses outils, chaque geste arrive sans répétition possible. Le métal encore tiède sous vos corps contraste avec la lenteur attentive par laquelle vous vous découvrez."], closing: ["La machine a prédit douze vis perdues, deux éternuements et « une excellente décision impossible à reproduire ». Saidin déchire la dernière bandelette sans la lire jusqu’au bout."] },
  },
  {
    id: "date-bellirith-music", character: "bellirith", title: "Une danse sans enchantement", type: "Musique et danse", description: "Danser dans le salon d’Akuhn’Nabad tandis que Bellirith tente de séduire sans le secours de son aura.", location: "akuhn", spot: "akuhn-music-room", period: "soirée", unlockStage: 3, minAffection: 28, minTrust: 30, mood: "seductive",
    intro: [line("Narration", "Bellirith a tracé autour de ses bijoux un cercle qui neutralise leur magie. La musique commence, mais elle reste à trois pas de vous."), line("Bellirith", "Je sais faire naître le désir avant même de tendre la main. Ce soir, je voudrais découvrir ce que vaut mon invitation lorsqu’elle peut réellement échouer."), line("Narration", "Elle s’incline sans utiliser le moindre charme et attend que vous choisissiez la distance du premier pas."), line("Bellirith", "Près, loin, ou pas de danse. Ta décision ne deviendra pas un affront à réparer.")],
    choices: [
      dateChoice("dbm-s", "Commencer dos à dos et laisser la danse réduire elle-même la distance.", "sangFroid", [line("Bellirith", "Une chorégraphie où je ne peux pas te captiver du regard. Tu sais choisir les difficultés qui m’obsèdent."), line("Narration", "Vos épaules, vos mains puis vos souffles se retrouvent au fil des mesures, jusqu’au baiser qui achève la danse.")], "great", { affection: 8, trust: 10, desire: 6 }),
      dateChoice("dbm-a", "L’attirer immédiatement contre vous après lui avoir demandé si elle le souhaite aussi.", "audace", [line("Bellirith", "Oui. Voilà une audace qui ne vole rien."), line("Narration", "Elle répond avec toute sa maîtrise, mais s’arrête plusieurs fois pour vous laisser relancer vous-même la danse.")], "great", { affection: 9, trust: 7, desire: 8 }),
      dateChoice("dbm-l", "Refuser de danser avant qu’elle dise ce qu’elle désire pour elle-même.", "lucidite", [line("Bellirith", "Être menée pendant une mesure. Puis te laisser choisir la suivante."), line("Narration", "L’équilibre la touche profondément, même si le désir met davantage de temps à s’exprimer.")], "good", { affection: 7, trust: 9, desire: 4 }),
    ],
    intimacySetting: { opening: ["Bellirith vous conduit derrière les panneaux acoustiques du salon, dans une alcôve où la musique devient une vibration douce sous la peau. Tous ses bijoux restent dans le cercle neutralisant.", "Son aura demeure muette. Pourtant, lorsque vous vous rapprochez encore, Bellirith perd un instant la perfection de sa posture et laisse voir combien cette attraction entièrement ordinaire la bouleverse."], closing: ["La musique s’est arrêtée depuis longtemps lorsque vous revenez au salon. Bellirith remet un seul bijou, purement décoratif, puis vous demande une dernière danse dont aucun enchantement ne corrigera les maladresses."] },
  },
  {
    id: "date-bellirith-market", character: "bellirith", title: "La femme la moins dangereuse du marché", type: "Sortie ordinaire", description: "Laisser Bellirith tenter une journée sans tenue spectaculaire, privilège ni séduction surnaturelle.", location: "algratal", spot: "algratal-market", period: "matin", unlockStage: 3, minAffection: 27, minTrust: 28, mood: "smirk",
    intro: [line("Narration", "Bellirith porte une chemise simple et a noué ses cheveux sans bijou. Elle semble plus vulnérable ainsi qu’au milieu d’une armée."), line("Bellirith", "Objectif du rendez-vous : acheter du pain, négocier honnêtement et ne provoquer aucun scandale sensuel. J’ai prévu une marge d’échec raisonnable."), line("Narration", "Le boulanger lui rend une pièce de trop. Bellirith la fixe comme si l’univers venait de lui proposer une tentation humiliante."), line("Bellirith", "Si je rends cette pièce sans transformer le geste en performance morale, ai-je réussi à être ordinaire ?")],
    choices: [
      dateChoice("dbk-l", "Lui demander ce qu’elle veut faire plutôt que ce qu’une personne ordinaire ferait.", "lucidite", [line("Bellirith", "La rendre. Puis acheter deux brioches et les manger avec toi sans séduire le boulanger. Voilà mon désir révolutionnaire."), line("Narration", "Elle accomplit ce programme avec un sérieux délicieux et rit lorsqu’aucun témoin ne l’applaudit.")], "great", { affection: 8, trust: 9, desire: 3 }),
      dateChoice("dbk-a", "Rendre la pièce et exiger une récompense sous forme de la pire plaisanterie du boulanger.", "audace", [line("Bellirith", "Tu as transformé l’honnêteté en catastrophe sociale. Cette méthode me convient beaucoup mieux."), line("Narration", "La plaisanterie est atroce ; son rire, totalement naturel, attire votre baiser.")], "great", { affection: 10, trust: 5, desire: 5 }),
      dateChoice("dbk-s", "La laisser gérer seule et rester disponible sans observer comme un juge.", "sangFroid", [line("Bellirith", "Tu ne surveilles même pas mes progrès. Je découvre que la confiance peut manquer cruellement de mise en scène."), line("Narration", "Elle apprécie la liberté, quoique le rendez-vous conserve une distance prudente.")], "good", { affection: 6, trust: 9, desire: 2 }),
    ],
    intimacySetting: { opening: ["Bellirith choisit une petite chambre d’auberge dépourvue de miroirs enchantés. Elle ferme les rideaux ordinaires et pose sur la table les derniers bijoux qui auraient pu transformer la pièce en scène.", "Le pain encore chaud reste entre vos vêtements tandis qu’elle découvre, avec une nervosité qu’aucun costume ne masque, que votre désir a suivi la femme du marché jusqu’ici."], closing: ["Vous regagnez le marché avec les brioches oubliées. Bellirith garde sa chemise simple et votre main visible, heureuse que la foule ne voie qu’un couple sortant trop tard d’une chambre ordinaire."] },
  },
  {
    id: "date-amanea-piano", character: "amanea", title: "Une chanson sans héritage", type: "Duo au piano", description: "Composer avec Amanea une musique qui n’appartient ni aux Farae, ni à l’Empire, ni aux Obscurcis.", location: "akuhn", spot: "akuhn-music-room", period: "soirée", unlockStage: 3, minAffection: 28, minTrust: 32, mood: "thinking",
    intro: [
      line("Narration", "Amanea a suspendu les audiences et confié la cour à Allenna pour la soirée. Dans le salon nocturne, le piano noir attend sous les flammes vertes."),
      line("Amanea", "Toutes les mélodies de ma famille ressemblent à des procès. Ce soir, nous allons en écrire une qui n’accuse, ne supplie et ne gouverne personne."),
      line("Narration", "Elle vous réserve la moitié du clavier. Ses doigts assurés ralentissent lorsqu’une mélodie rappelle Tia, puis retrouvent leur autorité sur un thème qui n’appartient qu’à elle."),
      line("Amanea", "Choisis la première note. Je refuse d’être la seule personne à décider de la direction — même dans quelque chose d’aussi dangereusement inutile."),
    ],
    choices: [
      dateChoice("dap-a", "Commencer par une dissonance et la défier d’en faire quelque chose de beau.", "audace", [line("Amanea", "Tu entres donc dans ma musique comme dans ma salle du trône : sans révérence correcte et avec une confiance excessive."), line("Narration", "Elle répond par un accord sombre, vous répliquez, et le duel se transforme en rire lorsqu’aucun de vous ne parvient à conclure."), line("Amanea", "Ne termine pas. J’aime que cette musique exige une prochaine soirée.")], "great", { affection: 10, trust: 6, desire: 5 }),
      dateChoice("dap-l", "Bâtir le thème autour des silences qu’elle choisit de laisser.", "lucidite", [line("Narration", "Vous ne remplissez pas les vides. Amanea comprend que vos notes ne cherchent pas à corriger ce qu’elle ne dit pas."), line("Amanea", "Tu laisses mes silences compter sans les traiter comme des secrets à arracher. Voilà une intimité que je ne connaissais pas."), line("Narration", "Sa main quitte le clavier pour venir, après une question du regard, se poser sur la vôtre.")], "great", { affection: 8, trust: 11, desire: 3 }),
      dateChoice("dap-r", "Accorder le piano à vos deux signatures sans les fusionner.", "resonance", [line("Narration", "Deux lignes lumineuses parcourent le bois : verte et sombre pour Amanea, claire et instable pour vous. Elles se répondent sans se confondre."), line("Amanea", "Proches sans devenir une seule chose. Conserve cet accord. Il vaut davantage que tous les pactes que ma famille a voulu transmettre."), line("Narration", "Le baiser qui suit est lent et précisément choisi.")], "great", { affection: 8, trust: 10, desire: 5, confluence: 3 }),
    ],
    intimacySetting: { opening: ["Amanea referme le piano et entraîne le dernier accord avec elle jusque dans l’alcôve du salon. D’un geste, elle abaisse les flammes vertes et renvoie au silence les enchantements de la cour.", "Sa franchise demeure celle d’une reine, mais sa bouche contre la vôtre ne donne aucun ordre ; elle exprime seulement l’impatience longtemps contenue derrière le morceau."], closing: ["Lorsque vous revenez au clavier, vos vêtements ne sont pas encore tous retrouvés. Vous ajoutez quatre mesures à votre morceau et laissez de nouveau la dernière en suspens."] },
  },
  {
    id: "date-amanea-terrace", character: "amanea", title: "La cité qu’elle prépare", type: "Souper sur la terrasse", description: "Regarder Akuhn’Nabad vivre pendant qu’Amanea apprend à laisser Allenna gouverner une soirée sans elle.", location: "akuhn", spot: "akuhn-terrace", period: "soirée", unlockStage: 4, minAffection: 34, minTrust: 36, mood: "smile",
    intro: [
      line("Narration", "Une table modeste a été dressée sur la terrasse. Amanea a choisi elle-même deux assiettes puis a interdit aux serviteurs de transformer le repas en audience."),
      line("Amanea", "En bas, Allenna organise la relève. Elle n’a pas demandé mon avis. Je découvre que cette absence de consultation peut ressembler à de la confiance plutôt qu’à une insulte."),
      line("Narration", "La cité bruisse sous le règne de la Reine Noire : marchés, gardes, enfants courant sous les lanternes vertes. Amanea observe le tout avec la fierté d’une souveraine qui prépare déjà la suivante."),
      line("Amanea", "Pose-moi une question qui ne concerne ni l’Empire, ni le pacte, ni mon royaume. J’aimerais vérifier si une reine possède encore des réponses ordinaires."),
    ],
    choices: [
      dateChoice("dat-l", "Lui demander quel endroit elle voudrait découvrir sans escorte ni objectif.", "lucidite", [line("Amanea", "La mer. Je l’ai vue depuis des cartes, des guerres et les souvenirs d’Allenna. Jamais depuis une plage où personne ne savait mon nom."), line("{player}", "Alors notre prochain voyage n’aura pas de mission."), line("Amanea", "Cette idée me terrifie suffisamment pour devenir séduisante.")], "great", { affection: 9, trust: 10, desire: 4 }),
      dateChoice("dat-a", "Lui demander quelle mauvaise habitude parfaitement banale elle souhaite adopter.", "audace", [line("Amanea", "Dormir tard. Manger trop de miel. Interrompre les conversations sérieuses pour t’embrasser."), line("Narration", "Elle met immédiatement la dernière proposition à l’épreuve et vous attire contre le parapet."), line("Amanea", "Je progresse vite lorsque le programme est bien conçu.")], "great", { affection: 11, trust: 6, desire: 7 }),
      dateChoice("dat-s", "Partager le repas en silence et laisser la ville fournir la conversation.", "sangFroid", [line("Narration", "Amanea mange lentement sans consulter les rapports qui s’accumulent derrière la porte."), line("Amanea", "Tu ne transformes pas mon silence en malaise ni mon repos en faiblesse. Je pourrais apprendre à aimer les soirées simples."), line("Narration", "Elle garde votre main sous la table pendant que les lanternes s’allument une à une.")], "great", { affection: 8, trust: 12, desire: 3 }),
    ],
    intimacySetting: { opening: ["Amanea vous conduit dans une chambre donnant sur la terrasse, loin de ses appartements officiels. Elle dépose sa couronne, laisse sa magie retomber avec les lourds pans de sa cape et soupire en comprenant que personne ne viendra la réclamer.", "La Reine Noire demeure près de la porte ; Amanea, elle, s’avance jusqu’à vous avec la franchise rare d’une femme qui n’a rien à gouverner pendant quelques heures."], closing: ["À l’aube, Akuhn’Nabad a été gouvernée une nuit entière par Allenna. Amanea reste près de vous, nue sous une cape simple, fière de son héritière et nullement pressée de transformer votre proximité en serment."] },
  },
  {
    id: "date-allenna-field", character: "allenna", title: "L’exercice qui n’évalue personne", type: "Jeu de rubans", description: "Disputer avec Allenna une série de manches rapides où la seule récompense est une revanche.", location: "akuhn", spot: "akuhn-war-room", period: "apres-midi", unlockStage: 5, minAffection: 34, minTrust: 34, minDesire: 22, mood: "smirk",
    intro: [
      line("Narration", "Allenna a vidé le terrain et remplacé les armes par des rubans noués aux poignets. Le premier qui saisit celui de l’autre gagne la manche."),
      line("Allenna", "Premier ruban pris : une victoire. Première plainte sur les règles : deux défaites."),
      line("Narration", "Elle adopte sa garde habituelle, le plaisir compétitif déjà visible dans son regard."),
      line("Allenna", "Vous pouvez commencer. Je préfère gagner sur une attaque honnête."),
    ],
    choices: [
      dateChoice("daf-s", "Attendre sa première feinte et retourner son propre mouvement.", "sangFroid", [line("Narration", "Vous cédez un pas, bloquez son poignet et prenez le ruban au moment où elle se croit déjà victorieuse."), line("Allenna", "Vous avez attendu uniquement pour devenir agaçant·e au meilleur moment."), line("Narration", "Elle conserve votre main dans la sienne après la fin de la manche."), line("Allenna", "Revanche. Immédiate.")], "great", { affection: 8, trust: 9, desire: 5 }),
      dateChoice("daf-a", "Feindre une chute, puis voler son ruban lorsqu’elle vient vous aider.", "audace", [line("Narration", "Allenna comprend la feinte une demi-seconde trop tard. Elle vous immobilise au sol, son visage à quelques centimètres du vôtre."), line("Allenna", "Déloyal."), line("{player}", "J’ai gagné."), line("Allenna", "Vous avez surtout choisi une position intéressante pour la revanche.")], "great", { affection: 10, trust: 6, desire: 7 }),
      dateChoice("daf-l", "Sacrifier votre ruban pour l’attirer dans une prise qu’elle n’a pas prévue.", "lucidite", [line("Narration", "Allenna saisit votre ruban et comprend trop tard que vous avez déjà refermé les doigts sur le sien."), line("Allenna", "Égalité."), line("{player}", "Double victoire."), line("Narration", "Elle conteste pendant trois manches et rit à la quatrième, sans jamais cesser d’essayer de gagner.")], "great", { affection: 8, trust: 8, desire: 5 }),
    ],
    intimacySetting: { opening: ["Allenna ferme la salle de guerre et déroule sur le sol les tapis d’exercice. Aucun soldat ne viendra interrompre la dernière manche.", "Les rubans froissés restent à vos poignets pendant que la rivalité change de terrain et que sa première assurance laisse apparaître une rougeur qu’elle refuse de commenter."], closing: ["Lorsque la salle rouvre, deux rubans froissés restent noués ensemble près de la carte. Allenna les range dans sa poche plutôt qu’avec le matériel d’entraînement."], replaceProfile: true },
  },
  {
    id: "date-allenna-terrace", character: "allenna", title: "Le chaudron à trois couleurs", type: "Cuisine de campagne", description: "Préparer avec Allenna un plat visuellement alarmant, parfaitement nourrissant et beaucoup trop bon pour son apparence.", location: "akuhn", spot: "akuhn-terrace", period: "soirée", unlockStage: 5, minAffection: 35, minTrust: 33, minDesire: 22, mood: "smirk",
    intro: [
      line("Narration", "Allenna pose sur le brasero un chaudron où trois couches refusent de partager la même couleur : vert sombre, orange vif et violet presque noir."),
      line("Allenna", "Chaque portion tient une marche entière, se conserve deux jours et n’a encore tué personne."),
      line("{player}", "Le dernier argument était nécessaire."),
      line("Allenna", "Oui. Je voulais une deuxième expertise."),
    ],
    choices: [
      dateChoice("datr-s", "Goûter sans demander la composition avant d’avoir rendu votre verdict.", "sangFroid", [line("Narration", "La première bouchée est épicée, fumée et franchement excellente."), line("{player}", "C’est bon."), line("Allenna", "Votre surprise manque de courtoisie."), line("Narration", "Elle vous ressert pourtant avec un sourire satisfait et rapproche son tabouret du vôtre.")], "great", { affection: 9, trust: 10, desire: 4 }),
      dateChoice("datr-a", "L’accuser d’avoir conçu le plat comme une arme psychologique.", "audace", [line("Allenna", "Une arme ne doit pas donner envie d’une seconde portion."), line("{player}", "Alors pourquoi cette couleur ?"), line("Allenna", "Pour éliminer les personnes qui jugent avant de goûter."), line("Narration", "Vous volez une bouchée dans sa cuillère. Allenna vous laisse faire, puis exige le même droit sur la vôtre.")], "great", { affection: 11, trust: 6, desire: 7 }),
      dateChoice("datr-l", "Identifier les trois ingrédients improbables et proposer une quatrième couleur.", "lucidite", [line("Narration", "Vous reconnaissez la racine noire, la courge épicée et l’herbe obscurcie. Allenna admet votre troisième réponse d’un signe de tête."), line("{player}", "On pourrait ajouter les baies rouges."), line("Allenna", "Le résultat deviendrait presque présentable. C’est suspect."), line("Narration", "Elle ajoute tout de même les baies et vous fait goûter directement au bout de la cuillère.")], "great", { affection: 8, trust: 9, desire: 5 }),
    ],
    intimacySetting: { opening: ["Allenna repousse le chaudron refroidi et vous conduit dans la petite réserve attenante à la terrasse, encore parfumée d’épices et chauffée par le brasero.", "Elle relève le menton lorsque vos vêtements rejoignent les tabliers, soutient votre regard une seconde de trop, rougit puis regarde ailleurs avec une irritation muette contre sa propre gêne."], closing: ["Plus tard, vous terminez la dernière portion assis·es sur le même tabouret. Allenna note seulement qu’une quatrième couleur exigerait une nouvelle soirée d’essai."], replaceProfile: true },
  },
  {
    id: "date-tia-ballroom", character: "tia", title: "Une danse sans ambassade", type: "Bal privé", description: "Occuper avec Tia une salle conçue pour représenter l’Empire, sans représenter personne.", location: "algratal", spot: "algratal-ballroom", period: "soirée", unlockStage: 3, minAffection: 27, minTrust: 32, mood: "troubled",
    intro: [
      line("Narration", "La Salle des Élus est vide. Tia a conservé une musicienne derrière un paravent et congédié tous les autres témoins."),
      line("Tia", "Chaque danse de cette salle possède normalement une fonction : alliance, rang, succession. Celle-ci n’en aura aucune que nous n’aurons pas choisie."),
      line("Narration", "Elle vous tend la main mais ne réduit pas la distance. La possibilité du refus demeure au centre du parquet."),
      line("Tia", "Je ne serai pas offensée par un non. Je serai peut-être contrariée. Vous avez le droit de me contrarier."),
    ],
    choices: [
      dateChoice("dtb-s", "Commencer à distance et laisser chaque mesure demander la suivante.", "sangFroid", [line("Narration", "Vos doigts se touchent à la première mesure, vos épaules à la quatrième. Tia attend toujours votre mouvement avant de refermer la distance."), line("Tia", "Une chorégraphie dont aucune étape ne devient acquise. Je comprends pourquoi elle reste vivante.")], "great", { affection: 8, trust: 11, desire: 4 }),
      dateChoice("dtb-a", "Transformer la valse en pas populaire appris sur la route.", "audace", [line("Tia", "Ce mouvement n’a aucune dignité."), line("Narration", "Elle l’exécute pourtant avec une précision parfaite, puis accepte de le rater volontairement lorsque vous l’entraînez."), line("Tia", "Toute mention de ceci sera traitée comme une déclaration de guerre privée.")], "great", { affection: 11, trust: 6, desire: 6 }),
      dateChoice("dtb-l", "Lui demander quel pas elle préfère avant de choisir le vôtre.", "lucidite", [line("Tia", "Celui où le partenaire recule sans être abandonné."), line("Narration", "Vous construisez la danse autour de cette distance, qui devient confiance plutôt que retrait.")], "great", { affection: 8, trust: 10, desire: 4 }),
    ],
    intimacySetting: { opening: ["Tia ouvre une porte latérale vers les appartements de réception et la referme elle-même, sans garde à l’intérieur. La musique demeure un battement étouffé derrière le mur.", "Elle conserve son autorité, mais aucun geste ne devient ordre : chaque rapprochement est formulé, attendu et choisi. Le contrôle qu’elle refuse d’imposer se transforme peu à peu en intensité."], closing: ["Vous regagnez le parquet avant le retour des gardes. Tia reprend sa couronne, puis laisse sa main dans la vôtre une mesure de plus que le protocole ne l’autoriserait."] },
  },
  {
    id: "date-tia-archives", character: "tia", title: "Le dossier sans conclusion", type: "Soirée aux archives", description: "Lire avec Tia des fragments de vies qui résistent à la version officielle et laisser un dossier inachevé.", location: "algratal", spot: "algratal-palace-council", period: "soirée", unlockStage: 4, minAffection: 34, minTrust: 37, mood: "thinking",
    intro: [
      line("Narration", "Tia a préparé deux dossiers : l’un porte le sceau impérial, l’autre seulement son prénom. Elle ouvre le second."),
      line("Tia", "Il contient des lettres familiales, des contradictions et des événements que les archives publiques rendent inutilement propres."),
      line("Narration", "Au lieu de vous demander une analyse, elle verse deux coupes et s’assied du même côté de la table."),
      line("Tia", "Nous n’achèverons pas ce dossier ce soir. Je souhaite vérifier si je peux laisser une histoire ouverte sans la traiter comme une menace."),
    ],
    choices: [
      dateChoice("dta-l", "Comparer deux versions incompatibles sans choisir immédiatement la vraie.", "lucidite", [line("Tia", "Une souveraine déteste les récits qui refusent le verdict."), line("{player}", "Et Tia ?"), line("Narration", "Elle ferme le document avant la réponse."), line("Tia", "Tia souhaite que vous restiez après la dernière page.")], "great", { affection: 9, trust: 11, desire: 4 }),
      dateChoice("dta-s", "Lire en silence et refermer le dossier lorsqu’elle en manifeste le besoin.", "sangFroid", [line("Narration", "Tia pose deux doigts sur la marge. Vous refermez sans lui demander pourquoi."), line("Tia", "Vous avez compris une limite avant qu’elle devienne défense. Approchez.")], "great", { affection: 8, trust: 12, desire: 4 }),
      dateChoice("dta-a", "Écrire sur une feuille séparée une conclusion volontairement provisoire.", "audace", [line("{player}", "Conclusion : l’Impératrice a tort de croire qu’une soirée inachevée est perdue."), line("Tia", "Argument insuffisamment étayé."), line("Narration", "Elle vous embrasse avant d’ajouter une note en marge."), line("Tia", "Nouvelle donnée. À réexaminer demain.")], "great", { affection: 11, trust: 7, desire: 7 }),
    ],
    intimacySetting: { opening: ["Tia verrouille le dossier et laisse la clef sur la table, geste de confiance qui n’exige aucune lecture supplémentaire. Les appartements privés sont à quelques pas.", "Elle ne devient ni docile ni soudainement accessible. Elle choisit pourtant de vous montrer chaque désir avant de le transformer en geste, et d’accueillir le vôtre sans en faire une concession impériale."], closing: ["Le dossier reste inachevé au matin. Tia ajoute seulement une feuille : « La suite nécessite deux présences et aucun secrétaire. » Votre prochaine soirée possède déjà une place."] },
  },
  {
    id: "date-draven-quays", character: "draven", title: "Le dernier verre avant la marée", type: "Soirée sur les quais", description: "Marcher avec Draven dans un port qui n’exige aucun rapport et découvrir l’homme derrière le commandement.", location: "forthaven", spot: "forthaven-harbor", period: "soirée", unlockStage: 3, minAffection: 26, minTrust: 28, mood: "gruff",
    intro: [
      line("Narration", "La relève a pris les remparts. Draven vous attend au bout du quai avec deux gobelets et une bouteille dont l’étiquette a manifestement perdu une bataille."),
      line("Draven", "C’est du rhum de marin. La marine prétend qu’il désinfecte, réchauffe et améliore les chants. Deux de ces affirmations sont des mensonges."),
      line("Narration", "Il vous tend un gobelet, puis retire de lui-même son manteau d’amiral. Sans les galons, sa carrure reste impressionnante ; son silence, beaucoup moins officiel."),
      line("Draven", "Nous avons deux heures avant la marée. Interdiction de parler stratégie pendant la première. Pour la seconde, nous improviserons comme des adultes irresponsables."),
    ],
    choices: [
      dateChoice("ddq-a", "Lui voler son gobelet et exiger la véritable histoire de sa pire chanson de bord.", "audace", [line("Draven", "Vol aggravé et atteinte à la dignité navale. J’ai fait pendre des gens pour moins que ça."), line("Narration", "Son sourire ruine entièrement la menace. L’histoire implique un gouverneur, trois tonneaux et Draven nu jusqu’aux bottes ; il jure que ce dernier détail est une calomnie.")], "great", { affection: 10, trust: 6, desire: 5 }),
      dateChoice("ddq-l", "Lui demander ce qu’il fait lorsqu’il n’a personne à protéger.", "lucidite", [line("Narration", "Draven regarde le port assez longtemps pour que la question cesse de sembler simple."), line("Draven", "J’apprends. Mal. Ce soir, par exemple, j’essaie de rester près de quelqu’un sans inventer un danger qui justifierait ma présence."), line("Narration", "Il rapproche son épaule de la vôtre, geste minuscule pour un homme habitué aux grandes manœuvres.")], "great", { affection: 8, trust: 10, desire: 4 }),
      dateChoice("ddq-s", "Admettre que son grade vous intimide encore et lui demander de ralentir.", "sangFroid", [line("Draven", "Alors le grade reste sur le manteau. Si je recommence à donner des ordres, vous avez permission de me jeter à l’eau."), line("Narration", "La tension s’allège. Il garde une distance rassurante, mais sa main reste ouverte entre vous sur le bois du quai.")], "good", { affection: 6, trust: 9, desire: 2 }),
    ],
    intimacySetting: { opening: ["La pluie arrive avant la marée. Draven vous entraîne dans une ancienne capitainerie désaffectée, pousse une table contre la porte et allume une lampe qui donne aux cartes murales une couleur d’ambre.", "Il pose le manteau, les armes et enfin son gobelet. Lorsqu’il s’approche, sa question est brève et parfaitement claire ; votre réponse l’est tout autant."], closing: ["La pluie s’achève avant vous. Draven remet ses galons dans le mauvais ordre, vous accuse d’avoir saboté l’uniforme et renonce à les corriger lorsqu’il comprend que votre sourire lui plaît davantage."] },
  },
  {
    id: "date-draven-watch", character: "draven", title: "Une nuit sans relève", type: "Veillée hors service", description: "Confier Forthaven à sa garde et offrir à Draven une nuit où rester n’est ni un ordre ni un sacrifice.", location: "forthaven", spot: "forthaven-quarters", period: "soirée", unlockStage: 4, minAffection: 34, minTrust: 34, mood: "approving",
    intro: [
      line("Narration", "Draven a fait préparer un repas dans une chambre d’officier donnant sur la mer. La porte reste ouverte jusqu’à ce qu’un messager confirme que Lineva commande la relève."),
      line("Draven", "La ville tient sans moi. J’éprouve une fierté immense et une envie très raisonnable d’aller vérifier quand même."),
      line("Narration", "Il ferme la porte avant que l’envie ne gagne, puis découvre sur la table une assiette trop délicate pour ses mains de marin."),
      line("Draven", "On m’a servi une fleur comestible. Si vous riez, je la mange avec une bravoure tactique et nous n’en parlons plus jamais."),
    ],
    choices: [
      dateChoice("ddw-a", "Manger la fleur avant lui et porter un toast à l’insubordination culinaire.", "audace", [line("Draven", "Enfin un commandement digne de confiance."), line("Narration", "Il trinque, goûte la seconde fleur et grimace avec une dignité si offensée que votre rire gagne le sien. Plus tard, il vous embrasse encore en souriant.")], "great", { affection: 10, trust: 6, desire: 7 }),
      dateChoice("ddw-l", "Lui dire que vous ne cherchez ni un héros ni un père de substitution.", "lucidite", [line("Narration", "Draven cesse de couper son pain. La franchise le heurte, puis lui rend visiblement de l’air."), line("Draven", "Bien. Parce que je vous regarde depuis des semaines d’une façon qu’aucun père digne de ce nom ne devrait employer."), line("Narration", "La rudesse de l’aveu n’en masque pas la prudence : il attend que vous réduisiez vous-même la distance.")], "great", { affection: 9, trust: 10, desire: 6 }),
      dateChoice("ddw-s", "Lui proposer de laisser la nuit ouverte, sans décider maintenant de sa conclusion.", "sangFroid", [line("Draven", "Une position défensive avec possibilité d’avancée consentie. Je comprends ce langage."), line("Narration", "Vous mangez lentement. La soirée demeure tendre ; lorsque sa main trouve la vôtre, elle n’en exige pas davantage.")], "good", { affection: 7, trust: 10, desire: 3 }),
    ],
    intimacySetting: { opening: ["Après le repas, aucun rapport n’arrive. Draven reste d’abord debout devant la fenêtre, puis se retourne et vous avoue d’une voix rauque qu’il a oublié comment demander quelque chose uniquement pour lui.", "Vous lui répondez sans détour. Il vient à vous avec la force d’un homme qui sait se retenir et le soulagement d’un homme auquel on ne demande plus de le faire seul."], closing: ["Au matin, Lineva fait glisser sous la porte un billet : « La ville a survécu. Essaie encore demain. » Draven jure, rit, puis replie le mot avec un soin qu’il ne cherche pas à cacher."] },
  },
];
