import type { HRManualSeed } from "./hylee-remerii-intimacy-shared";
import { H, N, P, R, manualHRRoutes } from "./hylee-remerii-intimacy-shared";

const CONTEXT = "group-date-hylee-remerii-home";

const seeds: HRManualSeed[] = [
  {
    slug: "canape-trop-petit",
    labels: {
      femme: "Le canapé trop petit — suivre Hylee jusqu’à la chambre",
      homme: "Le canapé trop petit — laisser Hylee transformer le logis en terrain de jeu",
      intersexe: "Le canapé trop petit — offrir tout votre désir au jeu domestique d’Hylee",
    },
    detail: "Hylee refuse de reconnaître que le canapé ne peut pas accueillir trois personnes. La maladresse devient un jeu, puis un passage choisi vers la chambre ; Remerii cesse de ranger la soirée et aide à lui donner une place durable dans le logis.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    revealChapter: 4,
    postOrgasmChapter: 8,
    tendre: [
      [N("Les bols vides restent sur la table basse. Hylee s’obstine à faire tenir trois personnes sur le canapé, une jambe sur vos genoux et l’épaule sous le bras de Remerii. Le logis paraît soudain plus habité que depuis votre emménagement.")],
      [R("Tu as la moitié du corps dans le vide."), H("La partie importante est encore avec vous."), P("Je crains de demander laquelle."), N("Remerii rit malgré elle et retient Hylee par la taille avant qu’elle ne glisse réellement.")],
      [N("Hylee profite du sauvetage pour l’embrasser, puis se tourne vers vous sans quitter son étreinte. Le baiser circule au-dessus d’un coussin écrasé ; personne ne cherche encore à rendre la position raisonnable.")],
      [N("Vous finissez pourtant par gagner la chambre, emportant la couverture du canapé et une lampe. Hylee remarque les livres près du lit ; Remerii redresse automatiquement l’un d’eux, puis laisse Hylee lui retirer la main.")],
      [N("Sur le lit, les caresses prennent leur temps. Hylee embrasse Remerii tandis que vous gardez leurs mains dans les vôtres ; elles vous ramènent entre elles et déposent sur votre peau une tendresse qui n’a rien d’improvisé.")],
      [N("Le plaisir reste doux, fait de corps nus blottis, de baisers et de paumes qui apprennent les frissons. Hylee serre vos doigts et ceux de Remerii au même instant, comme si le canapé trop petit avait enfin trouvé sa forme correcte.")],
      [H("Nous devrions peut-être déplacer le lit dans le salon."), R("Ou acheter un canapé conçu par quelqu’un qui connaît les nombres supérieurs à deux."), P("Je préfère vous voir négocier l’espace chaque fois."), N("Deux regards complices se tournent vers vous.")],
      [N("La lampe reste allumée sur la pile de livres. Hylee laisse sa tunique sur le fauteuil ; Remerii ne la ramasse pas. Elles se couchent de part et d’autre de vous avec la certitude simple qu’aucune ne doit repartir ce soir.")],
    ],
    suggestif: [
      [N("Le repas terminé, Hylee tente de s’étendre en travers de vous et de Remerii sur un canapé manifestement trop court. Un bol menace de tomber ; Remerii le sauve d’une main et retient Hylee de l’autre, vieille habitude exécutée avant même son soupir.")],
      [H("Tu vois ? Nous tenons."), R("Nous survivons à une erreur de mobilier."), N("Hylee l’embrasse, puis vous attire contre leurs deux corps. La couverture glisse avec les premiers vêtements ouverts.")],
      [N("Les baisers deviennent trop ardents pour le bord étroit. Hylee se lève, emporte la couverture et vous tend la main. Remerii prend la lampe et ferme la porte du logis ; ce sont de petits gestes domestiques qui rendent la suite plus intime qu’un décor préparé.")],
      [N("Dans la chambre, Hylee défait la coiffure de Remerii et s’allonge contre elle. Vous les regardez se toucher avec une facilité ancienne avant que leurs deux mains ne vous invitent à les rejoindre sous la lumière basse.")],
      [N("Les vêtements rejoignent le fauteuil, les livres et le tapis. Les caresses parcourent trois corps sans ordre fixe ; Hylee trouble Remerii d’un geste connu, puis vous apprend à reconnaître le souffle qui lui répond.")],
      [N("Le plaisir grandit dans les draps. Hylee jouit entre vos deux attentions ; Remerii perd sa mesure ensuite sans perdre le contact avec elle, et toutes deux vous gardent au centre de leur étreinte jusqu’à votre propre abandon.")],
      [R("Le canapé était objectivement insuffisant."), H("Mais indispensable à la démonstration."), P("J’ai surtout retenu la solution expérimentale."), N("Remerii vous embrasse tandis que Hylee s’installe déjà contre sa poitrine.")],
      [N("Vous laissez l’eau près du lit et la vaisselle pour demain. Le logis garde leurs vêtements, leur odeur et les traces visibles d’une soirée qui ne s’est pas contentée de vous rendre visite.")],
    ],
    explicite: {
      femme: [
        [N("Les bols vides sont encore sur la table lorsque Hylee tente de s’étendre en travers de vous et de Remerii. Le canapé proteste. Remerii sauve un verre, vous retenez une hanche, et Hylee utilise cette prise commune pour vous rapprocher au lieu de reconnaître son erreur."), H("La place existe si personne ne réclame de frontière.", "teasing")],
        [N("Elle embrasse Remerii, qui lui répond avec la familiarité d’un geste attendu depuis le premier bol partagé. Vous trouvez leur bouche tour à tour tandis que leurs mains ouvrent votre tunique sous la couverture. Le canapé devient vite trop étroit pour le désir qu’Hylee vient de réveiller entre vos trois corps.")],
        [N("Hylee se lève en emportant la couverture et vous tend la main. Remerii prend la lampe, ferme la porte du logis et laisse volontairement les bols où ils sont. Vous gagnez la chambre ensemble, en passant devant les objets exposés et les livres qui font de cette pièce votre lieu plutôt qu’une chambre interchangeable.")],
        [N("Sur le lit, Hylee libère les cheveux de Remerii et retire sa propre tunique. Leurs corps nus se retrouvent sous la lumière bleue de la fenêtre ; Remerii caresse les cicatrices de Hylee, qui embrasse la sienne avec une tendresse immédiatement brisée par un sourire provocant. Elles vous attirent entre elles avant que vous ne deveniez spectatrice.")],
        [N("Hylee ouvre vos vêtements et découvre vos seins. Elle en prend un dans sa bouche ; Remerii couvre l’autre de sa paume, puis se penche pour embrasser Hylee au-dessus de votre poitrine. Leurs langues se rencontrent contre votre peau, et vos mains descendent sur leurs deux corps afin que le désir circule dans les trois directions.")],
        [N("Vous allongez Remerii contre les oreillers. Hylee vient entre ses cuisses et la goûte avec une assurance nourrie d’habitudes anciennes ; vous l’embrassez et glissez vos doigts dans sa chaleur. Remerii caresse Hylee entre les épaules, puis vous guide d’un mouvement de bassin plutôt que par une explication.")],
        [N("Remerii jouit dans la bouche de Hylee, ses doigts serrés dans vos cheveux. Hylee remonte l’embrasser et partage son plaisir sans pudeur théâtrale. Vous les regardez quelques secondes, puis elles vous allongent entre elles : Hylee descend sur vous, Remerii vient à votre bouche, et leurs mains restent nouées au-dessus de votre ventre.")],
        [N("Votre langue fait trembler Remerii tandis que celle de Hylee vous conduit vers le bord. Vous caressez Hylee de deux doigts, suivant le rythme de ses hanches contre le matelas. Votre orgasme éclate le premier ; Remerii jouit presque en même temps contre votre bouche, et Hylee se brise sous votre main avant d’abandonner votre chaleur.")],
        [N("Le calme revient dans les draps défaits. Hylee repose contre la poitrine de Remerii, encore rouge, et garde une main sur votre ventre. La seconde image de la soirée n’est plus celle d’un canapé trop petit, mais de trois places volontairement gardées. Vous partagez l’eau, un linge doux et des baisers sans empressement.")],
        [H("Je maintiens que nous tenions sur le canapé."), R("Nous tenions parce que deux personnes t’empêchaient de tomber."), P("Nous pouvons conserver cette organisation ici."), N("Hylee approuve en se serrant davantage contre vous deux. Sa tunique reste sur le fauteuil ; Remerii la regarde et décide très clairement de ne pas la ranger.")],
      ],
      homme: [
        [N("Les bols vides sont encore sur la table lorsque Hylee tente de s’étendre en travers de vous et de Remerii. Le canapé proteste. Remerii sauve un verre, vous retenez une hanche, et Hylee utilise cette prise commune pour vous rapprocher au lieu d’admettre qu’elle n’a plus de place."), H("La place existe si personne ne réclame de frontière.", "teasing")],
        [N("Elle embrasse Remerii, qui répond comme si ce geste attendait depuis le premier bol partagé. Vous trouvez leurs lèvres à tour de rôle pendant que leurs mains ouvrent votre chemise. Lorsque votre désir se tend sous la couverture, Hylee le remarque d’un sourire et Remerii cesse aussitôt de prétendre que le mobilier constitue le seul problème.")],
        [N("Hylee emporte la couverture et vous conduit vers la chambre. Remerii prend la lampe, ferme la porte du logis et laisse volontairement la vaisselle pour demain. Vous passez devant les souvenirs exposés et les livres déjà touchés durant la soirée ; chaque détail affirme que la suite se déroule chez vous, dans un lieu où elles peuvent rester.")],
        [N("Sur le lit, Hylee défait la coiffure de Remerii et retire sa tunique. Leurs corps nus se retrouvent sous la lueur bleue de la fenêtre. Remerii caresse les cicatrices de Hylee, qui embrasse la sienne avant de l’attirer dans un baiser plus affamé. Elles vous ouvrent les bras sans interrompre leur mouvement.")],
        [N("Hylee défait votre ceinture et prend votre désir dressé dans sa main. Remerii couvre ses doigts des siens, attentive à votre souffle, puis Hylee vous accueille dans sa bouche. Vous caressez la poitrine de Remerii pendant qu’elle touche Hylee entre les cuisses ; le plaisir donné à l’une transforme immédiatement celui qu’elle vous donne.")],
        [N("Vous allongez Remerii contre les oreillers. Hylee vient entre ses cuisses et la goûte avec une assurance ancienne ; vous embrassez la mage et gardez une main sur la hanche de Hylee. Remerii serre votre désir dans sa paume, suivant les réactions de Hylee plutôt qu’un compte, et ses propres gémissements passent dans votre bouche.")],
        [N("Remerii jouit sous la langue de Hylee et vous maintient au bord dans sa main. Hylee remonte l’embrasser, puis s’allonge entre elles. Remerii soutient sa nuque et caresse ses seins ; vous entrez lentement en Hylee, guidé par ses jambes autour de vous et par la paume de Remerii sur votre bassin.")],
        [N("Hylee jouit sous vos mouvements, la bouche contre celle de Remerii. Vous poursuivez jusqu’à votre propre limite ; Remerii accompagne chaque avancée de ses doigts sur Hylee et de ses baisers sur votre épaule. Vous jouissez en Hylee, retenu par leurs deux corps, puis restez profondément contre elle jusqu’à ce que les dernières contractions s’apaisent.")],
        [N("Vous vous retirez avec douceur et le calme remplit la chambre. Hylee repose contre la poitrine de Remerii, encore rouge, une main sur votre ventre. La seconde image de la soirée n’est plus celle d’un canapé impossible : trois places sont gardées sous les draps. L’eau, le linge et les baisers passent sans qu’une seule personne serve les autres.")],
        [H("Nous tenions très bien sur le canapé."), R("Parce que deux personnes empêchaient ta chute."), P("Gardons cette répartition ici."), N("Hylee se serre davantage contre vous deux. Sa tunique reste sur le fauteuil ; Remerii la voit, hésite par habitude, puis choisit vos bras au lieu de la ranger.")],
      ],
      intersexe: [
        [N("Les bols vides sont encore sur la table lorsque Hylee tente de s’étendre en travers de vous et de Remerii. Le canapé proteste. Remerii sauve un verre, vous retenez une hanche, et Hylee transforme votre prise commune en invitation plutôt que d’admettre le moindre problème d’espace."), H("La place existe si personne ne dessine de frontière.", "teasing")],
        [N("Elle embrasse Remerii, qui lui répond avec la familiarité d’un geste attendu depuis le dîner. Vous trouvez leurs lèvres tandis que leurs mains ouvrent votre tunique. Sous la couverture, les deux expressions de votre désir répondent ; Hylee et Remerii les accueillent ensemble, sans décider laquelle doit raconter la suite de votre corps.")],
        [N("Hylee emporte la couverture vers la chambre. Remerii prend la lampe, ferme la porte du logis et laisse la vaisselle pour demain. Vous passez devant les souvenirs exposés et les livres touchés durant la soirée ; la suite appartient à votre foyer, à ses objets et à la possibilité nouvelle de les y voir rester.")],
        [N("Sur le lit, Hylee libère les cheveux de Remerii et retire sa tunique. Leurs corps nus se retrouvent sous la lumière bleue. Remerii caresse les cicatrices de Hylee, qui embrasse la sienne puis l’attire dans un baiser plus avide. Elles vous ouvrent leurs bras sans interrompre cet échange qui existe aussi entre elles.")],
        [N("Hylee libère votre poitrine et descend vers votre désir dressé pendant que Remerii caresse votre chaleur. La bouche de Hylee vous accueille ; les doigts de Remerii entrent en vous. Vous ouvrez leurs vêtements et elles s’embrassent au-dessus de votre ventre, ajustant chaque geste aux réponses réunies de votre corps.")],
        [N("Vous allongez Remerii contre les oreillers. Hylee vient entre ses cuisses et la goûte ; vous embrassez la mage et caressez Hylee dans le même mouvement. Remerii garde une main autour de votre désir, l’autre dans votre chaleur, et son propre plaisir se nourrit de cette chaîne plutôt que de vous répartir en deux besoins séparés.")],
        [N("Remerii jouit contre la bouche de Hylee. Celle-ci remonte l’embrasser, puis elles vous allongent entre elles. Hylee reprend votre désir avec sa bouche ; Remerii poursuit en vous une caresse profonde. Vous gardez une main entre les cuisses de chacune, et leurs baisers passent au-dessus de votre poitrine comme un rythme partagé.")],
        [N("Votre orgasme traverse les deux foyers de votre plaisir. Hylee vous garde dans sa bouche, Remerii maintient l’angle en vous, leurs mains se rejoignent sur votre ventre. Hylee se presse contre votre cuisse et jouit sous vos doigts ; Remerii reçoit votre autre main jusqu’à son second frisson, sans que le triangle se défasse.")],
        [N("Le calme revient dans les draps. Hylee repose contre la poitrine de Remerii, une main sur votre ventre. La soirée ne ressemble plus à un canapé trop petit : trois places sont volontairement gardées. Vous partagez l’eau et le linge sans commenter l’anatomie qui a répondu, seulement les gestes que vous voulez retrouver.")],
        [H("Nous tenions parfaitement sur le canapé."), R("Deux personnes empêchaient ta chute."), P("Gardons exactement cette organisation ici."), N("Hylee approuve en se serrant contre vous deux. Sa tunique reste sur le fauteuil ; Remerii la regarde, puis choisit pour une fois de ne rien remettre en ordre avant le matin.")],
      ],
    },
    ellipse: [
      [N("Après le repas, Hylee tente de faire tenir trois personnes sur le canapé. Remerii sauve un verre, vous sauvez Hylee, et personne ne sauve la distance.")],
      [H("Nous tenons."), R("Nous compensons une erreur de mobilier."), N("Hylee l’embrasse comme si cette objection confirmait exactement son raisonnement.")],
      [N("Les baisers circulent sous la couverture. Quand le canapé devient réellement impossible, Hylee l’emporte et vous conduit vers la chambre avec Remerii.")],
      [N("Remerii prend la lampe et ferme la porte. Vous passez devant les objets exposés et les livres ; le logis entier accompagne le choix de rester.")],
      [N("Dans la chambre, Hylee et Remerii se déshabillent l’une l’autre avant de vous attirer entre elles. Leurs habitudes anciennes font immédiatement place à vos gestes.")],
      [N("La lumière baisse sur le lit. Trois plaisirs s’y répondent, liés par les mains et les baisers qui refusent de laisser une personne hors du mouvement.")],
      [R("Le canapé était insuffisant."), H("Il nous a conduits ici."), P("Je vote pour le conserver."), N("Elles approuvent d’un même rire fatigué.")],
      [N("La vaisselle attendra. Leurs vêtements restent dans la pièce et leurs corps de part et d’autre du vôtre affirment qu’aucune ne repart cette nuit.")],
    ],
  },
  {
    slug: "lumiere-basse",
    labels: {
      femme: "La lumière basse — laisser Remerii demander ce qu’elle veut garder",
      homme: "La lumière basse — recevoir l’initiative intime de Remerii au logis",
      intersexe: "La lumière basse — laisser Remerii écouter votre corps sans le classer",
    },
    detail: "Remerii baisse elle-même les lampes et demande à rester. Son initiative naît des détails du logis et de la confiance acquise ; Hylee la connaît assez pour ne pas plaisanter trop tôt, puis assez bien pour rendre son désir moins solennel.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    revealChapter: 4,
    postOrgasmChapter: 8,
    tendre: [
      [N("Remerii débarrasse trois bols, puis s’arrête devant une petite lampe laissée près de vos livres. Elle baisse la flamme au lieu de l’éteindre et replace machinalement un marque-page qui dépassait.")],
      [H("Tu ranges quand tu veux rester."), R("Je range quand quelque chose est mal placé."), H("Tu viens de déplacer la lampe trois fois."), N("Remerii lui adresse un regard inutilement sévère, puis tend la main vers vous.")],
      [N("Elle vous embrasse avec une franchise calme et revient ensuite vers Hylee. Celle-ci ne plaisante plus ; elle pose les mains sur sa taille et reçoit le baiser qu’elle savait venir avant même la première dénégation.")],
      [N("Vous gagnez la chambre sans urgence. Remerii prend le temps de regarder les livres, la couverture et les objets choisis ; lorsqu’elle s’assied sur le lit, elle demande simplement si elle peut rester jusqu’au matin.")],
      [N("Hylee répond en se glissant contre elle. Vous les rejoignez et les caresses deviennent un langage lent : une main sur une cicatrice, une bouche contre une tempe, trois corps nus qui ne cherchent aucune performance.")],
      [N("Le plaisir vient comme une confiance physique. Remerii reçoit autant qu’elle donne ; Hylee garde son visage entre ses mains au moment de son frisson, et elles vous entourent ensemble lorsque le vôtre répond.")],
      [H("Tu as oublié de ranger ma tunique."), R("Je ne l’ai pas oubliée."), P("Nous assistons à un événement historique."), N("Remerii vous ramène, Hylee et vous, contre elle avant que la célébration ne prenne de l’ampleur.")],
      [N("La lampe basse dessine encore les bibliothèques lorsque vous vous installez pour dormir. Remerii choisit le milieu, non pour surveiller, mais parce qu’elle veut sentir une respiration de chaque côté.")],
    ],
    suggestif: [
      [N("Après le repas, Remerii baisse elle-même les lampes. Elle replace un objet exposé, hésite, puis le remet exactement comme vous l’aviez posé. Hylee observe cette capitulation domestique avec une douceur inhabituelle.")],
      [H("Tu ranges quand tu as peur de demander quelque chose."), R("Je souhaite rester."), N("La réponse coupe toute taquinerie. Remerii vous embrasse, puis Hylee, et garde vos deux mains dans les siennes.")],
      [N("Vous gagnez la chambre en emportant la dernière lampe. Remerii remarque les livres près du lit ; Hylee lui retire celui qu’elle allait encore redresser et remplace ce geste par un baiser contre ses doigts.")],
      [N("Les vêtements tombent lentement. Hylee embrasse les cicatrices de Remerii tandis que vous ouvrez sa coiffure ; elle touche Hylee puis votre corps avec une attention qui n’a plus besoin de se déguiser en méthode.")],
      [N("Sur les draps, Remerii guide d’abord les caresses, puis accepte que Hylee dérange chaque cadence et que vous choisissiez des chemins qu’elle n’avait pas prévus. Son rire discret rejoint bientôt les souffles plus ardents.")],
      [N("Elle jouit entre vous sans détourner le visage. Hylee l’embrasse à travers le frisson ; Remerii vous garde contre elle et conduit ensuite les deux autres plaisirs sans retrouver sa distance.")],
      [H("Ma tunique est toujours sur le fauteuil."), R("Oui."), P("Doit-on s’inquiéter ?"), R("Pas ce soir."), N("Cette réponse vaut un nouveau baiser à Hylee, puis à vous.")],
      [N("La lampe reste basse, jamais éteinte. Vous vous couchez ensemble, entourés des livres et des traces du repas, avec la certitude que Remerii a choisi le désordre parce qu’il signifie qu’elle demeure.")],
    ],
    explicite: {
      femme: [
        [N("Remerii rapporte trois bols à la table, puis s’arrête devant la petite lampe près de vos livres. Elle baisse la flamme et replace un marque-page avant de s’immobiliser. Hylee reconnaît le tic : ranger ce qui l’entoure lorsqu’une demande la rend vulnérable. Elle pose doucement une main sur la sienne au lieu d’en rire."), R("Je voudrais rester cette nuit. Avec vous deux.", "soft")],
        [N("Elle vous embrasse la première, sans vocabulaire savant pour amortir son désir, puis attire Hylee par la nuque. Leur baiser est ancien dans ses réflexes et nouveau dans ce qu’il accepte d’inclure. Vous gardez une main sur chacune ; Remerii les prend et les réunit sur son cœur avant de vous conduire vers la chambre.")],
        [N("La dernière lampe voyage avec vous. Remerii regarde les livres empilés près du lit et les objets que vous avez choisis d’exposer. Hylee retire de ses doigts le vêtement qu’elle s’apprêtait à plier, le jette sur le fauteuil et embrasse chaque phalange, jusqu’à ce que la précision de Remerii se transforme en impatience.")],
        [N("Elles se déshabillent face à vous sous la lumière bleue. Hylee embrasse la cicatrice de Remerii ; cette dernière caresse les marques claires sur sa peau et lui murmure qu’elle se souvient de chacune. Vous les rejoignez sur le lit, invité par leurs deux mains, et leur histoire devient un passage ouvert plutôt qu’un secret auquel assister.")],
        [N("Remerii vous allonge entre elles et ouvre votre tunique. Elle embrasse vos seins avec une lenteur appliquée que Hylee dérange en caressant sa poitrine puis sa chaleur. Chaque frisson reçu change la bouche posée sur vous. Vous attirez Hylee pour l’embrasser et lui donnez à votre tour ce que ses doigts donnent à Remerii.")],
        [N("Vous faites asseoir Remerii contre les oreillers. Hylee vient à sa bouche ; votre langue descend entre ses cuisses. La mage ouvre son corps, une main dans vos cheveux, l’autre sur Hylee. Hylee glisse ses doigts en vous tout en embrassant Remerii, de sorte que son plaisir traverse les deux personnes qui la regardent enfin le recevoir.")],
        [N("Remerii jouit sous votre langue, le visage tourné vers Hylee. Celle-ci recueille son cri dans un baiser, puis vous attire sur les draps. Remerii vient entre vos cuisses ; Hylee s’installe au-dessus de votre bouche. Vous les goûtez toutes deux tandis qu’elles gardent leurs mains jointes sur votre ventre.")],
        [N("La bouche de Remerii et les mouvements de Hylee vous conduisent au bord. Votre orgasme vous fait serrer leurs cuisses ; Hylee jouit contre votre langue, soutenue par la main de Remerii sur sa hanche. Remerii prolonge vos frissons, puis Hylee la ramène contre vous afin que le plaisir achevé ne crée aucune distance.")],
        [N("Dans l’après, Hylee repose contre la poitrine de Remerii. Vous caressez leurs mains jointes sur le drap ; l’image est calme, lumineuse, débarrassée de toute nécessité de ranger. Remerii accepte l’eau que vous lui tendez, laisse Hylee essuyer sa peau et garde sa tête au milieu des deux oreillers.")],
        [H("Ma tunique est encore sur le fauteuil."), R("Je sais."), P("Elle y sera demain."), N("Remerii regarde le vêtement, puis vos deux visages. Elle choisit le milieu du lit et éteint enfin la lampe d’un geste, non pour clore la scène, mais parce qu’elle n’a plus besoin de surveiller la pièce pour savoir qu’elle peut rester.")],
      ],
      homme: [
        [N("Remerii rapporte trois bols, puis s’arrête devant la lampe près de vos livres. Elle baisse la flamme et replace un marque-page avant de s’immobiliser. Hylee reconnaît son vieux réflexe : ranger lorsqu’une demande la rend vulnérable. Elle pose une main sur la sienne sans laisser la taquinerie gâcher l’instant."), R("Je voudrais rester cette nuit. Avec vous deux.", "soft")],
        [N("Elle vous embrasse la première, sans explication protectrice, puis attire Hylee par la nuque. Leur baiser porte des gestes appris durant des années et un désir qu’elles choisissent maintenant d’ouvrir. Vous gardez une main sur chacune ; Remerii les réunit sur son cœur avant de vous conduire vers la chambre.")],
        [N("La dernière lampe voyage avec vous. Remerii regarde les livres et les objets exposés. Hylee lui retire le vêtement qu’elle allait plier, le jette sur le fauteuil et embrasse ses doigts jusqu’à ce que la précision disparaisse. Vous ouvrez votre chemise ; leurs regards suivent votre désir avant que leurs mains ne le rejoignent.")],
        [N("Elles se déshabillent sous la lumière bleue. Hylee embrasse la cicatrice de Remerii ; la mage caresse les marques claires sur Hylee et lui murmure qu’elle se souvient de chacune. Vous les rejoignez sur le lit, accueilli par leurs deux mains, et leur histoire demeure visible jusque dans le désir qu’elles posent sur vous.")],
        [N("Remerii s’agenouille devant vous et prend votre désir dans sa bouche. Hylee vient derrière elle, caresse ses seins puis descend entre ses cuisses. Les mouvements de Remerii se dérèglent sous ce plaisir ; vous caressez Hylee à votre tour, gardant le triangle actif plutôt que de laisser une femme travailler pendant que l’autre attend.")],
        [N("Vous arrêtez Remerii avant le bord et l’allongez contre les oreillers. Hylee l’embrasse ; votre bouche descend entre ses cuisses. Remerii ouvre son corps, une main dans vos cheveux, l’autre autour de votre désir. Hylee caresse votre poitrine et la sienne, puis guide vos hanches sans reprendre le contrôle de la scène.")],
        [N("Remerii jouit sous votre langue, son cri recueilli par la bouche de Hylee. Elles vous relèvent ensuite et Hylee s’allonge entre elles. Remerii soutient sa nuque, vous entrez lentement en elle ; les deux femmes s’embrassent pendant que vos mouvements suivent le rythme que leurs corps inventent ensemble.")],
        [N("Hylee jouit sous vous, serrée contre Remerii. Son plaisir vous entraîne ; vous jouissez en elle pendant que Remerii garde une main sur votre bassin et l’autre entre les cuisses de Hylee. Elle prolonge vos frissons, puis vous rapproche tous deux afin que personne ne quitte trop vite le corps des autres.")],
        [N("Dans l’après, Hylee repose contre la poitrine de Remerii. Vous couvrez leurs mains jointes des vôtres ; la scène est calme, lumineuse, délivrée de toute tâche. Remerii reçoit l’eau, laisse Hylee essuyer sa peau et accepte que votre propre confort soit pris en charge sans transformer l’attention en protocole.")],
        [H("Ma tunique est toujours sur le fauteuil."), R("Je sais."), P("Elle y sera demain."), N("Remerii regarde le vêtement, puis vos deux visages. Elle choisit le milieu du lit et éteint la lampe, assez sereine pour dormir avec une respiration de chaque côté.")],
      ],
      intersexe: [
        [N("Remerii rapporte trois bols, puis s’arrête devant la lampe près de vos livres. Elle baisse la flamme et replace un marque-page avant de s’immobiliser. Hylee reconnaît le réflexe : ranger lorsque demander devient difficile. Elle pose une main sur la sienne sans taquinerie, et attend que Remerii choisisse ses propres mots."), R("Je voudrais rester cette nuit. Avec vous deux.", "soft")],
        [N("Elle vous embrasse la première sans explication protectrice, puis attire Hylee par la nuque. Leur baiser mêle des gestes appris et un désir désormais ouvert. Vous gardez une main sur chacune ; Remerii les réunit sur son cœur, attentive à la manière entière dont votre corps répond avant de vous conduire vers la chambre.")],
        [N("La lampe voyage avec vous. Remerii regarde les livres et les objets exposés. Hylee lui retire le vêtement qu’elle allait plier, le jette sur le fauteuil et embrasse ses doigts. Vous ouvrez votre tunique ; leurs regards accueillent votre poitrine, votre désir dressé et votre chaleur sans chercher à ordonner ces réponses.")],
        [N("Elles se déshabillent sous la lumière bleue. Hylee embrasse la cicatrice de Remerii ; la mage caresse les marques claires sur Hylee et lui murmure qu’elle se souvient de chacune. Vous les rejoignez sur le lit, accueilli par leurs deux mains, corps entier parmi deux histoires qui demeurent liées.")],
        [N("Remerii s’agenouille devant vous. Sa bouche entoure votre désir tandis que ses doigts glissent dans votre chaleur. Hylee vient derrière elle, caresse ses seins puis son intimité. Les gestes de Remerii se dérèglent sous ce plaisir ; vous touchez Hylee à votre tour et chaque réaction nourrit immédiatement les deux autres.")],
        [N("Vous arrêtez Remerii avant votre limite et l’allongez contre les oreillers. Hylee l’embrasse, votre bouche descend entre ses cuisses. Remerii garde une main autour de votre désir, l’autre en vous ; Hylee guide parfois l’une puis l’autre sans réduire votre corps à une seule forme de plaisir.")],
        [N("Remerii jouit sous votre langue, son cri recueilli par la bouche de Hylee. Elles vous allongent ensuite entre elles. Hylee reprend votre désir avec sa bouche ; Remerii poursuit profondément en vous. Vous caressez chacune et regardez leurs mains se rejoindre sur votre ventre avant que le rythme n’emporte toute parole.")],
        [N("Votre orgasme traverse simultanément tout votre corps. Hylee maintient sa bouche sur vous, Remerii ses doigts en vous, et leurs attentions se prolongent jusqu’à ce que vous cessiez de trembler. Hylee jouit sous votre main ; Remerii reçoit la vôtre ensuite, embrassée par Hylee au moment de son propre abandon.")],
        [N("Dans l’après, Hylee repose contre la poitrine de Remerii. Vous couvrez leurs mains jointes des vôtres ; rien ne doit être classé ni rangé. Remerii accepte l’eau, laisse Hylee prendre soin de sa peau et vous demande seulement quels gestes vous souhaitez retrouver, jamais quelle moitié de votre corps a compté davantage.")],
        [H("Ma tunique est encore sur le fauteuil."), R("Je sais."), P("Elle y sera demain."), N("Remerii regarde le vêtement puis vos visages. Elle choisit le milieu du lit et éteint la lampe, certaine de pouvoir rester entre deux respirations qui connaissent désormais la sienne.")],
      ],
    },
    ellipse: [
      [N("Après le repas, Remerii baisse la lampe près des livres et replace trois fois le même marque-page. Hylee pose une main sur la sienne.")],
      [H("Tu ranges quand tu veux demander quelque chose."), R("Je veux rester cette nuit."), N("La franchise efface aussitôt la plaisanterie du visage de Hylee.")],
      [N("Remerii vous embrasse, puis Hylee. Elle garde vos mains réunies sur son cœur avant de vous conduire vers la chambre.")],
      [N("La lampe voyage avec vous. Les livres, les objets exposés et les vêtements laissés sur le fauteuil rendent la pièce réellement vôtre.")],
      [N("Hylee et Remerii se retrouvent nues dans la lumière bleue, anciennes cicatrices reconnues par des gestes connus. Leurs mains viennent ensuite ouvrir une place entière à votre corps.")],
      [N("Les draps recueillent un désir sans méthode. Trois plaisirs y circulent, se soutiennent et s’apaisent sans laisser l’une des personnes au bord du lit.")],
      [H("Tu as laissé ma tunique sur le fauteuil."), R("Je sais."), P("Nous avons donc une preuve."), N("Remerii embrasse Hylee, puis vous, pour interrompre l’enquête.")],
      [N("Elle choisit le milieu du lit et éteint la lampe. Une respiration de chaque côté suffit à lui confirmer qu’elle peut réellement rester.")],
    ],
  },
  {
    slug: "elles-restent",
    labels: {
      femme: "Elles restent — faire du logis un lieu réellement partagé",
      homme: "Elles restent — laisser le désir naître de trois présences chez vous",
      intersexe: "Elles restent — habiter ensemble le désir et l’après",
    },
    detail: "Aucune personne ne mène durablement. Un objet exposé, un vêtement laissé et une place créée dans la bibliothèque transforment la soirée en promesse concrète : Hylee et Remerii ne sont pas seulement invitées à passer, mais à revenir et à rester.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    revealChapter: 4,
    postOrgasmChapter: 8,
    tendre: [
      [N("Hylee dépose un petit galet ramassé durant la promenade parmi vos objets exposés. Remerii proteste qu’il tachera l’étagère, puis glisse dessous un morceau de tissu au lieu de le retirer.")],
      [P("Il faudra donc lui laisser une place."), H("Au galet ?"), P("À tout ce que vous oublierez ici."), R("Hylee n’oublie rien. Elle colonise."), N("Hylee répond en posant sa tête sur son épaule.")],
      [N("Le baiser qui suit naît de ce geste minuscule. Hylee embrasse Remerii, puis vous attire dans leur proximité. Vos trois reflets apparaissent un instant dans la vitre sombre, ensemble au milieu de la pièce.")],
      [N("Vous portez les couvertures et la lampe dans la chambre, mais laissez les vêtements se disperser sur le chemin. Chaque pièce conserve ainsi la trace d’un passage qui ne ressemble plus à une visite polie.")],
      [N("Sur le lit, aucune personne ne garde le centre. Les baisers et les caresses changent de direction ; Hylee et Remerii se retrouvent, vous regardent, puis vous ramènent dans leur mouvement commun.")],
      [N("Le plaisir doux accompagne trois promesses sans serment : demander, écouter, revenir. Vous atteignez ensemble cette détente qui rend les corps lourds et les silences simples.")],
      [R("Le galet reste sur l’étagère."), H("Victoire historique."), P("La tunique aussi ?"), R("N’abusons pas de la portée de cet accord."), N("Elle la laisse pourtant sur le fauteuil.")],
      [N("Vous vous endormez sans répartir les places pour toujours. Ce soir, Hylee garde le mur, Remerii le bord et vous le milieu ; demain, la configuration pourra changer parce qu’elles seront encore là pour le décider.")],
    ],
    suggestif: [
      [N("Hylee installe sur votre étagère un galet de la promenade. Remerii le soulève, essuie la poussière dessous et le repose sur un carré de tissu. Le geste admet déjà que l’objet a le droit de rester.")],
      [P("Gardons une place pour ce que vous laisserez ici."), R("Hylee transforme les oublis en stratégie territoriale."), H("Tu viens de protéger mon territoire avec un tissu."), N("Remerii l’embrasse pour éviter une réponse.")],
      [N("Vous les rejoignez devant l’étagère. Les baisers gagnent en profondeur, les attaches s’ouvrent, et vos trois reflets se mêlent dans la fenêtre avant que Hylee ne vous entraîne vers la chambre.")],
      [N("Les vêtements jalonnent le trajet : manteau sur le dossier, tunique au pied du lit, bijoux près de vos livres. Le logis garde chaque abandon comme la promesse visible d’un lendemain partagé.")],
      [N("Sur les draps, l’initiative circule. Hylee et Remerii s’embrassent pendant que vous les touchez ; elles vous attirent ensuite entre elles et répondent ensemble aux réactions qu’elles provoquent.")],
      [N("Les plaisirs se succèdent sans tours séparés. Deux corps soutiennent toujours le troisième, puis les places changent jusqu’à ce que le dernier frisson s’apaise dans trois paires de bras mêlées.")],
      [H("Le galet reste."), R("Oui."), P("Et vous ?"), N("La question n’exige pas de discours. Hylee se glisse sous la couverture ; Remerii pose ses bijoux sur la table de nuit.")],
      [N("La lampe s’éteint sur une pièce marquée par trois présences. Le repas attend dans la cuisine, les vêtements dans le salon, et personne ne prépare un départ avant le matin.")],
    ],
    explicite: {
      femme: [
        [N("Hylee installe sur l’étagère un galet rapporté de la promenade. Remerii le soulève, essuie la poussière et glisse dessous un morceau de tissu avant de le reposer. Elle vient d’admettre, sans le dire, que cette trace a le droit de rester chez vous. Hylee l’observe avec un sourire qui n’a rien de moqueur."), P("Il faudra garder de la place pour ce que vous laisserez encore.")],
        [N("Hylee embrasse Remerii devant l’étagère. Vous les rejoignez ; votre reflet apparaît avec les leurs dans la vitre sombre. Remerii garde une main sur la taille de Hylee et vous attire de l’autre. Le baiser à trois n’efface pas leur échange : il lui donne un espace plus vaste dans lequel votre désir existe pleinement.")],
        [N("Vous gagnez la chambre en laissant des traces dans chaque pièce : manteau sur le dossier, tunique près de la porte, bijoux entre deux de vos livres. Hylee emporte la lampe, Remerii la couverture. Ce trajet lent transforme le logis entier en scène, non un simple seuil avant un lit sans histoire.")],
        [N("Dans la lumière nocturne, Hylee et Remerii se déshabillent l’une l’autre. Les cicatrices claires de Hylee passent sous la bouche de Remerii ; la longue marque de la mage reçoit les lèvres de Hylee. Elles se regardent, nues et familières, puis vous tendent chacune une main pour que ce tableau ne demeure jamais fermé.")],
        [N("Vous vous allongez entre elles. Hylee embrasse votre poitrine pendant que Remerii ouvre vos cuisses et caresse votre chaleur. Votre main trouve Hylee ; l’autre remonte sur Remerii. Elles s’embrassent au-dessus de votre ventre, et chaque contact qu’elles échangent modifie les gestes qu’elles vous donnent, comme une conversation tenue par trois corps.")],
        [N("Hylee s’étend sur le dos, Remerii vient entre ses cuisses et vous vous placez près de son visage. Vous embrassez Hylee pendant que la langue de Remerii lui donne du plaisir ; Hylee glisse ses doigts en vous et garde son autre main dans les cheveux de Remerii. La première place centrale ne devient jamais une place solitaire.")],
        [N("Hylee jouit entre vous, son rire devenu cri contre votre bouche. Elle ramène Remerii pour l’embrasser, puis toutes deux vous allongent. Remerii vient à votre bouche ; Hylee descend entre vos cuisses. Vous goûtez Remerii tandis qu’elle se presse contre vous et que la bouche de Hylee vous porte vers votre limite.")],
        [N("Votre orgasme éclate sous la langue de Hylee. Remerii jouit au même instant contre votre bouche, retenue par votre main et celle de Hylee sur sa hanche. Elles se retrouvent au-dessus de vous dans un baiser haletant ; vous les gardez serrées contre votre corps jusqu’à ce que les derniers tremblements deviennent une simple chaleur partagée.")],
        [N("Après, Hylee repose contre la poitrine de Remerii, leurs mains jointes sur le drap. Vous vous blottissez contre leurs dos et partagez l’eau. La chambre, les livres et la lumière derrière la fenêtre composent l’image d’un lieu habité. Aucun plaisir n’a clos la soirée : il l’a changée en temps que vous pouvez encore partager.")],
        [H("Le galet reste."), R("Oui."), P("Et vous ?"), N("Hylee se glisse sous la couverture. Remerii pose ses bijoux près de vos livres, puis vous embrasse toutes deux avant de choisir une place qui pourra changer demain. La réponse est dans leurs vêtements dispersés et dans l’absence complète de préparatifs de départ.")],
      ],
      homme: [
        [N("Hylee installe sur l’étagère un galet rapporté de la promenade. Remerii le soulève, essuie la poussière et place dessous un morceau de tissu avant de le reposer. Elle vient d’admettre sans discours que cette trace peut rester chez vous. Hylee observe la capitulation avec une douceur qui protège l’instant."), P("Il faudra garder de la place pour ce que vous laisserez encore.")],
        [N("Hylee embrasse Remerii devant l’étagère. Vous rejoignez leurs corps ; votre reflet se mêle aux leurs dans la vitre sombre. Remerii maintient Hylee à la taille et vous attire de l’autre main. Le baiser à trois élargit leur échange sans le remplacer, et votre désir se tend contre elles dans ce mouvement commun.")],
        [N("Vous gagnez la chambre en laissant des traces dans chaque pièce : manteau sur le dossier, chemise près de la porte, bijoux entre deux livres. Hylee emporte la lampe, Remerii la couverture. Le trajet fait du logis entier un lieu de désir, et non un couloir vers une chambre interchangeable.")],
        [N("Dans la lumière nocturne, Hylee et Remerii se déshabillent l’une l’autre. Les marques claires de Hylee passent sous la bouche de Remerii ; sa cicatrice reçoit les lèvres de Hylee. Elles se regardent, nues et familières, puis vous tendent leurs mains afin que cette histoire visible accueille aussi votre corps.")],
        [N("Hylee s’agenouille devant vous et prend votre désir dans sa bouche pendant que Remerii embrasse votre poitrine. Vous caressez Remerii entre les cuisses ; elle glisse une main sous Hylee et lui donne du plaisir. Les mouvements autour de vous changent avec chaque frisson reçu, reliant immédiatement ce que chacune donne et éprouve.")],
        [N("Vous étendez Hylee sur le dos. Remerii vient entre ses cuisses et vous restez près de son visage ; Hylee vous caresse tout en embrassant votre ventre. La langue de Remerii trouve sa chaleur, votre main trouve celle de Remerii, et Hylee garde le lien par ses baisers et ses doigts autour de vous.")],
        [N("Hylee jouit sous la bouche de Remerii et vous attire ensuite au-dessus d’elle. Remerii soutient sa nuque, caresse sa poitrine et vous guide par la hanche pendant que vous entrez lentement. Hylee embrasse la mage à chaque mouvement, et leur plaisir mutuel accompagne le vôtre au lieu d’attendre une place suivante.")],
        [N("Vous jouissez en Hylee au moment où Remerii la conduit vers un second frisson. Les deux femmes restent enlacées sous vous ; Remerii embrasse Hylee à travers les contractions, puis vous ramène contre elles. Aucun corps ne s’écarte avant que la tension se soit changée en une chaleur égale entre les trois.")],
        [N("Après, Hylee repose contre la poitrine de Remerii, leurs mains jointes. Vous vous blottissez contre elles et partagez l’eau. La chambre, les livres et la fenêtre composent l’image d’un lieu habité. Le plaisir n’a pas terminé la visite : il a confirmé qu’il existe désormais un lendemain possible dans ces mêmes draps.")],
        [H("Le galet reste."), R("Oui."), P("Et vous ?"), N("Hylee se glisse sous la couverture. Remerii pose ses bijoux près de vos livres, puis vous embrasse tous deux avant de choisir une place qui pourra changer demain. Aucun vêtement n’est rassemblé pour partir.")],
      ],
      intersexe: [
        [N("Hylee installe sur l’étagère un galet rapporté de la promenade. Remerii le soulève, essuie la poussière et glisse dessous un morceau de tissu avant de le reposer. Elle vient d’admettre, sans discours, que cette trace peut rester chez vous. Hylee observe ce geste avec une douceur qui protège son aveu silencieux."), P("Il faudra garder de la place pour ce que vous laisserez encore.")],
        [N("Hylee embrasse Remerii devant l’étagère. Vous les rejoignez ; votre reflet se mêle aux leurs dans la vitre sombre. Remerii garde une main sur la taille de Hylee et vous attire de l’autre. Leur baiser s’ouvre à votre corps entier, à votre poitrine comme aux deux formes visibles de votre désir.")],
        [N("Vous gagnez la chambre en laissant des traces dans chaque pièce : manteau sur le dossier, tunique près de la porte, bijoux entre deux livres. Hylee emporte la lampe, Remerii la couverture. Le trajet fait du logis entier la scène du désir, plutôt qu’un simple passage vers un lit sans histoire.")],
        [N("Dans la lumière nocturne, Hylee et Remerii se déshabillent l’une l’autre. Les marques de Hylee passent sous la bouche de Remerii ; sa cicatrice reçoit les lèvres de Hylee. Elles se regardent, nues et familières, puis vous tendent leurs mains pour accueillir votre anatomie sans en faire la condition de votre place.")],
        [N("Hylee s’agenouille devant vous. Sa bouche entoure votre désir pendant que Remerii embrasse votre poitrine et glisse ses doigts dans votre chaleur. Vous caressez Remerii ; elle touche Hylee entre les cuisses. Chaque réaction transforme les gestes reçus par les deux autres, et aucune partie de votre corps n’est laissée en attente.")],
        [N("Vous étendez Hylee sur le dos. Remerii vient entre ses cuisses ; vous restez près de son visage pendant que ses mains continuent sur votre désir et dans votre chaleur. Votre bouche trouve Remerii, sa langue trouve Hylee, et Hylee garde le lien avec vous par ses baisers et par les deux rythmes qu’elle entretient.")],
        [N("Hylee jouit entre vos attentions et ramène Remerii pour l’embrasser. Elles vous allongent ensuite. Hylee reprend votre désir avec sa bouche, Remerii poursuit profondément en vous ; vos mains restent entre leurs cuisses. Leur propre désir continue l’une contre l’autre au-dessus de votre ventre, jamais suspendu à votre seul plaisir.")],
        [N("Votre orgasme traverse les deux foyers de votre corps sous leurs gestes réunis. Remerii jouit contre votre main, embrassée par Hylee ; Hylee se presse contre votre cuisse jusqu’à son propre abandon. Les trois plaisirs se chevauchent, puis retombent dans une étreinte où aucune personne ne devient l’après des deux autres.")],
        [N("Après, Hylee repose contre la poitrine de Remerii, leurs mains jointes. Vous vous blottissez contre elles et partagez l’eau. La chambre et les livres composent l’image d’un lieu habité. Aucun inventaire de votre corps n’est dressé ; seules demeurent les attentions que vous voulez retrouver ici.")],
        [H("Le galet reste."), R("Oui."), P("Et vous ?"), N("Hylee se glisse sous la couverture. Remerii pose ses bijoux près de vos livres, puis vous embrasse toutes deux avant de choisir une place qui pourra changer demain. Leurs vêtements dispersés répondent avant leurs mots.")],
      ],
    },
    ellipse: [
      [N("Hylee pose sur l’étagère un galet de la promenade. Remerii le protège d’un morceau de tissu au lieu de l’enlever.")],
      [P("Gardons de la place pour ce que vous laisserez ici."), R("Hylee colonise par les oublis."), H("Tu viens de fortifier mon territoire."), N("Leur baiser interrompt le débat.")],
      [N("Vous les rejoignez devant la vitre sombre. Trois reflets s’y rapprochent avant que Hylee n’emporte la lampe vers la chambre.")],
      [N("Les vêtements jalonnent le logis. Chaque pièce conserve une trace qui affirme qu’aucune de vous ne prépare déjà le départ.")],
      [N("Nues dans la lumière bleue, Hylee et Remerii retrouvent leurs cicatrices et leurs habitudes, puis ouvrent entre elles une place qui engage tout votre corps.")],
      [N("Le plaisir change plusieurs fois de centre. Deux personnes soutiennent toujours la troisième, jusqu’à ce que les trois abandons se rejoignent dans les mêmes draps.")],
      [H("Le galet reste."), R("Oui."), P("Et vous ?"), N("Hylee se glisse sous la couverture tandis que Remerii pose ses bijoux près de vos livres.")],
      [N("La lampe s’éteint sur un logis marqué par trois présences. Personne ne promet une place fixe ; toutes trois promettent de revenir la choisir.")],
    ],
  },
];

export const HYLEE_REMERII_HOME_ROUTES = manualHRRoutes(CONTEXT, seeds);
