import type { AmbientDialogue } from "./ambient-dialogues";
import type { ChoiceData, DialogueLine, Effects, StatKey } from "./game-data";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const H = (text: string, mood = "soft"): DialogueLine => ({ speaker: "Hylee", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });
const Q = (id: string, text: string, stat: StatKey, response: DialogueLine[], effects: Effects): ChoiceData => ({
  id, text, stat, response, effects: { ...effects, stats: { [stat]: 1 } },
});
const S = (id: string, title: string, prompt: string, choices: ChoiceData[], options: Partial<AmbientDialogue> = {}): AmbientDialogue => ({ id, title, prompt, choices, mood: "soft", ...options });

// Chaque réponse possède sa propre fin : aucune clôture commune ne lui ajoute
// une action contraire au choix du joueur. Les anciens identifiants persistent.
export const HYLEE_AMBIENT_LINES: AmbientDialogue[] = [
  S("hylee-flocon", "Six branches, pas une de plus", "Un flocon grand comme une pièce tourne au-dessus de la paume d’Hylee. Elle le penche vers vous. « Regarde celui-là ! Il avait six branches. Maintenant, il en a… Attends, arrête de tourner ! »", [
    Q("hyl-flocon-a", "« Il essaie de t’empêcher de compter. »", "audace", [H("Très malin. Je peux faire pareil quand Remerii me demande combien d’exercices j’ai terminés.", "teasing"), N("Elle fait tourner le flocon plus vite, puis le laisse retomber sur sa manche."), H("Ah. Elle verrait vite la différence : lui, au moins, il a fini quelque chose.", "teasing")], { affection: 3 }),
    Q("hyl-flocon-r", "Attendre qu’il ralentisse pour compter ses branches avec elle.", "resonance", [N("Vous comptez à voix basse. Hylee rapproche sa paume et retient son souffle."), H("Six ! C’est l’ombre qui m’en ajoutait une."), N("Elle tourne le flocon face à la lumière pour vérifier, puis vous montre l’ombre au sol.")], { trust: 3 }),
    Q("hyl-flocon-s", "Lui proposer de le poser sur votre manche sombre.", "sangFroid", [H("Ne bouge pas. Juste une seconde."), N("Le flocon se pose sur le tissu. Une pointe se casse aussitôt ; Hylee ouvre la bouche, puis rit."), H("Bon. Cinq. Celui-là, on peut le compter sans discuter.", "teasing")], { affection: 2, trust: 1 }),
  ], { locations: ["miraldas", "echo-clearing"] }),

  S("hylee-tartelette", "Le partage de la dernière", "Hylee ouvre une boîte : il reste une tartelette aux baies et beaucoup de miettes. « Je t’en avais gardé une. Enfin… Je croyais qu’il en restait deux. Tu as un couteau ? »", [
    Q("hyl-tarte-a", "Proposer qu’elle garde les baies et vous la pâte.", "audace", [H("C’est un très mauvais partage. Accepte vite avant que je change d’avis.", "teasing"), N("Elle commence à détacher une baie, regarde la pâte qui vient avec et abandonne le tri."), H("Tiens. La moitié. Tu aurais mis des miettes partout pour rien.")], { affection: 3 }),
    Q("hyl-tarte-l", "Couper deux parts et la laisser choisir.", "lucidite", [N("Hylee compare les deux parts, puis fait pivoter la boîte."), H("Celle-ci. Non, l’autre. Attends, tu as coupé une baie exactement au milieu !"), N("Elle choisit enfin une moitié et la mange avant de pouvoir hésiter encore.")], { trust: 2, affection: 1 }),
    Q("hyl-tarte-r", "Tapoter la croûte pour trouver où elle se cassera proprement.", "resonance", [N("Un petit craquement vous indique le bord le plus friable. Hylee tient la boîte pendant que vous séparez les parts."), H("Oh, bien ! Moi, j’avais surtout prévu de casser le fond."), N("Elle récupère une baie échappée et la pose sur votre morceau.")], { trust: 2, affection: 2 }),
  ], { locations: ["algratal", "miraldas"], mood: "teasing" }),

  S("hylee-baton", "Jusqu’à dix", "Hylee tient son bâton immobile devant elle. Du givre remonte lentement le bois, puis déborde sur son pouce. Elle secoue la main. « Remerii a dit : juste le bâton. Pas le bâton et tout ce qui le touche. Tu peux compter jusqu’à dix ? »", [
    Q("hyl-baton-r", "Compter en surveillant la progression du givre.", "resonance", [N("À six, une traînée blanche revient vers ses doigts. Vous la lui signalez ; Hylee interrompt aussitôt le sort."), H("Six, c’est déjà mieux. J’avais eu tout le poignet avant que tu arrives.", "determined"), N("Elle essuie le bois avec un chiffon avant de réessayer.")], { trust: 3 }),
    Q("hyl-baton-l", "Lui demander ce qu’elle doit regarder pendant l’exercice.", "lucidite", [H("Le bord du givre. Sauf que je regarde aussi si tu comptes. Et si quelqu’un passe."), N("Elle se tourne vers un mur vide et vous demande de rester sur le côté."), H("Voilà. Maintenant, même si tu fais des grimaces, je ne les verrai pas.", "teasing")], { trust: 3, affection: 1 }),
    Q("hyl-baton-a", "Compter les dix nombres beaucoup trop vite.", "audace", [H("Non ! Ça ne marche pas comme ça !", "surprised"), N("Le rire lui fait baisser son bâton. Elle arrête le givre avant qu’il touche le sol."), H("Recommence. Avec des espaces entre les nombres, cette fois.", "teasing")], { affection: 3 }),
  ], { locations: ["miraldas"], mood: "determined" }),

  S("hylee-foule", "De l’autre côté des paniers", "La place d’Al’Gratal s’est remplie de porteurs et de clients. Hylee monte sur la pointe des pieds pour chercher son chemin. « Il y avait un passage là il y a une minute. Maintenant, il y a un homme et six paniers. On attend le septième ou on contourne ? »", [
    Q("hyl-foule-s", "Attendre qu’un porteur ait fini de traverser.", "sangFroid", [N("Vous vous écartez sous un auvent. Hylee suit des yeux le panier qui oscille au-dessus des autres."), H("S’il tombe, je refuse d’être dessous."), N("Le porteur passe sans rien perdre. Hylee se glisse dans l’espace libéré et vous indique de la suivre.")], { trust: 3, affection: 1 }),
    Q("hyl-foule-a", "Demander solennellement le passage pour deux voyageurs sans panier.", "audace", [N("Un marchand rit et retire une corbeille du chemin. Hylee le remercie avant de vous dépasser."), H("Tu devrais essayer devant les gardes. Non, attends… N’essaie pas devant les gardes.", "teasing"), N("Elle vous entraîne du geste vers la rue où la foule s’éclaircit.")], { affection: 3 }),
    Q("hyl-foule-l", "Repérer la ruelle qui longe les étals.", "lucidite", [H("Oui, par là. Je préfère éviter la grande porte aujourd’hui."), N("Elle vérifie que vous suivez, puis ralentit devant un étal de rubans."), H("Ah ! C’était donc ici. J’ai cherché cette boutique hier dans trois mauvaises rues.")], { trust: 4 }),
  ], { locations: ["algratal"] }),

  S("hylee-plume", "Une livraison de Medig", "Hylee retire une plume blanche de la boucle de son sac. « Medig est venue, a marché sur mes affaires et est repartie. Voilà tout ce qu’elle m’a laissé. J’aurais préféré qu’elle rapporte le lacet qu’elle a emporté hier. »", [
    Q("hyl-plume-a", "« C’est peut-être le paiement du lacet. »", "audace", [H("Alors elle me doit encore l’autre moitié. Il était presque neuf.", "teasing"), N("Elle coince la plume derrière son oreille, puis la retire quand elle lui chatouille la joue."), H("Et son paiement ne tient même pas en place.", "teasing")], { affection: 3 }),
    Q("hyl-plume-l", "Examiner si la boucle du sac peut retenir le prochain lacet.", "lucidite", [N("Vous passez le lacet restant sous la sangle. Hylee tire dessus pour tester le nœud."), H("Elle va essayer de partir avec le sac entier."), N("Elle ferme quand même la boucle et range la plume dans une poche séparée.")], { trust: 2, affection: 1 }),
    Q("hyl-plume-r", "Souffler doucement pour maintenir la plume en l’air.", "resonance", [H("Attends, à mon tour !", "teasing"), N("Hylee souffle trop fort. La plume monte hors de portée, puis tombe derrière son col."), H("Ah ! Elle pique ! Tu peux regarder où elle est ?", "surprised"), N("Vous lui montrez le bout qui dépasse. Elle récupère la plume et la range avant un nouvel essai.")], { trust: 2, affection: 2 }),
  ]),

  S("hylee-mer", "La vague suivante", "Depuis les remparts de Forthaven, Hylee regarde l’eau éclater contre les rochers. Une rafale lui envoie des embruns au visage. Elle essuie son nez. « D’accord, je l’ai vue. Elle n’avait pas besoin de monter jusqu’ici. »", [
    Q("hyl-mer-a", "Annoncer que la prochaine vague sera beaucoup plus discrète.", "audace", [N("Une gerbe d’eau dépasse la précédente. Vous reculez ensemble."), H("Tu la connais très mal, ta vague.", "teasing"), N("Elle choisit un poste derrière un créneau et vous fait une place pour surveiller la suivante.")], { affection: 3 }),
    Q("hyl-mer-s", "Lui proposer le côté abrité du rempart.", "sangFroid", [H("Bonne idée. Mes cheveux ont déjà eu assez d’eau."), N("Le mur coupe le vent. Hylee s’y adosse en cherchant un coin sec de sa manche."), H("On entend encore tout. C’est mieux comme ça.")], { trust: 3 }),
    Q("hyl-mer-r", "Lui tendre votre gourde pour chasser le goût du sel.", "resonance", [H("Merci. J’en ai jusque sur les lèvres."), N("Elle boit, referme soigneusement la gourde et vous la rend."), H("Je voulais savoir quel goût avait la mer. Maintenant, je sais. On peut chercher quelque chose de sucré ?", "teasing")], { trust: 2, affection: 2 }),
  ], { locations: ["forthaven"], mood: "teasing" }),

  S("hylee-livre", "La marge déborde", "Hylee vous montre un manuel annoté par Remerii. « Ici, elle a corrigé la phrase. Là, elle a corrigé sa correction. Et là… Je crois qu’elle se dispute avec elle-même. Tu arrives à lire le tout petit mot ? »", [
    Q("hyl-livre-a", "Proposer une nouvelle marge sur une feuille volante.", "audace", [H("Oui ! Avec une flèche, pour qu’elle puisse continuer.", "teasing"), N("Hylee glisse votre feuille entre les pages, puis y écrit “suite de la dispute”."), H("Elle saura que c’est moi. Toi, tu dessines les flèches plus droites.", "teasing")], { affection: 3 }),
    Q("hyl-livre-l", "Suivre la phrase depuis le début pour déchiffrer le mot.", "lucidite", [N("Vous tournez le livre vers la lumière. Le mot finit par se distinguer : “vérifier”."), H("Tout ça pour dire qu’elle n’est pas sûre !"), N("Elle pose un marque-page au bon endroit, prête à demander à Remerii ce qu’elle a trouvé.")], { trust: 2, affection: 1 }),
    Q("hyl-livre-s", "Lui proposer de demander à Remerii à son retour.", "sangFroid", [H("Oui. Sinon, on va devoir ajouter nos propres corrections."), N("Elle ferme le livre en gardant son doigt dans la page, puis cherche un marque-page dans ses poches."), H("Tiens le livre une seconde. Je suis presque sûre d’en avoir un qui n’est pas un reçu.")], { trust: 3 }),
  ], { locations: ["miraldas", "algratal"], minStage: 1, mood: "teasing" }),

  S("hylee-danse", "Le banc est dans le chemin", "Hylee répète un pas de danse, heurte le pied d’un banc et s’arrête net. Elle vous aperçoit. « Le banc a bougé. Tu l’as vu, toi aussi ? »", [
    Q("hyl-danse-a", "Accuser le banc avec le plus grand sérieux.", "audace", [H("Merci. Enfin un témoin fiable.", "teasing"), N("Elle pousse le banc du talon et refait le pas à côté."), H("Voilà. Beaucoup mieux quand personne ne triche.", "teasing")], { affection: 4 }),
    Q("hyl-danse-s", "Éloigner le banc pendant qu’elle reprend son mouvement.", "sangFroid", [N("Hylee recommence plus lentement, en comptant sur ses doigts."), H("Un, deux… Ah ! C’est là que je tournais trop tôt."), N("Elle réussit le tour suivant et vous adresse un sourire avant d’essayer dans l’autre sens.")], { trust: 2, affection: 2 }),
    Q("hyl-danse-l", "Lui demander de vous montrer le départ du pas.", "lucidite", [H("Le pied droit. Enfin, mon droit. Mets-toi dans le même sens, ce sera plus simple."), N("Vous essayez côte à côte. Hylee inverse elle-même les pieds au second mouvement."), H("Bon. Repartons du début. On va finir par l’avoir.", "teasing")], { trust: 3, affection: 2 }),
  ], { periods: ["apres-midi", "soirée"], minStage: 1, mood: "teasing" }),

  S("hylee-chaleur", "Le thé attendra", "Hylee effleure sa tasse fumante. Une pellicule de glace se forme sur le thé. Elle retire vite les doigts et soupire. « Je voulais le refroidir un peu. Un tout petit peu. Maintenant, la cuillère tient debout. »", [
    Q("hyl-tasse-r", "Écouter le craquement de la glace quand elle remue la cuillère.", "resonance", [N("La croûte se fend au bord de la tasse. Vous lui indiquez le passage ; Hylee dégage sa cuillère."), H("Voilà. Je peux au moins récupérer ça."), N("Elle pousse la tasse au soleil et surveille les morceaux qui flottent à la surface.")], { trust: 3 }),
    Q("hyl-tasse-a", "Lui demander si le thé se mange avec du pain.", "audace", [H("Tu peux essayer, mais je veux voir ta tête.", "teasing"), N("Elle récupère un petit éclat avec la cuillère et y goûte avant vous."), H("Non. Il faut attendre. Beaucoup trop de thé, pas assez de tout le reste.", "teasing")], { affection: 3 }),
    Q("hyl-tasse-s", "Ajouter un peu d’eau chaude de la théière.", "sangFroid", [H("Doucement. Sinon, je vais vouloir recommencer à le refroidir."), N("Vous versez juste assez pour libérer les bords. Hylee teste une petite gorgée."), H("Là, c’est bon. Je pose mes mains ici, et je bois avant d’avoir une autre idée.")], { trust: 4 }),
  ], { locations: ["miraldas", "echo-clearing"], minStage: 1, mood: "surprised" }),

  S("hylee-chanson", "Le couplet oublié", "Hylee fredonne en rangeant son sac, puis bute sur le même vers. « Il y avait un capitaine, un tonneau et… des chaussettes ? Je l’ai entendue cent fois à l’auberge. Je ne pensais pas avoir besoin de retenir les paroles. »", [
    Q("hyl-chanson-a", "Inventer la mésaventure des chaussettes dans le tonneau.", "audace", [H("Non, attends, le capitaine doit les retrouver avant de boire !", "teasing"), N("Elle essaie votre couplet sur l’air et manque la rime en riant."), H("On va en enlever deux. Des chaussettes. Il y a trop de mots.", "teasing")], { affection: 4 }),
    Q("hyl-chanson-l", "Lui demander ce qui venait juste avant.", "lucidite", [H("Il cherchait son bateau… Ah ! Ses bottes. Pas ses chaussettes."), N("Elle reprend deux lignes plus haut, retrouve la suite et tape le rythme sur son sac."), H("C’est ça ! Maintenant, il faut que je la chante avant de l’oublier.")], { trust: 3, affection: 1 }),
    Q("hyl-chanson-s", "Battre doucement la mesure pendant qu’elle cherche.", "sangFroid", [N("Hylee fredonne la mélodie à la place du vers manquant. Vous continuez jusqu’au refrain."), H("Garde ce rythme. Je vais essayer depuis le début."), N("Elle reprend plus bas, assez près de vous pour que vous entendiez sans couvrir les bruits alentour.")], { trust: 3, affection: 1 }),
  ], { minStage: 1, mood: "teasing" }),

  S("hylee-bouton", "Un bouton presque à sa place", "Hylee recoud le bouton de sa cape. Elle tire le fil, essaie de fermer le col et grimace. « Trop haut. De presque rien. Mais apparemment, presque rien suffit pour m’étrangler. »", [
    Q("hyl-bouton-l", "Marquer le bon emplacement avant de défaire le fil.", "lucidite", [N("Elle ferme le tissu à la bonne hauteur pendant que vous faites une petite marque."), H("Là. Je vais la regarder cette fois, ma marque."), N("Hylee découd le bouton et l’aligne soigneusement avant le premier point.")], { trust: 4 }),
    Q("hyl-bouton-a", "Déclarer le bouton coupable d’avoir grimpé pendant la couture.", "audace", [H("Je le savais. Il avait l’air trop content, dans sa boîte.", "teasing"), N("Elle coupe le fil, rattrape le bouton entre ses genoux et le montre du doigt."), H("Et maintenant, il essaie de s’enfuir ! Passe-moi la boîte.", "teasing")], { affection: 3 }),
    Q("hyl-bouton-r", "Tenir le tissu à plat pendant qu’elle replace le bouton.", "resonance", [H("Un peu plus bas. Oui. Reste comme ça."), N("Elle défait les derniers points, reprend la couture et vous laisse lâcher avant d’essayer le col."), H("Je peux tourner la tête ! Je vais garder cette version.", "teasing")], { trust: 3, affection: 1 }),
  ], { minStage: 1, mood: "determined" }),

  S("hylee-statue", "Le monsieur sans plaque", "Une statue garde l’entrée d’une cour. Hylee se penche pour lire sa plaque, entièrement effacée. « Tu crois qu’il a fait quoi ? À part perdre son nom et garder un pigeon sur la tête. »", [
    Q("hyl-statue-a", "Lui inventer une carrière de goûteur de tartes.", "audace", [H("C’est pour ça qu’il tient une assiette !", "teasing"), N("Elle contourne la statue et découvre que l’assiette est un bouclier."), H("Ah. Les tartes étaient peut-être très mauvaises.", "teasing")], { affection: 4 }),
    Q("hyl-statue-l", "Chercher un détail encore lisible dans la pierre.", "lucidite", [N("Vous trouvez une petite fleur gravée au bord du socle. Hylee s’accroupit pour la regarder."), H("Elle est sur son manteau aussi. Il faudrait demander à quelqu’un."), N("Elle en dessine une copie dans son carnet, avec un pigeon minuscule à côté.")], { trust: 3, affection: 1 }),
    Q("hyl-statue-r", "Prêter à la statue une voix grave pour chasser son pigeon.", "resonance", [H("Plus fâché. Il en a sûrement assez.", "teasing"), N("Le pigeon reste immobile pendant votre discours, puis s’envole au rire d’Hylee."), H("Oh ! Pardon, monsieur. Je ne voulais pas chasser votre coiffure.", "teasing")], { trust: 3 }),
  ], { locations: ["algratal", "miraldas"], minStage: 1, mood: "teasing" }),

  S("hylee-pluie", "Le coin encore sec", "L’averse surprend Hylee pendant qu’elle range un papier. Elle le glisse sous sa cape et remonte son col. « Mon dos est déjà mouillé. Si je cours très vite, tu crois que je peux sauver le devant ? »", [
    Q("hyl-pluie-r", "Écouter où les gouttes frappent moins fort pour chercher un abri.", "resonance", [N("Vous repérez un rebord où l’eau tombe en rideau devant une bande de sol sec. Hylee s’y faufile."), H("Viens. Il reste de la place si je pousse mon sac."), N("Elle déplie le papier : un coin est mouillé, mais l’encre tient encore.")], { trust: 4 }),
    Q("hyl-pluie-s", "Lui prêter votre cape pour protéger son papier jusqu’à l’abri.", "sangFroid", [H("Juste pour le papier. On sera deux à sécher nos capes après."), N("Elle protège ses notes contre elle et vous suit sous un toit. Une fois au sec, elle vous rend la cape."), H("Merci. Remerii avait même écrit assez gros pour que je puisse me relire.")], { trust: 3, affection: 2 }),
    Q("hyl-pluie-a", "Lancer la course jusqu’au prochain abri.", "audace", [H("Tu pars avant de dire où !", "surprised"), N("Elle vous rattrape en évitant une flaque et arrive sous le toit avec une botte de plus mouillée."), H("On dira que j’ai gagné. Toi, tu avais choisi l’arrivée.", "teasing")], { affection: 4 }),
  ], { minStage: 1 }),

  S("hylee-nom", "Elle a un prénom", "Deux apprentis de Mir’Aldas passent en parlant de « la cryomancienne humaine ». Hylee se retourne après eux. « Ils m’ont posé six questions ce matin. Ils auraient pu commencer par mon nom. »", [
    Q("hyl-nom-l", "Lui demander si elle connaît les leurs.", "lucidite", [H("L’un des deux. L’autre parlait tout le temps, je n’ai pas entendu."), N("Elle cherche encore les apprentis du regard."), H("Je lui demanderai. Après, on pourra arrêter de dire “l’autre”.")], { trust: 4, affection: 1 }),
    Q("hyl-nom-a", "Proposer une présentation avec beaucoup trop de titres.", "audace", [H("Non, pas “maîtresse des hivers” ! Ils vont revenir avec leurs questions.", "teasing"), N("Elle vous coupe avant le troisième titre, mais sourit encore en reprenant son sac."), H("Hylee, c’est bien. Ça prend moins de temps à dire.")], { affection: 3, trust: 1 }),
    Q("hyl-nom-s", "Lui proposer de continuer la promenade.", "sangFroid", [H("Oui. Ils peuvent attendre demain pour la septième question."), N("Elle tourne vers le jardin et ralentit devant un parterre."), H("Regarde celles-ci. Elles sont toutes petites. On les avait vues, la dernière fois ?")], { trust: 4 }),
  ], { locations: ["miraldas"], minStage: 2, mood: "determined" }),

  S("hylee-maison", "Ce qui reste sur l’étagère", "Hylee sort de son sac une petite boîte en bois, l’ouvre, puis la referme. « Je voulais laisser mon nécessaire à couture sur l’étagère, à Mir’Aldas. Mais si j’en ai besoin sur la route ? Remerii a dit que j’avais posé la même question pour six objets. »", [
    Q("hyl-maison-l", "Séparer de quoi réparer une couture du reste de la boîte.", "lucidite", [N("Hylee choisit une aiguille, du fil et un bouton de rechange."), H("Deux boutons. Je les perds plus vite que les aiguilles."), N("Elle emballe le petit nécessaire dans un tissu et met la boîte vide à part pour leur prochain retour.")], { trust: 4, affection: 1 }),
    Q("hyl-maison-a", "Lui demander si elle compte emporter l’étagère aussi.", "audace", [H("Si tu la portes, je veux bien.", "teasing"), N("Elle mesure votre dos du regard, puis éclate de rire avant votre réponse."), H("Non. On va commencer par enlever les trois morceaux de ficelle dont je ne fais rien.")], { affection: 3, trust: 1 }),
    Q("hyl-maison-r", "Secouer doucement le sac pour repérer ce qui cogne.", "resonance", [N("Un tintement vous fait retrouver une cuillère sous la boîte. Hylee la récupère, surprise."), H("Je l’ai cherchée partout ! J’accusais Medig."), N("Elle range la cuillère avec sa gamelle et réorganise la poche jusqu’à ce que plus rien ne cogne.")], { trust: 4 }),
  ], { minStage: 2 }),

  S("hylee-silence", "Une minute sur le banc", "Hylee s’est assise à l’écart avec son sac sur les genoux. À votre approche, elle le pose à ses pieds. « Tu peux t’asseoir. Je suis juste fatiguée. J’ai déjà raconté ma journée deux fois, et la deuxième était moins intéressante. »", [
    Q("hyl-silence-s", "Vous asseoir sans lui demander de recommencer.", "sangFroid", [N("Hylee étire les jambes et ferme un instant les yeux. Vous regardez les passants."), H("Merci. J’avais besoin de ne plus marcher."), N("Elle rouvre les yeux au bruit d’un chariot, puis se cale plus confortablement sur le banc.")], { trust: 4, affection: 2 }),
    Q("hyl-silence-l", "Lui demander si elle a pensé à manger.", "lucidite", [H("Oui. Enfin… J’ai acheté quelque chose."), N("Elle fouille son sac, en sort un paquet intact et vous regarde avec un sourire embarrassé."), H("Voilà. J’avais fait la première moitié. Tu en veux ?")], { trust: 4, affection: 1 }),
    Q("hyl-silence-a", "Proposer de raconter votre journée en trois mots.", "audace", [H("D’accord. Mais je compte.", "teasing"), N("Votre troisième mot la fait rire. Elle en propose trois à son tour, puis en ajoute un quatrième."), H("Celui-là était nécessaire. Tu peux en rajouter un aussi.", "teasing")], { affection: 3, trust: 2 }),
  ], { minStage: 2, periods: ["soirée"] }),

  S("hylee-jalousie", "Le second paquet", "Hylee vous aperçoit après un détour et replie vite un petit paquet. Un autre est déjà ouvert sur ses genoux. « Ah, te voilà. Je pensais que tu passerais plus tôt. J’ai commencé sans toi. »", [
    Q("hyl-jal-l", "Lui demander si la place à côté d’elle est encore libre.", "lucidite", [H("Oui. Le paquet ne l’avait pas réservée pour quelqu’un d’autre."), N("Elle vous tend la portion intacte et déplace son sac pour vous laisser vous asseoir."), H("Il est froid maintenant. Tu me raconteras ce qui t’a retenu pendant qu’on mange ?")], { trust: 5, affection: 2 }),
    Q("hyl-jal-s", "Expliquer que vous devez repartir bientôt.", "sangFroid", [N("Hylee regarde le paquet qu’elle venait d’avancer, puis en resserre le nœud."), H("Prends-le quand même. Moi, j’ai déjà le mien."), P("Merci. Je ne peux pas rester longtemps."), H("Je sais. Raconte-moi au moins où tu cours.")], { trust: 5, affection: 2 }),
    Q("hyl-jal-a", "« Tu m’as quand même gardé le plus gros. »", "audace", [H("Ils avaient la même taille avant que je commence.", "teasing"), N("Vous regardez les deux paquets. Hylee cède et vous tend celui qu’elle n’a pas ouvert."), H("Bon, peut-être. Assieds-toi avant que je corrige.", "teasing")], { affection: 4, desire: 2 }),
  ], { minStage: 3 }),

  S("hylee-demain", "Avant le petit déjeuner", "Hylee replie son écharpe en regardant les derniers passants. « Remerii veut qu’on parte tôt demain. Elle a dit “avant le petit déjeuner”. Je lui ai demandé lequel des deux elle comptait supprimer. Elle n’a pas répondu. »", [
    Q("hyl-demain-s", "L’aider à préparer de quoi manger en chemin.", "sangFroid", [N("Vous répartissez le pain et les fruits dans deux petits paquets. Hylee vérifie les nœuds."), H("Voilà. Je lui donnerai le sien avant qu’elle m’explique qu’on est en retard."), N("Elle place le repas tout en haut du sac, à portée de main.")], { trust: 4, affection: 3 }),
    Q("hyl-demain-a", "Suggérer d’appeler le repas “provisions immédiates”.", "audace", [H("Oui. Elle pourra difficilement être contre des provisions.", "teasing"), N("Hylee répète l’expression d’une voix sérieuse, puis secoue la tête."), H("Non, je vais rire avant de finir. Je lui donnerai juste du pain.", "teasing")], { affection: 4 }),
    Q("hyl-demain-r", "Écouter la cloche du soir avant d’estimer combien de temps reste pour les courses.", "resonance", [N("Les derniers coups résonnent au loin. Hylee compte les boutiques encore éclairées."), H("On peut encore trouver quelque chose. Viens, celle du coin n’a pas fermé."), N("Elle ramasse son écharpe et vous précède, décidée à régler la question avant le matin.")], { trust: 4, affection: 3 }),
  ], { locations: ["algratal", "miraldas"], minStage: 4, periods: ["soirée"] }),

  S("hylee-petit-choix", "Le détour qui sent les pommes", "Hylee s’arrête devant un embranchement. « À gauche, ça sent les pommes. À droite, je n’ai jamais regardé. Si on prend à gauche, je vais encore dire demain que je ne sais pas ce qu’il y a à droite. »", [
    Q("hyl-choix-l", "Lui proposer le chemin inconnu, puis les pommes au retour.", "lucidite", [H("D’accord. Mais si ça fait un grand tour, on achète quelque chose avant."), N("Elle avance de quelques pas à droite, repère une ouverture dans la haie et se retourne."), H("Viens voir ! Je crois qu’on aperçoit déjà où ça rejoint.")], { trust: 3 }),
    Q("hyl-choix-a", "Lancer une pièce pour départager les chemins.", "audace", [N("La pièce tombe pour la gauche. Hylee regarde encore le chemin de droite."), H("On peut recommencer ?"), P("Tu as déjà choisi, non ?"), H("Oui. Garde la pièce pour les pommes.", "teasing")], { affection: 3 }),
    Q("hyl-choix-s", "Choisir les pommes et garder le détour pour une autre promenade.", "sangFroid", [H("Tu sais parler aux gens qui ont faim."), N("Elle prend à gauche, puis s’arrête pour repérer l’embranchement derrière elle."), H("La pierre plate. Voilà. La prochaine fois, je saurai où tourner.")], { trust: 3, affection: 1 }),
  ], { locations: ["algratal", "miraldas", "forestier", "echo-clearing"] }),

  S("hylee-temperature", "Le courant d’air en trop", "Hylee essaie de rafraîchir l’air autour d’une carafe. Une buée blanche déborde sur la table et elle rabat aussitôt la main. « Tu as eu froid ? Je voulais seulement garder l’eau fraîche. Pas préparer l’hiver sous le banc. »", [
    Q("hyl-temperature-s", "Lui dire que vos doigts commençaient à refroidir.", "sangFroid", [H("Ah, pardon. J’arrête là."), N("La buée se dissipe. Hylee rapproche la carafe de son côté et essuie la condensation."), H("Elle est assez fraîche pour nous deux, de toute façon. Je te sers ?")], { trust: 3 }),
    Q("hyl-temperature-r", "Lui indiquer la limite où vous sentez encore le froid.", "resonance", [N("Vous déplacez votre main au-dessus de la table. Hylee suit votre geste sans relancer son sort."), H("Jusque-là ? Je ne pensais pas que ça allait aussi loin."), N("Elle note l’écart entre la carafe et votre gobelet, puis vous sert l’eau avant qu’elle refroidisse davantage.")], { trust: 2, affection: 1 }),
    Q("hyl-temperature-a", "Réclamer un minuscule glaçon à la place de tout cet hiver.", "audace", [H("Un seul. Tu vas voir.", "determined"), N("Elle forme un petit glaçon dans sa paume et le glisse dans votre gobelet. Un second y tombe avec le premier."), H("Le deuxième était caché. Tu n’es pas obligé de le compter.", "teasing")], { affection: 3 }),
  ], { locations: ["miraldas", "echo-clearing"], mood: "surprised" }),
];
