import type { HRManualSeed } from "./hylee-remerii-intimacy-shared";
import { H, N, P, R, manualHRRoutes } from "./hylee-remerii-intimacy-shared";

const CONTEXT = "group-date-hylee-remerii-free-day";

const seeds: HRManualSeed[] = [
  {
    slug: "rire-reste",
    labels: {
      femme: "Le rire reste — suivre l’élan d’Hylee dans l’alcôve des artisans",
      homme: "Le rire reste — laisser Hylee transformer votre trouble en jeu",
      intersexe: "Le rire reste — confier à Hylee le premier mouvement de vos deux désirs",
    },
    detail: "Hylee entraîne le trio dans une alcôve inutilisée au bord de la galerie. Son rire mène la bascule, mais Remerii refuse de rester spectatrice et les deux femmes inventent ensemble la suite.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    tendre: [
      [N("Hylee découvre derrière les échoppes une alcôve où les artisans rangent leurs coussins pendant les jours de pluie. Elle tire le rideau à moitié, s’assied entre Remerii et vous, puis pose la boîte bancale sur ses genoux comme si elle avait trouvé une excuse officielle pour rester.")],
      [H("On peut attendre que la confiture sèche.", "teasing"), N("Remerii observe le sachet, le rideau et le sourire d’Hylee."), R("Cette justification est techniquement absurde."), H("Mais tu es encore assise.")],
      [N("Hylee vous embrasse d’abord, encore amusée, puis tourne naturellement la tête vers Remerii. Leur second baiser dure davantage. Vous voyez la main de Remerii retrouver la taille d’Hylee avec une facilité acquise bien avant cette journée.")],
      [N("Elles vous rappellent dans leur mouvement en prenant chacune une de vos mains. Hylee guide la vôtre contre la joue de Remerii ; Remerii dépose l’autre sur le cœur rapide d’Hylee et sourit lorsqu’elle sent sa prétendue désinvolture trembler.")],
      [N("Les baisers circulent sans ordre. Hylee se glisse contre votre épaule pendant que Remerii embrasse sa tempe, puis vous ramène, Hylee et vous, jusqu’à ce que les trois fronts se touchent et que le rire devienne un souffle partagé.")],
      [N("Le plaisir vient par la lenteur des caresses, la chaleur des paumes et les corps qui trouvent assez de place sur les coussins. Hylee serre la main de Remerii au moment où un frisson la traverse, et Remerii garde votre bouche contre la sienne lorsque le vôtre répond.")],
      [R("Tu avais donc un programme.", "soft"), H("Seulement depuis le banc."), N("Hylee embrasse son nez ; Remerii essaie de rester sévère avant de céder à un rire silencieux contre sa joue.")],
      [N("Vous restez serrés derrière le rideau entrouvert. La boîte repose toujours de travers, la confiture n’a jamais été le vrai problème et aucun de vous ne cherche immédiatement la prochaine destination.")],
    ],
    suggestif: [
      [N("Hylee vous fait bifurquer derrière la galerie vers une alcôve de repos vide. Elle tire le rideau, pose les provisions à l’abri et s’installe sur les coussins, les joues encore colorées par les baisers du banc.")],
      [H("On a dit qu’on ne prévoyait rien.", "teasing"), R("Cela n’interdit pas de fermer correctement ce rideau."), N("Remerii en noue le cordon, puis revient assez près pour que Hylee puisse la retenir par la ceinture.")],
      [N("Hylee ouvre votre col entre deux baisers. Elle se détourne aussitôt pour faire de même avec Remerii, qui lui répond en libérant ses cheveux et en embrassant la peau découverte sous son oreille.")],
      [N("Vous les regardez quelques secondes : Hylee sur les genoux de Remerii, leurs mains sous les étoffes, leur complicité plus ancienne que votre présence. Puis Hylee tend le bras et vous attire dans leur échange sans l’interrompre.")],
      [N("Les vêtements glissent juste assez pour que trois chaleurs se rencontrent. Remerii guide une main d’Hylee sur vous tandis qu’elle reçoit la vôtre ; Hylee alterne les baisers, refusant que l’une des deux personnes demeure hors de son jeu.")],
      [N("Le rythme devient plus pressant derrière le rideau. Les caresses restent hors du regard de la galerie, mais vos souffles disent clairement le plaisir reçu et rendu. Hylee atteint le sommet contre Remerii, puis toutes deux vous gardent entre leurs corps jusqu’à votre propre abandon.")],
      [H("Je crois que la confiture a eu le temps de sécher.", "breathless"), R("Je ne vérifierai pas tout de suite."), N("Remerii embrasse sa bouche encore ouverte avant de revenir vers vous avec une tendresse moins méthodique que d’ordinaire.")],
      [N("Vous remettez les vêtements en ordre sans retrouver immédiatement une distance convenable. Hylee partage la dernière pâtisserie entre trois bouches ; Remerii récupère la boîte et laisse le rideau fermé quelques minutes de plus.")],
    ],
    explicite: {
      femme: [
        [N("Hylee vous entraîne dans l’alcôve des artisans, tire le rideau et vous pousse doucement sur les coussins. La lumière de la galerie passe encore sous le tissu. Remerii pose les provisions hors de portée, puis revient s’asseoir derrière Hylee, déjà consciente que son rire vient de choisir une direction très précise."), H("Je n’avais rien prévu. J’ai seulement très envie de continuer.", "determined")],
        [N("Hylee se penche sur vous et ouvre votre tunique entre deux baisers. Remerii dénoue ses cheveux, embrasse sa nuque puis glisse les mains sur sa poitrine. Hylee gémit contre votre bouche sans interrompre son geste ; elle découvre vos seins, les caresse et invite Remerii à couvrir vos trois corps du même mouvement.")],
        [N("Vous attirez Remerii près de vous. Hylee se place entre vos cuisses, mais tourne la tête pour embrasser l’intérieur de la paume que Remerii vient de poser sur sa joue. Leur regard dure, ancien et tendre. Hylee vous lèche ensuite lentement, tandis que Remerii caresse ses épaules et suit le mouvement de sa langue à travers vos réactions.")],
        [N("Remerii vient s’agenouiller près de votre visage. Vous ouvrez ses cuisses et la goûtez pendant qu’elle embrasse Hylee au-dessus de votre ventre. Hylee glisse deux doigts dans votre chaleur, sa bouche toujours attentive au point sensible ; Remerii accompagne ses mouvements d’une main posée sur sa hanche, corrigeant le rythme par un simple souffle.")],
        [N("Hylee quitte un instant votre plaisir pour faire asseoir Remerii contre le mur. Elle l’embrasse, descend entre ses cuisses et vous tend la main. Vous les rejoignez : votre bouche retrouve celle d’Hylee entre deux caresses, vos doigts donnent à Remerii ce que la langue d’Hylee vient de commencer. Aucune ne prend son tour ; leurs plaisirs se répondent.")],
        [N("Remerii jouit la première, la main serrée dans vos cheveux et l’autre sur la nuque d’Hylee. Hylee remonte l’embrasser, partageant avec elle le goût resté sur ses lèvres. Vous les regardez quelques secondes se calmer l’une contre l’autre, puis elles se tournent ensemble vers vous avec la même intention devenue impossible à confondre.")],
        [N("Elles vous allongent entre elles. Remerii entre deux doigts en vous et maintient une cadence profonde ; Hylee se serre contre votre cuisse, frotte sa chaleur contre vous et garde sa langue sur votre point le plus sensible. Elles s’embrassent au-dessus de votre poitrine, chacune attentive aux réactions que provoque le geste de l’autre.")],
        [N("Votre orgasme monte sous leurs deux rythmes. Hylee sent votre cuisse se tendre et accélère contre vous ; Remerii ne change plus la pression. Vous jouissez en retenant leurs mains, et le plaisir d’Hylee suit presque aussitôt, étouffé contre la bouche de Remerii qui la garde fermement près d’elle."), P("Restez… toutes les deux.")],
        [N("Le calme revient dans un désordre de jambes et de vêtements ouverts. Hylee garde la joue sur votre ventre ; Remerii caresse son dos puis votre hanche, vérifiant sans solennité que chacune retrouve son souffle. Vous lui faites remarquer qu’elle compte encore. Elle répond qu’elle compte seulement jusqu’à trois.")],
        [H("On n’avait vraiment rien prévu.", "breathless"), R("Tu as trouvé une alcôve, fermé un rideau et déshabillé deux personnes."), H("C’est arrivé dans cet ordre, oui."), N("Vous riez ensemble. La pâtisserie passe de main en main et Hylee embrasse Remerii avant de vous donner la dernière bouchée.")],
      ],
      homme: [
        [N("Hylee vous entraîne dans l’alcôve des artisans, tire le rideau et vous fait asseoir sur les coussins. Remerii range les provisions, puis vient derrière elle. La galerie reste proche, mais le tissu, les boîtes empilées et leurs deux corps composent un refuge improvisé qui appartient encore à cette journée sans programme."), H("Je n’avais rien prévu. J’ai seulement envie de ne pas m’arrêter.", "determined")],
        [N("Hylee ouvre votre chemise et embrasse votre poitrine. Remerii libère ses cheveux, glisse les mains sous sa tunique et prend ses seins en coupe. Hylee laisse échapper un gémissement contre votre peau, puis se retourne pour l’embrasser avant de revenir défaire votre ceinture avec un sourire qui n’a plus rien d’innocent.")],
        [N("Votre membre se dresse dans la main d’Hylee. Elle l’explore lentement, suit votre souffle et embrasse son extrémité sans quitter Remerii des yeux. La mage noire s’agenouille derrière elle, caresse son ventre puis descend entre ses cuisses ; Hylee vous prend dans sa bouche au moment exact où les doigts de Remerii trouvent sa chaleur.")],
        [N("Vous gardez une main dans les cheveux d’Hylee et attirez Remerii par la nuque. Votre baiser accompagne les mouvements de sa main sur Hylee. Celle-ci accélère autour de vous, puis recule pour embrasser Remerii ; votre désir reste entre leurs paumes jointes pendant que leurs langues se retrouvent au-dessus.")],
        [N("Hylee fait asseoir Remerii contre le mur et descend entre ses jambes. Vous vous placez près d’elle, caressez sa poitrine et recevez ses indications courtes. Hylee lui donne du plaisir avec sa bouche ; Remerii vous garde dressé dans sa main et rythme vos réactions sans retirer ses yeux de la femme agenouillée devant elle.")],
        [N("Remerii jouit dans la bouche d’Hylee, ses doigts serrés autour de vous. Hylee remonte l’embrasser et leur baiser vous laisse regarder quelques secondes un désir qui existe entre elles sans vous demander d’en être le centre. Puis leurs deux mains vous attirent contre leurs corps et leur mouvement s’ouvre à nouveau.")],
        [N("Hylee s’allonge sur les coussins et vous guide entre ses cuisses. Remerii se place derrière elle, soutient sa nuque et l’embrasse pendant que vous entrez lentement en Hylee. Chacune vous indique le rythme : Hylee par ses hanches, Remerii par la main qu’elle garde sur votre bassin et les baisers qu’elle vole à l’autre femme.")],
        [N("Le plaisir d’Hylee éclate sous vous. Remerii maintient son corps contre le sien pendant les contractions, puis vous attire assez près pour que son souffle atteigne votre oreille. Vous jouissez à votre tour en Hylee, retenu par leurs deux regards et par la main de Remerii qui ne vous laisse pas quitter le rythme trop tôt.")],
        [N("Vous vous retirez avec précaution et restez allongé contre Hylee. Remerii essuie vos peaux, donne à boire à l’une puis à l’autre et accepte enfin que Hylee s’occupe d’elle : un baiser prolongé, une main encore chaude entre ses cuisses, sans transformer l’après en service rendu.")],
        [H("On n’avait vraiment rien prévu.", "breathless"), R("Tu as choisi une alcôve et déshabillé deux personnes."), H("Je préfère ma version."), N("La boîte bancale sert de table à la pâtisserie. Remerii nourrit Hylee d’une bouchée, puis vous embrasse avant de partager la suivante.")],
      ],
      intersexe: [
        [N("Hylee vous entraîne dans l’alcôve des artisans et tire le rideau avant de vous faire asseoir sur les coussins. Remerii pose les provisions à l’abri, puis revient derrière elle. Votre corps répond déjà au souvenir du banc ; elles le remarquent toutes deux, sans supposer laquelle de vos sensations doit conduire la suite."), H("Je n’avais rien prévu. J’ai seulement envie de continuer avec tout ce que tu es.", "determined")],
        [N("Hylee ouvre votre tunique et caresse votre poitrine. Remerii défait ses cheveux, embrasse sa nuque et glisse les mains sous ses vêtements. Hylee gémit contre votre bouche, puis descend le long de votre ventre ; elle prend votre membre dressé dans sa main tandis que Remerii vient caresser la chaleur offerte entre vos cuisses.")],
        [N("Leurs gestes se répartissent sans couper votre corps en deux. Hylee embrasse votre extrémité, varie la pression de sa paume et revient parfois lécher votre poitrine. Remerii glisse deux doigts en vous, attentive à l’angle qui vous fait revenir contre elle, puis embrasse Hylee chaque fois que leurs mains se croisent sur votre ventre.")],
        [N("Vous attirez Remerii à votre bouche pendant qu’Hylee poursuit. La main de Remerii quitte un instant votre chaleur pour descendre entre les cuisses d’Hylee ; votre propre main la remplace sur vous, guidée par son regard. Hylee vous donne du plaisir et en reçoit dans le même mouvement, reliée aux deux autres par ses baisers et ses doigts.")],
        [N("Hylee fait asseoir Remerii contre le mur. Elle descend sur elle, langue précise et mains ouvertes sur ses cuisses. Vous restez près de leur visage : Remerii reprend votre membre dans sa paume, Hylee glisse une main dans votre chaleur et leurs deux rythmes répondent aux réactions que l’autre provoque.")],
        [N("Remerii jouit contre la bouche d’Hylee tout en vous maintenant au bord. Hylee remonte l’embrasser ; vous les regardez partager leur plaisir sans vous effacer. Leurs mains reviennent ensuite ensemble sur votre corps, l’une autour de votre désir dressé, l’autre en vous, et elles vous demandent seulement de leur montrer ce que vous voulez garder.")],
        [N("Vous vous allongez entre elles. Hylee frotte sa chaleur contre votre cuisse et garde sa bouche autour de vous ; Remerii poursuit les mouvements profonds de ses doigts. Elles s’embrassent au-dessus de votre poitrine, ajustant la cadence d’après vos hanches plutôt que d’après une idée abstraite de votre anatomie.")],
        [N("Votre orgasme traverse vos deux foyers de plaisir. Hylee garde votre membre dans sa bouche tandis que Remerii maintient l’angle en vous ; leurs mains se rejoignent sur votre ventre lorsque vous jouissez. La cuisse d’Hylee se serre contre la vôtre et son propre plaisir suit sous les doigts de Remerii.")],
        [N("Le calme revient sans inventaire de ce qui a fonctionné. Hylee repose sa joue sur votre ventre ; Remerii caresse votre hanche, puis laisse Hylee embrasser sa paume. Vous les ramenez l’une vers l’autre afin que l’après appartienne encore au triangle, pas à deux personnes occupées séparément de vous.")],
        [H("On n’avait vraiment rien prévu.", "breathless"), R("Tu as trouvé une alcôve et très précisément choisi de ne pas t’arrêter."), H("Ça reste de l’improvisation."), N("Vous partagez la pâtisserie sur la boîte bancale, encore nus sous des vêtements mal remis, et leurs deux baisers accompagnent la dernière bouchée.")],
      ],
    },
    ellipse: [
      [N("Hylee trouve une alcôve de repos derrière les échoppes et tire le rideau. La journée sans programme vient d’inventer sa première destination secrète.")],
      [N("Elle vous embrasse, puis embrasse Remerii avec la même joie visible. Remerii referme le cordon du rideau avant de revenir poser les mains sur vos deux tailles.")],
      [N("Les vêtements s’ouvrent par gestes incomplets. Hylee rit quand Remerii tente encore de ranger un paquet ; elle lui prend le visage et remplace l’ordre par un baiser.")],
      [N("Vous les regardez se toucher quelques secondes, histoire ancienne et désir présent mêlés. Hylee tend ensuite la main et vous attire sans rompre leur mouvement.")],
      [N("Derrière le tissu, trois ombres se rapprochent sur les coussins. Les bouches, les mains et les souffles circulent jusqu’à ce qu’aucune silhouette ne reste isolée.")],
      [N("Le rideau préserve la suite. Le plaisir de l’une appelle celui des deux autres ; le rire d’Hylee devient un souffle, puis revient lorsque le calme commence.")],
      [R("Tu avais donc un programme.", "soft"), H("Je l’ai inventé très tard."), N("Vous restez enlacés assez longtemps pour rendre l’argument impossible à trancher.")],
      [N("La boîte bancale sert enfin à quelque chose : elle porte la dernière pâtisserie, partagée entre trois bouches avant que vous ne retrouviez la galerie.")],
    ],
  },
  {
    slug: "boite-secrets",
    labels: {
      femme: "La boîte à trois secrets — laisser Remerii abandonner la mesure",
      homme: "La boîte à trois secrets — recevoir l’initiative sèche de Remerii",
      intersexe: "La boîte à trois secrets — offrir à Remerii un corps sans mode d’emploi",
    },
    detail: "Remerii prétend vouloir réparer la boîte dans un établi prêté. Sa précision se transforme en initiative, Hylee la taquine sans la déposséder et le joueur découvre une Remerii plus chaleureuse que professorale.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    tendre: [
      [N("Le marchand vous prête son petit établi arrière pour examiner la boîte. Une lampe basse éclaire les copeaux ; le rideau reste ouvert sur une cour vide. Remerii retire son manteau, relève ses manches et découvre Hylee déjà assise sur le tabouret qui lui était destiné.")],
      [R("Tu savais que j’allais vouloir l’ouvrir."), H("Je savais que tu allais prétendre vouloir seulement l’ouvrir."), N("Remerii pose la boîte, s’approche et embrasse Hylee pour interrompre son sourire.")],
      [N("Le geste surprend même Hylee. Remerii revient vers vous avant que la première n’ait préparé sa riposte et vous embrasse avec une chaleur franche, débarrassée de toute explication.")],
      [N("Hylee se lève derrière elle, entoure sa taille et pose le menton sur son épaule. Vous gardez Remerii entre vous sans l’enfermer ; elle choisit la main d’Hylee puis la vôtre et les place où elle souhaite être touchée.")],
      [N("Le trio s’assied au sol contre l’établi. Hylee embrasse Remerii, vous caressez son visage, puis les places tournent. Remerii rit lorsqu’Hylee annonce chaque nouveau baiser comme une étape de réparation.")],
      [N("Les caresses deviennent assez lentes pour conduire chacune vers un plaisir doux. Remerii reçoit sans compter, donne sans corriger et garde Hylee contre sa poitrine pendant que votre frisson rejoint le leur.")],
      [H("Diagnostic ?"), R("La boîte est toujours mal ajustée."), H("Je parlais de toi."), R("Je sais."), N("Remerii embrasse son front, sourire ouvert, puis vous attire contre elles.")],
      [N("Vous remontez les manches et les cols. La boîte n’a pas bougé de l’établi. Remerii décide finalement qu’elle la réparera un autre jour, décision que Hylee accueille comme la preuve d’un progrès remarquable.")],
    ],
    suggestif: [
      [N("Le marchand vous confie un établi derrière son échoppe. Remerii ferme la porte de la cour, pose la boîte sous la lampe et relève ses manches. Hylee occupe déjà le tabouret prévu pour elle.")],
      [H("Tu vas prétendre que nous sommes ici pour le couvercle."), R("Non."), N("La réponse directe coupe le rire d’Hylee. Remerii l’embrasse, puis vous, avec une assurance rendue plus troublante par sa rareté.")],
      [N("Elle ouvre vos vêtements sans produire d’hypothèse. Hylee vient derrière elle, dégage sa nuque et retire ses propres attaches pour que Remerii puisse la toucher sans interrompre ce qu’elle commence avec vous.")],
      [N("Vous gardez Remerii au centre quelques instants, mais Hylee refuse la logique d’un simple tour. Elle embrasse votre épaule pendant que Remerii la caresse, puis guide votre main vers la chaleur que leurs deux corps partagent déjà.")],
      [N("Les vêtements rejoignent les copeaux propres. Remerii organise seulement les appuis nécessaires sur le tapis ; pour le reste, elle laisse Hylee changer le rythme, vous rapprocher et la surprendre jusqu’à lui arracher un rire essoufflé.")],
      [N("Les gestes passent hors cadre, clairement sexuels et réciproques. Remerii vous mène au plaisir tandis qu’Hylee la fait céder à son tour ; après votre sommet, toutes deux se retrouvent bouche contre bouche avant de vous ramener dans leur étreinte.")],
      [R("Je n’ai réparé absolument rien."), H("Tu as cessé de faire semblant que c’était l’objectif."), N("Hylee lui donne un baiser satisfait. Vous couvrez leurs épaules avec le manteau abandonné.")],
      [N("La lampe continue d’éclairer la boîte intacte. Vous mangez le reste des provisions assis au sol, Remerii entre vous deux, ses mains occupées par les vôtres plutôt que par un outil.")],
    ],
    explicite: {
      femme: [
        [N("Remerii ferme la porte de la petite cour, pose la boîte sous la lampe et relève ses manches. Hylee s’assied sur l’établi, jambes croisées, prête à commenter. Remerii ne touche pas au couvercle : elle s’approche, place une main derrière sa nuque et l’embrasse jusqu’à faire disparaître sa première plaisanterie."), R("Je ne suis pas venue réparer cela maintenant.", "smirk")],
        [N("Elle se tourne vers vous et ouvre votre tunique avec la même décision. Hylee glisse derrière elle, défait ses attaches et embrasse la cicatrice sous son sein avant de prendre sa poitrine dans ses mains. Remerii gémit, mais garde votre bouche contre la sienne et descend une paume entre vos cuisses.")],
        [N("Ses doigts découvrent votre chaleur, entrent lentement et trouvent l’angle auquel vos hanches répondent. Hylee observe ses réactions plutôt que sa méthode : elle caresse Remerii entre les jambes, mord doucement son épaule et accélère chaque fois que la précision de ses gestes sur vous menace de redevenir un refuge froid.")],
        [N("Vous embrassez Hylee au-dessus de l’épaule de Remerii. La femme noire demeure au centre, recevant la main d’Hylee et votre bouche tout en vous donnant du plaisir. Elle cesse bientôt de compter ; son bassin cherche les doigts d’Hylee au même rythme que les siens vont et viennent en vous.")],
        [N("Remerii vous allonge sur le tapis et fait venir Hylee près de votre visage. Vous ouvrez les cuisses de la jeune mage et la goûtez pendant que Remerii s’agenouille entre les vôtres. Hylee se penche pour l’embrasser par-dessus votre ventre, puis leurs langues se retrouvent tandis que les doigts de Remerii poursuivent en vous.")],
        [N("Hylee jouit contre votre bouche. Son cri se brise dans le baiser de Remerii, qui remonte un instant pour la retenir. Vous voyez leur tendresse revenir immédiatement après l’intensité : une main dans les cheveux, un front contre l’autre, puis deux regards qui se tournent vers vous sans vous avoir oublié.")],
        [N("Elles changent les places. Hylee descend entre vos jambes et Remerii s’allonge près de vous. Vous caressez Remerii jusqu’à ce qu’elle ouvre enfin ses cuisses sans donner d’instruction ; Hylee garde sa langue sur votre point sensible et glisse deux doigts en vous, plus joueuse mais tout aussi attentive à vos réactions.")],
        [N("Votre orgasme arrive contre la bouche d’Hylee. Remerii vous embrasse pendant que votre corps se contracte, puis la main que vous gardiez entre ses cuisses lui donne à son tour le plaisir qu’elle retenait. Elle jouit contre votre paume et la nuque d’Hylee, prise entre les deux personnes qu’elle avait décidé de ne pas diriger.")],
        [N("Hylee remonte se coucher sur elle et l’embrasse longuement. Vous les rejoignez sur le tapis ; vos jambes se mêlent, vos mains apaisent les peaux sensibles et Remerii accepte l’eau que Hylee lui tend sans se relever pour la servir elle-même.")],
        [H("Diagnostic ?"), R("J’ai oublié d’ouvrir la boîte."), H("C’est grave."), R("Je supporterai les conséquences."), N("Son rire reste contre vos deux bouches. La lampe baisse et la boîte demeure mal ajustée, parfaite témoin d’un après-midi qui ne l’était pas.")],
      ],
      homme: [
        [N("Remerii ferme la porte de la petite cour, relève ses manches et pose la boîte sous la lampe. Hylee s’installe sur l’établi, prête à se moquer de son sérieux. Remerii ignore le couvercle, vient saisir sa nuque et l’embrasse assez franchement pour lui retirer toute phrase préparée."), R("Je ne suis pas venue réparer cela maintenant.", "smirk")],
        [N("Elle se tourne vers vous, ouvre votre chemise et défait votre ceinture. Hylee se glisse derrière elle, libère sa poitrine et embrasse sa cicatrice. Votre membre se dresse dans la paume de Remerii ; elle le caresse lentement tout en recevant la bouche d’Hylee contre sa peau.")],
        [N("Remerii s’agenouille devant vous et vous prend dans sa bouche. Hylee reste derrière elle, une main sur sa poitrine, l’autre entre ses cuisses. Chaque mouvement de la langue de Remerii sur vous répond au mouvement des doigts d’Hylee en elle, jusqu’à ce que sa précision se rompe dans un gémissement qui vous traverse.")],
        [N("Vous l’attirez pour l’embrasser. Hylee revient sur votre membre avec sa main pendant que sa bouche trouve celle de Remerii. Vous les regardez partager le goût et le désir quelques secondes ; puis Remerii guide votre paume sur Hylee, créant une chaîne où aucune ne se contente de vous servir.")],
        [N("Remerii fait asseoir Hylee au bord de l’établi et vous conduit entre ses cuisses. Elle soutient sa nuque, l’embrasse et caresse sa chaleur pendant que vous entrez en elle. Hylee serre vos hanches et celles de Remerii à la fois, maintenant vos trois corps réunis à chaque poussée.")],
        [N("Hylee jouit entre vous, le visage caché contre le cou de Remerii. Cette dernière accompagne ses contractions d’une main et embrasse sa tempe jusqu’à ce que son souffle revienne. Vous ralentissez sans sortir de leur étreinte, témoin de l’attention qu’elles se donnent avant de réclamer la suite.")],
        [N("Remerii s’allonge ensuite sur le tapis et ouvre ses cuisses. Hylee vient contre son flanc, la caresse et vous guide en elle. Vous entrez lentement ; Hylee embrasse Remerii, pince doucement ses seins et vous indique par sa main sur votre bassin le rythme qui fait céder le contrôle de la femme noire.")],
        [N("Remerii jouit autour de vous, bouche ouverte contre celle d’Hylee. Son plaisir vous entraîne ; vous jouissez à votre tour tandis qu’Hylee garde les deux mains sur vos corps, attentive à la puissance puis au ralentissement nécessaire. Remerii vous retient encore lorsqu’il faut vous retirer.")],
        [N("Vous restez allongés au sol. Hylee essuie la peau de Remerii et lui donne à boire ; vous remettez une mèche derrière son oreille. Elle accepte les soins sans les transformer en dette, puis vous embrasse l’un après l’autre avant de réunir vos mains sur son ventre.")],
        [H("Diagnostic ?"), R("J’ai oublié d’ouvrir la boîte."), H("C’est grave."), R("Je supporterai les conséquences."), N("La boîte demeure intacte sous la lampe. Vous partagez les provisions sur le tapis, encore assez proches pour que chaque bouchée soit interrompue par un baiser.")],
      ],
      intersexe: [
        [N("Remerii ferme la porte de la petite cour et relève ses manches. Hylee s’installe sur l’établi, prête à commenter la réparation. Remerii pose pourtant la boîte sans l’ouvrir, saisit la nuque d’Hylee et l’embrasse jusqu’à faire tomber sa plaisanterie en un souffle surpris."), R("Je ne suis pas venue réparer cela maintenant.", "smirk")],
        [N("Elle se tourne vers vous, ouvre vos vêtements et prend le temps de regarder votre corps réel. Hylee vient derrière elle, découvre sa poitrine et embrasse sa cicatrice. Remerii referme une main autour de votre membre dressé tandis que l’autre caresse la chaleur ouverte entre vos cuisses, refusant de choisir quelle part de votre désir mérite d’abord son attention.")],
        [N("Remerii s’agenouille. Sa bouche accueille votre membre pendant que ses doigts entrent lentement en vous. Hylee reste derrière elle, une main sur sa poitrine et l’autre entre ses cuisses ; chaque mouvement donné par Remerii reçoit une réponse d’Hylee, jusqu’à ce que leurs souffles et le vôtre perdent toute mesure régulière.")],
        [N("Vous relevez Remerii pour l’embrasser. Hylee reprend votre membre dans sa paume et glisse deux doigts dans votre chaleur, alternant les sensations sans les opposer. Remerii l’embrasse par-dessus votre épaule puis guide votre main sur Hylee, créant un mouvement continu entre trois corps plutôt que trois attentions séparées.")],
        [N("Remerii fait asseoir Hylee sur l’établi. Vous vous placez entre elles : Hylee frotte sa chaleur contre votre cuisse, Remerii vient derrière vous et poursuit ses doigts en vous tandis que sa paume maintient votre désir dressé. Vous embrassez Hylee et recevez le regard de Remerii par-dessus son épaule.")],
        [N("Hylee jouit la première sous votre main et contre votre cuisse. Remerii la retient, embrasse sa tempe et garde l’autre main sur vous sans accélérer. Leur ancienne tendresse traverse la scène ; puis Hylee, encore secouée, tend les doigts vers Remerii et l’invite à abandonner enfin sa place centrale.")],
        [N("Remerii s’allonge sur le tapis. Hylee descend entre ses cuisses pendant que vous vous placez près de sa bouche. Elle reprend votre membre entre ses lèvres ; vous caressez votre propre chaleur contre sa main libre et accompagnez la bouche d’Hylee sur elle. Remerii reçoit et donne dans le même souffle, incapable de compter davantage.")],
        [N("Le plaisir de Remerii éclate sous la langue d’Hylee. Sa bouche reste autour de vous et sa main en vous ; la double stimulation vous mène à votre propre orgasme, qui traverse votre membre et votre profondeur presque ensemble. Hylee garde une paume sur votre ventre, Remerii l’autre, réunies autour de votre secousse plutôt que réparties de part et d’autre.")],
        [N("Vous restez au sol, Hylee couchée sur Remerii et vous contre leurs flancs. Elle donne de l’eau à chacune, reçoit vos caresses sur sa cicatrice et accepte de ne pas remettre immédiatement les vêtements en ordre. Aucun commentaire méthodique ne vient réduire ce qui s’est passé.")],
        [H("Diagnostic ?"), R("J’ai oublié d’ouvrir la boîte."), H("C’est grave."), R("Je supporterai les conséquences."), N("Vous partagez les provisions sous la lampe. La boîte reste intacte et vos trois mains, posées l’une sur l’autre, ne cherchent plus aucun outil.")],
      ],
    },
    ellipse: [
      [N("Le marchand prête un petit établi à Remerii. Hylee s’assied sur le tabouret prévu pour elle, certaine que la boîte n’est déjà plus le vrai sujet.")],
      [N("Remerii le confirme en l’embrassant, puis en venant vers vous sans détour. La rareté de son initiative rend la chaleur du geste plus franche encore.")],
      [N("Les manches se relèvent, puis les cols et les attaches cèdent. Hylee reste derrière Remerii, l’embrasse et la maintient liée à vous dans le même mouvement.")],
      [N("Remerii choisit le tapis plutôt que l’établi. Elle place vos mains où elle les souhaite, puis laisse Hylee déplacer les corps sans corriger sa spontanéité.")],
      [N("La lampe projette trois silhouettes liées. Les gestes deviennent sexuels hors du regard du récit, toujours reliés par les baisers qu’Hylee et Remerii échangent au-dessus de vous.")],
      [N("Le plaisir vous traverse tour à tour sans devenir une file d’attente. Celui d’Hylee change le rythme de Remerii ; le vôtre les ramène toutes deux contre vous.")],
      [H("Diagnostic ?"), R("J’ai oublié la boîte."), N("Hylee embrasse son sourire, ravie d’avoir obtenu l’unique résultat qu’elle espérait vraiment.")],
      [N("Vous mangez au sol sous le manteau de Remerii. La boîte demeure mal ajustée ; vos trois places, elles, ont trouvé leur forme sans mesure préalable.")],
    ],
  },
  {
    slug: "aucun-itineraire",
    labels: {
      femme: "Aucun itinéraire — entrer dans un mouvement commencé entre elles",
      homme: "Aucun itinéraire — accepter de ne pas conduire la dérive",
      intersexe: "Aucun itinéraire — laisser trois désirs choisir leur propre ordre",
    },
    detail: "Sur une loggia végétale déserte, Hylee et Remerii se retrouvent d’abord l’une l’autre. Le joueur observe, est invité, puis perd avec bonheur le contrôle social de la scène.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    tendre: [
      [N("La fin de l’après-midi vous conduit sur une loggia végétale presque vide. Hylee s’appuie à la balustrade ; Remerii remet derrière son oreille la mèche que le vent du dôme déplace depuis le matin.")],
      [H("Tu l’as fait au moins six fois."), R("Et elle revient au moins six fois."), N("Hylee prend sa main, l’embrasse et la garde contre sa joue au lieu de rendre la mèche à sa place.")],
      [N("Leur baiser commence sans vous. Vous les regardez se reconnaître dans les petits gestes : Hylee qui sait quand avancer, Remerii qui cesse de réfléchir au moment exact où sa taille rejoint ses mains.")],
      [N("Hylee tend ensuite une main vers vous sans quitter Remerii. Vous l’acceptez et entrez dans leur proximité par le côté, non pour interrompre, mais pour ajouter votre souffle et votre bouche au rythme déjà vivant.")],
      [N("Vous vous installez sur le large banc de pierre. Les caresses circulent ; parfois elles se liguent pour vous surprendre, parfois vous les regardez rire l’une contre l’autre avant d’être rappelé par deux mains ouvertes.")],
      [N("Le plaisir reste doux, né des pressions lentes et des baisers prolongés. Hylee frissonne contre Remerii ; Remerii garde vos doigts entre les siens lorsque votre propre sommet vous fait fermer les yeux.")],
      [P("J’ai perdu le contrôle de cette sortie."), H("Tu n’en avais jamais eu."), R("C’était pourtant très courageux de le découvrir si tard."), N("Elles vous embrassent chacune sur une joue, parfaitement liguées.")],
      [N("La lumière baisse sous le dôme. Vous repartez sans itinéraire, Hylee entre vous deux pour quelques pas, puis Remerii au milieu lorsqu’elle prétend connaître un raccourci qu’Hylee refuse de croire.")],
    ],
    suggestif: [
      [N("Une loggia végétale déserte termine votre promenade. Hylee s’appuie à la balustrade ; Remerii remet une mèche derrière son oreille. Cette fois, Hylee retient sa main et l’embrasse au creux de la paume.")],
      [N("Leur baiser se prolonge avant qu’elles pensent à vous appeler. Vous voyez leurs corps se reconnaître : les mains d’Hylee sous le manteau de Remerii, la bouche de Remerii au point précis qui fait trembler ses épaules.")],
      [N("Hylee tend enfin un bras. Vous venez contre son dos pendant que Remerii reste devant elle. Vos baisers sur sa nuque rejoignent ceux de Remerii sur sa bouche ; leurs mains vous ouvrent une place sans cesser de se toucher.")],
      [N("Sur le banc de pierre, les vêtements glissent sous les manteaux étendus. Remerii attire Hylee sur ses genoux ; vous recevez leurs deux regards, puis elles vous rapprochent jusqu’à ce que vos trois peaux se rencontrent hors de la vue de la galerie.")],
      [N("Le récit garde les gestes les plus intimes sous les étoffes, mais pas leur dynamique : Hylee et Remerii se donnent du plaisir, vous regardent les perdre quelques secondes, puis vous ramènent entre elles avec un sourire partagé.")],
      [N("Votre sommet arrive alors qu’elles se sont liguées autour de vous. Le plaisir d’Hylee suit sous la main de Remerii ; celle-ci reçoit ensuite vos deux attentions sans réussir à conserver son calme impeccable.")],
      [P("Je n’étais pas censé devenir le sujet de votre complot."), R("Nous n’avions aucun programme."), H("C’est donc arrivé naturellement."), N("Leur satisfaction commune rend toute protestation inutile.")],
      [N("Vous remettez les manteaux avant le reste, comme si la fraîcheur justifiait encore de rester emmêlés. La loggia se vide avec vous, mais la sensation d’avoir rejoint leur histoire sans l’interrompre persiste.")],
    ],
    explicite: {
      femme: [
        [N("Sur la loggia déserte, Hylee retient la main qui replace encore une fois la mèche de Remerii et embrasse sa paume. Remerii répond en la tirant contre elle. Leur baiser commence sans vous, long et familier, tandis que vous restez près de la balustrade à regarder leurs mains retrouver des chemins appris bien avant votre arrivée.")],
        [N("Hylee ouvre le manteau de Remerii. La femme noire glisse les doigts sous sa tunique, caresse sa poitrine et mord doucement la peau sous son oreille. Hylee gémit, puis tend une main vers vous sans quitter sa bouche. Vous venez derrière elle et embrassez sa nuque pendant que Remerii vous sourit par-dessus son épaule.")],
        [N("Vous vous abritez sur le banc, manteaux étendus sous vos corps. Remerii fait asseoir Hylee sur ses genoux et ouvre ses cuisses. Vous caressez Hylee entre les jambes depuis l’arrière tandis que Remerii prend ses seins et l’embrasse. Elle reçoit deux attentions dans un seul mouvement et guide vos mains l’une vers l’autre.")],
        [N("Hylee descend des genoux de Remerii pour s’agenouiller entre les siens. Vous vous placez près de sa bouche. Elle goûte Remerii, puis vous, alternant sans vous mettre en attente ; Remerii glisse une main dans vos cheveux et l’autre entre vos cuisses, ses doigts entrant en vous au rythme de la langue d’Hylee sur elle.")],
        [N("Vous embrassez Remerii pendant qu’Hylee poursuit. Son plaisir monte sous la bouche de la jeune mage ; vos doigts rejoignent ceux de Remerii en vous, guidés par sa main. Lorsque leurs bouches se retrouvent, Hylee vous attire entre elles et partage avec Remerii le goût qu’elle vient de lui prendre.")],
        [N("Remerii jouit contre la langue d’Hylee, le souffle brisé dans votre cou. Hylee remonte sur le banc ; vous les regardez s’embrasser pendant quelques secondes entièrement à elles. Puis Hylee vous couche sous les manteaux et Remerii suit, toutes deux souriantes de vous avoir laissé attendre juste assez.")],
        [N("Hylee s’allonge contre votre flanc, frotte sa chaleur à votre cuisse et vous lèche lentement. Remerii entre deux doigts en vous depuis l’autre côté et embrasse Hylee au-dessus de votre ventre. Leurs gestes se répondent ; quand vous bougez vers l’une, l’autre ajuste son rythme au lieu de réclamer votre attention.")],
        [N("Vous jouissez entre elles, la bouche d’Hylee sur votre point sensible et les doigts de Remerii profondément en vous. Votre main reste entre les cuisses d’Hylee ; ses propres contractions commencent sous votre paume et Remerii l’embrasse jusqu’à son orgasme, réunissant vos deux plaisirs sans les confondre.")],
        [N("Vous vous retournez enfin vers Remerii. Hylee et vous la caressez ensemble, l’une avec sa bouche, l’autre avec ses doigts, jusqu’à lui arracher un second frisson moins contenu. Elle rit contre le front d’Hylee, surprise d’avoir laissé la scène lui échapper deux fois.")],
        [P("J’ai perdu le contrôle de cette sortie."), H("Tu n’en avais jamais eu."), R("Nous avons pourtant pris grand soin de vous."), N("Elles se liguent encore pour remettre vos vêtements de travers. Vous repartez entre elles, assez près pour que la loggia semble conserver la chaleur de trois corps.")],
      ],
      homme: [
        [N("Sur la loggia déserte, Hylee retient la main qui replace encore une fois la mèche de Remerii et embrasse sa paume. Remerii la tire contre elle. Leur baiser commence sans vous, profond et familier ; vous restez près de la balustrade, témoin de deux femmes qui n’ont jamais eu besoin de votre présence pour se désirer.")],
        [N("Hylee ouvre son manteau. Remerii glisse les mains sous sa tunique, caresse sa poitrine et mord la peau sous son oreille. Hylee tend alors une main vers vous. Vous venez derrière elle ; votre membre se dresse contre ses hanches tandis que vous embrassez sa nuque et que Remerii vous regarde par-dessus son épaule.")],
        [N("Sur le banc couvert de manteaux, Remerii fait asseoir Hylee sur ses genoux. Vous vous agenouillez devant elles. Hylee ouvre votre ceinture et prend votre membre dans sa main sans quitter la bouche de Remerii ; cette dernière caresse Hylee entre les cuisses et guide parfois sa paume sur vous.")],
        [N("Hylee descend pour vous prendre dans sa bouche. Remerii reste derrière elle, une main sur sa poitrine et l’autre dans sa chaleur. Vous regardez le plaisir d’Hylee répondre aux doigts de Remerii pendant qu’elle vous accueille plus profondément, puis vous la relevez pour que leurs bouches se retrouvent au-dessus de votre désir.")],
        [N("Remerii s’allonge sur le manteau et attire Hylee entre ses cuisses. Hylee lui donne du plaisir avec sa langue pendant que vous vous placez derrière elle. Vous entrez lentement en Hylee ; chaque poussée la rapproche de Remerii, et leurs mains restent jointes près du visage qu’elle embrasse entre deux gémissements.")],
        [N("Remerii jouit la première sous la bouche d’Hylee. Elle la retient par les cheveux, l’embrasse dès qu’elle remonte et garde une main sur sa joue. Vous ralentissez sans quitter Hylee, laissant leur après immédiat exister avant que ses hanches vous demandent à nouveau de bouger.")],
        [N("Le rythme reprend. Remerii caresse Hylee pendant que vous allez et venez en elle ; Hylee serre ses doigts et vous guide par ses mouvements. Son orgasme vous traverse, les contractions autour de votre membre accompagnées par la bouche de Remerii sur la sienne.")],
        [N("Vous jouissez peu après, maintenu entre leurs deux corps et leurs regards. Hylee reste contre vous pendant que Remerii soutient sa nuque. Lorsque vous vous retirez, elles vous couchent sur le manteau et se tournent l’une vers l’autre, refusant que votre sommet signifie la fin de leur mouvement.")],
        [N("Vous les regardez se caresser, puis vous les rejoignez : votre main donne à Remerii un nouveau plaisir tandis qu’Hylee l’embrasse et guide vos doigts. Elle jouit de nouveau sous vos attentions réunies, son rire surpris se mêlant au souffle satisfait d’Hylee.")],
        [P("J’ai perdu le contrôle de cette sortie."), H("Tu n’en avais jamais eu."), R("Nous avons pourtant pris grand soin de vous."), N("Elles remettent votre chemise avec deux boutons inversés et refusent de corriger leur œuvre. Vous quittez la loggia liés par le même rire.")],
      ],
      intersexe: [
        [N("Sur la loggia déserte, Hylee retient la main qui replace encore une fois la mèche de Remerii et embrasse sa paume. Leur baiser commence sans vous, profond et familier. Vous restez près de la balustrade, regardant deux femmes qui se connaissent assez pour trouver le désir dans un geste répété depuis des années.")],
        [N("Hylee ouvre le manteau de Remerii. Celle-ci caresse sa poitrine et mord doucement la peau sous son oreille. Hylee tend enfin une main vers vous. Vous venez derrière elle ; votre membre dressé presse contre ses hanches tandis que Remerii glisse son autre main dans la chaleur ouverte entre vos cuisses.")],
        [N("Sur le banc couvert de manteaux, Remerii fait asseoir Hylee sur ses genoux. Hylee prend votre membre dans sa paume et l’embrasse ; Remerii entre deux doigts en vous. Leurs gestes n’alternent pas : ils se répondent, Hylee revenant parfois caresser votre profondeur tandis que Remerii reprend votre désir dressé.")],
        [N("Hylee descend entre les cuisses de Remerii et la goûte. Vous restez près de leur visage ; Remerii maintient une main autour de votre membre, l’autre en vous, pendant que vous embrassez Hylee au-dessus de son ventre. Le plaisir donné à l’une se transmet par les mains et les souffles des deux autres.")],
        [N("Remerii jouit sous la bouche d’Hylee. Sa main se serre autour de vous et ses doigts gardent l’angle en vous ; la double pression vous fait gémir contre l’épaule d’Hylee. Celle-ci remonte embrasser Remerii, puis vous attire entre elles sans effacer l’échange que vous venez d’observer.")],
        [N("Vous vous allongez sur le manteau. Hylee prend votre membre dans sa bouche pendant que Remerii continue ses mouvements en vous. Elles s’embrassent au-dessus de votre ventre, leurs mains parfois jointes sur votre peau. Vous leur indiquez le rythme par vos hanches, et toutes deux l’adoptent sans supposer laquelle de vos sensations doit primer.")],
        [N("Votre orgasme approche par vagues croisées. Remerii garde ses doigts en vous, Hylee sa bouche autour de votre membre ; leurs deux paumes se rejoignent sur votre ventre lorsque votre plaisir traverse les deux foyers à la fois. Elles restent ensemble autour de vous, pas chacune à une extrémité de votre corps.")],
        [N("Hylee se frotte ensuite contre votre cuisse. Vous la caressez pendant que Remerii l’embrasse et prend sa poitrine. Son orgasme arrive sous votre main ; Remerii le reçoit contre sa bouche et vous ramène dans le baiser avant que le frisson ne soit entièrement retombé.")],
        [N("Vous vous tournez vers Remerii à trois. Hylee descend entre ses cuisses, vous guide une main sur son point sensible et embrasse ses lèvres chaque fois qu’elle remonte. Remerii jouit sous vos gestes réunis, incapable de conserver son ironie plus de quelques secondes.")],
        [P("J’ai perdu le contrôle de cette sortie."), H("Tu n’en avais jamais eu."), R("Nous avons pourtant pris grand soin de tout votre corps."), N("Elles replacent vos vêtements de manière volontairement imparfaite. La loggia conserve derrière vous trois manteaux froissés et un rire impossible à attribuer à une seule personne.")],
      ],
    },
    ellipse: [
      [N("Une loggia végétale presque vide clôt la promenade. Hylee retient la main de Remerii contre sa joue au lieu de la laisser remettre sa mèche en place.")],
      [N("Leur baiser commence sans vous. Vous regardez leurs habitudes devenir désir, puis Hylee tend une main ouverte sans interrompre ce qui existe entre elles.")],
      [N("Vous les rejoignez sur le banc de pierre. Les manteaux protègent du froid et des regards ; les attaches cèdent dessous avec une patience rapidement abandonnée.")],
      [N("Hylee et Remerii se touchent et s’embrassent quelques secondes pendant que vous les observez. Deux mains viennent ensuite vous rappeler dans leur mouvement.")],
      [N("Les silhouettes disparaissent sous les manteaux. Les caresses deviennent sexuelles, les places tournent et personne ne reste le centre assez longtemps pour transformer les deux autres en satellites.")],
      [N("Les plaisirs se répondent. Celui de l’une change le souffle des deux autres ; le vôtre arrive au milieu de leurs corps serrés et non au terme d’une attente séparée.")],
      [P("J’ai perdu le contrôle de cette sortie."), H("Tu n’en avais jamais eu."), R("Découverte tardive, mais exacte."), N("Elles vous embrassent ensemble pour sceller le diagnostic.")],
      [N("Vous repartez sans itinéraire. Les vêtements sont légèrement de travers, la lumière plus basse et leurs mains retrouvent les vôtres à chaque bifurcation.")],
    ],
  },
];

export const HYLEE_REMERII_FREE_DAY_ROUTES = manualHRRoutes(CONTEXT, seeds);
