import type { HRManualSeed } from "./hylee-remerii-intimacy-shared";
import { H, N, P, R, manualHRRoutes } from "./hylee-remerii-intimacy-shared";

const CONTEXT = "group-date-hylee-remerii-wind";

const seeds: HRManualSeed[] = [
  {
    slug: "manteau-partage",
    labels: {
      femme: "Sous le même manteau — suivre l’élan brûlant d’Hylee",
      homme: "Sous le même manteau — laisser Hylee jouer avec la chaleur retrouvée",
      intersexe: "Sous le même manteau — confier vos deux désirs au jeu d’Hylee",
    },
    detail: "Hylee refuse de rendre le manteau partagé et transforme l’abri de pierre en prolongement de la promenade. Remerii connaît trop bien son sourire pour feindre la surprise, mais assez mal cette liberté à trois pour ne pas en être troublée.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    tendre: [
      [N("Le vent vous pousse jusqu’à un ancien abri de guet dont il ne reste qu’un mur, un banc de pierre et un toit incliné. Hylee s’assied sans quitter le grand manteau partagé ; elle vous entraîne d’un côté et retient Remerii de l’autre, transformant l’étoffe en tente maladroite.")],
      [H("On devait seulement reprendre notre souffle.", "teasing"), R("Tu as cessé d’avoir froid depuis trois virages."), H("Je n’ai jamais dit que le froid était encore le problème."), N("Remerii lève les yeux au ciel, puis rabat tout de même le col sur les trois nuques.")],
      [N("Hylee embrasse votre joue froide, puis la bouche de Remerii. Cette dernière répond avec une familiarité immédiate, une main déjà posée au creux de son dos. Vous les regardez sourire dans le même baiser avant qu’elles ne vous ramènent entre elles.")],
      [N("Les mains restent d’abord au-dessus des vêtements : paumes sur les côtes, doigts réchauffant des joues, genoux serrés sous l’étoffe. Remerii connaît l’endroit exact où Hylee est chatouilleuse ; Hylee connaît celui où son sérieux se défait.")],
      [N("Vous échangez des baisers de plus en plus lents pendant que le vent frappe le mur. Hylee garde la main de Remerii contre son cœur, puis place la vôtre par-dessus. Le geste calme un instant le jeu sans en retirer le désir.")],
      [N("Le plaisir vient sans hâte, à travers les tissus ouverts juste assez et les caresses cachées sous le manteau. Hylee étouffe un souffle contre l’épaule de Remerii ; celle-ci vous embrasse au moment où votre propre frisson rapproche vos trois corps.")],
      [R("Nous allons devoir expliquer pourquoi nous avons mis une heure à franchir un sentier de vingt minutes."), H("Tu peux rédiger un rapport sur les effets imprévus d’un manteau trop grand."), P("Avec trois signatures."), N("Le rire de Remerii vous surprend tous les trois.")],
      [N("Vous restez encore un peu sur le banc, jambes mêlées et cols mal remis. Lorsque vous repartez, Hylee exige que le manteau demeure partagé. Remerii proteste pour la forme et se glisse dessous avant même la fin de sa phrase.")],
    ],
    suggestif: [
      [N("Un ancien abri de guet coupe enfin le vent. Hylee s’assied sur le banc de pierre et refuse de libérer le grand manteau ; elle vous tire contre elle, puis accroche Remerii par la ceinture avant que la mage ait le temps de proposer une pause raisonnable.")],
      [H("Nous sommes encore gelés. Il faut une méthode plus efficace."), R("Tu prépares cette phrase depuis la crête."), H("Depuis le deuxième baiser, exactement."), N("Remerii referme l’étoffe derrière vos trois corps au lieu de s’éloigner.")],
      [N("Hylee glisse ses mains sous vos couches de vêtements et cherche directement la peau. Elle revient vers Remerii, ouvre son col avec une aisance ancienne et embrasse la marque rouge laissée par le vent sous son oreille.")],
      [N("Remerii la retient par les hanches et transforme la taquinerie en baiser profond. Pendant quelques secondes, leur désir circule devant vous, nourri de gestes qu’elles connaissent déjà. Puis leurs deux mains trouvent les vôtres et vous invitent dans le même rythme.")],
      [N("Le manteau cache les attaches défaites, les cuisses rapprochées et les paumes qui remontent sous les étoffes. Hylee donne le tempo, mais Remerii le dérange volontairement ; vous devenez la troisième réponse de ce jeu plutôt que son arbitre.")],
      [N("Les souffles se brisent plus vite que le vent. Hylee trouve son plaisir entre vos deux corps, la bouche contre celle de Remerii ; vous atteignez le vôtre sous leurs mains coordonnées, puis gardez Remerii au centre jusqu’à ce que son contrôle cède à son tour.")],
      [H("Je vote pour rester ici jusqu’au printemps.", "breathless"), R("Ton vote est irrecevable. Et séduisant, ce qui complique inutilement la procédure."), N("Remerii embrasse son front, puis votre bouche, sans tenter de récupérer toute sa dignité.")],
      [N("Les vêtements sont remis en ordre sous le manteau. Vous reprenez le sentier avec la même étoffe autour des épaules ; trois démarches différentes doivent apprendre à avancer ensemble, et aucun de vous ne semble pressé d’y parvenir parfaitement.")],
    ],
    explicite: {
      femme: [
        [N("L’ancien abri de guet vous soustrait enfin aux rafales. Hylee s’assied sur le banc, conserve le grand manteau sur ses épaules et vous attire entre ses genoux. Remerii vérifie d’abord la stabilité du toit ; Hylee l’attrape ensuite par la ceinture et lui rappelle d’un sourire que le danger le plus immédiat se trouve désormais sous l’étoffe."), H("Viens nous réchauffer au lieu d’inspecter les pierres.", "determined")],
        [N("Remerii rabat le manteau derrière vos dos et vient embrasser Hylee. Leur baiser est franc, sans découverte prudente : la main de Remerii connaît déjà sa taille, celle d’Hylee retrouve sa nuque. Vous les regardez quelques secondes avant qu’Hylee ne prenne votre visage pour vous embrasser à son tour, encore marquée du goût de l’autre femme.")],
        [N("Hylee ouvre votre tunique et libère vos seins de la couche humide. Sa bouche réchauffe l’un tandis que Remerii couvre l’autre de sa paume. Elles échangent un regard au-dessus de votre poitrine, ajustent ensemble leurs gestes, puis s’embrassent contre votre peau lorsque votre respiration se fait plus courte.")],
        [N("Vous défaites le col de Remerii. Hylee se place derrière elle, embrasse sa gorge et guide votre main sous ses vêtements. La chaleur que vous trouvez contraste avec ses joues froides. Remerii entrouvre les cuisses, retient un souffle, puis glisse à son tour une main entre celles d’Hylee pour atteindre votre intimité déjà offerte.")],
        [N("Hylee s’agenouille devant vous sur le manteau replié. Elle écarte vos cuisses et vous goûte avec une avidité joueuse, tandis que Remerii reste contre votre dos, les doigts dans vos seins et la bouche sur votre oreille. Entre deux mouvements de langue, Hylee cherche les yeux de Remerii ; celle-ci lui caresse la joue et l’encourage sans donner d’ordre.")],
        [N("Vous interrompez Hylee juste assez longtemps pour l’attirer sur le banc. Remerii l’embrasse pendant que votre bouche descend entre ses cuisses. Son rire se brise en gémissement ; la main qu’elle tend vers Remerii trouve sa chaleur sous la jupe, et vos trois plaisirs se nouent sans que personne attende sagement son tour.")],
        [N("Remerii jouit sous les doigts d’Hylee, le visage enfoui contre sa nuque. Vous sentez Hylee frissonner autour de votre langue, mais elle vous relève avant de s’abandonner complètement. Elle veut vous voir entre elles ; elle vous installe sur le manteau, Remerii à votre bouche et son propre corps pressé contre votre cuisse.")],
        [N("Les doigts de Hylee entrent en vous pendant que sa bouche revient sur votre point sensible. Vous goûtez Remerii, qui garde une main dans vos cheveux et l’autre entre les cuisses d’Hylee. Le rythme se propage d’un corps à l’autre. Votre orgasme éclate sous leurs gestes ; celui d’Hylee suit, tremblant contre votre jambe, retenu par la main ferme de Remerii.")],
        [N("Le manteau retombe autour de trois corps encore ouverts et haletants. Remerii essuie doucement votre peau avec le coin sec d’une étoffe, puis Hylee prend sa main et embrasse chaque doigt sans plaisanter. Vous partagez l’eau de la même gourde ; le vent demeure dehors, réduit à un bruit sans pouvoir sur la chaleur créée ensemble.")],
        [H("Je maintiens que c’était une mesure contre le froid.", "breathless"), R("Une mesure exige normalement qu’on puisse la reproduire."), P("Nous pouvons vérifier au prochain abri."), N("Remerii vous fixe, prise entre indignation et envie, puis rit et ramène vos deux visages contre le sien avant de rouvrir le manteau sur le sentier.")],
      ],
      homme: [
        [N("L’ancien abri de guet coupe les rafales sans effacer leur grondement. Hylee s’assied sur le banc, garde le grand manteau autour d’elle et vous attire entre ses genoux. Remerii inspecte le toit par habitude ; Hylee l’accroche par la ceinture et lui offre ce sourire qu’elle reconnaît assez vite pour rougir avant même d’être embrassée."), H("Tu peux sauver le mur après nous.", "determined")],
        [N("Remerii ferme le manteau derrière vos trois dos et embrasse Hylee. Leurs gestes ont la sûreté d’une histoire déjà vécue : une main à la taille, des doigts dans les cheveux, un rire étouffé au bon endroit. Hylee vous ramène ensuite contre elles et partage avec vous la chaleur de la bouche qu’elle vient de quitter.")],
        [N("Hylee ouvre votre chemise, parcourt votre poitrine et descend jusqu’à votre ceinture. Remerii l’embrasse par-dessus votre épaule tout en défaisant ses cheveux. Lorsque votre désir se dresse dans la main d’Hylee, elle le serre lentement ; Remerii couvre ses doigts des siens et leurs deux rythmes apprennent ensemble votre souffle.")],
        [N("Vous ouvrez les vêtements de Remerii. Hylee se glisse derrière elle, embrasse sa nuque et guide votre main jusqu’à la chaleur entre ses cuisses. Remerii laisse échapper votre prénom, puis cherche Hylee d’une main et votre membre de l’autre, maintenant les trois corps reliés sous l’étoffe plutôt que disposés face à elle.")],
        [N("Hylee s’agenouille sur le pan sec du manteau. Elle vous prend dans sa bouche avec une gourmandise qui efface son dernier rire. Remerii reste derrière elle, caresse ses seins et glisse une main plus bas. Le plaisir que Hylee vous donne transforme ses propres mouvements ; vous la sentez réagir chaque fois que les doigts de Remerii la trouvent.")],
        [N("Vous l’arrêtez avant le bord et la faites asseoir sur le banc. Remerii l’embrasse tandis que vous descendez entre ses cuisses. Hylee ouvre son corps à votre bouche, mais garde une main autour de votre désir et l’autre dans la chaleur de Remerii. Aucune attention ne quitte vraiment le triangle, même lorsque l’une gémit plus fort.")],
        [N("Remerii jouit la première contre la main d’Hylee et mord doucement son épaule pour retenir sa voix. Hylee vous attire ensuite au-dessus d’elle. Remerii soutient sa nuque et caresse sa poitrine ; vous entrez lentement en Hylee, guidé par ses hanches et par la paume de Remerii posée sur votre bassin.")],
        [N("Chaque mouvement rapproche aussi les deux femmes : Remerii embrasse Hylee, suit de ses doigts la jonction de vos corps et recueille ses réactions. Le plaisir d’Hylee se brise entre vos bouches. Vous jouissez en elle quelques instants plus tard, maintenu contre toutes deux, tandis que Remerii accompagne les dernières secousses sans vous séparer.")],
        [N("Vous restez serrés sous le manteau, le froid incapable d’atteindre vos peaux humides. Remerii nettoie doucement vos corps avec une étoffe sèche ; Hylee embrasse sa paume, puis votre ventre, et lui interdit de transformer l’attention en tâche. La gourde circule, suivie de baisers plus calmes et d’un silence parfaitement habitable.")],
        [H("Je maintiens que c’était une stratégie contre le froid.", "breathless"), R("Une stratégie exige normalement un résultat mesurable."), P("Trois personnes qui refusent de rendre le manteau."), N("Remerii admet la mesure d’un sourire. Vous reprenez le sentier enlacés sous la même étoffe, plus lents et beaucoup moins crédibles.")],
      ],
      intersexe: [
        [N("L’ancien abri de guet coupe enfin les rafales. Hylee s’assied sur le banc, garde le grand manteau sur ses épaules et vous attire entre ses genoux. Remerii vérifie le toit par habitude ; un sourire de Hylee suffit à lui faire comprendre que les pierres peuvent attendre, contrairement à la chaleur déjà tendue entre vos trois corps."), H("Viens avant que je prétende encore avoir froid.", "determined")],
        [N("Remerii referme le manteau derrière vous et embrasse Hylee. Leur proximité porte des années de gestes appris : une main trouve une taille, une bouche sait où naît le rire. Hylee revient ensuite vers vous, vous embrasse avec la saveur de Remerii sur les lèvres et pose vos mains là où les deux femmes souhaitent vous sentir.")],
        [N("Hylee ouvre votre tunique et libère votre poitrine. Remerii la caresse pendant qu’Hylee embrasse les pointes dressées par le froid. Plus bas, votre désir se tend sous les doigts de Remerii et votre chaleur s’ouvre à sa paume. Elles accueillent ensemble les deux réponses de votre corps sans en choisir une comme plus vraie que l’autre.")],
        [N("Vous dénouez les vêtements de Remerii. Hylee vient dans son dos, embrasse sa nuque et guide votre main entre ses cuisses. Remerii gémit contre votre bouche, mais garde l’autre main autour de votre désir dressé. Hylee couvre cette main de la sienne, puis glisse ses doigts dans votre chaleur, nouant les gestes au lieu de les répartir.")],
        [N("Hylee s’agenouille sur le pan sec du manteau. Sa bouche entoure votre désir pendant que ses doigts vous pénètrent avec lenteur. Remerii reste contre votre dos, caresse votre poitrine et stimule Hylee sous sa jupe. Les trois rythmes se répondent ; chaque plaisir reçu donne à l’une un mouvement nouveau pour les deux autres.")],
        [N("Vous retenez Hylee avant le bord et la faites asseoir sur le banc. Votre bouche descend entre ses cuisses tandis que Remerii l’embrasse. Hylee prend votre désir dans sa main ; Remerii poursuit en vous les caresses commencées plus tôt. Même centrée un instant, Hylee demeure liée à vos deux corps par ses gestes et ses regards.")],
        [N("Remerii jouit sous les doigts de Hylee, le front posé contre le sien. Vous sentez Hylee frémir autour de votre langue ; elle vous relève pourtant pour vous allonger entre elles. Remerii vient à votre bouche, Hylee reprend votre désir et leurs mains se relaient dans votre chaleur sans cesser de se toucher entre chaque mouvement.")],
        [N("Votre orgasme traverse votre corps sous leurs attentions réunies : la bouche de Hylee autour de votre désir, les doigts de Remerii profondément en vous, leurs paumes jointes sur votre ventre. Hylee se frotte contre votre cuisse et jouit à son tour lorsque Remerii la serre contre vous, leurs bouches réunies au-dessus de votre souffle rompu.")],
        [N("Le manteau retombe sur trois corps encore haletants. Remerii prend une étoffe sèche ; Hylee lui retire doucement des mains pour essuyer d’abord sa peau, puis la vôtre, et l’obliger à recevoir aussi. La gourde circule avec des baisers plus calmes. Personne ne dresse l’inventaire de ce qui a répondu : tout votre corps a été entendu.")],
        [H("Je maintiens que c’était une mesure contre le froid.", "breathless"), R("Tes mesures sont de plus en plus difficiles à consigner."), P("Écris seulement : manteau partagé, résultat concluant."), N("Remerii rit contre vos deux fronts. Vous reprenez le sentier sous la même étoffe, maladroits à trois et parfaitement décidés à le rester.")],
      ],
    },
    ellipse: [
      [N("Un ancien abri de guet coupe le vent. Hylee s’assied sur le banc et entraîne le trio sous le manteau partagé.")],
      [H("Je n’ai plus vraiment froid."), R("Je sais. Tu souris comme avant une très mauvaise idée."), N("Hylee l’embrasse au lieu de nier.")],
      [N("Le baiser entre elles porte une familiarité sans mise en scène. Vous les regardez quelques secondes ; deux mains viennent ensuite chercher les vôtres.")],
      [N("Les attaches s’ouvrent sous l’étoffe. Le vent frappe le mur pendant que trois souffles construisent une chaleur plus proche et plus volontaire.")],
      [N("Hylee conduit d’abord le jeu, Remerii dérange son rythme avec une précision tendre, et vous les obligez toutes deux à perdre la mesure ensemble.")],
      [N("Le manteau ne révèle que des silhouettes réunies. Le plaisir passe de l’une aux autres, revient, puis se calme sans jamais réduire la scène à deux gestes séparés.")],
      [R("Nous allons mettre une heure pour vingt minutes de marche."), H("Alors il faudra partager le manteau plus longtemps."), N("Votre rire se mêle au leur sous le col relevé.")],
      [N("Vous reprenez le sentier serrés sous la même étoffe. Les pas ne sont pas synchrones, mais personne ne propose de retrouver une marche solitaire.")],
    ],
  },
  {
    slug: "mesure-derangee",
    labels: {
      femme: "La mesure dérangée — recevoir l’initiative de Remerii dans le vent",
      homme: "La mesure dérangée — laisser Remerii décider sans se cacher derrière une méthode",
      intersexe: "La mesure dérangée — offrir à Remerii un désir sans anatomie présumée",
    },
    detail: "Remerii choisit elle-même de prolonger la halte. Hylee reconnaît immédiatement sa manière de dissimuler une envie derrière une observation, puis l’aide à abandonner la méthode sans lui voler l’initiative.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    tendre: [
      [N("Sous l’abri de pierre, Remerii constate que vos doigts restent froids. Elle les enferme entre ses paumes, puis fait la même chose avec ceux d’Hylee sans attendre qu’elle réclame quoi que ce soit.")],
      [H("Tu pourrais simplement dire que tu veux qu’on reste."), R("Je viens de le faire."), H("Avec huit mots sur la circulation sanguine en moins, peut-être."), N("Remerii l’embrasse avant qu’elle n’invente le neuvième.")],
      [N("Elle revient vers vous avec une décision inhabituelle, prend votre visage et vous embrasse longtemps. Hylee se place derrière elle et masse ses épaules, présente sans diriger ce que Remerii a choisi.")],
      [N("Remerii vous guide, Hylee et vous, sur le manteau étendu contre le mur. Elle choisit chaque proximité, puis accepte que Hylee l’interrompe d’un baiser ou que vous changiez doucement la place de ses mains.")],
      [N("Les caresses lentes réchauffent davantage que la marche. Hylee embrasse Remerii au-dessus de votre épaule ; vous sentez leur sourire commun avant que leurs deux attentions ne reviennent sur vous.")],
      [N("Le plaisir reste doux, composé de mains cachées, de souffles retenus et de trois corps rapprochés. Remerii perd le compte la première ; Hylee se garde de le signaler jusqu’à ce que votre frisson ait rejoint le leur.")],
      [R("Tu peux rire."), H("Je préfère mémoriser."), R("C’est nettement plus inquiétant."), N("Hylee l’embrasse avec une gravité exagérée, puis éclate de rire contre ses lèvres.")],
      [N("Remerii remet elle-même le manteau sur vos trois épaules. Au moment de repartir, elle prend une main à chacune et ne prétend pas que ce geste améliore l’équilibre sur le sentier.")],
    ],
    suggestif: [
      [N("Remerii étend le manteau contre le mur sec de l’abri et annonce que la halte durera. Hylee reconnaît le ton, mais pas le regard qui l’accompagne ; elle s’assied, soudain plus attentive que moqueuse.")],
      [H("Tu viens de décider quelque chose qui n’était pas dans le plan."), R("Oui."), H("Je vais avoir besoin d’une minute."), N("Remerii profite de cette minute pour vous embrasser, puis attire Hylee par le col.")],
      [N("Elle défait vos couches de vêtements avec une patience qui n’est plus clinique. Hylee ouvre les siennes et embrasse les doigts de Remerii lorsqu’ils tremblent légèrement sur une attache.")],
      [N("Vous gardez Remerii au centre, sans faire d’elle un objet immobile. Elle guide vos mains sur son corps, puis les reprend pour toucher Hylee et vous avec une urgence qu’elle ne transforme en aucune explication.")],
      [N("Hylee connaît ses réactions et vous les révèle par de petits regards plutôt que par des commentaires. Remerii s’en venge en trouvant sous ses vêtements une caresse ancienne, tandis que sa bouche et votre main poursuivent leur propre conversation.")],
      [N("Le désir s’accomplit dans une chaleur de tissus ouverts et de corps serrés. Remerii jouit entre vous, puis refuse de se retirer du mouvement avant d’avoir conduit Hylee et vous vers un plaisir qui lui répond.")],
      [H("Tu avais donc un plan."), R("Une intention. La distinction compte."), P("Elle compte moins quand tu rougis encore."), N("Remerii vous embrasse pour imposer le silence, mais son sourire ruine toute autorité.")],
      [N("Vous vous rhabillez en vous aidant sans ordre défini. Remerii replace la mèche de Hylee, Hylee ferme votre col, et vous rabattez le manteau sur elles avant de reprendre le chemin.")],
    ],
    explicite: {
      femme: [
        [N("Dans l’abri, Remerii étend le manteau sur la pierre sèche au lieu de proposer immédiatement le retour. Hylee remarque le choix et se tait avec une rare discipline. La mage prend vos mains froides, les réchauffe contre sa bouche, puis fait asseoir Hylee auprès de vous avant de s’agenouiller entre vos deux corps."), R("Je veux que nous restions. Pas seulement à cause du vent.", "soft")],
        [N("Elle vous embrasse la première, longuement, puis se tourne vers Hylee. Celle-ci connaît sa manière de retenir une émotion au bord des lèvres ; elle ne la taquine pas. Elle prend doucement sa nuque et laisse Remerii choisir la profondeur du baiser, pendant que vous gardez une main ouverte sur leurs tailles réunies.")],
        [N("Remerii ouvre votre tunique et couvre vos seins de ses paumes réchauffées. Hylee s’installe derrière elle, défait sa coiffure et embrasse chaque parcelle de nuque révélée. Lorsque Remerii descend la bouche sur votre poitrine, Hylee glisse ses mains sous ses vêtements et transforme sa précision en souffle irrégulier.")],
        [N("Vous attirez Remerii contre le mur et ouvrez ses vêtements à votre tour. Hylee sait déjà où poser sa bouche pour la faire trembler ; vous découvrez le rythme de vos doigts entre ses cuisses en suivant ses hanches plutôt qu’une instruction. Remerii vous caresse en même temps, refusant que son abandon la retranche du trio.")],
        [N("Elle vous allonge sur le manteau et vient entre vos jambes. Sa langue explore votre intimité avec une attention qui devient vite avide. Hylee embrasse Remerii dans le dos, caresse sa poitrine puis sa chaleur ; chaque mouvement qu’elle lui donne se propage dans la bouche posée sur vous et vous fait réagir ensemble.")],
        [N("Vous échangez les places sans rompre les contacts. Hylee s’assied contre la pierre, Remerii entre ses cuisses. Vous embrassez Hylee tandis que Remerii la goûte ; votre main descend sur Remerii, trouve sa chaleur ouverte et répond aux gestes de sa langue. Hylee gémit entre vos lèvres, une main sur chacune de vos nuques.")],
        [N("Le plaisir de Hylee monte le premier. Remerii la maintient contre sa bouche jusqu’à sentir les secousses, puis remonte l’embrasser. Vous poursuivez sur Remerii, deux doigts profondément en elle, et Hylee vous rejoint d’une caresse sur le point sensible. Leur connaissance ancienne devient une offrande commune plutôt qu’un langage fermé.")],
        [N("Remerii jouit entre vos mains, le visage contre celui d’Hylee. Pourtant elle vous ramène aussitôt sur le manteau, une femme de chaque côté. Leurs doigts se rejoignent en vous, leurs bouches alternent entre vos seins et votre point sensible ; votre orgasme arrive sous leur regard partagé et vous leur serrez les mains lorsqu’il traverse tout votre ventre.")],
        [N("Remerii reste au centre après le calme, tête sur votre épaule et jambe mêlée à celle d’Hylee. Cette dernière lui remet une mèche en place avec une délicatesse presque cérémonieuse, puis vous donne la gourde. Vous buvez chacune avant de partager des baisers qui n’ont plus rien à prouver au vent.")],
        [H("Je n’ai fait aucun commentaire pendant tout ce temps."), R("Tu viens de gâcher cet exploit en le signalant."), P("Elle a tenu plus longtemps que toi sans compter."), N("Remerii rit, vous attire toutes deux sous le manteau et assume elle-même le premier pas lorsque le chemin reprend.")],
      ],
      homme: [
        [N("Dans l’abri, Remerii étend le manteau sur la pierre sèche plutôt que de proposer le retour. Hylee remarque ce choix contraire au programme et se tait, attentive. Remerii réchauffe vos mains contre sa bouche, prend celles d’Hylee dans le même geste, puis vous fait asseoir de chaque côté d’elle."), R("Je veux que nous restions. Et le vent n’est plus une excuse suffisante.", "soft")],
        [N("Elle vous embrasse avec une décision qui ne cherche aucun vocabulaire protecteur, puis se tourne vers Hylee. Celle-ci prend sa nuque et laisse Remerii conduire leur baiser. Vous posez une main sur leurs tailles ; elles la couvrent ensemble, signe clair que leur échange ancien ne se ferme pas autour de vous.")],
        [N("Remerii ouvre votre chemise et suit votre poitrine de sa bouche. Hylee vient derrière elle, libère ses cheveux et glisse les mains sous sa tenue. Lorsque votre désir se dresse contre les doigts de Remerii, Hylee prend ses poignets et l’aide à trouver une pression qui trouble autant celle qui donne que celui qui reçoit.")],
        [N("Vous installez Remerii contre le mur et défaites ses vêtements. Hylee embrasse la peau sous son oreille, là où elle sait faire naître un frisson, tandis que vos doigts explorent la chaleur entre ses cuisses. Remerii vous caresse encore, maintenant votre désir contre sa paume et refusant de disparaître dans le plaisir qu’elle reçoit.")],
        [N("Elle vous fait asseoir sur le manteau et s’agenouille. Sa bouche vous accueille lentement, puis avec une avidité qu’elle ne dissimule plus. Hylee reste derrière elle, caresse ses seins et descend entre ses cuisses ; les mouvements de Remerii autour de vous se désordonnent chaque fois que Hylee trouve exactement ce qu’elle cherchait.")],
        [N("Vous retenez Remerii avant votre limite et attirez Hylee contre la pierre. Remerii descend entre ses jambes ; vous embrassez Hylee et gardez une main sur la nuque de l’une, l’autre dans la chaleur de l’autre. Hylee caresse votre désir pendant que la bouche de Remerii lui arrache des gémissements moins rieurs.")],
        [N("Hylee jouit la première et ramène Remerii à sa bouche pour partager le goût et le souffle. Vous les regardez quelques secondes, puis Remerii vous attire au-dessus d’elle. Hylee se place près de son visage, ouvre sa tunique et l’embrasse pendant que vous entrez lentement dans la mage étendue sur le manteau.")],
        [N("Remerii vous guide par les hanches ; Hylee accompagne chaque mouvement de sa bouche et de ses doigts. Son contrôle cède dans un cri étouffé contre la poitrine d’Hylee. Vous jouissez peu après, profondément en elle, tandis que les deux femmes vous retiennent ensemble et que Hylee embrasse Remerii à travers les dernières secousses.")],
        [N("Vous restez mêlés dans l’espace étroit. Hylee nettoie doucement la peau de Remerii ; celle-ci s’occupe de vous, puis accepte enfin que vous lui tendiez l’eau au lieu de reprendre chaque tâche. Le vent secoue le toit, mais votre silence est chaud, ponctué de baisers sans ordre ni urgence.")],
        [H("Je n’ai fait aucun commentaire pendant tout ce temps."), R("Tu viens de détruire l’exploit en le signalant."), P("Elle a quand même tenu plus longtemps que toi sans compter."), N("Remerii rit contre vos deux fronts, referme le manteau sur le trio et choisit elle-même de vous tenir la main sur le chemin.")],
      ],
      intersexe: [
        [N("Dans l’abri, Remerii étend le manteau sur la pierre sèche au lieu de proposer le retour. Hylee remarque ce choix contraire au plan et garde le silence. Remerii réchauffe vos mains, puis celles d’Hylee, avant de vous faire asseoir de part et d’autre d’elle avec une détermination dont elle ne dissimule plus la cause."), R("Je veux rester avec vous. Le vent n’a plus besoin de porter la responsabilité.", "soft")],
        [N("Elle vous embrasse la première, attentive à votre réponse plutôt qu’à une idée de votre corps, puis se tourne vers Hylee. Celle-ci prend sa nuque et laisse Remerii conduire leur baiser. Vous gardez une main sur leurs tailles ; elles la couvrent ensemble et rouvrent immédiatement leur mouvement vers vous.")],
        [N("Remerii libère votre poitrine sous la tunique. Sa bouche réchauffe votre peau pendant que sa main descend vers les deux expressions de votre désir. Hylee vient dans son dos, ouvre sa coiffure et glisse les doigts sous ses vêtements. Chaque frisson qu’elle donne à Remerii modifie les caresses reçues, comme un rythme vivant plutôt qu’une méthode.")],
        [N("Vous installez Remerii contre le mur et défaites sa tenue. Hylee embrasse le point sous son oreille qu’elle connaît depuis longtemps ; vos doigts trouvent la chaleur entre ses cuisses. Remerii entoure votre désir d’une main et entre en vous avec l’autre, refusant d’abandonner votre plaisir au moment même où le sien devient visible.")],
        [N("Elle vous fait asseoir sur le manteau et s’agenouille. Sa bouche accueille votre désir tandis que ses doigts poursuivent en vous un mouvement profond. Hylee caresse sa poitrine, puis se glisse entre ses cuisses. Les gestes de Remerii se désordonnent chaque fois que Hylee la touche, et cette perte de mesure rend son attention plus ardente encore.")],
        [N("Vous échangez les places. Hylee s’appuie contre la pierre, Remerii entre ses jambes ; vous l’embrassez et caressez Remerii pendant que sa langue donne à Hylee ce qu’elle réclame. Hylee garde une main autour de votre désir, l’autre sur votre chaleur, de sorte que personne ne devient le simple soutien de la scène.")],
        [N("Hylee jouit contre la bouche de Remerii, puis la relève pour l’embrasser. Vous les laissez partager ce frisson quelques secondes avant qu’elles ne vous allongent entre elles. Remerii se place à votre bouche ; Hylee revient autour de votre désir, et leurs doigts se relaient en vous en suivant les réponses de tout votre corps.")],
        [N("Votre orgasme monte de deux foyers réunis. Hylee maintient sa bouche sur vous, Remerii garde ses doigts profondément en vous, et leurs mains se rejoignent sur votre ventre. Remerii jouit presque au même instant sous votre langue ; Hylee l’embrasse au-dessus de vous, puis revient recueillir vos derniers tremblements sans séparer les corps.")],
        [N("Le calme vous laisse tous trois sous la même étoffe. Hylee remet une mèche de Remerii en place ; vous partagez l’eau et les gestes de soin sans dresser d’inventaire anatomique. Remerii pose sa tête contre votre poitrine, une jambe mêlée à celle d’Hylee, et reçoit simplement le confort qu’elle aurait d’ordinaire organisé pour les autres.")],
        [H("Je n’ai fait aucun commentaire pendant tout ce temps."), R("Tu viens de compromettre cette donnée."), P("On retiendra surtout que tu as perdu le compte."), N("Remerii rit, referme le manteau sur vous deux et choisit elle-même de lier vos trois mains pour reprendre le sentier.")],
      ],
    },
    ellipse: [
      [N("Remerii étend le manteau dans l’abri au lieu d’annoncer le retour. Hylee reconnaît une décision inhabituelle et, pour une fois, ne l’interrompt pas.")],
      [R("Je veux que nous restions."), H("Tu vois ? Quatre mots. Aucun rapport nécessaire."), N("Remerii l’embrasse avant que la leçon ne continue.")],
      [N("Elle vous embrasse ensuite avec la même franchise. Hylee vient dans son dos, présente sans reprendre l’initiative qu’elle vient enfin d’assumer.")],
      [N("Les vêtements s’ouvrent sous le manteau. Remerii place vos mains, puis accepte que leurs chemins changent et que sa propre mesure se perde.")],
      [N("Hylee révèle par un regard les habitudes qu’elles partagent déjà. Vous les rejoignez sans devenir traducteur, et leurs deux attentions apprennent vos réponses.")],
      [N("Trois souffles gagnent sur le vent. La pierre garde le secret du plaisir qui circule, change de centre et revient jusqu’à ce que personne ne demeure à l’écart.")],
      [H("Je n’ai pas ri."), R("Tu vas le faire maintenant."), N("Hylee éclate effectivement de rire, puis embrasse Remerii avec une tendresse sans moquerie.")],
      [N("Vous remettez les vêtements et le manteau en place. Remerii prend vos deux mains sur le sentier sans inventer de raison pratique à ce choix.")],
    ],
  },
  {
    slug: "contre-le-vent",
    labels: {
      femme: "Contre le vent — inventer une chaleur conduite à trois",
      homme: "Contre le vent — laisser leurs deux habitudes faire place à votre rythme",
      intersexe: "Contre le vent — composer trois désirs sans centre fixe",
    },
    detail: "Le trio refuse de désigner une meneuse. Hylee et Remerii commencent par un geste qui leur appartient, puis vous y ménagent une place active ; les initiatives tournent comme le manteau et aucune ne devient l’assistante d’une autre.",
    climax: { tendre: 5, suggestif: 5, explicite: 7, ellipse: 5 },
    tendre: [
      [N("Vous atteignez l’abri en riant d’avoir tenté de marcher à trois sous un manteau prévu pour deux. Hylee s’appuie au mur ; Remerii replace automatiquement sa capuche, geste si ancien qu’aucune ne semble le remarquer.")],
      [P("Je refuse de départager celle qui avait raison sur le chemin."), H("Parfait. Nous avions décidé de t’accuser ensemble."), R("Pour une fois, son résumé est exact."), N("Elles vous encadrent avec la satisfaction de deux conspiratrices.")],
      [N("Hylee embrasse Remerii avant de vous regarder. Remerii répond, lui caresse la joue, puis vous tend la main sans rompre leur proximité. Vous entrez dans un mouvement déjà vivant au lieu de le remplacer.")],
      [N("Chacun invente une règle simple : aucune main inutilisée, aucun baiser isolé, aucune personne chargée de distribuer les places. Les règles sont aussitôt détournées par des rires et des contacts imprévus.")],
      [N("Vous glissez entre elles, puis les laissez se retrouver au-dessus de votre épaule. Les fronts, les joues et les bouches circulent. Remerii surprend Hylee d’une morsure tendre ; Hylee lui vole son sérieux en retour.")],
      [N("Le plaisir doux arrive sans vainqueur ni centre durable. Deux personnes soutiennent toujours la troisième, puis les positions changent jusqu’à ce que vos trois frissons se répondent sous l’étoffe.")],
      [R("Notre méthode était dépourvue de toute rigueur."), H("Et pourtant, tu veux la recommencer."), P("Je propose une réplication au retour."), N("Elles se tournent ensemble vers vous, déjà liguées contre votre ton savant.")],
      [N("Vous quittez l’abri côte à côte. Le manteau passe d’une épaule à l’autre selon les rafales et les mains restent liées même lorsqu’il ne protège plus personne correctement.")],
    ],
    suggestif: [
      [N("L’abri vous accueille avec un mur sec et un banc trop étroit. Hylee se laisse tomber contre Remerii ; cette dernière replace sa capuche, puis garde la main sur sa joue plus longtemps que le geste ne l’exige.")],
      [P("Pas d’arbitre ce soir."), H("Très bien. Nous allons prendre les décisions à deux."), R("À trois, Hylee."), H("Je vérifiais si tu suivais."), N("Leur baiser empêche la discussion de devenir sérieuse.")],
      [N("Elles commencent l’une contre l’autre, étoffes ouvertes et mains déjà sûres. Vous les regardez jusqu’à ce que Remerii vous attire par le poignet et que Hylee vous accueille entre leurs corps sans interrompre le baiser.")],
      [N("Les places tournent. Une bouche en cherche une autre pendant que deux paires de mains réchauffent la troisième personne. Chaque initiative oblige les deux autres à répondre ensemble plutôt qu’à patienter.")],
      [N("Le manteau glisse au sol et devient un refuge. Hylee perd son rire sous vos caresses ; Remerii perd sa mesure sous celles d’Hylee ; vous perdez toute envie de distinguer laquelle des deux vous trouble le plus.")],
      [N("Le plaisir traverse le trio par vagues. Quand l’une approche de sa limite, les deux autres la soutiennent et poursuivent leur propre désir l’une contre l’autre, jusqu’à ce que trois abandons distincts appartiennent au même mouvement.")],
      [H("Aucun arbitre."), R("Aucune gagnante."), P("Et trois personnes incapables de repartir."), N("Hylee vous embrasse ; Remerii termine la phrase contre sa bouche : « conclusion acceptable ».")],
      [N("Les vêtements retrouvent approximativement leur place. Sur le chemin, elles vous encadrent encore et se renvoient au-dessus de votre épaule les détails qu’elles prétendent vouloir améliorer.")],
    ],
    explicite: {
      femme: [
        [N("Vous arrivez dans l’abri après avoir tenté de marcher à trois sous un manteau trop étroit. Hylee s’appuie au mur, essoufflée de rire ; Remerii replace sa capuche avec un automatisme tendre, puis garde les doigts sur sa joue. Le silence change. Elles s’embrassent sans vous demander de choisir laquelle regarder."), P("Pas d’arbitre. Pas de tour de rôle.")],
        [N("Remerii acquiesce contre la bouche d’Hylee et vous tend la main. Vous entrez dans leur étreinte ; Hylee embrasse votre gorge pendant que vous trouvez les lèvres de Remerii. Vos trois mains se croisent sur les tailles et les nuques, déjà incapables d’attribuer un geste à une seule relation.")],
        [N("Vous ouvrez la tunique d’Hylee ; Remerii libère votre poitrine. Hylee défait à son tour le col de Remerii. Les bouches circulent entre les seins découverts, les épaules rougies par le froid et les lèvres qui réclament encore. Chaque fois que deux corps se rapprochent, le troisième est saisi par une main et ramené au mouvement.")],
        [N("Le manteau devient un lit étroit sur la pierre. Remerii s’allonge au centre sans conserver cette place : Hylee descend entre ses cuisses pendant que vous l’embrassez, puis Remerii vous attire au-dessus d’elle et caresse votre intimité ouverte. Sa main libre demeure dans les cheveux de Hylee, qui répond à chaque frisson donné.")],
        [N("Vous faites rouler Hylee sur le dos et prenez sa place entre les jambes de Remerii. Votre langue trouve sa chaleur pendant qu’elle embrasse Hylee au-dessus de vous. Hylee glisse deux doigts en vous, puis tend la main vers Remerii ; celle-ci la prend et la guide sur son sein, maintenant la chaîne intacte.")],
        [N("Remerii jouit sous votre bouche. Son cri se perd dans le baiser de Hylee, qui la garde contre elle pendant que vous remontez. Elles vous allongent ensemble ; Remerii vient contre votre cuisse, Hylee à votre bouche, et leurs doigts se rejoignent dans votre chaleur avant de trouver deux rythmes complémentaires.")],
        [N("Votre plaisir monte pendant que vous caressez Hylee entre les cuisses. Remerii frotte son corps encore sensible contre votre jambe et embrasse Hylee par-dessus votre poitrine. Hylee jouit sous votre main, bouche ouverte contre celle de Remerii ; ses contractions accélèrent les doigts qu’elles gardent toutes deux en vous.")],
        [N("Votre orgasme les saisit ensemble : Hylee maintient la pression sur votre point sensible, Remerii poursuit les mouvements profonds, puis leurs mains s’immobilisent seulement lorsque votre corps relâche enfin leurs épaules. Elles restent embrassées au-dessus de vous quelques secondes, et vous les ramenez contre votre bouche dès que votre souffle le permet.")],
        [N("L’après n’a pas de centre non plus. Vous essuyez la peau de Remerii pendant qu’elle donne à boire à Hylee ; Hylee vous couvre toutes deux et embrasse les doigts qui l’ont fait trembler. Les confidences restent minuscules : un geste à garder, un autre à ralentir, et l’assurance que personne n’a attendu hors de la scène.")],
        [R("Méthode dépourvue de rigueur."), H("Tu veux la recommencer."), P("Elle veut surtout corriger notre échantillon."), N("Elles se liguent pour vous faire taire sous deux baisers simultanés. Le retour se fait ensuite sous le manteau, trois épaules mal couvertes et trois mains obstinément liées.")],
      ],
      homme: [
        [N("Vous atteignez l’abri après une marche impossible à trois sous un manteau trop étroit. Hylee s’appuie au mur, encore secouée de rire ; Remerii replace sa capuche avec un geste ancien, puis garde les doigts sur sa joue. Leur baiser commence sans qu’aucune ne vous demande de trancher quoi que ce soit."), P("Pas d’arbitre. Et pas de tour de rôle.")],
        [N("Remerii vous tend la main sans quitter Hylee. Vous entrez dans leur étreinte ; Hylee embrasse votre gorge, vous trouvez la bouche de Remerii et celle-ci garde une paume sur la taille de Hylee. Les contacts composent déjà un seul mouvement à trois plutôt que deux invitations parallèles.")],
        [N("Hylee ouvre votre chemise et descend vers votre ceinture. Vous libérez la poitrine de Remerii pendant qu’elle défait la tunique d’Hylee. Les bouches circulent ; lorsque le désir se dresse contre le ventre de Hylee, les deux femmes le prennent entre leurs mains jointes et apprennent votre souffle à travers leurs propres baisers.")],
        [N("Le manteau devient un lit étroit sur la pierre. Remerii s’allonge au centre, Hylee descend entre ses cuisses et vous embrassez la mage. Remerii vous caresse tout en gardant une main dans les cheveux de Hylee. Le plaisir donné par l’une nourrit directement celui qu’elle donne à l’autre.")],
        [N("Vous faites rouler Hylee sur le dos et prenez sa place entre les jambes de Remerii. Votre bouche poursuit ce qu’elle a commencé tandis que Remerii embrasse Hylee au-dessus de vous. Hylee garde une main autour de votre désir et l’autre sur la poitrine de Remerii, reliant les deux rythmes sans réclamer le centre.")],
        [N("Remerii jouit sous votre langue, son cri contenu contre la bouche d’Hylee. Elles vous relèvent ensemble et font asseoir Hylee sur le manteau. Remerii soutient son dos ; vous entrez lentement en elle. Hylee vous accueille en restant tournée vers Remerii, qu’elle embrasse à chaque mouvement de vos hanches.")],
        [N("Le plaisir de Hylee monte sous vos mouvements. Remerii caresse sa poitrine, puis sa chaleur autour de vous ; vous l’attirez assez près pour qu’elle reçoive aussi votre bouche et votre main. Hylee jouit entre vos deux corps, serrant Remerii contre elle tandis que ses contractions vous rapprochent de votre propre limite.")],
        [N("Vous jouissez en Hylee, retenu par ses jambes et par la main de Remerii sur votre bassin. Remerii embrasse son visage pendant les dernières secousses, puis vous garde tous deux contre elle. Aucun corps ne se retire aussitôt ; le plaisir se défait dans une étreinte qui reste triangulaire jusqu’au bout.")],
        [N("Après, vous prenez soin de Remerii tandis qu’elle donne de l’eau à Hylee ; Hylee vous couvre tous deux et embrasse alternativement vos doigts. Vous nommez chacun un geste à garder sans transformer l’instant en bilan. Le vent remue le toit et confirme seulement que l’abri tient encore.")],
        [R("Une méthode absolument dépourvue de rigueur."), H("Tu veux la reproduire."), P("Avec un manteau plus large."), N("Elles se liguent pour vous faire taire sous deux baisers. Le retour vous trouve encore enlacés sous la même étoffe, incapables de marcher droit et peu disposés à essayer.")],
      ],
      intersexe: [
        [N("Vous atteignez l’abri après une marche impossible à trois sous un manteau trop étroit. Hylee s’appuie au mur, encore secouée de rire ; Remerii replace sa capuche avec un geste ancien et garde les doigts sur sa joue. Leur baiser commence sans exclure ni convoquer votre corps comme un problème à résoudre."), P("Pas d’arbitre. Aucun tour de rôle.")],
        [N("Remerii vous tend la main sans quitter Hylee. Vous entrez dans leur étreinte ; Hylee embrasse votre gorge, vous trouvez la bouche de Remerii et celle-ci garde une paume sur la taille de Hylee. Vos trois corps construisent un mouvement commun avant même que les vêtements ne s’ouvrent.")],
        [N("Hylee libère votre poitrine ; Remerii descend jusqu’aux deux expressions de votre désir. Sa main entoure ce qui se dresse pendant que ses doigts caressent votre chaleur. Vous ouvrez leurs tuniques et elles s’embrassent au-dessus de vous, ajustant leurs gestes à tout ce qui répond sans hiérarchie imposée.")],
        [N("Le manteau devient un lit étroit sur la pierre. Remerii s’allonge au centre, Hylee entre ses cuisses et vous l’embrassez. La main de Remerii entoure votre désir ; ses doigts libres glissent en vous. Elle reste liée à Hylee par les cheveux qu’elle caresse et par chaque mouvement de langue reçu.")],
        [N("Vous prenez la place de Hylee entre les jambes de Remerii. Votre bouche poursuit son plaisir tandis qu’elle embrasse Hylee. Hylee s’agenouille près de vous, prend votre désir dans sa bouche et maintient une main dans votre chaleur ; elle vous donne deux rythmes sans perdre de vue les réactions de Remerii sous votre langue.")],
        [N("Remerii jouit la première et ramène Hylee vers sa bouche. Vous les laissez s’embrasser quelques secondes avant qu’elles ne vous allongent ensemble. Remerii vient à votre bouche, Hylee poursuit autour de votre désir, et leurs doigts se rejoignent en vous. Votre main reste entre les cuisses de Remerii, la tenant dans le mouvement.")],
        [N("Hylee se presse contre votre cuisse, guidée par Remerii, tandis que vous recevez leurs attentions réunies. Son plaisir éclate contre votre peau ; Remerii l’embrasse à travers les secousses et Hylee garde sa bouche sur votre désir, ses doigts en vous, refusant de rompre la cadence qui vous porte au bord.")],
        [N("Votre orgasme traverse les deux foyers de votre corps au même instant. Les mains de Hylee et Remerii se rejoignent sur votre ventre, leurs bouches se trouvent au-dessus de vous, et toutes deux maintiennent les gestes choisis jusqu’à ce que vos muscles se relâchent. Vous les ramenez contre vous sans séparer leur étreinte.")],
        [N("L’après circule lui aussi : vous prenez soin de Hylee, elle donne de l’eau à Remerii, Remerii nettoie doucement votre peau sans réduire votre corps à une liste. Chacun nomme un geste à garder. Le vent frappe la pierre, incapable de rendre solitaire l’espace créé sous le manteau.")],
        [R("Aucune rigueur dans cette méthode."), H("Tu veux la refaire."), P("Avec exactement les mêmes variables."), N("Elles se liguent pour vous faire taire sous deux baisers. Le chemin du retour vous trouve sous la même étoffe, trois mains liées et aucun centre fixe.")],
      ],
    },
    ellipse: [
      [N("Dans l’abri, Remerii replace la capuche de Hylee. Le geste ancien dure assez longtemps pour devenir un baiser.")],
      [P("Pas d’arbitre."), H("Alors nous décidons à deux."), R("À trois."), N("Leur sourire commun annonce que vous venez déjà de perdre le contrôle social de la scène.")],
      [N("Elles commencent l’une contre l’autre, puis vous tendent deux mains sans interrompre leur mouvement. Vous entrez dans une proximité qui existait avant vous et s’ouvre volontairement.")],
      [N("Le manteau glisse sur la pierre. Les vêtements suivent ; chaque fois que deux corps se rapprochent, le troisième est ramené par une paume ou un baiser.")],
      [N("Les places tournent sans ordre fixe. Hylee rit, Remerii perd la mesure et vous abandonnez toute idée de devoir distribuer équitablement chaque seconde.")],
      [N("L’abri conserve la suite : trois plaisirs reliés, trois abandons différents et aucun instant où l’une attend seule que les autres aient terminé.")],
      [R("Aucune rigueur."), H("Tu veux recommencer."), P("Nous prendrons un manteau plus grand."), N("Deux baisers simultanés vous imposent enfin le silence.")],
      [N("Vous repartez à trois sous l’étoffe. Elle couvre mal les épaules, mais les mains liées empêchent désormais le vent de vous séparer.")],
    ],
  },
];

export const HYLEE_REMERII_WIND_ROUTES = manualHRRoutes(CONTEXT, seeds);
