import type { ChoiceData, DialogueLine, Effects } from "./game-data";
import type { CrossQuestProgress } from "./cross-quests";
import { validAnchorState, type AnchorState } from "./anchor-operation";
export const HR_KEY = "hyleeRemerii";
export const HR_OPEN = "cross-hr-dates-unlocked";
export type HRBeat = { intro: DialogueLine[]; choices: ChoiceData[]; cast?: string[]; responseCast?: string[] };
export type HRScene = HRBeat & { id: string; title: string; location: string; spot: string; cast: string[]; beats: HRBeat[]; music: string };
export type HRState = { branch?: "standard" | "double"; configuration?: "waiting" | "separate" | "refused" | "accepted"; prepared?: boolean; anchor?: AnchorState; recognitionDay?: number; checkpoint?: { sceneId: string; round: number; picks: string[] }; choices: Record<string,string[]> };
export const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
export const H = (text: string, mood = "soft"): DialogueLine => ({ speaker: "Hylee", text, mood });
export const R = (text: string, mood = "calm"): DialogueLine => ({ speaker: "Remerii", text, mood });
export const P = (text: string): DialogueLine => ({ speaker: "{player}", text });
export const Q = (id: string, text: string, response: DialogueLine[], effects: Effects = {}, stat: ChoiceData["stat"] = "lucidite"): ChoiceData => ({ id, text, response, effects, stat });
export const HR_TITLES = ["Après les Serres", "Quelque chose dans les relevés", "La distance correcte", "Ce qu’on dit quand on a peur", "Ce qu’on n’a pas su dire", "Ce qui existait déjà", "Les Trois Points d’Ancrage"];
export const HR_OBJECTIVES = ["Retrouver Hylee et Remerii à Mir’Aldas.", "Comparer les relevés à la bibliothèque.", "Reconnaître les terrasses périphériques des Serres.", "Convenir du rôle d’Hylee dans l’opération.", "Revoir Hylee, puis Remerii, après leur dispute.", "Les rejoindre à la résidence avant le départ.", "Préparer les mécanismes, neutraliser les ancrages et retrouver les deux mages au col."];
export const HR_LETTERS = [
 { id: "cross-hr-letter-reports", stage: 1, subject: "Les relevés", body: ["Les copies seront à la bibliothèque. Je vous y attends lorsque vous pourrez venir. — Remerii", "Prends quelque chose pour retenir les feuilles. Elle a déjà pris les trois presse-papiers. — Hylee"] },
 { id: "cross-hr-letter-detail", stage: 2, subject: "La deuxième secousse", body: ["J’ai retrouvé le récit du carrier. Il a compté deux secousses, pas trois. La dernière venait de la charrette. — Hylee", "Exact. J’ai barré la troisième sur notre copie. Garde l’original. — R."] },
 { id: "cross-hr-letter-bag", stage: 5, subject: "Le sac bleu", body: ["Nous partons avec les deux cordes. Le sac bleu est réparé. — Remerii", "Par moi. Elle a seulement tenu la boucle. Nous mangerons avant de partir ; il y a de la place. — Hylee"] },
 { id: "cross-hr-letter-window", stage: 6, subject: "Le passage du col", body: ["Le poste nous laissera gagner les terrasses après la relève. Le portail reste hors de portée. Nous repartons si le chemin n’est plus libre. — Remerii", "J’ai essayé les gants. Cette fois, je peux fermer les doigts. — Hylee"] },
];
export function hrUnlocked(g: { flags: string[]; relationships: Record<string,{stage:number}> }) { return g.flags.some(f => ["main-story-act-1-complete","main-story-complete"].includes(f)) && g.relationships.hylee?.stage >= 5 && g.relationships.remerii?.stage >= 5; }
export function hrIndividualIntimacy(flags: string[], person: "hylee" | "remerii") { return flags.some(f => f === `home-intimate:${person}` || f.startsWith(`date-intimate:date-${person}-`)); }
export function createHRProgress(day: number): CrossQuestProgress { return { id: HR_KEY, stage: 0, startedDay: day, stageStartedDay: day, letters: [], hr: { choices: {} } }; }
export function hydrateHR(p: CrossQuestProgress): CrossQuestProgress {
 const h = p.hr || { choices: {} };
 return { ...p, stage: Math.max(0, Math.min(7, Math.floor(Number(p.stage)||0))), letters: Array.isArray(p.letters) ? p.letters.filter(e => HR_LETTERS.some(l => l.id === e.id)) : [], hr: { ...h, choices: h.choices && typeof h.choices === "object" ? h.choices : {}, anchor: validAnchorState(h.anchor) ? h.anchor : undefined, checkpoint: h.checkpoint && typeof h.checkpoint.sceneId === "string" && Number.isInteger(h.checkpoint.round) && h.checkpoint.round >= -1 && Array.isArray(h.checkpoint.picks) && h.checkpoint.picks.every(p => typeof p === "string") ? h.checkpoint : undefined } };
}
export function hrAmbient(stage: number): DialogueLine[] {
 if (stage === 4) return [N("La chaise d’Hylee reste vide à l’atelier. Remerii l’a dégagée des livres, puis a remis les livres ailleurs. À la résidence, Hylee raccommode la même lanière sans venir la chercher.")];
 if (stage === 5) return [N("Hylee pose une boucle sur la table. Remerii rapproche la lampe. Elles essaient deux trous, échangent le poinçon et reprennent leur couture.")];
 if (stage > 1 && stage < 4) return [N("Une feuille dépasse du livre de Remerii. Hylee la retourne avant qu’elle soit rangée : au dos, une heure manque encore. Remerii lui passe la plume.")];
 return [];
}
const S = (id: string, title: string, spot: string, intro: DialogueLine[], choices: ChoiceData[], beats: HRBeat[] = [], cast = ["hylee","remerii"], music = "mage-city"): HRScene => ({ id, title, location: spot.startsWith("rocky-") ? "rocky-spires" : "miraldas", spot, intro, choices, beats, cast, music });
export const HR_SCENES: HRScene[] = [
 S("cross-hr-01", HR_TITLES[0], "miraldas-atelier", [
 N("Une caisse venue des Serres occupe la place du banc d’essai. La poussière rouge a traversé la toile. Remerii en éloigne son livre ; Hylee, accroupie, retient le couvercle avec son genou."), H("Tu peux tirer le dernier clou ? Il tourne dans le bois."), N("Vous prenez la pince. Le clou cède avec une plainte. À l’intérieur, des relevés et deux instruments cassés ; aucun fragment du portail."),
 R("Posez la pince. Il y a des éclats sous le tissu."), H("Je les ai vus."), N("Hylee replie la toile autour d’eux avant de sortir les feuilles. Remerii lui prend une copie des mains pour la lire ; Hylee conserve l’autre."),
 R("Trois secousses au poste nord. Puis deux au retour du convoi."), P("Ils ont vu quelque chose tomber ?"), R("Pas d’ici. Le rapport dit seulement que la passerelle bougeait."), H("Les heures ne sont pas les mêmes sur les deux feuilles."), N("Elle les rapproche. Remerii laisse aussitôt son instrument et se penche sur la seconde."),
 H("Si ça continue sous le portail, ça ne va pas disparaître parce qu’on est rentrés."), R("Non. J’ai demandé qu’on m’envoie les originaux."), H("Nous, alors. J’aimerais les voir aussi."), R("Vous les avez dans les mains."), H("Les originaux. Quand ils arriveront."), N("Remerii regarde la feuille, puis Hylee. Elle finit par hocher la tête."),
 R("Nous les lirons ensemble."), N("Hylee lui tend la copie. Au passage, elle retire une écharde accrochée à sa manche. Remerii attend que ses doigts aient fini avant de replier le bras."),
 ], [
 Q("cross-hr-01-copy", "Proposer de classer les copies par heure.", [P("Je peux remettre les témoignages dans l’ordre. Vous me direz ce qui manque."), H("Je prends ceux du convoi. Ils ont écrit au dos aussi."), R("Laissez les trous dans la liste ; ne leur inventons pas une heure pour que tout s’aligne."), N("Vous dégagez une place sur le banc. Hylee pose sa feuille près de celle de Remerii et tire un tabouret vers vous.")], { trust: 1, relationshipEffects: { remerii: { trust: 1 } } }),
 Q("cross-hr-01-source", "Demander où trouver les témoins encore en ville.", [H("Le carrier vient demain chercher son reçu. J’ai gardé son nom."), R("Demandez-lui seulement ce qu’il a vu. Il a déjà reçu assez d’explications de gens qui n’étaient pas là."), P("Je noterai ses mots."), N("Hylee vous montre le nom, souligné une seule fois dans la marge.")], { trust: 2 }),
 Q("cross-hr-01-sure", "Dire que Remerii saura certainement régler le problème seule.", [R("Je ne sais pas encore ce qui l’alimente.", "strict"), H("Et j’aimerais éviter de préparer des affaires pour un départ dont on me préviendrait à la porte."), N("Remerii repose la feuille entre vous trois."), R("Personne ne part ce soir. Commençons par lire.")], { trust: -2 }),
 ]),
 S("cross-hr-02", HR_TITLES[1], "miraldas-archives", [
 N("La bibliothèque vous a réservé le bout d’une table. Des copies s’étendent sous trois presse-papiers différents. Hylee apporte une feuille pliée en quatre, dont le bord porte une trace de farine."), H("Le carrier avait noté ça sur le reçu de son déjeuner. Il n’y a eu que deux secousses. La troisième, c’était sa charrette."), R("Vous lui avez demandé combien de temps les roues avaient tremblé ?"), H("Oui. Il a refait le bruit. Deux fois. Très fort."), N("Remerii barre un chiffre. Le bibliothécaire lève les yeux ; Hylee lui fait signe qu’elle n’a pas l’intention de refaire la démonstration."),
 P("Les gardes étaient ici. Ils pouvaient voir la terrasse du centre, mais pas celle de gauche."), N("Vous posez le doigt sur la copie du chemin. Remerii rapproche sa chaise."), R("Alors ces deux rapports décrivent probablement la même secousse."), H("Et celle-ci vient après, plus à droite."), N("Elle relie deux heures au crayon. Le trait atteint une petite terrasse jusqu’alors couverte par le presse-papier."),
 R("Trois points éloignés du portail. S’ils répondent ainsi, ils pourraient le maintenir depuis les abords."), P("Des ancrages ?"), R("Peut-être. Nous pouvons aller vérifier les mécanismes périphériques sans approcher l’ouverture."), H("Le centre tire les deux autres. Regarde l’heure du deuxième relevé."), N("Remerii suit le trait jusqu’au bout. Elle hoche la tête et corrige son propre dessin."), R("Oui. C’est le centre qu’il faudra regarder d’abord."),
 ], [
 Q("cross-hr-02-order", "Noter séparément ce que les témoins ont vu et ce que vous en déduisez.", [P("Je mets les secousses ici. Les ancrages, au crayon."), R("Gardez de la place autour. Nous aurons des corrections."), H("Tu peux me laisser le dessin ? J’arrive mieux à suivre quand je le refais."), N("Elle recopie les passerelles tandis que Remerii indique les positions connues des postes.")], { trust: 1, relationshipEffects: { remerii: { trust: 2 } } }),
 Q("cross-hr-02-trace", "Demander à Hylee de comparer les trois terrasses.", [H("Celle du centre est reliée aux deux autres. Et celle de droite a une sortie derrière."), R("Bien vu. Cela pourrait nous laisser un repli."), H("Ou être un escalier écroulé. Je l’entoure aussi au crayon."), N("Remerii sourit brièvement et lui tend la gomme.")], { affection: 1, trust: 2 }),
 Q("cross-hr-02-certain", "Rédiger tout de suite un rapport annonçant trois ancrages.", [R("Écrivez trois terrasses. Nous ignorons encore ce qu’elles portent.", "strict"), H("On a déjà assez de copies qui se répètent. Celle-ci peut attendre."), N("Vous rayez le mot. La nouvelle ligne tient moins de place.")], { relationshipEffects: { remerii: { trust: -2 } } }),
 ]),
 S("cross-hr-03", HR_TITLES[2], "rocky-spires-pass", [
 N("Le portail occupe une entaille de la montagne, si loin que la brume passe devant lui en couches séparées. Sa lueur atteint pourtant les bords de vos cartes."), N("Sous le col, trois terrasses entourent un ravin. Des bandes sombres à motifs verts pendent à deux balustrades ; la pierre taillée autour des anneaux porte d’autres signes, anguleux, étrangers aux bannières."),
 R("Nous restons sur le chemin haut pour aujourd’hui."), P("Je vois les poignées depuis ici. Une sur chaque palier."), H("Et les fentes sous les anneaux. Elles ne s’allument pas ensemble."), N("Vous notez l’ordre. Hylee s’avance vers un rocher qui masque une partie de la terrasse orientale. Remerii lui barre le passage avec son bâton."), R("D’ici."), H("Je reste sur le sentier. Il me manque juste cet angle."), R("Je vais regarder."),
 N("Elle dépasse le rocher, vérifie le bord et revient décrire une gorge métallique. Hylee écoute sans tendre la main vers la carte."), H("Tu peux regarder si le sol tient. Après, je peux y aller aussi."), R("Une personne suffit à cet endroit."), H("Alors laisse-moi être cette personne quelquefois.", "determined"), N("Un bruit de chaînes arrive du ravin. Toutes deux se tournent aussitôt. Vous avez la pointe du crayon sur la seconde pulsation : B, puis C, puis A."), P("Le centre tire les autres. Ça recommence."), R("Oui. Reculez le papier sous votre manteau ; on repart avec cela."), H("Je l’ai vu aussi."),
 ], [
 Q("cross-hr-03-angle", "Montrer à Hylee la place depuis laquelle vous avez noté le cycle.", [N("Vous vous décalez sur la portion large du chemin. Hylee regarde une dernière fois, sans contourner le rocher."), H("C se vide plus lentement. Il faudra lui laisser du temps."), R("Je l’ajoute."), N("La remarque rejoint le relevé. Au retour, Hylee marche quelques pas devant.")], { trust: 2 }),
 Q("cross-hr-03-back", "Ranger le matériel et garder vos questions pour le retour.", [N("Vous attachez la carte. Remerii vérifie le chemin derrière le groupe ; Hylee vous demande le crayon pour ajouter un détail de mémoire."), H("Sinon, demain, ça sera devenu l’idée de personne."), N("Elle signe sa note et vous rend le crayon.")], { trust: 1, relationshipEffects: { remerii: { trust: 1 } } }),
 Q("cross-hr-03-proof", "Suggérer à Hylee un petit essai pour montrer ce qu’elle peut faire.", [H("Ici ? Pour le plaisir de nous faire voir ?", "surprised"), R("Rangez cette idée avec le matériel."), H("Je veux participer à ce qu’on prépare. Pas faire une démonstration pour obtenir une permission."), N("Vous reprenez le chemin du col sans essai.")], { trust: -3, relationshipEffects: { remerii: { trust: -1 } } }),
 ], [], ["hylee","remerii"], "tension"),
 S("cross-hr-04", HR_TITLES[3], "miraldas-atelier", [
 N("Hylee a dessiné trois anneaux au charbon sur la table. Des copeaux marquent les passerelles. Remerii a déplacé le copeau qui portait le nom d’Hylee jusqu’au bord du dessin."), H("Pourquoi là ?"), R("Vous maintiendrez la voie de retour."), H("Il n’y a rien à tenir à cet endroit. On l’a vérifié."), R("Il peut y avoir une rupture. Je veux savoir le chemin libre."), H("Tu as besoin de moi pour ça, ou tu veux me mettre derrière ?", "determined"), N("Remerii reprend le charbon. Il laisse une trace noire sur son pouce."),
 R("Le point A demandera une décharge visible depuis les postes. Si l’on vous distingue, nous ne pourrons plus choisir qui entendra parler de vous."), H("Je le sais. Et si personne ne fait rien, ce portail restera là. Il n’attendra pas que je sois prête à être vue."), R("Je peux maintenir A."), H("En gardant B et en nous couvrant ? Tout à l’heure tu as dit que non."), R("Je trouverai un autre angle."), H("On en a cherché pendant une heure. Le mien est utilisable."),
 N("Hylee replace son copeau. Remerii le retient du bout de l’ongle."), H("Je peux te dire quand ça devient trop lourd. Tu m’as appris à le sentir."), R("Une fois sur place, il sera trop tard pour apprendre ce que vous aviez mal évalué."), H("Alors je resterai toujours ici ? Parce que tu as déjà vu ce qu’on fait aux gens comme nous ?"), N("Remerii relève brusquement la tête."), R("Vous en parlez comme d’une histoire qu’on vous aurait racontée."), H("Je parle de demain. Je veux y être. Je ne te demande pas de trouver ça facile."), R("Vous voulez surtout que je vous dise oui."), N("Hylee retire sa main. Le petit copeau reste pris sous l’ongle de Remerii."),
 ], [
 Q("cross-hr-04-stop", "Proposer de poser le plan quelques instants.", [P("On peut poser le charbon. Vous n’êtes plus en train de regarder le dessin."), H("Je le regarde depuis le début."), R("Et vous continuez à ne pas vouloir voir ce qui vient après.", "strict")], { trust: 1 }),
 Q("cross-hr-04-hylee", "Rappeler qu’Hylee a répondu sur le risque du point A.", [P("Elle a dit combien de temps elle pouvait tenir."), R("Elle a dit combien elle voulait tenir."), H("Non. J’ai fait la différence. Tu m’as entendue.", "angry")], { trust: 2, relationshipEffects: { remerii: { trust: -1 } } }),
 Q("cross-hr-04-remerii", "Dire que l’expérience de Remerii devrait trancher.", [H("Alors pourquoi me demander un plan ?", "angry"), R("Je ne vous ai pas demandé de répondre pour moi, {player}."), N("Hylee se retourne vers Remerii, attendant toujours sa réponse.")], { trust: -3 }),
 Q("cross-hr-04-silence", "Les laisser poursuivre.", [N("Vous posez le registre. Hylee fixe la main qui retient le copeau."), H("Lâche-le."), R("Ce morceau de bois ne change rien."), H("Alors lâche-le.", "determined")]),
 ], [{ intro: [
 R("Vous croyez qu’il suffit de décider pour que les conséquences deviennent supportables."), H("Je n’ai jamais dit ça."), R("Moi, je sais ce que c’est que de n’avoir personne à appeler quand cela commence. Vous n’avez pas encore eu à l’apprendre.", "strict"), N("Hylee ne bouge plus. Derrière elle, la fenêtre claque doucement contre son crochet."), H("D’accord.", "sad"),
 N("Elle ramasse son gant, puis le second. Le copeau reste sur la table. Remerii regarde les gants et ouvre la main trop tard."), R("Hylee. Ce n’est pas ce que je voulais…"), H("Je sais ce que tu voulais dire.", "sad"), R("Je ne parlais pas de l’auberge."), N("Hylee lève enfin les yeux. Remerii n’achève pas la phrase suivante."), H("Je vais rentrer.", "sad"), N("Elle ferme la porte sans la claquer. Le charbon roule jusqu’au bord ; vous l’arrêtez avant qu’il tombe."),
 ], responseCast: ["remerii"], choices: [
 Q("cross-hr-04-after-plain", "Dire simplement qu’Hylee est partie blessée.", [R("Oui."), N("Remerii essuie son pouce. La marque ne part pas."), R("Laissez le plan. Je le rangerai.", "sad"), N("Elle ne remet pas le copeau d’Hylee au bord.")], { relationshipEffects: { remerii: { trust: 1 } } }),
 Q("cross-hr-04-after-quiet", "Laisser le registre et partir sans ajouter d’argument.", [N("Vous reposez le charbon près du dessin. Remerii reste debout tandis que vous gagnez la porte."), R("Si vous la voyez…"), N("Elle s’interrompt, puis secoue la tête."), R("Je lui parlerai moi-même.", "sad")]),
 ] }], ["hylee","remerii"], "imperial-lament-instrumental"),
 S("cross-hr-05", HR_TITLES[4], "miraldas-quarters", [
 N("Hylee répare une couture près de la fenêtre. Elle vous montre la chaise du menton. Le fil traverse deux fois le même trou."), H("Elle t’envoie ?", "sad"), P("Non."), H("Tant mieux. Je ne veux pas répondre à une lettre qu’elle te ferait réciter.", "sad"), N("L’aiguille bute. Hylee tire le fil en arrière et défait son dernier point."), H("Je sais qu’elle a souffert. Je l’écoute quand elle m’en parle. Mais elle sait où elle m’a trouvée.", "sad"), N("Elle pose enfin le vêtement sur ses genoux."), H("Je n’ai pas envie de sortir tout ce que j’ai vécu pour avoir le droit de dire que ça m’a fait mal.", "sad"), P("Tu n’as rien à me raconter de plus."), H("Je voulais qu’elle me garde une vraie place. Hier, j’avais l’impression qu’elle essayait surtout de trouver où me ranger.", "sad"),
 ], [
 Q("cross-hr-05-listen", "Lui demander si elle veut de la compagnie ou rester seule.", [H("Reste un peu. Tu peux tenir ce bord ?"), N("Vous tendez la couture. Cette fois, l’aiguille passe."), H("Je veux bien lui parler. Mais je ne vais pas commencer par la rassurer sur ce qu’elle m’a dit.")], { trust: 2 }),
 Q("cross-hr-05-excuse", "Faire remarquer que Remerii tient énormément à elle.", [H("Moi aussi, je tiens à elle. Ça n’a pas rendu sa phrase plus douce."), P("Tu as raison. Je voulais aller trop vite."), H("Alors reste ici deux minutes sans essayer de finir la conversation à sa place.")], { trust: -2 }),
 Q("cross-hr-05-blame", "Dire qu’elle devrait se passer de Remerii pour l’opération.", [H("Et laisser B tomber pendant que je tiens A ?"), N("Elle secoue la tête."), H("Je suis en colère. Je n’ai pas oublié ce qu’elle sait faire, ni envie de la perdre.")], { trust: -2 }),
 ], [
 { cast: ["remerii"], intro: [N("Plus tard, Remerii arrive à la résidence avec le registre sous le bras. Elle reste près de la porte. La même page est ouverte que lorsque vous l’avez quittée."), R("Elle est ici ?"), P("Elle a terminé sa couture."), R("Je sais ce qu’il faut reprendre dans le plan. Pour le reste…"), N("Elle referme le livre, l’ouvre, puis le referme vraiment."), R("Tout ce que je prépare finit par ressembler à une justification.")], choices: [
 Q("cross-hr-05-door", "Lui dire qu’Hylee veut bien l’entendre, puis lui laisser la porte.", [P("Elle veut bien vous entendre. Je peux l’appeler ; les mots, ce seront les vôtres."), R("Oui. Faites cela."), N("Remerii pose le registre hors de portée avant que vous frappiez.")], { relationshipEffects: { remerii: { trust: 2 } } }),
 Q("cross-hr-05-short", "Lui demander ce qu’elle dirait sans le registre.", [N("Remerii regarde le livre contre sa poitrine et l’abaisse."), R("Que j’ai été injuste."), P("Vous pouvez commencer là."), R("C’est assez court pour que je ne me perde pas en chemin.")], { relationshipEffects: { remerii: { trust: 1 } } }),
 ] },
 { cast: ["hylee","remerii"], intro: [
 N("Hylee ouvre. Elle regarde d’abord le livre sur le banc, puis Remerii. Vous reculez vers la fenêtre ; elles ont le passage entre elles."), R("Ce que je t’ai dit était injuste. Je savais assez de ce que tu as vécu pour ne pas te parler comme si rien ne t’avait jamais coûté.", "sad"), N("Hylee serre la poignée derrière elle, sans fermer."), R("J’ai eu peur qu’on te voie sur cette terrasse. Je me suis remise à chercher tous les moyens de t’en éloigner. Et quand tu as refusé, je t’ai blessée pour arrêter la discussion."), H("Tu pensais vraiment que je n’avais jamais été seule ?", "sad"), R("Non. Je n’ai aucune excuse pour l’avoir dit."),
 N("Le bois grince sous les doigts d’Hylee. Elle desserre sa prise."), H("La prochaine fois, dis-moi que tu as peur. Ne me dis pas que je ne comprends rien."), R("J’essaierai. Si je recommence à déplacer ton nom sans t’écouter, arrête-moi."), H("Je l’ai fait hier."), R("Oui. Et je ne me suis pas arrêtée."), N("Hylee baisse les yeux. Remerii attend ; le silence s’allonge sans qu’elle le remplisse."), H("Je ne peux pas te promettre que je ne me tromperai jamais."), R("Je ne peux pas te le promettre non plus."),
 H("Mais je peux te dire quand je ne tiens plus. Et tu peux m’aider à lâcher sans tout faire tomber."), R("Alors nous prévoirons cela dans le plan. Ensemble."), N("Hylee quitte enfin le seuil. Elle s’assoit près de Remerii et laisse une place pour le registre."),
 ], choices: [
 Q("cross-hr-05-return", "Apporter le livre, puis les laisser reprendre le dessin.", [N("Remerii demande à Hylee de replacer son copeau. Hylee prend le charbon à la place."), H("Il faut dessiner où la glace peut céder. Pas seulement où elle doit tenir."), R("Montre-moi."), N("Vous allez chercher une feuille propre. Elles discutent encore de ce passage lorsque vous revenez.")], { trust: 1, relationshipEffects: { remerii: { trust: 1 } } }),
 Q("cross-hr-05-tea", "Proposer de remettre le plan à demain et d’apporter à boire.", [H("Demain. J’ai assez parlé pour ce soir."), R("D’accord."), N("Vous sortez chercher de l’eau chaude. Derrière vous, Hylee pousse doucement le registre pour que Remerii puisse poser ses mains sur le banc.")], { affection: 1 }),
 ] },
 ], ["hylee"], "imperial-lament-instrumental"),
 S("cross-hr-06", HR_TITLES[5], "miraldas-quarters", [
 N("La relève du col n’est pas encore passée. Les sacs attendent près de la porte et une marmite refroidit sur la table. Hylee détache la longue épingle qui retient les cheveux de Remerii ; celle-ci penche la tête sans interrompre la lecture du billet."), H("Tu l’as encore enfoncée à travers deux mèches."), R("Elle tenait."), H("C’est ce que tu dis chaque fois."), N("L’épingle cède enfin. Hylee la pose hors de portée du bol avant d’aller chercher une troisième assiette."),
 P("Je tombe au milieu du repas ?"), H("Au bon moment. Sinon elle relit le billet jusqu’à ce que ce soit froid."), R("Le précédent annonçait une autre heure."), H("Et je te l’ai lu pendant que tu mangeais. On peut recommencer."), N("Remerii plie le papier. Hylee lui verse la partie la moins épaisse de la soupe, puis racle pour elle-même le fond de la marmite."),
 R("Vous faites encore cela."), H("Tu laisses tous les morceaux. Il faut bien que quelqu’un les mange."), R("Je pourrais changer d’avis."), H("Essaie. Il en reste."), N("Elle approche sa cuillère ; Remerii y prend un morceau sans reprendre son bol. Hylee reste un instant contre le dossier de sa chaise, la main posée sur son épaule."),
 H("On attendait déjà comme ça avant de te connaître. Pas les mêmes nouvelles."), R("Et pas toujours assez de bols."), H("Tu pouvais en acheter un deuxième."), R("Je n’avais pas prévu que vous resteriez aussi près du mien."), N("Le sourire d’Hylee se fait plus discret. Remerii lui prend brièvement les doigts sur son épaule, puis les libère pour qu’elle s’asseye."),
 ], [
 Q("cross-hr-06-bowl", "Partager le repas et leur demander comment elles occupaient ces attentes.", [H("Je lui posais des questions. Jusqu’à ce qu’elle prétende avoir besoin de silence."), R("J’avais réellement besoin de silence."), H("Tu répondais quand même."), R("Vous laissiez très peu de place au doute."), N("Vous vous servez. Le billet reste plié pendant qu’elles se disputent doucement le souvenir d’une soirée de pluie.")], { affection: 1, relationshipEffects: { remerii: { affection: 1 } } }),
 Q("cross-hr-06-help", "Prendre la marmite et proposer de faire réchauffer ce qui reste.", [R("Il y a encore assez de braises."), H("Je viens avec toi. Cette poignée tourne."), N("Remerii tend un linge à Hylee avant qu’elle touche le métal. Hylee le prend, l’effleure au poignet et vous aide à transporter la marmite.")], { trust: 1 }),
 Q("cross-hr-06-label", "Faire remarquer qu’elles auraient pu vous dire qu’elles étaient ensemble.", [H("On t’a dit où nous allions. On n’a pas toujours su dire le reste."), R("Et nous ne vous devons pas une version définitive de quelque chose que nous vivons encore."), N("Vous baissez votre cuillère. Hylee reprend la marmite et vous en propose malgré tout.")], { trust: -2, relationshipEffects: { remerii: { trust: -2 } } }),
 ], [], ["hylee","remerii"], "two-stars-night"),
];
const DOUBLE_BEAT: HRBeat = { intro: [
 N("Lorsque les bols sont vides, Hylee reste près de Remerii. Elle fait tourner l’épingle entre ses doigts."), H("Je voudrais te demander quelque chose. Et je préfère qu’on soit là tous les trois."), N("Remerii relève les yeux vers elle, puis vers vous."), H("Tu as envie de retrouver {player}, toi aussi ?"), R("Oui."), H("D’accord. Je pensais que oui. Je préférais l’entendre."), R("Je ne vais pas raconter ce qui nous appartient pour rendre ma réponse plus précise."), H("Je ne te le demande pas."),
 N("Hylee cesse de faire tourner l’épingle."), H("Je ne sais pas bien où me mettre quand je pense à toi et à {player} en même temps."), R("Je croyais pouvoir y réfléchir avant que vous posiez la question."), H("Tu as eu tout le repas."), N("Remerii laisse échapper un rire court. Sa main rejoint celle d’Hylee sur la table."), R("Un peu plus que cela, à vrai dire. Cela n’a pas suffi."), N("Elles se tournent vers vous sans retirer leurs mains."),
 ], choices: [
 Q("cross-hr-06-double-open", "Dire que vous aimeriez partager du temps avec elles, si elles en ont envie.", [P("Je ne sais pas encore à quoi cela ressemblerait. Mais j’aimerais vous retrouver ensemble, un jour où nous n’avons rien à préparer."), H("Moi aussi."), R("Alors commençons par rentrer des Serres. Je préfère avoir cette journée devant moi."), N("Hylee acquiesce. Elle rend l’épingle à Remerii sans quitter sa main.")]),
 Q("cross-hr-06-double-slow", "Leur dire que vous avez besoin de temps pour savoir ce que vous souhaitez.", [H("On peut en reparler."), R("Oui. Rien ne nous oblige à finir cette conversation avant le départ."), N("Vous rangez les bols ensemble. Remerii passe l’épingle dans sa manche au lieu de relever ses cheveux.")]),
 Q("cross-hr-06-double-separate", "Préférer, pour l’instant, continuer vos rencontres séparément.", [R("Je l’entends."), H("Ça ne m’empêche pas de vouloir te revoir."), N("Remerii acquiesce. Hylee ramasse les trois bols ; aucune ne s’écarte lorsque vous les aidez à débarrasser.")]),
 ] };
export function hrQuestScene(stage: number, hr: HRState): HRScene | undefined {
 if (stage < 6) { const s = HR_SCENES[stage]; return s && stage === 5 && hr.branch === "double" ? { ...s, beats: [...s.beats, DOUBLE_BEAT] } : s; }
 if (stage !== 6) return;
 if (!hr.anchor?.result || hr.anchor.result === "retreat") return S("cross-hr-07-prepare", HR_TITLES[6], "rocky-spires-pass", [
 N("Le poste vous laisse passer à la relève. Au-delà du dernier abri, les terrasses plongent dans la brume. Le portail reste bien plus haut, hors d’atteinte ; vous n’emprunterez aucun des chemins qui y mènent."), R("B alimente les deux autres. Je retiens sa charge. Hylee intervient sur A lorsque nous aurons vidé C."), H("Et je te dis quand j’approche de ma limite."), R("Je reprends la liaison à ce moment-là."),
 N("Vous vérifiez les poignées avec votre gant. Les mécanismes se manœuvrent à la main ; les signes indiquent leur position, pas un sort à prononcer."), P("Je m’occupe des verrous et je vous décris les repères."), H("Sur C, regarde toute la suite avant d’essayer. On a le temps de la revoir."), R("Deux ruptures, et nous nous retirons. Nous pourrons revenir avec les relevés conservés."), N("Hylee tend sa main à Remerii. Elles serrent leurs doigts une fois avant de gagner chacune leur poste."),
 ], [Q("cross-hr-07-ready", "Vérifier la corde de retour et gagner le premier mécanisme.", [N("Le nœud tient. Vous montrez votre gant aux deux mages pour signaler que vous êtes en place. Remerii relève son bâton ; Hylee attend la première pulsation, les yeux tournés vers les trois terrasses."), H("Je vous vois. On y va.", "determined")])], [], ["hylee","remerii"], "tension");
 return S("cross-hr-07-return", HR_TITLES[6], "rocky-spires-pass", [
 N(hr.anchor.result === "pressure" ? "Un bord du relevé a brûlé. Vous le gardez contre votre poitrine pendant la remontée ; les heures du dernier cycle restent lisibles. Derrière vous, les trois ancrages ont cessé de battre." : "Les cinq étapes du cycle sont notées. Vous rangez le relevé à l’abri de l’humidité ; derrière vous, les trois terrasses demeurent silencieuses."), N("Le portail luit encore au fond de la montagne. Les mécanismes périphériques sont neutralisés, mais l’ouverture reste une menace pour ceux qui gardent le col."),
 H("J’ai les doigts engourdis."), N("Remerii s’arrête aussitôt. Hylee ouvre et ferme les mains devant elle."), H("Ça revient. Je peux marcher."), R("D’accord."), N("Elle attend qu’Hylee remette son gant, puis reprend le chemin à sa hauteur. Hylee lui touche brièvement le bras."), H("Sur le dernier cycle, j’ai cru que tu allais reprendre avant le signal."), R("J’en ai eu envie."), H("Je sais."), R("Tu tenais."), N("Hylee garde les yeux sur le sentier pendant quelques pas. Elle finit par sourire."),
 P("Le poste voudra les heures."), R("Nous les leur donnerons. Ensuite, nous rentrons."), H("Et on mange quelque chose qui n’a pas voyagé dans ce sac."), R("Vous choisirez."), H("Je vais m’en souvenir."),
 ], [
 Q("cross-hr-07-report", "Confier vos notes au poste et les rejoindre pour le retour.", [N("Le garde recopie les heures. Vous revenez vers les deux femmes ; Hylee a pris une extrémité de la sangle du sac, Remerii l’autre. Elles vous laissent sa poignée centrale."), H("Il pèse moins qu’à l’aller."), R("Nous avons laissé les pièces cassées au poste."), H("Je parlais surtout de la montée. Mais oui, aussi."), N("Vous redescendez ensemble, assez proches pour parler sans hausser la voix.")], { trust: 2, relationshipEffects: { remerii: { trust: 2 } } }),
 Q("cross-hr-07-rest", "Proposer une pause à l’abri avant de redescendre.", [H("Oui. Là, je veux bien m’asseoir."), N("Remerii dégage une pierre plate et s’installe près d’elle. Hylee pose la tête contre son épaule ; Remerii lui tient le gant qu’elle a retiré."), R("Quelques minutes."), N("Vous vous asseyez de l’autre côté du sac. Quand les doigts d’Hylee ont retrouvé leur chaleur, elle le dit elle-même et vous repartez.")], { affection: 2, relationshipEffects: { remerii: { affection: 1 } } }),
 ], [], ["hylee","remerii"], "wild-calm");
}
export function hrRecognition(waiting = false): HRScene {
 return S(waiting ? "cross-hr-recognition-later" : "cross-hr-recognition", "Une place à la table", "miraldas-quarters", [
 N(waiting ? "Hylee vous garde une chaise. Le départ n’est plus une excuse pour remettre la conversation à demain." : "Le matériel est rendu et les relevés déposés. Hylee vous retrouve à la résidence ; Remerii a commandé trois boissons, sans rapport ouvert devant elle."), H("Je voudrais qu’on se revoie comme ça. Tous les trois, exprès. Sans qu’un portail nous fournisse la raison."), N("Remerii fait tourner son verre avant de regarder Hylee."), R("J’en ai envie aussi. Et j’aurai sûrement le réflexe d’essayer de prévoir la journée entière."), H("Je te laisserai choisir l’heure. Pour commencer."), R("Généreuse.", "smirk"), N("Hylee prend sa main sur la table. Remerii la serre, puis tourne vers vous son autre paume, ouverte."), R("Est-ce que vous voulez essayer ? Vous pouvez aussi vouloir nous voir séparément."),
 ], [
 { ...Q("cross-hr-config-accepted", "Proposer une première journée ensemble.", [P("Oui. Une journée, et on verra ce qui nous plaît."), H("J’ai déjà une idée."), R("Gardez-la jusqu’à ce que nous ayons fini de boire."), H("D’accord. Mais demain, pas de registre."), N("Remerii acquiesce. Hylee laisse sa main entre les vôtres.")]), requiresRelationship: [{ character: "hylee", stage: 5, trust: 22, affection: 22 }, { character: "remerii", stage: 5, trust: 22, affection: 22 }] },
 Q("cross-hr-config-separate", "Préférer continuer vos relations séparément.", [H("D’accord. Je voudrais quand même te revoir."), R("Moi aussi. Nous prendrons nos rendez-vous comme avant."), N("Remerii repose sa main près de celle d’Hylee. Aucune ne reprend la place qu’elle vous avait gardée.")]),
 Q("cross-hr-config-waiting", "Demander encore un peu de temps.", [R("Prenez-le. Revenez nous en parler quand vous saurez ce que vous voulez."), H("Pas besoin de recommencer toute la discussion. Tu nous diras."), N("Vous restez finir votre boisson. La table ne se vide pas à votre hésitation.")]),
 Q("cross-hr-config-refused", "Dire que vous ne souhaitez pas de rendez-vous à trois.", [H("Merci de le dire maintenant."), R("Nous n’en ferons pas la condition de nos autres rencontres."), N("Hylee reprend sa tasse. La conversation passe au repas du lendemain, sans vous demander de défendre votre réponse.")]),
 ], [], ["hylee","remerii"], "two-stars-night");
}
