import type { SocialScene } from "./social-scenes";
import { H, R, N, Q, HR_KEY } from "./hylee-remerii-cross-quest";

export const HR_AMBIENT_SCENES: SocialScene[] = [
  {
    id: "cross-hr-world-reports",
    title: "Le coin de la page",
    characters: ["hylee", "remerii"],
    locations: ["miraldas"],
    sublocations: ["miraldas-atelier", "miraldas-archives"],
    oneTime: true,
    priority: 110,
    mood: "soft",
    crossStage: { series: HR_KEY, min: 2, max: 3 },
    prompt: [
      N("Hylee garde un doigt sur une ligne du registre pendant que Remerii retourne la copie. Sans lever les yeux, cette dernière pousse vers elle la tasse posée trop près du bord."),
      H("Tu l’avais entourée de l’autre côté."),
      R("Il y a deux heures sur ce relevé."),
      H("Oui. Mais celle-ci, c’est l’arrivée de la charrette."),
      N("Remerii compare les pages, puis lui glisse le crayon."),
      R("Corrige. Je tiens le coin."),
      H("Tu disais déjà ça avec les cartes de route."),
      R("Et tu les laissais déjà s’enrouler sur elles-mêmes."),
    ],
    choices: [
      Q(
        "cross-hr-world-reports-help",
        "Poser votre tasse vide sur l’autre coin qui se soulève.",
        "lucidite",
        [
          N("Hylee peut enfin retirer sa main. Elle étire ses doigts avant de reprendre le crayon."),
          H("Merci. Je commençais à faire partie du mobilier."),
          R("Du mobilier qui conteste les légendes."),
          H("Du bon mobilier, donc."),
        ],
        { trust: 1, relationshipEffects: { remerii: { trust: 1 } } },
      ),
      Q(
        "cross-hr-world-reports-pass",
        "Les laisser terminer leur échange sans en devenir l’arbitre.",
        "sangFroid",
        [
          N("Remerii tourne la page seulement quand Hylee a levé le crayon. Vous les entendez encore discuter de l’heure en quittant la pièce."),
          H("Celle-là, je ne la comprends pas."),
          R("Moi non plus. Nous demanderons l’original."),
        ],
      ),
    ],
  },
  {
    id: "cross-hr-world-silence",
    title: "La chaise dégagée",
    characters: ["remerii"],
    locations: ["miraldas"],
    sublocations: ["miraldas-atelier"],
    oneTime: true,
    priority: 110,
    mood: "sad",
    crossStage: { series: HR_KEY, min: 4, max: 4 },
    prompt: [
      N("Remerii a retiré les livres de la chaise d’Hylee. Elle les reprend sur la table, cherche une autre place et finit par les poser au sol. Une écharpe oubliée reste pliée sur le dossier."),
      R("Vous cherchez le registre ?", "sad"),
      N("Le registre est ouvert devant elle. Aucun nouveau trait n’a rejoint le plan depuis votre dernier passage."),
    ],
    choices: [
      Q(
        "cross-hr-world-silence-stay",
        "Demander si vous pouvez rester sans parler à la place d’Hylee.",
        "resonance",
        [
          R("Oui. Prenez l’autre chaise."),
          N("Vous vous asseyez près de la porte. Elle laisse celle d’Hylee libre."),
          R("Je n’ai pas beaucoup avancé."),
          N("Elle ne précise pas de quel travail elle parle."),
        ],
      ),
      Q(
        "cross-hr-world-silence-leave",
        "Lui laisser le temps de préparer ses propres mots.",
        "sangFroid",
        [
          R("Je viendrai à la résidence plus tard."),
          N("Remerii referme le registre. Lorsque vous partez, elle prend enfin l’écharpe avec elle."),
          R("Merci d’être passé."),
        ],
        { trust: 1 },
      ),
    ],
  },
  {
    id: "cross-hr-world-buckle",
    title: "Deux trous plus loin",
    characters: ["hylee", "remerii"],
    locations: ["miraldas"],
    sublocations: ["miraldas-quarters", "miraldas-atelier"],
    oneTime: true,
    priority: 110,
    mood: "soft",
    crossStage: { series: HR_KEY, min: 5, max: 7 },
    prompt: [
      N("Hylee présente la boucle du sac bleu. Remerii rapproche la lampe avant qu’elle ne le demande."),
      H("Le deuxième trou."),
      R("Celui-là tirera sur la couture."),
      H("Je peux doubler le fil."),
      N("Remerii vérifie l’épaisseur du cuir, puis lui passe le poinçon."),
      R("Essaie. Je maintiens dessous."),
      H("Tu gardes bien tes doigts ?"),
      R("Je les garde mieux que tu ne gardais nos couteaux."),
      N("Hylee rit et attend tout de même qu’elle ait placé sa main avant de percer."),
    ],
    choices: [
      Q(
        "cross-hr-world-buckle-hold",
        "Leur tenir la lampe pendant qu’elles terminent ensemble.",
        "resonance",
        [
          N("Remerii libère une main pour retourner la boucle. Hylee tire sur la couture neuve ; rien ne bouge."),
          H("Ça tiendra."),
          R("Oui."),
          N("Elles reprennent le sac chacune par un côté pour le redresser, puis vous confient la poignée centrale."),
        ],
        { trust: 1, relationshipEffects: { remerii: { trust: 1 } } },
      ),
      Q(
        "cross-hr-world-buckle-joke",
        "Demander combien de réparations ce sac peut encore supporter.",
        "audace",
        [
          H("Autant qu’il faudra. Maintenant, il y a plus de fil neuf que d’ancien."),
          R("Cela ne vous oblige pas à vérifier chaque couture aujourd’hui."),
          N("Hylee s’arrête au milieu d’une traction et vous adresse un sourire."),
          H("Elle dit ça parce qu’elle en a déjà vérifié quatre."),
        ],
        { affection: 1, desire: 1, relationshipEffects: { remerii: { affection: 1 } } },
      ),
    ],
  },
];
