import type { PlayerSex } from "./date-scenes";
import type { DialogueLine } from "./game-data";
import type { GroupIntimacyRoute } from "./group-dates";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const A = (text: string, mood?: string): DialogueLine => ({ speaker: "Allenna", text, mood });
const L = (text: string, mood?: string): DialogueLine => ({ speaker: "Lineva", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });

const TRAINING_FEMME: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-training-femme-revanche",
    text: "Revanche — reprendre le banc à deux contre une",
    detail: "Une revanche vive dans les vestiaires : le banc, les casiers et les renversements gardent le goût du défi sans réduire le désir à une métaphore de duel.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous avez encore le choix de sortir avec votre victoire. Si vous restez, je compte bien vous la faire oublier.", "smirk")],
      familiar: [L("Tu as encore le choix de sortir avec ta victoire. Si tu restes, je compte bien te la faire oublier.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("La porte des vestiaires retombe derrière vous. Allenna pose ses protections sur le premier banc ; Lineva envoie les siennes dans un casier resté ouvert et le choc de métal lui arrache un sourire encore essoufflé."), A("Personne n’a gagné assez nettement pour fanfaronner.", "smirk")],
        [N("Lineva s’assied au milieu du banc et tend les bras comme si elle en revendiquait toute la longueur. Vous prenez un côté, Allenna l’autre ; leurs épaules se touchent derrière elle avant que vos trois rires ne se calment."), P("On peut régler le score sans compter les points.")],
        [N("Allenna se penche la première. Son baiser sur votre bouche reste bref, presque prudent, jusqu’à ce que Lineva lui attrape doucement le menton et prolonge le sien. Vous les réunissez par la nuque au lieu de choisir."), L("Voilà une règle qui me plaît.", "soft")],
        [N("Les boucles d’Allenna accrochent encore la lumière humide de l’effort. Lineva dégage l’une d’elles de sa joue ; Allenna répond en ouvrant le col de sa chemise, puis pose votre paume sur la peau chaude qu’elle vient de découvrir."), A("À trois. Sinon ce n’est pas une revanche.")],
        [N("Vous glissez à moitié sur les genoux d’Allenna tandis que Lineva reste serrée contre votre dos. L’une embrasse votre gorge, l’autre votre tempe ; leurs mains se croisent sur votre taille et finissent par se chercher entre elles."), L("Pas mal, capitaine.", "teasing")],
        [N("Le jeu ralentit lorsque leurs deux bouches reviennent sur la vôtre, alternativement puis ensemble au coin de vos lèvres. Une longue caresse vous fait trembler entre elles ; le plaisir monte et se défait dans un souffle que toutes deux recueillent sans triomphe."), A("Restez là. Juste là.", "soft")],
        [N("Lineva appuie son front au vôtre, les joues encore roses de l’effort et de tout le reste. Son sourire perd son défi au moment exact où elle choisit enfin la familiarité."), L("Tu es magnifique quand tu cesses de tenir le compte.", "soft")],
        [N("Allenna ramasse trois serviettes et en abandonne aussitôt deux pour revenir s’asseoir. Vous restez serrées sur le banc, jambes emmêlées, tandis que Lineva réclame une revanche qui ressemble surtout à la promesse de recommencer.")],
      ],
      suggestif: [
        [N("Les armes demeurent au râtelier, les protections tombent près des casiers. Lineva recule jusqu’au banc en vous défiant du regard ; Allenna ferme la porte, puis s’adosse un instant au bois comme pour reprendre un souffle qu’elle n’a pas perdu dehors."), A("Cette fois, personne ne quitte la pièce en prétendant que le score est clair.")],
        [N("Vous attrapez Lineva par sa ceinture et la faites asseoir. Allenna prend place derrière elle, genoux de chaque côté du banc, et ouvre lentement les attaches que la capitaine allait arracher. Lineva rit lorsque quatre mains la privent de toute feinte."), L("Je reconnais une embuscade bien menée.", "smirk")],
        [N("Allenna vous attire ensuite sur ses cuisses. Son baiser devient plus profond pendant que Lineva suit du bout des lèvres la ligne de votre épaule. Vous défaites à votre tour la chemise d’Allenna ; sa rougeur gagne jusqu’à sa poitrine."), A("Ne vous arrêtez pas pour me regarder rougir.", "troubled")],
        [N("Les étoffes s’accumulent entre le banc et les casiers. Lineva se tient debout devant vous, torse nu, tandis qu’Allenna reste assise derrière votre corps. Les mains de l’une descendent ; celles de l’autre remontent, et leur rencontre vous cambre."), P("Vous aviez prévu cette manœuvre ?")],
        [N("Lineva s’agenouille entre vos jambes écartées. Allenna garde votre dos contre sa poitrine et embrasse votre nuque ; lorsque la bouche de Lineva disparaît plus bas, sa propre main glisse sur la cuisse nue de son amie et la ramène tout près."), L("Je préfère improviser.", "teasing")],
        [N("La chronique demeure au niveau des souffles et des silhouettes : la tête de Lineva entre vos cuisses, Allenna pressée contre votre dos, vos doigts refermés dans leurs cheveux. Le plaisir atteint son sommet avant que le banc cesse tout à fait de grincer."), A("Doucement… gardez ce rythme.", "breathless")],
        [N("Lineva se redresse, essuie du pouce le coin de sa bouche et vous regarde autrement. La première familiarité tombe dans le calme qui suit, plus nue que toutes les provocations précédentes."), L("Tu n’as vraiment rien laissé de ma victoire.", "soft")],
        [N("Allenna noue une serviette autour de vos épaules à toutes les trois. Les équipements restent abandonnés au sol ; Lineva jure que le prochain défi aura des règles, et personne ne fait semblant de la croire.")],
      ],
      explicite: [
        [N("La dernière recrue quitte les vestiaires sans voir Allenna retenir la porte. Lorsqu’elle tourne la clef, Lineva pose son épée contre les casiers et fait glisser ses protections une à une sur le sol. La sueur refroidit encore dans votre dos, mais son regard vous rend aussitôt la chaleur."), A("La cour est vide. Nous pouvons finir ce que le duel a commencé.", "determined")],
        [N("Vous poussez Lineva sur le banc avant qu’elle termine sa provocation. Allenna vient derrière elle, ouvre son col et mord doucement l’épaule offerte. Coincée entre vous, Lineva éclate de rire, saisit votre taille et vous attire à califourchon sur une de ses cuisses."), L("Deux contre une ? Enfin un défi honnête.", "smirk")],
        [N("Allenna vous embrasse par-dessus l’épaule de Lineva. Sa bouche est d’abord retenue ; votre main sous sa chemise la rend plus franche. Lineva profite de l’échange pour défaire votre ceinture, puis Allenna tire elle-même votre vêtement jusqu’à vos chevilles."), A("Elle triche dès qu’on détourne les yeux."), P("Alors ne détournez plus les yeux.")],
        [N("Vous restez debout entre les genoux de Lineva, nue de la taille aux pieds. Allenna s’assied derrière elle et referme les mains sur sa poitrine pendant que la capitaine embrasse votre ventre. Vos doigts ouvrent la chemise d’Allenna ; Lineva tourne la tête pour recevoir son baiser sans quitter vos hanches."), L("Continuez toutes les deux.", "breathless")],
        [N("Lineva vous fait asseoir au bord du banc puis s’agenouille sur les dalles. Elle écarte vos cuisses et pose sa bouche sur vos lèvres intimes ; sa langue trouve la perle sensible avec une précision vite rendue joueuse. Allenna, toujours derrière vous, vous soutient sous les bras et glisse une main entre les jambes de Lineva."), A("Voilà. Elle accélère quand je la touche ici.", "smirk")],
        [N("Le va-et-vient des doigts d’Allenna en Lineva répond au mouvement de sa langue sur vous. Vous tenez d’une main les boucles d’Allenna, de l’autre les cheveux courts de Lineva ; Allenna se penche pour vous embrasser tandis que son pouce maintient sur son amie une pression qui lui coupe un rire."), L("Garde cet air victorieux pour plus tard, Allenna…", "breathless")],
        [N("Vous interrompez la cadence avant qu’elle ne vous emporte et tirez Lineva sur le banc. Allenna se met à genoux devant elle ; sa bouche remplace sa main entre les cuisses ouvertes de la capitaine. Vous vous placez derrière Allenna, embrassez son dos nu et glissez deux doigts en elle pendant qu’elle lèche Lineva."), A("Plus profond.", "breathless")],
        [N("Allenna cambre les reins contre votre main sans abandonner la bouche de Lineva. Celle-ci retient ses cheveux, non pour la conduire, mais pour garder son visage près d’elle lorsque l’orgasme la saisit. Son ventre se tend, ses cuisses tremblent autour des épaules d’Allenna, puis son rire revient en fragments."), L("Un point pour Allenna. Je déteste l’admettre.", "shaken")],
        [N("Lineva vous renverse doucement sur le banc dès qu’elle retrouve son souffle. Elle s’allonge à votre côté, une jambe passée entre les vôtres ; vos sexes humides se pressent et frottent l’un contre l’autre. Allenna reste agenouillée au bout du banc, sa bouche contre votre perle pendant que ses doigts caressent encore Lineva."), P("Ne changez plus rien.")],
        [N("Votre bassin suit celui de Lineva, de plus en plus vite, tandis qu’Allenna garde sa langue exactement où votre plaisir se concentre. Lineva vous embrasse pour étouffer son propre gémissement ; l’orgasme vous traverse la première, resserre vos jambes autour des siennes et vous laisse haletante sous les deux femmes."), A("Respirez. Nous vous tenons.", "soft")],
        [N("Vous restez couchée, encore secouée, mais votre main reprend entre les cuisses d’Allenna. Lineva se redresse et l’attire sur son visage ; Allenna s’accroupit au-dessus de sa bouche, une main agrippée au casier, pendant que vos doigts entrent en elle par-dessous et rejoignent le rythme de la langue."), L("Tu vois ? La partie continue après ton point.", "smirk")],
        [N("Allenna perd enfin la retenue qui lui restait. Elle pousse contre la bouche de Lineva et vos doigts jusqu’à jouir dans un cri bref, les genoux tremblants. Lineva la retient par les hanches ; vous caressez son ventre jusqu’à ce qu’elle puisse se rasseoir entre vous sur le banc."), A("Je ne rédigerai rien de tout ça.", "shaken")],
        [N("Trois serviettes finissent sur deux épaules et un genou. Vous buvez à la même gourde, encore nues parmi les ceintures défaites. Lineva conteste le score ; Allenna lui répond par un baiser lent, puis pose la tête contre vous. La revanche attendra que vos jambes acceptent de vous porter."), L("Demain, même banc.", "teasing"), A("Demain, petit déjeuner d’abord.", "soft")],
      ],
      ellipse: [
        [N("La clef tourne dans la porte des vestiaires. Allenna dépose soigneusement son plastron ; Lineva laisse tomber le sien avec fracas, puis s’installe sur le banc comme si le dernier duel n’avait été qu’une invitation."), L("Il reste une manche.", "smirk")],
        [N("Vous vous placez devant elle. Allenna vient dans son dos et ouvre son col ; le rire de Lineva se brise lorsque vos deux bouches touchent sa peau au même instant."), A("Cette fois, gardez votre souffle.")],
        [N("Les chemises rejoignent les protections. Allenna rougit mais ne recule pas ; elle prend votre visage entre ses mains, vous embrasse, puis offre sa nuque à Lineva sans cesser de vous regarder.")],
        [N("Le banc accueille trois corps serrés et des jambes qui cherchent leur place. La compétition survit dans les sourires, tandis que les caresses descendent hors du champ de la chronique.")],
        [N("Le rideau de vapeur venu des douches brouille les casiers. On distingue Lineva agenouillée, Allenna derrière vous et vos mains occupées à les retenir toutes deux dans le même mouvement.")],
        [N("Les silhouettes changent encore deux fois de place. Votre plaisir culmine au milieu de leurs souffles ; un rire d’Allenna répond à la protestation étouffée de Lineva, puis la vapeur garde le détail des gestes.")],
        [N("Lineva revient près de votre oreille quand le silence se fait. Sa voix abandonne pour la première fois la distance qu’elle conservait jusque-là."), L("Tu viens de rendre la revanche beaucoup plus intéressante.", "soft")],
        [N("La vapeur se dissipe sur trois personnes enlacées au bout du banc. Allenna distribue les serviettes, Lineva réclame déjà une nouvelle manche et vous laissez les protections là où elles sont.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-training-femme-douches",
    text: "Sous les douches — tenir debout entre deux élans",
    detail: "L’eau, le mur et les appuis glissants dictent une scène verticale où chaque prise et chaque changement de hauteur appartient aux douches.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez encore garder une distance raisonnable. Mais le sol est glissant, et je ne promets pas de vous aider à la conserver.", "smirk")],
      familiar: [L("Tu peux encore garder une distance raisonnable. Mais le sol est glissant, et je ne promets pas de t’aider à la conserver.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 8, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 9, ellipse: 6 },
      revealChapter: 3,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("L’eau chaude frappe les dalles avec assez de bruit pour isoler votre alcôve. Allenna dénoue ses cheveux ; Lineva passe dessous sans prévenir et reçoit toute la cascade sur le visage."), L("J’avais besoin de ça.", "bright")],
        [N("Vous rejoignez Lineva sous le jet. Allenna reste d’abord au bord, puis votre main mouillée autour de son poignet l’attire entre vous. Ses boucles s’aplatissent contre ses joues et son rire devient presque adolescent.")],
        [N("Un pied glisse. Lineva vous plaque doucement au mur, Allenna la retient par la taille, et la chute évitée laisse trois corps pressés l’un contre l’autre. Personne ne se dépêche de reprendre une distance sûre."), A("Nous sommes censées mieux tenir sur nos jambes.", "smirk")],
        [N("Lineva embrasse votre bouche tandis qu’Allenna essuie l’eau sur vos paupières. Vous tournez la tête pour embrasser Allenna ; Lineva garde une main à votre hanche et l’autre sur la joue de son amie.")],
        [N("Vous changez de place sous la douche : Allenna contre le mur, vous devant elle, Lineva dans votre dos. Les baisers se transmettent avec la chaleur du jet, et les mains trouvent la peau sans pouvoir s’y accrocher longtemps.")],
        [N("Une caresse plus insistante vous fait vous cambrer contre Allenna. Lineva soutient votre bassin, Allenna enfouit sa bouche dans votre cou ; le plaisir roule lentement jusqu’à son sommet, adouci par l’eau qui continue de tout envelopper.")],
        [N("Lineva reste le front contre votre épaule, mouillée et soudain sérieuse. Elle attend que votre respiration revienne avant de laisser tomber le mot qui change la distance entre vous."), L("Tu tiens mieux debout que moi après ça.", "soft")],
        [N("Allenna ferme le jet. Dans le silence neuf, vous vous séchez à trois avec une seule grande serviette, maladroitement serrées, tandis que Lineva accuse le savon d’avoir faussé toute la scène.")],
      ],
      suggestif: [
        [N("La vapeur avale déjà le plafond lorsque Lineva ouvre le premier jet. Elle se débarrasse de sa chemise trempée ; Allenna la suit moins vite, consciente de votre regard jusqu’à ce que vous veniez défaire le dernier nœud."), A("Ne dites rien.", "troubled")],
        [N("Vous passez sous l’eau avec Allenna. Lineva se glisse derrière elle et rassemble ses cheveux mouillés sur une épaule ; votre bouche prend l’autre. Allenna ferme les yeux, prise entre deux chaleurs qui ne viennent pas du jet.")],
        [N("Lineva vous attire contre le mur carrelé et place les mains d’Allenna à vos hanches. La pierre est fraîche dans votre dos, leurs corps brûlants devant vous, et l’eau rend chaque mouvement trop lisse pour conserver longtemps la même prise.")],
        [N("Allenna s’agenouille malgré le sol mouillé ; Lineva l’aide d’une main ferme sous le bras. Sa bouche descend sur votre ventre pendant que Lineva vous embrasse, et vos doigts se perdent dans deux chevelures alourdies par l’eau."), L("Impossible de détourner les yeux d’elle.", "breathless")],
        [N("Vous inversez les hauteurs : Allenna retrouve le mur, Lineva descend à son tour, et vous restez entre elles, une main sur chaque peau. Les bouches s’attardent là où la chronique choisit encore de ne montrer que leurs réactions.")],
        [N("Le jet frappe vos épaules lorsque le plaisir vous traverse. Allenna vous tient contre elle ; Lineva garde sa bouche plus bas jusqu’à ce que vos jambes cessent de trembler et que l’eau emporte le dernier souffle brisé.")],
        [N("Lineva se relève avec l’aide de votre main et pose un baiser sur votre cuisse avant de vous regarder."), L("Tu avais raison de ne pas lâcher le mur.", "soft")],
        [N("Allenna ferme l’eau puis essore doucement les cheveux de Lineva. Vous les rejoignez sous une serviette ; vos peaux refroidissent, mais leur proximité reste assez chaude pour prolonger le silence.")],
      ],
      explicite: [
        [N("Lineva tourne les robinets à fond. L’eau chaude martèle ses épaules et plaque sa chemise à sa peau jusqu’à ce qu’elle l’arrache au-dessus de sa tête. Allenna reste nue près du mur, bras croisés un bref instant, rouge sous votre regard avant de décroiser les mains et de venir vers vous."), A("Je n’ai pas froid.", "troubled")],
        [N("Vous embrassez Allenna sous le jet. Lineva se colle à son dos, glisse les mains sur sa poitrine ruisselante et mord la naissance de son cou. Allenna pousse ses hanches contre elle, puis vous ramène par la nuque pour approfondir le baiser au lieu de cacher sa réaction."), L("Voilà. Beaucoup mieux.", "smirk")],
        [N("Le savon rend vos flancs glissants. Allenna en fait mousser entre ses paumes et lave lentement votre poitrine ; Lineva guide l’une de ses mains plus bas, sur votre ventre, pendant que vous savonnez ses seins et que votre pouce durcit leur pointe sous l’eau."), A("Lineva… laisse-moi choisir la suite."), L("Je regarde.", "soft")],
        [N("Allenna vous place dos au carrelage, une de vos jambes relevée sur sa hanche pour vous ouvrir. Elle s’agenouille, soutenue par la main de Lineva sur son épaule, puis pose la bouche entre vos cuisses. Sa langue écarte vos lèvres tandis que Lineva vous embrasse debout et garde votre jambe stable."), P("Allenna, plus lentement.")],
        [N("Allenna ralentit et dessine chaque passage autour de votre perle avant de l’aspirer doucement. Lineva descend deux doigts sur le sexe d’Allenna resté à hauteur de sa main ; elle les glisse en elle par derrière, le pouce frottant son plaisir pendant que sa bouche vous donne le vôtre."), A("Ne retire pas ta main.", "breathless")],
        [N("L’eau coule sur le visage d’Allenna et le long de vos cuisses. Vous tenez le pommeau au-dessus d’elle pour dégager son souffle ; Lineva se presse contre votre flanc, ses doigts entrant et sortant d’Allenna au rythme que ses hanches réclament. Allenna gémit contre vous sans interrompre sa langue."), L("Elle va céder la première.", "teasing")],
        [N("Allenna se redresse avant de jouir et plaque Lineva contre le mur à votre place. Elle l’embrasse durement, puis descend à genoux. Vous soutenez Lineva sous une cuisse, l’obligeant à rester sur un seul appui, tandis qu’Allenna lèche son sexe et que votre main caresse sa poitrine mouillée."), L("D’accord… ce renversement compte.", "shaken")],
        [N("Lineva agrippe la barre de cuivre. Allenna garde sa bouche sur sa perle ; vous glissez deux doigts en Lineva, juste au-dessus du visage de son amie. La double stimulation la fait jouir debout, cuisse tremblante dans votre bras, sa nuque heurtant doucement les carreaux sous le jet."), A("Je crois que ce point est à moi.", "smirk")],
        [N("À peine stable, Lineva reprend votre jambe et vous ramène contre le mur. Allenna s’accroupit entre vous deux, une main sur chaque sexe ; Lineva se baisse pour embrasser Allenna pendant que ses doigts rejoignent les siens sur votre perle. Leur pression alternée vous emporte à votre tour."), P("Oui… maintenant."), N("Votre orgasme serre tout votre corps contre la pierre ; elles vous tiennent jusqu’au dernier frisson.")],
        [N("Lineva appuie sa joue mouillée contre la vôtre. Le tutoiement arrive au milieu d’un sourire épuisé, après le plaisir, comme une porte ouverte sans cérémonie."), L("Tu n’as pas glissé une seule fois. C’est presque vexant.", "soft")],
        [N("Allenna n’a pas encore joui. Vous la placez face au mur, Lineva devant elle pour recevoir ses baisers. Votre bouche descend entre ses fesses et ses cuisses ; vos doigts entrent en elle tandis que Lineva frotte sa perle du plat de la main et lui offre son épaule à mordre."), A("Toutes les deux… ne ralentissez pas.", "breathless")],
        [N("Allenna pousse contre vos doigts et la paume de Lineva jusqu’à ce que ses genoux fléchissent. Lineva la retient sous les bras ; vous restez agenouillée derrière elle pendant que l’orgasme la secoue. Puis vous coupez enfin l’eau, laissant seulement trois respirations et le ruissellement des rigoles."), A("J’avais tort. Mes jambes ne tiennent plus.", "shaken")],
        [N("Vous vous enveloppez dans deux serviettes pour trois. Les cheveux de Lineva dressent des mèches absurdes ; Allenna les aplatit en riant malgré elle. Assises sur la dalle tiède, vous partagez une gourde et laissez la vapeur se retirer avant vous.")],
        [N("Quand vous vous levez enfin, Allenna récupère les vêtements détrempés et Lineva abandonne toute tentative de dompter ses cheveux. Vous traversez les vestiaires en riant, encore assez proches pour vous tenir par la taille jusqu’à la porte.")],
      ],
      ellipse: [
        [N("La première douche s’allume avec un claquement. Lineva passe sous le jet toute habillée, puis retire sa chemise collée en riant ; Allenna secoue la tête avant de vous aider à dénouer la vôtre.")],
        [N("La vapeur gagne le plafond. Vous embrassez Allenna tandis que Lineva rassemble ses cheveux mouillés et pose la bouche sur sa nuque ; son sérieux cède avec la première goutte qui roule entre vos trois peaux.")],
        [N("Un appui glisse et vous vous retrouvez contre le mur, Lineva devant vous, Allenna derrière elle. Les mains qui devaient empêcher la chute choisissent de rester, plus bas et plus longtemps.")],
        [N("Allenna s’agenouille sur les dalles ; Lineva garde votre jambe relevée et vous embrasse. L’eau cache une partie du mouvement, jamais la place de chacune ni la façon dont vos doigts les retiennent.")],
        [N("Vous échangez les hauteurs sous le jet. La vapeur transforme les corps en silhouettes, mais laisse voir Allenna contre le mur, Lineva à genoux et votre main guidant doucement le rythme.")],
        [N("Votre plaisir atteint son sommet au milieu du fracas de l’eau. Deux femmes vous maintiennent debout, puis leurs silhouettes changent encore de place derrière le rideau blanc.")],
        [N("Lineva revient contre vous lorsque votre souffle se calme, ses cheveux collés au front."), L("Tu vas devoir m’apprendre cette façon de tenir sous la pluie.", "soft")],
        [N("Allenna ferme les robinets. Le silence vous surprend toutes les trois ; vous le remplissez avec une serviette partagée, un rire bas et la promesse de ne pas remettre tout de suite vos vêtements.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-training-femme-apres-duel",
    text: "Après le duel — laisser la fatigue rendre les gestes vrais",
    detail: "Une entrée lente et attentive après l’effort ; Allenna, d’abord rouge et silencieuse, finit par prendre une initiative qui transforme la douceur en intensité.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous n’avez rien à prouver ici. Restez seulement si cette fatigue vous donne la même envie qu’à nous.", "soft")],
      familiar: [L("Tu n’as rien à prouver ici. Reste seulement si cette fatigue te donne la même envie qu’à nous.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Le duel est terminé depuis plusieurs minutes, pourtant aucune de vous ne se lève du banc. Allenna masse son avant-bras, Lineva laisse retomber sa tête contre le casier et vous écoutez ensemble vos respirations revenir."), A("Je pourrais dormir ici.", "tired")],
        [N("Vous prenez la main d’Allenna pour délier ses doigts crispés. Lineva se rapproche de l’autre côté et pose sa paume sur votre genou ; la chaleur tranquille de ce triangle semble plus intime que la nudité encore à venir.")],
        [N("Allenna remarque votre regard lorsqu’elle ouvre son col. Elle rougit, hésite, puis vous laisse dégager l’étoffe collée à son épaule. Lineva embrasse la marque laissée par une sangle sans faire la moindre plaisanterie."), L("Elle a tenu jusqu’au bout.", "soft")],
        [N("Vous embrassez Allenna avec lenteur. Elle reste immobile une seconde, consciente de chaque centimètre offert, puis sa main vous ramène. Lineva se glisse contre son dos et leurs doigts se nouent sur votre taille.")],
        [N("Allongées en travers du banc, vous soutenez la tête d’Allenna sur votre bras. Lineva caresse vos deux ventres sous les chemises ouvertes ; Allenna finit par tourner le visage pour l’embrasser elle aussi, sans détourner ensuite les yeux.")],
        [N("Les caresses restent lentes mais cessent d’être sages. Allenna suit votre plaisir jusqu’à ce qu’un frisson long vous traverse entre elles ; Lineva garde votre jambe contre la sienne et murmure votre nom lorsque votre souffle se défait.")],
        [N("La joue de Lineva repose contre votre clavicule. Sa voix est basse, débarrassée de tout défi."), L("Tu peux t’endormir là. Je ne bougerai pas.", "soft")],
        [N("Allenna couvre vos trois corps avec les tuniques les moins froissées. Personne ne dort vraiment ; vous échangez encore quelques baisers paresseux avant qu’elle décide qu’une soupe chaude vaut enfin l’effort de se lever.")],
      ],
      suggestif: [
        [N("L’adrénaline retombe d’un seul coup. Allenna s’assied, jambes écartées pour délacer ses bottes ; Lineva glisse au sol contre le banc, le dos entre vos genoux. Vous restez ainsi jusqu’à ce que leurs souffles se ressemblent."), L("Pas de revanche tout de suite.", "tired")],
        [N("Vous essuyez une trace de sueur sur la tempe d’Allenna. Elle suit vos doigts des yeux, rouge avant même que vous l’embrassiez. Lineva lève la main et caresse sa joue, attentive à la manière dont elle choisit enfin de se pencher vers vous.")],
        [N("Les vêtements s’ouvrent sans hâte. Allenna découvre sa poitrine puis tente de croiser les bras ; Lineva les écarte doucement et pose un baiser sur son sternum. Vous embrassez son ventre, lui laissant le temps de transformer sa gêne en envie.")],
        [N("Allenna se redresse soudain et vous fait asseoir entre ses cuisses. Sa bouche trouve votre épaule ; sa main descend sous votre vêtement tandis que Lineva, toujours au sol, embrasse l’intérieur de son genou et remonte lentement."), A("Je ne veux plus qu’on s’arrête pour moi.", "determined")],
        [N("Vous vous étendez sur le banc, Allenna penchée sur votre bouche et Lineva entre vos jambes. Les gestes précis demeurent sous le bord du cadre, mais les positions restent nettes : Allenna vous embrasse, Lineva vous donne du plaisir, votre main cherche Allenna sous sa chemise.")],
        [N("Le plaisir vous atteint dans cette lente chaîne. Allenna vous tient le visage, Lineva maintient son attention jusqu’au dernier frisson ; puis Allenna descend vers elle et l’embrasse avec une franchise qui surprend même la capitaine.")],
        [N("Lineva relève les yeux vers vous, heureuse et désarmée."), L("Tu as vu ? Elle n’était pas fatiguée. Elle préparait son attaque.", "soft")],
        [N("Allenna rougit de nouveau, mais cette fois sans se cacher. Elle s’allonge entre vous sous une serviette, accepte deux bras autour d’elle et promet seulement de réfléchir à la soupe après cinq minutes de plus.")],
      ],
      explicite: [
        [N("Le silence des vestiaires arrive après le vacarme de la cour. Allenna s’assied lourdement sur le banc, les mains encore tremblantes d’effort ; Lineva se laisse glisser au sol contre vos jambes. Aucun défi ne subsiste dans leurs visages, seulement la fatigue et la confiance de rester vulnérables devant vous."), A("Je n’arrive plus à fermer les doigts.", "tired")],
        [N("Vous massez la paume d’Allenna. Lineva, assise entre vos genoux, embrasse l’intérieur de votre poignet puis celui d’Allenna. Le geste est si simple qu’Allenna rougit davantage que sous toutes les provocations précédentes ; pourtant elle ne retire pas sa main lorsque Lineva la retourne pour y poser sa joue."), L("On peut prendre notre temps.", "soft")],
        [N("Allenna ouvre sa tunique humide. Son regard saute de vous à Lineva, conscient de sa poitrine nue et de la réponse visible de son corps. Vous embrassez une marque rouge sous sa clavicule ; Lineva pose la bouche sur l’autre sein. Allenna inspire brusquement puis garde vos deux têtes contre elle."), A("Continuez. Je m’habituerai au regard.", "troubled")],
        [N("Vous allongez Allenna sur le banc, sa tête sur les cuisses de Lineva. La capitaine lui caresse les cheveux et l’embrasse à l’envers pendant que vous retirez lentement le reste de ses vêtements. Les jambes d’Allenna s’ouvrent sans ordre ; son regard reste cette fois accroché au vôtre."), P("Je vous vois. Et j’aime ce que je vois.")],
        [N("Votre bouche suit l’intérieur de ses cuisses jusqu’à son sexe. Vous écartez ses lèvres avec les pouces et passez la langue sur sa perle sensible. Lineva garde Allenna contre ses cuisses, lui offre ses doigts à serrer et descend l’autre main sur votre nuque pour accompagner votre cadence sans la commander."), A("Plus haut… oui.", "breathless")],
        [N("Allenna cesse soudain d’être passive à sa propre gêne. Elle vous fait relever, se met à genoux sur le banc et attire Lineva par la chemise. Son baiser contre la capitaine est profond, décidé ; pendant qu’elles se déshabillent mutuellement, Allenna guide votre main entre les cuisses de Lineva."), A("À mon tour de choisir.", "determined")],
        [N("Lineva s’allonge sur le dos, épaules soutenues par votre cuisse. Allenna s’agenouille entre les siennes et enfonce deux doigts en elle, sa bouche sur la perle gonflée. Vous vous penchez au-dessus de Lineva pour l’embrasser, puis offrez votre sein à la bouche qu’elle libère entre deux gémissements."), L("Allenna apprend vite quand elle cesse de réfléchir.", "shaken")],
        [N("Allenna fait jouir Lineva sans presser le rythme : ses doigts se courbent en elle, sa langue reste ferme, et vous retenez le bassin de la capitaine lorsqu’il se soulève. Après les contractions, Lineva garde une main dans les boucles d’Allenna et l’attire pour un baiser où son plaisir a encore un goût."), A("Je ne réfléchissais plus du tout.", "breathless")],
        [N("Allenna vous fait ensuite coucher à côté de Lineva, vos jambes croisées sur le banc. Elle se place entre vos cuisses et reprend votre sexe avec sa bouche ; Lineva se tourne contre vous, frotte sa chaleur à la vôtre et glisse deux doigts en vous pendant que vous caressez sa poitrine."), P("Restez toutes les deux comme ça.")],
        [N("La langue d’Allenna sur votre perle, ses doigts en Lineva et ceux de Lineva en vous construisent un rythme lent devenu brutalement profond. Vous jouissez la première, bouche ouverte contre l’épaule de Lineva ; Allenna continue jusqu’à ce que vos cuisses cessent de se refermer autour d’elle."), N("Lineva vous enveloppe pendant que votre plaisir retombe.")],
        [N("Lineva essuie votre joue du bout des doigts et laisse enfin le tutoiement passer après le climax."), L("Tu n’avais rien à prouver. Mais je me souviendrai longtemps de ça.", "soft"), N("Vous gardez une main en Allenna tandis qu’elle remonte sur le banc, décidée à ne pas rester la seule encore tendue.")],
        [N("Allenna s’assied sur votre visage, les genoux de part et d’autre de votre tête ; Lineva se place derrière elle et reprend ses seins dans ses mains. Votre langue retrouve sa perle tandis que Lineva embrasse sa nuque et glisse deux doigts en elle. Allenna jouit en se cambrant contre vos deux corps, rouge et entièrement assumée."), A("Ne dites surtout pas que j’étais timide.", "shaken")],
        [N("La fatigue revient d’un seul coup, douce cette fois. Lineva vous apporte de l’eau ; Allenna rassemble les serviettes sans chercher à ranger le reste. Vous finissez allongées par terre sur un manteau, Allenna entre vous, échangeant des baisers lents avant de négocier la soupe et une revanche très lointaine.")],
      ],
      ellipse: [
        [N("Après le duel, personne n’a l’énergie de prétendre que le silence gêne. Allenna s’assied sur le banc ; Lineva reste au sol entre vos jambes et pose la tête contre votre genou.")],
        [N("Vous massez la main crispée d’Allenna. Lineva embrasse son poignet, puis le vôtre ; Allenna rougit de ce geste minuscule mais laisse ses doigts se mêler aux deux autres mains.")],
        [N("Les cols s’ouvrent, les peaux marquées par l’effort se découvrent. Allenna reste consciente de vos regards jusqu’à ce qu’elle vous attire elle-même contre sa poitrine et offre sa nuque à Lineva.")],
        [N("Vous l’allongez sur le banc, la tête sur les cuisses de Lineva. Vos baisers descendent ; les siens remontent. La chronique laisse les gestes précis derrière la ligne de leurs souffles.")],
        [N("Allenna inverse soudain les places. Elle attire Lineva sous elle, vous ramène contre leur flanc et fait de son ancienne gêne une initiative assez nette pour vous surprendre toutes les deux.")],
        [N("Votre plaisir atteint son sommet dans cette étreinte resserrée. Les silhouettes continuent ensuite à changer lentement de position, chacune soutenant les deux autres malgré la fatigue.")],
        [N("Lineva caresse votre joue quand vos respirations redeviennent calmes."), L("Tu peux rester là aussi longtemps que tu veux.", "soft")],
        [N("Allenna ramène une serviette sur vous trois et oublie volontairement les vêtements au sol. La soupe attend ; pendant quelques minutes encore, personne n’a besoin de quitter le banc.")],
      ],
    },
  },
];

const TRAINING_HOMME: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-training-homme-revanche",
    text: "Revanche — perdre l’avantage entre le banc et les casiers",
    detail: "Une partie physique et rieuse où Allenna et Lineva se disputent l’initiative, puis changent de place sans jamais reléguer la troisième personne.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez encore déclarer forfait avec dignité. Après cette porte, Allenna et moi ne garantirons plus rien pour votre fierté.", "smirk")],
      familiar: [L("Tu peux encore déclarer forfait avec dignité. Après cette porte, Allenna et moi ne garantirons plus rien pour ta fierté.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Les casiers vibrent lorsque Lineva y lance ses brassards. Allenna récupère le dernier avant qu’il touche le sol, le pose sur le banc et vous désigne la place entre elles avec un sourire qui vaut défi."), A("Asseyez-vous. Nous allons départager les mauvaises perdantes.", "smirk")],
        [N("Vous vous laissez tomber sur le bois. Lineva pose une botte de chaque côté de la vôtre ; Allenna dénoue vos lacets sans raison valable, puis garde votre cheville sur ses genoux. La fatigue rend leurs rires bas et proches.")],
        [N("Lineva vous embrasse la première. Allenna l’écarte par l’épaule pour prendre sa place, mais Lineva reste contre votre flanc et l’embrasse par-dessus vous. Le concours se transforme en trois bouches qui oublient leur ordre.")],
        [N("Vous ouvrez la chemise d’Allenna ; elle rougit puis dégage elle-même ses épaules. Lineva suit la peau révélée du bout des doigts et vous confie l’autre côté de son corps, comme si partager l’attention était sa meilleure riposte."), L("Impossible de la laisser reprendre son air sérieux.", "teasing")],
        [N("Allenna s’allonge à moitié sur vos cuisses, Lineva contre son dos. Vous caressez leurs cheveux encore humides, puis leurs mains reviennent ensemble sur votre torse et votre ventre avec une lenteur qui fait disparaître le vestiaire.")],
        [N("Les baisers descendent juste assez pour que votre plaisir se tende puis cède entre elles. Allenna vous tient contre le casier ; Lineva garde sa joue sur votre ventre jusqu’à ce que le frisson s’apaise et que vos doigts cessent de trembler.")],
        [N("Lineva remonte près de votre bouche, le sourire adouci par ce qu’elle vient de voir."), L("Tu n’as plus du tout l’air d’un arbitre. Tant mieux.", "soft")],
        [N("Vous restez tous les trois sur le banc, Allenna la tête sur votre épaule et Lineva étendue sur vos jambes. Le score devient une plaisanterie paresseuse ; les serviettes attendent pendant que personne ne souhaite se relever.")],
      ],
      suggestif: [
        [N("Lineva bloque la porte du pied et se débarrasse de son baudrier. Allenna aligne d’abord ses protections sur le banc, puis les pousse toutes au sol lorsque vous lui prenez la main et l’attirez contre vous."), L("Cette fois, pas de témoins pour contester le résultat.", "smirk")],
        [N("Allenna vous embrasse avec une retenue qui ne dure pas. Lineva passe derrière elle, ouvre sa chemise et caresse sa poitrine ; vous sentez le souffle d’Allenna changer contre votre bouche lorsqu’elle accepte d’être regardée.")],
        [N("Vous asseyez Lineva sur le banc. Allenna se place entre ses genoux et l’embrasse pendant que vous défaites les derniers boutons de la capitaine. Le rire de Lineva devient rauque lorsque deux paires de mains suivent son ventre.")],
        [N("Le reste de vos vêtements rejoint les brassards. Allenna s’agenouille devant vous, Lineva debout dans votre dos ; l’une embrasse votre ventre, l’autre votre nuque, et leurs doigts se retrouvent à votre taille."), A("Il réagit vite à notre revanche.", "smirk")],
        [N("Lineva attire Allenna contre elle et lui offre un baiser profond sans vous lâcher. Vous les entourez toutes deux, votre désir pressé entre leurs hanches, tandis que le banc oblige les corps à rester étroitement superposés.")],
        [N("La chronique laisse leurs bouches descendre et vos mains remonter. Le plaisir vous emporte entre Allenna agenouillée et Lineva penchée sur elle, leurs contacts l’une avec l’autre aussi visibles que l’attention qu’elles vous donnent.")],
        [N("Lineva revient contre votre oreille lorsque votre souffle ralentit."), L("Tu viens de perdre très élégamment. Je pourrais m’y habituer.", "soft")],
        [N("Allenna vous couvre avec sa tunique, puis se glisse dessous avec Lineva. La revanche s’achève dans un amas de jambes sur le banc et une dispute joyeuse à propos d’une gourde devenue impossible à atteindre.")],
      ],
      explicite: [
        [N("La porte claque derrière Allenna. Lineva retire ses gants avec les dents, les jette sur le banc et vous saisit par le col avant que vous puissiez commenter le duel. Son baiser a le goût du rire et de l’effort ; Allenna vient contre votre dos, ses mains déjà sous votre chemise."), L("La revanche commence maintenant.", "smirk")],
        [N("Allenna vous fait pivoter et prend votre bouche tandis que Lineva ouvre votre pantalon. Votre sexe dur se libère entre leurs hanches ; Allenna le regarde, rougit franchement, puis referme sa main autour de sa base avec une décision qui fait sourire Lineva."), A("Je ne vais pas faire semblant de ne pas en avoir envie.", "determined")],
        [N("Vous asseyez Allenna sur le banc et vous placez entre ses genoux. Lineva s’agenouille derrière elle sur le bois, ouvre sa tunique et prend ses seins dans ses mains. Pendant que vous embrassez Allenna, Lineva pince doucement ses pointes et mord son cou ; Allenna vous serre entre ses cuisses."), L("Elle tient moins bien sa garde ici.", "teasing")],
        [N("Allenna descend à genoux devant vous. Elle lèche le long de votre sexe, en prend l’extrémité entre ses lèvres puis vous accueille plus profondément. Lineva reste penchée au-dessus d’elle, l’embrasse à chaque retrait et glisse une main entre ses cuisses pour la caresser pendant qu’elle vous donne sa bouche."), P("Regardez-moi, Allenna.")],
        [N("Ses yeux restent levés vers vous tandis que sa bouche va et vient. Les doigts de Lineva entrent en elle par derrière ; Allenna gémit autour de votre sexe, accélère malgré elle, puis saisit la cuisse de Lineva pour lui imposer la même cadence. Vous caressez leurs deux visages sans rompre la chaîne."), L("Elle apprend à commander sans parler.", "smirk")],
        [N("Vous reculez avant de jouir. Allenna se relève et renverse Lineva sur le banc d’une poussée d’épaule. Elle lui écarte les jambes ; votre bouche trouve la poitrine de Lineva pendant que celle d’Allenna descend entre ses cuisses et que vos doigts se glissent en Allenna, restée cambrée au-dessus de son amie."), A("Personne ne gagne seul.", "breathless")],
        [N("Lineva jouit sous la langue d’Allenna et votre bouche, les talons frappant une fois le bord du banc. Allenna garde sa perle entre ses lèvres jusqu’au dernier tremblement ; vous maintenez deux doigts en elle et sentez son propre plaisir se tendre sans encore céder."), L("Très bien… ce point-là est incontestable.", "shaken")],
        [N("Lineva se redresse aussitôt et place Allenna à quatre pattes sur le banc. Elle l’embrasse par-dessus son épaule et écarte ses fesses pendant que vous guidez votre sexe contre son entrée humide. Allenna recule d’elle-même ; vous la pénétrez lentement, Lineva frottant sa perle de deux doigts."), A("Plus profond. Je le veux maintenant.", "determined")],
        [N("Le banc grince sous chaque poussée. Allenna reçoit votre bassin contre le sien ; Lineva garde sa bouche sur la sienne et sa main entre ses cuisses. Quand Allenna jouit autour de vous, ses bras cèdent et Lineva la soutient contre sa poitrine sans vous demander de sortir.")],
        [N("Vous poursuivez plus lentement dans le corps encore contracté d’Allenna. Lineva vous embrasse au-dessus d’elle, puis referme sa main autour de la base de votre sexe quand vous vous retirez. Votre orgasme arrive dans sa paume et sur le ventre d’Allenna, séparé du leur, accompagné par leurs deux regards."), P("Je n’ai plus la moindre idée du score.")],
        [N("Lineva essuie sa main avec une serviette puis revient toucher votre joue. C’est seulement maintenant que la distance tombe de sa voix."), L("Tu as tenu plus longtemps que je ne l’aurais parié. Ne prends pas cet air fier.", "soft")],
        [N("Allenna se couche sur le dos, encore sensible, et attire Lineva à califourchon sur sa bouche. Vous vous agenouillez près de sa tête pour embrasser Allenna tandis qu’elle lèche Lineva ; vous entrez à votre tour deux doigts dans la capitaine et prolongez le mouvement jusqu’à un second orgasme qui lui arrache un rire incrédule."), L("D’accord, celle-là était gratuite.", "shaken")],
        [N("Vous finissez serrés sur le banc, une serviette autour des hanches et deux autres jetées sur vos épaules. Allenna boit, vous tend la gourde, puis la donne à Lineva. Les armes restent au mur ; la seule revanche discutée concerne la personne qui devra aller chercher le repas."), A("Il faut d’abord réussir à se lever.", "soft")],
        [N("Lineva perd le débat en essayant de se mettre debout trop vite. Vous la rattrapez avec Allenna, puis partez chercher de quoi manger tous les trois, les épaules encore réunies sous la même serviette.")],
      ],
      ellipse: [
        [N("Les vestiaires se vident. Lineva ferme le dernier casier et vous attire contre le banc ; Allenna pose les protections au sol avec moins de soin qu’à l’habitude.")],
        [N("Un premier baiser vous vient de Lineva, un second d’Allenna. Elles se rejoignent ensuite au-dessus de votre épaule, refusant que leur rivalité dessine deux scènes séparées.")],
        [N("Vous faites asseoir Allenna tandis que Lineva ouvre sa tunique par derrière. Ses joues rougissent ; ses mains, elles, défont votre ceinture avec une assurance croissante.")],
        [N("Lineva prend à son tour la place sur le banc. Allenna s’agenouille devant elle, vous restez contre son flanc, et les silhouettes n’offrent plus aucun espace inutile.")],
        [N("La lumière des casiers découpe trois corps nus et plusieurs changements d’appui. La chronique recule lorsque les bouches et les mains quittent les zones qu’elle choisit de nommer.")],
        [N("Votre plaisir culmine entre elles, puis le jeu se poursuit derrière la rangée de bancs : Allenna renverse Lineva, Lineva riposte, et vos mains restent prises dans leur mouvement.")],
        [N("Lineva rejoint votre épaule après le silence."), L("Tu avais donc gardé des forces. C’est une information dangereuse.", "soft")],
        [N("Allenna lance une serviette sur vous deux et s’assied au milieu. Personne ne reconstitue le score ; la gourde passe de bouche en bouche pendant que le soir refroidit les dalles.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-training-homme-douches",
    text: "Sous les douches — trouver l’angle contre le mur",
    detail: "Une scène debout, contrainte par l’eau et le carrelage : appuis partagés, jambes relevées et corps qui se soutiennent à chaque changement.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous avez l’air de croire que ce mur suffira à garder vos appuis. Je serais curieuse de vérifier.", "smirk")],
      familiar: [L("Tu as l’air de croire que ce mur suffira à garder tes appuis. Je serais curieuse de vérifier.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 3,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Le jet éclate sur l’épaule de Lineva lorsqu’elle tourne le robinet. Allenna se glisse sous l’eau de l’autre côté ; vous entrez entre elles, le dos au mur, et recevez leurs deux sourires à travers la vapeur.")],
        [N("Lineva vous lave les cheveux avec trop d’énergie. Allenna lui attrape les poignets, reprend le massage avec patience puis laisse vos doigts savonner ses propres boucles. L’eau rend leurs visages ouverts et étonnamment jeunes."), L("Je maintiens que ma méthode était plus rapide.", "teasing")],
        [N("Votre pied dérape. Allenna vous retient par la taille, Lineva par les épaules ; l’incident finit en rire contre le carrelage, vos trois torses collés et leurs mains peu pressées de quitter votre peau.")],
        [N("Vous embrassez Lineva, puis Allenna. Elles s’embrassent au-dessus de votre clavicule tandis que vous gardez une main dans le dos de chacune, l’eau chaude dessinant le chemin de vos doigts.")],
        [N("Allenna vous plaque doucement contre le mur pour mieux atteindre votre bouche. Lineva reste derrière elle et l’enlace ; vous sentez son rire passer du dos d’Allenna à votre poitrine.")],
        [N("Leurs caresses deviennent assez précises pour faire monter puis céder votre plaisir. Allenna garde votre bassin stable, Lineva votre visage entre ses mains ; le sommet arrive sans hâte sous le bruit régulier du jet.")],
        [N("Lineva essuie l’eau sur vos yeux et vous regarde sans détour."), L("Tu peux lâcher le mur maintenant. Nous te tenons.", "soft")],
        [N("Allenna coupe le jet. Vous vous retrouvez sous une grande serviette, Lineva au milieu, et le rire qui suit le retour du silence vaut mieux que toute nouvelle provocation.")],
      ],
      suggestif: [
        [N("Lineva se débarrasse de sa tunique mouillée sous le premier jet. Allenna vous aide avec la vôtre, ses doigts lents sur chaque attache ; lorsque vous êtes torse nu, la capitaine vous attire tous deux dans la vapeur.")],
        [N("Vous embrassez Allenna pendant que Lineva savonne son dos. Les mains glissent plus bas que nécessaire ; Allenna rougit, se retourne et rend à Lineva une caresse qui lui coupe son commentaire.")],
        [N("Dos au mur, vous accueillez Lineva contre votre poitrine et Allenna contre votre flanc. Leurs cheveux collent à leurs seins ; vos mains suivent l’eau sur leurs tailles avant qu’elles vous enlèvent ensemble le dernier vêtement.")],
        [N("Allenna s’accroupit devant vous, Lineva penchée sur son épaule. Sa bouche s’approche de votre désir tandis que Lineva la touche entre les cuisses ; la vapeur garde encore le détail, pas la géographie des trois corps."), A("Restez contre le mur.", "breathless")],
        [N("Vous les échangez de place sans les séparer : Lineva se retrouve contre le carrelage, Allenna devant elle, et vous derrière Allenna. Les baisers circulent tandis que les mains poursuivent leur trajet hors cadre.")],
        [N("Votre plaisir culmine debout, retenu par leurs deux bras. Allenna garde son visage près de votre ventre ; Lineva, toujours contre le mur, serre sa main et vous regarde reprendre votre souffle.")],
        [N("Lineva attire votre bouche après que le frisson est passé."), L("Tu étais beaucoup plus sage sur le terrain.", "soft")],
        [N("Vous coupez l’eau et essorez ensemble les cheveux d’Allenna. Elle proteste sans conviction ; la serviette autour de vos trois épaules transforme la douche en abri provisoire.")],
      ],
      explicite: [
        [N("La vapeur épaissit dès que Lineva ouvre deux jets. Elle retire sa tunique sous l’eau, la laisse tomber lourdement sur les dalles et vient plaquer sa poitrine nue contre votre torse. Allenna se déshabille près du mur ; son regard descend vers votre sexe qui durcit déjà, puis remonte avec une rougeur assumée."), L("L’eau ne va pas suffire à nous rafraîchir.", "smirk")],
        [N("Vous embrassez Allenna tandis que Lineva savonne ses seins par derrière. Allenna se laisse d’abord guider, puis attrape la nuque de son amie et l’embrasse franchement au-dessus de votre épaule. Vos mains suivent leurs flancs ruisselants jusqu’à leurs fesses, où l’eau rend chaque prise mouvante."), A("Tenez-nous mieux que ça.", "smirk")],
        [N("Allenna s’agenouille devant vous sur les dalles mouillées. Lineva pose un pied sur la banquette de pierre et présente son sexe à la main d’Allenna ; celle-ci referme ses lèvres autour de votre membre pendant que deux doigts caressent la perle de Lineva. Vous retenez leurs cheveux pour dégager leurs visages du jet."), P("Vous êtes splendides comme ça.")],
        [N("La bouche d’Allenna vous prend plus profondément, sa langue pressée sous votre sexe. Lineva se penche pour l’embrasser à chaque retrait, goûtant votre désir sur sa bouche, puis glisse elle-même deux doigts en Allenna. Le gémissement de la guerrière vous enveloppe et accélère ses lèvres."), L("Elle aime quand nous la prenons entre nous.", "breathless")],
        [N("Vous reculez avant le point de non-retour et relevez Allenna. Lineva se place dos au mur, une jambe levée dans vos bras ; Allenna s’accroupit devant elle et lèche sa perle pendant que vous entrez deux doigts en Lineva. La capitaine agrippe la barre de cuivre au-dessus de sa tête."), L("Pas question de glisser maintenant.", "shaken")],
        [N("Lineva jouit debout, prise entre vos doigts et la bouche d’Allenna. Son talon se crispe dans votre paume ; Allenna maintient sa langue pendant les contractions, puis remonte l’embrasser sous le jet. Vous gardez leurs deux bassins contre le vôtre, votre sexe tendu entre elles."), A("Une de nous ne tient déjà plus debout.", "smirk")],
        [N("Allenna vous plaque ensuite contre le carrelage et lève une jambe sur la hanche de Lineva. Celle-ci soutient sa cuisse et frotte sa perle du pouce ; vous guidez votre sexe à l’entrée d’Allenna puis la pénétrez debout, lentement, le mur prenant votre poids à chaque poussée."), A("Plus fort. Lineva me tient.", "determined")],
        [N("L’eau frappe le dos d’Allenna pendant que vous entrez profondément en elle. Lineva l’embrasse, garde sa jambe haute et poursuit la caresse entre ses cuisses. Allenna jouit autour de vous avec un cri noyé par le jet, ses ongles glissant sur votre épaule sans pouvoir s’y accrocher."), N("Lineva la maintient contre elle jusqu’à ce que ses jambes répondent.")],
        [N("Vous vous retirez et tournez Lineva face au mur. Allenna, encore secouée, lui offre sa bouche et passe une main entre vos corps. Vous pénétrez Lineva par derrière, vos mains sur ses hanches mouillées, tandis qu’Allenna l’embrasse et entretient sa perle à chaque poussée."), L("Voilà… cet angle-là.", "breathless")],
        [N("Le bassin de Lineva vient contre le vôtre, court et ferme. Allenna vous regarde par-dessus son épaule, sa main rejoignant vos bourses puis la base de votre sexe. Vous jouissez en Lineva tandis qu’elle agrippe le mur et embrasse Allenna, son propre second plaisir montant avec vos dernières poussées."), P("Je ne peux plus tenir.")],
        [N("Lineva reste appuyée au carrelage jusqu’à ce que vous sortiez lentement d’elle. Elle se retourne, embrasse votre bouche et laisse tomber la familiarité dans le ruissellement."), L("Tu peux perdre tes appuis. On ne te laissera pas tomber.", "soft")],
        [N("Allenna se met derrière Lineva et reprend son sexe de deux doigts tandis que vous vous agenouillez devant elle. Votre langue rejoint sa perle ; Allenna entre en elle au même rythme. Le second orgasme de Lineva la plie entre vous, rire et gémissement confondus."), L("Je retire ce que j’ai dit sur mes jambes.", "shaken")],
        [N("Les robinets se ferment enfin. Assis sur les dalles tièdes, vous séchez Allenna pendant qu’elle sèche Lineva ; la grande serviette finit sur vos trois genoux. Une flaque gagne les vêtements abandonnés, mais personne ne se lève pour les sauver.")],
      ],
      ellipse: [
        [N("Deux jets remplissent les douches de vapeur. Lineva jette sa tunique trempée près de la rigole ; Allenna retire la sienne plus lentement, puis rejoint votre corps nu contre le mur.")],
        [N("Vous embrassez Allenna tandis que Lineva savonne sa poitrine. L’eau force les mains à reprendre leurs prises ; chaque reprise les place un peu plus bas et rapproche davantage les trois bassins.")],
        [N("Allenna s’agenouille sur les dalles devant vous. Lineva reste près de son épaule, une main entre ses cuisses, et vos doigts retiennent leurs cheveux hors du courant.")],
        [N("Vous faites relever Allenna et placez Lineva contre le mur, une jambe soutenue. Les hauteurs changent ; la vapeur masque le détail lorsque la bouche d’Allenna descend et que votre bassin se rapproche.")],
        [N("La scène reste verticale, ponctuée d’appuis repris sur la barre et le carrelage. Allenna se retrouve ensuite contre le mur, Lineva soutenant sa cuisse tandis que vous restez entre elles.")],
        [N("Votre plaisir culmine sous le jet, distinct des leurs. Les deux femmes vous gardent debout puis poursuivent leurs mouvements derrière le rideau de vapeur sans attendre votre retour au calme.")],
        [N("Lineva retrouve votre bouche lorsque vous ouvrez les yeux."), L("Tu peux remercier ce mur. Nous lui devons beaucoup.", "soft")],
        [N("Allenna coupe l’eau. Vous restez assis sur les dalles dans une serviette commune, écoutant les dernières gouttes avant de rire de vos vêtements entièrement détrempés.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-training-homme-apres-duel",
    text: "Après le duel — recevoir l’audace tardive d’Allenna",
    detail: "La fatigue impose d’abord la douceur ; Allenna cesse ensuite de se cacher, chevauche le désir et conduit une seconde moitié beaucoup plus intense.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez rester sans jouer les vainqueurs. Je préfère savoir ce que vous voulez quand personne n’attend de performance.", "soft")],
      familiar: [L("Tu peux rester sans jouer les vainqueurs. Je préfère savoir ce que tu veux quand personne n’attend de performance.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Allenna s’assied sur le banc comme si ses jambes avaient attendu la porte close pour céder. Vous prenez place contre elle ; Lineva s’allonge au sol, la tête sur vos bottes, et annonce qu’elle ne bougera plus."), A("Elle ment. Mais pas dans la prochaine minute.", "tired")],
        [N("Vous défaites les doigts crispés d’Allenna un à un. Lineva pose sa main sur les vôtres, silencieuse. Les trois paumes restent empilées jusqu’à ce que l’effort quitte enfin les épaules d’Allenna.")],
        [N("Un baiser naît sans élan spectaculaire. Allenna le reçoit les yeux ouverts, rouge de se savoir observée ; Lineva se redresse juste assez pour embrasser sa tempe, puis vous laisse revenir à sa bouche.")],
        [N("Vous ouvrez les cols humides. Allenna pose sa joue sur votre poitrine nue ; Lineva se colle à son dos et passe un bras autour de vous deux. Le banc trop dur devient soudain le seul endroit où rester.")],
        [N("Les caresses se font plus profondes sous les vêtements desserrés. Allenna finit par prendre votre main et la placer là où son souffle change ; Lineva suit son geste d’un baiser au creux de son cou.")],
        [N("Votre plaisir monte sous leurs mains réunies, lent et entier. Vous vous abandonnez contre le casier ; Allenna vous tient à la taille, Lineva contre le cœur, et le frisson passe sans que personne cherche à le rendre spectaculaire.")],
        [N("Lineva garde sa paume sur votre poitrine après le calme."), L("Tu peux fermer les yeux. Nous sommes encore là.", "soft")],
        [N("Allenna étend deux serviettes sur le sol et vous attire tous deux dessus. Vous restez enlacés, trop fatigués pour remettre les bottes, jusqu’à ce que Lineva murmure le nom d’une soupe assez bonne pour justifier le trajet.")],
      ],
      suggestif: [
        [N("Le combat est fini ; l’effort demeure dans les bras lourds et les souffles courts. Allenna s’assied contre un casier, Lineva sur le banc, et vous vous installez entre elles sans chercher une posture élégante.")],
        [N("Vous essuyez la joue d’Allenna. Elle rougit sous votre attention, puis prend votre poignet et embrasse vos doigts. Lineva la regarde avec une tendresse qui ne réclame aucune plaisanterie.")],
        [N("Les tuniques s’ouvrent lentement. Allenna laisse votre bouche suivre sa poitrine ; Lineva embrasse son dos et garde une main sur votre ventre, reliant les trois corps sans presser leur fatigue.")],
        [N("Allenna change soudain de posture. Elle vous pousse contre le banc, vient à califourchon sur vos cuisses et embrasse Lineva par-dessus votre épaule avant de défaire elle-même votre ceinture."), A("Je suis fatiguée d’hésiter.", "determined")],
        [N("Lineva s’agenouille près de votre hanche et glisse ses mains sous la tenue d’Allenna. Celle-ci garde sa bouche sur la vôtre tandis que son bassin suit des caresses désormais invisibles au récit.")],
        [N("Le plaisir vous emporte sous Allenna, Lineva pressée contre votre flanc. Allenna reste assise sur vos cuisses jusqu’à ce que votre respiration se calme, puis se tourne pour offrir à Lineva un baiser long et étonnamment assuré.")],
        [N("Lineva sourit contre votre joue après le sommet."), L("Tu viens de voir le moment exact où elle a cessé de rougir.", "soft")],
        [N("Allenna rougit de nouveau à cette phrase, mais demeure entre vous. Une serviette couvre les trois corps ; le banc devient lit de fortune et le dîner une question volontairement repoussée.")],
      ],
      explicite: [
        [N("Allenna atteint le banc et s’y laisse tomber, les avant-bras sur les cuisses. Lineva s’assied au sol contre votre jambe, sa nuque offerte à votre main. Le vestiaire sent le cuir humide et l’effort ; aucun des trois n’a assez d’énergie pour transformer ce silence en défi."), A("Je sens encore chaque coup dans mes épaules.", "tired")],
        [N("Vous massez Allenna tandis que Lineva embrasse ses doigts meurtris. Allenna observe cette bouche sur sa main, puis votre torse lorsque vous ouvrez votre chemise. Sa rougeur la trahit avant son corps ; son regard descend malgré elle vers votre pantalon et n’en remonte qu’après une longue seconde."), L("Personne ne presse rien.", "soft")],
        [N("Allenna vous embrasse avec hésitation. Lineva vient contre son dos et ouvre sa tunique ; vous découvrez sa poitrine, embrassez un sein tandis que Lineva prend l’autre dans sa paume. Allenna se tend sous deux attentions puis saisit vos nuques, refusant elle-même que vous reculiez."), A("Je veux sentir vos regards. Même si j’en rougis.", "troubled")],
        [N("Vous allongez Lineva sur le banc et laissez Allenna choisir sa place. Elle s’agenouille entre les jambes de son amie, l’embrasse d’abord sur la bouche, puis descend. Vous restez près de la tête de Lineva, votre sexe sorti contre sa joue tandis qu’elle le caresse et qu’Allenna écarte ses cuisses."), L("Je crois qu’elle a choisi.", "breathless")],
        [N("Allenna lèche la perle de Lineva et glisse deux doigts en elle. Lineva prend votre sexe dans sa bouche, lentement à cause de la fatigue, sa langue enveloppant l’extrémité à chaque retrait. Vous caressez les cheveux des deux femmes et regardez Allenna perdre peu à peu sa gêne dans le plaisir qu’elle donne."), A("Elle serre mes doigts… continuez.", "focused")],
        [N("Lineva jouit la première, la bouche quittant votre sexe dans un gémissement grave. Allenna maintient ses doigts en elle pendant les contractions, puis remonte l’embrasser. Vous restez dur contre leurs ventres lorsque leurs lèvres se séparent ; Allenna le voit et se redresse avec une décision nouvelle."), A("Maintenant, moi.", "determined")],
        [N("Elle vous pousse assis contre le casier et vient à califourchon sur vos cuisses. Lineva, allongée à côté, guide votre sexe vers l’entrée humide d’Allenna. La guerrière descend lentement, vous accueille jusqu’au bout puis reste immobile, rouge mais le regard droit, pendant que Lineva caresse sa perle."), P("Prenez le rythme qui vous plaît.")],
        [N("Allenna commence par de courts mouvements, puis pose les mains sur vos épaules et vous chevauche avec une force que la fatigue n’avait pas effacée. Lineva se redresse pour l’embrasser et garde ses doigts entre vos bassins ; chaque remontée expose votre sexe luisant avant qu’Allenna ne le reprenne profondément."), A("Ne me regardez pas comme si j’allais me cacher.", "breathless")],
        [N("La main de Lineva et vos poussées font jouir Allenna au-dessus de vous. Elle se cambre, serre votre sexe à l’intérieur d’elle et mord l’épaule de son amie pour étouffer son cri. Lineva soutient sa taille jusqu’à ce que ses mouvements reprennent, plus lents, uniquement pour votre plaisir."), L("Elle ne se cache plus du tout.", "smirk")],
        [N("Allenna continue de vous chevaucher malgré ses jambes tremblantes ; Lineva se place derrière elle, prend ses seins et vous embrasse par-dessus son épaule. Vous jouissez en Allenna dans une série de poussées profondes, votre climax venant après le sien et non avec lui. Allenna vous garde en elle tandis que Lineva vous maintient tous deux contre sa poitrine jusqu’au calme."), P("Je n’ai plus rien à retenir.")],
        [N("Lineva pose son front au vôtre tandis qu’Allenna demeure sur vos cuisses. Le premier tutoiement arrive seulement après votre plaisir."), L("Tu avais raison de rester. Et maintenant tu vas nous aider à finir.", "soft")],
        [N("Allenna se retire et s’allonge à côté de vous. Vous plongez la tête entre les cuisses de Lineva ; Allenna, encore sensible, glisse deux doigts en elle et embrasse sa bouche. Votre langue sur sa perle et la main d’Allenna lui donnent un second orgasme, plus lent, qui achève de détendre tout son corps."), L("Je ne réclamerai aucune revanche avant demain.", "shaken")],
        [N("Vous restez nus sur le banc et le sol, couverts par deux serviettes mal réparties. Allenna apporte de l’eau sans remettre sa chemise ; Lineva lui vole une gorgée, reçoit un baiser en représailles et se rendort presque contre votre flanc. Le dîner attend sans urgence.")],
      ],
      ellipse: [
        [N("Les respirations du duel mettent longtemps à retomber. Allenna s’assied sur le banc, Lineva au sol contre vos jambes ; vous laissez le silence faire ce que les provocations faisaient jusque-là.")],
        [N("Vous massez les doigts d’Allenna. Lineva embrasse son poignet puis votre paume ; la guerrière rougit sous ce regard tranquille et choisit pourtant de ne plus le fuir.")],
        [N("Les tuniques s’ouvrent avec lenteur. Vous embrassez la poitrine d’Allenna tandis que Lineva reste contre son dos, les mains assez visibles pour que sa gêne se change en désir.")],
        [N("Allenna vous pousse soudain contre le banc et vient sur vos cuisses. Elle embrasse Lineva au-dessus de votre épaule, puis conduit elle-même vos mains sous les derniers vêtements.")],
        [N("La chronique recule devant le banc où vos trois corps se superposent. On voit encore Lineva allongée, Allenna redressée sur vous et les mains qui les empêchent de devenir deux scènes séparées.")],
        [N("Votre plaisir culmine après celui d’Allenna. Elle reste contre votre torse tandis que Lineva poursuit le sien dans le silence, et la fatigue rend chaque mouvement plus attentif.")],
        [N("Lineva vous rejoint après le calme, la joue sur votre épaule."), L("Tu peux rester exactement là. Même la soupe attendra.", "soft")],
        [N("Allenna déploie des serviettes sur le sol et vous rassemble dessus. Les vêtements restent là où ils sont ; trois corps épuisés choisissent de ne plus rien accomplir pendant quelques minutes.")],
      ],
    },
  },
];
const TRAINING_INTERSEXE: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-training-intersexe-revanche",
    text: "Revanche — imposer au banc les règles de votre corps",
    detail: "Le défi s’adapte aux plaisirs que vous montrez, tandis qu’Allenna et Lineva se renversent entre le bois, les casiers et vos interventions.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous décidez ce que nous pouvons prendre et ce que nous devons vous laisser conduire. Pour le reste, je compte gagner.", "smirk")],
      familiar: [L("Tu décides ce que nous pouvons prendre et ce que nous devons te laisser conduire. Pour le reste, je compte gagner.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Lineva occupe tout le banc en travers ; Allenna retire ses bottes et les pose exactement là où ses jambes devraient finir. Vous vous installez au milieu de cette querelle sans paroles et les obligez à se serrer contre vous.")],
        [N("Leurs épaules se rejoignent derrière votre nuque. Allenna embrasse votre joue, Lineva votre bouche ; vous inversez leurs places d’une traction aux ceintures et obtenez deux rires très différents.")],
        [N("Vous prenez leurs mains et leur montrez les zones où la caresse vous apaise, celles où elle vous trouble. Elles suivent sans supposer, puis leurs doigts se croisent sur votre peau au lieu de se relayer.")],
        [N("Allenna s’allonge sur vos cuisses. Lineva lui ouvre le col tandis que vous caressez sa tempe ; la guerrière rougit mais tourne la bouche vers son amie pour réclamer un baiser.")],
        [N("Le banc devient trop court lorsque Lineva vient à moitié sur vous. Les trois jambes se nouent, les souffles se rapprochent et le défi se dissout dans une chaleur choisie ensemble.")],
        [N("Les attentions convergent exactement là où vous les avez guidées. Votre plaisir se dénoue entre leurs mains, votre front contre celui d’Allenna et la bouche de Lineva sur votre épaule.")],
        [N("Lineva garde vos doigts dans les siens après le sommet."), L("Tu viens de fixer une règle que j’accepte volontiers : ne rien deviner à ta place.", "soft")],
        [N("Allenna couvre le trio d’une serviette et garde le centre du banc. Les brassards restent dispersés ; une nouvelle revanche est annoncée, puis repoussée jusqu’à ce que les respirations soient redevenues normales.")],
      ],
      suggestif: [
        [N("La porte se verrouille et les pièces d’armure tombent près des casiers. Lineva vous attire au banc ; Allenna s’assied de l’autre côté, attentive aux gestes par lesquels vous lui montrez ce que votre corps désire ce soir.")],
        [N("Vous posez une main de Lineva sur une zone sensible et celle d’Allenna plus bas, à l’endroit que vous voulez ouvrir à ses doigts. Elles répondent ensemble au changement de votre souffle.")],
        [N("Allenna vous embrasse pendant que Lineva défait vos attaches. Vous les déshabillez à votre tour ; leurs peaux chaudes se touchent devant vous, et Allenna cesse de détourner les yeux.")],
        [N("Lineva s’allonge sur le banc. Allenna vient entre ses cuisses ; vous restez à genoux près de leurs visages, donnant une main à l’une et votre bouche à l’autre.")],
        [N("Les silhouettes se renversent : Allenna sur vos cuisses, Lineva contre votre dos. Leurs caresses suivent les plaisirs que vous avez nommés sans interrompre leurs propres baisers.")],
        [N("La chronique retient seulement la montée claire de votre plaisir, les deux femmes qui restent actives l’une auprès de l’autre et le frisson qui vous traverse entre elles.")],
        [N("Lineva embrasse votre paume après que votre souffle revient."), L("Tu rends la défaite beaucoup trop tentante.", "soft")],
        [N("Vous partagez le banc et une gourde. Allenna remet une mèche derrière l’oreille de Lineva ; la capitaine lui vole un baiser au lieu de contester encore le résultat.")],
      ],
      explicite: [
        [N("Lineva ferme la porte d’un coup de talon et lance son baudrier vers les casiers. Allenna le rattrape, le pose proprement puis vient vous défaire le vôtre. Vous leur montrez d’un geste ce que votre corps offre ce soir et où chacune peut chercher votre plaisir ; leurs regards restent sur vous, non sur une idée préfabriquée."), P("Pas de supposition. Suivez mes mains.")],
        [N("Vous faites asseoir Lineva sur le banc et Allenna se place derrière elle. Votre bouche prend celle de la capitaine tandis qu’Allenna ouvre sa chemise et caresse ses seins. Une de vos mains glisse entre les cuisses de Lineva ; l’autre attire Allenna assez près pour que leurs bouches se rencontrent au-dessus de votre épaule."), L("Une entrée en matière convaincante.", "smirk")],
        [N("Allenna vous déshabille ensuite. Vous guidez sa bouche vers la partie de votre sexe qui se dresse sous son souffle et placez les doigts de Lineva à l’ouverture sensible que vous souhaitez sentir remplie. Elles commencent lentement, l’une avec sa langue, l’autre avec deux doigts, leurs épaules pressées l’une contre l’autre."), A("Comme cela ?"), P("Exactement. Ensemble.")],
        [N("La bouche d’Allenna enveloppe votre désir extérieur tandis que les doigts de Lineva entrent et se courbent en vous. Vous écartez les cuisses sur le banc, une main dans chaque chevelure. Allenna glisse sa propre main entre les jambes de Lineva et la stimule sans interrompre les mouvements de ses lèvres."), L("Elle refuse vraiment de laisser quelqu’un attendre.", "breathless")],
        [N("Vous les arrêtez avant le climax et renversez Allenna sur le bois. Lineva s’agenouille entre ses cuisses, lèche sa perle et enfonce deux doigts dans sa chaleur. Vous vous placez près du visage d’Allenna ; sa bouche reprend la partie de votre sexe que vous lui présentez pendant que vos doigts caressent la poitrine de Lineva."), A("Ne ralentissez ni l’une ni l’autre.", "breathless")],
        [N("Allenna jouit la première. Sa bouche quitte votre sexe dans un cri, mais sa main y reste ; Lineva poursuit sa langue jusqu’au dernier tremblement. Vous embrassez Allenna puis Lineva, mêlant leurs souffles pendant que la guerrière retrouve assez de force pour sourire."), A("Ce point n’était pas prévu."), L("Les meilleurs ne le sont pas.", "smirk")],
        [N("Allenna vous fait coucher à votre tour et Lineva vient à califourchon sur votre poitrine, tournée vers vos jambes. Elle reprend votre sexe extérieur dans sa bouche ; Allenna s’allonge près de votre hanche, deux doigts dans votre ouverture, tandis que votre langue atteint le sexe de Lineva au-dessus de vous."), P("Gardez cette position.")],
        [N("Vous léchez Lineva pendant qu’elle vous suce, vos mains sur ses fesses pour régler son angle. Allenna maintient ses doigts en vous et embrasse la cuisse de son amie. Lineva jouit contre votre bouche, mais continue ses lèvres autour de votre désir au lieu de quitter le cercle."), L("Je n’ai pas dit que j’arrêtais.", "shaken")],
        [N("Allenna remplace alors les doigts par sa langue à votre ouverture, tandis que Lineva garde sa bouche sur votre sexe extérieur et une main sur la nuque d’Allenna. Les deux rythmes se rejoignent sans se confondre ; vous les sentez travailler l’une avec l’autre à travers votre corps."), P("Encore… toutes les deux.")],
        [N("Votre orgasme arrive sous cette double stimulation. Votre sexe pulse entre les lèvres de Lineva tandis que votre ouverture se contracte contre la langue d’Allenna ; elles restent en place pendant chaque vague, puis ralentissent séparément lorsque vos mains cessent de les retenir.")],
        [N("Lineva remonte s’allonger contre vous et pose sa bouche sur votre tempe."), L("Tu viens de gagner sans choisir entre tes plaisirs. Je reconnais la beauté du geste.", "soft")],
        [N("Vous n’en avez pas fini avec Allenna. Elle s’assied à cheval sur le banc ; Lineva se place derrière elle et lui ouvre les cuisses. Votre bouche trouve sa perle, vos doigts entrent en elle, ceux de Lineva caressent ses seins. Allenna jouit de nouveau, cette fois contre vos deux corps, sans la moindre retenue."), A("Je retire toute objection à cette revanche.", "shaken")],
        [N("Les trois serviettes restent empilées hors de portée. Vous finissez nus sur le banc, Allenna contre votre ventre et Lineva derrière elle, à boire dans la même gourde. L’équipement abandonné raconte mieux le désordre que n’importe quel score.")],
      ],
      ellipse: [
        [N("Les casiers sont fermés, les armes laissées au mur. Vous vous asseyez entre Allenna et Lineva et leur montrez par vos propres mains la forme de proximité que votre corps appelle.")],
        [N("Lineva vous embrasse tandis qu’Allenna ouvre vos vêtements. Leurs doigts prennent deux chemins distincts, tous deux guidés par vos réactions plutôt que par une catégorie.")],
        [N("Vous placez Allenna sur le banc et Lineva derrière elle. Leurs bouches se rencontrent tandis que vos mains découvrent chacune sans attribuer de rôle fixe.")],
        [N("Les positions changent encore : Lineva allongée, Allenna entre ses cuisses, vous près de leurs visages. Les trois corps restent lisibles jusqu’au bord du fondu.")],
        [N("La chronique se retire lorsque leurs attentions reviennent ensemble vers les zones que vous leur avez indiquées. Le banc grince ; une main d’Allenna reste nouée à celle de Lineva.")],
        [N("Votre plaisir atteint son sommet dans ce cercle choisi. Derrière le rideau, Allenna puis Lineva reçoivent à leur tour sans que la géographie du trio se défasse.")],
        [N("Lineva revient contre votre poitrine lorsque tout se calme."), L("Tu viens de rendre les anciennes règles parfaitement inutiles.", "soft")],
        [N("Une seule serviette couvre trois bassins et trop de jambes. Allenna rit lorsqu’elle essaie de reconstituer le score ; Lineva l’embrasse pour lui épargner ce travail.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-training-intersexe-douches",
    text: "Sous les douches — guider deux bouches dans la vapeur",
    detail: "Le mur soutient votre corps pendant que l’eau impose des prises mouvantes et que les deux femmes suivent les plaisirs que vous leur confiez.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous nous montrerez où l’eau aide et où elle gêne. Je me charge de rendre le reste mémorable.", "smirk")],
      familiar: [L("Tu nous montreras où l’eau aide et où elle gêne. Je me charge de rendre le reste mémorable.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 8, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 9, ellipse: 6 },
      revealChapter: 3,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("La vapeur accueille vos trois silhouettes. Lineva passe sous le jet, Allenna ajuste l’eau avec soin et vous les rejoignez en indiquant d’un sourire la place que vous voulez entre elles.")],
        [N("Allenna savonne votre dos ; Lineva votre poitrine. Leurs mains se croisent sur vos flancs et l’eau emporte aussitôt toute tentative de conserver des gestes sages.")],
        [N("Vous glissez d’un demi-pas. Elles vous retiennent ensemble, puis restent contre vous au mur, les cheveux collés à la peau et les rires mêlés au fracas du jet.")],
        [N("Les baisers tournent : votre bouche sur Allenna, celle de Lineva sur votre cou, puis leurs lèvres réunies devant vous pendant que vos bras les encerclent.")],
        [N("Vous guidez leurs paumes vers les caresses qui vous conviennent. L’une soutient vos hanches, l’autre suit le plaisir, et elles échangent la tâche sans perdre leur contact.")],
        [N("Le frisson vous traverse contre le carrelage. Allenna garde son front au vôtre ; Lineva serre votre main sous l’eau jusqu’à ce que votre respiration redevienne régulière.")],
        [N("Lineva embrasse vos doigts mouillés après le sommet."), L("Tu peux toujours compter sur nous pour les appuis difficiles.", "soft")],
        [N("Le jet s’arrête. Allenna vous sèche les épaules pendant que vous séchez Lineva ; la serviette passe de l’un à l’autre sans que les trois corps cessent de se toucher.")],
      ],
      suggestif: [
        [N("Lineva ouvre l’eau avant d’enlever sa chemise. Allenna la lui retire lorsqu’elle colle à sa peau ; vous les rejoignez nu, votre corps visible dans la vapeur et vos envies montrées sans gêne.")],
        [N("Vous placez leurs mains là où vous souhaitez commencer. Allenna suit lentement ; Lineva transforme votre indication en caresse plus joueuse, puis accepte votre correction avec un sourire.")],
        [N("Dos au mur, vous embrassez Allenna. Lineva reste derrière elle, défait ses cheveux et descend une main entre ses cuisses tandis que vos doigts parcourent sa poitrine.")],
        [N("Les hauteurs changent. Allenna s’accroupit devant vous, Lineva soutient votre jambe et leurs bouches se partagent les chemins que vous avez choisis, encore masqués par la vapeur.")],
        [N("Vous faites relever Allenna et placez Lineva contre la pierre. Les trois corps pivotent sans se séparer ; chaque prise glissante oblige une nouvelle étreinte.")],
        [N("Votre plaisir culmine debout entre elles. L’eau couvre votre voix mais pas leurs visages, tournés vers vous jusqu’au dernier frisson.")],
        [N("Lineva pose sa bouche contre votre front mouillé."), L("Tu es beaucoup trop beau comme ça pour que je prétende rester raisonnable.", "soft")],
        [N("Allenna coupe l’eau et ramène une serviette autour de vous trois. Ses joues restent rouges ; ses mains demeurent parfaitement décidées lorsqu’elle garde Lineva et vous près d’elle.")],
      ],
      explicite: [
        [N("Les jets couvrent le bruit de la porte que Lineva ferme. Vous vous déshabillez dans la vapeur et leur montrez les deux zones de votre corps que vous voulez voir stimulées. Allenna écoute du regard ; Lineva vient déjà poser sa paume sur l’une, puis attend votre geste pour choisir l’autre."), P("Commencez debout. Je veux vous voir toutes les deux.")],
        [N("Allenna vous plaque doucement au mur et embrasse votre bouche. Lineva se met derrière elle, savonne ses seins et descend entre ses cuisses. Vous guidez la main d’Allenna sur votre sexe extérieur tandis que la vôtre rejoint les doigts de Lineva dans la chaleur de la guerrière."), A("Je vous tiens. Laissez le mur prendre le reste.")],
        [N("Lineva s’accroupit entre vos jambes. Vous relevez un pied sur la banquette afin d’ouvrir l’accès que vous lui avez choisi ; sa langue s’y pose pendant qu’Allenna prend votre autre plaisir entre ses lèvres. Les deux femmes restent épaule contre épaule, l’eau ruisselant sur leurs visages tournés vers vous."), L("Voilà une position qui mérite d’être gardée.", "breathless")],
        [N("La bouche d’Allenna va et vient autour de votre sexe dressé tandis que Lineva glisse deux doigts dans votre ouverture et lèche sa bordure. Vous tenez le pommeau au-dessus d’elles pour dégager leurs souffles ; Allenna tend une main vers le sexe de Lineva et y maintient une caresse rapide."), P("Ensemble… ne vous éloignez pas.")],
        [N("Vous les relevez avant de jouir. Allenna se place dos au mur, Lineva devant elle ; vous vous agenouillez entre leurs jambes, léchant Allenna pendant que deux de vos doigts entrent en Lineva. Elles s’embrassent au-dessus de vous et tiennent chacune une de vos épaules mouillées."), A("Lineva va céder."), L("Parlez moins vite.", "shaken")],
        [N("Lineva jouit la première autour de vos doigts. Allenna serre sa taille et frotte encore sa perle du pouce tandis que votre langue poursuit celle d’Allenna. La capitaine reste debout grâce au mur et au corps de son amie, le rire défait par les contractions.")],
        [N("Allenna vous replace ensuite contre les carreaux et s’accroupit. Elle reprend votre sexe extérieur dans sa bouche ; Lineva, encore tremblante, glisse derrière vous et entre deux doigts dans votre ouverture. Vous sentez leurs mains se retrouver à votre bassin pour coordonner la profondeur et la cadence."), A("Cette fois, nous allons jusqu’au bout.", "determined")],
        [N("Lineva embrasse votre nuque tout en vous pénétrant de ses doigts. Allenna accélère sa bouche, sa langue serrée autour de votre plaisir extérieur. Vous retenez leurs poignets contre vous ; la chaleur monte malgré l’eau et rend vos appuis inutiles.")],
        [N("Votre orgasme éclate dans les deux directions : votre sexe pulse dans la bouche d’Allenna, votre ouverture se contracte autour des doigts de Lineva. Elles maintiennent exactement leurs places jusqu’à la dernière vague, puis se relèvent pour vous porter à trois contre le mur."), P("Ne me lâchez pas.")],
        [N("Lineva essuie l’eau sur vos lèvres et les embrasse."), L("Tu peux lâcher. Je t’ai promis les appuis.", "soft")],
        [N("Allenna réclame sa part d’un geste. Elle se tourne face au mur ; Lineva frotte sa perle tandis que votre bouche descend entre ses cuisses et que deux doigts entrent en elle. L’eau glisse dans son dos jusqu’à ce que son orgasme la cambre contre vos deux corps."), A("Je n’ai plus besoin du mur.", "shaken")],
        [N("Lineva n’en reste pas là : elle s’assied sur la banquette, Allenna s’agenouille devant elle et vous la pénétrez de vos doigts depuis le côté que vous choisissez. La bouche d’Allenna et votre main lui donnent un second plaisir, plus lent, dans lequel elle se laisse tomber sans défi."), L("Je reconnais une excellente douche.", "soft")],
        [N("Vous fermez les jets et restez assis sur les dalles, trois peaux encore ruisselantes sous deux serviettes. Allenna essore les cheveux de Lineva ; vous essuyez les siens. Le vestiaire peut attendre que vos jambes se souviennent de leur fonction.")],
      ],
      ellipse: [
        [N("La vapeur efface les angles de la pièce. Vous indiquez aux deux femmes ce que votre corps réclame ; Lineva sourit, Allenna hoche simplement la tête avant de vous attirer sous l’eau.")],
        [N("Leurs mains suivent deux chemins choisis sur votre peau. Vous embrassez Allenna pendant que Lineva reste contre son dos, et l’eau rend leurs caresses visibles par leurs reprises constantes.")],
        [N("Dos au mur, vous levez une jambe. Allenna et Lineva changent de hauteur, leurs épaules se touchent devant vous et leurs silhouettes ne laissent aucune personne hors de la scène.")],
        [N("Vous inversez ensuite les places : Allenna contre le carrelage, Lineva devant elle, vous agenouillé entre leurs jambes. La vapeur ferme doucement le cadre.")],
        [N("Les appuis glissent, se retrouvent et forcent les trois corps à se serrer. Les gestes précis disparaissent, mais la douche continue de dicter chaque position.")],
        [N("Votre plaisir culmine sous le jet avant ceux des deux femmes. Elles vous soutiennent puis poursuivent l’une avec l’autre, vos mains encore présentes dans leur mouvement.")],
        [N("Lineva revient toucher votre joue après le sommet."), L("Tu peux oublier le sol. Nous ne te laissons pas tomber.", "soft")],
        [N("Le silence revient quand Allenna ferme l’eau. Une serviette commune, des cheveux impossibles à démêler et trois sourires épuisés achèvent la scène sur les dalles tièdes.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-training-intersexe-apres-duel",
    text: "Après le duel — offrir à Allenna une confiance sans modèle",
    detail: "La lenteur née de la fatigue laisse chacun montrer son désir ; Allenna transforme ensuite sa gêne en une initiative précise et ardente.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous n’avez pas à traduire votre corps pour nous. Montrez seulement ce qui vous fait du bien, et restez près de nous.", "soft")],
      familiar: [L("Tu n’as pas à traduire ton corps pour nous. Montre seulement ce qui te fait du bien, et reste près de nous.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous vous asseyez entre Allenna et Lineva, toutes trois trop fatiguées pour tenir une posture. La tête d’Allenna tombe sur votre épaule ; celle de Lineva trouve vos genoux.")],
        [N("Vos doigts dénouent les mains d’Allenna. Lineva embrasse votre paume puis la sienne, et la tension quitte lentement les trois corps sans qu’aucun mot soit nécessaire.")],
        [N("Allenna rougit lorsque son col s’ouvre. Vous lui montrez le même tremblement sur votre peau ; elle comprend, sourit à peine et vous embrasse avec une douceur soudain moins inquiète.")],
        [N("Lineva vient derrière Allenna. Ses bras vous entourent tous deux ; vos mains se retrouvent sur le ventre de la guerrière, qui garde les yeux ouverts malgré le regard partagé.")],
        [N("Vous guidez leurs caresses sur votre corps réel. Allenna suit votre respiration, Lineva votre main ; aucune ne réclame d’explication et leurs baisers continuent de circuler entre elles.")],
        [N("Le plaisir se défait lentement au creux de cette fatigue. Allenna vous retient contre elle, Lineva caresse votre visage et le sommet vous laisse plus calme que brisé.")],
        [N("Lineva reste près de votre oreille."), L("Tu peux dormir ici. Ton corps n’a plus rien à nous expliquer.", "soft")],
        [N("Allenna tire une serviette sur les trois épaules. Vous restez au sol, étroitement réunis, jusqu’à ce qu’une faim tardive devienne la seule raison acceptable de bouger.")],
      ],
      suggestif: [
        [N("Le silence du vestiaire vous trouve assis au sol avec Lineva, Allenna sur le banc. Elle regarde vos mains jointes puis descend vous rejoindre, encore rouge de l’effort et de l’idée d’être désirée.")],
        [N("Vous ouvrez votre tenue et lui montrez où son toucher vous plaît. Elle pose sa main sans supposer davantage ; Lineva embrasse son épaule, attentive à son courage plus qu’à sa précision.")],
        [N("Allenna retire sa propre chemise. Votre bouche suit sa poitrine tandis que Lineva caresse son dos ; son souffle hésite, puis ses mains vous attirent tous deux plus près.")],
        [N("Elle vous allonge soudain sur le banc et vient au-dessus de vous. Lineva s’agenouille près de votre tête ; Allenna l’embrasse avant de conduire leurs deux mains sur votre corps.")],
        [N("Les gestes quittent le cadre, jamais les positions : Allenna sur vos cuisses, Lineva contre votre flanc, leurs bouches passant de votre peau à celle de l’autre.")],
        [N("Votre plaisir culmine sous cette initiative nouvelle. Allenna ne détourne pas les yeux ; Lineva garde votre main contre son cœur jusqu’à ce que le frisson s’apaise.")],
        [N("La voix de Lineva arrive basse dans le calme."), L("Tu as vu comme elle a cessé de retenir sa propre envie ?", "soft")],
        [N("Allenna rougit encore, puis embrasse Lineva pour répondre. Une serviette couvre vos jambes et le reste de la soirée demeure sans score ni urgence.")],
      ],
      explicite: [
        [N("La fatigue vous rassemble sur le banc sans ordre. Allenna garde ses mains serrées entre ses genoux ; Lineva s’appuie contre votre hanche, les yeux fermés. Vous leur montrez les réactions encore visibles de votre corps après le duel, sans leur demander de les classer ni de les deviner."), P("Je veux de la lenteur. Et vos deux mains.")],
        [N("Allenna pose une main là où vous la conduisez ; Lineva prend l’autre place. Leurs caresses commencent au-dessus des vêtements, puis vous ouvrez vous-même les attaches. Allenna rougit devant l’intimité révélée, mais son pouce suit déjà le trajet que votre propre doigt lui montre."), A("Je regarde parce que j’en ai envie.", "troubled")],
        [N("Vous déshabillez Allenna à votre tour. Lineva s’assied derrière elle et embrasse son épaule pendant que votre bouche prend un sein. Allenna serre vos deux têtes contre sa poitrine ; sa gêne reste dans ses joues, plus dans la façon dont ses cuisses s’ouvrent devant vous."), L("Elle est magnifique quand elle choisit.", "soft")],
        [N("Vous placez Lineva sur le dos au bout du banc. Allenna s’agenouille entre ses jambes et glisse deux doigts en elle ; votre bouche lèche la perle de la capitaine tandis que Lineva tend une main vers le plaisir extérieur de votre corps et l’autre vers l’ouverture que vous lui avez indiquée."), L("Gardez-moi entre vous.", "breathless")],
        [N("Allenna accélère ses doigts en Lineva. Vous maintenez la langue sur sa perle ; Lineva vous stimule des deux façons choisies, ses gestes troublés par ce qu’elle reçoit. Son orgasme arrive le premier et tend son ventre sous votre paume avant de la laisser haletante sous Allenna."), A("Elle tremble encore.", "soft")],
        [N("Allenna se redresse alors avec une détermination qui surprend. Elle vous allonge à la place de Lineva, s’installe entre vos jambes et donne à son amie la place près de votre bouche. Puis elle reprend sur vous exactement les deux gestes montrés plus tôt, cette fois sans hésitation."), A("Je ne veux plus m’arrêter pour rougir.", "determined")],
        [N("Lineva s’accroupit au-dessus de votre bouche ; vous léchez son sexe tandis qu’elle caresse votre poitrine. Allenna prend votre plaisir extérieur entre ses lèvres et glisse ses doigts dans votre ouverture, alternant profondeur et pression. Le trio forme une chaîne où chacune reçoit pendant qu’elle donne."), P("Allenna… gardez ce rythme.")],
        [N("Votre langue fait jouir Lineva une seconde fois. Elle reste au-dessus de vous, jambes tremblantes, et embrasse Allenna lorsqu’elle se penche. Cette dernière ne cesse ni sa bouche ni ses doigts ; son initiative devient plus assurée à chaque réaction qu’elle vous arrache."), L("Elle ne s’arrêtera plus maintenant.", "shaken")],
        [N("Vous changez seulement l’angle de vos hanches afin qu’Allenna vous atteigne plus profondément. Lineva descend une main entre les cuisses de son amie et la stimule pendant qu’elle vous donne du plaisir. Les deux femmes s’embrassent au-dessus de votre ventre, Allenna gémissant sans perdre sa cadence."), A("Encore un peu… tous les deux.", "breathless")],
        [N("Votre orgasme vous traverse sous la bouche et les doigts d’Allenna. Lineva tient votre bassin contre le banc ; Allenna reste en place jusqu’au dernier spasme, puis remonte lentement en vous embrassant le ventre. Votre climax s’achève avant que l’une d’elles ne réclame la suite.")],
        [N("Lineva se couche contre votre flanc et laisse le tutoiement ouvrir l’après."), L("Tu n’avais rien à traduire. On t’a très bien compris.", "soft")],
        [N("Vous faites asseoir Allenna à cheval sur votre visage. Lineva vient derrière elle, masse ses seins puis glisse deux doigts en elle tandis que votre langue reste sur sa perle. Allenna jouit en se cambrant contre vous, sa main agrippée à celle de Lineva plutôt qu’au casier."), A("Je ne regrette pas d’avoir choisi.", "shaken")],
        [N("Vous finissez étendus sur des serviettes, Allenna au milieu, Lineva contre son dos. Une gourde passe entre vos mains ; personne ne réassemble l’équipement. La fatigue revient, débarrassée de toute tension, et vous laisse assez proches pour vous endormir presque là.")],
        [N("Allenna finit par vous faire lever pour aller manger, mais conserve une main dans la vôtre et l’autre autour de Lineva. Les trois silhouettes quittent le vestiaire sans reconstruire leurs défenses ni leurs distances.")],
      ],
      ellipse: [
        [N("Le duel laisse trois corps trop lourds pour se tenir droits. Vous vous asseyez entre Allenna et Lineva et leur montrez simplement la proximité que vous voulez recevoir.")],
        [N("Allenna suit votre main sur votre peau ; Lineva suit votre souffle. Elles n’interprètent rien à votre place et restent en contact l’une avec l’autre pendant qu’elles vous découvrent.")],
        [N("Vous déshabillez Allenna. Elle rougit sous vos regards, puis vous attire contre sa poitrine et embrasse Lineva avec une décision qui commence à effacer sa gêne.")],
        [N("Lineva s’allonge sur le banc ; Allenna s’agenouille entre ses jambes et vous prenez place près de leurs visages. Les corps forment un cercle clair avant que le récit se retire.")],
        [N("Allenna change ensuite toutes les places. Elle vous allonge, appelle Lineva contre votre bouche et conduit elle-même les gestes que vous lui avez montrés.")],
        [N("Votre plaisir culmine dans cette initiative. Les deux femmes continuent après vous ; la fatigue ralentit leurs mouvements sans en diminuer la franchise.")],
        [N("Lineva garde votre main contre sa joue."), L("Tu peux laisser ton corps parler comme il veut. Nous restons.", "soft")],
        [N("Allenna se glisse sous la serviette entre vous. Les vêtements et la faim attendent ; le banc accueille encore quelques minutes de silence et trois respirations apaisées.")],
      ],
    },
  },
];

export const LINEVA_ALLENNA_TRAINING_ROUTES: Record<PlayerSex, GroupIntimacyRoute[]> = {
  femme: TRAINING_FEMME,
  homme: TRAINING_HOMME,
  intersexe: TRAINING_INTERSEXE,
};
