import type { PlayerSex } from "./date-scenes";
import type { DialogueLine } from "./game-data";
import type { GroupIntimacyRoute } from "./group-dates";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const A = (text: string, mood?: string): DialogueLine => ({ speaker: "Allenna", text, mood });
const L = (text: string, mood?: string): DialogueLine => ({ speaker: "Lineva", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });

const HOME_FEMME: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-home-femme-canape",
    text: "Canapé trop petit — laisser les jambes décider",
    detail: "Une soirée ordinaire glisse vers le sexe parce que trois corps refusent de se répartir raisonnablement sur un meuble prévu pour deux.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez prendre le dernier coussin. Mais si vos jambes finissent sur les miennes, je considérerai que c’est volontaire.", "smirk")],
      familiar: [L("Tu peux prendre le dernier coussin. Mais si tes jambes finissent sur les miennes, je considérerai que c’est volontaire.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Trois tasses occupent la table basse et Lineva presque tout le canapé. Allenna soulève ses pieds, vous vous glissez dessous, puis tout le monde prétend que cette répartition impossible est confortable."), A("Personne ne bouge. Ce serait pire.", "soft")],
        [N("Vos jambes finissent sur les cuisses de Lineva ; Allenna se retrouve à moitié appuyée contre votre épaule. La conversation continue autour de rien, ponctuée de petites corrections de position qui rapprochent encore les corps.")],
        [N("Lineva rit contre votre joue. Lorsque vous tournez la tête, vos lèvres se rencontrent. Le baiser aurait pu rester accidentel ; Allenna en pose un second au coin de votre bouche et détruit cette possibilité.")],
        [N("Vous embrassez Allenna tandis que Lineva garde vos chevilles sur ses genoux. Puis elle se penche au-dessus de vos jambes, embrasse son amie et vous attire dans le même mouvement.")],
        [N("Une couverture tombe du dossier. Vous la tirez sur les trois corps ; dessous, les mains trouvent les tailles, les ventres et les peaux chaudes sans que personne propose de changer de pièce.")],
        [N("Le plaisir monte doucement sous leurs caresses cachées. Le canapé vous maintient serrée contre Allenna, Lineva en travers de vos jambes, et votre frisson s’achève dans leurs deux baisers.")],
        [N("Lineva repousse une mèche de votre front après le sommet."), L("Tu avais raison : bouger aurait vraiment été pire.", "soft")],
        [N("Les tasses refroidissent. Allenna ajuste la couverture, Lineva garde vos pieds contre son ventre et vous restez toutes trois dans le creux du canapé jusqu’à vous endormir presque.")],
      ],
      suggestif: [
        [N("Lineva est allongée en travers du canapé ; Allenna prend le coin restant et vous vous asseyez entre elles. Vos genoux montent, leurs jambes se croisent sur les vôtres et aucune conversation ne justifie cette proximité.")],
        [N("Votre main repose sur la cuisse de Lineva. Allenna pose la sienne sur votre ventre ; un silence court passe avant que vous embrassiez l’une, puis que l’autre vous ramène vers sa bouche.")],
        [N("Les baisers s’allongent. Allenna ouvre votre chemise ; Lineva ouvre celle d’Allenna et glisse derrière elle malgré le dossier, leurs corps comprimés contre votre flanc.")],
        [N("Vous vous retrouvez à moitié couchée sur les genoux d’Allenna, Lineva agenouillée au bout du canapé. Sa bouche descend tandis qu’Allenna vous embrasse et garde une main sur sa nuque.")],
        [N("Le meuble grince quand vous inversez les places. Allenna vient entre vos jambes, Lineva contre votre poitrine ; leurs gestes disparaissent sous la couverture sans que les positions deviennent floues.")],
        [N("Votre plaisir culmine dans cet espace trop étroit. Allenna vous tient par les hanches, Lineva par le visage, et un coussin tombe au sol au moment où votre corps se cambre.")],
        [N("Lineva ramasse le coussin sans quitter le canapé."), L("Tu viens de gagner sa place. Je ne sais pas si le canapé s’en remettra.", "soft")],
        [N("Allenna tire la couverture sur vous trois. La théière demeure oubliée ; personne ne souhaite atteindre la lumière et le salon reste doucement allumé jusqu’au sommeil.")],
      ],
      explicite: [
        [N("La soirée a commencé par du thé et une histoire si insignifiante que Lineva en a oublié la fin. Elle occupe le canapé en diagonale ; Allenna se cale dans un coin et vous prenez l’espace entre elles. Vos jambes reposent sur Lineva, votre épaule sous la joue d’Allenna."), L("Voilà. Trois personnes tiennent parfaitement.", "pleased")],
        [N("Vous riez, tournez la tête et rencontrez la bouche de Lineva. Le baiser dure une seconde de trop ; Allenna le regarde, rouge mais souriante. Vous l’attirez par le col pour lui offrir le suivant, puis Lineva se penche au-dessus de vos jambes et embrasse Allenna à son tour."), A("Le thé va refroidir."), L("Il survivra.", "smirk")],
        [N("Les chemises s’ouvrent sans décision annoncée. Allenna découvre votre poitrine, Lineva celle d’Allenna ; vous prenez un sein de chaque femme dans vos mains pendant qu’elles s’embrassent au-dessus de vous. Le dossier oblige Allenna à rester presque couchée sur votre flanc."), P("Ne cherchons pas une meilleure place.")],
        [N("Lineva se glisse au bout du canapé et retire votre pantalon. Vous restez à moitié assise contre Allenna, les jambes ouvertes sur les genoux de la capitaine. Allenna embrasse votre cou et descend une main entre les cuisses de Lineva, agenouillée près de vos pieds."), L("Ce meuble vient de devenir beaucoup plus intéressant.", "breathless")],
        [N("Lineva pose sa bouche sur votre sexe. Sa langue trouve votre perle tandis que deux doigts entrent en vous. Allenna vous soutient contre le dossier, vous embrasse et caresse Lineva entre les cuisses ; vos propres doigts glissent sous sa jupe et l’ouvrent à votre main."), A("Nous sommes vraiment trop serrées.", "breathless"), P("C’est précisément ce qui me plaît.")],
        [N("Les doigts de Lineva et sa langue accélèrent. Vous pénétrez Allenna de deux doigts pendant qu’elle fait de même à Lineva, leurs hanches bougeant de part et d’autre de votre jambe. La chaîne se tend ; Allenna jouit la première contre votre main, sa bouche ouverte sur votre épaule."), A("Ne vous arrêtez pas pour moi.", "shaken")],
        [N("Vous tirez Lineva sur le canapé. Allenna, encore tremblante, se place entre ses cuisses et lèche sa perle ; vous vous allongez derrière la capitaine, deux doigts en elle et votre bouche sur sa nuque. Lineva s’agrippe au dossier plutôt qu’à vos épaules."), L("Le canapé va porter plainte.", "shaken")],
        [N("Lineva jouit sous la bouche d’Allenna et vos doigts, ses fesses pressées contre votre bassin. Un coussin tombe ; personne ne le regarde. Allenna poursuit jusqu’au dernier spasme puis remonte embrasser Lineva, tandis que vous les enlacez toutes deux depuis l’arrière.")],
        [N("Elles vous ramènent ensuite au centre. Allenna s’allonge contre le dossier, vous sur le côté face à elle ; Lineva reste en travers de vos jambes. Allenna entre deux doigts en vous pendant que Lineva reprend votre perle avec sa bouche et garde une main sur le sexe d’Allenna."), P("Cette fois, jusqu’au bout.")],
        [N("Votre orgasme arrive dans cette position compacte, vos cuisses sur les épaules de Lineva et votre bouche contre celle d’Allenna. Les deux femmes maintiennent leurs gestes pendant les contractions, puis vous retiennent lorsque votre corps menace de glisser avec le dernier coussin.")],
        [N("Lineva remonte en riant doucement et embrasse votre ventre."), L("Tu avais bien posé tes jambes sur moi volontairement. Je le savais.", "soft")],
        [N("Allenna n’a pas fini de recevoir. Elle s’assied sur votre visage au milieu du canapé ; Lineva vient derrière elle, caresse ses seins et glisse deux doigts en elle pendant que votre langue retrouve sa perle. Allenna jouit une seconde fois, étouffant son cri dans la bouche de Lineva."), A("Nous ne changerons vraiment pas de meuble.", "shaken")],
        [N("La couverture tombe sur les trois corps nus. Les tasses et les vêtements restent hors de portée ; Lineva a votre cheville sur le ventre, Allenna la tête contre votre poitrine. Au lieu de ranger quoi que ce soit, vous décidez que le matin peut découvrir le salon exactement ainsi.")],
        [N("Au réveil, personne ne sait à qui appartient la jambe tombée du canapé. Allenna récupère les tasses pendant que Lineva vous retient sous la couverture ; le petit déjeuner commence finalement sur le tapis, sans démêler complètement le trio.")],
      ],
      ellipse: [
        [N("Trois tasses, deux places et aucune volonté de choisir le fauteuil : la soirée vous empile sur le canapé, les jambes mêlées avant même que la conversation s’épuise.")],
        [N("Un baiser accidentel rencontre la bouche de Lineva. Allenna en ajoute un second ; bientôt les trois lèvres se cherchent sans que personne ait annoncé la suite.")],
        [N("Les chemises s’ouvrent dans l’espace trop petit. Vous êtes à moitié sur Allenna, Lineva au bout de vos jambes, toutes trois reliées par des mains qui refusent de se retirer.")],
        [N("Lineva s’agenouille entre vos cuisses tandis qu’Allenna garde votre dos contre elle. La couverture glisse et le cadre commence à se refermer.")],
        [N("Le canapé grince lors d’un renversement : Lineva allongée, Allenna plus bas, vous contre son dos. Aucune chambre ne pourrait reproduire cet enchevêtrement.")],
        [N("Votre plaisir culmine après celui d’Allenna. Lineva reçoit ensuite le sien, accompagnée par vos deux corps malgré les coussins tombés.")],
        [N("Lineva retrouve votre bouche dans le calme."), L("Tu avais choisi la meilleure mauvaise place de ce canapé.", "soft")],
        [N("La couverture recouvre l’ensemble. Les tasses refroidissent sur la table et personne ne bouge avant le matin, sauf pour retrouver une main ou un baiser sous le tissu.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-home-femme-cuisine",
    text: "Cuisine après minuit — oublier le verre sur le comptoir",
    detail: "Un verre d’eau, une part de tarte et le réflexe de rangement d’Allenna conduisent à une scène spontanée où le comptoir décide des positions.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous étiez venue chercher de l’eau. Je préfère prévenir : Allenna est beaucoup plus difficile à reposer sur une étagère.", "smirk")],
      familiar: [L("Tu étais venue chercher de l’eau. Je préfère prévenir : Allenna est beaucoup plus difficile à reposer sur une étagère.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Après minuit, Allenna replace une assiette dans le placard tandis que vous remplissez un verre. Lineva entre pieds nus, lui enlève l’assiette des mains et la pose sur le comptoir."), L("Le rangement dormira très bien tout seul.", "soft")],
        [N("Il reste une part de tarte. Vous la partagez avec trois fourchettes, debout sous la petite lampe ; Allenna essuie une miette au coin de votre bouche et laisse son pouce y rester.")],
        [N("Vous embrassez ce pouce, puis Allenna. Lineva vient derrière elle et lui donne un second baiser sur la nuque ; la guerrière pose les mains à plat sur le comptoir.")],
        [N("Vous la faites asseoir sur le bois. Lineva prend place entre ses genoux, vous contre son côté ; les pieds nus d’Allenna se croisent dans votre dos.")],
        [N("Les baisers deviennent lents sous la faible lumière. Une main de Lineva se mêle à la vôtre sur le ventre d’Allenna, puis celle-ci vous rapproche toutes deux.")],
        [N("Le plaisir vous traverse debout contre le comptoir, prise entre leurs caresses. Le verre d’eau tremble près de votre coude sans tomber ; Allenna vous tient jusqu’au calme.")],
        [N("Lineva boit dans votre verre et vous le rend."), L("Tu étais vraiment venue pour ça. Je reconnais une remarquable prévoyance.", "soft")],
        [N("Allenna laisse enfin l’assiette sur place. Vous retournez ensemble vers la chambre, la dernière part terminée et les doigts encore entremêlés.")],
      ],
      suggestif: [
        [N("La cuisine n’est éclairée que par une petite lampe. Allenna range un bol ; Lineva le reprend aussitôt et le pose près de votre verre d’eau."), A("Il restait une seule chose."), L("Il en restera toujours une.", "smirk")],
        [N("Vous partagez une bouchée de tarte. Lineva recueille du bout des lèvres une miette sur la bouche d’Allenna ; vous embrassez l’autre coin avant qu’elle puisse rougir davantage.")],
        [N("Allenna s’assied sur le comptoir. Vous ouvrez sa chemise, Lineva sa jupe ; la lumière basse suit leurs mains lorsqu’elles font glisser vos propres vêtements.")],
        [N("Lineva se place entre les jambes d’Allenna. Vous restez derrière la guerrière, poitrine contre son dos ; sa bouche trouve la vôtre tandis que celle de Lineva descend hors cadre.")],
        [N("Vous inversez les places sans quitter la cuisine. Allenna vient entre vos cuisses sur le comptoir, Lineva vous embrasse depuis le côté et garde une main sur son amie.")],
        [N("Votre plaisir culmine assise sur le bois, un pied sur une chaise et l’autre autour d’Allenna. Lineva vous retient à la taille quand le verre menace de glisser.")],
        [N("Lineva repose le verre hors de portée."), L("Tu as failli renverser la seule chose que nous étions venues chercher.", "soft")],
        [N("Allenna oublie le bol et emporte seulement la part de tarte vers la chambre. Vous la suivez avec Lineva, encore serrées l’une contre l’autre dans le couloir.")],
      ],
      explicite: [
        [N("Vous trouvez Allenna dans la cuisine après minuit, occupée à ranger une assiette lavée. La petite lampe éclaire ses avant-bras et le verre d’eau que vous venez de remplir. Lineva apparaît derrière elle, prend l’assiette et la repose résolument sur le comptoir."), L("Le placard ne mérite pas autant d’attention.", "teasing")],
        [N("Il reste une part de tarte. Vous mangez dans la même assiette, trois fourchettes se heurtant au centre. Une miette reste sur la lèvre d’Allenna ; Lineva la cueille avec sa bouche. Allenna rougit, puis vous attire pour vous donner le même baiser sans miette comme excuse."), A("C’était plus équitable.", "smirk")],
        [N("Vous la soulevez sur le comptoir. Ses jambes s’ouvrent autour de vos hanches ; Lineva reste dans son dos et dégage ses cheveux. Vous ouvrez sa chemise, embrassez ses seins, tandis que Lineva retire sa jupe et caresse les fesses posées sur le bois."), P("Ne rangez plus rien cette nuit.")],
        [N("Allenna vous déshabille à son tour depuis sa place haute. Lineva embrasse votre poitrine, puis s’agenouille entre les jambes pendantes d’Allenna. La guerrière garde votre bouche sur la sienne pendant que la capitaine écarte ses lèvres et passe la langue sur sa perle."), A("Lineva… ne ralentis pas.", "breathless")],
        [N("Vous glissez deux doigts en Allenna par-dessus l’épaule de Lineva. Sa bouche gémit contre la vôtre ; Lineva maintient sa langue tandis que votre main se courbe profondément en elle. Allenna caresse votre sexe libre de l’autre main, dessinant un cercle sur votre perle sans perdre sa place sur le comptoir."), L("Elle sait très bien faire trois choses à la fois.", "smirk")],
        [N("Allenna jouit la première, assise au bord du bois, serrée entre votre main et la bouche de Lineva. Son talon frappe doucement le placard ; elle rit contre votre épaule quand le verre tremble. Lineva se relève pour l’embrasser et reçoit vos doigts entre ses propres cuisses."), A("Le verre tient encore.", "shaken")],
        [N("Vous asseyez Lineva sur le comptoir à la place d’Allenna. Cette dernière reste debout entre ses genoux et prend sa bouche ; vous vous agenouillez, léchez la perle de Lineva et glissez deux doigts en elle. Allenna caresse sa poitrine et guide son bassin vers votre langue."), L("Je retire mes critiques sur cette cuisine.", "breathless")],
        [N("Lineva jouit au-dessus de vous, ses doigts crispés dans les cheveux d’Allenna. Vous poursuivez pendant les contractions ; Allenna l’embrasse puis descend une main vers votre sexe. La capitaine reste assise et vous ouvre les jambes afin que son amie vous atteigne mieux."), A("À son tour.", "determined")],
        [N("Vous montez sur le comptoir, allongée sur le dos, les hanches au bord. Allenna s’agenouille entre vos jambes et entre deux doigts en vous ; Lineva se tient à votre tête, vous embrasse à l’envers et tend une main jusqu’à votre perle, son bras le long de votre ventre."), P("Gardez cette différence de hauteur.")],
        [N("Les doigts d’Allenna vous pénètrent depuis le sol tandis que ceux de Lineva frottent votre perle depuis le haut du comptoir. Votre orgasme vous cambre sur le bois ; Allenna retient vos hanches, Lineva votre visage, et le verre d’eau survit à quelques centimètres de votre main.")],
        [N("Lineva vous aide à vous redresser puis boit dans le verre."), L("Tu étais venue chercher de l’eau. Promesse tenue, si j’ose dire.", "soft")],
        [N("Allenna réclame encore le corps de Lineva. Elle la fait se pencher sur le comptoir ; vous entrez deux doigts en la capitaine par derrière tandis qu’Allenna, agenouillée, lèche sa perle. Lineva jouit une seconde fois, la joue près de l’assiette vide et le rire pris dans son souffle."), L("Cette part de tarte méritait vraiment le détour.", "shaken")],
        [N("Personne ne range la cuisine. Allenna emporte le verre, vous la tarte terminée et Lineva la couverture du canapé. Dans la chambre, les trois objets finissent oubliés à leur tour tandis que vous vous glissez ensemble sous les draps.")],
      ],
      ellipse: [
        [N("La faible lumière montre Allenna qui range encore une assiette. Lineva la lui retire ; vous posez votre verre d’eau à côté et partagez la dernière part de tarte.")],
        [N("Une miette sur la bouche d’Allenna devient un baiser de Lineva. Vous en ajoutez un sans prétexte et le comptoir reçoit les trois mains qui cherchent un appui.")],
        [N("Allenna s’assied sur le bois. Vous ouvrez sa chemise, Lineva sa jupe ; ses pieds nus se croisent derrière vos jambes pendant que les baisers descendent.")],
        [N("Lineva reste entre les genoux d’Allenna, vous contre son dos. La lumière laisse voir les trois corps puis se retire des gestes devenus plus précis.")],
        [N("Les places changent : Lineva assise sur le comptoir, Allenna devant elle, vous plus bas. Le meuble et la hauteur donnent à la route sa seconde forme.")],
        [N("Votre plaisir culmine allongée sur le bois après celui d’Allenna. Lineva reçoit ensuite le sien, le verre vibrant sans jamais tomber.")],
        [N("Lineva porte le verre à vos lèvres."), L("Tu n’oublieras plus pourquoi tu étais entrée dans cette cuisine.", "soft")],
        [N("L’assiette reste sur le comptoir. Vous regagnez la chambre avec Allenna et Lineva, la tarte finie et le rangement officiellement abandonné au matin.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-home-femme-chambre",
    text: "Chambre sans urgence — laisser durer le silence",
    detail: "Déjà allongées, elles n’ont aucune transition à forcer : un contact dure, devient caresse, puis la lenteur cède à une sexualité profonde et précise.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous n’avez rien à faire demain dans la prochaine heure. Moi non plus. C’est une excellente raison de rester exactement là.", "soft")],
      familiar: [L("Tu n’as rien à faire demain dans la prochaine heure. Moi non plus. C’est une excellente raison de rester exactement là.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous êtes déjà allongées, Allenna près du mur, Lineva au bord. Une conversation paresseuse s’éteint au milieu d’une phrase et personne ne cherche à la sauver.")],
        [N("Votre main repose sur le ventre d’Allenna. La sienne couvre vos doigts ; derrière vous, Lineva pose un genou contre vos jambes et laisse le contact durer.")],
        [N("Vous tournez la tête vers Lineva et l’embrassez. Allenna suit le mouvement, vous embrasse à son tour puis cherche la bouche de son amie au-dessus de votre épaule.")],
        [N("Les chemises remontent sous des paumes lentes. Allenna caresse votre dos, Lineva son flanc ; vous restez serrées sur le côté, sans raison de changer la simplicité de la position.")],
        [N("Allenna se glisse au centre. Vous l’enlacez par-devant, Lineva par-derrière ; ses mains reviennent sur vos deux corps avec une assurance née du calme.")],
        [N("Le plaisir vous traverse lentement sous les draps. Leurs caresses ne pressent rien ; votre frisson se termine avec la bouche d’Allenna sur votre front et la main de Lineva dans la vôtre.")],
        [N("Lineva murmure dans l’obscurité."), L("Tu peux prendre toute la nuit. Elle n’attend personne d’autre.", "soft")],
        [N("La couverture remonte jusqu’aux épaules. Allenna s’endort presque entre vous ; le petit déjeuner devient une idée lointaine dont personne ne règle encore l’heure.")],
      ],
      suggestif: [
        [N("Trois corps sont déjà allongés sous la couverture. La conversation s’épuise ; votre main reste sur la cuisse d’Allenna et celle de Lineva sur votre hanche.")],
        [N("Le silence devient un baiser donné à Lineva, puis un autre à Allenna. Elles se rejoignent au-dessus de vous et la couverture glisse jusqu’aux tailles.")],
        [N("Vous ouvrez la chemise d’Allenna sans quitter le lit. Lineva embrasse sa nuque et vous laisse sa propre poitrine à caresser dans la pénombre.")],
        [N("Allenna vient entre vos jambes ; Lineva reste couchée contre votre côté. Les mains descendent et les bouches suivent, toujours prises dans la lenteur du matelas.")],
        [N("Vous changez de côté. Lineva se place entre vos cuisses, Allenna derrière elle ; leurs attentions deviennent invisibles, leurs trois positions jamais.")],
        [N("Votre plaisir culmine sous la couverture, accompagné par leurs souffles plutôt que par le moindre bruit extérieur. Le lit reçoit les tremblements sans les hâter.")],
        [N("Lineva embrasse votre épaule."), L("Tu vois ? Personne n’avait besoin d’être ailleurs.", "soft")],
        [N("Allenna ramène la couverture et garde une jambe sur les vôtres. Vous vous endormez dans le même enchevêtrement, les tasses du matin encore inexistantes.")],
      ],
      explicite: [
        [N("Vous êtes déjà allongées sous la couverture, Allenna contre le mur, Lineva au bord, vous entre elles. La conversation s’efface sans malaise. Votre main est posée sur le ventre d’Allenna ; la paume de Lineva repose sur votre hanche depuis assez longtemps pour ne plus sembler distraite."), A("Je n’ai pas envie de dormir tout de suite.", "soft")],
        [N("Vous tournez la tête et embrassez Lineva. Le baiser commence paresseux, se creuse, puis Allenna se penche au-dessus de votre épaule pour prendre votre bouche à son tour. Lineva lui caresse la joue ; elles s’embrassent devant vous dans un silence où aucun geste n’a besoin d’être annoncé."), L("Alors restons éveillées.", "soft")],
        [N("Les chemises s’ouvrent sous les draps. Vous caressez la poitrine d’Allenna pendant que Lineva embrasse sa nuque depuis l’autre côté ; Allenna glisse une main sur vos seins et l’autre entre les cuisses de la capitaine. Les corps demeurent couchés sur le flanc, serrés en une ligne."), P("J’aime cette lenteur.")],
        [N("Allenna descend sous la couverture et vient entre vos jambes. Lineva reste contre votre côté, vous offre un sein à embrasser et tend sa main vers son amie. La bouche d’Allenna trouve votre sexe ; Lineva glisse deux doigts en elle par-dessus votre cuisse."), A("Gardez vos mains où elles sont.", "breathless")],
        [N("La langue d’Allenna suit votre perle avec de longs mouvements. Lineva entre et sort ses doigts en elle tandis que vous sucez sa poitrine et caressez son propre sexe. Le matelas absorbe chaque déplacement ; personne n’a à soutenir une posture ou à regarder l’heure."), L("Elle devient très appliquée quand elle oublie d’être gênée.", "breathless")],
        [N("Allenna jouit la première autour des doigts de Lineva, sa bouche quittant votre perle dans un gémissement contre votre cuisse. Elle reste allongée entre vos jambes ; vous caressez ses cheveux, Lineva son dos, jusqu’à ce qu’elle relève les yeux et reprenne exactement où elle s’était arrêtée."), A("Je n’avais pas fini.", "determined")],
        [N("Vous faites ensuite coucher Lineva sur le dos. Allenna s’allonge entre ses cuisses et lèche sa perle ; vous vous placez près de son visage, deux doigts en la capitaine et votre bouche sur la sienne. Lineva embrasse vos gémissements tandis que sa main caresse Allenna plus bas."), L("Cette nuit manque vraiment d’urgence.", "shaken")],
        [N("Lineva jouit sous la langue d’Allenna et vos doigts. Son ventre se tend contre le vôtre ; Allenna poursuit jusqu’au dernier frisson puis remonte partager avec elle un baiser lent. Vous restez au-dessus de leurs deux corps, une main sur chaque joue."), A("Il reste encore elle.", "soft")],
        [N("Elles vous ramènent sur le côté entre elles. Allenna entre deux doigts en vous depuis l’avant ; Lineva se serre derrière votre dos, frotte votre perle par-dessus votre hanche et embrasse votre nuque. Leurs rythmes se croisent sans se confondre, l’un profond, l’autre rapide."), P("Je suis tout près.")],
        [N("Votre orgasme vous replie autour de la main d’Allenna. Lineva garde la pression sur votre perle et vous retient contre sa poitrine ; leurs deux bouches se rejoignent près de votre épaule pendant qu’elles accompagnent chaque contraction, puis ralentissent avec votre souffle.")],
        [N("Lineva reste derrière vous et parle tout bas après le climax."), L("Tu avais raison de laisser le silence durer. Il nous a menées exactement ici.", "soft")],
        [N("Vous n’arrêtez pas aussitôt. Allenna s’allonge face à Lineva ; leurs cuisses s’entrelacent et leurs sexes frottent l’un contre l’autre. Vous restez entre leurs torses, un doigt sur chaque perle, jusqu’à ce qu’Allenna puis Lineva jouissent à quelques secondes d’écart en s’embrassant."), A("Maintenant, je peux dormir.", "shaken")],
        [N("La couverture revient sur les trois corps. Personne ne se lève pour l’eau ; Lineva trouve le verre posé près du lit et le fait circuler. Allenna s’endort au milieu, votre main sur son ventre, la sienne sur Lineva. Le matin attendra que vous ayez envie de petit-déjeuner.")],
      ],
      ellipse: [
        [N("Déjà allongées, vous laissez la conversation mourir sans remplir son silence. Une main d’Allenna reste sur la vôtre ; le genou de Lineva demeure contre vos jambes.")],
        [N("Vous embrassez Lineva, puis Allenna. Les deux femmes se rejoignent au-dessus de votre épaule et la couverture glisse lentement vers vos tailles.")],
        [N("Les chemises s’ouvrent sans que personne quitte le lit. Vous restez sur le côté, Allenna devant vous, Lineva derrière, les caresses allant et revenant dans la même ligne.")],
        [N("Allenna descend entre vos jambes tandis que Lineva demeure à votre flanc. La pénombre masque les gestes, pas les mains qui relient leurs deux corps au vôtre.")],
        [N("Lineva prend ensuite la place au centre ; Allenna se couche plus bas, vous près du visage de la capitaine. Le matelas accueille chaque changement sans rupture.")],
        [N("Votre plaisir culmine le dernier après celui des deux femmes. Rien n’est simultané ni pressé ; la nuit demeure ouverte autour de vos respirations.")],
        [N("Lineva murmure lorsque le calme revient."), L("Tu peux laisser demain attendre encore un peu.", "soft")],
        [N("La couverture recouvre trois corps restés dans la même chaleur. Allenna s’endort entre vous et le petit déjeuner ne devient une question qu’avec la lumière du matin.")],
      ],
    },
  },
];

const HOME_HOMME: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-home-homme-canape",
    text: "Canapé trop petit — accueillir Allenna sur vos cuisses",
    detail: "Les jambes entremêlées et un baiser imprévu font glisser une soirée banale vers une sexualité qui exploite chaque centimètre du canapé.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous êtes officiellement le dernier espace libre de ce canapé. Je vous conseille de ne pas respirer trop largement.", "smirk")],
      familiar: [L("Tu es officiellement le dernier espace libre de ce canapé. Je te conseille de ne pas respirer trop largement.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Lineva occupe le dossier et la moitié des coussins. Allenna s’assied dans le seul coin libre ; vous vous glissez entre elles et recevez immédiatement deux paires de jambes sur les vôtres."), L("Parfaitement spacieux.", "pleased")],
        [N("La conversation dérive. Allenna pose la tête sur votre épaule ; les pieds de Lineva trouvent vos cuisses, puis sa main votre ventre sous prétexte de chercher la couverture.")],
        [N("Vous tournez le visage et embrassez Allenna sans l’avoir prévu. Lineva ajoute un baiser sur votre joue ; vous la ramenez par la nuque avant que l’instant ne puisse redevenir banal.")],
        [N("Les trois bouches se cherchent au-dessus des jambes emmêlées. Allenna embrasse Lineva, puis revient vers vous tandis que votre main demeure chaude sur la taille de chacune.")],
        [N("Vous vous retrouvez couché, Allenna à moitié sur votre poitrine, Lineva serrée contre votre flanc. Le canapé interdit la moindre distance et ralentit chaque caresse.")],
        [N("Le plaisir se détend sous leurs mains, doux mais entier. Allenna vous retient entre ses bras ; Lineva garde ses lèvres contre votre tempe jusqu’à ce que le frisson passe.")],
        [N("Lineva tire la couverture sur votre ventre."), L("Tu n’étais pas une place assise. Tu étais le meilleur coussin.", "soft")],
        [N("Les tasses restent sur la table. Allenna ne quitte pas votre poitrine, Lineva garde une jambe sur les vôtres et le sommeil arrive sans que personne ait éteint la petite lampe.")],
      ],
      suggestif: [
        [N("Vous vous installez entre Allenna et Lineva sur le canapé. Les jambes se superposent, les épaules se coincent et la soirée continue comme si ce contact permanent était parfaitement ordinaire.")],
        [N("Un mouvement d’Allenna presse sa hanche contre votre désir naissant. Elle s’immobilise, rougit, puis vous embrasse au lieu de s’écarter. Lineva sourit contre votre cou.")],
        [N("Les chemises s’ouvrent sous la couverture. Vous caressez la poitrine d’Allenna pendant que Lineva embrasse son épaule et laisse sa propre peau se découvrir contre votre flanc.")],
        [N("Allenna vient à califourchon sur vos cuisses, Lineva derrière elle malgré le dossier. Leurs bouches se rejoignent tandis que leurs mains descendent hors du champ.")],
        [N("Vous inversez les places : Lineva allongée sur le canapé, Allenna près de ses jambes, vous contre son côté. Le meuble grince et le cadre se resserre.")],
        [N("Votre plaisir culmine sous Allenna, accompagné par la main de Lineva et leurs deux regards. Un coussin tombe ; personne ne fait mine de le ramasser.")],
        [N("Lineva embrasse le coin de votre bouche."), L("Tu viens de confirmer que trois personnes tiennent très bien ici.", "soft")],
        [N("Allenna ramène la couverture et s’endort presque sur vous. Les tasses refroidissent ; le canapé garde trois corps emmêlés jusqu’au matin.")],
      ],
      explicite: [
        [N("Lineva est étendue en diagonale sur le canapé, un pied posé sur les genoux d’Allenna. Vous prenez le milieu, recevez les jambes de l’une et l’épaule de l’autre, puis continuez une conversation qui ne mène nulle part. La théière refroidit entre deux phrases."), A("Si quelqu’un bouge, tout s’effondre.", "soft")],
        [N("Allenna se retourne pour répondre et sa bouche rencontre la vôtre. Le contact pourrait n’être qu’une maladresse ; elle revient pourtant l’embrasser, plus lentement. Lineva se redresse derrière votre épaule, pose un baiser sur votre nuque puis attire Allenna pour goûter à son tour ses lèvres."), L("Voilà une bien meilleure conversation.", "smirk")],
        [N("Sous la couverture, votre main ouvre la chemise d’Allenna. Lineva prend ses seins depuis l’arrière pendant que vous en embrassez un ; Allenna défait votre pantalon et libère votre sexe déjà dur entre ses cuisses. Sa rougeur s’accompagne d’un mouvement volontaire de ses hanches."), A("Le canapé nous a vraiment trop rapprochés.", "breathless")],
        [N("Elle vient à califourchon sur vous, genoux coincés entre votre corps et le dossier. Lineva reste derrière elle, mord sa nuque et glisse deux doigts entre ses cuisses. Allenna referme une main sur votre sexe et le caresse contre son ventre tandis que vous embrassez sa poitrine."), P("Ne cherchez pas plus de place.")],
        [N("Allenna descend du canapé et s’agenouille devant vous. Elle prend votre sexe dans sa bouche ; Lineva s’allonge sur vos jambes, tournée vers elle, et glisse deux doigts en Allenna pendant que vous caressez la poitrine de la capitaine. Les trois corps remplissent toute la longueur du meuble."), L("Je crois que nous avons encore perdu un coussin.", "breathless")],
        [N("La bouche d’Allenna va et vient jusqu’à la base. Lineva l’embrasse à chaque retrait puis frotte sa perle du pouce ; Allenna gémit autour de votre sexe et accélère. Vous retenez les cheveux des deux femmes, les gardant à portée sans céder encore au plaisir."), P("Pas tout de suite. Venez ici.")],
        [N("Vous tirez Lineva sur le dos. Allenna s’allonge entre ses cuisses et lèche sa perle ; vous vous placez à genoux sur le bord du canapé, deux doigts en Lineva et votre bouche sur celle d’Allenna lorsqu’elle se tourne. Lineva jouit la première, les talons pressés contre votre dos."), L("Le canapé avait donc encore cette position.", "shaken")],
        [N("Allenna revient sur vos cuisses. Lineva, encore haletante, guide votre sexe jusqu’à l’entrée humide de son amie. Allenna descend lentement, vous accueille profondément puis commence à vous chevaucher dans le peu d’amplitude laissé par le dossier. Lineva caresse sa perle entre vos bassins."), A("Cette place suffit.", "determined")],
        [N("Les mouvements courts rendent chaque pénétration plus serrée. Allenna jouit autour de vous sous les doigts de Lineva, son torse collé au vôtre ; la capitaine l’embrasse par-dessus votre épaule et continue la caresse tandis qu’Allenna reste assise, encore contractée autour de votre sexe."), L("Elle ne va pas se lever. Tant mieux.", "smirk")],
        [N("Allenna reprend lentement ses mouvements uniquement pour vous. Lineva referme sa main autour de la base de votre sexe à chaque remontée ; vous jouissez en Allenna après son climax, la serrant contre votre poitrine tandis que les trois corps font grincer le canapé une dernière fois."), P("Je reste là… ne bougez plus.")],
        [N("Lineva embrasse votre joue au-dessus de l’épaule d’Allenna."), L("Tu avais effectivement choisi la meilleure place. Je reconnais mon erreur.", "soft")],
        [N("Allenna se retire et s’allonge en travers de vous. Lineva vient entre ses jambes, la lèche, pendant que vous entrez deux doigts en la capitaine depuis l’autre côté et embrassez Allenna. Son second orgasme se perd dans vos bouches, le canapé entièrement occupé jusqu’aux accoudoirs."), A("Je refuse désormais le fauteuil.", "shaken")],
        [N("La couverture recouvre les trois corps nus. Vos vêtements, les coussins et les tasses sont hors de portée ; personne n’y voit une raison suffisante pour se lever. Allenna reste sur votre poitrine, Lineva sur vos jambes, et le matin trouve le salon exactement ainsi.")],
      ],
      ellipse: [
        [N("Trois personnes s’entassent sur un canapé trop petit. Les jambes se mélangent, Allenna se retrouve sur votre épaule et Lineva presque en travers de vos cuisses.")],
        [N("Un baiser imprévu vous lie à Allenna. Lineva rejoint votre nuque, puis la bouche de son amie ; la soirée ordinaire glisse sans annonce vers autre chose.")],
        [N("Les chemises s’ouvrent sous la couverture. Votre désir devient visible entre leurs hanches, et Allenna choisit de rester contre vous plutôt que de reprendre sa place.")],
        [N("Elle vient à califourchon, Lineva derrière elle. Les mains descendent hors cadre tandis que le dossier maintient les trois corps serrés.")],
        [N("Un renversement place Lineva sur le dos et Allenna plus bas, vous au bord du meuble. Le canapé grince lorsque la chronique se retire.")],
        [N("Votre plaisir culmine après celui d’Allenna. Lineva reçoit le dernier, accompagnée par vous deux malgré l’espace et les coussins tombés.")],
        [N("Lineva pose sa joue sur votre épaule."), L("Tu vois ? Nous n’avions besoin d’aucune place supplémentaire.", "soft")],
        [N("La couverture rassemble ce qui dépasse encore du canapé. Les tasses et les vêtements attendent le jour ; trois corps choisissent le sommeil sans se démêler.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-home-homme-cuisine",
    text: "Cuisine après minuit — soulever Allenna sur le comptoir",
    detail: "La part de tarte et le verre d’eau sont vite oubliés ; le comptoir permet une scène spontanée, verticale et plus vive que la chambre.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous vouliez seulement boire. Allenna voulait seulement ranger. Je crois que nous sommes tous les trois d’excellents menteurs.", "smirk")],
      familiar: [L("Tu voulais seulement boire. Allenna voulait seulement ranger. Je crois que nous sommes tous les trois d’excellents menteurs.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Allenna replace un bol après minuit. Vous remplissez un verre ; Lineva arrive pieds nus, prend le bol et le repose sur le comptoir avec une satisfaction tranquille."), L("Il sera encore là demain.", "soft")],
        [N("La dernière part de tarte se partage à la fourchette. Allenna essuie une miette sur votre lèvre ; vous embrassez son pouce et Lineva vient cueillir le sourire qui suit.")],
        [N("Vous embrassez Allenna sous la petite lampe. Lineva reste derrière elle, bras autour de sa taille, et pose sa joue contre votre épaule.")],
        [N("Allenna s’assied sur le comptoir ; vous prenez place entre ses genoux. Lineva se tient à son côté et vos mains se rencontrent sur les jambes pendantes.")],
        [N("Le bois tiède, les pieds nus et la faible lumière rendent les caresses domestiques et lentes. Le verre demeure près de votre coude, oublié sans danger.")],
        [N("Votre plaisir se détend debout contre le comptoir. Allenna vous enlace par les épaules ; Lineva retient vos hanches jusqu’à ce que le frisson s’apaise.")],
        [N("Lineva vous tend enfin l’eau."), L("Tu peux au moins prétendre que le voyage jusqu’à la cuisine était nécessaire.", "soft")],
        [N("Allenna laisse le bol où il est. Vous retournez vers la chambre avec la même assiette et trois mains jointes, le rangement remis à une matinée sans heure précise.")],
      ],
      suggestif: [
        [N("La cuisine est presque noire. Allenna range un bol ; Lineva l’intercepte tandis que vous posez un verre d’eau près de la dernière part de tarte.")],
        [N("Vous partagez trois bouchées. Une miette sur les lèvres d’Allenna devient un baiser de Lineva ; la vôtre rejoint les leurs avant que la fourchette retombe.")],
        [N("Vous soulevez Allenna sur le comptoir. Ses jambes se referment autour de vos hanches ; Lineva se place derrière elle et ouvre lentement sa chemise.")],
        [N("Allenna défait votre ceinture tandis que vous embrassez sa poitrine. Lineva descend près de vos corps et ses mains quittent le cadre sans quitter Allenna.")],
        [N("Vous échangez les places : Lineva assise, Allenna devant elle, vous contre le comptoir. La faible lumière dessine encore les trois silhouettes.")],
        [N("Votre plaisir culmine entre elles, debout, le verre vibrant contre le bois. Allenna vous tient au cou ; Lineva garde une main sur sa cuisse.")],
        [N("Lineva boit une gorgée puis vous tend le verre."), L("Tu allais vraiment oublier l’eau après tout ça.", "soft")],
        [N("Allenna emporte l’assiette vide, puis la repose dans le couloir en riant. Vous atteignez la chambre sans aucun objet utile et sans regret.")],
      ],
      explicite: [
        [N("La cuisine n’a gardé qu’une petite lampe allumée. Vous remplissez un verre pendant qu’Allenna range un bol propre. Lineva arrive pieds nus, prend le bol de ses mains et le pose près de la dernière part de tarte."), L("Demain saura très bien où le trouver.", "teasing")],
        [N("Vous mangez tous dans la même assiette. Lineva retire une miette de la bouche d’Allenna avec ses lèvres ; la guerrière rougit, puis vous embrasse sans chercher de prétexte. Vos mains se rejoignent à sa taille et la soulèvent presque ensemble sur le comptoir."), A("Je pouvais monter seule."), P("Mais nous avions envie de vous porter.")],
        [N("Assise sur le bois, Allenna ouvre les jambes autour de vous. Lineva se place dans son dos, retire sa chemise et prend ses seins ; vous embrassez son ventre puis sa poitrine. Allenna laisse une main dans vos cheveux et l’autre entre les cuisses de Lineva, debout contre son flanc."), L("Elle ne range déjà plus rien.", "smirk")],
        [N("Allenna défait votre pantalon et prend votre sexe en main. Lineva l’embrasse par-dessus son épaule, puis s’agenouille entre vos deux corps. Sa bouche se pose sur la perle d’Allenna tandis que vous restez debout, votre sexe frotté par la main de la guerrière contre votre ventre."), A("Plus près, tous les deux.", "breathless")],
        [N("Vous entrez deux doigts en Allenna depuis le côté pendant que Lineva la lèche. Allenna continue de vous masturber, sa cadence troublée par les mouvements de la langue. Vous embrassez Lineva lorsqu’elle relève brièvement le visage, puis la ramenez entre les cuisses ouvertes sur le comptoir."), P("Ne la laissez pas s’échapper.")],
        [N("Allenna jouit la première, ses talons frappant les portes basses. Votre main reste en elle ; Lineva garde sa bouche sur sa perle jusqu’au dernier spasme. La guerrière se penche ensuite pour l’embrasser, puis vous regarde comme si sa rougeur ne comptait plus."), A("Lineva sur le comptoir. Maintenant.", "determined")],
        [N("Vous soulevez Lineva à la place d’Allenna. Cette dernière s’agenouille entre ses cuisses et la lèche ; vous vous tenez derrière la capitaine, deux doigts en elle et votre sexe contre son dos. Lineva s’agrippe à votre avant-bras et caresse les cheveux d’Allenna."), L("Elle devient autoritaire après minuit.", "shaken")],
        [N("Lineva jouit sous la bouche d’Allenna et vos doigts, la joue contre la vôtre. Allenna se relève, encore souriante, et guide votre sexe à l’entrée de la capitaine. Lineva s’avance au bord du comptoir ; vous la pénétrez debout pendant qu’Allenna frotte sa perle."), L("Oui… cet angle.", "breathless")],
        [N("Votre bassin vient contre les cuisses de Lineva suspendues au bois. Allenna l’embrasse et maintient ses doigts entre vos corps ; la capitaine jouit une seconde fois autour de vous, puis reste ouverte et frémissante tandis que vous ralentissez pour ne pas confondre son plaisir avec le vôtre.")],
        [N("Vous reprenez ensuite des poussées profondes. Allenna referme une main autour de la base de votre sexe à chaque retrait ; vous jouissez en Lineva après ses deux orgasmes, courbé sur son dos, tandis que leurs bouches restent réunies dans la lumière basse."), P("Le verre va tomber.")],
        [N("Lineva retient le verre du bout des doigts et vous le tend une fois votre souffle revenu."), L("Tu étais venu le chercher. Il serait dommage de repartir sans.", "soft")],
        [N("Allenna s’allonge à son tour sur le comptoir, hanches au bord. Vous glissez deux doigts en elle pendant que Lineva lèche sa perle et lui offre sa bouche entre deux mouvements. Son second orgasme fait vibrer l’assiette vide, que personne ne songe encore à ranger."), A("Le bol attendra vraiment demain.", "shaken")],
        [N("Vous gagnez la chambre avec le verre, la couverture et aucune assiette. Allenna s’arrête dans le couloir pour rire contre Lineva ; vous les entourez toutes deux et laissez la cuisine exactement comme elle est jusqu’au petit matin.")],
        [N("Le lendemain, vous retrouvez ensemble le bol, le verre et l’assiette sous la même petite lampe. Lineva sert la tarte qui n’existe plus ; Allenna répond avec du pain frais et un baiser avant de ranger quoi que ce soit.")],
      ],
      ellipse: [
        [N("Après minuit, Allenna range encore un bol. Lineva le reprend, vous posez votre verre près de la tarte et la petite lampe enferme la cuisine dans une lumière douce.")],
        [N("Une miette devient un baiser entre les deux femmes. Vous les rejoignez ; la fourchette retombe tandis que trois mains se cherchent autour de la taille d’Allenna.")],
        [N("Vous la soulevez sur le comptoir. Lineva ouvre sa chemise par-derrière, vous restez entre ses jambes et les pieds nus d’Allenna se croisent contre votre dos.")],
        [N("Votre désir devient visible quand Allenna défait votre ceinture. Lineva descend entre vos deux corps et le cadre suit seulement les réactions sur leurs visages.")],
        [N("Les places changent : Lineva assise, Allenna devant elle, vous derrière. Le comptoir impose la hauteur et la rapidité de la suite.")],
        [N("Votre plaisir culmine après celui de Lineva. Allenna reçoit ensuite le dernier, allongée sur le bois tandis que vous restez tous deux près d’elle.")],
        [N("Lineva vous tend le verre intact."), L("Tu as donc obtenu exactement ce que tu étais venu chercher. Entre autres.", "soft")],
        [N("Le bol et l’assiette demeurent sur le comptoir. Vous retournez vers la chambre avec Allenna et Lineva, la cuisine abandonnée à la lumière du matin.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-home-homme-chambre",
    text: "Chambre sans urgence — laisser Allenna et Lineva choisir le temps",
    detail: "Déjà couchés, vous passez d’un silence confortable à une sexualité lente puis intense, sans quitter la proximité du lit ni presser aucun climax.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez rester au milieu. Il n’existe aucune bonne raison de quitter ce lit dans les prochaines heures.", "soft")],
      familiar: [L("Tu peux rester au milieu. Il n’existe aucune bonne raison de quitter ce lit dans les prochaines heures.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous êtes déjà couché entre elles. La conversation se tait sans malaise ; Allenna garde une main sur votre poitrine, Lineva un genou contre votre jambe.")],
        [N("Le contact dure. Vous couvrez la main d’Allenna, puis trouvez celle de Lineva derrière vous et réunissez les trois sur votre ventre.")],
        [N("Vous embrassez Allenna dans la pénombre. Lineva rejoint votre nuque, puis la bouche de son amie lorsque vous vous effacez juste assez.")],
        [N("Les chemises s’ouvrent sous des paumes lentes. Allenna reste contre votre torse ; Lineva contre son dos, et le matelas accueille leurs corps sans les séparer.")],
        [N("Allenna passe au milieu. Vous l’enlacez face à face, Lineva depuis l’arrière ; les caresses suivent le rythme tranquille de vos respirations.")],
        [N("Le plaisir vous gagne sans hâte entre leurs mains. Votre corps se tend, puis se relâche avec Allenna contre votre bouche et Lineva près de votre cœur.")],
        [N("Lineva murmure lorsque vous ouvrez les yeux."), L("Tu peux laisser la nuit continuer sans toi une minute. Nous restons là.", "soft")],
        [N("La couverture remonte. Allenna s’endort sur votre épaule ; Lineva garde une main sur votre ventre et le petit déjeuner attend encore de devenir une idée.")],
      ],
      suggestif: [
        [N("Allenna est couchée contre le mur, vous au milieu, Lineva au bord. Une phrase s’interrompt ; le silence devient confortable et la main de Lineva reste sur votre cuisse.")],
        [N("Vous l’embrassez par-dessus votre épaule. Allenna vient chercher votre bouche de l’autre côté ; les deux femmes se rejoignent ensuite au-dessus de votre poitrine.")],
        [N("Les vêtements s’ouvrent sans que personne se lève. Vous caressez Allenna sous la couverture, Lineva contre votre dos ; leurs mains descendent à leur tour.")],
        [N("Allenna vient à califourchon sur vos cuisses. Lineva reste couchée près d’elle, embrasse sa poitrine et garde votre main dans la sienne.")],
        [N("Les positions tournent lentement sur le matelas. Lineva entre vos jambes, Allenna près de votre bouche, et le cadre s’arrête avant les gestes les plus précis.")],
        [N("Votre plaisir culmine sous la couverture après celui d’Allenna. Lineva reste contre vos jambes ; la nuit absorbe les souffles et le mouvement du lit.")],
        [N("Lineva embrasse votre tempe."), L("Tu n’as aucune raison de compter les heures maintenant.", "soft")],
        [N("Allenna se glisse entre vous et ramène la couverture. Vous vous endormez à trois, les corps encore liés et le lendemain laissé hors de la chambre.")],
      ],
      explicite: [
        [N("Vous êtes déjà couché entre Allenna et Lineva. La lampe est basse, la couverture chaude, la conversation achevée sans conclusion. Une main d’Allenna repose sur votre poitrine ; le genou de Lineva touche votre cuisse depuis plusieurs minutes. Personne n’a besoin de trouver un prétexte."), A("Je n’ai pas sommeil.", "soft")],
        [N("Vous embrassez Allenna. Sa bouche s’ouvre lentement sous la vôtre ; Lineva se rapproche dans votre dos, embrasse votre nuque puis attire Allenna au-dessus de votre épaule. Vous regardez leurs lèvres se joindre avant de reprendre chacune à votre tour."), L("Moi non plus.", "soft")],
        [N("Les chemises s’ouvrent sous la couverture. Vous prenez les seins d’Allenna dans vos mains tandis que Lineva mord doucement son épaule et caresse votre ventre. Allenna descend jusqu’à votre pantalon, libère votre sexe dur et le garde contre sa paume sans presser la suite."), P("Nous avons toute la nuit.")],
        [N("Allenna glisse entre vos jambes et prend votre sexe dans sa bouche. Lineva reste couchée contre votre côté, vous embrasse et tend une main vers son amie ; deux de ses doigts entrent en Allenna, dont le gémissement entoure votre membre. Vous caressez la poitrine de Lineva."), A("Ne la retirez pas.", "breathless")],
        [N("La bouche d’Allenna descend lentement, puis remonte en faisant jouer sa langue autour du gland. Lineva poursuit ses doigts en elle tout en vous offrant sa poitrine à embrasser. Allenna tend une main vers le sexe de la capitaine et la caresse pendant qu’elle vous suce."), L("Elle refuse décidément de choisir une seule personne.", "breathless")],
        [N("Vous arrêtez Allenna avant votre climax et la ramenez sur le matelas. Lineva s’allonge sur le dos ; Allenna vient entre ses cuisses et lèche sa perle. Vous vous placez derrière Allenna, deux doigts en elle et votre bouche sur son dos, pendant que Lineva caresse votre sexe."), A("Restez tous les deux près de moi.", "determined")],
        [N("Lineva jouit la première sous la langue d’Allenna. Ses doigts se crispent autour de votre sexe puis reprennent plus doucement ; vous maintenez la pénétration de vos doigts en Allenna, qui remonte ensuite embrasser son amie sans que le cercle se défasse."), L("Nous avions vraiment toute la nuit.", "shaken")],
        [N("Allenna s’allonge sur le dos et ouvre les jambes. Vous guidez votre sexe à son entrée puis la pénétrez lentement, couché entre ses cuisses. Lineva reste sur le côté, embrasse Allenna et frotte sa perle du bout des doigts pendant que vos poussées deviennent plus profondes."), A("Plus lentement… je veux tout sentir.", "breathless")],
        [N("Allenna jouit sous vous, ses jambes resserrées autour de vos hanches. Lineva maintient sa caresse pendant les contractions et recueille son cri dans un baiser. Vous restez immobile en elle jusqu’à ce qu’elle vous demande d’avancer encore, cette fois pour votre plaisir."), A("Continuez. Je vous garde en moi.", "shaken")],
        [N("Vous reprenez des poussées longues, Lineva embrassant vos deux visages et refermant sa main autour de la base de votre sexe à chaque retrait. Votre orgasme arrive après celui d’Allenna, profondément en elle ; les deux femmes vous entourent pendant que votre corps pulse puis se relâche."), P("Je ne veux plus bouger.")],
        [N("Lineva se serre contre votre dos après le climax."), L("Tu n’as pas à bouger. C’était précisément l’idée.", "soft")],
        [N("Allenna se retire lentement et s’allonge face à Lineva. Vous passez entre leurs jambes, léchez la perle de la capitaine et entrez deux doigts en elle tandis qu’Allenna l’embrasse et caresse sa poitrine. Lineva jouit une seconde fois, plus silencieusement, dans leurs mains réunies."), L("Maintenant, je peux dormir.", "shaken")],
        [N("Vous partagez le verre posé près du lit et remontez la couverture. Allenna s’installe au milieu, une jambe sur les vôtres ; Lineva garde sa main sur votre ventre. Le petit déjeuner du lendemain reste sans heure, sans menu et sans personne désignée pour se lever.")],
      ],
      ellipse: [
        [N("Déjà couchés, vous laissez une conversation mourir paisiblement. Allenna garde sa main sur votre poitrine ; Lineva son genou contre votre jambe.")],
        [N("Vous embrassez Allenna, puis Lineva. Elles se rejoignent au-dessus de vous et la couverture glisse jusqu’aux hanches sans que personne quitte le matelas.")],
        [N("Les vêtements s’ouvrent dans la pénombre. Votre désir devient visible sous la main d’Allenna tandis que Lineva reste collée à votre dos.")],
        [N("Allenna vient entre vos jambes, Lineva contre votre côté. Les mains relient les trois corps avant que le cadre ne laisse la nuit garder les gestes.")],
        [N("Les places changent avec lenteur : Lineva allongée, Allenna plus bas, vous derrière elle ; puis Allenna au centre de vos deux corps.")],
        [N("Votre plaisir culmine après celui d’Allenna. Lineva reçoit le dernier, accompagnée par vous deux, sans que le lit impose la moindre hâte.")],
        [N("Lineva murmure dans le calme."), L("Tu peux laisser demain attendre de l’autre côté de la porte.", "soft")],
        [N("La couverture revient sur trois corps enlacés. Le verre circule une fois, puis le sommeil vous garde ensemble jusqu’à la lumière du matin.")],
      ],
    },
  },
];
const HOME_INTERSEXE: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-home-intersexe-canape",
    text: "Canapé trop petit — faire de votre corps la place commune",
    detail: "La proximité née du meuble permet à Allenna et Lineva de découvrir vos plaisirs sans supposition, au fil d’une soirée qui glisse naturellement.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous êtes la seule place encore disponible. Heureusement, votre corps offre plusieurs façons de nous installer près de lui.", "smirk")],
      familiar: [L("Tu es la seule place encore disponible. Heureusement, ton corps offre plusieurs façons de nous installer près de lui.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous vous asseyez dans le dernier espace du canapé. Allenna s’appuie contre votre épaule, Lineva étend ses jambes sur les vôtres et les trois tasses demeurent sur la table.")],
        [N("La conversation devient lente. Vous montrez à Allenna une façon confortable de vous tenir ; Lineva ajoute sa main à la sienne sur votre ventre.")],
        [N("Un baiser naît avec Lineva lorsque vous tournez la tête. Allenna en pose un autre sur votre bouche puis embrasse son amie au-dessus de votre poitrine.")],
        [N("Les corps glissent sans se lever. Allenna se retrouve à moitié sur vous, Lineva serrée contre votre flanc et les jambes impossibles à attribuer.")],
        [N("Leurs caresses suivent ce que vous leur montrez sous la couverture. Chacune continue de toucher l’autre, gardant la proximité entière.")],
        [N("Votre plaisir se dénoue au creux du canapé. Allenna vous tient par la taille ; Lineva garde vos doigts contre ses lèvres jusqu’au dernier frisson.")],
        [N("Lineva sourit après le sommet."), L("Tu étais vraiment la meilleure place de la pièce.", "soft")],
        [N("La couverture rassemble trois corps et les tasses refroidissent. Personne ne cherche une posture plus logique avant que le sommeil ne gagne le salon.")],
      ],
      suggestif: [
        [N("Le canapé oblige vos jambes à se mêler. Allenna se cale contre votre épaule ; Lineva garde les pieds sur vos cuisses et la conversation oublie son sujet.")],
        [N("Vous guidez une main vers une zone sensible de votre corps. Allenna suit ; Lineva embrasse sa nuque et ajoute une caresse différente sans la remplacer.")],
        [N("Les chemises s’ouvrent sous la couverture. Vous embrassez Lineva tandis qu’Allenna découvre votre peau et se laisse découvrir à son tour.")],
        [N("Vous vous retrouvez allongé, Allenna sur votre hanche et Lineva entre vos jambes. Les trois positions restent compactes et lisibles malgré les coussins.")],
        [N("Les gestes quittent le cadre, jamais le contact entre les deux femmes. Allenna embrasse Lineva au-dessus de vous pendant que leurs mains suivent vos indications.")],
        [N("Votre plaisir culmine sous leurs deux attentions. Le canapé grince, un coussin tombe et leurs corps vous retiennent dans l’espace libéré.")],
        [N("Lineva ramasse le coussin du bout du pied."), L("Tu viens encore d’agrandir ce canapé d’une manière très personnelle.", "soft")],
        [N("Allenna tire la couverture sur vous trois. Les tasses attendent ; le salon demeure la seule chambre dont personne n’a besoin.")],
      ],
      explicite: [
        [N("Vous prenez le dernier espace du canapé entre Allenna et Lineva. La conversation continue autour de rien ; les jambes se mêlent et la main de la capitaine reste sur votre hanche. Vous leur montrez sous la couverture les parties de votre corps qui répondent déjà à cette proximité."), P("Pas besoin de mieux nous installer.")],
        [N("Lineva vous embrasse quand vous tournez la tête. Allenna regarde, rouge et souriante, puis prend votre bouche à son tour. Les deux femmes se rejoignent au-dessus de votre poitrine tandis que vous placez une main de chacune sur un plaisir différent de votre corps."), A("Nous pouvons apprendre ici.", "soft")],
        [N("Les vêtements s’ouvrent sans que personne ne se lève. Allenna caresse votre sexe extérieur ; Lineva glisse deux doigts dans l’ouverture que vous lui avez montrée. Vous prenez leurs seins dans vos mains et les regardez s’embrasser, serrées contre votre flanc par le dossier."), L("Le canapé nous garde honnêtes.", "breathless")],
        [N("Vous faites allonger Lineva en travers des coussins. Allenna vient entre ses cuisses et lèche sa perle ; vous restez près de leurs visages, deux doigts en la capitaine et votre bouche sur celle d’Allenna à chaque fois qu’elle se relève."), L("Je retire toute plainte sur le manque de place.", "shaken")],
        [N("Lineva jouit la première sous la langue d’Allenna et vos doigts. Ses jambes se referment contre le dossier ; vous maintenez la caresse pendant qu’Allenna l’embrasse. La guerrière vous ramène ensuite au centre en tirant doucement sur vos hanches."), A("À vous maintenant.", "determined")],
        [N("Allenna s’allonge contre votre poitrine, tournée vers vos jambes. Elle prend votre désir extérieur dans sa bouche pendant que Lineva, agenouillée au bout du canapé, entre deux doigts dans votre ouverture. Leurs visages se rejoignent près de votre bassin à chaque changement de rythme."), P("Restez ensemble.")],
        [N("Vous caressez Allenna entre les cuisses pendant qu’elle vous donne sa bouche. Lineva embrasse la nuque d’Allenna et poursuit ses doigts en vous ; la guerrière gémit autour de votre sexe sans perdre le mouvement de ses lèvres.")],
        [N("Vous les arrêtez avant votre climax et asseyez Allenna sur votre visage, ses genoux de part et d’autre de votre tête. Lineva vient derrière elle, entre deux doigts en son sexe et caresse ses seins pendant que votre langue retrouve sa perle."), A("Ne vous arrêtez plus maintenant.", "breathless")],
        [N("Allenna jouit au-dessus de vous, mordant la bouche de Lineva. Elle reste une seconde à reprendre souffle, puis se recouche contre votre torse et reprend votre sexe extérieur avec sa main tandis que Lineva retourne ses doigts dans votre ouverture."), L("Nous finissons ce que nous avons commencé.", "determined")],
        [N("Votre orgasme vient sous leurs deux gestes : votre sexe pulse dans la paume d’Allenna, votre ouverture se serre autour des doigts de Lineva. Le meuble vous maintient tous trois collés ; elles ne ralentissent qu’après la dernière contraction.")],
        [N("Lineva embrasse votre bouche une fois le calme revenu."), L("Tu n’étais pas seulement une place. Tu étais tout le canapé.", "soft")],
        [N("Vous glissez deux doigts en Allenna tandis que Lineva lèche sa perle, son corps couché sur vos jambes. La guerrière jouit une seconde fois entre vous, puis se laisse retomber sur votre poitrine sans chercher à reprendre une place plus convenable."), A("Je ne bougerai plus.", "shaken")],
        [N("La couverture retombe sur trois corps nus. Les vêtements, coussins et tasses restent dispersés ; Lineva garde vos pieds contre son ventre, Allenna votre bras autour de sa taille. Le matin peut bien trouver le salon encombré.")],
      ],
      ellipse: [
        [N("Le canapé vous empile entre Allenna et Lineva. Vous leur montrez les contacts qui conviennent à votre corps ; elles les suivent au milieu des jambes déjà mêlées.")],
        [N("Un baiser avec Lineva devient deux avec Allenna. Les femmes se rejoignent au-dessus de vous et la couverture glisse sous leurs mouvements.")],
        [N("Les vêtements s’ouvrent. Une main de chacune prend un chemin différent sur votre corps, leurs bouches restant liées près de votre épaule.")],
        [N("Lineva s’allonge, Allenna se place entre ses jambes et vous restez contre leurs visages. Le canapé donne une première configuration nette.")],
        [N("Vous revenez au centre, Allenna contre votre poitrine, Lineva plus bas. Le récit se retire lorsque leurs gestes suivent les plaisirs choisis.")],
        [N("Votre plaisir culmine après celui de Lineva et avant celui d’Allenna. Les trois corps continuent de se toucher malgré chaque coussin tombé.")],
        [N("Lineva pose son front au vôtre."), L("Tu as rendu ce canapé exactement assez grand.", "soft")],
        [N("La couverture recouvre l’enchevêtrement. Les tasses refroidissent et le sommeil garde les trois personnes dans la pièce où rien n’avait été prévu.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-home-intersexe-cuisine",
    text: "Cuisine après minuit — montrer vos envies sur le comptoir",
    detail: "La lumière basse et le bois à hauteur de hanches donnent une scène vive où Allenna et Lineva suivent deux plaisirs distincts sans quitter la cuisine.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous avez apporté votre verre. Allenna sa manie de ranger. Moi, une très mauvaise influence. Nous sommes au complet.", "smirk")],
      familiar: [L("Tu as apporté ton verre. Allenna sa manie de ranger. Moi, une très mauvaise influence. Nous sommes au complet.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Allenna range un bol pendant que vous remplissez un verre. Lineva le reprend et le pose près de la tarte, imposant à la cuisine une pause après minuit.")],
        [N("Vous partagez la dernière part. Allenna essuie une miette sur votre bouche ; Lineva embrasse ses doigts et vous attire tous deux dans le sourire qui suit.")],
        [N("Vous vous appuyez au comptoir entre elles. Les baisers passent de Lineva à Allenna, puis les deux femmes se rejoignent devant votre visage.")],
        [N("Allenna s’assied sur le bois. Vous restez contre un genou, Lineva contre l’autre ; ses jambes réunissent les trois corps sous la lampe.")],
        [N("Vous guidez leurs caresses avec vos mains. Le verre reste près de votre coude, le bol hors du placard et la nuit parfaitement tranquille.")],
        [N("Votre plaisir se détend debout contre le comptoir. Allenna vous tient par le cou, Lineva à la taille, jusqu’à ce que le frisson disparaisse.")],
        [N("Lineva porte le verre à votre bouche."), L("Tu n’auras même pas oublié de boire. Soirée irréprochable.", "soft")],
        [N("Allenna abandonne le rangement. Vous repartez tous trois vers la chambre, la tarte finie et les doigts encore joints dans le couloir.")],
      ],
      suggestif: [
        [N("La petite lampe éclaire Allenna et son bol propre. Lineva le pose sur le comptoir ; vous ajoutez votre verre et découvrez une part de tarte oubliée.")],
        [N("Une bouchée passe entre les trois bouches. Allenna rougit lorsque Lineva embrasse la sienne ; vous rejoignez leurs lèvres avant qu’elle puisse reprendre la fourchette.")],
        [N("Vous vous asseyez sur le comptoir et leur montrez les zones où vous voulez leurs mains. Elles prennent deux chemins, reliées par leurs épaules contre vos cuisses.")],
        [N("Allenna reste entre vos jambes ; Lineva se tient derrière elle et l’embrasse pendant que leurs gestes quittent la lumière.")],
        [N("Vous faites asseoir Lineva à votre place. Allenna se met devant elle, vous derrière, et le bois dessine une seconde posture plus vive.")],
        [N("Votre plaisir culmine allongé sur le comptoir, leurs attentions combinées sans être identiques. Le verre tremble à portée de votre main.")],
        [N("Lineva stabilise le verre puis vous le rend."), L("Tu avais choisi un excellent appui.", "soft")],
        [N("Allenna laisse enfin le bol. La chambre vous reçoit encore serrés, la couverture emportée par Lineva et la cuisine laissée en paix.")],
      ],
      explicite: [
        [N("Après minuit, Allenna range encore un bol. Lineva le lui retire ; vous posez votre verre d’eau près de la dernière part de tarte. Sous la petite lampe, vous leur montrez les deux façons dont votre corps répond déjà à leur proximité."), L("Le placard attendra. Ce corps-là, beaucoup moins.", "smirk")],
        [N("Vous partagez la tarte. Allenna essuie une miette sur vos lèvres et vous embrasse ; Lineva goûte ensuite sa bouche. Vous les faites asseoir à moitié sur le comptoir, une cuisse de chaque femme contre votre hanche, et ouvrez leurs chemises."), A("La part est terminée."), P("Pas la soirée.")],
        [N("Vous caressez leurs seins pendant qu’elles s’embrassent. Allenna ouvre vos vêtements et prend votre sexe extérieur en main ; Lineva glisse deux doigts dans l’ouverture que vous lui montrez. Le bois soutient votre dos tandis que leurs gestes prennent chacun une cadence différente."), L("Dites-nous ce que le comptoir change.", "breathless")],
        [N("Vous vous asseyez sur le bord, jambes ouvertes. Allenna s’agenouille devant vous et prend votre plaisir extérieur dans sa bouche ; Lineva reste debout derrière elle, deux doigts en vous. Vous caressez Allenna entre les cuisses tandis que la capitaine embrasse sa nuque."), P("Il permet exactement ça.")],
        [N("La bouche d’Allenna descend et remonte pendant que les doigts de Lineva vous pénètrent. Les femmes se rejoignent près de votre bassin à chaque retrait ; Allenna gémit autour de votre sexe lorsque vos doigts trouvent sa perle."), A("Continuez à me toucher.", "breathless")],
        [N("Vous les arrêtez avant votre climax et soulevez Allenna sur le comptoir. Lineva s’agenouille entre ses jambes ; sa langue lèche la perle de la guerrière tandis que deux de vos doigts entrent en elle. Allenna vous masturbe encore depuis sa place haute.")],
        [N("Allenna jouit, les pieds frappant doucement les portes basses. Lineva garde sa bouche contre elle ; vous maintenez vos doigts en profondeur. La guerrière vous attire ensuite dans un baiser et désigne Lineva d’un simple regard, décidée à rendre ce qu’elle vient de recevoir."), A("À elle.", "determined")],
        [N("Lineva s’assied sur le bois, jambes ouvertes. Allenna prend sa perle dans sa bouche ; vous entrez deux doigts en la capitaine depuis le côté tout en laissant sa main reprendre votre sexe extérieur. Lineva jouit au-dessus d’elles, une main sur chaque tête."), L("Cette cuisine est pleine de talents cachés.", "shaken")],
        [N("Vous vous allongez enfin sur le comptoir. Allenna se place entre vos jambes, bouche autour de votre plaisir extérieur ; Lineva monte à genoux près de votre hanche et glisse ses doigts dans votre ouverture. Elles s’embrassent au-dessus de votre ventre sans interrompre leurs mouvements."), P("Cette fois, jusqu’au bout.")],
        [N("Votre orgasme vient sur le bois : votre sexe pulse dans la bouche d’Allenna et votre ouverture se serre autour des doigts de Lineva. Le verre vibre près de votre épaule ; elles maintiennent leurs gestes jusqu’à ce que votre corps retombe contre le comptoir.")],
        [N("Lineva vous redresse et porte le verre à vos lèvres."), L("Tu venais chercher de l’eau. Je considère que nous avons été très serviables.", "soft")],
        [N("Allenna se penche sur le comptoir. Vous entrez deux doigts en elle par derrière tandis que Lineva, agenouillée, lèche sa perle. Allenna jouit une seconde fois, le visage près de l’assiette vide, puis rit de voir le bol toujours hors du placard."), A("Il restera là.", "shaken")],
        [N("Vous quittez la cuisine avec le verre et une couverture, sans ranger le moindre objet. Dans le couloir, Lineva embrasse Allenna ; vous les rejoignez avant de gagner la chambre tous les trois.")],
      ],
      ellipse: [
        [N("Le bol d’Allenna, votre verre et la dernière part de tarte se retrouvent ensemble sur le comptoir. Lineva fait de cette accumulation une raison de ne plus rien ranger.")],
        [N("Un baiser suit une bouchée. Vous montrez aux deux femmes ce que votre corps veut recevoir ; leurs mains prennent des chemins distincts sous la lampe.")],
        [N("Vous vous asseyez sur le bois, Allenna entre vos jambes et Lineva derrière elle. Leurs bouches se rejoignent avant que les gestes ne descendent hors du cadre.")],
        [N("Allenna prend ensuite la place assise. Lineva reste plus bas, vous contre son flanc ; le comptoir impose une nouvelle hauteur au trio.")],
        [N("Lineva monte à son tour sur le bois. Allenna devant elle, vous derrière, les trois corps gardent une géographie claire jusqu’au fondu.")],
        [N("Votre plaisir culmine allongé sur le comptoir avant le dernier des leurs. Le verre tremble, l’assiette demeure intacte et personne ne se presse.")],
        [N("Lineva vous aide à boire."), L("Tu as donné à ce verre une histoire beaucoup trop longue.", "soft")],
        [N("Le rangement attendra le matin. Vous regagnez la chambre avec Allenna et Lineva, laissant la petite lampe éclairer les objets oubliés.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-home-intersexe-chambre",
    text: "Chambre sans urgence — laisser vos plaisirs prendre leur temps",
    detail: "Dans le lit déjà partagé, Allenna et Lineva suivent votre corps sans modèle ; le silence devient une scène sexuelle lente, profonde et domestique.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez rester entre nous avec tout ce que votre corps est. La nuit ne vous demande aucune explication.", "soft")],
      familiar: [L("Tu peux rester entre nous avec tout ce que ton corps est. La nuit ne te demande aucune explication.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous êtes déjà allongé entre Allenna et Lineva. La conversation se tait ; leurs mains restent sur votre ventre et votre hanche sans chercher de raison de repartir.")],
        [N("Vous réunissez leurs doigts et leur montrez la façon dont vous voulez être tenu. Le silence accueille la réponse mieux que n’importe quelle phrase.")],
        [N("Vous embrassez Allenna, puis Lineva. Elles se rejoignent au-dessus de votre poitrine et la couverture descend légèrement sous leurs mouvements.")],
        [N("Les vêtements s’ouvrent sans quitter le lit. Allenna reste contre votre torse, Lineva contre son dos, leurs caresses suivant votre corps réel.")],
        [N("Vous changez de côté et placez Allenna au milieu. Trois bras se croisent sur trois ventres ; chaque contact dure sans urgence.")],
        [N("Votre plaisir se dénoue dans cette lenteur. Les deux femmes vous gardent contre elles jusqu’au dernier frisson, puis reprennent simplement leurs baisers.")],
        [N("Lineva murmure près de votre bouche."), L("Tu n’as rien à expliquer. Seulement à rester si tu en as envie.", "soft")],
        [N("La couverture remonte. Allenna s’endort entre vous ; le lendemain demeure assez loin pour ne réclamer encore personne.")],
      ],
      suggestif: [
        [N("Allongé entre elles, vous laissez le silence remplir la chambre. La main d’Allenna repose sur votre poitrine, celle de Lineva sur votre cuisse.")],
        [N("Vous guidez leurs mains vers deux plaisirs de votre corps. Elles suivent sans parler puis s’embrassent au-dessus de votre épaule.")],
        [N("Les chemises et la couverture glissent. Allenna découvre votre peau, Lineva découvre la sienne, et vos propres mains restent sur les deux femmes.")],
        [N("Allenna vient entre vos jambes ; Lineva demeure près de votre bouche. La pénombre retient le détail, jamais la place de chacune.")],
        [N("Vous inversez les positions sur le matelas. Lineva plus bas, Allenna contre votre flanc, leurs gestes continuent à passer par votre corps et celui de l’autre.")],
        [N("Votre plaisir culmine sous leurs deux attentions. Le lit absorbe le mouvement et le silence garde votre souffle jusqu’au calme.")],
        [N("Lineva embrasse votre tempe."), L("Tu peux laisser tes deux plaisirs prendre toute la nuit.", "soft")],
        [N("Allenna se glisse au milieu et tire la couverture sur le trio. Le sommeil arrive sans que personne ne décide encore qui préparera les tasses du matin.")],
      ],
      explicite: [
        [N("Vous êtes déjà allongé entre Allenna et Lineva lorsque les mots s’épuisent. Sous la couverture, vous prenez leurs mains et leur montrez les deux plaisirs que votre corps veut offrir cette nuit. Allenna suit votre geste sans question ; Lineva embrasse vos doigts avant de prendre l’autre place."), P("Nous pouvons rester ici longtemps.")],
        [N("Vous embrassez Allenna, puis Lineva dans votre dos. Elles se rejoignent au-dessus de votre épaule ; leurs mains restent sur votre sexe extérieur et à l’ouverture choisie, lentes, encore presque immobiles. Le matelas rapproche les trois torses sans demander d’effort."), L("Toute la nuit, si nécessaire.", "soft")],
        [N("Les chemises s’ouvrent sous les draps. Vous caressez les seins d’Allenna pendant que Lineva embrasse son dos ; Allenna prend votre poitrine et Lineva votre ventre. Chaque personne touche les deux autres dans la même ligne couchée."), A("Je préfère ne plus parler.", "soft")],
        [N("Allenna descend entre vos jambes et prend votre sexe extérieur dans sa bouche. Lineva reste derrière vous, glisse deux doigts dans votre ouverture et vous offre sa poitrine par-dessus votre épaule. Vous caressez Allenna entre les cuisses pendant qu’elle vous donne ses lèvres."), P("Gardez vos deux rythmes.")],
        [N("La bouche d’Allenna enveloppe votre désir extérieur ; les doigts de Lineva entrent plus profondément en vous. Allenna tend une main vers le sexe de la capitaine et la caresse au même rythme que sa langue, tandis que votre bouche trouve la pointe d’un sein de Lineva."), L("Personne ne dort encore.", "breathless")],
        [N("Vous les arrêtez avant le climax et faites allonger Allenna sur le dos. Lineva se place entre ses cuisses, lèche sa perle ; vous entrez deux doigts en elle depuis le côté et embrassez Lineva à chaque fois qu’elle relève la tête."), A("Plus profond. Je veux vous sentir tous les deux.", "breathless")],
        [N("Allenna jouit la première sous votre main et la bouche de Lineva. Elle se cambre silencieusement puis attire la capitaine dans un baiser. Vous gardez vos doigts en elle pendant les contractions, votre autre main caressant le sexe de Lineva contre sa cuisse."), N("Le plaisir d’Allenna s’achève avant que le vôtre reprenne.")],
        [N("Lineva vient à califourchon près de votre visage. Vous léchez sa perle et entrez deux doigts en elle ; Allenna, couchée plus bas, reprend votre sexe extérieur avec sa bouche pendant que sa main revient à l’ouverture que vous lui avez montrée.")],
        [N("Lineva jouit contre votre bouche, ses cuisses serrées autour de votre tête. Allenna ne cesse ni ses lèvres ni ses doigts sur vous ; la capitaine reste au-dessus, caresse les cheveux de son amie et vous laisse poursuivre vers votre propre sommet."), L("Continuez sans moi… je reste là.", "shaken")],
        [N("Votre orgasme arrive sous la bouche et la main d’Allenna : le plaisir extérieur pulse contre sa langue tandis que votre ouverture se contracte autour de ses doigts. Lineva soutient votre bassin et embrasse Allenna près de votre hanche jusqu’à la dernière vague.")],
        [N("Lineva se couche derrière vous après le climax."), L("Tu as laissé chaque partie de toi prendre son temps. C’était beau.", "soft")],
        [N("Allenna se tourne vers Lineva. Vous restez entre leurs jambes, un doigt sur chaque perle, pendant qu’elles frottent leurs sexes l’un contre l’autre et s’embrassent. Allenna reçoit le dernier orgasme de la nuit quelques instants après celui de Lineva, sans synchronie recherchée."), A("Maintenant, dormons.", "shaken")],
        [N("La couverture remonte sur trois corps. Le verre posé près du lit circule puis retrouve sa place. Allenna s’endort au milieu, Lineva garde votre main sur son ventre, et les tasses du matin n’existent encore pour personne.")],
        [N("La lumière du matin vous trouve dans le même ordre. Allenna ouvre un œil, décide que le petit déjeuner peut patienter et ramène votre bras autour d’elle ; Lineva approuve sans même se réveiller tout à fait.")],
      ],
      ellipse: [
        [N("Déjà couché entre Allenna et Lineva, vous leur montrez les deux formes de plaisir que votre corps désire. Le silence accueille leurs mains sans commentaire.")],
        [N("Vous embrassez chacune, puis les regardez s’embrasser au-dessus de vous. La couverture glisse et les chemises s’ouvrent dans la pénombre.")],
        [N("Allenna descend entre vos jambes, Lineva reste dans votre dos. Leurs attentions suivent les chemins indiqués sans cesser de toucher l’autre.")],
        [N("Vous faites allonger Allenna et placez Lineva plus bas. Le matelas permet une rotation lente où chaque corps reste entouré par les deux autres.")],
        [N("Vous revenez au centre, Lineva près de votre bouche, Allenna contre votre bassin. La chronique laisse la nuit garder les gestes précis.")],
        [N("Votre plaisir culmine entre les leurs. Allenna reçoit le dernier plus tard, accompagnée par vos deux corps dans le calme de la chambre.")],
        [N("Lineva murmure après le sommet."), L("Tu n’avais rien à simplifier pour nous rejoindre ici.", "soft")],
        [N("La couverture rassemble le trio. Allenna s’endort entre vous et le lendemain attend sagement que quelqu’un pense au petit déjeuner.")],
      ],
    },
  },
];

export const LINEVA_ALLENNA_HOME_ROUTES: Record<PlayerSex, GroupIntimacyRoute[]> = {
  femme: HOME_FEMME,
  homme: HOME_HOMME,
  intersexe: HOME_INTERSEXE,
};
