import type { PlayerSex } from "./date-scenes";
import type { DialogueLine } from "./game-data";
import type { GroupIntimacyRoute } from "./group-dates";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const A = (text: string, mood?: string): DialogueLine => ({ speaker: "Allenna", text, mood });
const L = (text: string, mood?: string): DialogueLine => ({ speaker: "Lineva", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });

const BASIN_FEMME: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-basin-femme-jeu-eau",
    text: "Jeu d’eau — laisser l’éclaboussure devenir caresse",
    detail: "Un début ludique au milieu du bassin ; les contacts cessent peu à peu d’être accidentels et l’humour accompagne les trois corps jusqu’au plaisir.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez encore prétendre que vous êtes venue pour admirer les mosaïques. Mais évitez de sourire comme ça si vous voulez être crédible.", "smirk")],
      familiar: [L("Tu peux encore prétendre que tu es venue pour admirer les mosaïques. Mais évite de sourire comme ça si tu veux être crédible.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Lineva entre dans le bassin avec assez d’élan pour envoyer une vague sur Allenna. La guerrière essuie son visage, reste parfaitement immobile, puis vous utilise comme écran avant de riposter avec ses deux mains."), A("Dommage collatéral.", "smirk")],
        [N("Vous plongez pour échapper à Lineva et ressortez entre elles. Leurs bras se referment autour de votre taille ; ce qui devait être une prise devient une étreinte flottante, vos jambes dérivant contre les leurs.")],
        [N("Allenna chasse l’eau des yeux de Lineva et l’embrasse par surprise. Vous recevez le rire de la capitaine contre votre bouche, puis le baiser d’Allenna encore humide du premier.")],
        [N("Les éclaboussures diminuent. Sous la surface, Lineva caresse votre hanche ; Allenna suit son poignet jusqu’à votre ventre et y laisse sa propre main. Leurs fronts se rapprochent du vôtre au milieu des reflets.")],
        [N("Vous flottez contre la poitrine d’Allenna tandis que Lineva soutient vos jambes. Le mouvement de l’eau balance les trois corps et transforme chaque baiser en contact prolongé.")],
        [N("Le plaisir monte sous les caresses cachées par l’eau et se libère en un frisson doux. Allenna vous tient contre elle ; Lineva embrasse votre cuisse jusqu’à ce que vos jambes se détendent dans le courant.")],
        [N("Lineva remonte, gouttes au bout des cils, et pose son nez contre le vôtre."), L("Tu triches encore mieux dans l’eau. C’est presque admirable.", "soft")],
        [N("Vous restez accrochées au rebord, épaules serrées. Allenna partage les dattes laissées sur une assiette ; Lineva réclame la dernière et la perd dans un baiser que son amie lui vole.")],
      ],
      suggestif: [
        [N("Une éclaboussure de Lineva atteint Allenna en plein visage. Elle riposte en vous entraînant avec elle sous l’eau ; vous ressortez entre deux femmes riantes, leurs tuniques légères collées à leurs corps."), L("Trahison parfaitement exécutée.", "bright")],
        [N("Vous tirez sur le tissu mouillé de Lineva et il glisse de son épaule. Allenna l’aide à l’enlever, puis vous abandonne sa propre tunique lorsque deux mains la rendent inutile.")],
        [N("Lineva vous enlace par derrière. Allenna se rapproche devant vous et l’embrasse au-dessus de votre épaule ; sous l’eau, leurs mains suivent vos cuisses et reviennent l’une vers l’autre.")],
        [N("Vous reculez jusqu’aux marches peu profondes. Allenna s’assied derrière vous, Lineva reste dans l’eau entre vos genoux ; les différences de hauteur rendent leurs intentions impossibles à confondre.")],
        [N("La bouche de Lineva descend hors du cadre tandis qu’Allenna vous embrasse et caresse sa nuque. Vos doigts cherchent Allenna entre ses cuisses, gardant le trio dans le même courant.")],
        [N("Votre plaisir éclate avec une petite vague contre les marches. Lineva reste en place, Allenna soutient votre poitrine et le rire qui vous échappe répond au leur.")],
        [N("Lineva rejoint votre bouche après le sommet."), L("Tu viens de gagner une course que personne n’avait annoncée.", "soft")],
        [N("Allenna vous conduit vers le panier de fruits sans quitter l’eau. Vous mangez au bord, jambes encore immergées, et chaque éclaboussure tardive se termine désormais par un baiser.")],
      ],
      explicite: [
        [N("Lineva fend l’eau jusqu’au centre du bassin et vous éclabousse d’un revers de main. Allenna reçoit la vague suivante, ferme les yeux avec dignité, puis se jette sur la capitaine. Vous êtes happée dans leur lutte ; trois corps roulent sous la surface avant de remonter en riant, tuniques plaquées à la peau."), A("Elle l’a cherché.", "bright")],
        [N("Lineva prétend se rendre et passe pourtant les bras autour de votre taille. Allenna vient par-devant pour lui barrer toute fuite. Leurs seins se pressent contre les vôtres à travers le tissu détrempé ; le rire ralentit lorsque la main de Lineva reste sur votre hanche et que celle d’Allenna couvre la sienne."), L("Personne ne bouge. J’ai peut-être trouvé un bon courant.", "smirk")],
        [N("Vous embrassez Allenna. Lineva chasse les cheveux mouillés de sa nuque puis y pose sa bouche ; Allenna gémit contre vos lèvres et se retourne pour l’embrasser aussi. Sous l’eau, vous ouvrez leurs tuniques ; elles retirent la vôtre et la laissent flotter vers le rebord."), P("La dernière habillée a perdu.")],
        [N("La compétition reprend le temps d’une seconde. Allenna arrache le haut de Lineva, Lineva défait le bas d’Allenna, et vous les aidez toutes deux jusqu’à ce que les étoffes reposent sur la pierre. Nues dans l’eau jusqu’à la poitrine, elles vous coincent entre leurs hanches et échangent un baiser au-dessus de votre épaule."), A("Égalité."), L("Pour l’instant.", "teasing")],
        [N("Vous reculez sur une marche, assise juste sous la surface. Lineva s’agenouille dans l’eau entre vos cuisses et pose la bouche sur votre sexe ; sa langue trouve votre perle, tandis qu’Allenna s’assied derrière vous sur la marche supérieure, vous soutient sous les seins et glisse deux doigts en Lineva par-dessus son dos."), L("Elle profite encore de ma position.", "breathless")],
        [N("La bouche de Lineva travaille avec des mouvements courts que le clapotis accompagne. Allenna entre et sort ses doigts de Lineva, son autre main frottant votre poitrine mouillée. Vous tournez la tête pour l’embrasser ; Lineva gémit contre votre perle lorsque les doigts d’Allenna se courbent en elle."), A("Elle accélère dès qu’elle veut se plaindre.", "smirk")],
        [N("Lineva abandonne votre sexe juste avant votre sommet et tire Allenna dans l’eau. Elle la plaque doucement contre le rebord, lui soulève une cuisse et s’agenouille. Vous embrassez Allenna debout, vos doigts entrant en Lineva pendant que sa langue écarte les lèvres de la guerrière."), A("C’était une fuite."), L("Une contre-attaque.", "smirk")],
        [N("Allenna jouit la première, sa cuisse serrée sur l’épaule de Lineva. Vous maintenez deux doigts en la capitaine et caressez sa perle du pouce ; Allenna agrippe votre nuque, le cri brisé par votre baiser, puis reste contre vous pendant que ses jambes retrouvent le fond du bassin."), A("Je retire l’accusation de fuite.", "shaken")],
        [N("Vous reprenez place sur la marche, Lineva entre vos jambes. Allenna s’agenouille cette fois près d’elle et l’embrasse pendant que la capitaine retrouve votre sexe. Allenna ajoute deux doigts en vous ; leurs deux gestes alternent, bouche sur votre perle, doigts plus profonds, jusqu’à ce que l’eau déborde à chaque mouvement de vos hanches."), P("Ne changez plus. Je suis tout près.")],
        [N("Votre orgasme vient sous la langue de Lineva et les doigts d’Allenna. Vous vous cambrez sur la marche, une main dans chaque chevelure ; elles gardent leur place jusqu’au dernier spasme, puis Allenna embrasse Lineva contre l’intérieur de votre cuisse, leurs visages encore mouillés de vous et du bassin.")],
        [N("Lineva remonte le long de votre corps et laisse son premier tutoiement se mêler à un rire très doux."), L("Tu fais des vagues même quand tu ne bouges plus.", "soft")],
        [N("Lineva n’a pas encore joui. Allenna l’assied sur la marche immergée et vient à genoux entre ses cuisses ; sa bouche reprend sa perle. Vous vous placez derrière Lineva, la poitrine contre son dos, deux doigts en elle et les mains sur ses seins. Elle jouit en éclaboussant Allenna d’un mouvement involontaire."), L("Cette vague-là n’était pas volontaire.", "shaken")],
        [N("Vous flottez ensuite près du rebord, Allenna entre vous deux, les jambes encore mêlées. Les dattes passent d’une bouche à l’autre ; Allenna rougit quand Lineva lui rappelle sa riposte, puis l’embrasse pour la faire taire. L’eau reste chaude assez longtemps pour ne rien hâter.")],
      ],
      ellipse: [
        [N("Lineva déclenche la première bataille d’eau ; Allenna vous entraîne dans sa riposte. Vous ressortez toutes trois au milieu du bassin, trempées, riantes et trop proches pour reprendre une distance neutre.")],
        [N("Les tuniques collées deviennent un nouveau jeu. Vous retirez celle de Lineva, Allenna la vôtre, puis la capitaine dénoue celle d’Allenna en lui volant un baiser.")],
        [N("Nues sous les reflets, vous vous enlacez au centre. Les mains disparaissent sous l’eau, reviennent sur une hanche, puis repartent avec des intentions qui n’ont plus rien d’accidentel.")],
        [N("Vous gagnez les marches peu profondes. Lineva s’agenouille entre vos jambes, Allenna s’assied derrière vous et leurs deux corps restent reliés par une main posée sur la nuque de la capitaine.")],
        [N("Les places changent dans une éclaboussure : Allenna contre le rebord, Lineva plus bas, vous entre elles. La chronique laisse les gestes précis aux reflets brisés par l’eau.")],
        [N("Votre plaisir culmine le premier, assez fort pour soulever une vague contre les mosaïques. Les deux femmes poursuivent ensuite leur jeu, vos mains restant dans le mouvement.")],
        [N("Lineva revient flotter contre vous après le sommet."), L("Tu avais caché ce talent pendant toute la visite.", "soft")],
        [N("Allenna apporte l’assiette de fruits jusqu’au bord. Vous mangez les pieds dans l’eau, épaules serrées, et la dernière datte disparaît au milieu d’un nouveau baiser à trois.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-basin-femme-rebord",
    text: "Rebord de pierre — construire le désir par les hauteurs",
    detail: "La route la plus structurée par le décor : une femme assise sur la pierre chaude, une autre dans l’eau et la troisième changeant d’appui entre elles.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous choisissez le rebord ou l’eau. Allenna et moi nous chargerons de rendre ce choix beaucoup moins simple.", "smirk")],
      familiar: [L("Tu choisis le rebord ou l’eau. Allenna et moi nous chargerons de rendre ce choix beaucoup moins simple.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("La pierre garde la chaleur du jour. Allenna s’assied au bord, pieds dans l’eau ; Lineva reste debout derrière elle et vous nagez jusqu’à leurs genoux."), L("Nous avons trouvé le meilleur siège.", "bright")],
        [N("Vous posez les bras sur les cuisses d’Allenna. Elle sèche votre visage avec sa paume, Lineva se penche au-dessus de son épaule et vous embrasse toutes deux dans un équilibre maladroit.")],
        [N("Allenna se tourne sur la pierre pour vous offrir une place. Vous vous hissez à côté d’elle ; Lineva reste dans l’eau, les bras autour de vos jambes, et dépose un baiser sur chaque genou.")],
        [N("Les hauteurs tournent avec lenteur. Lineva monte, Allenna descend d’une marche, vous restez entre elles ; aucun changement ne coupe les mains qui caressent deux corps à la fois.")],
        [N("Allenna s’allonge sur la pierre chaude, sa tête sur votre cuisse. Lineva embrasse sa bouche depuis l’eau tandis que vous suivez du doigt les gouttes sur son ventre.")],
        [N("Une caresse plus intime vous fait céder au bord du bassin. Allenna garde votre main sur sa poitrine ; Lineva soutient vos hanches depuis l’eau et le plaisir se prolonge dans le contraste de la pierre et du courant.")],
        [N("Lineva pose son menton sur vos genoux après le calme."), L("Tu as choisi les deux. C’était évidemment la bonne réponse.", "soft")],
        [N("Vous vous séchez sur la dalle, Allenna entre vous. Une galette se brise en trois parts inégales ; Lineva accepte la plus petite uniquement parce qu’elle peut voler une bouchée aux deux autres.")],
      ],
      suggestif: [
        [N("Allenna s’assied sur le rebord de pierre, jambes dans l’eau. Lineva reste derrière elle, vous devant ; la différence de hauteur place son visage exactement à portée de votre bouche.")],
        [N("Vous embrassez Allenna et ouvrez sa tunique humide. Lineva la débarrasse du tissu par les épaules ; sa poitrine se découvre entre vos deux visages et sa rougeur ne l’empêche pas de vous rapprocher.")],
        [N("Lineva glisse dans l’eau. Elle embrasse l’intérieur de la cuisse d’Allenna tandis que vous restez debout derrière la guerrière, vos mains sur ses seins et votre bouche à son oreille.")],
        [N("Allenna descend ensuite dans le bassin et vous fait asseoir sur la pierre chaude. Lineva se place à votre côté ; leurs bouches prennent deux chemins différents pendant que vos jambes reposent sur leurs épaules.")],
        [N("Vous changez encore : Lineva assise au bord, Allenna dans l’eau, vous à genoux derrière la capitaine. Les caresses hors cadre restent reliées par vos mains croisées sur son ventre.")],
        [N("Votre plaisir culmine assise sur la pierre, maintenue par Allenna entre vos jambes et Lineva contre votre dos. Le contraste de l’eau fraîche sur vos chevilles prolonge chaque frisson.")],
        [N("Lineva embrasse votre épaule après le sommet."), L("Tu transformes vraiment chaque place en avantage.", "soft")],
        [N("Allenna étend les serviettes sur le rebord désormais mouillé. Vous vous allongez côte à côte, partageant une galette et les dernières gouttes qui roulent encore sur vos jambes.")],
      ],
      explicite: [
        [N("Allenna s’assied sur le rebord, les mollets dans l’eau. La pierre chaude traverse sa tunique humide ; Lineva se tient derrière elle et vous nagez jusqu’à vous placer entre ses genoux. Le décor distribue déjà les hauteurs sans décider qui conduira."), A("La pierre est plus chaude que le bassin.", "soft")],
        [N("Vous posez les mains sur les cuisses d’Allenna et embrassez son ventre à travers le tissu. Lineva ouvre sa tunique depuis l’arrière, découvre sa poitrine puis l’embrasse sur la bouche par-dessus son épaule. Allenna garde une main dans vos cheveux et l’autre sur la nuque de son amie."), L("Elle nous tient toutes les deux. C’est prometteur.", "smirk")],
        [N("Allenna lève les hanches pour laisser Lineva retirer le dernier vêtement. Assise nue sur la pierre, jambes ouvertes au-dessus de l’eau, elle rougit sous vos regards sans les fuir. Vous embrassez l’intérieur de sa cuisse ; Lineva prend ses seins dans ses mains et lui mord doucement l’épaule."), A("Je préfère quand vous me regardez d’ici.", "troubled")],
        [N("Depuis le bassin, vous posez la bouche sur le sexe d’Allenna. Votre langue suit sa perle tandis que deux doigts entrent en elle vers le haut. Lineva reste debout derrière le rebord, soutient son dos contre ses jambes et se penche pour l’embrasser, une main descendue entre ses propres cuisses."), P("Gardez-la contre vous.")],
        [N("Allenna pousse sur vos doigts et votre langue, les talons battant doucement l’eau. Lineva remplace sa propre main par celle d’Allenna puis la guide sur son sexe ; les deux femmes se caressent pendant que vous restez entre les jambes de la guerrière, leurs souffles passant au-dessus de vous."), A("Lineva… plus près.", "breathless")],
        [N("Allenna vous arrête avant son orgasme et descend dans l’eau. Elle vous hisse sur le rebord à sa place ; Lineva s’assied à côté de vous, une jambe sur vos cuisses. Allenna, debout dans le bassin, prend votre sexe avec sa bouche pendant que vos doigts entrent en Lineva et que celle-ci embrasse votre poitrine."), L("Voilà un changement que j’approuve.", "breathless")],
        [N("La langue d’Allenna reste sur votre perle et ses mains soutiennent vos fesses au bord de la pierre. Vous caressez Lineva de deux doigts profonds ; elle frotte sa perle contre votre cuisse et vous embrasse jusqu’à jouir la première, son bassin pressé contre votre jambe chaude."), L("Ne vous arrêtez pas pour moi.", "shaken")],
        [N("Vous glissez toutes deux dans l’eau. Lineva prend la place debout derrière Allenna, lui soulève une cuisse ; vous restez sur le rebord, penchée vers elles. Votre main entre en Allenna tandis que la bouche de Lineva lèche sa perle et qu’Allenna, appuyée contre la pierre, suce deux de vos doigts."), A("Maintenant. Ne me laissez plus redescendre.", "determined")],
        [N("Allenna jouit contre le rebord, serrée entre le corps de Lineva et votre bras. Sa cuisse tremble dans la main de la capitaine ; vos doigts demeurent en elle pendant que la bouche de Lineva accompagne chaque contraction. Elle vous attire ensuite dans l’eau par un baiser.")],
        [N("Vous remontez assise sur la pierre, les deux femmes dans le bassin entre vos jambes. Allenna glisse deux doigts en vous ; Lineva reprend votre perle avec sa langue. Leurs épaules se touchent, leurs mains se croisent sur vos hanches et votre orgasme arrive dans cette position parfaitement dessinée par le rebord."), P("Oui… restez en bas.")],
        [N("Lineva pose sa joue sur votre cuisse lorsque le plaisir retombe."), L("Tu avais choisi la meilleure vue. Je comprends maintenant.", "soft")],
        [N("Vous faites monter Allenna sur la pierre et l’allongez entre vous. Lineva se place à genoux près de sa bouche ; vous revenez entre ses cuisses. Allenna lèche Lineva pendant que votre langue et vos doigts lui arrachent un second orgasme, plus lent, sous les étoiles de l’ouverture."), A("Je vais finir par aimer ce rebord.", "shaken")],
        [N("Les serviettes absorbent la chaleur de la dalle. Vous vous couchez toutes les trois, pieds encore dans l’eau, et partagez des galettes sèches qui s’émiettent sur vos ventres nus. Allenna redevient légèrement rouge ; Lineva ne commente pas, occupée à lui voler un baiser.")],
      ],
      ellipse: [
        [N("Allenna s’assied au bord, les jambes dans l’eau. Lineva demeure debout derrière elle et vous nagez jusqu’à vous placer entre ses genoux, déjà guidée par les hauteurs du lieu.")],
        [N("Vous ouvrez la tunique d’Allenna pendant que Lineva la retire par les épaules. La guerrière rougit sur la pierre chaude mais conserve une main sur chacune de vous.")],
        [N("Lineva glisse dans le bassin et reste entre les jambes d’Allenna. Vous vous placez derrière la femme assise ; les baisers et les mains relient le haut et le bas de la scène.")],
        [N("Allenna descend à son tour et vous fait asseoir sur le rebord. Les deux femmes demeurent dans l’eau devant vous, leurs épaules rapprochées entre vos cuisses.")],
        [N("La chronique se retire lorsque Lineva prend la place sur la pierre, Allenna plus bas et vous derrière elle. Le décor impose une troisième configuration sans répétition.")],
        [N("Votre plaisir culmine assise au-dessus du bassin. Allenna et Lineva restent entre vos jambes, puis poursuivent leurs propres élans tandis que vous les retenez par les épaules.")],
        [N("Lineva pose un baiser sur votre genou après le calme."), L("Tu as gagné le rebord. Je réclamerai l’eau la prochaine fois.", "soft")],
        [N("Vous vous allongez sur les serviettes, pieds pendants dans le bassin. Les galettes passent de main en main et le rire d’Allenna se mêle au clapotis contre la pierre.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-basin-femme-alcove",
    text: "Alcôve chaude — suivre Allenna quand elle cesse d’hésiter",
    detail: "Une proximité resserrée dans le refuge qu’Allenna a choisi ; sa gêne contenue devient une initiative sexuelle franche qui surprend Lineva et vous.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous êtes ici parce qu’Allenna a ouvert cette alcôve. Je crois qu’elle vient de nous confier bien plus qu’un endroit chaud.", "soft")],
      familiar: [L("Tu es ici parce qu’Allenna a ouvert cette alcôve. Je crois qu’elle vient de nous confier bien plus qu’un endroit chaud.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Allenna écarte le rideau de l’alcôve chaude. Elle entre la première, puis attend que Lineva et vous la rejoigniez sur la dalle étroite bordée de coussins."), A("Je viens ici quand le bassin devient trop bruyant.", "soft")],
        [N("Vous vous asseyez de part et d’autre d’elle. La chaleur du brasero sèche vos vêtements ; Allenna reste consciente de chaque contact jusqu’à ce que Lineva pose simplement sa tête sur son épaule.")],
        [N("Vous prenez la main d’Allenna. Elle embrasse vos doigts, puis ceux de Lineva, rouge de son propre geste mais assez décidée pour recommencer sur vos bouches.")],
        [N("Les trois corps s’allongent sur le côté faute de largeur. Allenna reste au milieu, votre poitrine contre la sienne et Lineva contre son dos ; les baisers deviennent lents et profonds.")],
        [N("Allenna se retourne soudain vers Lineva, l’embrasse et guide sa main sous votre tunique. Sa gêne cesse d’organiser le moment ; ses envies prennent enfin la place.")],
        [N("Les caresses vous conduisent à un plaisir silencieux, retenu par l’intimité de l’alcôve. Allenna garde votre bouche contre la sienne, Lineva votre hanche contre son ventre jusqu’au sommet.")],
        [N("Lineva vous regarde par-dessus l’épaule d’Allenna."), L("Tu viens d’assister à sa façon très discrète de nous renverser.", "soft")],
        [N("Vous restez sous une étoffe sèche, Allenna au centre sans chercher à s’excuser de sa place. Une assiette de fruits arrive sur vos genoux et personne ne rouvre le rideau.")],
      ],
      suggestif: [
        [N("Le rideau retombe et enferme la chaleur autour de vous. Allenna s’assied contre les coussins ; Lineva et vous prenez place si près que vos cuisses encadrent les siennes.")],
        [N("Vous embrassez Allenna avec douceur. Elle rougit, tourne les yeux vers Lineva, puis attire elle-même la capitaine par la nuque pour lui donner un baiser plus audacieux.")],
        [N("Les tuniques humides se retirent dans l’espace étroit. Votre épaule touche le mur, celle de Lineva le rideau ; Allenna demeure entre vous, peau nue et regard de plus en plus stable.")],
        [N("Elle vous allonge sans avertissement et fait asseoir Lineva près de votre visage. Puis Allenna descend entre vos jambes, répartissant les trois corps avec une assurance qui surprend la capitaine."), L("Je n’avais pas vu venir celle-là.", "smirk")],
        [N("Les bouches se posent hors cadre, mais l’enchaînement reste clair : vous embrassez Lineva, Allenna vous donne du plaisir, Lineva caresse la guerrière agenouillée entre vos cuisses.")],
        [N("Votre plaisir culmine sous l’initiative d’Allenna. Elle reste contre vous pendant que Lineva l’embrasse, puis relève la tête sans retrouver son ancienne hésitation.")],
        [N("Lineva caresse votre joue après le sommet."), L("Tu comprends pourquoi je ne sous-estime jamais ses silences.", "soft")],
        [N("Allenna ramène une couverture légère sur vous trois et distribue les quartiers d’orange. Sa rougeur revient quand Lineva sourit, mais elle répond en lui donnant le fruit directement entre les lèvres.")],
      ],
      explicite: [
        [N("Allenna écarte le rideau de perles et vous fait entrer dans une alcôve à peine assez large pour trois coussins. Le brasero chauffe la pierre ; les sons du bassin deviennent lointains. Elle s’assied au centre, consciente d’avoir ouvert un lieu où elle vient d’ordinaire seule, les joues déjà colorées."), A("Je voulais que ce soit ici. Même si je ne sais pas encore quoi faire de cette envie.", "troubled")],
        [N("Vous vous placez devant elle, Lineva derrière. Votre baiser reste lent ; Lineva dégage les boucles de sa nuque et l’embrasse là où son souffle accroche. Allenna ouvre sa tunique elle-même, puis celle de Lineva, refusant que sa gêne laisse les deux autres décider de toute la nudité."), L("Commence par ce qui te plaît, Allenna.", "soft")],
        [N("Allenna découvre votre poitrine et la caresse du bout des doigts. Lineva, serrée dans son dos, prend ses seins en coupe ; vous sucez l’un pendant que la capitaine pince doucement l’autre. Allenna ferme les yeux, rouge jusqu’au cou, mais sa main descend fermement entre vos cuisses."), A("Je veux vous sentir réagir.", "determined")],
        [N("Vous écartez les jambes autour des siennes. Deux doigts d’Allenna entrent en vous ; son pouce trouve votre perle. Lineva l’embrasse par-dessus son épaule tout en glissant une main dans son sexe. Les mouvements commencent lents, pris dans l’étroitesse qui maintient vos trois ventres pressés.")],
        [N("Allenna se libère soudain de votre étreinte et vous pousse doucement sur les coussins. Elle fait asseoir Lineva près de votre tête, jambes ouvertes au-dessus de votre bouche, puis s’agenouille entre les vôtres. La capitaine reste un instant surprise par cette distribution claire des corps."), A("Ne m’aidez pas à hésiter.", "determined")],
        [N("La bouche d’Allenna se pose sur votre sexe, sa langue ferme sur votre perle, tandis que vous léchez Lineva au-dessus de vous. Lineva se penche pour embrasser Allenna à travers la longueur de votre corps et glisse deux doigts en elle. Chacune donne du plaisir sans cesser d’en recevoir."), L("Je retire tout ce que j’allais dire.", "breathless")],
        [N("Vous faites jouir Lineva contre votre bouche. Ses cuisses serrent vos tempes ; Allenna continue de vous lécher pendant que les doigts de Lineva restent en elle. Lorsque le plaisir de la capitaine retombe, elle descend embrasser Allenna, partageant avec elle le goût resté sur ses lèvres."), A("Restez près de moi.", "breathless")],
        [N("Allenna s’allonge ensuite entre vous et Lineva, une jambe relevée sur chacune. Votre bouche reprend sa perle ; Lineva entre deux doigts en elle depuis l’autre côté. Allenna caresse vos cheveux et embrasse Lineva, les regards désormais francs, les hanches poussant sans retenue vers vos deux gestes.")],
        [N("Son orgasme arrive dans un cri étouffé par la bouche de Lineva. Vous sentez sa perle pulser sous votre langue et ses cuisses se fermer autour de vos épaules. Même après, Allenna vous attire sur elle et guide Lineva vers votre sexe encore tendu de désir."), A("Maintenant, toutes les deux pour elle.", "shaken")],
        [N("Vous vous allongez sur le côté faute de place. Allenna se glisse entre vos jambes et vous pénètre de deux doigts ; Lineva se place derrière vous, frotte sa chaleur contre vos fesses et rejoint votre perle par-dessus votre hanche. Leurs rythmes différents vous conduisent au climax, enveloppée entre leurs deux corps."), P("Je vais jouir… ne changez rien.")],
        [N("Lineva embrasse votre épaule lorsque votre plaisir se calme."), L("Tu sais maintenant ce qu’Allenna cache dans les endroits silencieux.", "soft")],
        [N("Allenna n’en a pas fini. Elle attire Lineva face à elle, leurs cuisses entrelacées dans l’espace étroit, et frotte son sexe au sien. Vous restez couchée contre leurs flancs, un doigt sur chaque perle ; elles jouissent à quelques souffles d’écart en se regardant sans chercher un nom nouveau à leur proximité."), L("D’accord… elle gagne cette soirée.", "shaken")],
        [N("Le rideau demeure fermé. Allenna distribue une couverture et des quartiers d’orange, de nouveau légèrement rouge quand elle mesure ce qu’elle vient de conduire. Vous restez toutes trois sur les coussins, Lineva la tête sur son ventre, jusqu’à ce que le brasero baisse.")],
        [N("Avant de rouvrir l’alcôve, Allenna vous embrasse chacune sans détourner les yeux. Lineva lui offre le dernier quartier de fruit et le bruit du bassin revient seulement lorsque vos trois mains soulèvent ensemble le rideau.")],
      ],
      ellipse: [
        [N("Allenna ouvre une alcôve cachée par un rideau de perles. Le lieu est petit, chaud, manifestement intime ; elle attend pourtant que Lineva et vous entriez avant de le refermer.")],
        [N("Vous vous asseyez de part et d’autre d’elle. Allenna reçoit votre baiser, celui de Lineva dans son cou, puis retire elle-même sa tunique au lieu d’attendre qu’on la guide.")],
        [N("Les trois corps s’allongent sur le côté. Votre poitrine touche celle d’Allenna, Lineva se serre contre son dos et les mains se glissent dans les seuls espaces encore libres.")],
        [N("Allenna change soudain les places. Elle vous couche sur les coussins, fait asseoir Lineva près de votre visage et s’agenouille entre vos jambes avec une décision neuve.")],
        [N("Le rideau laisse seulement passer les ombres : la vôtre allongée, celle de Lineva au-dessus de vous et Allenna penchée entre vos cuisses, reliée aux deux autres par leurs mains.")],
        [N("Votre plaisir culmine sous l’attention d’Allenna. Elle poursuit ensuite le mouvement avec Lineva et vous, assumant jusqu’au bout l’envie qu’elle avait d’abord à peine osé nommer.")],
        [N("Lineva vous embrasse après le calme."), L("Tu viens de découvrir sa manière préférée de surprendre les gens.", "soft")],
        [N("Allenna partage une couverture et une orange, rouge de nouveau mais sans regret. Personne ne rouvre le rideau avant que la chaleur du brasero ne devienne douce.")],
      ],
    },
  },
];

const BASIN_HOMME: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-basin-homme-jeu-eau",
    text: "Jeu d’eau — se laisser encercler au milieu du bassin",
    detail: "Les éclaboussures rapprochent les corps, puis Allenna riposte aux provocations de Lineva avec des gestes de plus en plus sexuels et toujours mobiles.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous avez deux possibilités : rester sec sur le bord ou accepter que nous trichions. La première vient de disparaître.", "smirk")],
      familiar: [L("Tu as deux possibilités : rester sec sur le bord ou accepter que nous trichions. La première vient de disparaître.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Lineva vous éclabousse avant que votre second pied touche l’eau. Allenna prétend n’avoir rien vu, puis envoie une vague dans son dos et se réfugie contre votre poitrine."), A("Je cherchais un abri.", "bright")],
        [N("Vous plongez avec elle. Lineva vous rattrape au centre ; ses bras entourent votre taille, ceux d’Allenna vos épaules, et la poursuite devient une étreinte flottante.")],
        [N("Allenna essuie les gouttes sur vos lèvres avant de les embrasser. Lineva se rapproche dans son dos, mord doucement sa nuque et reçoit son baiser suivant par-dessus votre épaule.")],
        [N("Sous la surface, vos jambes se mêlent. Lineva garde une main sur votre hanche ; Allenna la recouvre de la sienne, puis les deux remontent ensemble sur votre ventre.")],
        [N("Vous vous laissez porter contre elles. Une main dans les cheveux d’Allenna, l’autre sur la joue de Lineva, vous échangez des baisers que le clapotis rend lents et maladroits.")],
        [N("Leurs caresses vous mènent à un plaisir doux au milieu de l’eau. Allenna tient votre bassin, Lineva votre bouche ; le frisson se diffuse dans vos jambes flottantes avant de s’apaiser.")],
        [N("Lineva pose son front mouillé au vôtre."), L("Tu viens de réussir à perdre pied sans couler. Joli talent.", "soft")],
        [N("Vous gagnez le bord pour partager des fruits. Allenna garde une jambe contre la vôtre dans l’eau ; Lineva vole deux quartiers d’orange et en rend un sous forme de baiser.")],
      ],
      suggestif: [
        [N("Une vague de Lineva trempe Allenna. Elle vous agrippe pour riposter et vous entraîne tous deux sous l’eau ; lorsque vous remontez, ses vêtements collent à sa poitrine et son air sérieux ne trompe plus personne.")],
        [N("Vous l’aidez à retirer l’étoffe lourde. Lineva se glisse derrière elle, embrasse son épaule nue et laisse Allenna ouvrir à son tour votre tunique au milieu des remous.")],
        [N("Nus dans l’eau jusqu’à la taille, vous vous enlacez au centre. La main de Lineva descend sous la surface ; Allenna suit son mouvement et rougit lorsque votre corps répond entre leurs paumes.")],
        [N("Vous reculez vers une marche. Allenna s’agenouille dans l’eau devant vous, Lineva derrière elle, et leurs bouches se rejoignent avant que celle d’Allenna ne descende hors cadre.")],
        [N("Lineva caresse Allenna pendant qu’elle vous donne du plaisir. Vous retenez leurs cheveux mouillés et gardez chacune à portée de votre bouche, refusant que le bassin sépare les gestes.")],
        [N("Votre plaisir culmine sur la marche. Allenna reste contre votre ventre, Lineva contre son dos ; une éclaboussure accompagne votre mouvement et leur rire vous suit jusque dans le calme.")],
        [N("Lineva relève votre menton après le sommet."), L("Tu fais encore plus de vagues quand tu essaies de rester sage.", "soft")],
        [N("Allenna apporte l’assiette de dattes jusqu’à l’eau. Vous mangez appuyés au rebord, épaules serrées, pendant que Lineva nie avoir déclenché la moindre bataille.")],
      ],
      explicite: [
        [N("Lineva vous accueille d’une gerbe d’eau au moment où vous descendez dans le bassin. Allenna reçoit votre riposte en plein visage, vous regarde avec une lente dignité, puis se jette sur vous. Tous trois roulez sous la surface ; en remontant, ses cuisses entourent votre taille et Lineva vous enlace par derrière."), A("Vous êtes tous les deux responsables.", "bright")],
        [N("La lutte s’immobilise. La poitrine d’Allenna se presse contre la vôtre, celle de Lineva contre votre dos. Vous embrassez Allenna pendant que Lineva mord sa nuque ; sous l’eau, leurs mains ouvrent votre tunique et s’arrêtent sur votre sexe déjà dur entre leurs hanches."), L("Voilà une réaction qui ne ressemble pas à une reddition.", "smirk")],
        [N("Les vêtements mouillés gagnent le rebord dans un concours désordonné. Allenna se retrouve nue la première et tente de protester ; Lineva l’embrasse pour la distraire tandis que vous retirez le dernier tissu de la capitaine. Leurs corps glissent l’un contre l’autre devant vous, l’eau à hauteur de leurs seins."), P("Égalité parfaite.")],
        [N("Allenna referme une main autour de votre sexe sous la surface. Lineva pose la sienne au-dessus, puis guide les doigts de son amie pendant qu’elles s’embrassent. Vous caressez leurs seins et leurs fesses, votre désir frottant entre leurs ventres à chaque mouvement de l’eau."), A("Il va falloir une meilleure prise.", "smirk")],
        [N("Vous gagnez les marches. Allenna s’agenouille devant vous, l’eau aux épaules, et prend votre sexe dans sa bouche. Lineva s’installe derrière elle sur la marche inférieure, écarte ses cuisses et glisse deux doigts en elle pendant que ses lèvres descendent sur sa nuque."), L("Continue, Allenna. Je m’occupe du reste.", "breathless")],
        [N("La bouche d’Allenna monte et descend, sa langue serrée sous votre gland. Chaque poussée des doigts de Lineva lui arrache un gémissement autour de vous. Vous tenez leurs deux chevelures hors de l’eau, puis embrassez Lineva lorsqu’elle se penche sur le côté sans cesser de pénétrer son amie."), P("Je veux vous sentir toutes les deux.")],
        [N("Vous reculez avant de jouir et tirez Lineva sur la marche. Allenna la fait asseoir, jambes ouvertes dans l’eau ; sa bouche prend sa perle pendant que vous entrez deux doigts en Allenna par derrière. Lineva vous agrippe à la hanche et rit entre deux gémissements."), L("Une pause tactique, rien de plus.", "shaken")],
        [N("Lineva jouit la première sous la langue d’Allenna. Vous maintenez vos doigts en Allenna et sentez son bassin répondre ; la guerrière continue jusqu’au dernier spasme de son amie, puis se retourne vers vous avec un regard où toute retenue vient de disparaître."), A("À moi de choisir la suite.", "determined")],
        [N("Allenna s’assied sur la marche immergée, une jambe relevée sur l’épaule de Lineva. Vous vous placez entre ses cuisses et la pénétrez lentement ; Lineva garde sa bouche sur sa perle tout en tenant son genou ouvert. Allenna vous accueille plus profondément à chaque petite vague."), A("Plus fort. L’eau absorbe le mouvement.", "breathless")],
        [N("Votre bassin frappe celui d’Allenna sous la surface. Lineva accélère sa langue et vous offre sa bouche par-dessus la cuisse levée. Allenna jouit autour de votre sexe ; vous continuez quelques poussées avant que votre propre orgasme arrive, distinct, profond en elle tandis que les deux femmes vous retiennent."), P("Je jouis… gardez-moi là.")],
        [N("Lineva se redresse dans l’eau, embrasse votre joue et laisse la nouvelle familiarité glisser avec une goutte."), L("Tu as réussi à faire déborder un bassin. Je respecte l’exploit.", "soft")],
        [N("Allenna se retire de vous, encore tremblante, puis fait asseoir Lineva sur le rebord. Elle s’agenouille dans l’eau et lèche son sexe ; vous restez derrière la capitaine, deux doigts en elle et les mains sur ses seins. Le second orgasme de Lineva fait jaillir son talon contre l’eau."), L("Cette fois, l’éclaboussure n’était pas ma faute.", "shaken")],
        [N("Vous flottez ensuite près du bord avec Allenna au milieu. Les dattes passent entre vos bouches ; elle rougit en regardant l’eau redevenir calme, mais Lineva lui prend la main sous la surface. Personne ne se sèche avant que le brasero faiblisse.")],
      ],
      ellipse: [
        [N("Lineva déclenche une bataille d’eau dès votre entrée. Allenna riposte en vous utilisant comme bouclier, puis vous entraîne avec elle sous la surface lorsque la capitaine contre-attaque.")],
        [N("Les tuniques mouillées deviennent trop lourdes. Vous retirez celle d’Allenna pendant que Lineva ouvre la vôtre ; les dernières étoffes flottent jusqu’au rebord.")],
        [N("Nus au centre du bassin, vous vous enlacez. Les mains disparaissent sous l’eau et les baisers passent de votre bouche à celles qu’Allenna et Lineva échangent entre elles.")],
        [N("Vous atteignez les marches. Allenna s’agenouille devant vous, Lineva s’installe derrière elle et les trois corps restent reliés par vos mains dans leurs cheveux.")],
        [N("Les silhouettes changent ensuite : Lineva assise dans l’eau, Allenna entre ses jambes, vous contre leur côté. Les reflets se brisent avant de révéler davantage.")],
        [N("Votre plaisir culmine après celui de Lineva et avant celui d’Allenna. Le jeu se poursuit sans simultanéité forcée, ponctué par des vagues et des rires étouffés.")],
        [N("Lineva flotte près de votre épaule une fois le calme revenu."), L("Tu viens de transformer une baignade en légende locale.", "soft")],
        [N("Allenna partage les fruits au bord du bassin. Les jambes restent dans l’eau et les épaules serrées, assez proches pour que chaque bouchée volée finisse en baiser.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-basin-homme-rebord",
    text: "Rebord de pierre — unir la bouche, l’eau et la hauteur",
    detail: "Les positions naissent du niveau de la pierre : Lineva ou Allenna assise, l’autre dans l’eau, tandis que votre bassin relie leurs plaisirs.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous avez l’avantage de la hauteur. Profitez-en avant qu’Allenna décide de changer les places.", "smirk")],
      familiar: [L("Tu as l’avantage de la hauteur. Profites-en avant qu’Allenna décide de changer les places.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous vous asseyez sur la pierre chaude, pieds dans le bassin. Allenna reste dans l’eau entre vos genoux ; Lineva se tient derrière vous et pose son menton sur votre épaule.")],
        [N("Allenna embrasse votre genou puis votre bouche lorsque vous vous penchez. Lineva garde une main sur votre torse et tend l’autre à son amie pour soutenir cet équilibre improbable.")],
        [N("Vous descendez dans l’eau et faites monter Allenna à votre place. Lineva s’assied près d’elle ; leurs jambes encadrent vos hanches et leurs baisers vous rejoignent à deux hauteurs.")],
        [N("Les places tournent encore. Lineva reste seule au bord, Allenna et vous dans le bassin ; vous enlacez la capitaine par les jambes tandis qu’Allenna embrasse sa tempe.")],
        [N("Allongé sur la pierre, vous recevez Allenna contre votre flanc et Lineva contre l’autre. Le rebord tiède sous votre dos rend leurs caresses plus lentes.")],
        [N("Le plaisir vous traverse sous leurs mains, vos jambes encore dans l’eau. Allenna vous tient à la hanche, Lineva au visage, et chaque frisson semble courir jusqu’aux vaguelettes.")],
        [N("Lineva se penche sur vous après le sommet."), L("Tu as essayé toutes les hauteurs. Verdict : aucune ne te rend raisonnable.", "soft")],
        [N("Vous partagez les serviettes sur la dalle. Allenna coupe une galette, Lineva vole la part centrale et vous restez assez serrés pour lui reprendre chacun une bouchée.")],
      ],
      suggestif: [
        [N("Lineva s’assied au bord, pieds dans l’eau, et vous attire entre ses genoux. Allenna reste dans le bassin derrière vous ; sa bouche atteint votre dos pendant que celle de Lineva trouve la vôtre.")],
        [N("Vous ouvrez la tunique de Lineva. Allenna la retire par en dessous, puis laisse vos mains dénouer son propre vêtement mouillé lorsqu’elle se hisse entre vous deux.")],
        [N("Allenna se replace dans l’eau et Lineva ouvre les jambes sur la pierre. Vous restez debout entre elles, une main sur chacune, leurs bouches à deux hauteurs différentes.")],
        [N("Vous prenez ensuite la place assise. Allenna s’agenouille dans le bassin devant vous ; Lineva se tient derrière, poitrine contre votre dos et doigts cachés plus bas.")],
        [N("La chronique laisse le rebord organiser le reste : une femme entre vos jambes, l’autre au-dessus de votre épaule, leurs contacts l’une avec l’autre maintenant la scène entière.")],
        [N("Votre plaisir culmine assis sur la pierre, retenu par Allenna dans l’eau et Lineva derrière vous. Le bassin reçoit les mouvements de vos jambes tremblantes.")],
        [N("Lineva pose un baiser dans votre nuque."), L("Tu vas regarder chaque rebord différemment maintenant.", "soft")],
        [N("Allenna vous aide à descendre avant d’étendre les serviettes. Vous mangez allongés, jambes encore mouillées, en laissant la pierre rendre lentement sa chaleur.")],
      ],
      explicite: [
        [N("Lineva s’assied sur le rebord, les pieds dans l’eau, et ouvre les genoux pour vous laisser venir entre eux. Allenna demeure dans le bassin derrière vous, l’eau à la poitrine. La pierre chauffe les cuisses de la capitaine ; le courant refroidit vos mollets."), L("Cette place offre plusieurs avantages.", "smirk")],
        [N("Vous embrassez Lineva et ouvrez sa tunique. Allenna se hisse assez haut pour prendre sa poitrine par-dessous vos bras ; ses doigts pincent les pointes mouillées tandis que votre bouche suit le cou de la capitaine. Lineva tend une main vers Allenna et caresse sa joue sans quitter vos hanches."), A("Elle profite déjà de la hauteur.")],
        [N("Allenna retire votre pantalon depuis l’eau. Votre sexe se dresse entre les cuisses ouvertes de Lineva ; elle le prend en main, le frotte contre sa perle sans vous laisser entrer, puis embrasse Allenna lorsque la guerrière se penche au-dessus de votre hanche."), L("Pas encore. Allenna choisit d’abord.", "breathless")],
        [N("Vous faites asseoir Allenna sur la pierre à côté de Lineva. Debout dans le bassin, vous écartez ses jambes et posez la bouche sur son sexe ; Lineva reste contre son flanc, embrasse ses seins et referme une main autour de votre membre pendant que votre langue travaille la perle d’Allenna."), A("Je ne sais plus quelle chaleur vient d’où.", "breathless")],
        [N("Deux doigts entrent en Allenna pendant que votre langue reste sur elle. Lineva vous masturbe depuis le bord et embrasse la guerrière par-dessus votre épaule. Allenna vous retient par les cheveux ; ses talons battent l’eau à mesure que son orgasme approche, puis elle vous fait reculer avant de céder."), A("Lineva d’abord.", "determined")],
        [N("Lineva s’allonge sur la pierre, les hanches au bord. Allenna descend dans le bassin et prend sa perle dans sa bouche ; vous restez debout entre ses jambes, votre sexe contre son entrée. Elle guide elle-même votre bassin et vous accueille lentement pendant que son amie la lèche par-dessous."), L("Cette hauteur était bien une excellente idée.", "shaken")],
        [N("Vous pénétrez Lineva en poussées profondes, ses fesses soutenues par la pierre. Allenna maintient sa langue entre vos corps et frotte sa perle à chaque retrait. Lineva jouit sous vous, cuisses refermées autour de vos hanches, sa main agrippant celle d’Allenna dans l’eau."), L("Continuez… je tiens encore.", "breathless")],
        [N("Vous vous retirez avant votre propre climax. Allenna reprend place assise sur le rebord ; Lineva reste dans l’eau entre ses jambes. Vous pénétrez Allenna debout tandis que Lineva lui lèche la perle et soutient une de ses cuisses sur son épaule."), A("Plus profond. La pierre me tient.", "determined")],
        [N("Allenna jouit autour de vous, sa nuque rejetée contre votre bouche. Lineva poursuit sa langue pendant les contractions ; vous embrassez la guerrière, puis ralentissez sans sortir, laissant son plaisir s’achever avant de reprendre pour le vôtre."), N("Ses doigts trouvent la main de Lineva sous l’eau.")],
        [N("Vos poussées repartent, plus courtes. Lineva se redresse et referme sa main autour de la base de votre sexe à chaque retrait ; Allenna vous garde en elle jusqu’à ce que vous jouissiez à votre tour. Votre plaisir vient après le sien et vous plie sur son épaule chaude."), P("Je ne peux plus tenir cette position.")],
        [N("Lineva appuie son visage mouillé contre votre flanc."), L("Tu as très bien tenu. Le rebord pourra témoigner.", "soft")],
        [N("Vous descendez dans l’eau et faites allonger Allenna sur la pierre. Lineva se remet entre ses cuisses ; sa bouche et vos doigts lui arrachent un second orgasme, tandis qu’Allenna caresse la capitaine entre les jambes et garde ainsi les trois plaisirs reliés."), A("Je ne regarderai plus cette pierre de la même façon.", "shaken")],
        [N("Les serviettes couvrent la dalle où vous vous étendez ensuite. Lineva garde les pieds dans l’eau, Allenna la tête sur votre ventre. Vous partagez une galette trop sèche, les miettes collées aux peaux humides, et personne ne propose de rejoindre le bruit du bassin principal.")],
        [N("La pierre finit par refroidir sous vos dos. Vous descendez une dernière fois dans l’eau pour rincer les miettes, Allenna entre vous, puis quittez le rebord avec les serviettes nouées et les doigts encore mêlés.")],
      ],
      ellipse: [
        [N("Lineva s’assied sur le rebord chaud, Allenna reste dans l’eau et vous prenez place entre elles. Le décor distribue immédiatement trois hauteurs et trois façons de se rapprocher.")],
        [N("Vous ouvrez la tunique de Lineva. Allenna se hisse pour embrasser sa poitrine ; la capitaine garde une main sur votre hanche et l’autre dans les cheveux de son amie.")],
        [N("Allenna monte ensuite sur la pierre. Vous restez dans le bassin entre ses jambes, Lineva contre son côté, et les baisers relient les trois corps malgré le dénivelé.")],
        [N("Vous prenez la place assise. Allenna se retrouve devant vous dans l’eau, Lineva derrière votre dos, et les mains disparaissent hors du cadre sans perdre leur géographie.")],
        [N("Le récit se retire lorsque Lineva s’allonge, les hanches au bord. Allenna reste plus bas, vous debout entre elles ; la pierre et l’eau imposent une nouvelle position.")],
        [N("Votre plaisir arrive après celui de Lineva. Allenna reçoit ensuite le sien dans vos deux gestes, et le bassin interdit toute conclusion artificiellement simultanée.")],
        [N("Lineva embrasse votre ventre quand le calme revient."), L("Tu as épuisé toutes les possibilités de cette pierre. Presque.", "soft")],
        [N("Vous vous couchez sur les serviettes, pieds dans l’eau. Allenna partage les galettes ; Lineva partage surtout les bouchées des deux autres et reçoit deux baisers en sanction.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-basin-homme-alcove",
    text: "Alcôve chaude — céder la conduite à Allenna",
    detail: "Dans son refuge étroit, Allenna commence intimidée puis choisit clairement la bouche, la pénétration et les places des trois corps.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous entrez chez elle, en quelque sorte. Laissez-lui le temps de décider comment elle veut nous y garder.", "soft")],
      familiar: [L("Tu entres chez elle, en quelque sorte. Laisse-lui le temps de décider comment elle veut nous y garder.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Allenna referme le rideau de l’alcôve et s’assied sur le coussin central. Vous prenez place à sa droite, Lineva à sa gauche ; vos trois genoux se touchent dans l’espace étroit.")],
        [N("La chaleur sèche vos peaux. Allenna garde d’abord les yeux baissés, puis vous prend la main et la pose sur sa joue. Lineva se contente de caresser sa nuque.")],
        [N("Vous l’embrassez lentement. Elle tourne ensuite le visage vers Lineva et l’embrasse avec plus d’assurance, comme si le premier geste avait ouvert le chemin du second.")],
        [N("Allongés sur le côté, vous formez une seule ligne : votre poitrine contre Allenna, son dos contre Lineva. Les bras se croisent au-dessus de son ventre.")],
        [N("Allenna change soudain de place, vous fait reculer sur les coussins et attire Lineva contre votre flanc. Sa gêne demeure dans ses joues, plus dans ses mains.")],
        [N("Le plaisir vous atteint sous leurs caresses réunies. Allenna garde votre regard, Lineva votre épaule ; le frisson s’achève dans un silence que le rideau protège.")],
        [N("Lineva vous sourit depuis l’autre côté d’Allenna."), L("Tu comprends maintenant pourquoi ses silences sont dangereux.", "soft")],
        [N("Vous restez sous une couverture fine, Allenna au centre. Elle distribue des morceaux de fruit et accepte sans protester les deux baisers qui suivent chaque bouchée.")],
      ],
      suggestif: [
        [N("L’alcôve avale le bruit du bassin. Allenna s’assied entre vous et Lineva, rouge d’avoir choisi ce refuge, les mains croisées sur des genoux qu’elle garde pourtant contre les vôtres.")],
        [N("Vous embrassez son épaule. Lineva suit l’autre ; Allenna ferme les yeux, puis prend vos deux visages et réclame elle-même des baisers plus profonds.")],
        [N("Les vêtements humides quittent les corps dans l’espace étroit. Allenna se laisse regarder, touche votre torse et la poitrine de Lineva sans reprendre sa vieille réserve.")],
        [N("Elle vous allonge et vient à genoux entre vos jambes. Lineva s’assied près de votre tête ; Allenna l’embrasse avant de descendre vers votre désir hors du cadre.")],
        [N("Vous gardez une main sur Allenna et l’autre sur Lineva. La capitaine caresse son amie penchée sur vous, empêchant la scène de se réduire à deux.")],
        [N("Votre plaisir culmine sous la conduite d’Allenna. Elle reste entre vos jambes, Lineva contre votre bouche, et ne détourne plus le regard lorsque votre corps se tend.")],
        [N("Lineva embrasse votre tempe après le sommet."), L("Tu viens de voir Allenna arrêter de se demander si elle ose.", "soft")],
        [N("Allenna revient entre vous sous la couverture. Sa rougeur renaît à la première plaisanterie de Lineva, mais elle la fait taire avec un quartier d’orange et un baiser.")],
      ],
      explicite: [
        [N("Allenna vous conduit derrière le rideau de perles. L’alcôve tient à peine trois corps assis ; sa pierre tiède et ses coussins portent l’empreinte d’un refuge souvent solitaire. Elle s’installe au centre, regarde votre sexe se tendre sous le tissu humide puis relève les yeux, rouge de son propre désir."), A("Je vous ai amenés ici parce que je ne voulais pas partager cet endroit avec le bruit.", "troubled")],
        [N("Vous embrassez Allenna, Lineva dans son dos. La capitaine ouvre sa tunique et prend ses seins dans ses paumes ; vous sucez une pointe pendant qu’elle pince l’autre. Allenna se cambre entre vous deux et garde ses mains sur vos nuques, encore hésitante mais nullement passive."), L("Nous sommes ici. Le reste peut attendre.", "soft")],
        [N("Allenna retire votre pantalon. Votre sexe se dresse contre son ventre ; elle le caresse d’abord du bout des doigts, attentive à votre réaction. Lineva se glisse près de votre hanche et embrasse Allenna, puis guide la main de son amie seulement jusqu’à ce que celle-ci reprenne elle-même le mouvement."), A("Je sais ce que je veux essayer.", "determined")],
        [N("Elle vous allonge sur les coussins et s’agenouille entre vos jambes. Lineva vient près de votre tête, une cuisse de chaque côté de votre épaule. Allenna prend votre sexe dans sa bouche tandis que vous léchez la perle de Lineva ; la capitaine se penche assez loin pour glisser deux doigts en Allenna."), L("Je n’avais pas prévu qu’elle nous place ainsi.", "breathless")],
        [N("La bouche d’Allenna descend profondément sur vous. Les doigts de Lineva entrent en elle depuis l’arrière ; votre langue maintient sa pression sur Lineva au-dessus de votre visage. Allenna gémit autour de votre sexe, mais ne ralentit pas, et ses yeux restent levés vers les vôtres."), P("Allenna, vous êtes sûre de vous."), A("Enfin.", "determined")],
        [N("Vous reculez avant le climax. Allenna fait alors asseoir Lineva contre le mur, jambes ouvertes, et s’installe entre elles. Elle lèche la capitaine pendant que vous la pénétrez de deux doigts par derrière ; Lineva prend votre sexe en main et vous masturbe au-dessus de l’épaule d’Allenna."), L("Elle vient vraiment de prendre toute l’alcôve.", "shaken")],
        [N("Lineva jouit sous la langue d’Allenna, sa main se crispant autour de votre sexe sans cesser le mouvement. Vous maintenez les doigts en Allenna jusqu’à ce qu’elle se cambre également, tout près de son propre plaisir, puis elle s’arrête volontairement pour changer encore les places."), A("Je veux vous sentir en moi.", "breathless")],
        [N("Allenna vous fait asseoir contre les coussins et vient à califourchon. Elle guide votre sexe à son entrée et descend lentement jusqu’à vous recevoir tout entier. Lineva s’agenouille derrière elle, embrasse sa nuque et frotte sa perle entre deux doigts pendant qu’Allenna commence à vous chevaucher."), P("Prenez tout le rythme.")],
        [N("Les mouvements d’Allenna deviennent rapides malgré l’espace resserré. Lineva maintient son corps contre le vôtre, une main sur sa poitrine, l’autre entre vos bassins. Allenna jouit autour de vous, se cambre contre Lineva et continue pourtant à bouger lentement une fois les contractions passées."), A("Je veux aussi le sentir jouir.", "shaken")],
        [N("Elle reprend des mouvements profonds, Lineva l’embrassant par-dessus son épaule. Vous jouissez en Allenna après son orgasme ; son bassin reste abaissé sur vous pendant chaque pulsation, ses bras autour de votre cou et la main de Lineva sur vos deux ventres."), P("Je suis à vous deux.")],
        [N("Lineva touche votre joue au-dessus de l’épaule d’Allenna."), L("Tu as choisi le bon endroit pour te rendre. Même si Allenna vient clairement de gagner.", "soft")],
        [N("Allenna se retire puis allonge Lineva sur le côté. Vous glissez deux doigts en la capitaine depuis l’arrière tandis qu’Allenna lèche sa perle et embrasse ensuite sa bouche. Le second orgasme de Lineva secoue les trois corps serrés, sans laisser un centimètre vide dans l’alcôve."), L("Je concède la victoire. Une seule fois.", "shaken")],
        [N("La couverture recouvre trois peaux et trop de jambes. Allenna partage une orange, un peu rouge devant l’ampleur de son initiative, mais ne retire pas la main posée sur votre ventre. Lineva s’endort presque contre sa poitrine avant que le brasero ne baisse.")],
      ],
      ellipse: [
        [N("Allenna vous invite dans l’alcôve qu’elle choisit lorsqu’elle veut échapper au bruit. Le rideau retombe sur trois personnes assises assez près pour partager la chaleur.")],
        [N("Vous l’embrassez ; Lineva embrasse sa nuque. Allenna rougit, puis ouvre elle-même sa tunique et guide vos mains au lieu de subir sa propre hésitation.")],
        [N("Les vêtements rejoignent le bord des coussins. Allenna touche votre désir visible, puis la poitrine de Lineva, et leurs bouches se rencontrent au-dessus de votre épaule.")],
        [N("Elle vous allonge, place Lineva près de votre visage et s’agenouille entre vos jambes. Cette initiative nette distribue les trois corps avant le fondu.")],
        [N("Les ombres sur le rideau montrent ensuite Allenna entre vous, puis au-dessus, puis penchée vers Lineva. L’alcôve interdit toute distance et toute scène parallèle.")],
        [N("Votre plaisir culmine après celui d’Allenna. Lineva reçoit le dernier, accompagnée par vous deux, tandis que le bruit du bassin reste au-dehors.")],
        [N("Lineva vous embrasse dans le calme."), L("Tu viens d’apprendre ce qu’elle garde derrière ses rideaux.", "soft")],
        [N("Allenna partage la couverture et les fruits, de nouveau rouge mais fière. Vous restez jusqu’à ce que la pierre refroidisse, sans donner d’autre nom à ce qu’elle a choisi.")],
      ],
    },
  },
];
const BASIN_INTERSEXE: GroupIntimacyRoute[] = [
  {
    id: "group-date-allenna-lineva-basin-intersexe-jeu-eau",
    text: "Jeu d’eau — mêler vos plaisirs aux éclaboussures",
    detail: "Le jeu devient sexuel à partir des réactions que vous leur montrez ; les trois corps restent mobiles, joueurs et reliés sous la surface.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez nous montrer ce que l’eau change pour vous. En échange, je promets de ne tricher que raisonnablement.", "smirk")],
      familiar: [L("Tu peux nous montrer ce que l’eau change pour toi. En échange, je promets de ne tricher que raisonnablement.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Une vague de Lineva vous atteint avant son rire. Allenna riposte avec votre aide ; tous trois perdez pied et remontez enlacés au milieu des mosaïques mouvantes.")],
        [N("Vous restez entre elles, les bras autour de leurs tailles. Ce qui était une prise devient une étreinte flottante, jambes et tuniques dérivant dans le même courant.")],
        [N("Allenna vous embrasse, Lineva embrasse Allenna. Vous réunissez ensuite leurs visages et le jeu continue avec des bouches plutôt qu’avec de l’eau.")],
        [N("Vous montrez à chacune une caresse différente sur votre corps. Elles la suivent sous la surface, leurs mains se touchant assez souvent pour ne jamais former deux duos.")],
        [N("Lineva soutient vos jambes tandis qu’Allenna garde votre dos contre sa poitrine. Le bassin balance doucement les trois corps et ralentit chaque frisson.")],
        [N("Votre plaisir se dénoue dans l’eau, pris entre les gestes que vous avez choisis. Allenna embrasse votre tempe ; Lineva garde votre main contre sa joue.")],
        [N("Lineva revient flotter face à vous."), L("Tu viens de prouver que ton corps connaît mieux le courant que moi.", "soft")],
        [N("Vous mangez les dattes au bord, toujours immergés jusqu’aux épaules. Allenna rit quand Lineva tente une dernière éclaboussure et reçoit deux baisers pour sanction.")],
      ],
      suggestif: [
        [N("La bataille d’eau commence avant que vos tuniques soient entièrement mouillées. Allenna vous entraîne sous la surface pour éviter Lineva ; vous remontez contre elle, le tissu collé à vos trois peaux.")],
        [N("Les vêtements gagnent le rebord. Vous leur montrez les zones que vous voulez offrir ; Allenna suit lentement, Lineva avec une audace que votre main ajuste sans rompre son sourire.")],
        [N("Nus au centre, vous embrassez Lineva pendant qu’Allenna reste contre son dos. Leurs mains explorent votre corps sous l’eau et se rejoignent sur votre bassin.")],
        [N("Vous gagnez les marches. Allenna s’agenouille devant vous, Lineva derrière elle, et les deux bouches descendent vers les plaisirs que vous leur avez indiqués.")],
        [N("Les rôles tournent : Lineva assise, Allenna entre ses cuisses, vous à leur côté. La vapeur et les reflets gardent le détail sans effacer la position de quiconque.")],
        [N("Votre plaisir culmine sur la marche, distinct du leur. Elles restent près de vous, puis poursuivent ensemble tandis que votre main les relie encore.")],
        [N("Lineva embrasse vos doigts après le sommet."), L("Tu deviens franchement dangereux dès que tu touches l’eau.", "soft")],
        [N("Allenna partage l’assiette de fruits. Vous restez épaules contre épaules au bord, et les dernières gouttes sur les lèvres servent de prétexte à d’autres baisers.")],
      ],
      explicite: [
        [N("Lineva lance la première vague ; Allenna répond en vous attirant sous l’eau. Vous remontez au centre, leurs bras autour de votre taille. Les vêtements plaqués rendent chaque réaction visible ; vous prenez leurs mains et leur montrez les plaisirs que votre corps veut recevoir dans le bassin."), P("Pas de tour. Restez toutes les deux avec moi.")],
        [N("Les tuniques dérivent jusqu’au rebord. Allenna embrasse votre bouche, Lineva sa nuque ; sous la surface, l’une caresse votre sexe extérieur tandis que l’autre glisse deux doigts dans l’ouverture que vous lui avez offerte. Leurs poignets se croisent sur votre ventre.")],
        [N("Vous répondez en caressant Allenna entre les cuisses et en pressant Lineva contre votre poitrine. Les deux femmes s’embrassent devant vous, leurs seins glissant l’un contre l’autre, puis échangent leurs places sur votre corps sans quitter leurs propres caresses."), L("Le courant vient de changer.", "breathless")],
        [N("Vous reculez sur une marche. Lineva s’agenouille entre vos jambes et prend votre désir extérieur dans sa bouche ; Allenna se place derrière vous, deux doigts dans votre ouverture. Vous masturbez Allenna d’une main pendant que l’autre retient Lineva par la nuque hors de l’eau."), A("Je sens chaque mouvement de Lineva à travers vous.", "breathless")],
        [N("La bouche de Lineva et les doigts d’Allenna construisent deux rythmes complémentaires. Allenna se penche pour embrasser la capitaine à chaque retrait ; Lineva glisse une main entre ses cuisses, de sorte que la guerrière reçoit du plaisir pendant qu’elle vous pénètre."), P("Continuez comme ça.")],
        [N("Vous les arrêtez avant le climax et faites asseoir Allenna sur la marche. Lineva se place entre ses cuisses ; sa langue trouve sa perle. Vous vous agenouillez derrière la capitaine et entrez deux doigts en elle tandis qu’Allenna prend la partie de votre sexe qu’elle désire dans sa bouche."), A("Cette fois, je ne recule pas.", "determined")],
        [N("Allenna jouit contre la langue de Lineva, sa bouche quittant votre corps dans un cri. Vos doigts restent en la capitaine, dont le bassin répond à chaque contraction de son amie. Allenna reprend ensuite votre bouche dans un baiser, encore tremblante et amusée par l’éclaboussure qu’elle vient de provoquer.")],
        [N("Lineva s’allonge dans l’eau peu profonde de la marche. Vous vous placez au-dessus de son sexe et le léchez ; Allenna reste entre vos jambes, sa bouche sur votre plaisir extérieur et ses doigts dans votre ouverture. Lineva caresse Allenna depuis dessous et garde ainsi le cercle fermé."), L("Voilà une revanche aquatique très sérieuse.", "shaken")],
        [N("Votre langue fait jouir Lineva la première. Elle continue pourtant sa main sur Allenna ; cette dernière ne quitte ni sa bouche ni ses doigts sur vous. Vous basculez en arrière, soutenu par les deux femmes, tandis que les remous annoncent l’approche de votre propre plaisir."), P("Je suis tout près.")],
        [N("Votre orgasme vous prend sur les marches : le sexe extérieur pulse dans la bouche d’Allenna tandis que votre ouverture se serre autour de ses doigts. Lineva maintient votre bassin et embrasse le ventre d’Allenna, qui continue jusqu’à la fin de chaque vague.")],
        [N("Lineva remonte près de votre visage après le calme."), L("Tu viens de faire plus de remous que notre bataille entière.", "soft")],
        [N("Allenna veut encore recevoir. Elle s’allonge sur le rebord ; Lineva frotte sa perle pendant que vos doigts entrent en elle depuis l’eau. Sa bouche embrasse la capitaine au-dessus de vous, puis son orgasme la fait rire contre leurs lèvres mêlées."), A("Cette vague-là était à moi.", "shaken")],
        [N("Vous restez dans l’eau jusqu’à ce que vos doigts se froissent. Les dattes passent d’Allenna à Lineva puis à votre bouche ; la guerrière rougit en regardant les tuniques au bord, mais ne retire pas sa jambe enlacée aux vôtres.")],
        [N("Quand Allenna décide enfin de sortir, Lineva lui rend sa tunique en échange d’un baiser. Vous gagnez tous trois les serviettes, laissant derrière vous un bassin calme et une assiette parfaitement vide.")],
      ],
      ellipse: [
        [N("Une bataille d’eau vous rassemble au centre du bassin. Vous montrez aux deux femmes comment votre corps veut être touché ; Lineva sourit, Allenna retient chaque indication.")],
        [N("Les tuniques mouillées flottent vers le rebord. Leurs mains suivent vos choix sous l’eau tandis que vos baisers passent de l’une à l’autre.")],
        [N("Vous répondez en caressant Allenna et Lineva, qui s’embrassent devant vous. Les trois corps tournent dans le courant sans jamais former une file d’attente.")],
        [N("Sur les marches, Lineva s’agenouille entre vos jambes, Allenna reste dans votre dos et les reflets commencent à couvrir les gestes précis.")],
        [N("Les places changent encore : Allenna assise, Lineva plus bas, vous penché sur leurs deux corps. La chronique laisse le bassin garder la suite.")],
        [N("Votre plaisir culmine avant le dernier des deux leurs. Elles vous maintiennent à flot puis poursuivent sous vos mains, le rire survivant aux mouvements cachés.")],
        [N("Lineva revient près de votre bouche."), L("Tu sais désormais exactement comment gagner dans l’eau.", "soft")],
        [N("Vous partagez les fruits au bord, encore enlacés. Allenna rougit au souvenir visible dans les remous ; Lineva lui offre la dernière datte pour éviter tout commentaire.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-basin-intersexe-rebord",
    text: "Rebord de pierre — dessiner trois plaisirs sur deux niveaux",
    detail: "Votre corps choisit les gestes ; la pierre et l’eau fixent les angles pendant qu’Allenna et Lineva donnent et reçoivent à chaque hauteur.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous nous montrez la place qui convient à votre corps. Le rebord se chargera de compliquer tout le reste.", "smirk")],
      familiar: [L("Tu nous montres la place qui convient à ton corps. Le rebord se chargera de compliquer tout le reste.", "smirk")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 4,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Vous vous asseyez sur la pierre, Allenna dans l’eau entre vos jambes, Lineva debout derrière. Le lieu trouve une géométrie avant que quiconque ait besoin de la nommer.")],
        [N("Allenna embrasse votre genou ; Lineva votre nuque. Vous tendez les bras vers elles et transformez les deux hauteurs en une seule étreinte.")],
        [N("Vous faites monter Allenna et descendre Lineva. Les baisers changent de direction, les mains restent sur deux corps à la fois et le rebord demeure chaud sous vos cuisses.")],
        [N("Allenna s’allonge sur la pierre. Vous restez près de sa tête, Lineva dans l’eau près de ses jambes ; chacune reçoit une caresse sans que l’autre cesse d’exister.")],
        [N("Vous leur montrez ce qui vous trouble. Une main vient de l’eau, l’autre du rebord ; leurs doigts se rejoignent sur votre ventre avant de reprendre leurs chemins.")],
        [N("Votre plaisir se dénoue au-dessus du bassin, soutenu par les deux niveaux et les deux femmes. Le frisson roule jusqu’à vos pieds immergés.")],
        [N("Lineva pose sa joue sur votre cuisse."), L("Tu viens de résoudre ce rebord mieux que n’importe quelle architecte.", "soft")],
        [N("Vous vous allongez sur les serviettes, Allenna au milieu. Les galettes se cassent mal et les parts restent inégales, ce qui fournit à Lineva une dernière excuse pour voler.")],
      ],
      suggestif: [
        [N("Assis sur le rebord, vous laissez Allenna se placer dans l’eau et Lineva derrière vous. Leurs bouches atteignent votre peau par le haut et par le bas.")],
        [N("Vous ouvrez vos vêtements et guidez leurs mains vers les plaisirs désirés. Elles suivent deux trajectoires nettes, reliées par les baisers qu’elles échangent à votre côté.")],
        [N("Allenna monte sur la pierre ; vous descendez dans le bassin. Lineva reste près d’elle et l’embrasse tandis que vos mains remontent depuis l’eau.")],
        [N("Lineva prend ensuite la place assise, Allenna plus bas, vous à genoux sur la dalle. Les trois corps dessinent une nouvelle position avant que les gestes ne quittent le cadre.")],
        [N("Vous revenez au centre, une jambe dans l’eau et l’autre sur la pierre. Les deux femmes suivent les zones montrées, chacune touchant aussi l’autre.")],
        [N("Votre plaisir culmine entre leurs deux hauteurs. Allenna vous tient depuis le bassin, Lineva depuis le rebord, puis leurs attentions continuent l’une vers l’autre.")],
        [N("Lineva embrasse votre cheville mouillée."), L("Tu as choisi la seule place qui les réunit toutes.", "soft")],
        [N("Allenna étend les serviettes sur la pierre. Vous partagez des fruits, jambes mêlées, tandis que le clapotis efface lentement les traces sur le rebord.")],
      ],
      explicite: [
        [N("Vous vous asseyez sur le rebord chaud, les jambes dans l’eau. Allenna vient entre elles depuis le bassin ; Lineva reste debout derrière votre dos. Vous guidez leurs mains vers les deux plaisirs que vous voulez leur confier, l’un offert à la bouche d’Allenna, l’autre aux doigts de Lineva."), P("Gardez ces hauteurs. Elles me plaisent.")],
        [N("Allenna prend votre sexe extérieur entre ses lèvres depuis l’eau. Lineva vous pénètre de deux doigts par-dessus votre hanche, sa poitrine contre votre dos. Vous tendez une main entre les cuisses de Lineva et l’autre vers Allenna, caressant les deux femmes pendant qu’elles vous stimulent."), L("Le rebord vient de trouver son utilité.", "breathless")],
        [N("La bouche d’Allenna descend plus profondément tandis que les doigts de Lineva se courbent en vous. Les femmes s’embrassent à chaque retrait au niveau de votre cuisse ; leur contact maintient une même cadence à travers votre corps sans effacer la différence des deux gestes."), A("Je sens la main de Lineva vous faire bouger.", "breathless")],
        [N("Vous les arrêtez et faites monter Allenna sur la pierre. Lineva descend dans l’eau entre ses jambes ; sa langue trouve la perle de la guerrière. Vous restez derrière Allenna, deux doigts en elle et votre bouche dans son cou, tandis qu’elle caresse la tête de Lineva."), A("Plus haut avec la langue.", "determined")],
        [N("Allenna jouit assise, ses talons éclaboussant l’eau. Lineva demeure entre ses jambes pendant les contractions ; vos doigts restent en elle et votre autre main masturbe la capitaine depuis le dessus du rebord. Les trois plaisirs restent actifs même au moment où l’un atteint son sommet.")],
        [N("Lineva prend la place d’Allenna sur la pierre. Vous vous tenez dans le bassin, une main entre ses cuisses ; Allenna s’agenouille derrière elle et lui offre ses seins à embrasser. Votre langue et vos doigts font jouir la capitaine, qui se cambre contre son amie."), L("Cette pierre est beaucoup trop efficace.", "shaken")],
        [N("Vous vous rasseyez au bord, Lineva dans l’eau et Allenna sur la dalle à votre côté. La capitaine reprend votre sexe extérieur avec sa bouche ; Allenna glisse deux doigts dans votre ouverture et vous embrasse. Vous caressez Allenna entre les cuisses pendant que sa main suit votre plaisir."), P("Cette fois, allez jusqu’au bout.")],
        [N("Lineva maintient ses lèvres et sa langue ; Allenna accélère ses doigts en vous. Leurs épaules se touchent près de votre hanche et leurs mains se retrouvent sur votre ventre. Vous ne pouvez plus distinguer la chaleur de la pierre de celle qui monte dans votre bassin.")],
        [N("Votre orgasme commence sous les doigts d’Allenna puis gagne le sexe pris dans la bouche de Lineva. Votre corps pulse et se contracte dans les deux directions ; elles restent exactement à leurs niveaux jusqu’à ce que les vagues cessent.")],
        [N("Lineva sort de l’eau pour s’allonger près de vous, sans réclamer le dernier plaisir immédiatement. Allenna garde une main sur votre poitrine ; vous respirez à trois avant que la scène ne reprenne autour d’elle.")],
        [N("La voix de Lineva vient contre votre épaule."), L("Tu as fait du rebord une carte de ton corps. Je saurai la relire.", "soft")],
        [N("Allenna s’allonge, hanches au bord. Lineva la lèche depuis l’eau tandis que vous entrez deux doigts en elle depuis la pierre et offrez votre autre main au sexe de la capitaine. Allenna jouit une seconde fois, prise entre les deux niveaux et les deux personnes.")],
        [N("Vous vous séchez sans quitter la dalle. Les galettes reposent sur une serviette ; Allenna rougit devant les traces humides dessinées sur la pierre, puis accepte le morceau que Lineva pose entre ses lèvres.")],
      ],
      ellipse: [
        [N("Vous choisissez la pierre, Allenna l’eau et Lineva la place derrière vous. Leurs mains suivent les plaisirs que vous leur avez montrés depuis deux hauteurs complémentaires.")],
        [N("Les vêtements humides disparaissent. Allenna reste entre vos jambes, Lineva contre votre dos et leurs bouches se rejoignent près de votre hanche.")],
        [N("Vous faites monter Allenna puis descendre Lineva. Les gestes changent avec les niveaux et le rebord empêche toute scène de sembler transportable ailleurs.")],
        [N("Lineva prend ensuite la place assise. Allenna reste dans l’eau, vous à genoux sur la pierre, et les trois corps demeurent reliés jusqu’au fondu.")],
        [N("Vous revenez au centre, jambes partagées entre la dalle et le bassin. La chronique laisse leurs attentions suivre les chemins indiqués sur votre corps.")],
        [N("Votre plaisir culmine avant le dernier des leurs. Le rebord soutient encore les changements qui suivent, chacun construit par une nouvelle différence de hauteur.")],
        [N("Lineva pose un baiser contre votre cuisse."), L("Tu as trouvé une place qui n’appartient qu’à toi.", "soft")],
        [N("Allenna déplie les serviettes. Vous mangez allongés sur la pierre, pieds dans l’eau, et laissez les galettes s’émietter au milieu des jambes entremêlées.")],
      ],
    },
  },
  {
    id: "group-date-allenna-lineva-basin-intersexe-alcove",
    text: "Alcôve chaude — confier votre corps à l’élan d’Allenna",
    detail: "Allenna accueille votre corps sans le réduire à une catégorie, puis transforme sa timidité en une conduite précise qui serre les trois personnes dans son refuge.",
    manual: true,
    linevaAddress: {
      firstTime: [L("Vous pouvez tout montrer ici, sans avoir à simplifier quoi que ce soit. Allenna a choisi un endroit qui sait garder les nuances.", "soft")],
      familiar: [L("Tu peux tout montrer ici, sans avoir à simplifier quoi que ce soit. Allenna a choisi un endroit qui sait garder les nuances.", "soft")],
    },
    progression: {
      playerClimaxChapter: { tendre: 5, suggestif: 5, explicite: 9, ellipse: 5 },
      linevaFirstTuChapter: { tendre: 6, suggestif: 6, explicite: 10, ellipse: 6 },
      revealChapter: 5,
      postOrgasmChapter: 11,
    },
    chapters: {
      tendre: [
        [N("Allenna ouvre son alcôve et s’assied au milieu. Vous prenez une place, Lineva l’autre ; les trois épaules se touchent avant même que le rideau ait fini de retomber.")],
        [N("Vous montrez à Allenna la façon dont vous aimez être tenu. Elle reproduit le geste sans question superflue ; Lineva pose simplement sa main sur la sienne.")],
        [N("Le premier baiser d’Allenna est timide. Le second, donné à Lineva au-dessus de votre épaule, l’est moins ; le troisième vous attire contre toute sa poitrine.")],
        [N("Allongés sur les coussins, vous gardez Allenna entre les deux corps. Elle accepte les regards, puis pose ses propres mains sur les peaux offertes.")],
        [N("Elle inverse soudain les places et vous attire au centre. Lineva rit de surprise ; Allenna répond en l’embrassant plutôt qu’en s’excusant.")],
        [N("Votre plaisir arrive dans une lente étreinte, suivi par leurs deux souffles. L’étroitesse du lieu transforme chaque frisson en mouvement partagé.")],
        [N("Lineva caresse votre tempe."), L("Tu viens d’être accueilli exactement comme tu es. Je crois qu’elle en est fière.", "soft")],
        [N("Allenna partage une couverture et les quartiers d’orange. Sa rougeur revient, mais son bras demeure autour de vous et ses jambes contre celles de Lineva.")],
      ],
      suggestif: [
        [N("Le rideau isole l’alcôve. Allenna vous installe entre elle et Lineva, encore intimidée par le corps que vous lui montrez mais déjà attentive aux gestes que vous choisissez.")],
        [N("Vous guidez sa main. Elle suit une zone, puis une autre, sans les hiérarchiser ; Lineva embrasse sa nuque et regarde sa confiance grandir.")],
        [N("Les vêtements quittent les trois corps. Allenna rougit sous vos yeux, puis vous regarde avec la même franchise et attire Lineva dans un baiser.")],
        [N("Elle vous allonge, place la capitaine près de votre bouche et s’agenouille entre vos jambes. L’initiative surprend Lineva assez longtemps pour lui faire perdre une plaisanterie.")],
        [N("Les gestes deviennent trop intimes pour le cadre, mais la chaîne reste nette : Allenna vous touche, vous embrassez Lineva, Lineva caresse Allenna.")],
        [N("Votre plaisir culmine sous l’attention d’Allenna. Elle soutient vos hanches, Lineva votre visage, puis les deux femmes restent ensemble au-dessus de vous.")],
        [N("Lineva sourit après le sommet."), L("Tu as vu ? Elle vient de décider pour son désir, pas pour ton corps.", "soft")],
        [N("Allenna se glisse au milieu sous la couverture. Elle distribue les fruits avec une solennité bientôt détruite par un baiser simultané sur chaque joue.")],
      ],
      explicite: [
        [N("Allenna referme le rideau sur son refuge chaud. Vous vous déshabillez devant elle et lui montrez sans détour les parties de votre corps que vous voulez offrir ce soir. Elle rougit, non devant leur forme, mais devant la confiance du geste ; Lineva reste dans son dos, une main paisible à sa taille."), A("Je veux apprendre ce qui vous plaît ici, pas ailleurs.", "troubled")],
        [N("Vous placez la main d’Allenna sur votre sexe extérieur, celle de Lineva à votre ouverture. Elles commencent lentement sur les coussins, leurs bras croisés autour de votre bassin. Vous les embrassez l’une après l’autre ; Allenna tourne ensuite la tête pour prendre la bouche de Lineva."), L("Elle n’hésite déjà plus beaucoup.", "soft")],
        [N("Allenna vous fait asseoir contre la pierre et retire sa propre tunique. Vous embrassez ses seins pendant que Lineva les caresse depuis l’arrière. Sa rougeur descend sur sa poitrine ; ses mains restent pourtant fermes lorsqu’elle guide votre bouche d’un sein à l’autre."), A("Continuez à me regarder.", "determined")],
        [N("Elle vous allonge et place Lineva à califourchon près de votre visage. Allenna s’agenouille entre vos jambes, prend votre sexe extérieur dans sa bouche et glisse deux doigts dans votre ouverture. Vous léchez Lineva au-dessus de vous ; la capitaine caresse les seins d’Allenna par-dessus votre ventre."), L("Cette disposition est entièrement son idée.", "breathless")],
        [N("La langue d’Allenna et ses doigts suivent deux rythmes distincts, tous deux appris de vos gestes. Vous faites entrer deux doigts en Lineva pendant que votre bouche reste sur sa perle. Lineva se penche pour embrasser Allenna, les trois corps repliés dans la largeur exacte de l’alcôve."), P("Ne changez rien.")],
        [N("Lineva jouit contre votre bouche, ses doigts se crispant sur l’épaule d’Allenna. Cette dernière poursuit votre plaisir puis s’arrête elle-même avant le sommet. Elle retire ses doigts, relève la tête et vous regarde avec une décision qui ne demande plus à être rassurée."), A("Je veux conduire la suite.", "determined")],
        [N("Allenna s’allonge entre vous et ouvre les jambes. Lineva se place sur son côté et lui offre sa bouche ; vous léchez sa perle pendant que deux de vos doigts entrent en elle. Allenna vous caresse le sexe extérieur d’une main et l’ouverture de l’autre, donnant pendant qu’elle reçoit."), A("Plus profondément en moi.", "breathless")],
        [N("Son orgasme arrive sous votre langue et vos doigts, amplifié par le baiser de Lineva. Elle se cambre, puis vous attire immédiatement au-dessus d’elle. Plutôt que de s’effacer après avoir joui, elle reprend votre corps dans ses deux mains et appelle Lineva contre votre dos."), L("Elle avait vraiment tout prévu.", "shaken")],
        [N("Vous vous allongez sur le côté entre elles. Allenna reprend votre sexe extérieur avec sa bouche ; Lineva entre deux doigts dans votre ouverture depuis l’arrière et frotte votre plaisir de l’autre main. Leurs visages se rejoignent près de votre hanche, leurs langues et leurs doigts coordonnés par vos réactions."), P("Je vais jouir.")],
        [N("Votre orgasme traverse les deux plaisirs que vous leur avez confiés. Allenna garde votre sexe dans sa bouche pendant les pulsations ; Lineva reste en vous jusqu’à la fin des contractions. Elles ralentissent séparément et vous laissent reprendre souffle au milieu de leurs corps.")],
        [N("Lineva se glisse près de votre visage."), L("Tu n’as simplifié aucune partie de toi. Et nous n’en avons perdu aucune.", "soft")],
        [N("Allenna attire Lineva face à elle. Vous les caressez toutes deux entre les cuisses pendant qu’elles frottent leurs sexes l’un contre l’autre sur le coussin étroit. Allenna jouit la dernière, sa bouche ouverte sous celle de Lineva, son initiative conservée jusqu’au bout."), A("Je voulais vraiment tout cela.", "shaken")],
        [N("Sous la couverture, Allenna redevient légèrement rouge en partageant une orange. Vous embrassez un coin de sa bouche, Lineva l’autre. Le rideau reste fermé et son refuge contient désormais trois respirations paisibles.")],
      ],
      ellipse: [
        [N("Allenna vous laisse entrer dans son alcôve et accueille le corps que vous lui montrez sans tenter de le réduire à une habitude. Lineva se tient près d’elle.")],
        [N("Vous guidez leurs mains vers les plaisirs désirés. Allenna suit, rougit, puis attire Lineva dans un baiser sans lâcher votre peau.")],
        [N("Les vêtements disparaissent sur les coussins. Vous embrassez Allenna tandis que Lineva reste dans son dos, leurs mains prenant des chemins précis sur vous.")],
        [N("Allenna inverse les places : vous allongé, Lineva près de votre bouche, elle-même entre vos jambes. Le rideau conserve la suite de son initiative.")],
        [N("Les ombres montrent encore Allenna recevant vos gestes puis vous ramenant au centre, Lineva serrée contre votre dos. Aucune silhouette ne quitte le cercle.")],
        [N("Votre plaisir culmine entre les deux femmes avant le dernier des leurs. Allenna continue de conduire jusqu’à ce que trois souffles retrouvent enfin leur calme.")],
        [N("Lineva embrasse votre front."), L("Tu as confié tout ton corps au bon silence.", "soft")],
        [N("Allenna partage les fruits et une couverture. Elle rougit devant le sourire de Lineva, puis choisit de répondre par un baiser plutôt que par une explication.")],
      ],
    },
  },
];

export const LINEVA_ALLENNA_BASIN_ROUTES: Record<PlayerSex, GroupIntimacyRoute[]> = {
  femme: BASIN_FEMME,
  homme: BASIN_HOMME,
  intersexe: BASIN_INTERSEXE,
};
