export const SPOT_MUSIC: Record<string, string> = {
  "algratal-streets": "algratal",
  "algratal-market": "algratal",
  "algratal-palace-audience": "algratal",
  "algratal-palace-council": "algratal",
  "algratal-music-room": "algratal",
  "algratal-ballroom": "algratal",
  "algratal-palace-quarters": "algratal",
  "algratal-catacombs": "algratal",

  "miraldas-dome": "miraldas",
  "miraldas-atelier": "miraldas",
  "miraldas-archives": "miraldas",
  "miraldas-hylee-glade": "miraldas",
  "miraldas-purple-woods": "miraldas",
  "miraldas-observatory": "miraldas",
  "miraldas-quarters": "miraldas",

  "forbidden-threshold": "forbidden",
  "forbidden-crossroads": "forbidden",
  "forbidden-sanctuary": "forbidden",
  "forbidden-ruins": "forbidden",

  "forthaven-harbor": "forthaven-lullaby",
  "forthaven-ramparts": "forthaven-lullaby",
  "forthaven-war-room": "forthaven-lullaby",
  "forthaven-memorial": "forthaven-lullaby",
  "forthaven-quarters": "forthaven-lullaby",

  "akuhn-gates": "akuhn",
  "akuhn-palace-exterior": "akuhn",
  "akuhn-throne-room": "akuhn",
  "akuhn-archives": "akuhn",
  "akuhn-war-room": "akuhn",
  "akuhn-music-room": "akuhn",
  "akuhn-terrace": "akuhn",

  "tzekarun-gates": "tzekarun-ost",
  "tzekarun-workshop": "tzekarun-ost",
  "tzekarun-archive": "tzekarun-ost",

  "forestier-inn": "forestier-ost",
  "echo-clearing": "echo-clearing-ost",
  "river-halt": "iriana-valurn-confessions",
  "imperial-road": "valurn-memory",
  "obsidian-waystation": "dune-relay",
};

export const MUSIC_LABELS: Record<string, string> = {
  algratal: "Le cœur de l’Empire, Al’Gratal",
  "capital-market": "Shopping dans la capitale",
  "iriana-entrance": "Entrée d’Iriana",
  "imperial-lament": "La Complainte impériale",
  "imperial-lament-instrumental": "La Complainte impériale — instrumental",
  "chosen-ball": "Le Bal des Élus",
  "marble-moon": "Clair de lune sur le marbre",
  catacombs: "Les Catacombes du Croissant",
  miraldas: "Thème de Mir’Aldas",
  "mage-city": "La cité des mages",
  "saidin-duel": "Le duel de Saidin",
  training: "Entraînement",
  "wild-calm": "Wild Calm",
  "two-stars-night": "Une nuit entre deux étoiles",
  "confessions-wind": "Vent et confessions",
  forbidden: "Les brumes de la Forêt Interdite",
  "naiah-duel-one": "Le duel de Naïah — premier mouvement",
  "naiah-duel-two": "Le duel de Naïah — second mouvement",
  "shadow-combat": "Combat des Ombres",
  "storm-without-you": "Storm Without You",
  "forthaven-lullaby": "Forthaven Lullaby",
  "dawn-training": "Entraînement à l’aube",
  fratricide: "Confrontation fratricide",
  "draven-daughter": "Draven, père et fille",
  ending: "L’heure suspendue",
  akuhn: "Étranger à Akuhn’Nabad",
  infiltration: "Infiltration",
  "amanea-black-queen": "Amanea, Reine Noire",
  captive: "Captif",
  "infernal-trade": "Infernal Trade",
  "bellirith-encounter": "Rencontre avec Bellirith",
  "unbroken-ice": "Une glace à jamais brisée",
  tension: "Tension",
  "tzekarun-ost": "Tzekar’ûn",
  unborn: "The Unborn",
  "valurn-lullaby": "La berceuse de Valurn",
  "hylee-remerii-ball": "Le Bal des Élus — Hylee et Remerii",
  "forestier-ost": "Taverne du Forestier",
  "star-night-soft": "Une nuit sous tes étoiles",
  "echo-clearing-ost": "Wild Calm",
  "iriana-valurn-confessions": "Un vent de confessions — Iriana et Valurn",
  "valurn-memory": "Mémoire de Valurn",
  "midnight-waltz": "Midnight Waltz",
  "dune-relay": "Les Tzekarii",
  intimate: "Une nuit sous tes étoiles — intime",
  menu: "Le grimoire de Sylvinia",
  title: "Le portail emprunté",
};

export function musicForContext(spotId: string, context?: { intimacy?: boolean; prologue?: boolean }) {
  if (context?.intimacy) return "intimate";
  if (context?.prologue) return "menu";
  return SPOT_MUSIC[spotId] || "title";
}
