import type { ChoiceData, DialogueLine, Effects, StatKey } from "./game-data";
import type { KnowledgeEntry, SecretConversation, SecretTier } from "./heritages-data";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const A = (text: string, mood = "smirk"): DialogueLine => ({ speaker: "Naïah", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });
const Q = (
  id: string,
  text: string,
  stat: StatKey,
  response: DialogueLine[],
  effects: Effects,
  requiresKnowledge?: string[],
): ChoiceData => ({ id, text, stat, response, effects: { ...effects, stats: { ...(effects.stats || {}), [stat]: 1 } }, requiresKnowledge });
const secret = (
  id: string,
  title: string,
  tier: SecretTier,
  reveals: string[],
  intro: DialogueLine[],
  choices: ChoiceData[],
): SecretConversation => ({
  id,
  title,
  character: "naiah",
  tier,
  reveals,
  intro,
  choices,
  locations: ["forbidden"],
});

export const NAIAH_KNOWLEDGE: KnowledgeEntry[] = [
  {
    id: "knows_naiah_hylee_nights",
    title: "Les nuits après le service",
    summary: "Quand Hylee travaillait encore à l'auberge, Naïah la retrouvait après le dernier service. Elles parlaient des heures, inventaient des jeux et dansaient loin des regards jusqu'à ce que la nuit leur donne l'impression d'être hors du monde.",
    people: ["naiah", "hylee"],
  },
  {
    id: "knows_naiah_exile",
    title: "Deux héritières, aucune sœur",
    summary: "Naïah envie ce qu'Allenna a reçu d'Amanea et souffre de ce contraste. Sa rancœur n'efface pourtant ni le respect qu'elle porte aux capacités d'Allenna, ni une rivalité qui existe aussi par leurs propres choix.",
    people: ["naiah", "allenna", "amanea"],
  },
  {
    id: "knows_naiah_surpass_amanea",
    title: "La preuve cachée dans la forêt",
    summary: "Naïah est restée près d'Akuhn’Nabad pour observer Amanea et devenir assez puissante pour prouver que sa grandeur ne viendrait ni d'elle ni de son rejet. Cette preuve reste encore adressée à la mère qu'elle prétend avoir cessé d'attendre.",
    people: ["naiah", "amanea"],
  },
  {
    id: "knows_naiah_maternal_rejection",
    title: "Pourquoi aucun regard ?",
    summary: "Naïah ne comprend pas pourquoi Amanea évite jusqu'à son regard alors qu'elle affronte ouvertement ses ennemis. Elle ignore la cause réelle et refuse qu'une explication inventée soit choisie à sa place.",
    people: ["naiah", "amanea"],
  },
];

export const NAIAH_CONFIDENCES: SecretConversation[] = [
  secret("secret-naiah-hylee-nights", "Les nuits après le service", 20, ["knows_naiah_hylee_nights"], [
    N("Naïah vous conduit derrière un tronc fendu où l'écorce forme une banquette étroite. Elle s'y installe, tape deux fois la place voisine, puis fait apparaître au loin la silhouette d'une auberge sans fenêtre éclairée."),
    A("Hylee sortait par derrière après le dernier service. Elle prétendait qu'elle venait seulement prendre l'air. J'avais l'élégance de ne pas relever ce mensonge."),
    P("Tu l'attendais ?"),
    A("Jamais. J'arrivais par hasard les mêmes nuits, au même endroit, avec trois nouveaux jeux préparés. Le destin travaillait énormément."),
    N("Deux silhouettes de brume s'assoient près du mur illusoire. Elles parlent, d'abord avec de grands gestes, puis presque sans bouger."),
    A("Elle racontait les clients impossibles, le travail qui ne finissait pas, les jours où elle avait dû cacher sa magie jusque dans sa manière de respirer. Moi, je racontais des monstres qui n'existaient qu'à moitié."),
    P("Elle savait quand tu mentais ?"),
    A("Toujours. Elle me laissait seulement choisir le moment où l'histoire redevenait vraie."),
    N("L'illusion change. Les deux silhouettes dansent quelques pas maladroits sur une musique absente, puis s'effondrent contre le mur en riant."),
    A("Pendant quelques heures, ni l'auberge ni la forêt ne nous réclamait quoi que ce soit. C'était très imprudent. J'aimais beaucoup."),
    P("Pourquoi as-tu cessé de venir ?"),
    N("Naïah regarde la silhouette d'Hylee attendre une nuit de plus. Elle fait disparaître l'auberge avant de répondre."),
    A("Parce que j'ai cru qu'un départ choisi ferait moins mal qu'une nuit où elle ne sortirait plus. C'était un calcul brillant et entièrement faux.", "thinking"),
  ], [
    Q("sna20-a", "Lui proposer de reprendre l'un de leurs jeux avec Hylee, sans rejouer la nuit à l'identique.", "audace", [
      A("Pas une reconstitution émouvante ? Pas de musique triste pendant que je demande pardon sous la pluie ?"),
      P("Un nouveau jeu. Avec des règles que vous pourrez toutes les deux contester."),
      N("Naïah fait apparaître trois cailloux, en cache deux et glisse ostensiblement le troisième dans sa manche."),
      A("Très bien. Mais tu arbitreras. Hylee prétend encore que changer les règles au milieu constitue de la triche."),
      P("Elle a raison."),
      A("Tu viens de perdre ton impartialité avant même l'invitation."),
    ], { affection: 5, trust: 3 }),
    Q("sna20-r", "Reconnaître ce que ces nuits leur donnaient sans les réduire à leur tristesse.", "resonance", [
      P("Vous n'étiez pas seulement deux personnes malheureuses qui se consolaient. Vous vous amusiez réellement."),
      N("Naïah relève la tête, surprise que vous n'ayez pas choisi la partie la plus douloureuse du souvenir."),
      A("Hylee dansait très mal."),
      P("Et toi ?"),
      A("Avec une perfection offensante. C'est ma version, elle est donc officielle."),
      N("Elle refait apparaître un seul pas : Hylee lui écrase le pied, Naïah exagère une agonie et toutes deux rient avant la chute."),
      A("Oui. C'était heureux aussi. Garde surtout cette partie-là."),
    ], { trust: 7, affection: 3 }),
    Q("sna20-s", "Ne pas chercher à expliquer son départ à la place d'Hylee et rester dans le souvenir qu'elle a choisi.", "sangFroid", [
      N("Vous ne lui dites pas qu'Hylee comprendrait, pardonnerait ou attend encore. Naïah surveille longtemps la phrase qui ne vient pas."),
      A("Tu pourrais rendre tout cela très simple avec une promesse concernant quelqu'un d'autre."),
      P("Ce serait la promesse d'Hylee, pas la mienne."),
      N("La banquette d'écorce s'élargit juste assez pour que vos épaules cessent de se heurter."),
      A("Réponse correcte. Ennuyeuse, mais correcte."),
      P("Tu veux recommencer le souvenir ?"),
      A("Non. Reste seulement jusqu'à ce que l'auberge disparaisse toute seule."),
    ], { trust: 8, affection: 2 }),
  ]),

  secret("secret-naiah-exile", "Deux héritières, aucune sœur", 40, ["knows_naiah_exile"], [
    N("Naïah répare un piège neutralisé avec une précision chirurgicale. Une note d'Allenna est attachée à la corde coupée : « Trop visible. Trop proche du passage civil. » Naïah a souligné le premier reproche et soigneusement laissé le second intact."),
    A("Même ses insultes se tiennent au garde-à-vous."),
    P("Elle avait raison ?"),
    A("La pertinence est une circonstance aggravante."),
    N("Naïah déplace le mécanisme loin du passage, remplace la corde par un fil discret, puis reproduit l'écriture d'Allenna pour ajouter : « Nettement mieux. Je déteste cela. »"),
    A("Elle a reçu la place près d'Amanea, son nom, sa confiance et le droit d'être protégée sans devenir un secret honteux. Moi, j'ai reçu une frontière."),
    P("Et pourtant tu gardes ses corrections."),
    A("Allenna est brillante. Cela la rend plus insupportable, pas moins."),
    N("Le piège se referme soudain sur la manche de Naïah. Elle baisse les yeux vers le fil qu'elle vient elle-même de tendre."),
    A("Tu n'as rien vu."),
    P("Je vois surtout qu'elle savait où tu poserais la main."),
    N("Naïah libère sa manche sans détruire la note. Son expression passe du rire à la colère, puis à quelque chose de plus ancien qu'elle efface aussitôt."),
    A("Elle me connaît assez pour gagner parfois. Pas assez pour décider ce que mon exil doit faire de moi."),
  ], [
    Q("sna40-l", "Distinguer ce qu'elle envie chez Allenna de ce qu'elle reconnaît en elle.", "lucidite", [
      P("Tu envies la place qu'elle a reçue. Tu respectes aussi la femme qui a appris à l'occuper."),
      A("Tu rends ma haine beaucoup trop organisée."),
      P("Elle ne l'est pas. C'est précisément pour cela que les deux peuvent être vrais."),
      N("Naïah relit la note et corrige une boucle dans l'écriture imitée."),
      A("Allenna protège sa cité, lit un terrain en un regard et possède l'imagination d'une porte verrouillée. Je pourrais l'admirer si elle avait la décence d'être moins elle-même."),
      P("Cela ressemble déjà beaucoup à de l'admiration."),
      A("Je vais replacer le piège sur le passage civil."),
      P("Non."),
      A("Bien. Au moins une personne ici sait rester sérieuse."),
    ], { trust: 8, affection: 2 }),
    Q("sna40-r", "Remarquer que garder la note est aussi une façon de conserver un échange entre elles.", "resonance", [
      N("Naïah referme aussitôt les doigts sur le papier."),
      A("C'est une pièce à conviction."),
      P("Tu aurais pu mémoriser les deux phrases et la brûler."),
      A("J'aurais pu. Son écriture est laide ; le feu aurait apprécié."),
      N("Elle range pourtant la note dans une poche intérieure, avec plusieurs plis plus anciens dont vous apercevez les bords."),
      A("Nous savons nous parler surtout quand aucune de nous n'est là pour répondre. C'est une habitude familiale très élégante."),
      P("Tu voudrais qu'elle réponde ?"),
      A("Je voudrais choisir moi-même quand je déteste la réponse."),
    ], { trust: 9, affection: 3 }),
    Q("sna40-a", "Ajouter une correction à la note et les provoquer toutes les deux.", "audace", [
      P("« Déplacement correct. Signature excessivement satisfaite. »"),
      N("Naïah vous arrache presque le charbon des mains, relit la phrase et laisse échapper un rire."),
      A("Allenna va croire que j'ai demandé de l'aide."),
      P("Tu peux retirer mon ajout."),
      A("Certainement pas. Je veux voir combien de minutes elle mettra à reconnaître une troisième écriture."),
      N("Elle suspend la note au nouveau piège, bien visible cette fois uniquement pour la commandante qui saura où regarder."),
      A("Si elle te fait arrêter, je nierai t'avoir rencontré·e."),
    ], { affection: 6, trust: 3 }),
  ]),

  secret("secret-naiah-surpass", "Ce que la forêt doit prouver", 60, ["knows_naiah_surpass_amanea"], [
    N("Naïah est assise au sommet d'une pierre, entourée de plans dessinés directement dans la brume : routes d'Akuhn’Nabad, lignes de patrouille, points où les protections de la forêt rencontrent celles de la cité."),
    P("Tu observes leur frontière depuis longtemps."),
    A("J'observe beaucoup de choses. C'est moins humiliant que d'admettre lesquelles m'intéressent."),
    N("Une silhouette d'Amanea traverse l'un des plans, minuscule et lointaine. Naïah la suit du regard sans la faire disparaître."),
    A("Je suis restée ici pour comprendre. Pour la regarder bâtir son royaume, mesurer ses défenses et devenir assez forte pour que personne ne puisse dire que je lui dois ma grandeur."),
    P("Ni que son rejet t'a rendue forte ?"),
    N("La brume se déchire net. Naïah vous fixe, puis reforme lentement la carte."),
    A("Ni grâce à elle. Ni à cause d'elle. Quelque chose qui m'appartienne tellement qu'elle ne puisse même pas en devenir l'absence."),
    P("Et entre-temps, tu entretiens les chemins qui protègent sa cité."),
    A("Ma forêt. Mes chemins. Les voyageurs ont simplement l'excellente idée de les utiliser."),
    N("Elle déplace une protection pour couvrir un passage venant d'Akuhn’Nabad, puis l'efface du plan avant de vous laisser le commenter."),
    A("Je veux encore qu'elle sache que j'ai survécu. C'est la partie la moins digne du plan."),
  ], [
    Q("sna60-l", "Séparer ce qu'elle construit de la personne à laquelle elle veut encore le prouver.", "lucidite", [
      P("Le réseau protège déjà des gens qui ignorent ton nom. Il existe avant qu'Amanea le reconnaisse, et même si elle ne le fait jamais."),
      A("Tu as le don de rendre mes grandes obsessions logistiquement inutiles."),
      P("Pas inutiles. Mal adressées."),
      N("Naïah rouvre le passage qu'elle venait d'effacer et ajoute trois points de surveillance."),
      A("Je peux continuer de vouloir qu'elle regarde et refuser que ce regard mesure tout."),
      P("Oui."),
      A("C'est beaucoup moins théâtral qu'une victoire absolue."),
      P("Mais plus difficile."),
      A("Voilà enfin un argument séduisant."),
      N("Elle couronne le passage d'un point lumineux. Le point se met aussitôt à fuir sur la carte, poursuivi par trois sentinelles minuscules qui réclament ses papiers."),
      A("Regarde. Mon œuvre autonome vient de commettre un délit frontalier. Elle a déjà très bien appris de moi.", "laugh"),
    ], { trust: 10, affection: 3 }),
    Q("sna60-r", "Reconnaître que son désir d'être vue n'annule pas l'autonomie de ce qu'elle accomplit.", "resonance", [
      P("Tu peux vouloir qu'elle sache. Cela ne transforme pas chaque geste en message pour elle."),
      N("Naïah contemple la silhouette lointaine d'Amanea, puis le réseau qu'elle a dessiné tout autour sans jamais la toucher."),
      A("J'aimerais une réponse plus propre : ne plus rien attendre, ne plus rien ressentir, gagner définitivement."),
      P("Ce ne serait pas plus vrai."),
      A("Non."),
      N("Elle souffle sur la silhouette. Seule cette image disparaît ; les routes restent."),
      A("Alors garde les deux vérités. Je construis pour moi. Et j'espère encore, certains jours, qu'elle le voie."),
      N("Deux pancartes surgissent au-dessus du réseau : « POUR MOI » et « QU'ELLE REGARDE ». Elles se heurtent, se volent leurs flèches puis finissent par indiquer le même chemin."),
      A("Elles vont se quereller longtemps. Je refuse de payer un médiateur.", "smirk"),
    ], { trust: 11, affection: 4 }),
    Q("sna60-a", "Lui demander de vous montrer l'œuvre dont elle est la plus fière, sans mentionner Amanea.", "audace", [
      N("Naïah cherche aussitôt une réponse brillante, puis désigne un petit nœud perdu au bord de la carte."),
      A("Celui-ci. Il ramène les enfants égarés au même arbre, avec assez de baies pour qu'ils attendent sans repartir."),
      P("Personne ne sait que c'est toi."),
      A("Les enfants savent qu'un arbre donne des baies. C'est une meilleure histoire pour eux."),
      N("Elle agrandit le point jusqu'à faire apparaître chaque racine et chaque détour."),
      A("Tu voulais voir ce qui m'appartient ? Regarde bien. Je ne le montre presque jamais."),
    ], { affection: 6, trust: 5 }),
  ]),

  secret("secret-naiah-look", "Ce qu'elle ne regarde jamais", 80, ["knows_naiah_maternal_rejection"], [
    N("La brume de Naïah cesse de décorer la clairière. Aucun double, aucun animal violet, aucune couronne ne vient modifier son visage."),
    A("Ne dis rien. J'essaie une expérience dangereuse : terminer une pensée avant d'étudier ta réponse.", "neutral"),
    N("Elle compte trois respirations et déteste visiblement chacune d'elles."),
    A("Je comprends une condamnation. Une guerre. Même une mère qui me hait. La haine regarde ce qu'elle frappe."),
    P("Mais pas son absence de regard."),
    A("Elle répond à ses ennemis. Elle observe ses prisonniers. Avec moi, elle sait toujours où ne pas tourner la tête."),
    N("Naïah arrache un brin d'herbe et le déchire en morceaux égaux."),
    A("J'ai essayé la menace, l'humiliation, la puissance et le silence. Rien. Je pourrais inventer mille raisons ; aucune ne deviendrait vraie parce qu'elle me blesse correctement."),
    N("Sa voix se réduit à mesure que la clairière devient plus dangereusement calme."),
    A("Alors je te demande une chose : si tu trouves un jour une réponse, ne décide pas à ma place que je suis trop fragile pour l'entendre."),
  ], [
    Q("sna80-s", "Refuser de lui offrir une certitude que vous ne possédez pas.", "sangFroid", [
      P("Je ne sais pas pourquoi elle fait cela."),
      A("Réponse décevante."),
      P("Je pourrais en fabriquer une plus douce. Elle resterait fausse."),
      N("Naïah cesse de déchirer l'herbe, sans en prendre une autre."),
      P("Son silence ne prouve rien de monstrueux en toi. Il ne prouve pas non plus ce qu'elle ressent."),
      A("Deux ignorances et aucune consolation. Tu t'es surpassé·e."),
      P("Tu m'as demandé de ne pas choisir l'histoire à ta place."),
      N("Elle frappe la terre près d'elle du plat de la main."),
      A("Assieds-toi. Tu peux au moins rendre l'ignorance moins solitaire."),
      N("Un banc de brume apparaît sous l'inscription « Comité des réponses insuffisantes ». Naïah y ajoute votre nom, puis dessine une pâtisserie au titre de budget de fonctionnement."),
      A("Le comité se réunit sans ordre du jour. C'est presque reposant.", "smirk"),
    ], { trust: 12, affection: 3 }),
    Q("sna80-l", "Dire seulement que l'indifférence n'explique pas tout ce que vous avez observé.", "lucidite", [
      P("Je n'ai pas la réponse. Mais l'indifférence simple ne suffit pas à expliquer tout ce que j'ai vu."),
      A("Qu'as-tu vu ?", "angry"),
      P("Une histoire publique qui prétend que tu ne comptes pas, et trop de précautions autour de ton nom pour que cette histoire soit complète. Rien de plus certain."),
      N("La brume revient d'un coup autour de ses doigts. Naïah la maintient loin de vous."),
      A("Tu me donnes une fissure sans inventer ce qu'il y a derrière."),
      P("Je ne sais pas ce qu'il y a derrière."),
      A("Bien. Si tu le découvres, tu viens d'abord me parler. Tu n'emploies pas la réponse pour agir dans mon dos."),
      P("D'accord."),
      A("Je vais détester attendre. Je préfère encore cela à un joli mensonge."),
      N("Un scarabée coiffé d'une minuscule visière inspecte la fissure imaginaire, note quelque chose et vous présente un formulaire entièrement blanc."),
      A("L'inspecteur confirme : le mystère reste mystérieux. Enfin un fonctionnaire compétent.", "smirk"),
    ], { trust: 12, affection: 2 }, ["knows_amanea_naiah_pain"]),
    Q("sna80-a", "Promettre une conversation avant toute utilisation future de cette vérité.", "audace", [
      P("Si j'apprends quelque chose, je te le dirai avant de m'en servir. Même si cela fait mal. Même si tu me demandes ensuite de ne rien faire."),
      A("Et si je prends une mauvaise décision ?"),
      P("Elle restera la tienne. Je pourrai la contester devant toi, pas la remplacer derrière ton dos."),
      N("Le silence de la forêt se relâche. Naïah vous saisit deux doigts, geste minuscule qu'aucune illusion ne vient agrandir."),
      A("Tu viens de promettre une dispute future avec une assurance très séduisante."),
      P("Je m'entraîne."),
      A("Alors reste. J'aimerais vérifier si ta bravoure survit à mon silence."),
      N("Un mannequin de brume portant votre visage lève une pancarte : « ARGUMENT FAIBLE ». Naïah lui lance le dernier morceau d'herbe ; il s'effondre avec une dignité offensée."),
      A("Première objection rejetée. La prochaine devra apporter ses propres biscuits.", "laugh"),
    ], { trust: 10, affection: 5 }),
  ]),
];
