import type { ChoiceData, DialogueLine, Effects, RouteScene, StatKey } from "./game-data";

// Arc personnel de Naïah · Acte I.
// Le protagoniste observe, transporte et décide ; il ne remplace jamais Naïah
// dans l'entretien des protections magiques de la Forêt Interdite.
const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const A = (text: string, mood = "smirk"): DialogueLine => ({ speaker: "Naïah", text, mood });
const P = (text: string): DialogueLine => ({ speaker: "{player}", text });
const L = (speaker: string, text: string): DialogueLine => ({ speaker, text });
const Q = (id: string, text: string, stat: StatKey, response: DialogueLine[], effects: Effects): ChoiceData => ({
  id,
  text,
  stat,
  response,
  effects: { ...effects, stats: { ...(effects.stats || {}), [stat]: 1 } },
});
const scene = (
  stage: number,
  dayMin: number,
  title: string,
  background: string,
  mood: string,
  intro: DialogueLine[],
  choices: ChoiceData[],
): RouteScene => ({
  id: `naiah-${stage}`,
  character: "naiah",
  stage,
  dayMin,
  title,
  location: "forbidden",
  background,
  mood,
  intro,
  choices,
});

export const NAIAH_ROUTES: RouteScene[] = [
  scene(0, 4, "Le jeu des branches", "forbidden_forest", "smirk", [
    N("Une branche frappe trois fois votre épaule. Quand vous vous retournez, elle porte un ruban violet noué comme une invitation et pointe vers un sentier qui n'existait pas une seconde plus tôt."),
    N("Le chemin vous conduit à une clairière où trois Naïah vous attendent. La première mange une pomme, la deuxième est assise dans le vide et la troisième inspecte une petite marque grise taillée dans l'écorce."),
    A("Tu es venu·e. J'avais parié contre le hêtre. Il te trouvait prudent·e ; je te trouvais curieux·se."),
    P("Et la gagnante obtient quoi ?"),
    A("Toi, pendant un jeu. Le hêtre réclamait seulement de l'eau, il manque d'ambition."),
    N("D'un geste, elle fait surgir trois sentiers. Au fond de chacun, une nouvelle silhouette vous adresse exactement le même sourire."),
    A("Retrouve la vraie avant que les branches ne te ramènent ici. Tu peux tricher, mentir et sortir du chemin. J'ai donné les mêmes droits à la forêt."),
    P("Pourquoi cette clairière ?"),
    N("Son regard passe une seconde fois sur la marque grise. Elle la couvre aussitôt d'une feuille qui vient d'apparaître."),
    A("Parce qu'elle est jolie. Et parce que je refuse les questions raisonnables avant le premier piège."),
    N("Elle tombe en arrière. Les trois Naïah disparaissent avant de toucher le sol ; les sentiers, eux, se mettent à bouger."),
  ], [
    Q("n0-resonance", "Écouter les réactions de la forêt plutôt que les voix qui vous appellent.", "resonance", [
      N("Les trois voix rient au même rythme. Les branches, elles, s'écartent légèrement d'un seul passage, comme si quelque chose devait y circuler sans être gêné."),
      N("Vous suivez cet espace jusqu'à la marque grise. Naïah est accroupie derrière le tronc, occupée à retendre un fil presque invisible entre la pierre et une racine."),
      P("Je croyais devoir te retrouver."),
      A("Tu m'as retrouvée. Rien dans les règles ne disait que je resterais inactive en attendant.", "thinking"),
      P("Ce fil faisait partie du jeu ?"),
      A("Tout fait partie du jeu quand on refuse d'expliquer la différence."),
      N("Elle vérifie la tension du fil, puis le dissimule sous la mousse avec un soin incompatible avec son désintérêt affiché."),
      A("Tu as écouté le chemin au lieu de la personne la plus brillante de la clairière. C'est vexant. C'était aussi la bonne idée."),
      P("Qu'est-ce que j'ai gagné ?"),
      A("Le droit de revenir assez souvent pour comprendre pourquoi cette pierre doit rester grise."),
    ], { trust: 7, affection: 3, confluence: 3, flags: ["naiah-watchpoint-seen"] }),
    Q("n0-lucidite", "Comparer les détails que ses doubles oublient de modifier.", "lucidite", [
      N("Les pommes portent les mêmes marques de dents, mais une seule brunit. Les cinq silhouettes évitent aussi de poser le pied sur la mousse qui cache la petite balise."),
      N("Vous abandonnez les sentiers et attendez près de la pierre grise."),
      A("C'est terriblement impoli de résoudre un jeu en refusant son décor.", "thinking"),
      N("La vraie Naïah descend de l'arbre au-dessus de vous. Elle tient un éclat de métal rouillé qu'elle vient d'ôter de la balise."),
      P("Tu surveillais cet endroit avant mon arrivée."),
      A("Après aussi. Entre les deux, j'ai trouvé le temps de te distraire. Mon organisation est admirable."),
      P("Quelqu'un a touché à la balise ?"),
      A("Une biche, un intrus ou un caillou politiquement motivé. Je saurai lequel avant qu'il recommence."),
      N("Elle range le métal, puis vous prend le poignet pour vous faire éviter une racine qui se soulève."),
      A("Tu regardes les mauvais détails avec beaucoup de talent. Reviens : j'en ai d'autres à te cacher."),
    ], { trust: 8, affection: 2, confluence: 2, flags: ["naiah-watchpoint-seen"] }),
    Q("n0-audace", "Quitter les trois sentiers et suivre la branche qui vous a invité·e.", "audace", [
      N("La branche recule dès que vous l'approchez. Vous la suivez à travers des ronces illusoires, sous un tronc réel et jusqu'à une pente que Naïah n'avait manifestement pas prévue."),
      A("Tu sais que refuser mes règles ne rend pas automatiquement ta méthode intelligente ?"),
      P("Tu me suis."),
      A("Je protège mon investissement."),
      N("Votre pied glisse. Naïah pourrait vous retenir ; elle choisit de saisir votre manche et de dévaler la pente avec vous."),
      N("Vous atterrissez près d'une pierre grise entourée d'un cercle de feuilles fraîchement replacées. Son rire s'arrête juste le temps de vérifier que le cercle est intact."),
      P("C'est cela que tu voulais voir ?"),
      A("Je voulais voir ce que tu ferais. La forêt, elle, voulait me rappeler une corvée."),
      N("Elle touche la pierre. Une pulsation violette file sous les racines, puis disparaît."),
      A("Bonne nouvelle : tu as gagné. Mauvaise nouvelle : je viens de décider qu'il y aura une revanche."),
    ], { affection: 7, trust: 3, desire: 2, confluence: 2, flags: ["naiah-watchpoint-seen"] }),
  ]),

  scene(1, 6, "Les brumes ne s'entretiennent pas toutes seules", "purple_forest", "thinking", [
    N("Le ruban violet vous attend cette fois noué autour d'un petit maillet. Au dos, Naïah a gravé : « Apporte deux mains auxquelles tu ne tiens pas trop. »"),
    N("Au carrefour, trois cordelettes relient une balise de pierre, un anneau de racines et une clochette sans battant. Naïah est couchée sous l'anneau, les bras enfoncés dans la terre jusqu'aux coudes."),
    A("Tu arrives juste à temps. La brume essaie de manger ses propres chemins."),
    P("C'est-à-dire ?"),
    A("Elle cache le passage, l'inverse, puis le rouvre au même endroit. Si je la laisse faire, elle guidera les intrus en cercle jusqu'à ce que leurs traces attirent les suivants."),
    N("Elle se relève et vous montre les trois protections. La première épaissit la brume pour cacher les routes. La deuxième échange leurs directions afin de désorienter les intrus. La dernière les renvoie vers l'extérieur au lieu de les laisser s'enfoncer dans la forêt."),
    A("Je les réaccorde. Toi, tu tiens les repères, tu annonces ce qui bouge et tu évites héroïquement de devenir mage par enthousiasme."),
    P("Cela arrive souvent ?"),
    A("Que des voyageurs se croient indispensables ? Constamment. Que mes balises se contredisent ? Non."),
    N("Elle active la pierre. La brume part dans trois directions, revient d'un coup et broie une jeune branche contre le sol."),
    N("Naïah rit une fois. Elle recommence. La pression augmente ; les arbres grincent et la corde du renvoi se tend jusqu'à vous brûler les paumes."),
    A("Tiens."),
    N("Un second essai arrache la clochette de son support. Le sourire de Naïah ne bouge plus du tout."),
  ], [
    Q("n1-lucidite", "Comparer l'ordre des trois réactions et chercher l'instruction contradictoire.", "lucidite", [
      P("La brume part avant que la balise de renvoi réponde. Ce n'est pas la force qui manque : une instruction arrive dans le mauvais ordre."),
      N("Vous suivez la corde jusqu'à un petit crampon de fer planté derrière la pierre. Il porte une marque étrangère à celles de Naïah."),
      A("Oh.", "neutral"),
      N("Elle ne plaisante pas. Elle retire le crampon ; la brume se contracte autour de sa main avec assez de violence pour fendre la pierre."),
      P("Quelqu'un l'a posé exprès."),
      A("Quelqu'un a voulu que mes protections cachent les gens après les avoir attirés. Une nuance très offensante."),
      N("Elle inverse deux liens, vous fait compter les pulsations et relance le réseau. Cette fois, le brouillard ouvre un corridor net vers l'extérieur."),
      A("Tu as vu l'ordre avant moi."),
      P("J'étais moins occupé·e à menacer la forêt."),
      A("Ne prends pas une victoire ponctuelle pour une licence d'insolence. Mais garde le crampon."),
    ], { trust: 9, affection: 2, confluence: 4, flags: ["naiah-wards-serviced"] }),
    Q("n1-resonance", "Repérer la protection qui résiste à Naïah plutôt que celle qui fait le plus de bruit.", "resonance", [
      N("La clochette vole et la branche casse, mais l'anneau de racines reste parfaitement immobile. Naïah ne le regarde jamais plus d'une seconde."),
      P("Celui-ci ne répond pas. Et tu l'évites."),
      A("Je n'évite rien. Je distribue mon mépris équitablement.", "angry"),
      N("Vous posez le maillet près de l'anneau sans le frapper. Sous la terre, une vibration régulière continue malgré le chaos."),
      P("Il reçoit encore un signal. Pas le tien."),
      N("Naïah arrache une racine morte. Un fil de fer apparaît, enroulé autour du cœur du mécanisme."),
      A("Quelqu'un lui souffle de ne pas me reconnaître."),
      N("Sa voix est douce ; la brume, elle, écrase le fil jusqu'à le réduire en poudre noire. Vous maintenez les cordelettes pendant qu'elle rétablit chaque nœud."),
      A("Ce n'était pas une crise. C'était une réponse légèrement enthousiaste."),
      P("La branche n'est pas d'accord."),
      A("Elle manquait de loyauté."),
    ], { trust: 8, affection: 3, confluence: 4, flags: ["naiah-wards-serviced"] }),
    Q("n1-sangfroid", "Maintenir les trois repères en place jusqu'à ce qu'elle puisse couper la surcharge.", "sangFroid", [
      N("Vous enroulez les cordelettes autour de vos avant-bras et plaquez le maillet entre les pierres. La force qui traverse le réseau cherche à vous faire lâcher, sans jamais devenir votre magie."),
      P("Les trois positions tiennent. Coupe ce qui revient sur lui-même."),
      N("Naïah vous regarde, puis cesse de frapper le système entier. Elle glisse deux doigts sous une attache de fer et l'arrache d'un geste sec."),
      N("La surcharge se vide dans le sol. Les racines cessent de gémir ; le sentier de retour réapparaît derrière vous."),
      A("Tu aurais pu lâcher."),
      P("Tu m'avais dit de tenir."),
      A("Les gens confondent souvent une consigne avec une raison de mourir stupidement."),
      P("J'avais encore une sortie."),
      N("Elle examine vos paumes rougies, puis les cordes. Le morceau de fer étranger tombe à ses pieds."),
      A("Bien. La prochaine fois, annonce quand tu approches de ta limite. Je préfère décider moi-même quand paniquer."),
    ], { trust: 10, affection: 2, confluence: 3, flags: ["naiah-wards-serviced"] }),
  ]),

  scene(2, 8, "Ceux qu'elle prétend ne pas protéger", "forbidden_forest", "smirk", [
    N("Naïah vous intercepte au seuil de la forêt et vous entraîne derrière un rideau de brume avant même de vous saluer."),
    A("Ne regarde surtout pas le convoi. Je ne surveille pas ses deux herboristes, sa soigneuse, ni l'enfant qui porte une caisse plus grande que lui."),
    P("Tu connais précisément ce que tu ne surveilles pas."),
    A("Je suis très consciencieuse dans mon indifférence."),
    N("En contrebas, quatre voyageurs portant les couleurs d'Akuhn’Nabad avancent vers un hameau de frontière avec des fioles de remède. Ils ignorent que la brume ouvre le passage devant eux et referme chaque piste dans leur dos."),
    N("Un sifflement coupe votre échange. Trois pillards surgissent près du chariot ; deux autres attendent sur la route de fuite."),
    A("Ils ont trouvé le seul passage que je n'ai pas fermé. Quelqu'un leur a donné l'heure."),
    N("Le rire de Naïah roule entre les arbres. Les assaillants s'immobilisent, chacun persuadé que ses compagnons viennent de disparaître."),
    A("Continuez. Vous étiez venus prendre quelque chose."),
    N("Le chef tombe à genoux. Naïah entre dans son souvenir sans toucher son corps : une galerie étroite se dessine dans ses yeux, se referme, recommence. Son cri lui arrache un sourire trop attentif."),
    P("Naïah."),
    A("Il sait qui leur a vendu la route."),
    N("Le convoi, toujours caché, approche pourtant du carrefour où deux illusions risquent de se rejoindre."),
  ], [
    Q("n2-audace", "Descendre ouvrir physiquement le passage pendant qu'elle retient les assaillants.", "audace", [
      N("Vous dévalez la pente, renversez la balise falsifiée et tirez le chariot hors de l'ornière avant que les deux illusions se heurtent."),
      P("À gauche ! Le terrain tient jusqu'au grand rocher."),
      N("La soigneuse ne demande pas qui vous êtes. Elle pousse l'enfant devant elle et suit le corridor que Naïah entrouvre à mesure que vous avancez."),
      N("Derrière vous, le cri du chef cesse brusquement. Les pillards réapparaissent ligotés par leurs propres ceintures, face à une route qui les conduit hors de la forêt."),
      A("Tu as marché au milieu de mon plus bel interrogatoire."),
      P("Le convoi arrivait au milieu de ton plus mauvais croisement."),
      N("Naïah jette un regard vers l'enfant désormais à l'abri. Son irritation perd une partie de sa conviction."),
      A("Ils ne m'ont pas vue."),
      P("C'était le but ?"),
      A("Le but était que personne ne me remercie. Ils le font toujours de travers."),
    ], { affection: 6, trust: 5, confluence: 4, flags: ["naiah-convoy-protected"] }),
    Q("n2-resonance", "Guider le convoi avec les repères laissés par Naïah sans interrompre son piège à l'aveugle.", "resonance", [
      N("Vous repérez les rubans violets qu'elle a noués trop haut pour les voyageurs : un, puis deux, puis le signe discret d'un retour sûr."),
      P("Fais apparaître le prochain repère. Je leur donnerai une raison ordinaire de le suivre."),
      N("Vous lancez une pierre sur la bonne piste. La soigneuse entend le bruit, découvre la terre ferme et détourne le chariot juste avant la collision des brumes."),
      N("Naïah extrait un nom du souvenir du chef. Elle pourrait poursuivre ; son sourire l'indique. À la place, elle desserre le piège."),
      A("Le marchand des vieux ponts. Voilà tout ce dont j'avais besoin."),
      N("Les agresseurs se réveillent sur la route extérieure, certains de s'être perdus plusieurs jours. Quelques minutes plus tard, le convoi franchit la borne sans avoir aperçu Naïah."),
      P("Tu avais préparé tous ces repères pour des gens que tu ne protèges pas."),
      A("Je les avais préparés pour mes arbres. Les arbres adorent les remèdes contre la fièvre."),
      P("Naturellement."),
      A("Ne prends pas ce ton. Ils sont très fragiles en hiver."),
    ], { trust: 8, affection: 3, confluence: 5, flags: ["naiah-convoy-protected"] }),
    Q("n2-sangfroid", "Obtenir le nom recherché, puis imposer une fin concrète à l'embuscade.", "sangFroid", [
      P("Tu as le nom. Renvoie-les dehors pendant que je dégage le corridor du convoi."),
      N("Naïah ne répond pas. Le chef revit une quatrième fois l'effondrement de la galerie ; elle observe la peur avec une curiosité qui n'a rien de feint."),
      P("Le nom, Naïah. Puis la route."),
      A("Le marchand des vieux ponts."),
      N("Le rire revient d'un coup. Cinq portes apparaissent autour des assaillants, toutes marquées « sortie ». Ils choisissent la seule qui les dépose attachés devant un poste de garde frontalier."),
      N("Vous redressez la balise pendant que Naïah maintient un corridor simple pour le chariot. L'enfant se retourne vers les arbres, comme s'il avait entendu quelque chose."),
      A("S'il raconte qu'une très belle voix l'a sauvé, je nie tout."),
      P("Et le moment où tu souriais ?"),
      A("Je ne prétends pas être gentille. Seulement efficace."),
      N("Elle regarde longtemps le convoi s'éloigner. Lorsqu'elle se retourne, son sourire est déjà revenu, beaucoup trop grand."),
    ], { trust: 7, affection: 4, confluence: 4, flags: ["naiah-convoy-protected"] }),
  ]),

  scene(3, 10, "Quand le rire s'arrête", "purple_forest", "thinking", [
    N("Le nom arraché aux pillards mène à des ruines où trois cartographes ont installé des cages de fer autour de fragments de balises volées."),
    N("Naïah commence la chasse en imitant la voix de leur chef, puis leurs pas, puis le bruit de leur propre fuite. Elle les fait tourner assez longtemps pour que deux d'entre eux se disputent avec leurs doubles."),
    A("J'hésite entre les perdre jusqu'à l'hiver et leur vendre une carte de sortie. La seconde option financerait mes loisirs."),
    P("Leur matériel envoie encore un signal."),
    N("Vous renversez l'émetteur. Le dernier cartographe surgit derrière vous ; Naïah le plaque contre une colonne avec une main de brume."),
    A("Qui achète mes routes ?"),
    N("L'homme reconnaît les couleurs d'Akuhn’Nabad cousues sous sa manche. Son sourire remplace sa peur."),
    L("Le cartographe", "La fille jetée dehors joue encore à garder la porte. Allenna avait raison : votre mère a conservé l'héritière utile."),
    N("Naïah ne rit plus."),
    N("La forêt entière se tait avec elle. La brume quitte le sol, entre par les yeux du captif et efface un à un les contours des ruines dans son regard."),
    L("Le cartographe", "Attendez…"),
    A("Le nom.", "neutral"),
    N("Deux mots seulement. Les cages de fer commencent à se tordre ; l'homme oublie déjà de quel côté se trouve la sortie."),
  ], [
    Q("n3-lucidite", "Récupérer les cartes et retourner leur propre balise contre le réseau des acheteurs.", "lucidite", [
      P("Le registre est dans la sacoche. Nous n'avons pas besoin de sa mémoire pour trouver les autres."),
      N("Vous ouvrez les cartes devant Naïah : chaque point volé porte une heure, un acheteur et un signal de réponse."),
      P("Laisse-les croire que ce camp fonctionne encore. Leurs prochains messages donneront les autres positions."),
      N("Le visage de Naïah ne change pas. La pression dans les yeux du captif cesse pourtant d'augmenter."),
      A("Tu proposes que je mente à distance à des gens qui se croient plus intelligents que moi."),
      P("Cela ressemblait à une activité adaptée."),
      N("Elle relâche l'homme, inverse la cage de fer et lui impose un seul souvenir faux : celui d'une opération réussie."),
      A("Il retrouvera la sortie. Ses employeurs, beaucoup moins vite."),
      N("Lorsqu'elle recommence à parler, son sourire demeure absent. Son regard, lui, calcule déjà trois coups d'avance."),
    ], { trust: 9, affection: 2, confluence: 5, flags: ["naiah-intruders-routed"] }),
    Q("n3-sangfroid", "Détruire les copies et accepter de perdre une partie des renseignements pour fermer le danger maintenant.", "sangFroid", [
      P("Les cages parlent encore au réseau. On brûle les cartes, on renvoie les trois dehors et on ferme cette route avant que quelqu'un réponde."),
      N("Naïah fixe le captif. Il prononce le nom d'Allenna comme une seconde lame ; la brume se resserre."),
      P("Maintenant."),
      N("Vous jetez les copies dans le brasero. Naïah écrase l'émetteur et ouvre brutalement un chemin de renvoi sous les cartographes."),
      N("Ils disparaissent. Au même instant, une pulsation venue de l'extérieur frappe la cage vide et s'y brise."),
      A("Nous aurions pu savoir qui répondait."),
      P("Et ils auraient su que la route fonctionnait."),
      N("Elle reste silencieuse assez longtemps pour que l'absence de plaisanterie pèse davantage qu'une dispute."),
      A("Tu as choisi ce que nous perdions."),
      P("Oui."),
      A("Bien. Alors je choisis ce que nous gardons : aucune nouvelle entrée cette nuit."),
    ], { trust: 10, affection: 1, confluence: 4, flags: ["naiah-intruders-routed"] }),
    Q("n3-audace", "Transformer leur appareil en fausse carte qui mène chaque intrus vers l'extérieur.", "audace", [
      P("Tu peux réécrire leur réseau sans entrer davantage dans sa tête ?"),
      A("Oui."),
      P("Alors donne à toutes leurs cartes la même destination : la borne extérieure."),
      N("Un éclat dangereux passe dans ses yeux. Il ne devient pas un rire."),
      A("Chaque équipe persuadée d'avancer reviendra au point de départ. Encore. Et encore."),
      N("Elle retire sa magie du captif et la verse dans les cages. Les lignes volées se replient comme des serpents et viennent toutes mordre le même point hors de la forêt."),
      P("Qu'ils racontent eux-mêmes que leurs cartes mentent."),
      A("C'est plus cruel que les perdre une fois."),
      P("Cela évite de le briser pour obtenir la même chose."),
      N("Naïah considère l'homme à terre, puis vous. Elle ouvre la route de sortie sans un mot de plus."),
      A("Va-t'en. Si tu reviens, je ne chercherai pas une idée plus élégante."),
    ], { affection: 5, trust: 6, confluence: 5, flags: ["naiah-intruders-routed"] }),
  ]),

  scene(4, 12, "La gardienne sans titre", "forbidden_forest", "neutral", [
    N("La première alerte ressemble à un battement sous vos bottes. La seconde fait apparaître, entre chaque arbre, le même chemin vers Akuhn’Nabad — y compris là où la terre s'ouvre sur un ravin."),
    N("Naïah vous rejoint sans branche messagère, sans double et sans sourire."),
    A("Le faux réseau s'est réveillé."),
    P("Combien de points ?"),
    A("Tous."),
    N("Au loin, une cloche de convoi sonne deux fois. Les herboristes aperçus quelques jours plus tôt reviennent par la route basse avec des gardes-frontières et deux familles. Le réseau saboté leur montre une entrée qui n'existe pas."),
    N("Naïah pose une main contre le sol. La brume se soulève sur des lieues ; ses trois couches — dissimulation, confusion, renvoi — se heurtent et changent de sens."),
    A("Prends les quatre bornes. Blanche au passage des civils, grise derrière eux, noire au ravin. La violette reste dans ta main jusqu'à mon ordre."),
    P("Et toi ?"),
    A("Je tiens la forêt."),
    N("Elle ne promet pas que cela suffira. Vous courez tandis qu'elle maintient seule les faux chemins à distance des voyageurs."),
    N("À la troisième borne, sa magie vacille. Un cri traverse la brume ; Naïah plie un genou, relève la tête et ne prononce toujours rien."),
  ], [
    Q("n4-lucidite", "Ouvrir d'abord un corridor unique pour les civils, puis condamner les fausses routes.", "lucidite", [
      N("Vous plantez la borne blanche à l'endroit où la terre porte encore les traces réelles des roues. La grise ferme chaque bifurcation derrière le dernier chariot."),
      P("Une seule route ouverte. Toutes les autres peuvent tomber."),
      N("Avant la fin de votre phrase, les illusions les plus lointaines s'éteignent. Naïah concentre le réseau sur ce corridor étroit."),
      N("Les familles franchissent le passage. Dès que le dernier garde atteint la borne, vous plantez le noir face au ravin."),
      A("Violette."),
      N("Vous la levez. Naïah referme les trois couches dans le bon ordre ; les faux sentiers s'effondrent sans emporter le vrai."),
      N("La cloche du convoi sonne de l'autre côté. Personne ne voit la femme agenouillée dans la brume qui vient de lui rendre une route."),
      A("Ils continueront à dire que la forêt les a laissés passer."),
      P("La forêt a d'excellentes mains."),
      A("Ne deviens pas poète maintenant. Ramasse les bornes."),
    ], { trust: 11, affection: 4, confluence: 6, flags: ["naiah-guardian-witnessed"] }),
    Q("n4-resonance", "Suivre le rythme ancien des protections et signaler à Naïah chaque battement copié.", "resonance", [
      N("Sous le fracas des faux ordres, le réseau originel conserve un rythme irrégulier : deux pulsations profondes, une pause, puis le renvoi."),
      P("Le vrai signal boite. Les copies sont trop parfaites."),
      N("Vous frappez la borne violette contre la pierre à chaque pulsation étrangère. Naïah coupe une branche du réseau après l'autre, sans vous demander d'y verser la moindre magie."),
      N("Lorsque sa main tremble, elle s'arrête une respiration au lieu de forcer. Vous gardez le rythme ; elle reprend sur le battement suivant."),
      A("Encore trois."),
      P("Deux."),
      N("La dernière copie tente de se confondre avec le signal ancien. Vous attendez son battement trop régulier et frappez."),
      N("Naïah l'arrache. Le vrai chemin réapparaît sous les roues du convoi."),
      A("Tu n'as pas tenu la forêt."),
      P("Non."),
      A("Tu m'as permis de l'entendre. C'était plus utile."),
    ], { trust: 12, affection: 3, confluence: 7, flags: ["naiah-guardian-witnessed"] }),
    Q("n4-sangfroid", "Ordonner un repli court vers la borne sûre plutôt que risquer l'effondrement complet.", "sangFroid", [
      P("Tu lâches le ravin pendant dix secondes. Je ramène les bornes sur la ligne grise, puis tu reprends."),
      N("Naïah tourne vers vous un visage parfaitement vide. Le convoi avance encore ; le faux passage aussi."),
      A("Dix."),
      N("Elle relâche le secteur dangereux. Vous courez jusqu'à la borne grise, tirez le câble de rappel et faites basculer les repères autour du corridor civil."),
      P("Six. Cinq."),
      N("À quatre, Naïah se relève. À trois, elle récupère la brume. À deux, le ravin disparaît derrière un mur de racines et le convoi retrouve la route basse."),
      N("Elle avait encore le pouvoir de forcer. Elle a choisi de se retirer parce que vous lui aviez donné une reprise possible."),
      A("Tu comptes très mal."),
      P("Ils sont passés."),
      A("Alors j'accepte officiellement tes dix secondes de quinze."),
    ], { trust: 13, affection: 2, confluence: 6, flags: ["naiah-guardian-witnessed"] }),
    Q("n4-audace", "Traverser le faux sentier pour replacer la borne noire au bord réel du ravin.", "audace", [
      N("Vous attachez la corde à la borne grise et avancez dans un chemin qui invente le sol sous chacun de vos pas. Naïah ouvre les yeux."),
      A("Reviens."),
      P("Tiens le vrai bord visible."),
      N("Elle ne vous arrache pas au passage. Elle maintient une ligne nue dans la brume ; vous la suivez jusqu'au rocher où la borne noire a été déplacée."),
      N("Vous la replantez. Le ravin reprend sa place et le faux pont se brise avant que le convoi l'atteigne."),
      N("Naïah referme le réseau autour de votre corde, pas autour de votre corps, et vous laisse effectuer vous-même le retour."),
      A("Tu aurais pu tomber."),
      P("Tu m'as montré le bord."),
      A("Et tu as décidé que cela suffisait."),
      N("Son reproche est réel. La confiance avec laquelle elle vous a laissé agir l'est aussi."),
      A("La prochaine fois, je choisis l'idée dangereuse. Tu manques encore de pratique."),
    ], { affection: 7, trust: 7, desire: 2, confluence: 6, flags: ["naiah-guardian-witnessed"] }),
  ]),
];
