import type { NaiahAuthoredScene } from "./naiah-date-intimacy-types";
import { NC } from "./naiah-date-intimacy-types";

export const NAIAH_HOME_INTIMACY_SCENES: NaiahAuthoredScene[] = [
  {
    id: "naiah-home-femme-hunt", context: "home-naiah", sex: "femme", concept: "terrain-chasse",
    text: "Terrain de chasse", detail: "Naïah retourne contre vous les habitudes de votre propre logement et découvre en chemin lesquelles troublent vraiment votre corps.",
    chapters: {
      tendre: [
        NC("Vous prenez votre place habituelle sur le canapé. Naïah disparaît derrière le dossier, alors que sa tasse reste bien visible près de la vôtre et trahit son intention de revenir."),
        NC("Ses mains couvrent vos yeux depuis l’arrière. Elle imite votre propre voix pour annoncer un danger imaginaire, puis rit lorsque vous l’attrapez par les poignets."),
        NC("Vous la faites basculer par-dessus le dossier. Naïah atterrit sur les coussins, surprise et ravie que son embuscade ait changé de propriétaire."),
        NC("Elle essaie de reprendre l’avantage avec trois copies cachées dans la pièce. Vous reconnaissez l’originale à son regard posé sur la tasse chaque fois qu’un double l’approche."),
        NC("Votre baiser la trouve sous la table. Une assiette illusoire proteste, un monstre minuscule s’enfuit avec une cuillère et Naïah oublie sa prochaine réplique."),
        NC("Vous revenez au canapé en échangeant les places à chaque rire. Le plaid passe de ses épaules aux vôtres puis finit autour de vous deux."),
        NC("Naïah pose sa tasse sur l’étagère sans annoncer qu’elle reste. Sa main rejoint la vôtre sous le plaid et son crâne trouve naturellement votre épaule."),
        NC("Elle s’endort ou feint de le faire jusqu’au moment où vous bougez. Un œil violet s’ouvre : « Mauvaise fuite. Recommence demain. »"),
      ],
      suggestif: [
        NC("Vous vous asseyez à votre place habituelle. Les mains de Naïah couvrent vos yeux depuis l’arrière tandis qu’une copie s’installe ostensiblement face à vous comme faux coupable."),
        NC("Vous saisissez l’originale et la faites passer sur le canapé. Son rire se brise dans un baiser ; elle découvre que le dossier soutient parfaitement vos hanches."),
        NC("Vos chemises s’ouvrent pendant une poursuite autour de la table. Naïah cache votre veste, vous capturez la sienne et les vêtements deviennent les trophées visibles du jeu."),
        NC("Elle essaie une caresse trop annoncée. Vous l’évitez et utilisez son élan pour la placer sous vous ; surprise, elle vous laisse mener jusqu’à ce qu’une ombre tire doucement votre cheville."),
        NC("Naïah revient entre vos cuisses, apprend à votre souffle quelle pression conserver et prétend avec aplomb que le canapé avait tout préparé."),
        NC("Le plaid recouvre la partie la plus charnelle du jeu. Sa bouche, ses mains et quelques ombres tricheuses transforment chaque habitude du logement en point d’embuscade."),
        NC("Votre plaisir atteint son terme sur le canapé que vous croyiez connaître. Naïah reste concentrée sur votre réaction, ravie par le résultat plus que par une excitation propre."),
        NC("Elle remet la tasse sur l’étagère et laisse ses vêtements sur la chaise. Vous vous endormez sous le plaid ; au matin, elle nie avoir gagné puisqu’aucun score n’avait été annoncé."),
      ],
      explicite: [
        NC("Vous vous asseyez à votre place habituelle. Naïah surgit derrière le canapé, couvre vos yeux et annonce qu’elle vous fera jouir sans quitter la moitié de pièce que vous pensez connaître.", ["Naïah", "Tout ce que tu fais sans réfléchir vient de devenir une faiblesse exploitable.", "teasing"]),
        NC("Vous l’attrapez et la faites basculer sur les coussins. Elle rit contre votre bouche, glisse une main sous votre chemise et découvre la sensibilité de vos seins au bord du dossier.", ["Naïah", "Cette place était donc déjà dangereuse. Tu me caches des choses.", "bright"]),
        NC("La chasse emporte vos vêtements selon le trajet de vos renversements : chemise sur la table, pantalon près du fauteuil, dernières étoffes sous le plaid. Naïah se déshabille en vous poursuivant jusqu’à ce que vous soyez nues devant le canapé."),
        NC("Naïah se tient nue dans votre salon, sa chemise abandonnée sur la chaise et sa tasse toujours près de la vôtre. Elle vous attire sur les coussins, ravie que cette pièce réelle suffise au jeu.", ["Naïah", "Pas de palais. Pas de lit inventé. Je vais corrompre ton canapé.", "smirk"]),
        NC("Elle vous allonge dans l’angle où vous lisez d’ordinaire et essaie plusieurs caresses autour de votre chaleur. Une pression trop basse ne produit rien ; elle remonte, entend votre souffle céder et s’arrête net, les yeux brillants."),
        NC("Naïah recommence exactement, puis modifie le mouvement pour vérifier ce qui vous a trahie. Vous lui attrapez le poignet avant la troisième interruption.", ["{player}", "Tu as trouvé. Ne transforme pas tout en devinette."], ["Naïah", "Mais c’est une excellente devinette.", "teasing"]),
        NC("Vous la renversez dans les coussins et pressez votre cuisse entre les siennes. Sa première réaction est un rire de surprise ; la seconde, lorsque vous ralentissez, lui vole quelques secondes de sa comédie et vous laisse conduire."),
        NC("Elle s’échappe sous le plaid, rampe jusqu’au pied du canapé et réapparaît entre vos jambes. Sa bouche trouve votre ventre, vos hanches, puis le point sensible qu’elle avait repéré avec ses doigts ; une main garde votre cuisse ouverte, l’autre cherche la vôtre."),
        NC("Une ombre froide longe votre flanc. Vous la chassez d’un geste ; Naïah comprend que le tour disperse votre plaisir et le remplace par sa paume réelle sur votre sein.", ["Naïah", "La magie vient de perdre contre ma main. Je demande une enquête.", "annoyed"]),
        NC("Sa langue reprend le rythme appris tandis que ses doigts modulent seulement l’extérieur de votre chaleur. Chaque fois que vos hanches se soulèvent, elle ajuste sa position contre le meuble familier au lieu de vous déplacer vers une scène plus commode."),
        NC("Votre plaisir éclate sur le canapé que vous croyiez connaître. Naïah garde sa bouche et sa main jusqu’au dernier frisson, puis relève la tête avec l’émerveillement satisfait d’une femme qui vient de découvrir un passage secret.", ["Naïah", "Cette expression appartient donc à cette place maintenant.", "bright"]),
        NC("Elle retrouve vos vêtements le long de la pièce, tire le plaid sur vos jambes et laisse pourtant sa chemise sur votre chaise. Nue contre vous, elle pose sa tasse près de la vôtre.", ["Naïah", "Je reviendrai vérifier si le canapé se souvient.", "soft"]),
      ],
      ellipse: [
        NC("Vous prenez votre place habituelle. Naïah surgit derrière le canapé et annonce qu’elle va transformer vos habitudes en terrain de chasse avant la fin de la soirée."),
        NC("Vous retournez sa première embuscade et la faites basculer sur les coussins. Son baiser surpris lance une partie dont aucune règle n’a été annoncée."),
        NC("La poursuite emporte vos vêtements, déposés à des endroits précis de la pièce. Naïah retire les siens à son tour ; vos corps deviennent nus avant que le plaid ne monte."),
        NC("Vous choisissez ensemble de poursuivre ce jeu charnel dans le salon réel. Sa tasse reste près de la vôtre et aucune illusion ne remplace le canapé sous vos corps."),
        NC("Le plaid garde hors champ les embuscades, les caresses et les renversements. Le récit revient lorsque vos vêtements forment un chemin impossible à expliquer par une visite sage."),
        NC("Naïah repose contre votre hanche, ravie que votre propre maison vous ait trahie. Vous lui rappelez qu’elle a perdu deux manches ; elle en invente une troisième rétroactive."),
        NC("Vous récupérez les vêtements un à un, sauf sa chemise qu’elle abandonne sur la chaise. La tasse retrouve l’étagère sans discussion."),
        NC("Au matin, elle surgit encore derrière le dossier pour tester votre sursaut. Vous l’attrapez sans regarder ; Naïah annonce une revanche avec une fierté immense."),
      ],
    },
  },
  {
    id: "naiah-home-homme-hunt", context: "home-naiah", sex: "homme", concept: "terrain-chasse",
    text: "Terrain de chasse", detail: "Naïah retourne contre vous les habitudes de votre propre logement et découvre en chemin lesquelles troublent vraiment votre corps.",
    chapters: {
      tendre: [
        NC("Vous prenez votre place habituelle. Naïah disparaît derrière le canapé, mais sa tasse demeure près de la vôtre et annonce qu’elle compte revenir."),
        NC("Ses mains couvrent vos yeux depuis le dossier. Elle imite votre voix pour décrire une attaque imaginaire, puis rit lorsque vous lui saisissez les poignets."),
        NC("Vous la faites passer par-dessus le dossier. Elle atterrit sur les coussins avec un cri ravi, première embuscade retournée avant d’avoir produit son grand effet."),
        NC("Trois copies se cachent dans la pièce. Vous repérez l’originale parce qu’elle surveille sa tasse chaque fois qu’une image s’en approche dangereusement."),
        NC("Votre baiser la trouve sous la table. Un monstre gros comme une pomme s’enfuit avec une cuillère et Naïah perd entièrement la phrase qu’elle préparait."),
        NC("Vous revenez au canapé en échangeant les places à chaque riposte. Le plaid passe de l’un à l’autre puis finit autour de vous deux."),
        NC("Naïah pose sa tasse sur l’étagère sans déclarer qu’elle reste. Sa tête vient contre votre poitrine et ses doigts s’installent dans les vôtres."),
        NC("Elle ferme les yeux jusqu’à ce que vous bougiez. Son sourire revient aussitôt : « Fuite médiocre. Je serai obligée de recommencer. »"),
      ],
      suggestif: [
        NC("Vous vous asseyez à votre place habituelle. Naïah couvre vos yeux depuis l’arrière tandis qu’un double innocent s’installe face à vous pour recevoir l’accusation."),
        NC("Vous saisissez l’originale et la faites passer sur le canapé. Son rire devient baiser ; elle découvre aussitôt que le dossier soutient parfaitement votre mouvement."),
        NC("Vos chemises s’ouvrent pendant une poursuite autour de la table. Elle cache votre veste, vous gardez la sienne et chaque vêtement devient un trophée concret."),
        NC("Naïah annonce une caresse trop tôt. Vous l’évitez, l’installez sous vous et menez le jeu jusqu’à ce qu’une ombre tire votre cheville au pire moment."),
        NC("Elle glisse alors une main plus basse, observe votre souffle et trouve la pression qui vous empêche de préparer la riposte suivante."),
        NC("Le plaid cache les gestes devenus charnels. Sa bouche, sa main et les ombres du salon détournent une à une toutes les habitudes qui vous rassuraient."),
        NC("Votre plaisir atteint son terme sur le canapé familier. Naïah compte votre respiration sur ses doigts, rayonne comme après une victoire impossible et invente déjà la revanche pendant que vous récupérez."),
        NC("Elle replace sa tasse et abandonne sa veste sur la chaise. Au matin, elle nie avoir gagné puisque le score n’existait pas avant qu’elle décide du résultat."),
      ],
      explicite: [
        NC("Vous prenez votre place habituelle. Naïah surgit derrière le dossier et annonce qu’elle vous fera jouir sans quitter cette moitié du salon que vous croyez parfaitement connaître.", ["Naïah", "Ta maison m’a donné tes habitudes. C’est presque irresponsable.", "teasing"]),
        NC("Vous la saisissez et la faites basculer sur les coussins. Elle rit contre votre bouche, ouvre votre chemise et presse votre désir à travers le pantalon. Votre réaction lui fait oublier la phrase qu’elle préparait.", ["Naïah", "Je la retrouverai. Ne bouge surtout pas.", "bright"]),
        NC("La chasse disperse vos vêtements : chemise sur la table, pantalon près du fauteuil, dernières étoffes sous le plaid. Naïah se déshabille en vous poursuivant jusqu’à ce que vous soyez nus devant le canapé, tous les chemins de retour clairement visibles."),
        NC("Nue dans la lumière du salon, Naïah laisse sa tasse à côté de la vôtre et vient à califourchon sur vos cuisses. Aucun palais d’ombre ne remplace la pièce.", ["Naïah", "Je vais rendre cette place très difficile à utiliser sagement.", "smirk"]),
        NC("Elle enferme votre élan entre ses cuisses, tente un rythme trop rapide et reçoit votre rire. Naïah ralentit avec une mine offensée, déplace ses hanches et ajoute la chaleur de sa paume là où le frottement devient enfin précis."),
        NC("Votre souffle change. Elle répète le mouvement, s’arrête juste avant votre réponse et recommence pour vérifier que l’attente vous trouble davantage.", ["{player}", "Tu viens de le découvrir."], ["Naïah", "Je viens de t’autoriser à le remarquer.", "teasing"]),
        NC("Vous la renversez sur le canapé et reprenez l’initiative par des baisers le long de sa poitrine et de son ventre. Naïah heurte sa tasse du talon ; une petite ombre la rattrape tandis qu’elle éclate de rire sous vous."),
        NC("Elle profite de votre distraction pour disparaître sous le plaid. Sa main vous retrouve d’abord, lente autour de votre désir ; sa bouche suit, chaude, pendant que vous restez assis dans l’angle exact où vous preniez autrefois votre livre."),
        NC("Sa première reprise est trop vive. Vos doigts dans ses cheveux l’arrêtent ; Naïah relève les yeux, attentive plutôt que vexée, puis adopte la cadence indiquée et ajoute seulement une ombre fraîche contre votre ventre."),
        NC("Vous tentez de reprendre le contrôle en tirant le plaid. Elle l’enroule autour de votre poignet et garde sa bouche sur vous.", ["Naïah", "Terrain familier, avais-je dit. Pas terrain loyal.", "smirk"], "Sa paume accompagne chaque mouvement sans presser davantage."),
        NC("Votre plaisir vous traverse dans le rythme qu’elle vient d’apprendre. Naïah maintient la chaleur de ses lèvres, suit les dernières pulsations et observe ensuite votre visage comme le passage secret caché dans une habitude ordinaire.", ["Naïah", "Refais-la demain matin.", "bright"]),
        NC("Elle rassemble vos vêtements, remet votre pantalon à portée et laisse sa propre chemise sur la chaise. Nue contre vous sous le plaid, elle cale ses pieds froids sous votre jambe et décide que cette moitié du salon lui appartient désormais un peu."),
      ],
      ellipse: [
        NC("Vous vous asseyez à votre place habituelle. Naïah surgit derrière le canapé et promet de changer chaque habitude rassurante en occasion de vous surprendre."),
        NC("Vous retournez son embuscade et la faites passer sur les coussins. Son rire surpris devient un baiser, puis une partie sans règle annoncée."),
        NC("La poursuite emporte vos vêtements, déposés à des endroits précis. Naïah retire les siens à son tour ; vos corps deviennent nus avant que le plaid vous couvre."),
        NC("Vous choisissez de poursuivre ce jeu charnel dans le salon réel. Les deux tasses restent côte à côte et aucune illusion ne remplace le meuble sous vous."),
        NC("Le plaid garde hors champ les embuscades et les renversements. Le récit revient lorsque les vêtements forment un chemin absurde du canapé à la table."),
        NC("Naïah repose contre votre torse, ravie que la maison vous ait trahi. Vous comptez deux manches gagnées ; elle en ajoute une troisième dans le passé."),
        NC("Vous récupérez les vêtements un à un, sauf sa chemise abandonnée sur la chaise. Sa tasse retrouve l’étagère comme si elle y avait toujours vécu."),
        NC("Au matin, elle retente l’attaque derrière le dossier. Vous l’attrapez sans regarder ; Naïah réclame une revanche et semble immensément fière de perdre autrement."),
      ],
    },
  },
  {
    id: "naiah-home-femme-shadow-room", context: "home-naiah", sex: "femme", concept: "chambre-ombre",
    text: "La chambre d’ombre", detail: "Naïah étend les sensations du logement dans un espace partagé que nul autre personnage ne pourrait ouvrir.",
    chapters: {
      tendre: [
        NC("Vous éteignez la lampe. La lanterne de Naïah reste sur l’étagère ; sa luciole violette étire les ombres jusqu’à faire disparaître les angles du salon."),
        NC("Elle prend vos deux mains et précise que la maison demeure réelle. Vous sentirez seulement son volume autrement : chaleur des murs, pression du sol, souffle dans les rideaux."),
        NC("Vous restez vêtues sur le canapé. Le coussin sous vos épaules devient une île de poids tandis que le reste de la pièce se change en distance souple."),
        NC("Naïah tente d’ajouter un plafond étoilé. La tasse ébréchée produit alors un tintement gigantesque dans le partage et fait tomber toutes les constellations."),
        NC("Vous riez ensemble, puis elle retire le spectacle. Vos doigts serrés deviennent le seul point lumineux ; votre respiration dessine le contour de son corps sans le toucher."),
        NC("Une caresse sur sa joue se propage dans les murs. Naïah ne l’avait pas prévu et reste immobile, attentive à ce geste devenu plus grand que sa magie."),
        NC("Elle referme l’espace jusqu’à retrouver votre bouche. Le baiser existe à la fois sur vos lèvres et dans la chaleur du canapé, étrange sans cesser d’être doux."),
        NC("La pièce ordinaire revient. La lanterne, la tasse et les vêtements sur la chaise sont toujours là ; Naïah garde votre main comme seule preuve du voyage."),
      ],
      suggestif: [
        NC("La lanterne avale les angles du salon et transforme les meubles en pressions familières. Naïah vous conduit par les mains, sans créer une chambre étrangère à votre logis."),
        NC("Vos baisers modifient l’espace : un souffle rapproche le plafond, une main sous la chemise réchauffe le mur contre lequel aucun corps ne repose pourtant."),
        NC("Vous ouvrez vos vêtements et les laissez sur le canapé. Chaque peau découverte donne une texture nouvelle à la pièce partagée, toujours sans mêler vos pensées."),
        NC("La tasse résonne lorsqu’elle tombe presque ; Naïah la rattrape et rit. Ce petit accident réel empêche l’expérience de devenir une cérémonie trop parfaite."),
        NC("Sa cuisse trouve les vôtres et la sensation se multiplie dans le sol, les coussins et l’air. Une tentative confuse vous fait rire ; elle simplifie aussitôt."),
        NC("Les caresses gagnent en intensité derrière l’obscurité violette. Elles restent externes, mais leurs échos semblent parcourir toute la pièce et revenir vers vous."),
        NC("Votre plaisir atteint son terme comme une lumière qui traverse les murs. Naïah suit le phénomène avec une attention silencieuse, sans chercher le même dénouement pour elle."),
        NC("Elle rallume la lampe, vous couvre et remet la tasse près de la vôtre. Le salon paraît plus petit ; sa main dans la vôtre suffit pourtant à garder l’espace ouvert."),
      ],
      explicite: [
        NC("La lanterne efface les angles du salon et change les meubles en pressions reconnaissables. Naïah garde vos mains dans les siennes afin que le logement réel reste toujours localisable.", ["Naïah", "Le canapé est derrière toi. La table à gauche. Moi partout où la distance devient mauvaise.", "thinking"]),
        NC("Un baiser rapproche le plafond sensoriel. Sa paume sous votre chemise chauffe tout un mur lorsqu’elle trouve votre sein ; la disproportion de l’écho la surprend et fait vaciller la lanterne.", ["Naïah", "Ta maison exagère. J’approuve.", "bright"]),
        NC("Vous retirez vos vêtements sur le canapé, puis Naïah se déshabille devant la lanterne. Les étoffes restent visibles sur les coussins ; vos deux corps sont réellement nus avant que l’espace partagé ne les agrandisse."),
        NC("La lumière violette glisse sur le corps nu de Naïah. Sa tasse tinte au bord de l’étagère ; une ombre la retient, puis elle revient contre vous sans effacer ce minuscule désordre domestique.", ["Naïah", "Elle reste. J’étais ici avant la magie et je serai ici après.", "soft"]),
        NC("Elle glisse sa main entre vos cuisses et caresse seulement l’extérieur. Chaque mouvement se répercute dans le canapé et les murs ; trop d’échos brouillent la sensation jusqu’à vous faire perdre le contact réel."),
        NC("Vous refermez vos doigts sur les siens et ramenez toute la pièce à une seule pression. Naïah dissipe les autres vagues avec une grimace.", ["Naïah", "Un seul geste gagne contre trente-sept. C’est une statistique insultante.", "annoyed"]),
        NC("Le mouvement redevient lisible. Sa paume suit votre chaleur, sa cuisse soutient votre bassin et le canapé renvoie une vibration lente sous vos omoplates ; Naïah observe ce que l’écho ajoute sans quitter ce que sa main produit."),
        NC("Vous retournez la vibration dans son ombre. Votre caresse sur sa cuisse lui revient depuis le dossier ; Naïah perd un instant le contrôle, rit dans votre cou et vous serre assez fort pour empêcher la pièce de s’éloigner davantage."),
        NC("Sa bouche rejoint ses doigts entre vos jambes. La chaleur de sa langue devient une lumière sous le sol, mais son rythme reste ancré dans votre corps réel. Vous guidez sa nuque lorsqu’un écho arrive trop tôt."),
        NC("Naïah corrige aussitôt, réduit la magie à un souffle qui précède chaque passage et murmure votre prénom contre vous.", ["{player}", "Plus lentement."], ["Naïah", "Je peux être lente. C’est le monde qui manque de patience.", "shaken"]),
        NC("Vous jouissez à travers toute la chambre d’ombre. Elle maintient le contact externe, perçoit les murs se contracter autour de vous et garde votre main nouée à la sienne jusqu’à ce que la lumière cesse de trembler."),
        NC("La pièce ordinaire revient autour de vos corps nus. Naïah tire le plaid sur vous, rallume la lampe et replace sa tasse ; sa chemise reste pourtant sur votre chaise.", ["Naïah", "Cette partie-là n’était pas magique. Elle peut donc rester.", "soft"]),
      ],
      ellipse: [
        NC("La lanterne transforme les meubles en pressions et les murs en distances. Naïah vous tient les mains afin que la maison réelle ne disparaisse jamais entièrement."),
        NC("Vos baisers modifient l’espace partagé. Une caresse sous la chemise devient chaleur sur un mur, souffle sous le sol et vibration dans le canapé."),
        NC("Vous retirez vos vêtements sur les coussins. Naïah se déshabille à son tour, puis vos corps nus rejoignent seulement après ce geste l’ombre élargie."),
        NC("La tasse menace de tomber ; elle la rattrape et rit. Vous choisissez de poursuivre cette intimité charnelle sans abandonner le logement à une illusion parfaite."),
        NC("L’obscurité violette garde hors champ une expérience de contacts externes et de sensations impossibles. Le récit revient lorsque les murs reprennent leur place."),
        NC("Naïah cherche votre main dans le salon redevenu petit. Elle ne demande pas ce que vous pensiez ; elle compare simplement la chaleur réelle à son écho immense."),
        NC("Vous vous rhabillez sur le canapé. Elle remet la tasse près de la vôtre et laisse sa chemise sur la chaise comme si l’objet avait choisi."),
        NC("La lanterne revient à la taille d’une luciole. Naïah l’accuse d’avoir exagéré la scène, puis l’embrasse du bout des doigts en croyant que vous ne regardez pas."),
      ],
    },
  },
  {
    id: "naiah-home-homme-shadow-room", context: "home-naiah", sex: "homme", concept: "chambre-ombre",
    text: "La chambre d’ombre", detail: "Naïah étend les sensations du logement dans un espace partagé que nul autre personnage ne pourrait ouvrir.",
    chapters: {
      tendre: [
        NC("Vous éteignez la lampe. La luciole de Naïah étire les ombres jusqu’à effacer les angles du salon, sans déplacer le moindre meuble réel."),
        NC("Elle prend vos mains et précise que la maison restera ici. Vous en sentirez seulement le volume autrement : chaleur des murs, poids du sol, souffle des rideaux."),
        NC("Vous restez vêtus sur le canapé. Le coussin sous vos épaules devient un îlot de pression et le reste de la pièce une distance souple."),
        NC("Naïah ajoute un plafond étoilé ; sa tasse ébréchée produit un tintement immense dans le partage et fait tomber toutes les constellations sur vous."),
        NC("Vous riez, puis elle renonce au spectacle. Vos doigts serrés deviennent le seul point lumineux et votre respiration dessine son corps sans le toucher."),
        NC("Votre main caresse sa joue. L’écho gagne les murs ; Naïah reste immobile, surprise qu’un geste minuscule dépasse soudain toute sa mise en scène."),
        NC("Elle réduit l’espace jusqu’à retrouver votre bouche. Le baiser existe sur vos lèvres et dans la chaleur du canapé, impossible mais toujours simple."),
        NC("Le salon revient. Tasse, lanterne et vêtements n’ont pas bougé ; Naïah garde votre main et affirme que le voyage n’a donc techniquement pas eu lieu."),
      ],
      suggestif: [
        NC("La lanterne avale les angles et transforme les meubles en pressions connues. Naïah vous conduit par les mains au cœur de votre propre salon."),
        NC("Vos baisers changent l’espace : un souffle rapproche le plafond, une paume sous la chemise réchauffe un mur lointain."),
        NC("Vos vêtements s’ouvrent et restent sur le canapé. Chaque zone de peau découverte donne une texture nouvelle à la pièce sans laisser passer aucune pensée."),
        NC("Sa tasse manque de tomber, résonne partout et brise le moment solennel. Naïah la rattrape, rit et revient contre votre torse encore secoué."),
        NC("Sa cuisse presse les vôtres ; l’écho se multiplie dans le sol. Une tentative trop confuse échoue, alors elle réduit la magie à sa main plus basse."),
        NC("L’ombre violette cache les gestes les plus charnels. Ils restent externes et reviennent vers votre corps comme des vagues venues des murs."),
        NC("Votre plaisir atteint son terme dans une lumière sans source. Naïah suit la forme de votre réaction, ravie sans réclamer que son corps fournisse une réponse symétrique."),
        NC("Elle rallume la lampe, vous couvre et replace sa tasse. Le salon paraît plus petit, mais sa main sur votre ventre garde quelque chose de l’espace partagé."),
      ],
      explicite: [
        NC("La lanterne efface les angles et change chaque meuble en pression reconnaissable. Naïah garde vos mains afin que vous puissiez toujours retrouver le canapé réel.", ["Naïah", "La table est une résistance. Le mur, une distance. Moi, un très mauvais repère.", "thinking"]),
        NC("Un baiser rapproche le plafond sensoriel. Sa paume presse votre désir à travers le pantalon ; la chaleur gagne aussitôt tout un mur et la surprend autant que vous.", ["Naïah", "Ta maison vient de rougir. C’est embarrassant pour elle.", "bright"]),
        NC("Vous retirez chemise, pantalon et dernière étoffe sur le canapé. Naïah se déshabille devant la lanterne ; vos vêtements restent visibles sur les coussins avant que vos corps nus n’entrent pleinement dans l’ombre."),
        NC("Le corps nu de Naïah prend les reflets violets de la pièce partagée. Sa tasse tinte sur l’étagère ; elle la rattrape d’une ombre, puis revient sur vos cuisses sans inventer le moindre autre décor.", ["Naïah", "La tasse reste. Elle sait déjà trop de choses.", "smirk"]),
        NC("Elle referme sa main autour de votre élan. Chaque mouvement se répercute dans le canapé et les murs ; Naïah ajoute tant d’ondes que votre plaisir se dissout dans une chaleur sans direction."),
        NC("Vous immobilisez son poignet et ramenez l’espace à sa paume réelle. Elle chasse les autres échos d’un souffle vexé.", ["Naïah", "Trente-deux effets battus par cinq doigts. Ne répète jamais cette humiliation.", "annoyed"]),
        NC("La cadence devient claire : sa main suit votre longueur, son pouce insiste près de la pointe et une seule pulsation revient du dossier au moment où vos hanches avancent. Naïah cesse de deviner et observe."),
        NC("Vous retournez l’onde sous sa propre cuisse. Elle sursaute, se cambre contre vous et rit de perdre la carte de votre salon.", ["{player}", "Tu voulais partager."], ["Naïah", "Je voulais surtout gagner.", "laugh"]),
        NC("Elle s’agenouille entre vos jambes et joint sa bouche à sa main. Sa langue joue autour de votre pointe tandis que l’écho parcourt votre ventre ; quand la vibration couvre le contact réel, vous la guidez plus près."),
        NC("Naïah simplifie sans protester. Sa bouche garde une chaleur continue, sa paume accompagne ce qu’elle ne couvre pas et la maison n’ajoute plus qu’un battement sourd sous le canapé.", ["Naïah", "Celui-là reste ?"], ["{player}", "Celui-là reste."]),
        NC("Vous jouissez à travers la chambre d’ombre. Elle ralentit avec les dernières pulsations, garde le contact jusqu’à votre détente et vous retient contre sa poitrine pendant que les murs cessent de vibrer."),
        NC("Le salon ordinaire revient autour de vos corps nus. Naïah tire le plaid sur vos jambes, rallume la lampe et replace sa tasse ; sa chemise demeure sur votre chaise.", ["Naïah", "Une trace réelle. Beaucoup plus difficile à dissiper.", "soft"]),
      ],
      ellipse: [
        NC("La lanterne transforme les meubles en pressions et les murs en distances. Naïah conserve vos mains pour que la maison réelle ne se perde jamais."),
        NC("Vos baisers modifient l’espace. Une caresse sous la chemise devient chaleur sur un mur, souffle sous le sol et vibration dans le canapé."),
        NC("Vous vous déshabillez sur les coussins. Naïah retire ses vêtements après vous ; vos corps nus rejoignent ensuite seulement l’ombre devenue immense."),
        NC("Sa tasse manque de tomber et brise la solennité. Vous riez, la sauvez et choisissez de poursuivre cette intimité charnelle dans le logement réel."),
        NC("L’obscurité violette garde hors champ les contacts externes et les sensations impossibles. Le récit revient lorsque chaque mur retrouve sa distance ordinaire."),
        NC("Naïah cherche votre poignet avant ses vêtements. Elle compare le battement réel à l’écho immense, sans demander ce que vous pensiez pendant l’expérience."),
        NC("Vous vous rhabillez sur le canapé. Elle remet la tasse près de la vôtre et abandonne sa chemise sur la chaise avec une indifférence beaucoup trop travaillée."),
        NC("La lanterne rétrécit jusqu’à une luciole. Naïah l’accuse d’avoir tout exagéré, puis la caresse lorsqu’elle croit votre regard tourné ailleurs."),
      ],
    },
  },
  {
    id: "naiah-home-femme-no-tricks", context: "home-naiah", sex: "femme", concept: "plus-de-tours",
    text: "Plus de tours", detail: "Vous interrompez sa provocation, retournez la situation et partagez une improvisation qu’aucune illusion n’avait préparée.",
    chapters: {
      tendre: [
        NC("Naïah lève un doigt pour annoncer une nouvelle épreuve. Vous l’attirez contre vous avant le premier mot ; son sort inachevé produit un canard de brume sous la table."),
        NC("Elle regarde le canard, puis votre bouche, incapable de décider quelle surprise mérite d’être traitée d’abord. Vous lui volez cette seconde hésitation avec un baiser."),
        NC("Naïah tente de reprendre le spectacle. Vous éteignez sa lanterne, gardez seulement la lumière ordinaire et lui demandez le prochain geste sans décor."),
        NC("Elle choisit de s’asseoir sur le tapis, dos contre le canapé. Vous la rejoignez ; le canard grimpe entre vous et reçoit une tasse vide comme casque."),
        NC("Votre main trouve sa nuque. Naïah ferme les yeux, puis essaie de vous surprendre en mordant doucement votre paume ; votre rire renverse encore son plan."),
        NC("Vous improvisez ainsi, chaque geste recevant une réponse inattendue plutôt qu’un score. Elle perd deux manches, en invente quatre et vous laisse néanmoins choisir le dernier baiser."),
        NC("Sa tasse rejoint les vôtres sur l’étagère tandis que le canard monte la garde. Naïah reste contre vous sans faire commenter le geste par une copie."),
        NC("Avant de dormir, elle réclame une revanche puis reconnaît seulement qu’elle ne sait pas encore contre quoi. Cette ignorance semble lui plaire énormément."),
      ],
      suggestif: [
        NC("Vous interrompez sa nouvelle provocation en l’attirant sur vos genoux. Le sort incomplet crée un canard de brume ; Naïah demeure, elle, très réelle contre vous."),
        NC("Votre baiser lui vole sa première règle. Elle essaie de guider vos mains, puis vous changez de place et la faites asseoir sur le tapis adossée au canapé."),
        NC("Vos chemises s’ouvrent sans compétition prévue. Naïah laisse tomber la sienne, surprise de la suivre plutôt que de conduire seule le déshabillage."),
        NC("Elle tente un geste spectaculaire qui vous fait rire au lieu de frissonner. Après une moue, elle demande seulement avec ses yeux que vous lui montriez ce que vous vouliez."),
        NC("Vous guidez sa main puis retirez la vôtre. Naïah essaie, vous observe et reprend la pression réussie avec une fourberie nouvellement acquise."),
        NC("Le tapis, le canapé et le plaid restent lisibles tandis que les gestes deviennent charnels hors champ. L’initiative circule sans qu’aucune de vous puisse préparer la scène entière."),
        NC("Votre plaisir la surprend au milieu d’une riposte. Elle s’arrête une seconde, rit doucement et revient au geste qui fonctionnait sans feindre l’infaillibilité."),
        NC("Vous terminez enlacées sur le tapis. Le canard porte encore sa tasse-casque ; Naïah réclame une revanche et vous laisse choisir quand elle commencera."),
      ],
      explicite: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort avorté produit un canard de brume ; elle reste bouche ouverte, réellement sans suite prévue.", ["Naïah", "Tu viens d’assassiner un tour magnifique."], ["{player}", "Il cancanait."]),
        NC("Votre baiser lui vole la conduite. Elle glisse une main sous votre chemise ; vous la faites asseoir sur le tapis et ouvrez sa tenue avant qu’elle puisse reconstruire les règles. Ses doigts restent un instant accrochés à votre col, sans nouveau plan."),
        NC("Vous vous déshabillez l’une l’autre sans alternance fixe. Chemises, pantalons et dernières étoffes rejoignent le dossier du canapé ; le canard tente d’emporter une manche avant que vos corps nus ne se retrouvent sur le plaid."),
        NC("Naïah demeure nue sur le sol, sans la moindre pose préparée. Le canard lui vole sa tasse ; son rire secoue son ventre contre votre cuisse et ruine avec bonheur toute tentative de séduction parfaite.", ["Naïah", "Je contrôle entièrement la situation."], ["{player}", "Il porte ta tasse sur la tête."]),
        NC("Vous pressez votre cuisse entre les siennes et la gardez sous vous. Naïah essaie de prévoir votre rythme ; vous l’interrompez à chaque changement, jusqu’à ce que ses mains cessent de diriger et s’agrippent simplement à vos épaules."),
        NC("Elle tente de reprendre l’initiative en glissant une main entre vos cuisses. Sa première caresse manque le point qui vous trouble ; vous couvrez ses doigts des vôtres et lui montrez la pression sans lui laisser transformer l’instant en démonstration."),
        NC("La seconde tentative obtient le souffle recherché. Naïah rayonne, recommence trop vite et perd l’effet.", ["Naïah", "Ça fonctionnait il y a une seconde."], ["{player}", "Alors écoute celle-ci.", "soft"], "Vous ralentissez sa main ensemble."),
        NC("Vous la renversez à votre tour et descendez vos baisers le long de sa poitrine et de son ventre. Naïah lève la tête vers le canard, comme s’il pouvait lui fournir une stratégie ; il répond en cachant sa tasse sous une aile."),
        NC("Elle profite de votre rire pour vous faire rouler. Sa bouche retrouve vos seins, puis votre chaleur. Vous tirez doucement ses cheveux pour changer l’angle ; Naïah accepte la correction et transforme le nouveau rythme en piège au passage suivant."),
        NC("Une ombre essaie d’attacher votre cheville. Vous la dissipez du pied sans éloigner Naïah.", ["Naïah", "C’était ma dernière ruse."], ["{player}", "Mensonge."], ["Naïah", "Évidemment.", "smirk"], "Sa langue ne quitte pas votre point sensible."),
        NC("Vous jouissez contre sa bouche, une main crispée sur le plaid. Naïah reste un instant surprise par l’intensité, puis maintient la caresse apprise jusqu’à votre apaisement avant de poser la joue sur votre cuisse."),
        NC("Vous restez nues sur le tapis et récupérez la tasse sous le canard scandalisé. Naïah pose votre main sur sa joue sans résumer la scène.", ["Naïah", "La prochaine fois, je veux perdre autrement.", "soft"], "Sa chemise reste sur votre canapé comme acompte de cette revanche."),
      ],
      ellipse: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort inachevé produit un canard de brume tandis qu’elle cherche réellement la suite."),
        NC("Votre baiser vole sa première règle. Vous la faites asseoir sur le tapis ; elle ouvre votre chemise sans savoir encore qui conduira le prochain geste."),
        NC("Vous vous déshabillez l’une l’autre et placez les vêtements sur le canapé. Vos corps nus rejoignent le plaid avant que le jeu ne devienne charnel."),
        NC("Le canard s’enfuit avec la tasse. Vous choisissez de continuer sans le dissiper, laissant cette absurdité réelle accompagner une improvisation à deux."),
        NC("Le récit garde hors champ la suite de caresses externes, de renversements et d’erreurs heureuses. Il revient quand le plaid ne couvre plus correctement personne."),
        NC("Naïah avoue uniquement qu’elle n’avait pas prévu la moitié de la scène. Elle nie que cette moitié ait été la meilleure, avec une mauvaise foi rayonnante."),
        NC("Vous vous rhabillez sur le tapis et récupérez la tasse. Le canard conserve une petite soucoupe en récompense de sa contribution involontaire."),
        NC("Naïah s’endort contre vous après avoir réclamé une revanche. Elle ne sait pas encore quel sera l’enjeu et cette incertitude rend son sourire presque paisible."),
      ],
    },
  },
  {
    id: "naiah-home-homme-no-tricks", context: "home-naiah", sex: "homme", concept: "plus-de-tours",
    text: "Plus de tours", detail: "Vous interrompez sa provocation, retournez la situation et partagez une improvisation qu’aucune illusion n’avait préparée.",
    chapters: {
      tendre: [
        NC("Naïah lève un doigt pour annoncer une épreuve. Vous l’attirez contre vous avant le premier mot ; son sort inachevé produit un canard de brume sous la table."),
        NC("Elle regarde le canard puis votre bouche, incapable de choisir quelle surprise mérite une réponse. Votre baiser profite de cette hésitation authentique."),
        NC("Naïah tente de reprendre son spectacle. Vous éteignez la lanterne, gardez la lumière ordinaire et lui demandez le prochain geste sans décor de secours."),
        NC("Elle choisit le tapis, dos contre le canapé. Vous vous asseyez près d’elle ; le canard s’installe entre vous avec une tasse vide sur la tête."),
        NC("Votre main caresse sa nuque. Naïah ferme les yeux, puis mord doucement votre paume pour retrouver l’avantage ; votre rire détruit encore le plan."),
        NC("Vous improvisez sans score durable. Elle perd deux manches, en invente quatre et vous laisse tout de même choisir le dernier baiser de la soirée."),
        NC("Sa tasse rejoint les vôtres sur l’étagère pendant que le canard monte la garde. Naïah reste contre votre torse sans demander à une copie de commenter."),
        NC("Elle réclame une revanche avant de dormir, puis admet qu’elle ignore encore contre quoi. Cette inconnue la rend visiblement heureuse."),
      ],
      suggestif: [
        NC("Vous interrompez sa provocation en l’attirant sur vos genoux. Le sort inachevé fabrique un canard de brume ; Naïah demeure très réelle contre votre ventre."),
        NC("Votre baiser efface sa première règle. Elle guide vos mains vers sa taille, puis vous changez la position et l’installez sur le tapis."),
        NC("Vos chemises s’ouvrent sans tour établi. Naïah laisse tomber la sienne, surprise de suivre une impulsion commune au lieu de mener seule le déshabillage."),
        NC("Elle essaie un geste théâtral qui vous fait rire. Après une moue, elle observe votre corps et vous laisse lui montrer ce que vous vouliez réellement."),
        NC("Vous guidez sa main plus bas, puis la retirez. Naïah tente la pression, voit votre réaction et reprend immédiatement le bon geste avec une satisfaction fourbe."),
        NC("Le tapis, le canapé et le plaid restent perceptibles tandis que les gestes deviennent charnels hors champ. L’initiative change avant que l’un de vous puisse écrire toute la scène."),
        NC("Votre plaisir la surprend pendant une riposte. Elle s’interrompt, sourit et revient au rythme qui fonctionnait sans prétendre l’avoir su dès le début."),
        NC("Vous terminez enlacés sur le tapis. Le canard porte encore sa tasse en casque ; Naïah réclame une revanche et vous laisse choisir le moment."),
      ],
      explicite: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort avorté produit un canard de brume ; elle reste un instant sans la moindre suite préparée.", ["Naïah", "Tu viens de tuer une catastrophe magnifique."], ["{player}", "Elle avait un bec."]),
        NC("Votre baiser prend l’initiative. Elle ouvre votre chemise et presse votre désir à travers le pantalon ; vous la faites asseoir sur le tapis avant qu’elle fixe les règles. Son sourire hésite entre défi et surprise véritable."),
        NC("Vous vous déshabillez l’un l’autre sans alternance nette. Chemises, pantalon, jupe et dernières étoffes rejoignent le canapé ; le canard s’empare d’une chaussette avant que vos corps nus ne s’installent sur le plaid."),
        NC("La lumière révèle Naïah nue sur le tapis, cherchant encore une attitude assez spectaculaire pour reprendre la main. Le canard vole sa tasse ; son rire fait trembler son ventre contre votre cuisse.", ["Naïah", "Tout demeure sous contrôle."], ["{player}", "Il boit dans ta tasse."]),
        NC("Elle enferme votre élan entre ses cuisses, tente un angle sans effet et fronce les sourcils. Vos mains déplacent ses hanches ; la seconde tentative vous fait répondre et elle rayonne avec une franchise trop rapide pour être jouée."),
        NC("Vous modifiez aussitôt la cadence et lui retirez cette certitude. Naïah s’accroche à vos épaules, suit votre bassin deux mouvements, puis tente de vous surprendre par une pression plus lente qu’elle n’avait pas annoncée."),
        NC("Vous la renversez sur le plaid, embrassez sa poitrine puis son ventre. Elle essaie de prédire où ira votre bouche ; vous changez de chemin chaque fois, jusqu’à ce qu’elle abandonne le commentaire et se contente de respirer contre votre main."),
        NC("Naïah vous fait rouler à son tour et referme sa paume autour de votre désir. Son premier mouvement est trop rapide ; vous posez votre main sur la sienne et imposez une cadence plus ample.", ["Naïah", "Je déteste les instructions utiles.", "annoyed"]),
        NC("Sa bouche remplace sa main. Elle accepte l’angle indiqué par vos hanches, garde ses lèvres autour de la pointe puis redescend lentement ; une ombre fraîche passe sur votre ventre et disparaît lorsque vous la jugez inutile."),
        NC("Le canard tire le plaid. Naïah rit sans vous lâcher, perd brièvement le rythme puis le retrouve seule, légèrement différent et plus efficace.", ["Naïah", "Ça, je l’ai inventé sans toi."], ["{player}", "Garde-le."]),
        NC("Vous jouissez contre sa bouche tandis que sa paume accompagne les dernières pulsations. Surprise par leur intensité, elle garde pourtant le mouvement appris jusqu’à votre détente et ne prétend savoir qu’après avoir vu votre souffle revenir."),
        NC("Vous restez nus sur le tapis et récupérez la tasse sous le canard scandalisé. Naïah pose votre main sur sa joue.", ["Naïah", "La prochaine fois, je veux perdre autrement.", "soft"], "Elle abandonne sa chemise sur le canapé pour s’assurer de revenir réclamer la revanche."),
      ],
      ellipse: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort inachevé produit un canard de brume pendant qu’elle cherche réellement la suite."),
        NC("Votre baiser vole sa première règle. Vous l’installez sur le tapis ; elle ouvre votre chemise sans savoir lequel de vous dirigera le prochain geste."),
        NC("Vous vous déshabillez ensemble et rangez les vêtements sur le canapé. Vos corps deviennent nus sur le plaid avant que le jeu ne prenne une direction franchement charnelle."),
        NC("Le canard s’enfuit avec la tasse. Vous laissez cette absurdité accompagner une improvisation dont aucune personne ne possède le scénario complet."),
        NC("Le récit garde hors champ les caresses externes, les renversements et les erreurs heureuses. Il revient lorsque le plaid ne couvre correctement aucun de vous."),
        NC("Naïah reconnaît n’avoir prévu que la moitié de la scène. Elle nie que l’autre moitié ait été meilleure, avec une mauvaise foi suffisamment brillante pour vous faire rire."),
        NC("Vous vous rhabillez sur le tapis et récupérez la tasse. Le canard garde une soucoupe minuscule en paiement de son intervention."),
        NC("Naïah s’endort contre votre poitrine après avoir exigé une revanche. Elle ignore encore son enjeu et sourit dans son sommeil comme devant un prochain tour."),
      ],
    },
  },
];
