import type { NaiahAuthoredScene } from "./naiah-date-intimacy-types";
import { NC } from "./naiah-date-intimacy-types";

export const NAIAH_HOME_INTIMACY_SCENES: NaiahAuthoredScene[] = [
  {
    id: "naiah-home-femme-hunt", context: "home-naiah", sex: "femme", concept: "terrain-chasse",
    text: "Terrain de chasse", detail: "Naïah retourne contre vous les habitudes de votre propre logement et découvre en chemin lesquelles troublent vraiment votre corps.",
    chapters: {
      tendre: [
        NC("Vous prenez votre place habituelle sur le canapé. Naïah disparaît derrière le dossier, alors que sa tasse reste bien visible près de la vôtre et trahit son intention de revenir."),
        NC("Ses mains couvrent vos yeux depuis l’arrière. Elle imite votre propre voix pour annoncer un danger imaginaire, puis rit lorsque vous l’attrapez par les poignets."),
        NC("Vous la faites basculer par-dessus le dossier. Naïah atterrit sur les coussins, surprise et ravie que son embuscade ait changé de propriétaire."),
        NC("Elle essaie de reprendre l’avantage avec trois copies cachées dans la pièce. Vous reconnaissez l’originale à son regard posé sur la tasse chaque fois qu’un double l’approche."),
        NC("Votre baiser la trouve sous la table. Une assiette illusoire proteste, un monstre minuscule s’enfuit avec une cuillère et Naïah oublie sa prochaine réplique."),
        NC("Vous revenez au canapé en échangeant les places à chaque rire. Le plaid passe de ses épaules aux vôtres puis finit autour de vous deux."),
        NC("Naïah pose sa tasse sur l’étagère sans annoncer qu’elle reste. Sa main rejoint la vôtre sous le plaid et son crâne trouve naturellement votre épaule."),
        NC("Elle s’endort ou feint de le faire jusqu’au moment où vous bougez. Un œil violet s’ouvre : « Mauvaise fuite. Recommence demain. »"),
      ],
      suggestif: [
        NC("Vous vous asseyez à votre place habituelle. Les mains de Naïah couvrent vos yeux depuis l’arrière tandis qu’une copie s’installe ostensiblement face à vous comme faux coupable."),
        NC("Vous saisissez l’originale et la faites passer sur le canapé. Son rire se brise dans un baiser ; elle découvre que le dossier soutient parfaitement vos hanches."),
        NC("Vos chemises s’ouvrent pendant une poursuite autour de la table. Naïah cache votre veste, vous capturez la sienne et les vêtements deviennent les trophées visibles du jeu."),
        NC("Elle essaie une caresse trop annoncée. Vous l’évitez et utilisez son élan pour la placer sous vous ; surprise, elle vous laisse mener jusqu’à ce qu’une ombre tire doucement votre cheville."),
        NC("Naïah revient entre vos cuisses, apprend à votre souffle quelle pression conserver et prétend avec aplomb que le canapé avait tout préparé."),
        NC("Le plaid recouvre une suite clairement sexuelle. Sa bouche, ses mains et quelques ombres tricheuses transforment chaque habitude du logement en point d’embuscade."),
        NC("Votre plaisir atteint son terme sur le canapé que vous croyiez connaître. Naïah reste concentrée sur votre réaction, ravie par le résultat plus que par une excitation propre."),
        NC("Elle remet la tasse sur l’étagère et laisse ses vêtements sur la chaise. Vous vous endormez sous le plaid ; au matin, elle nie avoir gagné puisqu’aucun score n’avait été annoncé."),
      ],
      explicite: [
        NC("Vous vous asseyez à votre place habituelle. Naïah surgit derrière le canapé, couvre vos yeux et annonce qu’elle vous fera jouir sans quitter la moitié de pièce que vous pensez connaître."),
        NC("Vous l’attrapez et la faites basculer sur les coussins. Elle rit contre votre bouche, glisse une main sous votre chemise et découvre la sensibilité de vos seins au bord du dossier."),
        NC("La chasse emporte vos vêtements : chemises sur la table, pantalons près du fauteuil, sous-vêtements sous le plaid. Naïah se déshabille en vous poursuivant jusqu’à ce que vous soyez nues devant le canapé."),
        NC("La CG révèle son corps dans votre salon. Sa tasse et la vôtre restent côte à côte ; elle vous attire sur les coussins, heureuse de voir le décor réel suffire à la scène."),
        NC("Naïah vous allonge, écarte vos cuisses et essaie avec ses doigts plusieurs caresses externes. Une pression trop basse ne produit rien ; elle remonte, entend votre souffle céder et sourit comme une voleuse."),
        NC("Vous la renversez, frottez votre cuisse entre les siennes puis l’obligez à improviser. Elle revient avec sa bouche sur vous, une main à votre sein et une ombre fraîche autour de vos hanches."),
        NC("Elle conserve les gestes qui fonctionnent jusqu’à vous faire jouir. Votre corps se tend contre sa langue ; Naïah vous regarde ensuite avec l’émerveillement satisfait d’une femme qui vient de découvrir un passage secret."),
        NC("Elle vous donne de l’eau, retrouve chaque vêtement et laisse pourtant sa chemise sur votre chaise. Nue sous le plaid, elle demande de revoir votre expression dès que vous aurez repris contenance."),
      ],
      ellipse: [
        NC("Vous prenez votre place habituelle. Naïah surgit derrière le canapé et annonce qu’elle va transformer vos habitudes en terrain de chasse avant la fin de la soirée."),
        NC("Vous retournez sa première embuscade et la faites basculer sur les coussins. Son baiser surpris lance une partie dont aucune règle n’a été annoncée."),
        NC("La poursuite emporte vos vêtements, déposés à des endroits précis de la pièce. Naïah retire les siens à son tour ; vos corps deviennent nus avant que le plaid ne monte."),
        NC("Vous choisissez ensemble de poursuivre ce jeu sexuel dans le salon réel. Sa tasse reste près de la vôtre et aucune illusion ne remplace le canapé sous vos corps."),
        NC("Le plaid garde hors champ les embuscades, les caresses et les renversements. Le récit revient lorsque vos vêtements forment un chemin impossible à expliquer par une visite sage."),
        NC("Naïah repose contre votre hanche, ravie que votre propre maison vous ait trahie. Vous lui rappelez qu’elle a perdu deux manches ; elle en invente une troisième rétroactive."),
        NC("Vous récupérez les vêtements un à un, sauf sa chemise qu’elle abandonne sur la chaise. La tasse retrouve l’étagère sans discussion."),
        NC("Au matin, elle surgit encore derrière le dossier pour tester votre sursaut. Vous l’attrapez sans regarder ; Naïah annonce une revanche avec une fierté immense."),
      ],
    },
  },
  {
    id: "naiah-home-homme-hunt", context: "home-naiah", sex: "homme", concept: "terrain-chasse",
    text: "Terrain de chasse", detail: "Naïah retourne contre vous les habitudes de votre propre logement et découvre en chemin lesquelles troublent vraiment votre corps.",
    chapters: {
      tendre: [
        NC("Vous prenez votre place habituelle. Naïah disparaît derrière le canapé, mais sa tasse demeure près de la vôtre et annonce qu’elle compte revenir."),
        NC("Ses mains couvrent vos yeux depuis le dossier. Elle imite votre voix pour décrire une attaque imaginaire, puis rit lorsque vous lui saisissez les poignets."),
        NC("Vous la faites passer par-dessus le dossier. Elle atterrit sur les coussins avec un cri ravi, première embuscade retournée avant d’avoir produit son grand effet."),
        NC("Trois copies se cachent dans la pièce. Vous repérez l’originale parce qu’elle surveille sa tasse chaque fois qu’une image s’en approche dangereusement."),
        NC("Votre baiser la trouve sous la table. Un monstre gros comme une pomme s’enfuit avec une cuillère et Naïah perd entièrement la phrase qu’elle préparait."),
        NC("Vous revenez au canapé en échangeant les places à chaque riposte. Le plaid passe de l’un à l’autre puis finit autour de vous deux."),
        NC("Naïah pose sa tasse sur l’étagère sans déclarer qu’elle reste. Sa tête vient contre votre poitrine et ses doigts s’installent dans les vôtres."),
        NC("Elle ferme les yeux jusqu’à ce que vous bougiez. Son sourire revient aussitôt : « Fuite médiocre. Je serai obligée de recommencer. »"),
      ],
      suggestif: [
        NC("Vous vous asseyez à votre place habituelle. Naïah couvre vos yeux depuis l’arrière tandis qu’un double innocent s’installe face à vous pour recevoir l’accusation."),
        NC("Vous saisissez l’originale et la faites passer sur le canapé. Son rire devient baiser ; elle découvre aussitôt que le dossier soutient parfaitement votre mouvement."),
        NC("Vos chemises s’ouvrent pendant une poursuite autour de la table. Elle cache votre veste, vous gardez la sienne et chaque vêtement devient un trophée concret."),
        NC("Naïah annonce une caresse trop tôt. Vous l’évitez, l’installez sous vous et menez le jeu jusqu’à ce qu’une ombre tire votre cheville au pire moment."),
        NC("Elle glisse alors une main plus basse, observe votre souffle et trouve la pression qui vous empêche de préparer la riposte suivante."),
        NC("Le plaid cache la suite devenue sexuelle. Sa bouche, sa main et les ombres du salon détournent une à une toutes les habitudes qui vous rassuraient."),
        NC("Votre plaisir atteint son terme sur le canapé familier. Naïah compte votre respiration sur ses doigts, rayonne comme après une victoire impossible et invente déjà la revanche pendant que vous récupérez."),
        NC("Elle replace sa tasse et abandonne sa veste sur la chaise. Au matin, elle nie avoir gagné puisque le score n’existait pas avant qu’elle décide du résultat."),
      ],
      explicite: [
        NC("Vous prenez votre place habituelle. Naïah surgit derrière le dossier et annonce qu’elle vous fera jouir sans quitter cette moitié du salon que vous croyez parfaitement connaître."),
        NC("Vous la saisissez et la faites basculer sur les coussins. Elle rit contre votre bouche, ouvre votre chemise et presse votre sexe à travers le pantalon pour découvrir votre première faiblesse."),
        NC("La chasse disperse vos vêtements : chemises sur la table, pantalons près du fauteuil, sous-vêtements sous le plaid. Naïah se déshabille en vous poursuivant jusqu’à ce que vous soyez nus devant le canapé."),
        NC("La CG révèle son corps dans votre salon. Sa tasse reste à côté de la vôtre ; Naïah vient à califourchon sur vos cuisses, enchantée que le décor réel suffise."),
        NC("Elle serre votre sexe entre ses cuisses, essaie un rythme trop rapide et reçoit votre rire. Elle ralentit, ajoute sa main et reproduit la pression exacte que vos hanches viennent de lui enseigner."),
        NC("Vous la renversez sur le canapé et reprenez l’initiative par des baisers le long de son torse. Elle s’échappe sous le plaid, revient à genoux et joint sa bouche à sa paume autour de vous."),
        NC("Elle vous fait jouir avec ce rythme appris, une ombre fraîche au ventre et sa main stable. Naïah observe votre visage, fascinée par le passage secret qu’elle vient de trouver dans une habitude ordinaire."),
        NC("Elle vous donne de l’eau, rassemble vos vêtements et laisse sa chemise sur la chaise. Nue contre vous sous le plaid, elle exige de revoir votre expression dès demain matin."),
      ],
      ellipse: [
        NC("Vous vous asseyez à votre place habituelle. Naïah surgit derrière le canapé et promet de changer chaque habitude rassurante en occasion de vous surprendre."),
        NC("Vous retournez son embuscade et la faites passer sur les coussins. Son rire surpris devient un baiser, puis une partie sans règle annoncée."),
        NC("La poursuite emporte vos vêtements, déposés à des endroits précis. Naïah retire les siens à son tour ; vos corps deviennent nus avant que le plaid vous couvre."),
        NC("Vous choisissez de poursuivre ce jeu sexuel dans le salon réel. Les deux tasses restent côte à côte et aucune illusion ne remplace le meuble sous vous."),
        NC("Le plaid garde hors champ les embuscades et les renversements. Le récit revient lorsque les vêtements forment un chemin absurde du canapé à la table."),
        NC("Naïah repose contre votre torse, ravie que la maison vous ait trahi. Vous comptez deux manches gagnées ; elle en ajoute une troisième dans le passé."),
        NC("Vous récupérez les vêtements un à un, sauf sa chemise abandonnée sur la chaise. Sa tasse retrouve l’étagère comme si elle y avait toujours vécu."),
        NC("Au matin, elle retente l’attaque derrière le dossier. Vous l’attrapez sans regarder ; Naïah réclame une revanche et semble immensément fière de perdre autrement."),
      ],
    },
  },
  {
    id: "naiah-home-femme-shadow-room", context: "home-naiah", sex: "femme", concept: "chambre-ombre",
    text: "La chambre d’ombre", detail: "Naïah étend les sensations du logement dans un espace partagé que nul autre personnage ne pourrait ouvrir.",
    chapters: {
      tendre: [
        NC("Vous éteignez la lampe. La lanterne de Naïah reste sur l’étagère ; sa luciole violette étire les ombres jusqu’à faire disparaître les angles du salon."),
        NC("Elle prend vos deux mains et précise que la maison demeure réelle. Vous sentirez seulement son volume autrement : chaleur des murs, pression du sol, souffle dans les rideaux."),
        NC("Vous restez vêtues sur le canapé. Le coussin sous vos épaules devient une île de poids tandis que le reste de la pièce se change en distance souple."),
        NC("Naïah tente d’ajouter un plafond étoilé. La tasse ébréchée produit alors un tintement gigantesque dans le partage et fait tomber toutes les constellations."),
        NC("Vous riez ensemble, puis elle retire le spectacle. Vos doigts serrés deviennent le seul point lumineux ; votre respiration dessine le contour de son corps sans le toucher."),
        NC("Une caresse sur sa joue se propage dans les murs. Naïah ne l’avait pas prévu et reste immobile, attentive à ce geste devenu plus grand que sa magie."),
        NC("Elle referme l’espace jusqu’à retrouver votre bouche. Le baiser existe à la fois sur vos lèvres et dans la chaleur du canapé, étrange sans cesser d’être doux."),
        NC("La pièce ordinaire revient. La lanterne, la tasse et les vêtements sur la chaise sont toujours là ; Naïah garde votre main comme seule preuve du voyage."),
      ],
      suggestif: [
        NC("La lanterne avale les angles du salon et transforme les meubles en pressions familières. Naïah vous conduit par les mains, sans créer une chambre étrangère à votre logis."),
        NC("Vos baisers modifient l’espace : un souffle rapproche le plafond, une main sous la chemise réchauffe le mur contre lequel aucun corps ne repose pourtant."),
        NC("Vous ouvrez vos vêtements et les laissez sur le canapé. Chaque peau découverte donne une texture nouvelle à la pièce partagée, toujours sans mêler vos pensées."),
        NC("La tasse résonne lorsqu’elle tombe presque ; Naïah la rattrape et rit. Ce petit accident réel empêche l’expérience de devenir une cérémonie trop parfaite."),
        NC("Sa cuisse trouve les vôtres et la sensation se multiplie dans le sol, les coussins et l’air. Une tentative confuse vous fait rire ; elle simplifie aussitôt."),
        NC("La suite devient sexuelle derrière une obscurité violette. Les gestes restent externes, mais leurs échos semblent parcourir toute la pièce et revenir vers vous."),
        NC("Votre plaisir atteint son terme comme une lumière qui traverse les murs. Naïah suit le phénomène avec une attention silencieuse, sans chercher le même dénouement pour elle."),
        NC("Elle rallume la lampe, vous couvre et remet la tasse près de la vôtre. Le salon paraît plus petit ; sa main dans la vôtre suffit pourtant à garder l’espace ouvert."),
      ],
      explicite: [
        NC("La lanterne efface les angles du salon et change les meubles en pressions reconnaissables. Naïah garde vos mains dans les siennes afin que le logement réel reste toujours localisable."),
        NC("Un baiser rapproche le plafond sensoriel. Sa paume sous votre chemise chauffe tout un mur lorsqu’elle trouve votre sein, surprise par la disproportion de l’écho."),
        NC("Vous retirez vos vêtements sur le canapé, puis Naïah se déshabille devant la lanterne. Les étoffes restent visibles sur les coussins avant que vos corps nus entrent dans l’espace partagé."),
        NC("La CG révèle Naïah dans la lumière violette. Sa tasse tinte au bord de l’étagère ; elle la stabilise d’une ombre puis revient à vous sans effacer le détail domestique."),
        NC("Elle glisse sa main entre vos cuisses et caresse seulement l’extérieur. Chaque mouvement se répercute dans le canapé et les murs ; trop d’échos brouillent d’abord la sensation, alors elle en conserve un seul."),
        NC("Vous posez votre main sur sa cuisse et modifiez la pression partagée. Naïah perd un instant le contrôle, rit dans votre cou, puis joint sa bouche à ses doigts pour suivre votre réaction réelle."),
        NC("Vous jouissez lorsque la chaleur traverse toute la chambre d’ombre. Elle maintient le contact externe, perçoit l’espace se contracter autour de vous et vous garde contre son torse jusqu’au calme."),
        NC("La pièce ordinaire revient autour de vos corps nus. Naïah vous couvre, apporte de l’eau et replace sa tasse ; sa magie disparaît, sa chemise reste pourtant sur votre chaise."),
      ],
      ellipse: [
        NC("La lanterne transforme les meubles en pressions et les murs en distances. Naïah vous tient les mains afin que la maison réelle ne disparaisse jamais entièrement."),
        NC("Vos baisers modifient l’espace partagé. Une caresse sous la chemise devient chaleur sur un mur, souffle sous le sol et vibration dans le canapé."),
        NC("Vous retirez vos vêtements sur les coussins. Naïah se déshabille à son tour, puis vos corps nus rejoignent seulement après ce geste l’ombre élargie."),
        NC("La tasse menace de tomber ; elle la rattrape et rit. Vous choisissez de poursuivre cette intimité sexuelle sans abandonner le logement à une illusion parfaite."),
        NC("L’obscurité violette garde hors champ une expérience de contacts externes et de sensations impossibles. Le récit revient lorsque les murs reprennent leur place."),
        NC("Naïah cherche votre main dans le salon redevenu petit. Elle ne demande pas ce que vous pensiez ; elle compare simplement la chaleur réelle à son écho immense."),
        NC("Vous vous rhabillez sur le canapé. Elle remet la tasse près de la vôtre et laisse sa chemise sur la chaise comme si l’objet avait choisi."),
        NC("La lanterne revient à la taille d’une luciole. Naïah l’accuse d’avoir exagéré la scène, puis l’embrasse du bout des doigts en croyant que vous ne regardez pas."),
      ],
    },
  },
  {
    id: "naiah-home-homme-shadow-room", context: "home-naiah", sex: "homme", concept: "chambre-ombre",
    text: "La chambre d’ombre", detail: "Naïah étend les sensations du logement dans un espace partagé que nul autre personnage ne pourrait ouvrir.",
    chapters: {
      tendre: [
        NC("Vous éteignez la lampe. La luciole de Naïah étire les ombres jusqu’à effacer les angles du salon, sans déplacer le moindre meuble réel."),
        NC("Elle prend vos mains et précise que la maison restera ici. Vous en sentirez seulement le volume autrement : chaleur des murs, poids du sol, souffle des rideaux."),
        NC("Vous restez vêtus sur le canapé. Le coussin sous vos épaules devient un îlot de pression et le reste de la pièce une distance souple."),
        NC("Naïah ajoute un plafond étoilé ; sa tasse ébréchée produit un tintement immense dans le partage et fait tomber toutes les constellations sur vous."),
        NC("Vous riez, puis elle renonce au spectacle. Vos doigts serrés deviennent le seul point lumineux et votre respiration dessine son corps sans le toucher."),
        NC("Votre main caresse sa joue. L’écho gagne les murs ; Naïah reste immobile, surprise qu’un geste minuscule dépasse soudain toute sa mise en scène."),
        NC("Elle réduit l’espace jusqu’à retrouver votre bouche. Le baiser existe sur vos lèvres et dans la chaleur du canapé, impossible mais toujours simple."),
        NC("Le salon revient. Tasse, lanterne et vêtements n’ont pas bougé ; Naïah garde votre main et affirme que le voyage n’a donc techniquement pas eu lieu."),
      ],
      suggestif: [
        NC("La lanterne avale les angles et transforme les meubles en pressions connues. Naïah vous conduit par les mains au cœur de votre propre salon."),
        NC("Vos baisers changent l’espace : un souffle rapproche le plafond, une paume sous la chemise réchauffe un mur lointain."),
        NC("Vos vêtements s’ouvrent et restent sur le canapé. Chaque zone de peau découverte donne une texture nouvelle à la pièce sans laisser passer aucune pensée."),
        NC("Sa tasse manque de tomber, résonne partout et brise le moment solennel. Naïah la rattrape, rit et revient contre votre torse encore secoué."),
        NC("Sa cuisse presse les vôtres ; l’écho se multiplie dans le sol. Une tentative trop confuse échoue, alors elle réduit la magie à sa main plus basse."),
        NC("L’ombre violette cache une suite clairement sexuelle. Les gestes restent externes et reviennent vers votre corps comme des vagues venues des murs."),
        NC("Votre plaisir atteint son terme dans une lumière sans source. Naïah suit la forme de votre réaction, ravie sans réclamer que son corps fournisse une réponse symétrique."),
        NC("Elle rallume la lampe, vous couvre et replace sa tasse. Le salon paraît plus petit, mais sa main sur votre ventre garde quelque chose de l’espace partagé."),
      ],
      explicite: [
        NC("La lanterne efface les angles et change chaque meuble en pression reconnaissable. Naïah garde vos mains afin que vous puissiez toujours retrouver le canapé réel."),
        NC("Un baiser rapproche le plafond sensoriel. Sa paume presse votre sexe à travers le pantalon ; la chaleur gagne aussitôt tout un mur et la surprend autant que vous."),
        NC("Vous retirez vêtements et sous-vêtement sur le canapé. Naïah se déshabille devant la lanterne ; les étoffes restent visibles avant que vos corps nus entrent pleinement dans l’ombre."),
        NC("La CG révèle son corps violet dans la pièce. Sa tasse tinte sur l’étagère ; Naïah la stabilise d’une ombre puis revient sur vos cuisses sans créer un autre décor."),
        NC("Elle referme sa main autour de votre sexe. Chaque mouvement se répercute dans le canapé et les murs ; trop d’échos brouillent d’abord votre plaisir, alors elle supprime tout sauf une onde précise."),
        NC("Vous guidez sa paume et caressez son ventre. Naïah rit de perdre un instant le contrôle, puis joint sa bouche à sa main en suivant uniquement les réactions de votre corps réel."),
        NC("Vous jouissez tandis que la chaleur traverse la chambre d’ombre. Elle ralentit, garde le contact externe et vous retient contre son torse jusqu’à ce que la pièce cesse de vibrer."),
        NC("Le salon ordinaire revient autour de vos corps nus. Naïah vous couvre, apporte de l’eau et replace sa tasse ; sa magie part, sa chemise reste sur votre chaise."),
      ],
      ellipse: [
        NC("La lanterne transforme les meubles en pressions et les murs en distances. Naïah conserve vos mains pour que la maison réelle ne se perde jamais."),
        NC("Vos baisers modifient l’espace. Une caresse sous la chemise devient chaleur sur un mur, souffle sous le sol et vibration dans le canapé."),
        NC("Vous vous déshabillez sur les coussins. Naïah retire ses vêtements après vous ; vos corps nus rejoignent ensuite seulement l’ombre devenue immense."),
        NC("Sa tasse manque de tomber et brise la solennité. Vous riez, la sauvez et choisissez de poursuivre cette intimité sexuelle dans le logement réel."),
        NC("L’obscurité violette garde hors champ les contacts externes et les sensations impossibles. Le récit revient lorsque chaque mur retrouve sa distance ordinaire."),
        NC("Naïah cherche votre poignet avant ses vêtements. Elle compare le battement réel à l’écho immense, sans demander ce que vous pensiez pendant l’expérience."),
        NC("Vous vous rhabillez sur le canapé. Elle remet la tasse près de la vôtre et abandonne sa chemise sur la chaise avec une indifférence beaucoup trop travaillée."),
        NC("La lanterne rétrécit jusqu’à une luciole. Naïah l’accuse d’avoir tout exagéré, puis la caresse lorsqu’elle croit votre regard tourné ailleurs."),
      ],
    },
  },
  {
    id: "naiah-home-femme-no-tricks", context: "home-naiah", sex: "femme", concept: "plus-de-tours",
    text: "Plus de tours", detail: "Vous interrompez sa provocation, retournez la situation et partagez une improvisation qu’aucune illusion n’avait préparée.",
    chapters: {
      tendre: [
        NC("Naïah lève un doigt pour annoncer une nouvelle épreuve. Vous l’attirez contre vous avant le premier mot ; son sort inachevé produit un canard de brume sous la table."),
        NC("Elle regarde le canard, puis votre bouche, incapable de décider quelle surprise mérite d’être traitée d’abord. Vous lui volez cette seconde hésitation avec un baiser."),
        NC("Naïah tente de reprendre le spectacle. Vous éteignez sa lanterne, gardez seulement la lumière ordinaire et lui demandez le prochain geste sans décor."),
        NC("Elle choisit de s’asseoir sur le tapis, dos contre le canapé. Vous la rejoignez ; le canard grimpe entre vous et reçoit une tasse vide comme casque."),
        NC("Votre main trouve sa nuque. Naïah ferme les yeux, puis essaie de vous surprendre en mordant doucement votre paume ; votre rire renverse encore son plan."),
        NC("Vous improvisez ainsi, chaque geste recevant une réponse inattendue plutôt qu’un score. Elle perd deux manches, en invente quatre et vous laisse néanmoins choisir le dernier baiser."),
        NC("Sa tasse rejoint les vôtres sur l’étagère tandis que le canard monte la garde. Naïah reste contre vous sans faire commenter le geste par une copie."),
        NC("Avant de dormir, elle réclame une revanche puis reconnaît seulement qu’elle ne sait pas encore contre quoi. Cette ignorance semble lui plaire énormément."),
      ],
      suggestif: [
        NC("Vous interrompez sa nouvelle provocation en l’attirant sur vos genoux. Le sort incomplet crée un canard de brume ; Naïah demeure, elle, très réelle contre vous."),
        NC("Votre baiser lui vole sa première règle. Elle essaie de guider vos mains, puis vous changez de place et la faites asseoir sur le tapis adossée au canapé."),
        NC("Vos chemises s’ouvrent sans compétition prévue. Naïah laisse tomber la sienne, surprise de la suivre plutôt que de conduire seule le déshabillage."),
        NC("Elle tente un geste spectaculaire qui vous fait rire au lieu de frissonner. Après une moue, elle demande seulement avec ses yeux que vous lui montriez ce que vous vouliez."),
        NC("Vous guidez sa main puis retirez la vôtre. Naïah essaie, vous observe et reprend la pression réussie avec une fourberie nouvellement acquise."),
        NC("Le tapis, le canapé et le plaid restent lisibles tandis que la suite devient sexuelle hors champ. L’initiative circule sans qu’aucune de vous puisse préparer la scène entière."),
        NC("Votre plaisir la surprend au milieu d’une riposte. Elle s’arrête une seconde, rit doucement et revient au geste qui fonctionnait sans feindre l’infaillibilité."),
        NC("Vous terminez enlacées sur le tapis. Le canard porte encore sa tasse-casque ; Naïah réclame une revanche et vous laisse choisir quand elle commencera."),
      ],
      explicite: [
        NC("Vous interrompez la provocation de Naïah en l’attirant nue d’intention sur vos genoux. Son sort avorté produit un canard de brume ; elle reste bouche ouverte, réellement sans suite prévue."),
        NC("Votre baiser lui vole la conduite. Elle glisse une main sous votre chemise ; vous la faites asseoir sur le tapis et ouvrez sa tenue avant qu’elle puisse reconstruire les règles."),
        NC("Vous vous déshabillez l’une l’autre sans alternance fixe. Chemises, pantalons et sous-vêtements rejoignent le dossier du canapé avant que vos corps nus se retrouvent sur le plaid posé au sol."),
        NC("La CG révèle Naïah sans mise en scène. Le canard lui vole sa tasse ; son rire secoue son ventre contre votre cuisse et ruine toute tentative de pose séduisante."),
        NC("Vous frottez votre cuisse entre les siennes, puis guidez sa main entre les vôtres. Sa première caresse externe manque le point sensible ; la seconde suit votre mouvement et obtient le souffle recherché."),
        NC("Naïah reprend l’initiative avec sa bouche sur vos seins puis entre vos cuisses. Vous tirez doucement ses cheveux pour changer l’angle ; elle accepte la correction et transforme aussitôt le nouveau rythme en piège."),
        NC("Vous jouissez contre sa langue, une main crispée sur le plaid. Naïah reste un instant surprise par l’intensité, puis sourit et maintient la caresse jusqu’à votre apaisement."),
        NC("Vous restez nues sur le tapis, buvez et récupérez la tasse du canard. Naïah ne résume rien : elle pose votre main sur sa joue et annonce seulement qu’elle veut perdre encore autrement."),
      ],
      ellipse: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort inachevé produit un canard de brume tandis qu’elle cherche réellement la suite."),
        NC("Votre baiser vole sa première règle. Vous la faites asseoir sur le tapis ; elle ouvre votre chemise sans savoir encore qui conduira le prochain geste."),
        NC("Vous vous déshabillez l’une l’autre et placez les vêtements sur le canapé. Vos corps nus rejoignent le plaid avant que le jeu devienne sexuel."),
        NC("Le canard s’enfuit avec la tasse. Vous choisissez de continuer sans le dissiper, laissant cette absurdité réelle accompagner une improvisation à deux."),
        NC("Le récit garde hors champ la suite de caresses externes, de renversements et d’erreurs heureuses. Il revient quand le plaid ne couvre plus correctement personne."),
        NC("Naïah avoue uniquement qu’elle n’avait pas prévu la moitié de la scène. Elle nie que cette moitié ait été la meilleure, avec une mauvaise foi rayonnante."),
        NC("Vous vous rhabillez sur le tapis et récupérez la tasse. Le canard conserve une petite soucoupe en récompense de sa contribution involontaire."),
        NC("Naïah s’endort contre vous après avoir réclamé une revanche. Elle ne sait pas encore quel sera l’enjeu et cette incertitude rend son sourire presque paisible."),
      ],
    },
  },
  {
    id: "naiah-home-homme-no-tricks", context: "home-naiah", sex: "homme", concept: "plus-de-tours",
    text: "Plus de tours", detail: "Vous interrompez sa provocation, retournez la situation et partagez une improvisation qu’aucune illusion n’avait préparée.",
    chapters: {
      tendre: [
        NC("Naïah lève un doigt pour annoncer une épreuve. Vous l’attirez contre vous avant le premier mot ; son sort inachevé produit un canard de brume sous la table."),
        NC("Elle regarde le canard puis votre bouche, incapable de choisir quelle surprise mérite une réponse. Votre baiser profite de cette hésitation authentique."),
        NC("Naïah tente de reprendre son spectacle. Vous éteignez la lanterne, gardez la lumière ordinaire et lui demandez le prochain geste sans décor de secours."),
        NC("Elle choisit le tapis, dos contre le canapé. Vous vous asseyez près d’elle ; le canard s’installe entre vous avec une tasse vide sur la tête."),
        NC("Votre main caresse sa nuque. Naïah ferme les yeux, puis mord doucement votre paume pour retrouver l’avantage ; votre rire détruit encore le plan."),
        NC("Vous improvisez sans score durable. Elle perd deux manches, en invente quatre et vous laisse tout de même choisir le dernier baiser de la soirée."),
        NC("Sa tasse rejoint les vôtres sur l’étagère pendant que le canard monte la garde. Naïah reste contre votre torse sans demander à une copie de commenter."),
        NC("Elle réclame une revanche avant de dormir, puis admet qu’elle ignore encore contre quoi. Cette inconnue la rend visiblement heureuse."),
      ],
      suggestif: [
        NC("Vous interrompez sa provocation en l’attirant sur vos genoux. Le sort inachevé fabrique un canard de brume ; Naïah demeure très réelle contre votre ventre."),
        NC("Votre baiser efface sa première règle. Elle guide vos mains vers sa taille, puis vous changez la position et l’installez sur le tapis."),
        NC("Vos chemises s’ouvrent sans tour établi. Naïah laisse tomber la sienne, surprise de suivre une impulsion commune au lieu de mener seule le déshabillage."),
        NC("Elle essaie un geste théâtral qui vous fait rire. Après une moue, elle observe votre corps et vous laisse lui montrer ce que vous vouliez réellement."),
        NC("Vous guidez sa main plus bas, puis la retirez. Naïah tente la pression, voit votre réaction et reprend immédiatement le bon geste avec une satisfaction fourbe."),
        NC("Le tapis, le canapé et le plaid restent perceptibles tandis que la suite devient sexuelle hors champ. L’initiative change avant que l’un de vous puisse écrire toute la scène."),
        NC("Votre plaisir la surprend pendant une riposte. Elle s’interrompt, sourit et revient au rythme qui fonctionnait sans prétendre l’avoir su dès le début."),
        NC("Vous terminez enlacés sur le tapis. Le canard porte encore sa tasse en casque ; Naïah réclame une revanche et vous laisse choisir le moment."),
      ],
      explicite: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort avorté produit un canard de brume ; elle reste un instant sans la moindre suite préparée."),
        NC("Votre baiser prend l’initiative. Elle ouvre votre chemise et presse votre sexe à travers le pantalon ; vous la faites asseoir sur le tapis avant qu’elle fixe les règles."),
        NC("Vous vous déshabillez l’un l’autre sans alternance nette. Chemises, pantalons et sous-vêtements rejoignent le canapé avant que vos corps nus s’installent sur le plaid."),
        NC("La CG révèle Naïah hors de toute pose. Le canard vole sa tasse ; son rire fait trembler son ventre contre votre cuisse et rend toute séduction parfaite impossible."),
        NC("Elle serre votre sexe entre ses cuisses, tente un angle sans effet et fronce les sourcils. Vos mains déplacent ses hanches ; la seconde tentative vous fait répondre et elle rayonne."),
        NC("Vous la renversez sur le plaid. Naïah reprend l’initiative avec sa main puis sa bouche, accepte la cadence indiquée par vos hanches et ajoute une ombre fraîche contre votre ventre."),
        NC("Vous jouissez dans sa bouche tandis que sa paume accompagne les dernières secousses. Surprise par l’intensité, elle garde pourtant le rythme appris jusqu’à votre détente."),
        NC("Vous restez nus sur le tapis, partagez de l’eau et récupérez la tasse. Naïah pose votre main sur sa joue et demande seulement de pouvoir perdre autrement la prochaine fois."),
      ],
      ellipse: [
        NC("Vous interrompez la provocation de Naïah en l’attirant sur vos genoux. Son sort inachevé produit un canard de brume pendant qu’elle cherche réellement la suite."),
        NC("Votre baiser vole sa première règle. Vous l’installez sur le tapis ; elle ouvre votre chemise sans savoir lequel de vous dirigera le prochain geste."),
        NC("Vous vous déshabillez ensemble et rangez les vêtements sur le canapé. Vos corps deviennent nus sur le plaid avant que le jeu prenne une direction sexuelle."),
        NC("Le canard s’enfuit avec la tasse. Vous laissez cette absurdité accompagner une improvisation dont aucune personne ne possède le scénario complet."),
        NC("Le récit garde hors champ les caresses externes, les renversements et les erreurs heureuses. Il revient lorsque le plaid ne couvre correctement aucun de vous."),
        NC("Naïah reconnaît n’avoir prévu que la moitié de la scène. Elle nie que l’autre moitié ait été meilleure, avec une mauvaise foi suffisamment brillante pour vous faire rire."),
        NC("Vous vous rhabillez sur le tapis et récupérez la tasse. Le canard garde une soucoupe minuscule en paiement de son intervention."),
        NC("Naïah s’endort contre votre poitrine après avoir exigé une revanche. Elle ignore encore son enjeu et sourit dans son sommeil comme devant un prochain tour."),
      ],
    },
  },
];
