import type { ChoiceData, DialogueLine, Effects, PeriodKey, StatKey } from "./game-data";
import type { AmbientDialogue } from "./ambient-dialogues";

const L = (speaker: string, text: string, mood?: string): DialogueLine => ({ speaker, text, mood });
const N = (text: string): DialogueLine => L("Narration", text);
const A = (text: string, mood = "smirk"): DialogueLine => L("Naïah", text, mood);
const P = (text: string): DialogueLine => L("{player}", text);
const Q = (
  id: string,
  text: string,
  stat: StatKey,
  response: DialogueLine[],
  effects: Effects,
): ChoiceData => ({ id, text, stat, response, effects: { ...effects, stats: { ...(effects.stats || {}), [stat]: 1 } } });
const scene = (
  id: string,
  title: string,
  prompt: string,
  choices: ChoiceData[],
  options: { minStage?: number; locations?: string[]; periods?: PeriodKey[]; mood?: string } = {},
): AmbientDialogue => ({ id, title, prompt, choices, ...options });

export const NAIAH_AMBIENT_LINES: AmbientDialogue[] = [
  scene("naiah-illusions", "La troisième Naïah", "Trois Naïah tournent autour de vous. Deux expliquent avec beaucoup de sérieux qu'elles sont les seules véritables ; la troisième fouille déjà votre sac. « Une seule ment, une seule triche et une seule a oublié les règles. »", [
    Q("nai-trois-r", "Suivre celle dont l'attention revient toujours vers les arbres.", "resonance", [N("Vous laissez parler les trois voix et regardez plutôt ce qu'elles surveillent. Une seule vérifie la même trouée entre deux plaisanteries."), P("La vraie garde le passage nord."), A("Et la fausse fouille ton sac avec beaucoup plus de talent. Choix difficile."), N("Les deux doubles éclatent. La véritable Naïah a déjà retenu la direction d'un bruit lointain.")], { trust: 4, affection: 1 }),
    Q("nai-trois-a", "Donner à chacune une mission différente et voir laquelle proteste.", "audace", [P("Une surveille le chemin, une rend mon sac et la dernière vient avec moi."), A("Autoritaire. Laquelle m'as-tu réservée ?"), P("Celle qui refuse la répartition."), N("Les trois Naïah protestent en même temps, puis la vraie rit la première."), A("Méthode contestable. Résultat charmant.")], { affection: 4, trust: 2 }),
    Q("nai-trois-l", "Comparer les empreintes plutôt que leurs visages.", "lucidite", [N("Deux silhouettes écrasent la mousse sans laisser de poids. La troisième a de la terre fraîche sur le talon."), P("Celle qui a marché jusqu'ici."), A("Ou celle qui a pensé à simuler la boue."), N("Elle vous montre son autre botte, parfaitement propre, et savoure votre doute."), A("Tu avais raison. Je refuse seulement que ce soit confortable.")], { trust: 5 }),
  ], { mood: "smirk" }),

  scene("naiah-baies", "Les baies violettes", "Naïah tient deux grappes presque identiques. « Celles de gauche tachent la langue. Celles de droite endorment un sanglier. J'ai oublié si je suis face à toi ou face au sanglier. »", [
    Q("nai-baie-r", "Observer quels fruits les oiseaux laissent intacts.", "resonance", [N("Les oiseaux ont vidé l'arbuste de gauche et n'approchent pas l'autre."), P("Nous partageons celles-ci."), A("Tu fais davantage confiance aux oiseaux qu'à moi."), P("Ils n'ont aucun intérêt à rendre le goûter dramatique."), A("Argument blessant et irréfutable."), N("Elle mange la première baie et sa langue devient aussitôt violette.")], { trust: 4, affection: 2 }),
    Q("nai-baie-l", "Repérer la poudre soporifique sur une seule tige.", "lucidite", [P("Les fruits ne sont pas différents. Tu as frotté cette grappe avec quelque chose."), N("Naïah retourne la tige. Une poussière grise marque son gant."), A("Je testais ton attention, pas ton système digestif. Le sanglier, lui, l'a reçue pour une blessure."), P("Tu aurais pu commencer par là."), A("Et perdre une excellente entrée ?")], { trust: 5 }),
    Q("nai-baie-a", "Lui faire choisir la première baie et prendre la même grappe.", "audace", [N("Naïah hésite juste assez pour trahir son jeu, puis choisit la baie la plus sombre."), P("La même."), A("Tu me fais confiance ?"), P("Je te rends responsable du goûter."), A("Beaucoup plus séduisant. Et plus dangereux pour ma réputation."), N("Les baies sont atrocement acides. Son rire l'est beaucoup moins.")], { affection: 5, desire: 1, trust: 1 }),
  ], { locations: ["forbidden"], mood: "smirk" }),

  scene("naiah-noms", "Les noms de la forêt", "Naïah pose la main sur un tronc couvert d'entailles. « Celui-ci s'appelle l'Oncle qui ment. Il indique toujours le mauvais sentier aux soldats et le bon aux enfants. Les arbres ont des critères. »", [
    Q("nai-arbre-r", "Lui demander comment l'arbre distingue les voyageurs.", "resonance", [A("Il ne distingue rien. Moi, si."), N("Elle vous montre les entailles : hautes pour les patrouilles, basses pour les petites mains qui cherchent leur chemin."), A("L'arbre reçoit tout le mérite et aucune plainte. C'est un excellent arrangement."), P("Tu l'as quand même nommé."), A("Je récompense mes complices.")], { trust: 5, affection: 1 }),
    Q("nai-arbre-a", "Lui proposer un nom ridiculement plus noble.", "audace", [P("Seigneur Écorce, gardien des Retours et duc de la Mousse."), N("Une pomme de pin tombe précisément sur votre épaule."), A("Il refuse le titre et te provoque en duel."), P("Mon témoin affirme qu'il a attaqué le premier."), A("Ton témoin possède une excellente impartialité.")], { affection: 4 }),
    Q("nai-arbre-l", "Lire dans les marques les changements de routes qu'il mémorise.", "lucidite", [N("Les entailles forment une chronique : crue, incendie, passage fermé, nouveau détour."), P("Ce n'est pas seulement un nom. C'est une carte qui grandit."), A("Enfin quelqu'un qui lit avant de caresser mystérieusement l'écorce."), N("Elle ajoute une marque pour le chemin emprunté aujourd'hui."), A("Celui-ci dira que tu as remarqué.")], { trust: 5 }),
  ], { locations: ["forbidden"], mood: "thinking" }),

  scene("naiah-ennui", "La corvée la plus lente", "Naïah est allongée dans l'herbe, entourée de vingt-sept galets alignés. « Je pratique l'ennui. Accessoirement, chaque pierre correspond à une balise que je dois vérifier avant la pluie. »", [
    Q("nai-ennui-s", "Compter les galets avec elle sans chercher à accélérer la tâche.", "sangFroid", [N("À chaque vibration lointaine, Naïah retourne une pierre. Le rythme est lent, mais jamais vide."), A("Tu sais rester sans produire un spectacle. C'est une compétence suspecte."), P("Vingt-deux."), A("Vingt-trois. La forêt vient de mentir sur la sixième."), N("Elle remet un galet à l'endroit et recommence le compte.")], { trust: 5 }),
    Q("nai-ennui-l", "Classer les galets selon la réponse des balises.", "lucidite", [N("Vous séparez les retours nets, tardifs et absents. Trois points dessinent la même zone."), P("Le retard se propage depuis le nord-ouest."), A("Mon ennui vient de gagner une destination."), N("Elle balaie les autres galets dans sa poche et garde les trois fautifs en main."), A("Je t'emmène. Tu portes les preuves extrêmement lourdes.")], { trust: 5, confluence: 1 }),
    Q("nai-ennui-a", "Inventer un enjeu absurde pour chaque pierre retournée.", "audace", [P("Si celle-ci répond, le chêne devient ministre. Si elle se tait, tu lui dois une chanson."), A("Tu viens de rendre l'entretien magique politiquement dangereux."), N("La balise répond. Naïah salue gravement le chêne."), A("Monsieur le ministre, votre premier décret sera d'interdire les chansons de {player}.")], { affection: 4 }),
  ], { minStage: 1, mood: "neutral" }),

  scene("naiah-oiseau", "L'oiseau qui ne chante pas", "Un oiseau d'illusion sautille sur le poignet de Naïah. Les couleurs et les battements d'ailes sont parfaits ; son bec s'ouvre sans produire un son. « J'ai imité sa forme. Le chant refuse de devenir une copie. »", [
    Q("nai-oiseau-r", "Écouter avec elle le véritable oiseau caché dans les branches.", "resonance", [N("Le chant vient par fragments, interrompu par le vent et une réponse plus lointaine."), A("Il change quand l'autre répond."), P("Ton illusion n'écoute personne."), N("Naïah fait pivoter le petit oiseau vers les branches. Au second appel, il produit une note maladroite."), A("Affreux. Donc probablement vivant.")], { trust: 5, confluence: 1 }),
    Q("nai-oiseau-a", "Prêter à l'illusion une voix héroïque et très grave.", "audace", [P("Je réclame des graines, un domaine et la chute de mes ennemis."), A("Enfin une interprétation fidèle."), N("L'oiseau bombe le torse, tombe du poignet et remonte en volant avec une dignité compromise."), A("Il t'engage comme porte-parole.")], { affection: 5 }),
    Q("nai-oiseau-l", "Comparer le mouvement de sa gorge à celui de l'original.", "lucidite", [N("L'illusion ouvre le bec, mais ne respire pas avant le son."), P("Tu copies le résultat sans le geste qui le produit."), A("Une erreur mécanique. Beaucoup moins poétique et nettement plus utile."), N("Elle ajoute un souffle. Une note trop aiguë jaillit ; l'oiseau réel répond tout de même."), A("Il a mauvais goût. Je l'aime déjà.")], { trust: 5, affection: 1 }),
  ], { minStage: 1, mood: "thinking" }),

  scene("naiah-tasse", "La tasse ébréchée", "Naïah sert le thé dans une coupe illusoire couverte de gemmes, puis boit dans une vieille tasse fêlée maintenue par une agrafe de cuivre. « Celle-ci impressionne. L'autre ne renverse pas le thé sur mes genoux. »", [
    Q("nai-tasse-l", "Examiner l'agrafe qui empêche la fissure de progresser.", "lucidite", [P("Tu l'as réparée trois fois."), A("Quatre. La deuxième réparation était très belle et parfaitement inutile."), N("Elle vous montre l'agrafe la plus récente, simple et solide."), A("J'apprends parfois. Ne répète surtout pas cela.")], { trust: 5 }),
    Q("nai-tasse-a", "Réclamer la coupe illusoire avec tout le protocole nécessaire.", "audace", [N("Naïah vous la tend avec une révérence. Le thé traverse le fond inexistant et s'arrête à un doigt de vos vêtements."), A("Votre Majesté vient d'être sauvée par une souveraine plus compétente."), P("Je soupçonne un complot de la vaisselle."), A("Le procès commence après le thé.")], { affection: 5 }),
    Q("nai-tasse-s", "Prendre une seconde tasse réelle et partager simplement le thé.", "sangFroid", [N("Vous choisissez un gobelet de bois sans commenter le contraste. Naïah attend le compliment symbolique qui ne vient pas."), A("Tu ne vas pas dire que ma tasse cassée est secrètement plus belle ?"), P("Non. Elle garde le thé chaud."), A("Enfin une personne qui respecte les objets laids et compétents."), N("Elle cogne doucement son bord de cuivre contre le vôtre.")], { trust: 4, affection: 2 }),
  ], { minStage: 1, mood: "smirk" }),

  scene("naiah-permission", "Le péage du corbeau", "Un corbeau illusoire garde un petit pont et exige des voyageurs qu'ils confessent leur pire chanson. Naïah observe une patrouille rebrousser chemin. « Il m'a donné l'autorisation. Son mandat est contestable, mais son jugement excellent. »", [
    Q("nai-farce-l", "Vérifier que la vraie route de retour reste ouverte derrière la patrouille.", "lucidite", [N("Le pont humilie les soldats, mais un sentier net les ramène hors de la forêt."), P("Tu les fais tourner sans les enfermer."), A("Ils peuvent repartir avec leur dignité abîmée et tous leurs membres. Je suis d'une générosité remarquable."), N("Le corbeau ajoute une seconde exigence concernant les bottes cirées.")], { trust: 5 }),
    Q("nai-farce-a", "Prêter serment comme adjoint·e officiel·le du corbeau.", "audace", [P("Je reconnais l'autorité du gardien du pont."), A("Promotion immédiate. Tu es responsable des refrains faux."), N("Le corbeau vous remet une plume violette. La patrouille vous aperçoit et accélère son repli."), A("Regarde : le service public fonctionne.")], { affection: 5 }),
    Q("nai-farce-s", "Attendre que les voyageurs soient sortis avant d'améliorer la farce.", "sangFroid", [N("Naïah retient une pluie de plumes jusqu'à ce que le dernier soldat atteigne le chemin sûr."), A("Tu imposes un calendrier à l'art."), P("J'évite surtout une panique sur le pont."), N("Dès la sortie franchie, les casques de la patrouille se mettent à chanter entre eux."), A("L'art accepte le compromis.")], { trust: 4, affection: 2 }),
  ], { minStage: 1, mood: "laugh" }),

  scene("naiah-chemin", "Le quatrième sentier", "Trois routes apparaissent : une sèche, une couverte de fleurs et une troisième qui sent la pluie. Naïah désigne le passage derrière vous. « Le quatrième est celui par lequel tu peux repartir. Je le compte parce que la forêt, elle, oublie parfois. »", [
    Q("nai-chemin-l", "Lire les traces qui révèlent l'usage réel de chaque route.", "lucidite", [N("Des roues ont creusé la voie sèche ; les fleurs cachent de petites empreintes ; l'odeur de pluie couvre du métal."), P("Convoi, animaux, patrouille."), A("Exact. La promenade romantique vient de devenir un rapport de circulation."), P("Tu avais déjà choisi laquelle fermer."), A("Oui. Je voulais voir si tu comprendrais pourquoi.")], { trust: 5 }),
    Q("nai-chemin-a", "Prendre la route de la patrouille avant qu'elle la ferme.", "audace", [N("Vous avancez de deux pas. Naïah vous attrape par l'arrière du manteau."), A("Audacieux ne signifie pas utile."), P("Je voulais voir ce qu'ils ont laissé."), N("Elle sourit, ferme le chemin derrière vous et vous tend une branche pour sonder le sol."), A("Mauvaise idée approuvée sous surveillance.")], { affection: 4, trust: 2 }),
    Q("nai-chemin-s", "Lui demander lequel doit rester ouvert, puis l'aider à le baliser.", "sangFroid", [A("La voie sèche. Les herboristes rentrent avant la nuit."), N("Vous placez des marques physiques pendant que Naïah éloigne les deux autres routes."), P("Pas de détour spectaculaire ?"), A("Ils transportent des remèdes. Même mon ego connaît parfois les priorités."), N("Elle ajoute tout de même une fleur violette sur la dernière borne.")], { trust: 5, affection: 1 }),
  ], { minStage: 1, mood: "thinking" }),

  scene("naiah-excuse", "Le sac rendu", "Un sac de berger pend à une branche, recousu avec un fil violet beaucoup trop voyant. « Mon piège l'a pris pour une patrouille. Le piège avait tort. Je corrige son erreur ; il refuse de rédiger la lettre. »", [
    Q("nai-excuse-l", "Vérifier avec elle que rien ne manque avant de rendre le sac.", "lucidite", [N("Vous inventoriez une couverture, deux outils, du fromage écrasé et un flacon intact."), A("Le fromage a subi l'essentiel des pertes."), P("Il faut le dire au propriétaire."), A("Je lui offrirai le responsable."), N("Une petite branche coupable apparaît dans le sac avec un écriteau d'excuse.")], { trust: 5 }),
    Q("nai-excuse-s", "Déposer le sac sur la route et laisser le berger le reprendre sans rencontre forcée.", "sangFroid", [N("Naïah ouvre un passage direct jusqu'au rocher où le berger reviendra chercher ses traces."), A("Pas d'apparition dramatique ?"), P("Il a surtout besoin de ses affaires."), A("Les victimes manquent parfois de sens artistique."), N("Elle pose le sac et efface ses propres empreintes, pas celles qui conduisent jusqu'à lui.")], { trust: 5, affection: 1 }),
    Q("nai-excuse-a", "Ajouter au colis une clochette qui avertira le prochain piège.", "audace", [A("Un cadeau utile qui sonne dès que ma forêt devient inconvenante ?"), P("Et qui t'empêchera de prétendre n'avoir rien entendu."), N("Naïah teste la clochette. Tous les pièges voisins répondent d'un tintement vexé."), A("Ils te détestent déjà. Excellente intégration.")], { affection: 4, trust: 3 }),
  ], { minStage: 2, mood: "thinking" }),

  scene("naiah-couronne", "La couronne du petit roi", "Une couronne de brindilles flotte entre les mains de Naïah. « Un enfant perdu me l'a donnée après que je l'ai ramené au chemin. Il m'a nommée reine des cailloux humides. Enfin un titre précis. »", [
    Q("nai-couronne-r", "Demander comment elle a obtenu la confiance de l'enfant.", "resonance", [A("Je lui ai montré que mes trois monstres avaient peur de sa couronne."), N("Elle fait apparaître les créatures, chacune reculant devant les brindilles avec une terreur exagérée."), P("Tu l'as laissé te sauver."), A("Exactement. Les enfants suivent mieux lorsqu'ils ont aussi un rôle dans l'histoire."), N("Elle repose la couronne sur un petit cairn au bord du chemin.")], { trust: 5, affection: 2 }),
    Q("nai-couronne-l", "Repérer sur les brindilles la route qu'ils ont parcourue.", "lucidite", [N("La boue, les feuilles et un fil accroché racontent le trajet jusqu'à la borne sud."), P("Tu l'as fait passer loin du ravin."), A("Le ravin refusait son audience."), P("Et la couronne ?"), A("Preuve officielle que la diplomatie forestière fonctionne.")], { trust: 4, confluence: 1 }),
    Q("nai-couronne-a", "Réclamer le poste de ministre des cailloux secs.", "audace", [A("Ambition démesurée. Il faudra vaincre le conseil des graviers."), P("Je suis prêt·e."), N("Naïah pose une branche de travers sur votre tête et convoque six pierres illusoires."), A("Première question : pourquoi sont-elles moins humides que les miennes ?")], { affection: 5 }),
  ], { minStage: 2, mood: "smirk" }),

  scene("naiah-jalousie", "La correction d'Allenna", "Naïah tient un schéma de patrouille signé par Allenna et en a redessiné chaque flèche en violet. « Sa version est efficace, austère et malheureusement excellente. J'envisage de l'améliorer uniquement pour des raisons scientifiques. »", [
    Q("nai-jal-l", "Identifier le point qu'Allenna a vu avant elle.", "lucidite", [P("Cette relève couvre la borne pendant le changement d'équipe."), A("Je l'avais vu."), P("Tu viens d'ajouter le cercle."), A("Je l'avais vu intérieurement."), N("Elle conserve la correction d'Allenna et déplace une seule flèche pour couvrir aussi le sentier civil."), A("Voilà. Maintenant je peux la critiquer honnêtement.")], { trust: 5 }),
    Q("nai-jal-r", "Reconnaître qu'elle respecte la compétence d'Allenna sans exiger qu'elle l'apprécie.", "resonance", [A("Merci de ne pas transformer une bonne carte en réconciliation familiale."), P("Elle reste bonne."), A("Atrocement."), N("Naïah plie le schéma avec soin au lieu de le brûler."), A("Je peux détester sa place et apprendre de son regard. Ne lui répète surtout pas la seconde partie.")], { trust: 6, affection: 1 }),
    Q("nai-jal-a", "Ajouter une flèche inutile et signer au nom d'une troisième sœur imaginaire.", "audace", [P("La mystérieuse Nallenah recommande un détour par les champignons."), A("Enfin une héritière raisonnable."), N("Naïah imite la signature militaire, puis ajoute une moustache au sceau."), A("Allenna saura que c'est moi au premier trait. Le jeu est de voir si elle corrige quand même la flèche.")], { affection: 5 }),
  ], { minStage: 3, mood: "thinking" }),

  scene("naiah-matin", "Le retour avant l'aube", "Naïah revient quand le ciel blanchit. Il y a de la boue sur sa manche, une coupure à la tempe et aucun sourire. En vous voyant, elle en affiche un trop grand. « Excellente nuit. Les braconniers recommandent cinq étoiles. »", [
    Q("nai-matin-s", "Lui tendre de quoi nettoyer la coupure avant de poser des questions.", "sangFroid", [N("Naïah considère le tissu, puis s'assied sur la pierre la plus proche."), A("Ils sont dehors. Deux blessés, aucun mort."), P("Et toi ?"), A("Présente et offensée."), N("Elle vous laisse nettoyer le sang. Le sourire disparaît sans que le danger revienne.")], { trust: 6, affection: 2 }),
    Q("nai-matin-l", "Lire les traces sur sa manche pour comprendre ce qui manque au récit.", "lucidite", [P("La boue vient du ravin et la corde a brûlé ta paume. Tu as retenu quelqu'un."), N("Naïah ouvre la main. La marque confirme le poids."), A("Un braconnier. Il a choisi de tomber avant de choisir de m'écouter."), P("Tu l'as ramené quand même."), A("Je voulais qu'il vive assez longtemps pour regretter sa stratégie.")], { trust: 6 }),
    Q("nai-matin-a", "Attendre qu'elle soit assise, puis noter que sa critique manque d'enthousiasme.", "audace", [P("Cinq étoiles, mais tu n'as gardé aucun souvenir ?"), A("J'ai leur piège."), N("Elle sort un ressort cassé de sa poche et retrouve enfin un sourire à sa taille réelle."), A("Je vais le transformer en dispositif qui leur vole leurs lacets."), P("Voilà une critique constructive."), A("Aide-moi à choisir la hauteur.")], { affection: 5, trust: 2 }),
  ], { minStage: 3, periods: ["aube", "matin"], mood: "neutral" }),

  scene("naiah-route", "Au-delà de sa brume", "À la halte du Fleuve bleu, Naïah suit les marques laissées par un convoi sorti de sa forêt. « Je vérifie seulement qu'ils n'ont pas amené mes problèmes avec eux. Ou les leurs chez moi. La nuance m'appartient. »", [
    Q("nai-route-l", "Comparer les roues au relevé du passage qu'elle a ouvert.", "lucidite", [N("Une cinquième monture a rejoint le groupe après la frontière. Ses fers portent une marque militaire."), P("Ils ont été suivis hors de la forêt."), A("Donc mon chemin a bien fait son travail. Leur route, moins."), N("Elle note le symbole sans déplacer la moindre brume hors de son territoire."), A("Nous prévenons la halte. Pas besoin que ma forêt joue à l'Empire.")], { trust: 5 }),
    Q("nai-route-s", "Surveiller le fleuve pendant qu'elle examine les traces.", "sangFroid", [N("Vous gardez la route visible tandis que Naïah mesure les empreintes et la profondeur des roues."), A("Rien n'est revenu vers la forêt."), P("Et vers eux ?"), A("Une piste de trop. Je vais laisser un avertissement aux bateliers."), N("Elle utilise du charbon et du papier plutôt qu'une illusion qui disparaîtrait loin d'elle.")], { trust: 5, affection: 1 }),
    Q("nai-route-a", "Suivre la cinquième piste jusqu'à son propriétaire.", "audace", [N("La trace mène à un éclaireur endormi derrière un talus, bottes encore couvertes de boue."), A("Tu veux le réveiller ou lui laisser un message humiliant ?"), P("Les deux."), N("À son réveil, l'homme trouve son cheval attaché devant le poste de garde et « DISCRET » écrit sur sa cape."), A("Une collaboration exemplaire.")], { affection: 4, trust: 2 }),
  ], { locations: ["river-halt"], minStage: 2, mood: "thinking" }),

  scene("naiah-court", "Le procès des pierres", "Dans les ruines, trois pierres sont alignées devant Naïah. « Celle-ci accuse une botte impériale, celle-là un sabot obscurci et la dernière refuse de témoigner sans avocat. La frontière traverse une crise judiciaire. »", [
    Q("nai-court-l", "Comparer la terre prise dans chaque empreinte.", "lucidite", [N("La première vient du chemin sec, la deuxième du marais et la troisième porte de la cendre récente."), P("Le troisième passage n'apparaît pas sur tes routes."), A("Le témoin récalcitrant devient soudain essentiel."), N("Elle abandonne sa posture de juge et range la pierre dans un sachet d'analyse."), A("Audience levée. Nous traquons la cendre.")], { trust: 5, confluence: 1 }),
    Q("nai-court-a", "Assurer la défense de la pierre silencieuse.", "audace", [P("Ma cliente invoque le droit de ne pas s'incriminer."), A("Objection : ta cliente est un caillou."), P("Préjugé minéral."), N("Naïah condamne finalement la botte impériale à être remplie de glands."), A("Justice rapide, appel impossible. Mon système est parfait.")], { affection: 5 }),
    Q("nai-court-r", "Sentir laquelle des traces a croisé une protection active.", "resonance", [N("Une faible vibration persiste dans la pierre couverte de cendre. Quelqu'un a traversé une brume de renvoi sans repartir."), P("Celle-ci a franchi ton réseau."), N("Naïah ne répond pas tout de suite. Son sourire disparaît tandis qu'elle observe les ruines."), A("Alors le procès devient une chasse.", "neutral")], { trust: 5, confluence: 2 }),
  ], { locations: ["forbidden"], minStage: 2, mood: "smirk" }),

  scene("naiah-lignage", "Le blason sous la pluie", "Naïah a tendu un ancien morceau d'étoffe aux couleurs d'Akuhn’Nabad au-dessus d'une balise. « On l'appelait héritage. Aujourd'hui, il empêche l'eau d'entrer dans un mécanisme. Promotion méritée. »", [
    Q("nai-lignage-l", "Reconnaître les coutures prévues pour un ancien étendard de route.", "lucidite", [P("Ce n'était pas un drapeau de salle. Les attaches servaient déjà dehors."), A("Une bannière de passage, avant que les héritiers ne préfèrent les murs."), N("Elle trouve la couture renforcée et l'adapte à la borne sans déchirer le blason."), A("L'objet se souvient mieux de son travail que la cour.")], { trust: 5 }),
    Q("nai-lignage-s", "L'aider à protéger la balise sans décider ce que l'étoffe doit signifier.", "sangFroid", [N("Vous tendez une seconde corde. Naïah choisit elle-même quel coin nouer et lequel laisser libre."), P("Cela tiendra jusqu'à la fin de la pluie."), A("Après, je déciderai si je le garde, le rends ou en fais une cape pour sanglier."), N("Le choix reste ouvert ; la balise, elle, reste sèche.")], { trust: 5, affection: 1 }),
    Q("nai-lignage-a", "Proposer d'ajouter au blason le symbole de la Forêt.", "audace", [A("Une branche ? Trop attendu."), P("Le sorbier vexé."), N("Naïah éclate de rire et dessine un arbre tordu dans un coin intérieur, invisible de loin."), A("Voilà. Mon lignage possède enfin un sens de l'humour.")], { affection: 5 }),
  ], { locations: ["forbidden"], minStage: 2, mood: "thinking" }),

  scene("naiah-caillou", "La pierre qui compte", "Naïah fait sauter un petit caillou gris dans sa paume. À chaque lancer, une balise lointaine répond. « Il n'est ni maudit ni royal. C'est un compteur. Ce qui le rend beaucoup plus utile que la plupart des reliques. »", [
    Q("nai-caillou-r", "Suivre la Résonance qui revient de chaque lancer.", "resonance", [N("La première réponse est claire, la seconde faible et la troisième dédoublée."), P("Deux balises répondent au troisième signal."), A("Ou une seule a appris à mentir."), N("Elle cesse de plaisanter, lance le caillou une quatrième fois et retient la direction du double écho."), A("Nous allons vérifier.")], { trust: 5, confluence: 2 }),
    Q("nai-caillou-l", "Noter l'ordre des réponses sur la carte.", "lucidite", [N("Les intervalles dessinent la distance entre les points de protection."), P("La borne du ravin répond trop vite."), A("Quelqu'un l'a rapprochée, ou a placé une copie."), N("Naïah vous confie le caillou pendant qu'elle replie la carte."), A("Garde le conseiller. Il a trouvé sa première crise.")], { trust: 5 }),
    Q("nai-caillou-a", "Le nommer officiellement ministre des réponses tardives.", "audace", [A("Il accepte, mais réclame un bureau."), P("Ma poche est disponible."), N("Vous rangez le caillou. Une balise répond depuis le tissu avec un éclat violet."), A("Il travaille déjà mieux que plusieurs conseils royaux.")], { affection: 4 }),
  ], { mood: "smirk" }),

  scene("naiah-permission-simple", "La question utile", "Naïah vous tend une plaque de cuivre devant une balise. « Quand je lance l'essai, elle va chauffer. Tu peux tenir le repère, me donner le rythme ou regarder de loin. Les trois servent réellement. »", [
    Q("nai-attend-s", "Choisir d'observer à distance et annoncer les changements du sentier.", "sangFroid", [N("Vous reculez jusqu'à la borne sûre. À l'activation, une fausse pente apparaît sur la gauche."), P("La route se dédouble après le troisième battement."), A("Information reçue, personne brûlée. Choix étonnamment productif."), N("Elle corrige la balise sans vous demander de vous rapprocher.")], { trust: 5 }),
    Q("nai-attend-r", "Donner le rythme pendant qu'elle tient elle-même la plaque.", "resonance", [N("Vous comptez les vibrations ; Naïah ajuste chaque couche au nombre annoncé."), P("Deux… pause… trois."), A("Ne te laisse pas séduire par la régularité. Elle ment au quatrième."), N("Vous marquez l'écart. La plaque chauffe dans ses mains, pas dans les vôtres."), A("Voilà une aide qui ne prétend pas lancer le sort.")], { trust: 5, confluence: 1 }),
    Q("nai-attend-a", "Tenir le repère avec des gants et lui demander l'essai le plus difficile.", "audace", [A("Tu choisis la chaleur et tu réclames en plus le problème intéressant."), P("J'ai des gants et une borne de repli."), N("L'essai secoue la plaque, mais vous annoncez avant chaque limite. Naïah coupe exactement au dernier signal."), A("Audace préparée. C'est presque une contradiction séduisante.")], { affection: 4, trust: 3 }),
  ], { minStage: 1, mood: "thinking" }),

  scene("naiah-bruit", "Le bruit entre les branches", "Naïah s'arrête au milieu d'une phrase. Au loin : une branche, puis un tintement de métal. Son sourire disparaît et elle ne dit plus qu'un mot. « Là. »", [
    Q("nai-bruit-s", "Rester immobile jusqu'à ce qu'elle indique une direction sûre.", "sangFroid", [N("Vous attendez. Le métal tinte de nouveau, plus bas ; un fil vient d'être tendu entre deux troncs."), A("Piège."), P("Le nôtre ?"), A("Non."), N("Elle vous désigne le chemin de contournement et avance sans ajouter de plaisanterie.")], { trust: 6 }),
    Q("nai-bruit-l", "Séparer les deux sources sonores avant d'avancer.", "lucidite", [P("La branche vient du nord. Le métal, de l'ouest. Quelqu'un veut que nous suivions le premier bruit."), N("Naïah tourne déjà vers l'ouest. Un sourire bref revient, sans alléger son regard."), A("Tu viens de gagner le droit de marcher derrière moi et de ne toucher à rien."), P("Récompense somptueuse."), A("Chut.", "neutral")], { trust: 6 }),
    Q("nai-bruit-r", "Écouter ce que les animaux ont cessé de faire autour du bruit.", "resonance", [N("Les oiseaux se sont tus à l'ouest, mais continuent au nord. La menace se trouve près du métal."), P("Ils évitent la zone du tintement."), N("Naïah acquiesce. La brume s'aplatit au sol et dessine une ligne vers un piège étranger."), A("Bon regard. Maintenant, moins de voix.", "neutral")], { trust: 6, confluence: 1 }),
  ], { mood: "neutral" }),
];
