import type { NaiahAuthoredScene } from "./naiah-date-intimacy-types";
import { NC } from "./naiah-date-intimacy-types";

export const NAIAH_EDGE_INTIMACY_SCENES: NaiahAuthoredScene[] = [
  {
    id: "naiah-edge-femme-thread", context: "date-naiah-akuhn", sex: "femme", concept: "perdre-le-fil",
    text: "Perdre le fil", detail: "Naïah se donne huit minutes pour vous faire oublier la ronde que vous vouliez encore suivre.",
    chapters: {
      tendre: [
        NC("Vous annoncez la prochaine relève. Naïah se place exactement entre vos yeux et les remparts, puis lève huit doigts : autant de minutes pour ruiner votre concentration."),
        NC("Elle commence par imiter le capitaine, puis fait marcher les cailloux sur votre genou. Vous continuez de compter malgré la garnison miniature qui escalade votre manche."),
        NC("Naïah essaie un baiser soudain. Vous dites « six minutes » contre sa bouche ; son rire chaud vous fait presque perdre le nombre qu’elle cherchait."),
        NC("Elle vous enveloppe dans sa cape sans quitter votre champ de vision. La chaleur rapproche vos épaules et transforme chaque observation de la ville en murmure partagé."),
        NC("Vous ripostez en déplaçant sa pierre noire pendant qu’elle vous distrait. Naïah découvre trop tard que sa porte imaginaire vient de tomber et applaudit votre tricherie."),
        NC("Ses doigts jouent ensuite avec les vôtres au-dessus du plan. Chaque caresse déplace une pièce ; la bataille devient illisible, mais votre rire reste parfaitement localisable."),
        NC("La relève change sans que vous regardiez. Naïah ne proclame pas sa victoire : elle suit votre regard vers la ville et pose simplement sa tempe contre la vôtre."),
        NC("Vous recomptez ensemble les lanternes après coup. Elle en invente une neuvième en forme de grimace, preuve que le jeu n’a pas entièrement cédé au silence."),
      ],
      suggestif: [
        NC("Naïah vous donne huit minutes pour observer la relève. Elle s’assied face à vous, genoux entre les vôtres, et promet que le dernier chiffre ne franchira pas votre bouche."),
        NC("Ses baisers arrivent entre vos comptes. Une main suit votre taille sous la cape ; elle retient aussitôt le frisson qui vous fait hésiter à « six »."),
        NC("Elle ouvre votre veste puis la sienne afin de partager la chaleur. Vos chemises restent encore en place, mais ses doigts apprennent déjà les chemins qui interrompent votre voix."),
        NC("Une tentative trop théâtrale vous laisse imperturbable. Naïah boude une seconde, glisse sa cuisse entre les vôtres et découvre une réaction beaucoup moins facile à dissimuler."),
        NC(["Naïah", "Quatre. Non, attends. Tu devais compter.", "teasing"], "Elle recommence la pression, fière d’un effet qu’elle vient manifestement de découvrir."),
        NC("Sous la cape, ses mains et sa bouche font disparaître le reste du monde hors champ. La ronde poursuit son trajet ; vous perdez enfin le fil dans une respiration brisée."),
        NC("Le plaisir arrive avant la huitième minute. Naïah reste attentive au rythme trouvé, sans chercher pour elle-même une preuve équivalente ni détourner l’instant vers son corps."),
        NC("Lorsque vous regardez de nouveau la ville, deux relèves sont passées. Naïah remet votre veste en place et annonce un temps officiel entièrement falsifié."),
      ],
      explicite: [
        NC("Naïah vous accorde huit minutes pour suivre la relève, puis s’agenouille entre vos jambes. Elle gagnera si elle vous fait jouir avant que la dernière patrouille atteigne la porte."),
        NC("Elle embrasse votre bouche, ouvre votre veste et cherche sous votre chemise le geste capable de casser votre compte. Ses doigts sur vos seins trouvent la réponse au troisième essai."),
        NC("À l’abri de l’arche, vous retirez vos vêtements et les placez sous la cape pour les protéger de la pierre froide. Naïah se déshabille à son tour avant de vous attirer sur le tissu."),
        NC("Sous l’arche, vos vêtements abandonnés ne cachent plus rien de vos corps nus. Naïah garde un instant les remparts dans son dos, puis vient remplir elle-même tout votre regard dès que vous recommencez à compter."),
        NC("Elle glisse sa cuisse contre l’extérieur de votre plaisir, essaie un rythme qui vous agace plus qu’il ne vous trouble, puis corrige aussitôt en voyant vos hanches chercher une pression plus lente."),
        NC("Vous renversez Naïah sur la cape et l’embrassez jusqu’à lui voler son sourire, mais elle se dégage par une ombre et revient entre vos cuisses. Sa bouche et ses doigts restent externes, précis grâce à vos réactions."),
        NC("La patrouille atteint la porte tandis que vous jouissez contre sa langue. Naïah maintient sa main sur votre hanche, compte elle-même les dernières secousses et oublie totalement d’annoncer sa victoire."),
        NC("Elle vous couvre avant de chercher les vêtements, puis ferme votre col avec des doigts encore maladroits. Quand vous lui demandez l’heure, Naïah invente trois réponses avant d’admettre qu’elle aussi a perdu le fil."),
      ],
      ellipse: [
        NC("Naïah vous donne huit minutes pour suivre la relève et se place entre vous et les remparts. Son but déclaré est de rendre le dernier chiffre impossible à prononcer."),
        NC("Elle intercale des baisers dans votre compte, essaie une main sous la cape et apprend très vite quelle proximité fragilise votre concentration."),
        NC("Vous gagnez l’abri de l’arche, retirez vos vêtements et les rangez sous la cape. Naïah se déshabille après vous, sans qu’aucune image nue précède ces gestes."),
        NC("Nues sur le tissu, vous décidez de poursuivre le défi. La ville reste visible, assez lointaine pour ne plus commander le rythme de ce qui commence."),
        NC("La cape et l’ombre gardent hors champ une suite clairement sexuelle. Le récit revient bien après la relève, lorsque Naïah tente de compter les cailloux éparpillés."),
        NC("Elle a gagné son défi et perdu son plan. Vous retrouvez une pierre sous votre hanche ; Naïah accuse la ville de sabotage avec un aplomb remarquable."),
        NC("Vous remettez vos vêtements dans le froid revenu. Elle ferme votre veste, garde ses doigts sur le col et vérifie que vous tremblez seulement de la température."),
        NC("Deux rondes plus bas, une lanterne s’éteint. Naïah annonce huit minutes exactes, puis vous embrasse avant que vous puissiez contester son mensonge."),
      ],
    },
  },
  {
    id: "naiah-edge-homme-thread", context: "date-naiah-akuhn", sex: "homme", concept: "perdre-le-fil",
    text: "Perdre le fil", detail: "Naïah se donne huit minutes pour vous faire oublier la ronde que vous vouliez encore suivre.",
    chapters: {
      tendre: [
        NC("Vous annoncez la prochaine relève. Naïah s’installe dans votre champ de vision et lève huit doigts : autant de minutes pour faire disparaître votre sérieux."),
        NC("Elle imite le capitaine, puis fait escalader votre manche par une armée de cailloux. Vous continuez de compter pendant qu’un noyau tente de conquérir votre épaule."),
        NC("Naïah essaie un baiser soudain. Vous murmurez « six minutes » contre ses lèvres ; son rire manque davantage de vous vaincre que sa stratégie entière."),
        NC("Elle partage sa cape et vient entre vos jambes sans cacher la ville. Vos observations deviennent des phrases courtes, prononcées contre ses cheveux."),
        NC("Vous profitez de sa diversion pour déplacer la pierre noire. Naïah découvre que sa porte imaginaire est tombée et vous accuse de saboter une opération sentimentale."),
        NC("Ses doigts se mêlent aux vôtres au-dessus du plan. Chaque contact renverse une pièce ; vous laissez la bataille se perdre puisque son sourire, lui, reste lisible."),
        NC("La relève change sans que vous la regardiez. Naïah suit votre attention revenue vers les murs et garde sa tête contre votre poitrine, sans réclamer le score."),
        NC("Vous recomptez ensemble les lanternes. Elle ajoute une tour minuscule portant votre coiffure, uniquement pour ruiner la gravité du souvenir."),
      ],
      suggestif: [
        NC("Naïah vous laisse huit minutes pour surveiller la ronde. Elle se place entre vos cuisses et promet que votre compte cédera avant la dernière lanterne."),
        NC("Ses baisers coupent les nombres. Une main descend sous la cape, suit votre ventre et repère le souffle qui se brise lorsqu’elle atteint votre ceinture."),
        NC("Elle ouvre votre veste puis la sienne pour partager la chaleur. Vos chemises restent sur vous, mais ses doigts ont déjà trouvé comment rendre votre voix moins stable."),
        NC("Une grande illusion sensuelle ne vous arrache qu’un rire. Vexée, Naïah essaie une pression plus simple de la paume et découvre aussitôt ce qu’elle cherchait."),
        NC(["Naïah", "Je savais. Mon hésitation faisait partie du spectacle.", "smirk"], "Vous ne la croyez pas ; elle recommence au milieu de votre chiffre suivant."),
        NC("Sous la cape, le reste de ses gestes disparaît hors champ. La ville continue sa ronde pendant que votre compte se défait entre sa main, sa bouche et ses tricheries."),
        NC("Votre plaisir atteint son terme avant la dernière minute. Naïah garde le rythme appris, oublie d’annoncer sa victoire et contemple votre abandon avec une joie presque féroce."),
        NC("Elle referme votre veste, glisse un caillou dans votre poche et annonce une heure entièrement fausse. Vous n’avez plus assez de concentration pour la corriger."),
      ],
      explicite: [
        NC("Naïah vous accorde huit minutes pour suivre la relève, puis s’installe à genoux devant vous. Elle veut vous faire jouir avant que la patrouille atteigne la porte basse."),
        NC("Elle ouvre votre veste, embrasse votre torse et presse votre sexe à travers le pantalon. Votre respiration lui révèle immédiatement que cette piste mérite d’être suivie."),
        NC("Sous l’arche, vous retirez vêtements et sous-vêtement avant de les abriter sous la cape. Naïah se déshabille ensuite, puis vous attire nu contre son corps."),
        NC("Naïah se redresse nue entre vous et les remparts, ses hanches effaçant la ville de votre champ de vision. Votre regard cesse enfin de suivre les patrouilles ; son sourire s’étire avec une satisfaction beaucoup trop vive."),
        NC("Naïah serre votre sexe entre ses cuisses, essaie un mouvement trop sec et reçoit votre grimace. Elle ralentit, ajoute sa main et reprend aussitôt l’air de tout avoir calculé."),
        NC("Vous la renversez sur la cape et prenez quelques baisers d’avance. Elle échappe à votre prise par une ombre, revient entre vos jambes et joint sa bouche à sa paume autour de vous."),
        NC("Vous jouissez lorsque la ronde atteint la porte. Naïah suit chaque réaction, ralentit sans perdre le contact et observe votre visage comme le véritable événement de la soirée."),
        NC("Elle vous couvre, rassemble vos vêtements sous la cape et remet elle-même votre chemise à l’endroit. Quand vous demandez qui a gagné, son long silence prouve qu’elle avait oublié le score."),
      ],
      ellipse: [
        NC("Naïah vous accorde huit minutes pour suivre la relève. Elle se place entre vous et les remparts avec l’intention avouée de ruiner votre dernier chiffre."),
        NC("Ses baisers interrompent le compte. Une main sous la cape explore votre ventre et découvre très vite quelle proximité suffit à détourner vos yeux."),
        NC("Vous gagnez l’abri de l’arche, retirez vos vêtements et les rangez sous le tissu sec. Naïah se déshabille ensuite, avant toute apparition de sa nudité."),
        NC("Nus l’un contre l’autre, vous choisissez de poursuivre le défi. La ville reste au loin ; aucun de ses mouvements ne décidera désormais des vôtres."),
        NC("La cape referme hors champ une suite clairement sexuelle. Le récit revient lorsque la relève est passée et que les pierres du plan ont roulé partout."),
        NC("Naïah prétend avoir gagné à la seconde exacte. Le caillou coincé sous son genou et son incapacité à retrouver le compte racontent une autre version."),
        NC("Vous remettez vos vêtements dans le froid revenu. Elle ferme votre col, garde sa main sur votre poitrine et attend que votre respiration ralentisse."),
        NC("Une lanterne s’éteint sur les murs. Naïah annonce huit minutes précises, puis vous embrasse avant que vous réunissiez assez de preuves pour contester."),
      ],
    },
  },
  {
    id: "naiah-edge-femme-city-shadow", context: "date-naiah-akuhn", sex: "femme", concept: "ville-dans-ombre",
    text: "La ville dans l’ombre", detail: "Naïah partage sa perception d’Akuhn’Nabad : pressions, trajets et présences, sans ouvrir aucune pensée.",
    chapters: {
      tendre: [
        NC("Naïah referme vos doigts sur la pierre centrale et pose sa paume dessus. Akuhn’Nabad disparaît visuellement, remplacée par des vibrations qui dessinent les routes sous votre peau."),
        NC("Chaque patrouille devient une pression mobile ; chaque porte, une résistance. Naïah vous guide sans expliquer, corrigeant seulement l’orientation de votre poignet."),
        NC("Vous restez vêtues sous l’arche. Son épaule touche la vôtre tandis que la ville entière semble tenir entre vos mains, immense et pourtant précise."),
        NC("Elle vous montre Allenna par un rythme reconnaissable : trois pas rapides, une pause devant chaque relève, le retour systématique vers le mur sud."),
        NC("Vous ne commentez pas. Naïah continue jusqu’au moment où la présence lointaine s’immobilise ; toutes ses lumières illusoires s’éteignent en même temps."),
        NC("Votre pouce caresse sa paume. Le geste entre dans la carte, devient une chaleur sans rue et surprend Naïah davantage que le mouvement de mille gardes."),
        NC("Elle ferme la ville autour de cette chaleur. Vos fronts se rejoignent et le dernier trajet partagé est celui de sa bouche jusqu’à la vôtre."),
        NC("Les tours reviennent dans la nuit réelle. Naïah garde la pierre entre vos paumes et prétend que personne n’a remarqué l’absence momentanée d’une capitale."),
      ],
      suggestif: [
        NC("Sous vos mains, la ville cesse d’être une image. Ses rues deviennent des lignes de pression et les pas des gardes vibrent le long de vos bras."),
        NC("Naïah ajoute votre souffle à la carte. Chaque expiration élargit une place ; chacun de ses baisers efface temporairement une route."),
        NC("Vos vestes s’ouvrent afin que davantage de peau partage les vibrations. Naïah glisse sa paume sous votre chemise et la ville répond jusque dans vos seins."),
        NC("La présence d’Allenna traverse le réseau avec une netteté brutale. Naïah coupe ce fil sans discours, puis remplace la cadence par celle de vos deux cœurs."),
        NC("Elle essaie une pression magique trop large ; vous perdez tout repère et la repoussez en riant. Naïah réduit aussitôt le monde à sa cuisse entre les vôtres."),
        NC("La suite devient sexuelle derrière les ombres du belvédère. Les mouvements de sa main créent des rues de chaleur ; votre souffle abat l’une après l’autre les portes imaginaires."),
        NC("Le plaisir vous emporte comme une ville qui éteint toutes ses lanternes au même instant. Naïah perçoit la forme du bouleversement et demeure attentive jusqu’au calme."),
        NC("Elle referme la perception, rattache votre veste et remet la pierre centrale dans le plan. Son pouce reste contre votre paume longtemps après le retour de la vue."),
      ],
      explicite: [
        NC("Naïah ouvre Akuhn’Nabad sous vos doigts : portes devenues résistances, gardes devenus pulsations, routes devenues lignes de pression courant sur votre peau. Aucune pensée ne s’y trouve."),
        NC("Elle inscrit votre souffle dans la carte et embrasse votre gorge. Chaque réaction déplace une frontière ; lorsqu’elle touche votre sein, un quartier entier paraît se contracter autour de vous."),
        NC("Vous retirez vos vêtements à l’abri de l’arche et étendez sa cape sur la pierre. Naïah se déshabille ensuite, laissant les vibrations parcourir vos corps seulement lorsqu’ils sont réellement nus."),
        NC("Nue contre vous, Naïah laisse un instant la ville battre sous vos deux ombres. La présence lointaine d’Allenna traverse la carte ; son sourire tombe, le lien se coupe, et votre paume se retrouve contre son sternum."),
        NC("Sa paume descend entre vos cuisses, caresse uniquement l’extérieur et transforme chaque mouvement en avenue chaude. Elle essaie plusieurs rythmes, abandonne celui qui brouille vos sensations et conserve votre préféré."),
        NC("Vous retournez une pulsation contre elle : votre main suit son ventre et ses hanches tandis que sa bouche rejoint ses doigts sur vous. Naïah improvise, surprise de ne plus posséder seule la carte."),
        NC("Vous jouissez lorsque toutes les lanternes sensorielles s’éteignent ensemble. Elle maintient la caresse externe ; la ville se replie dans sa perception et son rire surpris vibre jusque sous votre peau."),
        NC("Naïah ferme le partage avant de vous couvrir. Vous buvez, récupérez vos vêtements et remettez la pierre à sa place ; elle laisse votre trace dans la carte jusqu’au départ."),
      ],
      ellipse: [
        NC("Naïah ouvre la ville sous vos paumes. Les rues deviennent pressions, les patrouilles vibrations et les portes résistances, sans qu’aucune pensée ne soit accessible."),
        NC("Votre souffle entre dans le réseau. Ses baisers effacent des trajets et sa main découvre comment faire vaciller les repères que vous tentiez encore de conserver."),
        NC("Vous retirez vos vêtements sous l’arche et placez la cape contre la pierre. Naïah se déshabille à son tour avant que le partage gagne vos corps nus."),
        NC("La présence d’Allenna traverse une seconde la carte. Naïah la coupe, revient à votre chaleur et choisit avec vous de poursuivre l’intimité sexuelle hors de son regard."),
        NC("L’ombre garde la suite, faite de sensations externes et de distances impossibles. Le récit revient lorsque la ville sensorielle rallume lentement ses portes."),
        NC("Naïah retrouve votre poignet avant même ses vêtements. Elle vérifie le battement réel, puis compare en silence la ville entière à ce point minuscule."),
        NC("Vous vous rhabillez et repliez la cape. Elle réinstalle chaque caillou sauf celui qui portait votre souffle, qu’elle glisse dans votre main."),
        NC("Akuhn’Nabad redevient une silhouette lointaine. Naïah prétend l’avoir oubliée pendant plusieurs minutes et sourit lorsque vous acceptez ce mensonge utile."),
      ],
    },
  },
  {
    id: "naiah-edge-homme-city-shadow", context: "date-naiah-akuhn", sex: "homme", concept: "ville-dans-ombre",
    text: "La ville dans l’ombre", detail: "Naïah partage sa perception d’Akuhn’Nabad : pressions, trajets et présences, sans ouvrir aucune pensée.",
    chapters: {
      tendre: [
        NC("Naïah referme vos doigts autour de la pierre centrale et pose sa paume sur la vôtre. La ville visible disparaît, remplacée par des vibrations qui dessinent ses routes."),
        NC("Chaque patrouille devient une pression mobile et chaque porte une résistance. Elle redresse votre poignet pour vous montrer le nord, sans transformer la découverte en leçon."),
        NC("Vous restez vêtus sous l’arche, épaule contre épaule. Akuhn’Nabad tient entre vos mains et conserve pourtant la taille immense d’une cité qui respire."),
        NC("Allenna apparaît dans le réseau par sa cadence : trois pas rapides, un arrêt à chaque relève, un retour constant vers le rempart sud."),
        NC("Vous gardez le silence. Naïah suit cette présence jusqu’à son immobilité, puis toutes ses lumières s’éteignent et son pouce se crispe sur le vôtre."),
        NC("Vous caressez sa paume. Le geste entre dans la carte comme une chaleur sans route ; Naïah sursaute davantage que devant le mouvement de cent gardes."),
        NC("Elle replie la ville autour de cette chaleur. Vos fronts se touchent et le dernier trajet commun devient celui de sa bouche jusqu’à la vôtre."),
        NC("Les tours réapparaissent. Naïah conserve la pierre entre vos mains et affirme que la capitale n’a rien remarqué, ce qui la rend presque décevante."),
      ],
      suggestif: [
        NC("La ville devient sensation sous vos mains : routes le long des bras, pas contre les paumes et portes comme des résistances qu’il faut contourner."),
        NC("Naïah ajoute votre souffle à la carte. Chaque expiration ouvre un espace ; ses baisers font disparaître des rues entières avec une efficacité croissante."),
        NC("Vos vestes et chemises s’ouvrent afin que la perception gagne votre peau. Sa paume descend sur votre torse et les patrouilles vibrent jusque sous votre ventre."),
        NC("La cadence d’Allenna traverse le réseau. Naïah coupe la présence sans un mot et remplace ce rythme par celui de votre cœur sous ses doigts."),
        NC("Elle tente une onde trop vaste, vous désoriente et reçoit votre rire. Vexée, elle réduit aussitôt la carte à sa cuisse pressée entre les vôtres."),
        NC("Les ombres cachent une suite clairement sexuelle. Sa main transforme votre plaisir en trajet chaud tandis que vos réactions lui apprennent quelles routes conserver."),
        NC("Votre jouissance éteint toutes les lanternes sensorielles. Naïah suit le bouleversement jusqu’au dernier écho et vous garde contre son corps lorsque la ville réelle revient."),
        NC("Elle ferme le passage, remet votre chemise sur vos épaules et replace la pierre. Son pouce reste dans votre paume tandis que la ville redevient seulement visible."),
      ],
      explicite: [
        NC("Sous vos mains, Naïah transforme Akuhn’Nabad en pressions, résistances et vibrations. Les pensées restent closes ; vous ne partagez que la façon impossible dont elle sent la ville."),
        NC("Elle inscrit votre souffle dans le réseau et embrasse votre gorge. Lorsque sa main presse votre sexe à travers le pantalon, plusieurs routes semblent converger vers le même point."),
        NC("Vous retirez vêtements et sous-vêtement sous l’arche, puis étendez la cape au sol. Naïah se déshabille après vous avant de laisser la perception circuler sur vos corps nus."),
        NC("Naïah reste nue contre votre torse tandis que les rythmes de la ville passent par vos ombres mêlées. Celui d’Allenna affleure ; elle le retranche aussitôt et pose votre paume sur sa poitrine, sans un mot."),
        NC("Sa main vous entoure et chaque mouvement devient une avenue de chaleur. Elle essaie une pression trop ferme, lit votre correction dans vos hanches et adapte aussitôt sa paume avec un sourire de bluffeuse."),
        NC("Vous renvoyez une pulsation vers son ventre et ses cuisses. Naïah perd une seconde la maîtrise de la carte, puis joint sa bouche à sa main autour de vous et improvise avec votre rythme."),
        NC("Vous jouissez lorsque toutes les lanternes sensorielles s’éteignent. Elle garde le contact, ralentit avec vous et suit l’orgasme comme une géographie qui se replie autour d’un unique point chaud."),
        NC("Naïah ferme le lien et vous couvre de sa cape. Vous vous rhabillez ensemble, les doigts encore engourdis par les distances retrouvées ; elle replace chaque pierre sauf celle qui conserve la chaleur de votre paume."),
      ],
      ellipse: [
        NC("Naïah ouvre Akuhn’Nabad sous vos mains. Les rues deviennent lignes de pression, les gardes vibrations et les portes résistances, sans accès aux pensées."),
        NC("Votre souffle rejoint le réseau. Ses baisers effacent des routes et sa paume découvre comment détourner votre attention de la ville réelle."),
        NC("Vous vous déshabillez sous l’arche et protégez vos vêtements avec la cape. Naïah retire les siens avant que la perception gagne vos corps nus."),
        NC("La cadence d’Allenna apparaît puis disparaît lorsque Naïah coupe le fil. Vous choisissez ensemble de poursuivre l’intimité sexuelle loin de cette présence."),
        NC("L’ombre garde hors champ la suite faite de contacts externes et de distances impossibles. Le récit revient quand les portes sensorielles se rallument lentement."),
        NC("Naïah cherche votre poignet avant ses vêtements et compare son battement réel à la vibration qu’elle percevait comme une ville entière."),
        NC("Vous vous rhabillez, repliez la cape et restaurez le plan. Elle garde une pierre tiède dans votre poche sans demander votre avis."),
        NC("La capitale redevient une silhouette. Naïah affirme l’avoir oubliée pendant plusieurs minutes, mensonge si évident que vous lui accordez tout de même la victoire."),
      ],
    },
  },
  {
    id: "naiah-edge-femme-unplanned", context: "date-naiah-akuhn", sex: "femme", concept: "plan-imprevu",
    text: "Le plan que Naïah n’avait pas prévu", detail: "Vous cassez son dernier scénario et l’obligez à improviser un jeu dont le contrôle circule réellement.",
    chapters: {
      tendre: [
        NC("Vous renversez la pierre noire avec votre morceau de bois et annoncez que la partie se joue désormais sur les gestes, non sur la dalle. Naïah cligne des yeux, prise de vitesse."),
        NC("Elle tente de reconstruire les règles autour de vous. Vous prenez son poignet avant le premier mot et lui confiez simplement la prochaine décision."),
        NC("Naïah choisit un baiser, puis prétend qu’il constituait une manœuvre de diversion. Vous déplacez sa tasse hors de portée pour l’obliger à rester près de vous."),
        NC("Elle riposte avec une copie. Vous donnez la main au double et invitez l’originale à vous rattraper ; le scénario se divise d’une façon qu’elle n’avait pas préparée."),
        NC("Naïah court autour de l’arche, rit, disparaît et revient dans votre dos. Vous l’attrapez par la taille ; cette fois, elle ne possède aucune phrase prête."),
        NC("Son silence dure une respiration. Elle vous embrasse de nouveau, plus lentement, puis vous laisse décider si le jeu continue assis ou debout."),
        NC("Vous choisissez le sol, adossées à la même pierre. Ses doigts trouvent les vôtres sans illusion pendant que les pièces abandonnées roulent avec le vent."),
        NC("Naïah déclare que votre victoire ne compte pas puisqu’elle réclame immédiatement une revanche. Elle garde pourtant votre morceau de bois avec ses pierres les plus précieuses."),
      ],
      suggestif: [
        NC("Vous balayez son dernier plan et annoncez une nouvelle règle : chaque initiative doit surprendre celle qui la reçoit. Naïah accepte avant de mesurer le danger pour son ego."),
        NC("Elle vous embrasse la première et ouvre votre veste. Vous utilisez le mouvement pour la retourner contre l’arche ; son rire révèle qu’elle n’avait pas envisagé la réponse."),
        NC("Les manteaux tombent sur la pierre et vos chemises s’ouvrent. Naïah tente de faire apparaître une copie, mais vous interrompez le sort par un baiser."),
        NC("La petite créature de brume née de l’échec court sur le plan. Vous riez toutes les deux ; cette maladresse excite sa compétition plus sûrement qu’une réussite parfaite."),
        NC("Vous guidez sa main sous votre chemise, puis la laissez inventer la suite. Elle apprend à vos réactions, perd l’avantage et le reprend avec une ombre froide le long de votre cuisse."),
        NC("Les cailloux disparaissent sous la cape tandis que le jeu devient sexuel hors champ. Chaque fois qu’elle croit prévoir votre geste, vous en choisissez un autre."),
        NC("Le plaisir vous emporte après un dernier renversement. Naïah reste bouche ouverte une seconde, puis affirme que votre victoire figurait dans une annexe invisible."),
        NC("Vous vous rhabillez en échangeant volontairement deux boutons et une pierre. Elle découvre l’erreur au départ et refuse de la corriger avant la prochaine partie."),
      ],
      explicite: [
        NC("Vous renversez la pierre noire et imposez une règle : toute personne qui devine le prochain geste perd l’initiative. Naïah accepte, certaine de vous lire plus vite."),
        NC("Elle ouvre votre veste ; vous la plaquez contre l’arche et glissez une main sous sa chemise. Son rire surpris prouve qu’elle vient de perdre la première manche."),
        NC("Vous retirez vos vêtements à tour de rôle, chacune décidant de la pièce suivante sur l’autre. Les étoffes rejoignent la cape, puis vos deux corps restent nus avant la reprise."),
        NC("Naïah se retrouve nue sous l’arche sans pose ni décor préparé. Elle appelle une copie pour reprendre l’avantage ; votre baiser brise le sort et n’en laisse sortir qu’un petit oiseau de brume, aussitôt parti avec sa pierre noire."),
        NC("Vous la faites asseoir sur vos cuisses et frottez vos corps l’un contre l’autre. Naïah cherche un rythme sûr, se trompe, rit contre votre bouche et vous laisse guider sa hanche."),
        NC("Elle reprend l’initiative en glissant une main entre vos cuisses. Ses doigts caressent uniquement l’extérieur ; vous changez la pression avec votre propre main posée sur la sienne, partageant réellement le contrôle."),
        NC("Une ombre fraîche suit vos seins tandis que sa paume conserve le mouvement appris. Vous jouissez contre son épaule ; Naïah oublie sa réplique, puis réclame aussitôt le droit à une revanche."),
        NC("Vous restez nues sous la cape et récupérez l’oiseau voleur au creux de vos genoux. Naïah ne transforme pas l’après en bilan : elle mord doucement votre doigt et sourit lorsque vous sursautez encore."),
      ],
      ellipse: [
        NC("Vous renversez son plan et annoncez une règle nouvelle : celle qui prévoit correctement le prochain geste doit céder l’initiative. Naïah accepte avec une confiance déraisonnable."),
        NC("Elle ouvre votre veste ; vous utilisez son mouvement pour la retourner contre l’arche. Son rire bref confirme qu’elle ne possédait pas cette suite."),
        NC("Vous vous déshabillez à tour de rôle et déposez chaque vêtement sur la cape. Vos corps nus se trouvent face à face avant que toute ombre intime apparaisse."),
        NC("Vous convenez de poursuivre un jeu sexuel où l’initiative peut changer à chaque geste. Naïah tente un sort, mais votre baiser le transforme en oiseau de brume."),
        NC("La cape ferme la scène sur vos renversements, vos rires et les réactions qu’aucune de vous n’avait prévues. Le récit reprend lorsque l’oiseau vole encore une pierre."),
        NC("Naïah prétend que votre victoire figurait dans un plan secret. Sa respiration et sa chemise introuvable rendent la mauvaise foi particulièrement visible."),
        NC("Vous vous rhabillez en corrigeant ensemble les erreurs de boutons. Elle garde volontairement votre morceau de bois dans la mauvaise poche."),
        NC("Au moment de partir, Naïah vous surprend avec un dernier baiser, puis demande si celui-là était prévu. Vous refusez de répondre et gagnez une nouvelle manche."),
      ],
    },
  },
  {
    id: "naiah-edge-homme-unplanned", context: "date-naiah-akuhn", sex: "homme", concept: "plan-imprevu",
    text: "Le plan que Naïah n’avait pas prévu", detail: "Vous cassez son dernier scénario et l’obligez à improviser un jeu dont le contrôle circule réellement.",
    chapters: {
      tendre: [
        NC("Vous renversez la pierre noire et annoncez que la suite ne se jouera plus sur la dalle. Naïah cligne des yeux, réellement prise de vitesse par ce déplacement."),
        NC("Elle tente d’inventer trois règles autour de vous. Vous prenez son poignet avant la première et lui confiez seulement la prochaine initiative."),
        NC("Naïah choisit un baiser, puis assure qu’il s’agissait d’une diversion. Vous cachez sa tasse derrière votre dos afin qu’elle doive rester proche pour la reprendre."),
        NC("Une copie apparaît. Vous lui confiez la tasse et invitez l’originale à vous rattraper ; son scénario vient d’acquérir un adversaire qu’elle ne dirige plus seule."),
        NC("Naïah court entre les arches, disparaît et revient sur votre épaule. Vous la saisissez par la taille ; aucune réplique brillante n’arrive à temps."),
        NC("Son silence dure une respiration. Elle vous embrasse plus lentement, puis vous laisse choisir de poursuivre assis contre la pierre plutôt qu’au centre de son décor."),
        NC("Les pièces roulent dans le vent pendant qu’elle s’installe entre vos jambes. Ses mains trouvent les vôtres sans double pour embellir la position."),
        NC("Elle invalide votre victoire au motif qu’elle exige une revanche. Votre morceau de bois rejoint pourtant ses pierres soigneusement rangées au lieu de retourner dans votre poche."),
      ],
      suggestif: [
        NC("Vous balayez le plan et imposez une règle : chaque initiative doit surprendre. Naïah accepte avec le sourire d’une femme qui ne mesure pas encore le risque pour son ego."),
        NC("Elle ouvre votre veste ; vous la retournez contre l’arche grâce au même mouvement. Son rire étonné vaut davantage que la victoire qu’elle voulait annoncer."),
        NC("Vos manteaux tombent et vos chemises s’ouvrent. Vous interrompez la copie qu’elle tentait d’appeler ; le sort inachevé produit un petit oiseau qui vole un caillou."),
        NC("Vous riez ensemble de l’échec. Naïah devient immédiatement compétitive, utilise sa jambe entre les vôtres et cherche la réaction qui vous empêchera de préparer la riposte."),
        NC("Vous guidez sa main sous votre chemise puis changez brusquement de place. Elle perd l’initiative, la reprend avec une ombre froide et refuse de compter les manches."),
        NC("La cape recouvre les pièces tandis que la suite devient sexuelle hors champ. Chaque geste prévu appelle une réponse différente, et aucun rôle ne tient longtemps."),
        NC("Le plaisir vous emporte après un dernier renversement. Naïah reste surprise une seconde, puis invoque sans honte une règle secrète qui lui donnerait la victoire."),
        NC("Vous vous rhabillez, échangez volontairement deux boutons et récupérez l’oiseau. Elle ne corrige rien, afin de conserver un prétexte de revanche."),
      ],
      explicite: [
        NC("Vous renversez son plan et imposez une règle : deviner correctement le geste suivant oblige à céder l’initiative. Naïah accepte, certaine de vous lire avant que vous bougiez."),
        NC("Elle ouvre votre veste ; vous utilisez le mouvement pour la plaquer contre l’arche et glisser une main sur son sein. Son rire surpris signe sa première défaite."),
        NC("Vous vous déshabillez à tour de rôle, chacun choisissant une pièce sur l’autre. Vêtements et sous-vêtements rejoignent la cape avant que vous restiez nus sur la pierre abritée."),
        NC("Nue sous l’arche, Naïah tente encore de convoquer une copie assez théâtrale pour sauver son plan. Votre baiser coupe l’incantation ; un petit oiseau de brume jaillit à sa place et s’enfuit avec la pierre noire."),
        NC("Naïah s’assied à califourchon sur vos cuisses et frotte son corps contre votre sexe. Son premier angle manque son but ; elle observe vos hanches, corrige et feint aussitôt l’infaillibilité."),
        NC("Vous la renversez sur la cape. Elle reprend le contrôle en refermant sa main autour de vous, mais vous placez la vôtre sur la sienne et modifiez ensemble pression et cadence."),
        NC("Sa bouche rejoint sa paume tandis qu’une ombre froide parcourt votre ventre. Vous jouissez dans le rythme partagé ; Naïah oublie toute phrase préparée puis réclame une revanche immédiate."),
        NC("Vous restez nus sous la cape, buvez et regardez l’oiseau rapporter enfin la pierre. Naïah mord votre doigt pour obtenir encore une réaction et paraît ravie que le jeu survive au climax."),
      ],
      ellipse: [
        NC("Vous renversez le plan et annoncez que prévoir le geste suivant oblige désormais à céder l’initiative. Naïah accepte avec une confiance qu’elle regrettera bientôt."),
        NC("Elle ouvre votre veste ; vous la retournez contre l’arche en suivant son propre mouvement. Son rire confirme que cette réponse ne figurait nulle part."),
        NC("Vous retirez vos vêtements à tour de rôle et les déposez sur la cape. Vos deux corps nus se font face avant que le jeu gagne sa dimension sexuelle."),
        NC("Naïah appelle une copie, mais votre baiser transforme le sort en petit oiseau. Vous choisissez de poursuivre malgré cette première défaite spectaculaire."),
        NC("La cape garde hors champ les renversements et les réactions imprévues. Le récit reprend lorsqu’aucun de vous ne sait plus qui devait céder l’initiative."),
        NC("Naïah affirme qu’une règle secrète lui accordait la victoire. Son souffle court et l’oiseau qui refuse de lui rendre la pierre détruisent l’autorité de cette déclaration."),
        NC("Vous vous rhabillez en corrigeant mutuellement les boutons. Elle glisse votre morceau de bois dans sa poche et prétend qu’il s’y est rendu seul."),
        NC("Avant le départ, Naïah vous surprend avec un baiser puis demande si vous l’aviez prévu. Votre silence l’oblige à préparer une nouvelle partie."),
      ],
    },
  },
];
