import type { NaiahAuthoredScene } from "./naiah-date-intimacy-types";
import { NC } from "./naiah-date-intimacy-types";

export const NAIAH_FOREST_INTIMACY_SCENES: NaiahAuthoredScene[] = [
  {
    id: "naiah-forest-femme-ribbon", context: "date-naiah-sanctuary", sex: "femme", concept: "ruban-vertige",
    text: "Le défi du ruban", detail: "Naïah transforme le ruban gagné en défi : découvrir, geste après geste, comment vous faire perdre toute contenance.",
    chapters: {
      tendre: [
        NC("Le ruban relie encore vos poignets lorsque Naïah recule sur la mousse. Elle promet de vous faire lâcher prise sans défaire le nœud ni employer le moindre sort de contrainte."),
        NC("Elle commence par tirer brusquement, vous rattrape contre elle et vole un baiser. Votre rire lui plaît davantage que l’effet théâtral qu’elle avait préparé."),
        NC("Naïah essaie ensuite une voix grave, un double solennel et une pluie de pétales. Rien ne fonctionne autant que son nez frôlant le vôtre par accident ; elle le remarque aussitôt."),
        NC(["Naïah", "Oh. Cette tête-là.", "teasing"], "Elle recommence exactement le même frôlement, une seconde plus lent, puis affiche l’assurance de quelqu’un qui aurait tout prévu."),
        NC("Vous ripostez en enroulant la soie autour de sa taille. Naïah doit avancer au lieu de vous attirer et finit assise sur vos cuisses, très satisfaite de cette défaite."),
        NC("Ses baisers alternent avec de minuscules tricheries : une feuille froide dans votre cou, une ombre qui chatouille votre cheville, ses doigts réels qui restent dans votre main."),
        NC("Vous finissez allongées côte à côte, toujours habillées, le ruban tendu entre vos paumes. Naïah renonce au score lorsque votre respiration retrouve la sienne."),
        NC("Elle noue la soie autour de vos deux poignets, beaucoup moins serrée, et déclare que personne n’a perdu pied. Son sourire prouve qu’elle réclamera une revanche."),
      ],
      suggestif: [
        NC("Naïah tire sur le ruban jusqu’à vous ramener contre l’aulne. Elle annonce qu’elle gagnera lorsque vous cesserez de prétendre que ses baisers ne troublent pas votre souffle."),
        NC("Sa bouche passe de votre sourire à votre gorge ; ses doigts explorent votre taille par-dessus l’étoffe. Chaque réaction devient une piste qu’elle suit avec une joie insolente."),
        NC("Elle défait votre veste, puis laisse le ruban retenir vos mains au-dessus de sa nuque. Vous ouvrez sa tenue à votre tour, assez pour sentir sa peau contre la vôtre."),
        NC("Une tentative trop calculée vous fait rire. Naïah se fige, vexée, puis rit aussi avant de remplacer le geste par une lente pression de cuisse entre les vôtres."),
        NC(["Naïah", "Tiens. Ça, ça marche.", "teasing"], "Elle recommence au milieu d’un baiser et vous laisse découvrir combien vite elle apprend dès qu’un frisson lui donne la réponse."),
        NC("La forêt masque la suite derrière un rideau d’ombres. Le ruban guide encore vos mains, sa bouche descend, et vos efforts pour rester silencieuse deviennent son nouveau jeu."),
        NC("Lorsque le plaisir vous emporte, Naïah garde votre rythme au lieu d’ajouter un tour. Elle écoute votre voix, puis sourit comme si elle venait de gagner un secret merveilleux."),
        NC("Vous retrouvez vos vêtements froissés et le ruban autour de sa cheville. Naïah exige que vous refassiez plus tard l’expression qui lui a appris comment gagner."),
      ],
      explicite: [
        NC("Naïah tend le ruban entre vos poignets et vous adosse doucement à l’aulne. Son défi est limpide : vous faire jouir avant que vous réussissiez à lui reprendre la soie.", ["Naïah", "Tu peux supplier, tricher ou rire. Je n’ai interdit aucune de ces excellentes stratégies.", "teasing"]),
        NC("Elle commence par votre bouche, puis glisse une main sous votre chemise. Deux pressions différentes contre votre sein donnent deux réponses ; à la seconde, votre souffle se brise et ses yeux s’agrandissent.", ["Naïah", "…Oh. Celle-là reste dans les règles.", "smirk"]),
        NC("Le ruban demeure noué tandis qu’elle retire votre chemise, votre pantalon et les dernières étoffes. Vous ouvrez sa tenue à votre tour ; ses bottes rejoignent vos vêtements contre une racine sèche avant que vous ne reveniez nues l’une vers l’autre."),
        NC("La lumière violette découvre Naïah sans vêtement ni pose préparée. Elle soutient votre regard une seconde, puis tire sur la soie pour vous ramener contre elle.", ["Naïah", "Si tu continues à me regarder ainsi, je vais prétendre que c’était prévu.", "troubled"]),
        NC("Sa cuisse se glisse entre les vôtres. Elle tente un mouvement trop rapide qui vous fait rire ; son expression se froisse, puis elle ralentit jusqu’à trouver la pression qui soulève vos hanches.", ["Naïah", "Le premier était un faux piège.", "smirk"], ["{player}", "Bien sûr."]),
        NC("Elle recommence au milieu d’un baiser, plus lentement, attentive au frottement qui vous fait vous presser contre elle. Ses doigts suivent ensuite le bord de votre chaleur, restent à la surface et reviennent chaque fois que votre corps les réclame."),
        NC("Vous tirez brusquement sur le ruban. Naïah bascule sur la mousse et vous la maintenez par les poignets le temps de déposer des baisers le long de sa poitrine. Son rire se change en souffle court lorsqu’elle comprend que son défi vient de changer de propriétaire."),
        NC("Elle s’échappe par une ombre, réapparaît à genoux entre vos jambes et utilise la soie pour les maintenir ouvertes sans jamais serrer. Sa bouche descend ; sa langue cherche, manque d’abord votre point le plus sensible, puis le retrouve grâce au mouvement involontaire de vos hanches."),
        NC("Naïah s’arrête juste assez pour vous frustrer.", ["Naïah", "Cette expression est presque la bonne. Encore un peu.", "teasing"], "Vous lui ordonnez de poursuivre ; ravie d’avoir obtenu votre impatience, elle joint sa paume à sa bouche et laisse une ombre fraîche courir sur vos seins."),
        NC("Le rythme devient plus dense sans devenir mécanique : sa langue revient au même endroit, ses doigts modulent la pression autour de votre chaleur, et la cuisse qu’elle garde sous la vôtre soutient chaque mouvement. Le ruban relie encore vos mains lorsqu’elle vous sent céder."),
        NC("Votre plaisir éclate contre sa bouche. Naïah maintient exactement le geste qu’elle vient d’apprendre, laisse vos doigts se crisper dans ses cheveux et ne ralentit qu’après les dernières secousses.", ["Naïah", "Voilà. Celle-là. Refais cette tête.", "bright"]),
        NC("Elle remonte contre vous, encore nue, et rabat votre chemise sur vos épaules avant de s’envelopper dans sa propre cape. Le ruban reste entre vos doigts tandis qu’elle embrasse votre paume, puis votre bouche, avec une douceur qu’elle se garde bien de commenter."),
      ],
      ellipse: [
        NC("Naïah tire le ruban et annonce qu’elle a trouvé un nouveau but : vous faire oublier jusqu’au chemin du retour sans jamais couper la soie."),
        NC("Ses premiers baisers restent un défi. Elle essaie, observe votre réaction, change légèrement d’angle et devient insupportablement satisfaite lorsqu’elle découvre ce qui vous trouble."),
        NC("Elle vous demande de garder le ruban pendant qu’elle ouvre votre tenue, puis retire la sienne. Les vêtements sont posés contre l’aulne avant que l’ombre n’enveloppe la clairière."),
        NC("Nues et toujours reliées, vous choisissez de poursuivre. Naïah promet de ne respecter que les règles effectivement prononcées ; vous lui répondez en tirant la soie vers vous."),
        NC("La forêt se ferme sur vos rires, vos baisers et un jeu désormais charnel. Le récit vous retrouve plus tard, lorsque le ruban pend entre deux mains enfin immobiles."),
        NC("Naïah est couchée contre votre hanche, ravie d’avoir appris au moins un geste capable de ruiner votre concentration. Elle refuse de révéler lequel."),
        NC("Vous récupérez chaque vêtement à l’endroit où il était tombé. Naïah noue le ruban autour de votre manche déchirée, vérifie deux fois que le tissu tient et prétend que cette réparation faisait partie des règles."),
        NC("Avant de repartir, elle noue sa moitié de ruban à votre poignet et garde l’autre. Sa demande de revanche ressemble déjà à une promesse de recommencer."),
      ],
    },
  },
  {
    id: "naiah-forest-homme-ribbon", context: "date-naiah-sanctuary", sex: "homme", concept: "ruban-vertige",
    text: "Le défi du ruban", detail: "Naïah transforme le ruban gagné en défi : découvrir, geste après geste, comment vous faire perdre toute contenance.",
    chapters: {
      tendre: [
        NC("Le ruban court de votre poignet au sien lorsque Naïah recule entre les racines. Elle promet de vous faire abandonner votre sérieux sans user d’autre arme que son mauvais caractère."),
        NC("Elle tire brusquement, vous oblige à la rattraper par la taille et dépose un baiser sous votre mâchoire. Votre surprise lui arrache un rire plus franc que sa pose."),
        NC("Une copie héroïque de vous tente une déclaration grandiose. Vous lui couvrez la bouche ; Naïah constate que votre vraie faiblesse réside plutôt dans ses doigts glissés dans vos cheveux."),
        NC(["Naïah", "Oh. Tu as essayé de cacher ça.", "teasing"], "Elle recommence, plus lentement, et adopte aussitôt l’expression d’une femme qui connaissait ce secret depuis toujours."),
        NC("Vous enroulez le ruban autour de sa taille et inversez la traction. Naïah atterrit contre votre torse, rit de sa propre surprise et refuse de reculer."),
        NC("Le jeu devient une suite de baisers volés, de fausses directions et de vraies mains. Chaque illusion exagère votre contenance au moment où elle disparaît réellement."),
        NC("Vous vous asseyez contre l’aulne, Naïah entre vos jambes, encore vêtus. La soie repose sur vos paumes pendant que son crâne trouve votre épaule."),
        NC("Elle proclame un match nul et noue le ruban plus lâche autour de vous deux. Son sourire annonce qu’elle connaît déjà la première tricherie de la revanche."),
      ],
      suggestif: [
        NC("Naïah vous ramène contre l’arbre avec le ruban et parie qu’elle peut vous faire perdre le fil avant que vous parveniez à lui voler un second baiser."),
        NC("Sa bouche suit votre gorge tandis que ses mains apprennent votre torse sous la chemise. Elle varie chaque geste et retient immédiatement ceux qui brisent votre respiration."),
        NC("Votre veste tombe, puis la sienne. Le ruban passe derrière sa nuque ; lorsque vous tirez, elle vient entre vos cuisses avec une docilité évidemment mensongère."),
        NC("Elle essaie une pression trop légère, obtient seulement votre sourire et fronce le nez. Sa seconde tentative, plus basse et plus ferme, vous oblige à fermer les yeux."),
        NC(["Naïah", "Je savais parfaitement que ça fonctionnerait.", "smirk"], "Son petit silence précédent raconte le contraire. Vous la laissez conserver son mensonge jusqu’à ce qu’elle recommence."),
        NC("L’ombre monte autour de vos hanches tandis que sa main poursuit le jeu hors champ. Vos vêtements s’éloignent encore et sa bouche vous empêche de retrouver une remarque cohérente."),
        NC("Le plaisir atteint son terme au rythme qu’elle vient de découvrir. Naïah ne cherche aucun triomphe pour elle-même ; votre abandon suffit à la rendre férocement heureuse."),
        NC("Elle se love ensuite contre vous, le ruban autour de deux doigts. Lorsque votre souffle se calme, elle exige une revanche à la première expression redevenue digne."),
      ],
      explicite: [
        NC("Naïah tend le ruban entre vous et annonce qu’elle gagnera lorsqu’elle vous aura fait jouir sans que vous réussissiez à le lui reprendre. Son sourire invite déjà toutes les tricheries.", ["Naïah", "Je respecterai chaque règle annoncée. Tu aurais dû en annoncer davantage.", "teasing"]),
        NC("Elle ouvre votre chemise, embrasse votre torse et referme une main par-dessus le tissu encore tendu à votre taille. Votre réaction la surprend ; elle masque cette seconde d’hésitation sous un haussement de sourcil souverain.", ["Naïah", "Exactement comme prévu.", "smirk"]),
        NC("Le ruban demeure à vos poignets pendant qu’elle retire chemise, pantalon et dernière étoffe. Vous défaites sa tenue en retour ; chaque pièce rejoint la racine sèche jusqu’à vous laisser nus sous l’aulne, toujours reliés par la soie."),
        NC("La lumière violette glisse sur le corps nu de Naïah. Elle suit votre regard sans feindre une assurance parfaite, puis tire sur le ruban pour presser sa chaleur contre votre ventre.", ["Naïah", "Regarde encore. J’essaie de décider si cela me déconcentre.", "troubled"]),
        NC("Elle enferme votre désir dressé entre ses cuisses et tente un mouvement qui manque son but. Votre rire la pique ; elle modifie l’angle, ajoute la chaleur de sa paume et sent enfin vos hanches lui répondre."),
        NC("Naïah répète la pression avec une lenteur beaucoup plus efficace, puis l’interrompt au moment où vous commencez à la suivre.", ["{player}", "Tu triches."], ["Naïah", "Tu as enfin compris le jeu.", "bright"]),
        NC("Vous enroulez le ruban autour de sa taille et la faites pivoter contre l’arbre. Vos baisers descendent sur sa poitrine ; elle perd une seconde son sourire, surprise d’être celle dont le souffle se dérègle, puis vous mord doucement l’épaule en représailles."),
        NC("Une ombre dénoue votre prise sans toucher au ruban. Naïah glisse à genoux, referme sa main autour de votre élan et essaie plusieurs cadences. La plus lente vous fait basculer la tête ; elle s’en souvient aussitôt."),
        NC("Sa bouche remplace sa paume, puis les deux travaillent ensemble. Sa langue joue autour de la pointe avant de redescendre ; une ombre fraîche effleure le creux de vos cuisses et rend chaque reprise plus vive sans jamais franchir votre corps."),
        NC("Vous guidez ses cheveux et lui donnez le rythme qu’elle n’avait pas deviné. Naïah l’accepte deux mouvements, le modifie légèrement au troisième et vous arrache une réaction plus forte.", ["Naïah", "Celle-ci aussi, je la garde.", "teasing"]),
        NC("Votre plaisir vous traverse dans sa bouche. Elle maintient sa paume à la base de votre désir, accompagne les dernières pulsations et ne relève les yeux qu’une fois votre souffle brisé.", ["Naïah", "…Oh. Refais cette tête.", "bright"]),
        NC("Naïah retrouve votre chemise avant la sienne et la pose sur vos épaules. Elle reste nue contre votre flanc, réchauffe vos doigts liés dans ses mains et prétend que le silence satisfait de la forêt constitue une déclaration officielle de victoire."),
      ],
      ellipse: [
        NC("Naïah tire le ruban et vous annonce un nouveau défi : vous faire perdre toute dignité avant que vous retrouviez le chemin hors de la clairière."),
        NC("Elle tente un baiser, écoute votre souffle, essaie une main plus basse et découvre avec un petit silence ce qui vous fait réagir le plus vivement."),
        NC("Vous gardez la soie au poignet pendant qu’elle ouvre votre tenue. Elle retire ensuite la sienne ; les vêtements sont rangés sur une racine sèche avant que l’ombre vous couvre."),
        NC("Nus et face à face, vous choisissez de continuer. Naïah jure de respecter toutes les règles que vous avez réellement prononcées, ce qui n’en représente presque aucune."),
        NC("Le récit abandonne à la forêt la partie la plus charnelle du défi. Il revient lorsque vos souffles ralentissent et que le ruban pend entre vos mains immobiles."),
        NC("Naïah repose contre votre torse, ravie d’avoir découvert une réaction qu’elle prétend désormais connaître depuis toujours. Vous ne lui accordez pas cette victoire."),
        NC("Vous retrouvez chaque vêtement dans la mousse. Elle vous aide à fermer votre chemise, défait aussitôt un bouton et appelle cela une erreur de calcul ; le ruban finit noué autour de votre poignet."),
        NC("Au seuil de la clairière, elle coupe le ruban en deux parts inégales et vous donne la plus longue. Sa revanche commencera, affirme-t-elle, dès que vous sourirez."),
      ],
    },
  },
  {
    id: "naiah-forest-femme-double", context: "date-naiah-sanctuary", sex: "femme", concept: "dernier-double",
    text: "Le dernier double", detail: "Une copie trop parfaite refuse de disparaître ; la reconnaître oblige Naïah à partager un jeu qu’elle ne contrôle plus seule.",
    chapters: {
      tendre: [
        NC("Le dernier double affirme être la vraie Naïah et vous tend une main parfaitement calme. L’originale s’assied sur une racine, vexée par cette version qui ne commet aucune erreur."),
        NC("Vous demandez aux deux femmes de raconter votre chute près du ravin. La copie décrit votre courage ; Naïah imite le bruit grotesque de votre botte et se trahit en riant."),
        NC("Vous choisissez l’originale, puis invitez pourtant le double à rester. Naïah n’avait pas prévu de devoir partager sa propre scène avec une image devenue si sûre d’elle."),
        NC("La copie propose un baiser élégant. Vous embrassez plutôt Naïah au moment où elle proteste, laissant la version parfaite applaudir avec un sérieux insultant."),
        NC("Naïah tente de dissiper l’image ; celle-ci revient avec votre visage et lui tire la langue. Vous rejoignez la grimace, transformant son tour en jeu à deux contre elle."),
        NC("Elle finit par rire, s’agrippe à votre bras et ordonne au double de garder l’entrée. L’illusion obéit trop bien ; vous lui ajoutez une couronne de fougères."),
        NC("Le spectacle ralentit. Naïah pose sa joue contre votre épaule tandis que sa copie surveille le sentier sans parler, présence étrange qu’aucune de vous ne commente."),
        NC("Au départ, le double se dissout en deux lucioles. Naïah en glisse une dans vos cheveux et garde l’autre, puis affirme que les preuves d’égalité ont été détruites."),
      ],
      suggestif: [
        NC("La copie survivante vous promet exactement la suite que vous attendez. La vraie Naïah, adossée à l’aulne, sourit trop peu : sa propre perfection commence à l’ennuyer."),
        NC("Vous reconnaissez l’originale à la façon dont son regard quitte votre bouche pour vérifier le ruban. Vous l’attirez contre vous ; le double reproduit le mouvement avec un temps de retard."),
        NC("Naïah ouvre votre veste tandis que la copie mime ses mains sans vous toucher. Vous défaites sa tenue réelle et laissez l’illusion conserver des habits impeccables."),
        NC("Le contraste la fait rire. Sa cuisse rejoint les vôtres, le double propose un rythme trop prévisible, et vous choisissez chaque fois l’improvisation de la femme contre vous."),
        NC("Vous retournez le tour en donnant vos ordres à la copie. Elle doit annoncer ce que Naïah fera ; l’originale change aussitôt de geste pour démentir chaque prédiction."),
        NC("L’ombre dissimule la suite tandis que les mains réelles et les images trompeuses se répondent. Votre plaisir naît précisément des écarts que la copie ne sait pas prévoir."),
        NC("Quand vous perdez pied, l’illusion se fige. Naïah aussi, une seconde, surprise d’avoir réussi autrement que prévu ; son sourire revient beaucoup trop satisfait."),
        NC("Le double vous tend vos vêtements puis disparaît avant de recevoir des remerciements. Naïah prétend l’avoir renvoyé, malgré la luciole boudeuse qui la suit au retour."),
      ],
      explicite: [
        NC("Le double restant promet de vous faire jouir avec une perfection irréprochable. La vraie Naïah s’assied près de vous, offensée par cette image qui connaît toutes ses poses et aucune surprise.", ["Naïah", "Elle est insupportable. Je reconnais un travail de grande qualité.", "annoyed"]),
        NC("Vous embrassez l’originale. Sa main glisse sous votre chemise ; le double mime la caresse dans le vide, toujours une seconde trop tôt. Naïah observe le décalage, puis vous adresse le sourire d’une femme qui vient de concevoir une faute délicieuse."),
        NC("Naïah retire vos vêtements un à un et vous l’aidez à quitter les siens. La copie demeure habillée comme au début, révélant par contraste quels deux corps sont réellement nus dans la clairière et lesquels ne possèdent ni poids ni chaleur."),
        NC("La lumière violette découvre Naïah nue contre la mousse ; l’image parfaite se dénude à son tour, trop tard et sans respiration. Sous votre paume, seule la vraie femme se rapproche.", ["Naïah", "Ne la regarde pas. Elle va croire qu’elle a du charme.", "jealous"]),
        NC("Le double annonce une caresse lente entre vos cuisses. Naïah pose plutôt sa bouche sur votre sein, glisse sa cuisse sous la vôtre et attend que l’attente trompée vous fasse chercher ses doigts. Votre mouvement lui donne exactement l’indice espéré."),
        NC("Elle effleure votre chaleur à l’extérieur, d’abord trop légèrement. Vous lui attrapez le poignet et augmentez la pression ; l’illusion prétend que cette correction était prévue, ce qui fait rire Naïah contre votre ventre."),
        NC("Vous ordonnez au double d’imiter Naïah au lieu de la prédire. Soudain observée par sa propre copie, elle perd sa cadence, relève la tête et vous fixe avec une indignation émerveillée.", ["Naïah", "Tu as retourné mon tour contre moi."], ["{player}", "Il tient très bien ainsi."]),
        NC("L’illusion reproduit chaque mouvement avec un retard minuscule : une seconde bouche sans chaleur près de votre hanche, des doigts de brume qui amplifient le passage de la main réelle. Naïah essaie trop d’effets, vous perd, puis les dissipe d’un claquement vexé."),
        NC("Elle revient seule, plus attentive. Sa bouche descend entre vos cuisses tandis que ses doigts entourent votre point sensible sans jamais quitter la surface ; elle suit vos réactions plutôt que les prédictions devenues inutiles du double."),
        NC("Quand vous tentez de retenir votre plaisir, Naïah laisse la copie annoncer qu’elle va ralentir, puis fait l’inverse. Votre rire se brise en gémissement.", ["Naïah", "Voilà une règle que je n’avais même pas besoin d’écrire.", "teasing"]),
        NC("Vous jouissez contre sa langue. L’illusion se fige sur une pose parfaite ; Naïah, elle, garde sa main sur votre hanche et sa bouche au rythme appris jusqu’à la fin, entièrement absorbée par votre visage réel."),
        NC("Le double rabat votre veste sur vos deux corps avant de se dissoudre, ultime insolence. Naïah se couche nue contre vous, boude trois secondes, puis glisse une luciole sous votre col.", ["Naïah", "Revanche demain. Sans version améliorée de moi.", "soft"]),
      ],
      ellipse: [
        NC("Le dernier double offre la suite idéale tandis que Naïah l’observe avec une hostilité presque comique. Vous choisissez la femme qui peut encore être surprise."),
        NC("Votre baiser dérègle l’illusion. Naïah ouvre votre tenue ; la copie imite déjà la fin du geste et reçoit une pomme de pin en plein front spectral."),
        NC("Vous vous déshabillez ensemble, puis Naïah dépose vos vêtements à l’abri. Le double reste vêtu jusqu’à ce que vous soyez réellement nus, incapable de comprendre l’importance de l’ordre."),
        NC("Vous acceptez de poursuivre avec l’image comme partenaire du jeu, jamais comme corps de remplacement. Naïah promet de la dissiper au premier mouvement qui ne vous amuse plus."),
        NC("La brume couvre les caresses, les prédictions déjouées et les initiatives échangées. Le récit revient lorsque la copie ne sait plus qui mène."),
        NC("Naïah a perdu le contrôle de son scénario sans perdre le sourire. Elle accuse votre capacité à donner des ordres à ses propres illusions de concurrence déloyale."),
        NC("Le double rassemble vos vêtements, s’incline et éclate en lucioles. Vous vous rhabillez pendant que Naïah tente, sans succès, de rappeler la plus insolente."),
        NC("Sur le sentier, une luciole imite encore sa démarche. Vous refusez de dire laquelle vous paraît la plus convaincante ; Naïah prépare déjà sa revanche."),
      ],
    },
  },
  {
    id: "naiah-forest-homme-double", context: "date-naiah-sanctuary", sex: "homme", concept: "dernier-double",
    text: "Le dernier double", detail: "Une copie trop parfaite refuse de disparaître ; la reconnaître oblige Naïah à partager un jeu qu’elle ne contrôle plus seule.",
    chapters: {
      tendre: [
        NC("La copie survivante affirme être la vraie Naïah et offre un sourire sans la moindre faille. L’originale s’accroupit sur une racine, déjà irritée par cette version trop raisonnable."),
        NC("Vous demandez aux deux de raconter votre passage du ravin. La copie loue votre maîtrise ; Naïah reproduit votre cri étouffé et se trahit en riant avant la fin."),
        NC("Vous choisissez l’originale, mais proposez au double de continuer. Naïah doit partager sa mise en scène avec une créature qui semble mieux connaître son texte qu’elle."),
        NC("La copie prépare un baiser parfait. Vous embrassez Naïah pendant qu’elle proteste, et la version impeccable applaudit cette mauvaise décision avec un enthousiasme déplacé."),
        NC("Quand Naïah tente de la dissiper, l’image prend votre visage et lui adresse son propre sourire. Vous imitez le reflet jusqu’à l’obliger à rire de son piège."),
        NC("Elle s’installe contre votre torse et confie l’entrée au double. La sentinelle adopte une pose héroïque ; vous lui placez le ruban en écharpe afin de ruiner sa dignité."),
        NC("Le jeu s’apaise sans explication. Naïah garde votre bras autour d’elle tandis que son image protège le sentier avec une compétence qu’elle prétend mépriser."),
        NC("Au retour, le double éclate en deux lucioles. L’une rejoint votre épaule, l’autre ses cheveux ; Naïah refuse de reconnaître cette symétrie beaucoup trop sentimentale."),
      ],
      suggestif: [
        NC("La copie promet une suite exactement conforme à vos attentes. La vraie Naïah s’appuie contre vous, agacée de voir son reflet confondre perfection et intérêt."),
        NC("Vous identifiez l’originale au regard qu’elle jette vers votre bouche avant de faire semblant d’observer le ruban. Le double, lui, vous regarde déjà comme le scénario l’exige."),
        NC("Naïah ouvre votre chemise ; la copie mime le geste trop tôt. Vous défaites la tenue de la femme réelle et laissez son image conserver une élégance inutile."),
        NC("Son corps se presse contre le vôtre pendant que l’illusion propose des mouvements prévisibles. Naïah change chaque fois d’angle, guidée par les réactions qu’elle découvre sous ses mains."),
        NC("Vous donnez des instructions au double. Il annonce la prochaine caresse ; Naïah désobéit aussitôt, de plus en plus proche et de moins en moins certaine de conduire seule."),
        NC("La brume couvre la suite. Les mains réelles, les lèvres et les sensations illusoires se mêlent jusqu’à ce que votre contenance cède devant l’imprévu."),
        NC("Lorsque le plaisir vous emporte, le double se trompe enfin. Naïah découvre la bonne réponse avec vous et prend immédiatement l’air de l’avoir toujours sue."),
        NC("L’illusion apporte vos vêtements, puis disparaît au moment de recevoir les félicitations. Naïah garde une luciole boudeuse dans sa paume pendant tout le retour."),
      ],
      explicite: [
        NC("Le dernier double assure pouvoir vous faire jouir sans hésitation ni erreur. Naïah s’assied entre vous et l’image, offensée par cette copie qui possède toutes ses poses et aucune curiosité.", ["Naïah", "Regarde-la sourire. Elle n’a jamais raté une seule chose intéressante.", "annoyed"]),
        NC("Vous embrassez l’originale. Sa main se pose sur votre pantalon, essaie une pression et sent votre élan répondre ; le double imite déjà l’assurance que Naïah vient seulement de gagner. Elle lui tire la langue sans cesser de vous toucher."),
        NC("Elle retire vos vêtements et vous l’aidez à faire glisser les siens. La copie demeure habillée pendant que vos deux corps nus se rapprochent, preuve visible de ce qui possède chaleur et poids dans la clairière."),
        NC("Naïah demeure nue dans la lumière violette ; l’illusion copie sa peau sans lui donner de respiration. Votre main trouve une hanche chaude, et seule l’originale vient instinctivement chercher davantage votre paume.", ["Naïah", "Elle est plus symétrique. Je suis plus près.", "smirk"]),
        NC("Le double annonce que Naïah va utiliser sa main. Elle enferme plutôt votre désir entre ses cuisses, cherche une pression, la manque et se fige lorsque votre rire répond à la place du plaisir.", ["Naïah", "Je vérifiais ton sens de l’humour.", "offended"]),
        NC("Vos mains déplacent ses hanches. La reprise vous arrache un souffle beaucoup plus net ; Naïah comprend, recommence et conserve cette lenteur jusqu’à ce que votre tension glisse fermement entre ses cuisses."),
        NC("Vous ordonnez au double de reproduire chaque geste au lieu de le prévoir. Naïah se découvre observée par elle-même et perd une seconde le fil ; vous la ramenez à votre bouche avant qu’elle invente une diversion."),
        NC("La copie pose des mains de brume sur votre torse pendant que Naïah s’agenouille. Sa paume vous entoure, monte lentement puis cède la place à sa bouche ; l’écho illusoire souligne chaque reprise sans jamais franchir votre peau."),
        NC("Elle va trop vite, le sent à la raideur de vos jambes et s’arrête avec une grimace. Vous guidez ses cheveux et son poignet ; elle reprend, apprend le mouvement, puis le décale juste assez pour vous surprendre.", ["Naïah", "Tu vois ? Maintenant, c’est bien moi qui triche.", "bright"]),
        NC("Le double annonce un ralentissement. Naïah maintient au contraire la chaleur de sa bouche et l’appui régulier de sa paume ; votre plaisir approche tandis que l’illusion perd sa belle certitude et commence à clignoter."),
        NC("Vous jouissez contre sa langue. Naïah accompagne les dernières pulsations, les yeux levés vers votre visage plutôt que vers son reflet vaincu.", ["Naïah", "Elle n’avait pas prévu ce bruit-là.", "teasing"], ["{player}", "Toi non plus." ]),
        NC("L’illusion rassemble vos vêtements avant de se dissoudre dans une révérence. Naïah demeure nue contre votre flanc, tire la chemise sur vos épaules et réclame une revanche où sa copie n’aura pas le droit d’être plus prévenante qu’elle."),
      ],
      ellipse: [
        NC("Le dernier double vous promet une suite parfaite. Vous choisissez Naïah parce qu’elle peut encore rater, apprendre et transformer son erreur en nouveau tour."),
        NC("Votre baiser dérègle la copie. Naïah ouvre votre chemise tandis que l’image mime déjà la suite ; une pomme de pin traverse son sourire impeccable."),
        NC("Vous vous déshabillez ensemble et placez vos vêtements sur la mousse sèche. Le double reste habillé jusqu’à ce que vos corps nus rendent son imitation presque comique."),
        NC("Vous acceptez qu’il reste pour le jeu. Naïah promet de le dissiper s’il cesse de vous amuser et vous lui rendez cette même liberté sans discours supplémentaire."),
        NC("La brume cache les gestes les plus charnels, chaque prédiction devenant une occasion de la contredire. Le récit revient quand plus personne ne sait qui a renversé la règle."),
        NC("Naïah repose contre vous, ravie d’avoir perdu le contrôle sans perdre la partie. Elle nie avec aplomb que votre idée ait amélioré son scénario."),
        NC("La copie rassemble les vêtements puis éclate en lucioles. Vous vous rhabillez pendant que Naïah poursuit celle qui s’est installée sur votre épaule."),
        NC("Une seule luciole rejoint le sentier avec vous. Naïah affirme qu’elle l’a laissée vivre pour l’interroger, alors qu’elle lui a déjà donné un nom ridicule."),
      ],
    },
  },
  {
    id: "naiah-forest-femme-shadow", context: "date-naiah-sanctuary", sex: "femme", concept: "partage-ombre-foret",
    text: "Dans l’ombre de la forêt", detail: "Naïah ouvre une perception partagée où le souffle, la distance et le contact existent autrement, sans lire vos pensées.",
    chapters: {
      tendre: [
        NC("Votre paume repose sur son ombre. Naïah pose la sienne sur la vôtre et la clairière perd sa profondeur, comme si chaque arbre retenait le même souffle."),
        NC("Elle vous prévient que vous n’entendrez aucune pensée. La première sensation partagée est seulement le poids d’une feuille tombant très loin, immense dans vos deux mains."),
        NC("Vous restez vêtues et assises face à face. Le ruban relie vos poignets tandis que chaleur, pression et mouvement voyagent par vos ombres au lieu de suivre la peau."),
        NC("Naïah tente de créer un grand spectacle violet. Votre rire résonne partout à la fois et fait éclater ses étoiles ; elle abandonne l’effet avec une grimace ravie."),
        NC("Votre souffle devient une brise perçue sous ses côtes. Le sien ressemble à une vibration contre votre nuque, bien qu’elle n’ait pas bougé."),
        NC("Vous faites glisser un doigt sur sa paume réelle. L’écho parcourt toute la clairière ; Naïah ouvre de grands yeux, surprise par l’ampleur de son propre sort."),
        NC("Elle cesse de parler. Vos fronts se rejoignent et l’espace impossible se réduit doucement jusqu’à ne garder que deux respirations et un baiser très simple."),
        NC("Quand les distances ordinaires reviennent, vos mains sont toujours jointes. Naïah déclare que la forêt a triché, puis reste silencieuse encore quelques pas."),
      ],
      suggestif: [
        NC("Naïah ouvre le partage sous vos paumes. La mousse devient une pression commune, le vent glisse sous deux peaux à la fois et la distance entre vos bouches cesse d’être mesurable."),
        NC("Elle essaie de vous éblouir avec mille frôlements imaginaires. Vous retrouvez son vrai souffle parmi eux ; son spectacle s’effondre en un rire pris contre vos lèvres."),
        NC("Vos vestes s’ouvrent, puis vos chemises glissent sur la mousse. Chaque morceau de peau découvert élargit le passage sans que vos pensées se mêlent."),
        NC("Vos torses se pressent l’un contre l’autre. La chaleur réelle se propage en cercles impossibles, jusque dans des ombres qui n’ont aucun corps pour la porter."),
        NC("Naïah explore ce que produit une caresse perçue à deux endroits. Sa main reste visible ; l’écho, lui, semble passer sous votre cuisse puis derrière votre respiration."),
        NC("Les caresses gagnent en intensité lorsque vos vêtements restants s’éloignent. Elles demeurent externes, multipliées par la magie et guidées par vos réponses."),
        NC("Le plaisir vous traverse comme une onde partagée. Naïah en reçoit la distance qui se contracte, la chaleur qui éclate et votre main qui la cherche ; son silence devient soudain absolu."),
        NC("Elle referme le passage avec précaution, vous couvre et reste étrangement muette. Une luciole apparaît seulement quand vous lui demandez si elle veut recommencer."),
      ],
      explicite: [
        NC("Sous vos paumes jointes, Naïah ouvre une perception où la mousse presse vos deux corps et où chaque souffle possède une distance plutôt qu’un son. Aucune pensée ne traverse.", ["Naïah", "Si tu entends une voix, ce sera la tienne. Ou un arbre menteur.", "thinking"]),
        NC("Elle essaie mille caresses d’ombre ; vous reconnaissez sa vraie main lorsqu’elle trouve votre sein. Votre frisson résonne dans les racines et la surprend assez pour interrompre son grand sourire.", ["Naïah", "Je n’avais pas prévu que ce serait si grand.", "shaken"]),
        NC("Vous retirez vos vêtements ensemble, pièce après pièce, afin que chaque contact découvert reste compréhensible. Les étoffes sèches forment une couche sous vos hanches avant que vous vous allongiez nues, face à face."),
        NC("La lumière de l’ombre révèle Naïah nue sur les étoffes étendues. Elle se rapproche jusqu’à mêler vos souffles, puis glisse sa cuisse entre les vôtres ; cette chaleur précise devient une pression mouvante autour de vous."),
        NC("Sa main caresse l’extérieur de votre plaisir pendant que son ombre répète la pression contre vos seins et vos hanches. Elle ajoute trois échos, vous fait perdre le geste réel et fronce le nez devant son propre excès."),
        NC("Tout disparaît sauf sa paume et sa cuisse. Vous retrouvez enfin une sensation nette, la guidez d’un mouvement de bassin et sentez la forêt entière répondre comme si la mousse respirait sous vous.", ["Naïah", "Moins de spectacle. C’est vexant.", "annoyed"]),
        NC("Vous renvoyez l’écho le long de sa propre ombre. Naïah sursaute lorsque votre caresse contre sa hanche semble l’atteindre aussi derrière l’épaule ; elle rit, puis cesse brusquement en découvrant qu’elle ne contrôle plus seule la direction du partage."),
        NC("Sa bouche rejoint la chaleur entre vos cuisses. Sa langue reste au-dehors, ses doigts ouverts sur vos hanches ; chaque passage se propage dans les racines, revient sous vos seins et vous oblige à distinguer le contact réel de son immense résonance."),
        NC("Naïah tente de déplacer l’écho avant votre prochaine réaction. Vous changez vous-même le courant et le faites revenir contre sa cuisse.", ["{player}", "Tu voulais partager."], ["Naïah", "Je n’avais pas dit équitablement.", "laugh"]),
        NC("Le jeu perd peu à peu ses plaisanteries. Elle garde sa bouche là où votre corps la réclame, réduit la magie à une vibration profonde et serre votre main lorsque le plaisir commence à contracter tout l’espace partagé."),
        NC("Vous jouissez comme si la clairière entière se resserrait autour d’un seul battement. Naïah maintient la caresse, reçoit l’onde sans la confondre avec la sienne et reste parfaitement silencieuse jusqu’à votre retour."),
        NC("Le monde ordinaire revient avec vos corps nus sur les vêtements. Naïah ramène la veste sur vos épaules et garde votre main au creux de sa poitrine.", ["Naïah", "Ne raconte pas aux arbres que j’ai préféré le silence.", "soft"]),
      ],
      ellipse: [
        NC("Naïah ouvre l’ombre sous vos paumes et vous avertit : aucune pensée ne sera lue, seulement la température, le mouvement, la pression et une distance devenue étrange."),
        NC("Vous reconnaissez sa vraie main au milieu des frôlements magiques. Elle abandonne son spectacle dès que votre souffle partagé vaut davantage que les lumières préparées."),
        NC("Vous retirez vos vêtements à deux et les placez sur la mousse sèche. Naïah vérifie que chaque peau découverte précède bien l’élargissement de la sensation commune."),
        NC("Nues l’une contre l’autre, vous choisissez d’aller plus loin dans le partage. Les sensations resteront externes et pourront être interrompues d’un simple retrait de main."),
        NC("L’ombre referme la scène sur une intimité charnelle impossible à raconter avec les repères ordinaires. Le récit reprend lorsque les arbres retrouvent leur taille et vos souffles leur corps."),
        NC("Naïah ne demande pas ce que vous avez pensé, puisqu’elle ne l’a jamais entendu. Elle touche seulement votre poignet pour comparer le battement réel à celui qu’elle percevait partout."),
        NC("Vous remettez vos vêtements dans l’ordre inverse, encore maladroites devant la gravité revenue. Elle noue le ruban à votre manche comme point fixe."),
        NC("Sur le chemin, Naïah reste silencieuse jusqu’à ce qu’une branche craque. Elle sursaute, puis accuse l’arbre d’avoir ruiné une sortie parfaitement mystérieuse."),
      ],
    },
  },
  {
    id: "naiah-forest-homme-shadow", context: "date-naiah-sanctuary", sex: "homme", concept: "partage-ombre-foret",
    text: "Dans l’ombre de la forêt", detail: "Naïah ouvre une perception partagée où le souffle, la distance et le contact existent autrement, sans lire vos pensées.",
    chapters: {
      tendre: [
        NC("Votre paume couvre son ombre et Naïah pose la sienne par-dessus. La clairière s’aplatit soudain ; chaque arbre semble retenir le même souffle que vous."),
        NC("Elle précise qu’aucune pensée ne passera. Une feuille tombe pourtant à vingt pas et son poids devient immense dans vos mains, comme si vous la receviez ensemble."),
        NC("Vous restez vêtus, assis genou contre genou. Le ruban relie vos poignets tandis que chaleur et mouvement empruntent les ombres au lieu de suivre vos corps."),
        NC("Naïah lance un ciel violet destiné à vous éblouir. Votre rire résonne dans toutes les racines et fait éclater ses constellations ; elle tire la langue au sort défaillant."),
        NC("Votre respiration devient une brise sous ses côtes. La sienne vous atteint derrière la nuque sans qu’elle ait quitté sa place face à vous."),
        NC("Vous passez le pouce sur sa paume. L’écho traverse la clairière entière et Naïah ouvre de grands yeux devant l’ampleur inattendue de ce contact minuscule."),
        NC("Les effets s’éteignent. Vos fronts se rejoignent, puis vos lèvres, et l’expérience devient un baiser simple que la magie n’améliore plus."),
        NC("Quand la distance revient, Naïah garde votre main. Elle accuse la forêt d’avoir exagéré le moment et marche quelques minutes sans chercher une meilleure plaisanterie."),
      ],
      suggestif: [
        NC("Le partage s’ouvre : la mousse soutient deux corps à la fois, le vent glisse sous vos vêtements et la distance jusqu’à sa bouche n’a plus de mesure stable."),
        NC("Naïah produit mille frôlements illusoires. Vous trouvez sa vraie main à votre ceinture ; elle perd son décor lorsque votre baiser l’oblige à rire."),
        NC("Vos chemises quittent vos épaules et restent sur les racines. Chaque zone de peau offerte au passage donne aux sensations davantage de relief sans révéler une seule pensée."),
        NC("Son torse vient contre le vôtre. La chaleur réelle se propage comme un cercle au-delà de vos corps, jusque dans les ombres des branches."),
        NC("Naïah cherche ce que fait une caresse ressentie à plusieurs distances. Sa main reste sur vous ; l’écho magique semble pourtant suivre votre ventre et l’intérieur de vos cuisses."),
        NC("Les étoffes restantes s’éloignent et les gestes deviennent franchement charnels. Ils restent externes, leurs échos changeant de pression selon votre souffle."),
        NC("Votre plaisir atteint son terme comme une onde que Naïah perçoit dans l’espace entier. Elle reste fascinée par la façon dont les racines, le souffle et la distance se contractent autour de vous."),
        NC("Elle ferme le partage, vous couvre et récupère vos vêtements. Son silence dure jusqu’à ce que vous demandiez une prochaine fois ; une luciole répond avant elle."),
      ],
      explicite: [
        NC("Naïah ouvre sous vos paumes un monde où la mousse porte vos deux poids et où chaque respiration devient une distance. Elle ne reçoit aucune de vos pensées.", ["Naïah", "Ne cherche pas ma tête. Elle est déjà assez encombrée.", "thinking"]),
        NC("Des frôlements d’ombre parcourent votre torse ; vous reconnaissez sa main réelle lorsqu’elle descend sur votre pantalon. Votre réaction résonne dans les racines et suspend son sourire.", ["Naïah", "Ça, c’était toi. Je recommence pour être certaine.", "teasing"]),
        NC("Vous retirez ensemble chemises, pantalons et dernières étoffes, puis étendez le tout sur la mousse. Vos corps deviennent nus avant que le passage magique gagne en intensité ; Naïah vérifie même que votre ceinture ne reste pas sous votre dos."),
        NC("La lumière sombre révèle Naïah nue contre vous, sa cuisse pressée sous votre désir dressé. La chaleur de ce contact se répercute dans la clairière comme une pression mouvante, toujours à la surface de votre corps."),
        NC("Sa main vous entoure tandis qu’une ombre fraîche parcourt votre poitrine et le creux brûlant de vos cuisses. Elle ajoute trop d’échos, brouille toute sensation utile et les chasse avec un juron boudeur."),
        NC("Vous replacez sa paume et guidez le mouvement. Le contact redevient simple : ses doigts autour de votre élan, son pouce près de la pointe, sa cuisse soutenant votre bassin.", ["Naïah", "Moins de magie. Quelle humiliation.", "annoyed"]),
        NC("Vous envoyez à votre tour une vibration dans son ombre. Naïah la reçoit le long du flanc alors que votre main repose sur sa hanche ; elle se cambre, surprise, puis vous accuse d’avoir volé une règle qu’elle n’avait pas encore inventée."),
        NC("Elle se penche et joint sa bouche à sa main. Sa langue décrit lentement le contour sensible, puis elle reprend votre longueur avec une assurance qui se fend lorsqu’un changement d’angle vous fait rire au lieu de frémir."),
        NC("Naïah relève la tête, faussement scandalisée. Vous lui montrez la cadence avec votre main ; elle l’imite, la ralentit, puis ajoute une pulsation d’ombre au moment exact où votre ventre se tend.", ["Naïah", "Là. Tu as encore fait la tête intéressante.", "bright"]),
        NC("Le partage abandonne ses lumières. Il ne reste que sa bouche, sa paume et l’écho de votre souffle qui revient sous votre peau ; Naïah suit ce rythme sans chercher à produire une réaction pour elle-même."),
        NC("Vous jouissez ; elle le perçoit comme une contraction de toute la clairière. Sa bouche conserve la chaleur, sa main accompagne les dernières pulsations et l’ombre ne se relâche qu’avec vous."),
        NC("Le monde reprend ses limites autour de vos corps nus. Naïah vous abrite sous sa cape et garde votre main contre sa poitrine.", ["Naïah", "Je croyais que le bruit serait la partie intéressante.", "soft"], "Elle n’ajoute rien lorsque vous lui demandez ce qu’elle a préféré."),
      ],
      ellipse: [
        NC("Sous vos paumes jointes, Naïah ouvre un espace de température, de pression et de distance. Elle vous avertit qu’aucune pensée ne traversera ce lien."),
        NC("Vous trouvez sa main véritable au milieu des frôlements magiques. Votre réaction vaut mieux que le spectacle prévu ; elle éteint les lumières inutiles."),
        NC("Vous vous déshabillez ensemble et étendez vos vêtements sur la mousse sèche. Le passage ne s’intensifie qu’après que vos deux corps nus ont trouvé une position claire."),
        NC("Vous choisissez de poursuivre cette expérience charnelle faite uniquement de contacts externes et de sensations partagées. Un retrait de main suffirait à fermer l’espace."),
        NC("L’ombre garde hors champ une intimité qu’aucun vocabulaire ordinaire ne décrirait correctement. Le récit revient quand vos souffles retrouvent chacun un seul corps."),
        NC("Naïah ne demande rien de vos pensées. Elle compare seulement le battement de votre poignet à la vibration immense qu’elle sentait quelques instants plus tôt."),
        NC("Vous remettez chemise et pantalon tandis que la gravité redevient familière. Elle attache le ruban à votre manche pour vous donner un point fixe."),
        NC("Une branche craque sur le chemin. Naïah sursaute, puis accuse l’arbre d’avoir ruiné une sortie silencieuse d’une rare qualité dramatique."),
      ],
    },
  },
];
