import type { DialogueLine } from "./game-data";

const N = (text: string): DialogueLine => ({ speaker: "Narration", text });
const C = (speaker: string, text: string, mood?: string): DialogueLine => ({ speaker, text, mood });

/**
 * Ces fins appartiennent à leur scène précise. Elles remplacent l'ancienne
 * banque de réactions génériques qui raccordait artificiellement des sujets
 * sans rapport entre eux.
 */
export const SCENE_CLOSURES: Record<string, DialogueLine[]> = {
  // Hylee — moments libres
  "hylee-flocon": [N("Le flocon descend entre vos mains réunies. Il s'amincit, devient une goutte claire, mais Hylee ne retire pas tout de suite ses doigts."), C("Hylee", "Il a fini par fondre. Je crois que ça ne voulait pas dire qu'il avait perdu.", "soft")],
  "hylee-tartelette": [N("Il ne reste bientôt que des miettes et une trace de baie sur le pouce d'Hylee. Elle l'essuie en riant, beaucoup moins préoccupée par l'équité du partage."), C("Hylee", "La prochaine fois, j'en prendrai deux. Comme ça, nous pourrons quand même nous disputer la dernière.", "teasing")],
  "hylee-baton": [N("Le bois cesse de vibrer lorsque vos deux prises trouvent enfin le même équilibre. Hylee le fait pivoter une dernière fois avant de vous le rendre."), C("Hylee", "Il t'écoute différemment. Pas mieux. Différemment. Ça me plaît davantage.", "soft")],
  "hylee-foule": [N("Le courant de la foule se referme autour de vous sans l'emporter. Hylee garde votre épaule dans son champ de vision jusqu'à la rue plus calme."), C("Hylee", "Je n'avais pas besoin que tu me tires. Seulement de savoir où te retrouver.", "determined")],
  "hylee-plume": [N("Hylee glisse la plume dans son carnet plutôt que dans une poche où elle pourrait se casser. Le geste possède le soin d'un petit rituel."), C("Hylee", "Medig dira qu'elle ne l'a jamais perdue. Nous ferons semblant de la croire.", "teasing")],
  "hylee-mer": [N("Une vague frappe plus bas contre les pierres. Hylee inspire l'air salé, grimace à son goût, puis recommence comme pour s'assurer que cette liberté existe."), C("Hylee", "Je comprends pourquoi Draven regarde toujours l'horizon. Je ne comprends pas comment il évite d'avaler tout ce sel.", "surprised")],
  "hylee-livre": [N("Elle referme le livre sans corriger la dernière annotation de Remerii. Son propre commentaire reste dans la marge, écrit d'une main plus assurée."), C("Hylee", "Elle va lever un sourcil. Si elle en lève deux, je saurai que j'ai vraiment touché juste.", "teasing")],
  "hylee-danse": [N("Le pas hésitant devient un tour complet. Hylee manque de vous entraîner contre une chaise, se rattrape à votre bras et assume le rire qui suit."), C("Hylee", "Nous appellerons ça une variation. Les accidents ont droit à un joli nom quand on recommence.", "teasing")],
  "hylee-chaleur": [N("La vapeur cesse de brouiller son visage. Hylee boit enfin, les deux mains autour de la tasse, et le givre sur ses phalanges se résorbe."), C("Hylee", "Parfois, le plus difficile n'est pas de produire du froid. C'est d'accepter qu'on puisse me réchauffer.", "soft")],
  "hylee-chanson": [N("Vous reprenez ensemble le refrain. Cette fois, Hylee n'évite pas la dernière mesure : elle la laisse simplement ouverte."), C("Hylee", "On l'écrira quand on saura ce qu'on veut garder de la journée. Pas avant.", "soft")],
  "hylee-bouton": [N("Le bouton finit par tenir de travers. Hylee examine le résultat, tire sur le fil et décide avec gravité que l'imperfection survivra au voyage."), C("Hylee", "Remerii le verra à vingt pas. Promets-moi seulement de ne pas lui donner une aiguille tout de suite.", "teasing")],
  "hylee-statue": [N("Le terrible seigneur de pierre reçoit une brindille en guise d'épée. Hylee lui adresse un salut si solennel qu'un passant se retourne."), C("Hylee", "Il protège désormais la rue. Nous pouvons partir l'esprit tranquille.", "teasing")],
  "hylee-pluie": [N("La pluie alourdit ses cheveux et efface peu à peu le givre de ses manches. Hylee lève le visage au lieu de chercher un abri immédiat."), C("Hylee", "Elle ne me demande rien. Elle tombe, c'est tout. J'avais oublié que certaines choses pouvaient être aussi simples.", "soft")],
  "hylee-nom": [N("Le mot prodige reste derrière vous, accroché à la conversation d'un inconnu. Hylee reprend la route sans accélérer."), C("Hylee", "Je veux qu'on se souvienne de ce que j'ai choisi avec ma magie. Pas seulement du fait que j'en avais.", "determined")],
  "hylee-maison": [N("Elle dessine du bout du pied un seuil imaginaire dans la poussière, puis l'efface avant qu'il ne ressemble à une frontière."), C("Hylee", "Une maison devrait être l'endroit où revenir, pas celui dont on n'a plus le droit de partir.", "soft")],
  "hylee-silence": [N("Le silence reste entre vous sans devenir vide. Hylee cesse de chercher une phrase et appuie simplement son épaule contre la vôtre."), C("Hylee", "D'accord. Aujourd'hui, je peux rester sans faire la conversation à notre place.", "soft")],
  "hylee-jalousie": [N("La rougeur ne quitte pas ses joues, mais son regard revient au vôtre. Elle a posé la question ; elle accepte maintenant d'entendre une réponse qui ne lui appartient pas."), C("Hylee", "Je ne veux pas gagner contre quelqu'un. J'avais seulement besoin de savoir si j'existe aussi quand je ne suis pas devant toi.", "sad")],
  "hylee-demain": [N("Le mot demain perd un peu de son poids. Hylee accroche son petit doigt au vôtre, un geste trop modeste pour devenir un serment."), C("Hylee", "Alors on se choisit aujourd'hui. Demain aura le droit de nous reposer la question.", "soft")],
  "hylee-petit-choix": [N("Hylee tranche finalement pour la couleur la plus vive. Elle contemple sa décision sans tenter d'y découvrir une leçon sur son destin."), C("Hylee", "C'est agréable, un choix qui ne décide pas qui je deviendrai.", "teasing")],
  "hylee-temperature": [N("Le froid s'ajuste jusqu'à devenir une fraîcheur légère entre vos doigts. Hylee mémorise votre réponse avec plus d'attention qu'une formule."), C("Hylee", "Je peux demander au lieu de deviner. C'est moins impressionnant qu'un sort, mais beaucoup plus précis.", "soft")],

  // Remerii — moments libres
  "remerii-lecture": [N("La page demeure ouverte, mais Remerii ne cherche plus la ligne où elle s'est arrêtée. Son attention a changé d'objet sans qu'elle s'en excuse."), C("Remerii", "Le livre survivra à cette interruption. Je commence à soupçonner qu'elle n'en était pas une.", "calm")],
  "remerii-the": [N("Elle ajoute exactement deux gouttes d'eau chaude, goûte de nouveau et vous tend la tasse comme s'il s'agissait d'une expérience commune."), C("Remerii", "Voilà. Imparfait selon ma méthode, juste selon mon palais. Ne prenez pas cet aveu en note.", "smirk")],
  "remerii-erreur": [N("La rune fautive reste visible au milieu des autres. Remerii la cerne d'encre au lieu de l'effacer."), C("Remerii", "Une erreur conservée enseigne parfois davantage qu'une démonstration impeccable. Cette phrase ne quittera pas la pièce.", "calm")],
  "remerii-bijoux": [N("Le dernier bijou demeure légèrement désaxé. Remerii l'effleure, rencontre votre regard et choisit de ne pas le remettre en place."), C("Remerii", "Quiconque le remarquera devra admettre m'avoir observée avec une attention inconvenante.", "smirk")],
  "remerii-medig": [N("Medig gonfle ses plumes puis tourne ostensiblement le dos à Remerii. L'archimage accepte le verdict avec une dignité remarquable."), C("Remerii", "Je note que votre témoin expert manque de neutralité. Sa conclusion reste malheureusement solide.", "strict")],
  "remerii-ponctuation": [N("La virgule change de place et, avec elle, tout le ton de la lettre. Remerii relit la phrase moins comme une diplomate que comme sa destinataire."), C("Remerii", "Un déplacement minuscule, une intention entièrement différente. Les relations possèdent une grammaire cruelle.", "calm")],
  "remerii-parapluie": [N("Votre construction penche contre le vent, mais elle vous garde au sec. Remerii mesure l'angle du regard avant d'abandonner le calcul."), C("Remerii", "La géométrie est offensante. Le résultat, lui, mérite que nous restions dessous.", "smirk")],
  "remerii-sablier": [N("Le dernier grain tombe sans qu'aucune question ne soit posée. Remerii retourne le sablier, cette fois uniquement pour prolonger la pause."), C("Remerii", "Je peux donc laisser passer du temps sans en produire un résultat. L'expérience demande confirmation.", "calm")],
  "remerii-enigme": [N("Elle barre la question initiale et écrit la vôtre en dessous. L'encre met quelques secondes à sécher ; Remerii ne la presse pas."), C("Remerii", "La bonne réponse était inaccessible parce que je protégeais une mauvaise question. C'est… utilement vexant.", "strict")],
  "remerii-musique": [N("La note suspendue trouve enfin une résolution, différente de celle portée par la partition. Remerii laisse vibrer l'accord jusqu'au silence."), C("Remerii", "Ne la rejouons pas tout de suite. J'aimerais conserver le fait qu'elle nous a surpris·es.", "smirk")],
  "remerii-fatigue": [N("Elle ferme deux dossiers et laisse le troisième inachevé. Le bureau paraît presque désordonné ; son souffle, lui, retrouve un rythme normal."), C("Remerii", "Je reprendrai demain. Si le monde s'effondre avant, il devra justifier son manque de patience.", "calm")],
  "remerii-tendresse": [N("Remerii renonce à définir le mot. Sa main se pose sur la vôtre avec une précision qui n'a pourtant rien de théorique."), C("Remerii", "Considérons ceci comme une démonstration provisoire. Sans conclusion obligatoire.", "calm")],
  "remerii-question-franche": [N("Aucun piège ne suit la question. Remerii attend réellement, quitte à recevoir une réponse qu'elle n'avait pas préparée."), C("Remerii", "Je découvre que demander clairement expose davantage que deviner avec élégance.", "calm")],
  "remerii-rature": [N("La phrase rayée demeure lisible sous l'encre. Remerii referme le carnet sans arracher la page."), C("Remerii", "Je n'ai plus besoin qu'une pensée soit fausse pour décider de ne pas la suivre.", "calm")],
  "remerii-cinq-minutes": [N("La cinquième minute s'achève. Remerii consulte l'horloge, puis s'accorde ostensiblement une sixième."), C("Remerii", "Nous venons de dépasser le protocole. Les conséquences semblent remarquablement agréables.", "smirk")],

  // Iriana — moments libres
  "iriana-invitations": [N("Iriana superpose les deux invitations, puis les sépare de nouveau. Elle en conserve une et rend l'autre au secrétaire sans explication mensongère."), C("Iriana", "Je viens de préférer une soirée à une stratégie. Que personne n'en fasse une réforme institutionnelle.", "smirk")],
  "iriana-echecs": [N("La reine tombe au tour suivant. Iriana garde la pièce vaincue dans sa paume au lieu de remettre immédiatement le plateau à zéro."), C("Iriana", "Perdre sans perdre un royaume reste une expérience curieusement supportable.", "calm")],
  "iriana-dessert": [N("Le glaçage disparaît avant l'arrivée d'un conseiller. Iriana essuie la preuve sur son gant, trop tard pour cacher son sourire."), C("Iriana", "Ce crime n'engage que nous. C'est peut-être son principal mérite.", "smirk")],
  "iriana-incognito": [N("Un marchand la bouscule sans reconnaître son visage. Iriana se retourne par réflexe, puis continue sans réclamer d'excuse officielle."), C("Iriana", "Être ignorée est moins humiliant que je ne l'imaginais. Presque reposant.", "calm")],
  "iriana-rumeur": [N("La rumeur perd de son venin à mesure que vous en retrouvez la source : un valet, une porte entrouverte et beaucoup d'ennui."), C("Iriana", "La cour fabrique du destin avec des courants d'air. Je devrais être moins surprise.", "stern")],
  "iriana-table": [N("Iriana s'assied finalement au siège numéro sept. Rien ne se produit, sinon le léger scandale de deux courtisans qui avaient mémorisé l'ancien ordre."), C("Iriana", "Magnifique. Une révolution dont la seule victime est un plan de table.", "smirk")],
  "iriana-course": [N("Vous atteignez l'autre bout de la galerie juste avant les gardes. Iriana reprend son souffle derrière une statue et replace sa dignité d'un geste inutile."), C("Iriana", "Nous n'avons pas couru. Nous avons accéléré une inspection architecturale.", "smirk")],
  "iriana-marche": [N("La pièce devient un objet inutile choisi par Iriana seule. Elle le retourne dans ses doigts comme une décision neuve."), C("Iriana", "Je n'ai aucune justification. Je le voulais. Cette phrase paraît presque indécente.", "calm")],
  "iriana-lettre": [N("La lettre reste non scellée. Iriana la plie néanmoins avec soin et la glisse dans un tiroir qui ne porte aucun emblème."), C("Iriana", "Tout ce qui est vrai n'a pas besoin d'être livré au bon moment pour conserver sa valeur.", "troubled")],
  "iriana-jardin": [N("Une cloche annonce une audience lointaine. Iriana ne bouge qu'à la seconde sonnerie, assez tard pour que ce retard lui appartienne."), C("Iriana", "Le jardin ne s'effondrera pas sans moi. La cour non plus. Voilà une découverte utile.", "calm")],
  "iriana-demande": [N("Elle reprend sa phrase sans verbe d'ordre. La demande paraît plus fragile ainsi, mais aussi plus facile à croire."), C("Iriana", "Je ne pensais pas qu'une simple question puisse me coûter davantage qu'un décret.", "troubled")],
  "iriana-couronne": [N("La couronne repose sur son coussin. Iriana passe devant sans la reprendre, le temps de traverser une pièce entière sous son seul prénom."), C("Iriana", "Elle m'attendra. C'est précisément ce que font les fonctions : elles attendent qu'on les remette.", "calm")],
  "iriana-convoi": [N("Le campement demeure boueux, le thé médiocre et la conversation inexplicablement légère. Iriana ne réclame aucune amélioration."), C("Iriana", "Je comprends enfin pourquoi certains souvenirs survivent mieux sans marbre autour d'eux.", "calm")],
  "iriana-front": [N("Les cartes sont lestées par des pierres ramassées sur le rempart. Iriana garde celle qui porte une trace de sel comme marque-page."), C("Iriana", "Un rapport devrait parfois conserver la matière du lieu qu'il prétend décrire.", "stern")],
  "iriana-forthaven-briefing": [N("La synthèse quitte la table sans que le sceau impérial recouvre les signatures du terrain. Iriana replace seulement le sien dans sa poche."), C("Iriana", "L'Empire peut soutenir cette ville. Il n'a pas besoin de parler plus fort qu'elle.", "calm")],
  "iriana-akuhn": [N("Les veines vertes continuent de luire sous la pierre noire. Iriana les suit jusqu'à la porte, attentive à ce que la cité raconte sans elle."), C("Iriana", "Je suis venue chercher des preuves. Je repars avec deux récits qui refusent de s'annuler.", "calm")],
  "iriana-prenom": [N("La minute s'achève, mais son prénom demeure entre vous sans reprendre immédiatement son titre."), C("Iriana", "Encore une minute. L'Empire survivra à cette imprécision de calendrier.", "smirk")],
  "iriana-sceau": [N("La cire refroidit sans emblème. Iriana passe le pouce sur sa surface lisse avant de ranger le message parmi ses affaires privées."), C("Iriana", "Pour une fois, l'absence de symbole dit exactement qui a écrit.", "calm")],
  "iriana-detail": [N("Le ruban choisi rejoint ses cheveux. Iriana consulte votre regard, non pour demander une approbation, mais pour partager le plaisir d'une décision sans conséquence."), C("Iriana", "Je le changerai peut-être demain. Cela ne rend pas le choix d'aujourd'hui moins vrai.", "smirk")],

  // Valurn — moments libres
  "valurn-cartes": [N("La carte perdante reste retournée entre vous. Valurn récupère les deux autres, mais vous laisse le jeton de la mise."), C("Valurn", "Gardez-le. J'ai la mauvaise intuition que nous rejouerons.", "charming")],
  "valurn-petit-dejeuner": [N("Le second œuf atteint l'assiette sans intervention démoniaque. Valurn contemple ce triomphe modeste avec une fierté absolument disproportionnée."), C("Valurn", "Vous êtes témoin d'un progrès historique. Épargnez-moi seulement une chanson commémorative.", "amused")],
  "valurn-contrat": [N("Le parchemin finit sous un pied de chaise trop court. Valurn teste la stabilité du siège et paraît presque offensé par l'utilité nouvelle de son contrat."), C("Valurn", "Une clause transformée en cale. Voilà peut-être le destin le plus honnête de mes pactes.", "amused")],
  "valurn-piece": [N("La pièce réapparaît là où aucun de vous ne l'avait prévue. Valurn la fait sauter une fois, puis la pose à plat au lieu de recommencer le tour."), C("Valurn", "Le mensonge était élégant. La surprise, manifestement, l'était davantage.", "charming")],
  "valurn-histoires": [N("Il range deux mensonges avec un sourire et conserve l'histoire vraie entre vous, débarrassée de sa valeur de pari."), C("Valurn", "Je pourrais répondre maintenant. Ce qui m'ennuie, c'est que j'en ai réellement envie.", "away")],
  "valurn-fleur": [N("La fleur rejoint sa boutonnière avec une maladresse que Valurn refuse de corriger. Son regard s'y attarde chaque fois qu'il croit le vôtre ailleurs."), C("Valurn", "L'enquête durera peut-être plusieurs jours. La prudence l'exige.", "away")],
  "valurn-fin": [N("Le roman reste ouvert au premier chapitre. Valurn lit trois pages sans retourner vérifier la dernière."), C("Valurn", "Si l'auteur me trahit, je vous tiendrai personnellement responsable de cette vulnérabilité littéraire.", "charming")],
  "valurn-ombre": [N("L'ombre rejoint enfin chacun de ses mouvements. Avant de s'immobiliser, elle vous adresse pourtant un salut que Valurn n'a pas fait."), C("Valurn", "Ne l'encouragez pas. Une seule version insolente de moi suffit amplement.", "amused")],
  "valurn-nom": [N("Son nom demeure sur le registre, isolé du sang auquel d'autres voudraient le rattacher. Valurn souffle sur l'encre fraîche."), C("Valurn", "Je le garderai jusqu'à ce qu'il signifie davantage mes choix que leurs attentes.", "away")],
  "valurn-sortie": [N("La porte reste libre tout au long de la conversation. Valurn ne la regarde plus qu'une fois, au moment précis où il décide de commander un second verre."), C("Valurn", "Je pourrais encore partir. Voilà sans doute pourquoi rester possède enfin un certain charme.", "charming")],
  "valurn-jalousie": [N("Le jeton cesse de tourner. Valurn le pousse au centre de la table sans nommer de rival ni réclamer de classement."), C("Valurn", "Gardons la mise ouverte. Je préfère être choisi parfois que couronné par défaut.", "away")],
  "valurn-bottes": [N("La boucle cède enfin. Valurn enfile sa botte, se lève, puis se rassied sous le prétexte très faible de vérifier l'autre."), C("Valurn", "Le départ demeure techniquement imminent. Le café, hélas, manque encore.", "charming")],
  "valurn-matin": [N("L'aube franchit entièrement la fenêtre avant qu'il récupère ses bottes. Valurn ne commente pas cette nouvelle défaite."), C("Valurn", "Je vous accorde le matin. N'en faites pas une habitude sans m'y inviter de nouveau.", "away")],
  "valurn-sans-dette": [N("Le renseignement change de main sans contrat visible ou invisible. Valurn garde les doigts ouverts une seconde, comme pour vérifier qu'aucune chaîne ne s'y forme."), C("Valurn", "Rien n'est dû. Répétons cette hérésie jusqu'à ce qu'elle cesse de me surprendre.", "away")],

  // Naïah — moments libres
  "naiah-illusions": [N("Les deux doubles se dissolvent et la véritable Naïah reste assise devant vous. Elle ne cherche pas à savoir si sa version sans spectacle était la plus convaincante."), C("Naïah", "Tu m'as trouvée. Pas gagnée, pas résolue. Trouvée. C'est beaucoup mieux.", "thinking")],
  "naiah-baies": [N("La baie choisie éclate entre ses doigts dans une fumée violette parfaitement inoffensive. Naïah goûte l'autre avec une méfiance ravie."), C("Naïah", "Celle-ci est vraie. Ou meilleure menteuse. Dans les deux cas, elle est délicieuse.", "smirk")],
  "naiah-noms": [N("Le nouveau nom reste suspendu entre les arbres, adopté par personne et pourtant déjà difficile à oublier."), C("Naïah", "La forêt décidera si elle le garde. Elle a des goûts terribles, donc j'ai bon espoir.", "smirk")],
  "naiah-ennui": [N("Une heure passe sans monstre, illusion ou catastrophe inventée. Naïah compte les fissures d'une pierre et ne s'enfuit pas."), C("Naïah", "C'était affreusement calme. On recommence demain ?", "thinking")],
  "naiah-oiseau": [N("L'oiseau demeure silencieux jusqu'à votre départ. Naïah lui adresse un signe de tête comme à quelqu'un qui a gardé une confidence."), C("Naïah", "Il ne chante pas pour remplir le vide. Je crois que je l'aime bien.", "soft")],
  "naiah-tasse": [N("La tasse ébréchée tient encore la chaleur. Naïah en suit la fissure du doigt sans la recouvrir d'une illusion réparatrice."), C("Naïah", "Elle est cassée et utilisable. Certains objets ont une philosophie très encourageante.", "thinking")],
  "naiah-permission": [N("La farce éclate comme prévu, puis s'arrête exactement à la limite annoncée. Naïah paraît presque plus fière de l'arrêt que de l'effet."), C("Naïah", "Tu as ri parce que tu savais où le jeu finissait. C'est une excellente règle.", "smirk")],
  "naiah-chemin": [N("Le quatrième sentier ramène au même arbre par un détour magnifique. Naïah touche l'écorce, vexée et enchantée."), C("Naïah", "Nous nous sommes perdu·es avec beaucoup de talent. La forêt devrait nous remercier.", "laugh")],
  "naiah-excuse": [N("Aucune brume ne transforme l'excuse en spectacle. Naïah attend votre réaction, les mains inhabituellement immobiles."), C("Naïah", "Je n'aime pas ce que j'ai fait. Je ne vais pas faire semblant que le regret suffit, mais je peux commencer là.", "sad")],
  "naiah-couronne": [N("La couronne de branches se défait lorsqu'elle incline la tête. Naïah laisse les brindilles tomber sans les rappeler par magie."), C("Naïah", "Elle était jolie. Elle serrait aussi beaucoup trop. C'est souvent le problème des couronnes.", "thinking")],
  "naiah-jalousie": [N("La brume cesse de dessiner des silhouettes rivales et retombe autour de ses chevilles. Naïah vous regarde sans décor pour soutenir la question."), C("Naïah", "Je ne veux pas être la plus brillante. J'ai besoin de savoir que tu me vois quand je n'éclaire rien.", "sad")],
  "naiah-matin": [N("Son visage demeure le même lorsque le soleil atteint la clairière. Naïah plisse les yeux, presque surprise que vous soyez encore là."), C("Naïah", "Le matin est terriblement indiscret. Heureusement, il ne t'a pas fait disparaître.", "thinking")],
  "naiah-route": [N("La brume reste derrière elle pendant plusieurs pas. Naïah se retourne une fois, puis choisit la route sans rappeler son refuge autour d'elle."), C("Naïah", "Je peux emporter la forêt sans la traîner partout. Regarde : elle tient très bien dans mes mauvaises habitudes.", "smirk")],
  "naiah-court": [N("Le siège demeure vide tandis qu'elle s'installe sur le rebord de la fenêtre. Le protocole perd contre une vue plus intéressante."), C("Naïah", "Si je dois revenir un jour, je choisirai d'abord où poser mes pieds.", "thinking")],
  "naiah-lignage": [N("Les noms gravés sur le mur restent à leur place. Naïah, elle, recule assez pour que son propre reflet ne se confonde plus avec eux."), C("Naïah", "Ils racontent d'où je viens. Ils n'ont aucune idée d'où je vais.", "determined")],
  "naiah-caillou": [N("Le caillou ne parle pas, ne luit pas et ne se transforme pas. Naïah le glisse pourtant dans sa poche avec un soin inattendu."), C("Naïah", "Parfaitement inutile. Il va devenir mon conseiller préféré.", "smirk")],
  "naiah-permission-simple": [N("La magie attend réellement. Lorsque vous acquiescez, une seule luciole paraît au creux de sa main, sans envahir le reste du soir."), C("Naïah", "Une petite chose choisie vaut mieux qu'un ciel entier imposé.", "thinking")],
  "naiah-bruit": [N("Le bruit traverse les branches et s'éloigne sans devenir voix, présage ou créature. Naïah écoute jusqu'au bout."), C("Naïah", "C'était seulement une branche. Je croyais que le monde me demandait toujours d'ajouter quelque chose.", "soft")],

  // Lineva — moments libres
  "lineva-promenade": [N("La ronde se termine au dernier poste, mais Lineva continue dix pas au-delà. Pour la première fois, elle ne vérifie rien sur ce morceau de rempart."), C("Lineva", "Voilà. Maintenant, c'est une promenade. Ne le répétez pas à la garnison.", "smirk")],
  "lineva-noeud": [N("Le nœud tient sous une traction brutale. Lineva vous rend la corde sans refaire votre geste à votre place."), C("Lineva", "Correct. Il sauvera une caisse, peut-être une personne. C'est assez pour aujourd'hui.", "approving")],
  "lineva-repas": [N("Elle finit par s'asseoir. Le repas est froid, mais Lineva le mange sans consulter une seule fois la porte."), C("Lineva", "La ville tient pendant que je mâche. Notez l'événement, pas l'horaire.", "smirk")],
  "lineva-chanson": [N("Le dernier refrain monte depuis les quais. Lineva le reprend à mi-voix, assez bas pour nier ensuite l'avoir chanté."), C("Lineva", "Les marins ajoutent un couplet à chaque tempête. La moitié est obscène, l'autre moitié fausse. Ça aide quand même.", "smirk")],
  "lineva-carte": [N("Le détour ajoute six minutes à l'itinéraire et deux pains encore chauds au paquet. Lineva corrige la carte avec une annotation très sérieuse."), C("Lineva", "Point de ravitaillement civil. Priorité variable selon l'odeur.", "smirk")],
  "lineva-des": [N("La relève reprend les dés et vous laisse une place dans la partie suivante. Lineva observe un tour avant de lancer elle-même."), C("Lineva", "Je perds rarement. Ce soir, je peux tolérer une exception bien documentée.", "smirk")],
  "lineva-courrier": [N("La lettre rejoint la pile des nouvelles civiles, au-dessus des rapports de dégâts. Lineva la relit une fois avant de la transmettre aux cuisines."), C("Lineva", "Un quai réparé mérite du pain avant un discours. Faites passer le mot.", "approving")],
  "lineva-manteau": [N("La couture résiste lorsque Lineva remet le manteau. Elle tire une fois dessus, satisfaite, puis garde le fil restant dans sa poche."), C("Lineva", "Ce n'est pas élégant. C'est solide et réparable. Je préfère.", "approving")],
  "lineva-memorial": [N("Vous ajoutez le dernier nom sans rang ni titre. Lineva attend que l'encre sèche avant de refermer le registre."), C("Lineva", "Ils ont tenu la même rue. C'est la hiérarchie qui compte ici.", "thoughtful")],
  "lineva-boussole": [N("L'aiguille retrouve le nord après avoir tremblé vers la mer. Lineva la range contre elle, dans la poche où aucune carte d'état-major ne tient."), C("Lineva", "Elle n'indique pas où se trouve mon père. Seulement la direction dans laquelle continuer.", "thoughtful")],
  "lineva-deleguer": [N("Le rapport quitte ses mains. Lineva suit l'officier du regard jusqu'à la porte, puis s'empêche volontairement de le rappeler."), C("Lineva", "S'il revient avec une autre solution que la mienne, j'essaierai de ne pas appeler cela une erreur.", "thoughtful")],
  "lineva-paix": [N("Aucune cloche ne sonne pendant plusieurs minutes. Lineva finit par détacher son ceinturon et le pose hors de portée immédiate."), C("Lineva", "Le calme n'est pas un piège à chaque fois. J'apprends lentement.", "thoughtful")],
  "lineva-reveil": [N("La première relève prend position sans qu'elle ait besoin de corriger un ordre. Lineva reste appuyée au mur, les yeux encore lourds."), C("Lineva", "Ils savent quoi faire. Je peux donc finir ce café avant de redevenir indispensable.", "smirk")],
  "lineva-inventaire": [N("Votre nom rejoint l'inventaire des personnes présentes, pas celui des ressources disponibles. Lineva souligne elle-même la différence."), C("Lineva", "Je peux compter sur vous sans vous compter comme du matériel. Rappelez-le-moi si j'oublie.", "thoughtful")],
  "lineva-releve": [N("La question demeure ouverte jusqu'à ce que vous répondiez. Lineva ne transforme pas votre disponibilité en ordre avant de l'avoir entendue."), C("Lineva", "Bien. Nous construirons la mission autour de cette limite, pas par-dessus.", "approving")],

  // Saidin — moments libres
  "saidin-horloge": [N("L'horloge repart lorsque Saidin retire son doigt du mécanisme. Une minute entière manque au cadran et n'appartient qu'à votre conversation."), C("Saidin", "Le temps n'a pas disparu. Il a simplement cessé d'être compté par quelqu'un d'autre.", "mysterious")],
  "saidin-fruit": [N("La poire se révèle farineuse, exactement comme aucune prédiction ne l'avait annoncé. Saidin en reprend pourtant une bouchée."), C("Saidin", "Une mauvaise surprise reste une surprise. C'est déjà une qualité.", "surprised")],
  "saidin-pari": [N("La prédiction reste pliée pendant que l'événement passe sans cérémonie. Saidin vous tend le papier encore fermé."), C("Saidin", "Gardez-le. Sa valeur tient désormais à ce que nous avons refusé de vérifier.", "thinking")],
  "saidin-plaisanterie": [N("La chute arrive avec plusieurs siècles de retard et demeure atroce. Saidin rit néanmoins, moins de la plaisanterie que de votre réaction."), C("Saidin", "Je l'avais prédit meilleure. Le passé sait encore me décevoir.", "surprised")],
  "saidin-encre": [N("La tache s'étend sur la manche exactement au mauvais endroit. Saidin la contemple sans le triomphe attendu d'un homme qui l'avait annoncée."), C("Saidin", "Savoir n'a rien empêché. Voilà une leçon que je devrais relire plus souvent.", "thinking")],
  "saidin-prenom": [N("Il prononce votre nom une seule fois, dans ce présent précis, et laisse mourir les sept autres intonations possibles."), C("Saidin", "Celle-ci n'était écrite nulle part. Elle me convient.", "surprised")],
  "saidin-chat": [N("Le chat ignore la main de Saidin et vient se frotter à votre jambe. L'archimage accepte cette défaite avec curiosité."), C("Saidin", "Enfin un être qui traite mes futurs avec le mépris approprié.", "mysterious")],
  "saidin-meteo": [N("La pluie s'arrête avant que le parapluie soit ouvert. Saidin le garde tout de même au-dessus de vous pendant quelques pas."), C("Saidin", "Il est devenu inutile. Cela ne l'empêche pas d'abriter encore quelque chose.", "thinking")],
  "saidin-ville": [N("La rue disparue demeure visible seulement dans son souvenir. Saidin décrit une dernière fenêtre, puis laisse la ville s'effacer sans la reconstruire devant vous."), C("Saidin", "Je peux me souvenir sans obliger le présent à lui ressembler.", "sad")],
  "saidin-cadeau": [N("Il défait l'emballage sans consulter aucun futur où l'objet serait différent. La surprise traverse enfin son visage avant toute analyse."), C("Saidin", "Je ne savais pas. Merci de comprendre la rareté exacte de cette phrase.", "surprised")],
  "saidin-heure": [N("Aucun sort ne marque l'heure. Saidin mesure la fin du moment à la lumière qui a changé sur votre visage."), C("Saidin", "Le présent possède ses propres instruments, lorsque je consens à les regarder.", "thinking")],
  "saidin-reveil": [N("Il ouvre la porte sans vérifier ce qu'elle cachera. Le couloir est vide ; son sourire ne l'est pas."), C("Saidin", "Pour une fois, l'absence d'événement ressemble à un commencement.", "surprised")],
  "saidin-aube": [N("La première tasse refroidit entre ses mains sans qu'il annonce la journée. Saidin boit avant de regarder l'horizon."), C("Saidin", "L'aube peut exister sans devenir un présage. Son goût est alors beaucoup plus simple.", "thinking")],
  "saidin-maintenant": [N("Le détail choisi — une odeur, une lumière, le bruit de votre souffle — demeure seul au centre de son attention."), C("Saidin", "Je ne savais pas que le présent pouvait être aussi vaste lorsqu'on cesse de lui demander la suite.", "surprised")],

  // Bellirith — moments libres
  "bellirith-coupe": [N("Bellirith boit la première, puis vous tend la coupe sans cérémonie séduisante. Le vin reste du vin ; son sourire, cette fois, vient après votre décision."), C("Bellirith", "Vérifiable, ordinaire et partagé. J'admets que la simplicité possède du goût.", "smirk")],
  "bellirith-compliment": [N("Le compliment ne vise ni son corps ni son pouvoir. Bellirith le reçoit avec un silence si bref qu'il aurait pu passer inaperçu."), C("Bellirith", "Voilà qui atteint un endroit que mon miroir néglige. Recommencez un autre jour, pour vérifier.", "thoughtful")],
  "bellirith-parfum": [N("Le parfum reste fermé. Bellirith s'approche tout de même, dépourvue de l'arme olfactive qu'elle avait préparée."), C("Bellirith", "Il faudra donc que ma conversation accomplisse tout le travail. Quelle pression délicieuse.", "smirk")],
  "bellirith-danse": [N("La distance varie au rythme de vos pas, jamais sous la contrainte d'une aura. Bellirith manque une mesure lorsqu'elle réalise que vous vous rapprochez de vous-même."), C("Bellirith", "Je préfère ce pas-là. Celui que je n'ai pas provoqué.", "thoughtful")],
  "bellirith-roman": [N("Le héros prononce une nouvelle métaphore catastrophique. Bellirith referme le livre sur vos rires mêlés."), C("Bellirith", "Je retire ce que j'ai dit : personne ne mérite d'être séduit ainsi. Même mon frère.", "teasing")],
  "bellirith-gants": [N("Elle choisit finalement une main nue et garde l'autre gantée. L'asymétrie paraît plus honnête qu'un dépouillement théâtral."), C("Bellirith", "Une moitié offerte, une moitié gardée. Je découvre la nuance.", "thoughtful")],
  "bellirith-jeu": [N("La défaite ne lui coûte ni public ni pouvoir. Bellirith laisse néanmoins le pion renversé jusqu'à la fin de votre verre."), C("Bellirith", "J'ai perdu sans être abandonnée. Voilà une règle que personne ne m'avait expliquée.", "thoughtful")],
  "bellirith-miroir": [N("Elle ternit le miroir d'un geste et observe son reflet redevenir simplement exact. Son regard revient alors au vôtre."), C("Bellirith", "Il me flatte moins. Je m'y reconnais davantage.", "thoughtful")],
  "bellirith-vetements": [N("La tenue simple ne produit aucune entrée remarquable. Bellirith traverse pourtant la pièce avec une assurance qui ne doit rien aux regards."), C("Bellirith", "Je reste spectaculaire. C'est presque vexant pour mes costumes.", "smirk")],
  "bellirith-silence": [N("Son charme se tait entièrement. Le silence révèle une respiration moins régulière et des mains qui ne savent plus exactement où se poser."), C("Bellirith", "Voilà ce qui reste quand je ne dirige pas la scène. Ne détournez pas les yeux trop vite.", "thoughtful")],
  "bellirith-jalousie": [N("Elle renonce à comparer, provoquer ou surenchérir. La jalousie perd son spectacle et garde seulement sa blessure."), C("Bellirith", "Je n'ai pas besoin d'être première. J'ai besoin de ne pas devenir interchangeable.", "cold")],
  "bellirith-matin": [N("Le matin dissout le maquillage et les ombres savamment placées. Bellirith formule sa demande sans sourire pour la rendre plus facile."), C("Bellirith", "Restez encore un peu. Je survivrai si vous partez ; je préfère seulement votre présence.", "thoughtful")],
  "bellirith-question": [N("Les cinq minutes s'achèvent sans qu'elle ait séduit qui que ce soit. Bellirith semble à la fois frustrée et étrangement reposée."), C("Bellirith", "J'ai parlé de moi sans conquérir la pièce. C'était obscènement intime.", "thoughtful")],
  "bellirith-mauvaise-blague": [N("La plaisanterie tombe à plat avec une perfection remarquable. Bellirith rit la première, sans magie pour entraîner la vôtre."), C("Bellirith", "C'était atroce. Le rire, au moins, m'appartenait.", "teasing")],

  // Amanea — moments libres
  "amanea-piano": [N("La note s'éteint sans recevoir d'ordre de résolution. Amanea garde les doigts au-dessus du clavier, puis les laisse enfin reposer."), C("Amanea", "Elle ne sert rien. C'est peut-être pour cela que je souhaite la rejouer.", "thinking")],
  "amanea-trone": [N("Le siège d'Allenna demeure vide pour l'instant, mais aucun conseiller n'ose plus le traiter comme décoratif. Amanea referme le dossier devant elle."), C("Amanea", "Elle n'héritera pas de mon ombre. Elle gouvernera avec sa propre lumière, quelle qu'en soit la couleur.", "smile")],
  "amanea-allenna": [N("La fierté traverse de nouveau son regard lorsqu'elle relit la décision d'Allenna. Cette fois, Amanea ne la dissimule pas derrière une correction."), C("Amanea", "Elle a choisi autrement que moi. Bien. Une héritière qui répète n'est qu'un écho.", "smile")],
  "amanea-tia": [N("Le nom de Tia demeure entre elles comme une frontière que personne ne franchit ce soir. Amanea range la lettre sans la brûler."), C("Amanea", "Je peux refuser son Empire sans prétendre que ma sœur n'existe plus.", "away")],
  "amanea-naiah": [N("Elle prononce le nom de sa fille une seconde fois, plus bas. Aucun garde ne reçoit l'ordre de refermer la frontière davantage."), C("Amanea", "Je l'aime. Cette vérité ne répare rien. Elle m'interdit seulement de mentir sur la blessure.", "sad")],
  "amanea-calciterres": [N("La clause retourne sous son sceau, loin des oreilles qu'elle pourrait guider. Amanea garde pourtant une copie destinée à Naïah lorsque le danger pourra être nommé."), C("Amanea", "Le secret n'est pas une innocence. C'est un délai que je devrai justifier devant elle.", "angry")],
  "amanea-silence": [N("La salle du trône reste vide. Amanea descend une marche et s'assied à côté de vous plutôt qu'au-dessus."), C("Amanea", "Ici, le silence n'exige aucune obéissance. Je pourrais m'y habituer.", "away")],
  "amanea-ordinaire": [N("La soirée passe sans audience, assassinat ni décision dynastique. Amanea termine son repas et regarde l'assiette vide comme une victoire privée."), C("Amanea", "Je comprends mal les loisirs. Celui-ci consistait à ne sauver personne, et je l'ai apprécié.", "smile")],
  "amanea-corps": [N("Sa main demeure dans la vôtre sans devenir prise, serment ou ordre. Amanea observe ce poids simple avec une attention désarmée."), C("Amanea", "Je passe ma vie à mesurer la force. J'avais oublié que le poids pouvait aussi rassurer.", "away")],

  // Draven — moments libres
  "draven-des": [N("Le dernier dé roule sous la table. Draven le récupère, constate sa défaite et paie la mise sans contester les règles."), C("Draven", "Revanche demain. Avec des dés qui respectent la chaîne de commandement.", "gruff")],
  "draven-carte": [N("La nouvelle route évite deux ponts fragiles et ajoute un village au ravitaillement. Draven signe la correction de votre nom, pas du sien."), C("Draven", "Une carte utile porte la trace de ceux qui l'ont contredite.", "approving")],
  "draven-chant": [N("Sa voix grave rejoint le refrain une seule fois. Les marins l'entendent et ont la sagesse de ne pas applaudir."), C("Draven", "Un mot à Lineva et je vous affecte au nettoyage des cales.", "gruff")],
  "draven-vent": [N("La rafale tourne comme il l'avait annoncé, mais apporte aussi une pluie absente du rapport. Draven relève son col."), C("Draven", "Le vent donne des faits. Jamais tous. C'est pourquoi on garde des yeux ouverts.", "stern")],
  "draven-lineva": [N("La phrase d'ordre disparaît de la lettre. Draven laisse à sa place une question simple et beaucoup plus difficile à écrire."), C("Draven", "Je lui demanderai comment elle tient. Ensuite, j'attendrai réellement la réponse.", "neutral")],
  "draven-relève": [N("Le rapport confirme que Lineva a changé trois de ses procédures et sauvé un quartier entier. Draven replie la feuille avec soin."), C("Draven", "Elle n'a pas besoin de commander comme moi. Elle avait besoin que je lui laisse la place de mieux faire.", "approving")],
  "draven-café": [N("Le café reste imbuvable après le troisième essai. Draven termine néanmoins la tasse, par discipline ou par défi personnel."), C("Draven", "Si l'Empire refuse son aide après ça, j'ajoute cette boisson au dossier des actes hostiles.", "gruff")],
  "draven-départ": [N("L'horizon demeure vide, mais Draven cesse de le traiter comme une promesse trahie. Il resserre les sangles de son paquet."), C("Draven", "Je rentrerai avec une réponse, même si cette réponse est que Forthaven devra tenir autrement.", "stern")],

  // Routes de Hylee
  "hylee-0": [N("La salle reprend son bruit autour de vous. Hylee noue son tablier, mais le geste n'a plus tout à fait l'air d'une chaîne."), C("Hylee", "Je terminerai ce service. Après, j'aimerais voir ce qu'il existe derrière la route — sans faire semblant de ne pas avoir peur.", "determined")],
  "hylee-1": [N("Le bâton repose entre ses paumes, stable malgré le froid qui bleuit le bois. Hylee le tient seule après avoir appris le geste avec vous."), C("Hylee", "Tu peux lâcher. Je sais que tu restes même quand tu ne portes pas à ma place.", "soft")],
  "hylee-2": [N("Elle rabat sa manche sans cacher précipitamment la cicatrice. Ce qu'elle vous a confié reste visible juste assez longtemps pour ne plus ressembler à une honte."), C("Hylee", "Je ne veux pas que cette marque raconte toute mon histoire. Mais je ne veux plus arracher la page non plus.", "determined")],
  "hylee-3": [N("La danse s'achève près du feu, les bottes couvertes de poussière. Hylee garde votre main lorsque la musique improvisée se tait."), C("Hylee", "J'ai passé trop de temps à attendre d'être assez douée pour vivre. Ce soir, j'étais seulement là. C'était mieux.", "teasing")],
  "hylee-4": [N("Le chemin se sépare à la sortie de la clairière. Hylee regarde les deux directions puis revient vers vous, non pour demander laquelle prendre, mais pour annoncer la sienne."), C("Hylee", "Je te choisis sans me perdre. Si un jour je dois partir, ce sera encore moi qui te dirai pourquoi.", "determined")],

  // Routes de Remerii
  "remerii-0": [N("Le thé refroidit tandis que la route se précise. Remerii replie la carte sans reprendre la conversation sous forme de leçon."), C("Remerii", "Voyagez avec nous si vous le souhaitez. Je préfère une présence choisie à une escorte docile.", "calm")],
  "remerii-1": [N("La dernière étincelle se stabilise, puis s'éteint proprement. Remerii abaisse enfin sa main, satisfaite sans dissimuler son soulagement."), C("Remerii", "Vous avez corrigé votre geste sans renoncer à votre intuition. C'est exactement ce que je voulais vous voir conserver.", "calm")],
  "remerii-2": [N("Son exigence ne disparaît pas ; elle change de place. Remerii referme le grimoire et reste auprès de vous sans produire un nouvel exercice."), C("Remerii", "Je peux vouloir vous protéger sans exiger que votre réussite me rassure à chaque instant. Il faudra me le rappeler.", "sad")],
  "remerii-3": [N("La musique continue sans itinéraire. Remerii manque volontairement le retour vers la mesure principale et sourit lorsque vous la suivez."), C("Remerii", "Nous avons techniquement perdu le morceau. Je n'ai aucune intention de le retrouver ce soir.", "smirk")],
  "remerii-4": [N("Le sort de contrainte s'effondre en filaments ternes. Remerii ne détourne pas les yeux de ce qu'il révélait sur sa peur de perdre."), C("Remerii", "Je refuse une sécurité qui vous transforme en chose gardée. Restez parce que vous le décidez — ou partez avec la même liberté.", "calm")],

  // Routes d'Iriana
  "iriana-0": [N("L'audience se termine sans secrétaire pour en fixer la version officielle. Iriana vous accompagne elle-même jusqu'à la porte."), C("Iriana", "Revenez avec des objections, pas avec une révérence mieux exécutée. J'en possède déjà suffisamment.", "calm")],
  "iriana-1": [N("La mesure suspendue ne reçoit aucun accord final. Iriana laisse le silence porter ce que le protocole aurait immédiatement classé."), C("Iriana", "Je voulais une réponse nette. Je découvre que certaines vérités respirent mieux avant de conclure.", "troubled")],
  "iriana-2": [N("La carte demeure sur la table, mais Iriana se place à côté de vous plutôt qu'en face. Le calcul n'est plus le seul langage disponible."), C("Iriana", "Vous avez vu le plan et la personne qui craint de l'avoir mal construit. Ne confondez ni l'une ni l'autre.", "troubled")],
  "iriana-3": [N("La copie du pacte se referme sur le sceau d'Alamma. Iriana pose sa main dessus sans laisser l'héritage engloutir son propre nom."), C("Iriana", "Je ne révoquerai pas seulement sa clause. Je révoquerai l'idée que son choix définit ce que je dois devenir.", "stern")],
  "iriana-4": [N("La couronne reste sur la table lorsque vous quittez le balcon. Iriana ne la reprend qu'après vous avoir suivi jusqu'à la porte."), C("Iriana", "Ce que je viens de choisir n'engage ni l'Empire ni ma lignée. C'est précisément pourquoi je le tiendrai.", "calm")],

  // Routes de Valurn
  "valurn-0": [N("Le jeton revient vers vous au lieu de rejoindre sa bourse. Valurn conserve seulement votre réaction, mise moins facile à compter."), C("Valurn", "La première partie est terminée. Je crains que vous ne soyez déjà devenu·e plus intéressant·e que le gain.", "charming")],
  "valurn-1": [N("La flamme se couche enfin dans sa paume sans disparaître. Valurn la regarde obéir par accord plutôt que par pacte."), C("Valurn", "Elle reste parce que je cesse de l'étrangler. Une métaphore outrageusement transparente.", "away")],
  "valurn-2": [N("Le nom de Bhaal perd son éclat sur le parchemin. Valurn ne le rature pas : il le laisse manquer de pouvoir tout seul."), C("Valurn", "Je ne serai pas son contraire. Ce serait encore lui offrir le centre de ma vie.", "away")],
  "valurn-3": [N("La mise perdue reste entre vos doigts. Valurn pourrait détourner la défaite par une plaisanterie ; il choisit un silence plus coûteux."), C("Valurn", "Gardez-la. Je préfère que quelqu'un possède la preuve que je peux perdre sans disparaître.", "away")],
  "valurn-4": [N("Le pacte neuf ne produit aucune marque sur vos peaux. Valurn relit ses quelques lignes et déchire même celles qui ressemblaient trop à une garantie."), C("Valurn", "Pas de chaîne, pas d'éternité, pas de dette. Seulement l'envie de revenir négocier demain.", "charming")],

  // Routes de Naïah
  "naiah-0": [N("La branche choisie craque sous vos pas et vous ramène dans la clairière. Naïah surgit devant vous, ravie que le jeu n'ait pas décidé à votre place."), C("Naïah", "Tu t'es trompé·e d'une manière très personnelle. C'est beaucoup plus intéressant qu'avoir simplement raison.", "smirk")],
  "naiah-1": [N("Les décors de brume s'effondrent un à un. Naïah reste au centre du théâtre vide, visible sans être exposée."), C("Naïah", "Le spectacle est fini. Tu peux applaudir, partir… ou rester pour la personne qui range les accessoires.", "thinking")],
  "naiah-2": [N("Elle ne parle plus. Le danger réel se mesure à l'immobilité de ses mains et à la brume qui refuse même de bouger."), C("Naïah", "Je t'ai dit la partie vraie. Ne la rends pas plus jolie pour pouvoir la supporter.", "sad")],
  "naiah-3": [N("La couronne de brume retombe sur le sol au lieu de se poser sur sa tête. Naïah l'enjambe et vient s'asseoir près de vous."), C("Naïah", "Je peux être une reine plus tard. Maintenant, j'aimerais savoir si tu aimes la fille qui refuse le trône.", "thinking")],
  "naiah-4": [N("L'illusion parfaite d'Amanea se dissipe avant d'achever sa phrase. Naïah demeure, différente de sa mère et enfin moins décidée à s'en excuser."), C("Naïah", "Je n'ai pas besoin d'être meilleure qu'elle. J'ai besoin d'être assez moi pour ne plus lui demander la permission.", "determined")],

  // Routes de Lineva
  "lineva-0": [N("Une grue recommence à tourner sur le quai. Lineva suit le chargement du regard, puis vous accorde enfin toute son attention."), C("Lineva", "Forthaven tient avec des cordes, des gens épuisés et des décisions vérifiables. Si vous restez, apportez-moi la troisième chose.", "determined")],
  "lineva-1": [N("Les dernières cartes sont empilées, non résolues mais confiées à la relève. Lineva se lève sans emporter toute la salle de guerre avec elle."), C("Lineva", "Ils reprendront sans moi pendant une heure. Si quelque chose brûle, ils savent où se trouve l'eau.", "thoughtful")],
  "lineva-2": [N("Elle franchit la porte du rempart sans se retourner avant la rue suivante. Derrière elle, la garnison poursuit la ronde correctement."), C("Lineva", "Je ne quitte pas mon poste. Je vérifie seulement que la ville existe aussi depuis l'intérieur.", "smirk")],
  "lineva-3": [N("Le silence de la nuit ne ressemble plus à une alerte retenue. Lineva détache son manteau et le laisse sur le dossier de la chaise."), C("Lineva", "Demain, je commanderai encore. Ce soir, je veux savoir qui je suis lorsque personne n'attend un ordre.", "thoughtful")],
  "lineva-4": [N("Le port porte encore ses cicatrices, mais les marteaux couvrent désormais les cloches d'alarme. Lineva vous montre les réparations plutôt que les pertes."), C("Lineva", "Nous n'avons pas gagné parce que tout est redevenu comme avant. Nous avons gagné parce que nous pouvons décider de la suite.", "approving")],

  // Routes de Saidin
  "saidin-0": [N("La montre repart, mais Saidin ne consulte pas l'heure qu'elle affiche. Il préfère observer ce que votre présence a changé dans la pièce."), C("Saidin", "Vous êtes arrivé·e par une erreur. Cela ne condamne pas ce que vous ferez de votre présence.", "mysterious")],
  "saidin-1": [N("Sa réponse demeure entre vous, volontairement incomplète mais plus honnête qu'une énigme décorative. Saidin ne cherche pas à la reprendre."), C("Saidin", "Je vous ai donné assez pour choisir, pas assez pour obéir. La différence est parfois tout ce que je peux protéger.", "thinking")],
  "saidin-2": [N("Le souvenir ne revient pas. Saidin ferme les yeux devant cette limite au lieu d'ouvrir un futur où elle serait contournée."), C("Saidin", "Le temps sait conserver sans rendre. Je suis désolé que cette vérité ne possède aucune élégance utile.", "sad")],
  "saidin-3": [N("Une minute passe sans magie, vision ou paradoxe. Saidin sourit seulement lorsque vous lui faites remarquer qu'elle est déjà terminée."), C("Saidin", "Je ne l'avais pas vue venir. Voilà peut-être ce qui l'a rendue ordinaire — et précieuse.", "surprised")],
  "saidin-4": [N("Les futurs restent fermés autour de lui. Saidin pose sa montre hors de portée et vous rejoint dans l'unique version de la pièce qui existe maintenant."), C("Saidin", "Je reste. Non parce que toutes les suites sont favorables. Parce que celle-ci est la mienne.", "calm")],

  // Routes de Bellirith
  "bellirith-0": [N("La coupe, la clé et la distance restent exactement où vous les avez placées. Bellirith observe vos limites sans chercher le défaut par lequel les retourner."), C("Bellirith", "Vous avez rendu les règles plus intéressantes en refusant que je sois la seule à les écrire.", "smirk")],
  "bellirith-1": [N("Son aura s'éteint entièrement. Le désir qui reste paraît moins spectaculaire et, pour cette raison, beaucoup plus difficile à feindre."), C("Bellirith", "Regardez-moi encore. Si vous me désirez maintenant, je saurai enfin qui vous avez choisi.", "thoughtful")],
  "bellirith-2": [N("Le masque tombe sans révéler une femme soudainement douce. Bellirith reste tranchante, orgueilleuse et réellement inquiète que vous partiez."), C("Bellirith", "Ne m'aimez pas pour la victime que vous imaginez dessous. Aimez-moi seulement si la femme entière vous donne envie de rester.", "cold")],
  "bellirith-3": [N("La marque de Bhaal se fissure sous leurs efforts croisés. Bellirith ne remercie pas son frère ; Valurn ne réclame pas qu'elle le fasse."), C("Bellirith", "Je ne serai plus sa chaîne contre Valurn. Pour le reste de notre haine fraternelle, nous improviserons.", "angry")],
  "bellirith-4": [N("Aucun charme ne vous retient lorsque Bellirith ouvre la porte. Elle reste au milieu de la chambre, prête à recevoir votre départ ou votre retour sans les modifier."), C("Bellirith", "Choisissez-moi si vous le voulez. Pour la première fois, je supporterai de ne pas savoir avant votre geste.", "thoughtful")],

  // Routes d'Amanea
  "amanea-0": [N("L'audience s'achève, mais Amanea vous rappelle avant que les portes ne se referment. Elle descend une marche du trône pour formuler la suite."), C("Amanea", "Tu as parlé devant la reine sans flatter sa peur. Reviens parler à la femme lorsque la cour sera vide.", "neutral")],
  "amanea-1": [N("Allenna quitte la salle avec le plan sous le bras, déjà occupée à le modifier. Amanea suit sa fille du regard avec une fierté austère et entière."), C("Amanea", "Elle me succédera parce qu'elle sait quand me désobéir. Assure-toi de ne jamais l'en féliciter comme d'une faveur reçue.", "smile")],
  "amanea-2": [N("Le nom de Naïah reste prononcé, sans titre ni condamnation. Amanea conserve la porte fermée, mais pose enfin la main sur la clef."), C("Amanea", "Je l'ai chassée. Je l'aime. Ne simplifie aucune de ces vérités pour me rendre plus facile à juger.", "sad")],
  "amanea-3": [N("L'accord disparaît des archives officielles et renaît sur trois feuillets détenus par des personnes qui ne se font pas entièrement confiance."), C("Amanea", "Une alliance que personne ne possède survivra peut-être aux familles qui ont voulu posséder le monde.", "rictus")],
  "amanea-4": [N("La couronne reste dans la salle voisine. Amanea ne paraît ni moins dangereuse ni moins elle-même lorsqu'elle vient à vous sans elle."), C("Amanea", "Je ne te demande pas d'oublier la reine. Je te demande de voir qu'elle ne contient pas toute la femme.", "smile")],

  // Routes de Draven
  "draven-0": [N("Le navire appareille sans cérémonie. Draven garde Forthaven en vue jusqu'à ce que la brume avale les derniers remparts."), C("Draven", "Je vais chercher de l'aide. Pas un sauveur. La différence décidera de ce que je pourrai rapporter à ma fille.", "stern")],
  "draven-1": [N("Les nouvelles sont mauvaises, mais précises. Draven les replie avec le calme d'un homme qui préfère une vérité exploitable à un espoir sans date."), C("Draven", "Lineva tient. Mon rôle n'est pas de lui voler ce mérite en prétendant qu'elle attend seulement mon retour.", "neutral")],
  "draven-2": [N("L'offre impériale révèle enfin son prix. Draven ne la rejette pas par orgueil ; il barre simplement les clauses qui feraient de Forthaven une possession."), C("Draven", "Nous avons besoin de soldats, de vivres et de navires. Pas d'un nouveau maître au bout du quai.", "stern")],
  "draven-3": [N("La lettre destinée à Lineva reste moins propre qu'un ordre militaire. Draven la signe tout de même avant de pouvoir retirer la phrase où il admet sa peur."), C("Draven", "Un père peut s'inquiéter sans rappeler sa fille sous son commandement. J'apprends tard, mais j'apprends.", "neutral")],
  "draven-4": [N("Forthaven paraît plus petite depuis le pont et plus solide à chaque pas vers le quai. Draven attend que Lineva vienne à lui au lieu de marcher reprendre sa place."), C("Draven", "Elle commande. Je rentre comme renfort, comme père et comme homme qui devra écouter le rapport jusqu'au bout.", "approving")],

  // Scènes de groupe et relations croisées
  "amanea-family-truth": [N("Le miroir s'éteint, mais la fleur de brume reste au centre de la table. Amanea ne la fait ni garder ni détruire."), C("Amanea", "Cette conversation ne répare pas notre famille. Elle retire seulement à mon silence le droit de décider seul.", "sad"), C("Naïah", "C'est un début minuscule. Je vais le surveiller avec une hostilité exemplaire.", "thinking")],
  "draven-lineva-letter": [N("Les deux lettres restent ouvertes côte à côte, couvertes d'annotations différentes. Aucune ne remplace l'autre."), C("Lineva", "Je répondrai aux deux. La Commandante d'abord. La fille quand j'aurai trouvé des mots qui ne sont pas des ordres.", "thoughtful"), C("Draven", "Je saurai attendre.", "neutral")],
  "medig-window": [N("Medig replie ses ailes sur la carte et fixe tour à tour Hylee, Remerii puis vous. Aucun doute : elle considère le groupe trop lent."), C("Hylee", "Très bien, on partira. Mais après le petit-déjeuner. Même les présages attendent les tartines.", "teasing"), C("Remerii", "Pour une fois, cette méthodologie me paraît irréprochable.", "smirk")],
  "hr-hylee-truth": [N("La bague cesse de tourner autour de son doigt. Hylee ne l'enlève pas et ne retire pas non plus ce qu'elle vient de vous confier."), C("Hylee", "La prochaine conversation devra inclure Remerii. Je refuse que la douceur d'ici devienne une cruauté dès qu'elle ouvre la porte.", "determined")],
  "hr-remerii-truth": [N("Remerii relâche enfin le bord de la table. Son désir n'a pas disparu ; il cesse seulement de prétendre pouvoir être traité séparément de Hylee."), C("Remerii", "Je parlerai avec elle avant de décider ce que cette possibilité signifie. Pas après. Pas à sa place.", "strict")],
  "hr-secret-hylee": [N("Le couloir reste vide, mais Hylee recule déjà avant que la porte ne puisse transformer votre proximité en mensonge."), C("Hylee", "Je ne veux plus d'un baiser qui exige que je vérifie ensuite si Remerii arrive.", "sad")],
  "hr-secret-remerii": [N("Remerii efface le sort qui masquait la serrure. La disparition de cette précaution rend soudain le secret impossible à rationaliser."), C("Remerii", "Nous allons lui parler. Ma discipline ne vaut rien si elle ne sert qu'à organiser une trahison.", "strict")],
  "hr-honest-hylee": [N("Les trois chaises demeurent à égale distance. Hylee tend une main vers Remerii sans retirer celle qu'elle vous a offerte."), C("Hylee", "Je ne veux ni vous additionner ni vous mettre en compétition. Je veux savoir ce que chacun·e peut réellement choisir.", "determined"), C("Remerii", "Alors nous commencerons par ne rien promettre que cette pièce ne puisse contenir.", "calm")],
  "hr-honest-remerii": [N("Les calculs restent inachevés sur le tableau. Remerii retourne la craie et regarde Hylee avant vous."), C("Remerii", "Je peux accepter une relation qui change sans prétendre en connaître déjà la forme."), C("Hylee", "Et moi, je peux dire quand cette forme me fait mal. Même si j'ai peur de la perdre.", "determined")],
  "hr-triad-morning": [N("Trois tasses occupent la petite table, aucune à la place habituelle. Le désordre ne menace rien ; il témoigne simplement d'une nuit qui a changé vos habitudes."), C("Hylee", "On est encore nous. Juste… avec plus de coudes dans le lit.", "teasing"), C("Remerii", "Et une gestion des couvertures objectivement catastrophique.", "smirk")],
  "iv-open-truth": [N("Iriana et Valurn échangent un regard qui porte déjà leurs propres règles. Aucun des deux ne vous demande de deviner ce qu'ils n'ont pas dit."), C("Iriana", "Notre liberté n'est pas une absence de conséquences. Si vous entrez dans cet équilibre, vous parlerez à chacun de nous."), C("Valurn", "La franchise avant le drame. C'est moins divertissant et nettement plus vivable.", "charming")],
  "iv-boundaries": [N("Les règles restent courtes, modifiables et dépourvues de clause cachée. Valurn paraît presque offensé par tant de lisibilité."), C("Valurn", "Je signe. Symboliquement, rassurez-vous ; aucun démon notaire ne se cache sous la table."), C("Iriana", "J'ai vérifié.", "smirk")],
  "shared-hylee-remerii-atelier": [N("Le sort prend une forme qu'aucune des deux n'avait prévue seule. Hylee le maintient ; Remerii résiste à la tentation de le corriger."), C("Hylee", "Tu as vu ? Elle n'a même pas dit “techniquement”."), C("Remerii", "Techniquement, je m'apprêtais à le faire.", "smirk")],
  "shared-hylee-naiah-visit": [N("La visite s'achève sans portail spectaculaire. Naïah accompagne Hylee jusqu'au bord des brumes et s'arrête avant que la frontière ne ressemble à un rejet."), C("Naïah", "Reviens quand tu veux. Pas quand tu crois devoir me réparer."), C("Hylee", "Je reviendrai quand tu me manqueras. C'est déjà souvent.", "soft")],
  "shared-remerii-saidin": [N("Les deux archimages laissent volontairement une question sans réponse dans le registre. Remerii trace un trait dessous ; Saidin n'y ajoute aucun symbole."), C("Remerii", "Nous savons donc tous deux que nous ignorons quelque chose."), C("Saidin", "C'est souvent le début le plus honnête.", "thinking")],
  "shared-iriana-lineva": [N("Les deux cartes se recouvrent à la frontière du port. Iriana retire son sceau ; Lineva ajoute les noms des rues."), C("Iriana", "L'Empire fournira ce que vous demandez, pas ce qu'il imagine glorieux."), C("Lineva", "Alors nous pourrons travailler ensemble.", "approving")],
  "shared-valurn-naiah": [N("La partie se termine sans pion sacrifié. Naïah renverse le plateau d'un souffle ; Valurn récupère seulement le jeton qu'elle lui lance."), C("Naïah", "Égalité ! C'est le mot poli pour dire que personne n'a réussi à posséder l'autre."), C("Valurn", "Je déteste cette définition parce qu'elle est excellente.", "charming")],
  "shared-valurn-bellirith": [N("Leur rire possède encore des dents, mais aucune magie ne se lève pour achever la dispute. Frère et sœur restent dans la même pièce une minute de plus."), C("Bellirith", "Ne prends pas cela pour une trêve."), C("Valurn", "Jamais. Une trêve familiale manquerait terriblement de style.", "charming")],
  "shared-iriana-valurn": [N("Valurn tend la main sans pari ; Iriana la prend sans transformer le geste en alliance officielle. Leur complicité demeure visible et non exclusive."), C("Iriana", "Nous n'appartenons pas l'un à l'autre."), C("Valurn", "C'est précisément pourquoi je reviens.", "away")],
  "shared-bellirith-naiah": [N("Les deux couronnes imaginaires s'entrechoquent puis éclatent en pluie violette. Bellirith et Naïah restent face à face, dépourvues de cour et nullement diminuées."), C("Bellirith", "Nous aurions gouverné un royaume insupportable."), C("Naïah", "Donc absolument magnifique.", "laugh")],

  // Rendez-vous
  "date-hylee-forestier": [N("La cheminée s'affaisse en braises tandis que la conversation atteint enfin le présent. Hylee ne surveille plus la porte de l'auberge."), C("Hylee", "Je croyais revenir pour mesurer la distance parcourue. En fait, j'avais surtout envie d'y ajouter un souvenir avec toi.", "soft")],
  "date-hylee-glade": [N("Les sculptures demeurent dans la clairière jusqu'à ce que le soleil les traverse. Hylee ne tente pas de les préserver au-delà du moment."), C("Hylee", "Elles vont fondre. Ça ne retire rien au fait qu'on les a faites ensemble.", "soft")],
  "date-remerii-observatory": [N("La constellation inventée ne figurera sur aucune carte. Remerii lui donne tout de même un nom secret et l'inscrit au bord d'une page blanche."), C("Remerii", "Inexacte, invérifiable et précieuse. Votre influence scientifique devient préoccupante.", "smirk")],
  "date-remerii-music": [N("Le morceau s'achève sur une note qui n'appartenait à aucune partition. Remerii garde sa main près de la vôtre sur le clavier silencieux."), C("Remerii", "Ne corrigeons rien. J'aimerais savoir où cette musique nous conduit lorsqu'elle cesse d'être sage.", "smirk")],
  "date-iriana-market": [N("La dernière pièce a disparu et Iriana tient un achat dont personne ne pourra réclamer l'utilité. Les gardes renoncent à comprendre son sourire."), C("Iriana", "Je ne sauverai aucun royaume avec ceci. Je crois que je vais le conserver très longtemps.", "smirk")],
  "date-iriana-ballroom": [N("La musique s'arrête mais Iriana ne lâche pas immédiatement votre main. La salle vide lui rend un visage que la cour ne voit jamais."), C("Iriana", "Demain, je danserai peut-être pour l'Empire. Cette danse-ci ne lui appartiendra pas.", "calm")],
  "date-valurn-forestier": [N("Les cartes restent face visible et la dernière mise n'est réclamée par personne. Valurn commande un autre verre sans vérifier la porte."), C("Valurn", "Une soirée qui ne rapporte rien et que je regretterais de perdre. Vous ruinez admirablement mes principes.", "away")],
  "date-valurn-river": [N("Le feu ordinaire se tasse sur lui-même. Valurn l'alimente d'une branche plutôt que de Chaos, puis s'assied assez près pour partager sa chaleur."), C("Valurn", "Aucun pacte ne nous oblige à voir l'aube ensemble. Voilà qui me donne très envie de tenter l'expérience.", "away")],
  "date-naiah-sanctuary": [N("Le goûter conserve le même goût jusqu'à la dernière bouchée. Naïah paraît encore étonnée que la réalité ait suffi à occuper toute l'après-midi."), C("Naïah", "Je n'ai rien changé et tu n'es pas parti·e. C'est peut-être mon tour de trouver ça magique.", "thinking")],
  "date-naiah-akuhn": [N("La terrasse ne referme aucune porte derrière elle. Naïah prend une pierre sombre, la glisse dans sa poche et laisse le reste de l'héritage à la cité."), C("Naïah", "Je reprends ce morceau. Le palais peut garder ses attentes.", "determined")],
  "date-lineva-ramparts": [N("La ronde s'achève et vos pas continuent jusqu'à un parapet où aucune consigne n'attend. Lineva s'y appuie enfin."), C("Lineva", "Mission terminée. La suite n'a pas besoin de rapport.", "thoughtful")],
  "date-lineva-quarters": [N("Le repas a refroidi mais personne ne s'est levé pour courir vers le premier bruit. Lineva laisse les assiettes attendre à leur tour."), C("Lineva", "J'ai passé une soirée entière sans sauver la ville. Elle tient encore. Moi aussi.", "smirk")],
  "date-saidin-observatory": [N("L'étoile choisie traverse le ciel sans devenir présage. Saidin la regarde disparaître derrière le dôme au lieu de calculer son retour."), C("Saidin", "Je ne sais pas ce qu'elle annoncera. Ce soir, elle n'annonçait peut-être rien. C'était beau.", "surprised")],
  "date-saidin-workshop": [N("La machine prédit que l'un de vous perdra bientôt un bouton. Saidin consulte sa manche, puis éclate d'un rire que l'appareil n'avait pas prévu."), C("Saidin", "Enfin une prophétie à la hauteur de son utilité.", "surprised")],
  "date-bellirith-music": [N("La dernière danse s'achève sans enchantement et vous laisse pourtant le souffle court. Bellirith s'incline sans réclamer d'applaudissements."), C("Bellirith", "Je n'ai poussé aucun de vos pas. Je crois que c'est la première danse dont je puisse réellement être fière.", "thoughtful")],
  "date-bellirith-market": [N("Les brioches sont mangées sur une marche, au milieu de gens qui ne reconnaissent aucune démone célèbre. Bellirith laisse tomber quelques miettes sur sa chemise simple."), C("Bellirith", "Ordinaire reste un costume étrange. Mais celui-ci ne me serre pas.", "smirk")],
  "date-amanea-piano": [N("Votre morceau reste sans titre et sans dernière mesure. Amanea referme doucement le clavier avant que la reine en elle ne tente d'en faire un hymne."), C("Amanea", "Nous le reprendrons. Pas pour l'achever — pour découvrir ce qu'il refuse encore de devenir.", "smile")],
  "date-amanea-terrace": [N("Sous la terrasse, Akuhn'Nabad continue sans réclamer sa souveraine. Amanea observe une décision d'Allenna être exécutée sans intervenir."), C("Amanea", "Ma cité peut vivre pendant que je dîne. Mon héritière vient de m'offrir un avenir que je n'avais pas su demander.", "smile")],
};

export function sceneClosure(sceneId: string) {
  return SCENE_CLOSURES[sceneId] || [];
}
