(function registerSylviniaStoryPeriods() {
  "use strict";

  if (window.SylviniaStoryContent) return;

  const EXTRA_MOMENTS = window.SylviniaStoryMoments || {};
  const DIALOGUES = window.SylviniaStoryDialogues || {};

  const APPROACHES = {
    lucidite: {
      label: "Observer avant d’agir",
      note: "Recouper les détails et chercher ce que la situation dissimule.",
      response: "En prenant le temps de relier les détails, la situation cesse d’être un décor et révèle enfin sa logique.",
      relation: { trust: 2 },
    },
    audace: {
      label: "Prendre l’initiative",
      note: "Assumer une décision franche sans attendre qu’un autre la prenne.",
      response: "L’initiative surprend, mais elle ouvre une possibilité que la prudence seule aurait laissée se refermer.",
      relation: { affection: 1, trust: 1 },
    },
    sangfroid: {
      label: "Garder le contrôle",
      note: "Laisser retomber l’urgence avant de choisir le geste utile.",
      response: "Le calme laisse au groupe assez d’espace pour décider avant la peur et l’orgueil.",
      relation: { trust: 2 },
    },
    resonance: {
      label: "Écouter la magie du lieu",
      note: "Ressentir sans imposer, puis vérifier ce que l’instinct suggère.",
      response: "La magie répond par une impression ténue. Elle n’offre pas une vérité, seulement un fil assez solide pour avancer autrement.",
      relation: { affection: 2 },
    },
  };

  const ROUTE_APPROACHES = {
    observer: {
      label: "Lire les intentions",
      note: "Chercher ce que les gestes révèlent derrière les paroles.",
      response: "Les intentions deviennent plus lisibles dès que les mots cessent d’être pris pour des preuves.",
      relation: { trust: 2 },
    },
    agir: {
      label: "Agir sans détour",
      note: "Accepter d’être jugé sur une décision claire.",
      response: "Le geste force les autres à répondre à quelque chose de réel plutôt qu’à une nouvelle hypothèse.",
      relation: { affection: 1, trust: 1 },
    },
    temporiser: {
      label: "Laisser une porte ouverte",
      note: "Ne pas confondre retenue et abandon.",
      response: "La retenue crée un espace où chacun peut encore changer de position sans perdre la face.",
      relation: { trust: 2 },
    },
  };

  const APPROACH_VARIANTS = {
    lucidite: [
      { label: "Démêler ce qui cloche", note: "Reprendre les faits dans l’ordre avant de répondre.", response: "Le détail qui semblait secondaire devient le point d’appui d’une réponse plus juste." },
      { label: "Poser la question précise", note: "Écarter les détours et nommer l’incohérence.", response: "La question atteint exactement ce que l’autre espérait laisser dans l’ombre." },
      { label: "Comparer avec ce que Hylee sait", note: "Rattacher ce moment aux événements déjà vécus.", response: "Ce rapprochement écarte la conclusion la plus commode et ouvre une question plus précise." },
      { label: "Observer les réactions", note: "Lire les silences autant que les paroles.", response: "Un regard retenu et une respiration trop courte en disent davantage que la première explication." },
      { label: "Chercher le détail oublié", note: "Examiner ce que personne n’a jugé important.", response: "Ce qui avait été négligé replace soudain toute la situation sous une lumière différente." },
    ],
    audace: [
      { label: "Dire franchement ce qu’elle pense", note: "Accepter que la sincérité dérange.", response: "La franchise coupe court aux précautions et oblige chacun à répondre sans masque." },
      { label: "Proposer une solution inattendue", note: "Sortir du rôle que les autres avaient prévu.", response: "La proposition surprend assez pour ouvrir une possibilité que personne n’avait formulée." },
      { label: "Prendre les devants", note: "Agir avant que l’hésitation ne referme l’occasion.", response: "Le premier geste entraîne les autres et transforme une attente inconfortable en décision commune." },
      { label: "Refuser la fausse politesse", note: "Nommer le problème sans l’enrober.", response: "Le ton est abrupt, mais personne ne peut désormais prétendre ne pas avoir compris l’enjeu." },
      { label: "Tenter quelque chose de risqué", note: "Faire confiance à l’élan plutôt qu’au protocole.", response: "Le risque ne disparaît pas ; il devient simplement un choix assumé au lieu d’une menace subie." },
    ],
    sangfroid: [
      { label: "Laisser retomber la tension", note: "Ne pas répondre au premier mouvement d’humeur.", response: "Le silence dure juste assez pour que la colère perde le contrôle de la conversation." },
      { label: "Rester un point fixe", note: "Offrir du calme sans minimiser ce qui se passe.", response: "Cette stabilité donne aux autres un espace où reprendre souffle sans avoir à se justifier." },
      { label: "Procéder étape par étape", note: "Résoudre le plus urgent avant de discuter du reste.", response: "La situation cesse de former un seul nœud dès que chaque problème retrouve sa place." },
      { label: "Ne rien laisser paraître", note: "Garder l’émotion pour un moment moins dangereux.", response: "Le contrôle évite l’escalade, même si ce qui n’a pas été dit continue d’exister entre eux." },
      { label: "Répondre avec mesure", note: "Choisir des mots qui n’ajoutent pas une blessure.", response: "La réponse ne cède rien d’essentiel, mais elle laisse encore une voie pour se comprendre." },
    ],
    resonance: [
      { label: "Suivre l’intuition magique", note: "Écouter la première vibration avant de l’expliquer.", response: "La magie ne formule aucun ordre ; elle souligne seulement l’endroit exact où l’attention doit se poser." },
      { label: "Accueillir ce que le lieu renvoie", note: "Cesser un instant de séparer émotion et magie.", response: "Le lieu répond moins par une vision que par une émotion étrangère, assez nette pour guider la suite." },
      { label: "Effleurer la trame", note: "Tester la magie avec retenue, sans chercher à la dominer.", response: "Une vibration discrète traverse la trame et révèle une présence que les yeux seuls auraient manquée." },
      { label: "Faire confiance au ressenti", note: "Assumer une impression impossible à prouver immédiatement.", response: "L’intuition demeure fragile, mais les événements lui donnent bientôt une cohérence inattendue." },
      { label: "Écouter avant de nommer", note: "Laisser la magie et l’émotion se distinguer d’elles-mêmes.", response: "Lorsque Hylee cesse de forcer une réponse, deux sensations jusque-là confondues se séparent enfin." },
    ],
    observer: [
      { label: "Lire ce qui n’est pas dit", note: "Comparer la posture aux paroles.", response: "Le silence et les gestes révèlent l’enjeu que la conversation évitait encore." },
      { label: "Reconstituer les intentions", note: "Distinguer le calcul de la peur.", response: "L’intention réelle apparaît moins glorieuse, mais aussi plus compréhensible que le discours officiel." },
      { label: "Attendre le faux pas", note: "Laisser l’autre préciser sa position.", response: "Une contradiction minuscule suffit à dévoiler ce qui devait rester implicite." },
      { label: "Examiner les conséquences", note: "Penser au-delà de l’instant présent.", response: "La décision change lorsqu’elle est regardée depuis le lendemain plutôt que depuis l’urgence." },
    ],
    agir: [
      { label: "Trancher sans détour", note: "Donner à la scène une direction claire.", response: "Le geste impose une réalité nouvelle à laquelle chacun doit désormais s’adapter." },
      { label: "Prendre la responsabilité", note: "Accepter d’être celui ou celle que l’on jugera.", response: "La décision déplaît à certains. Quelqu’un accepte enfin d’en porter les conséquences." },
      { label: "Forcer une réponse concrète", note: "Remplacer les sous-entendus par un acte.", response: "L’action rend les intentions visibles et met fin aux hypothèses confortables." },
      { label: "Choisir le risque utile", note: "Ne pas confondre prudence et immobilité.", response: "Le risque ouvre un passage étroit, assez réel pour que les autres puissent le suivre." },
    ],
    temporiser: [
      { label: "Préserver une issue", note: "Ne fermer aucune porte trop tôt.", response: "La retenue permet à chacun de revenir sur sa position sans transformer cela en défaite." },
      { label: "Reporter le conflit", note: "Choisir un moment où la vérité coûtera moins cher.", response: "Rien n’est résolu, mais le désaccord cesse de menacer tout ce qui l’entoure." },
      { label: "Accorder un peu de temps", note: "Laisser l’émotion perdre sa première violence.", response: "Quelques minutes suffisent pour que la même question puisse enfin recevoir une réponse honnête." },
      { label: "Proposer un compromis provisoire", note: "Avancer sans prétendre avoir tout réglé.", response: "Le compromis tient assez longtemps pour éviter la rupture et préparer une vraie décision." },
    ],
  };

  function stableIndex(value, length) {
    let hash = 0;
    String(value || "").split("").forEach(function each(character) { hash = ((hash << 5) - hash + character.charCodeAt(0)) | 0; });
    return Math.abs(hash) % Math.max(1, length);
  }

  function slug(value) {
    return String(value || "")
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .toLowerCase();
  }

  function makeActivity(periodId, spot, definition, routeOnly, perspective) {
    const source = routeOnly ? ROUTE_APPROACHES : APPROACHES;
    const approachIds = definition.approaches || Object.keys(source).slice(0, 3);
    const relationId = definition.relation || null;
    const commonResources = definition.resources || {};
    const commonItems = definition.items || [];
    const choices = approachIds.map(function buildChoice(approachId) {
      const approach = source[approachId];
      const variants = APPROACH_VARIANTS[approachId] || [];
      const variant = variants[stableIndex(`${periodId}:${definition.id}:${approachId}`, variants.length)] || {};
      const override = (definition.choiceText || {})[approachId] || {};
      const statEffects = routeOnly || definition.noStats ? {} : { [approachId]: definition.statGain || 1 };
      const relationshipEffects = relationId ? { [relationId]: { ...approach.relation } } : {};
      const response = ((definition.responses || {})[approachId] || "").trim();
      return {
        id: approachId,
        label: override.label || variant.label || approach.label,
        note: override.note || variant.note || approach.note,
        response: [definition.resolution, response || variant.response || approach.response].filter(Boolean).join("\n\n"),
        effects: {
          stats: statEffects,
          relationships: relationshipEffects,
          resources: commonResources,
          items: commonItems,
          flags: [`storyWorld_${slug(periodId)}_${slug(definition.id)}_${slug(approachId)}`],
        },
      };
    });
    const activity = {
      id: definition.id,
      kind: definition.kind || "activity",
      title: definition.title,
      eyebrow: definition.eyebrow || (definition.kind === "job" ? "Service facultatif" : "Événement facultatif"),
      speaker: definition.speaker || "Narrateur",
      intro: definition.intro,
      prompt: definition.prompt || "Choisissez la manière d’aborder ce moment.",
      availableFrom: definition.availableFrom || 0,
      requiresRelation: definition.requiresRelation || null,
      choices,
    };
    if (typeof DIALOGUES.enrichActivity === "function") {
      return DIALOGUES.enrichActivity({ periodId, spot, definition, routeOnly, perspective, activity });
    }
    return activity;
  }

  function makeSpot(periodId, definition, routeOnly, perspective) {
    const extraMoments = EXTRA_MOMENTS[`${periodId}:${definition.id}`] || [];
    const dialogueMoments = (DIALOGUES.additions && DIALOGUES.additions[`${periodId}:${definition.id}`]) || [];
    return {
      id: definition.id,
      icon: definition.icon || "⌖",
      name: definition.name,
      shortName: definition.shortName || definition.name,
      description: definition.description,
      presence: definition.presence || "Le lieu continue de vivre autour de vous.",
      visualScene: definition.visualScene,
      background: definition.background || null,
      character: definition.character || null,
      sprite: definition.sprite || null,
      partyOutfits: definition.partyOutfits === true,
      availableFrom: definition.availableFrom || 0,
      activities: [...(definition.activities || []), ...extraMoments, ...dialogueMoments].map(function activity(entry) {
        const patched = typeof DIALOGUES.patchDefinition === "function"
          ? DIALOGUES.patchDefinition(periodId, definition.id, entry)
          : entry;
        return makeActivity(periodId, definition, patched, routeOnly || patched.routeOnly === true, perspective);
      }),
    };
  }

  function makePeriod(definition) {
    const routeOnly = definition.perspective && definition.perspective !== "Hylee";
    return {
      id: definition.id,
      target: `story_world_${slug(definition.id)}`,
      anchorScene: definition.anchorScene,
      nextScene: definition.nextScene,
      echoScene: definition.echoScene === undefined ? definition.nextScene : definition.echoScene,
      entryLabel: definition.entryLabel,
      title: definition.title,
      subtitle: definition.subtitle,
      chapterGate: definition.chapterGate,
      location: definition.location,
      locationNote: definition.locationNote,
      perspective: definition.perspective || "Hylee",
      music: definition.music || null,
      maxActions: definition.maxActions || definition.slots.length,
      slots: definition.slots,
      echo: definition.echo,
      completionFlags: definition.completionFlags || [],
      spots: definition.spots.map(function spot(entry) { return makeSpot(definition.id, entry, routeOnly, definition.perspective || "Hylee"); }),
    };
  }

  const periods = [
    makePeriod({
      id: "forestier-avant-depart",
      anchorScene: "ending",
      nextScene: "c2_01",
      chapterGate: "Fin du chapitre I",
      title: "Le camp avant Al’Gratal",
      subtitle: "Quelques heures avant de reprendre la route",
      entryLabel: "Vivre la halte avant Al’Gratal",
      location: "Campement de la forêt sylvinienne",
      locationNote: "Hylee et Remerii restent près du camp. Après deux années loin de l’auberge, la prochaine étape est Al’Gratal.",
      music: "music_confessions",
      maxActions: 2,
      slots: [
        { id: "soir", label: "Soirée", detail: "Le feu baisse après la décision de rejoindre Al’Gratal." },
        { id: "aube", label: "Avant l’aube", detail: "Les sacs attendent près du sentier encore sombre." },
      ],
      echo: "La halte donne au départ un poids concret : Hylee ne suit plus seulement Remerii, elle choisit de reprendre la route vers Al’Gratal avec elle.",
      spots: [
        {
          id: "salle",
          icon: "♨",
          name: "Feu du camp",
          description: "Les braises éclairent les cartes, deux gamelles et la route qu’elles reprendront au matin.",
          presence: "Remerii corrige l’itinéraire tandis qu’Hylee cherche ce que ce nouveau départ change réellement.",
          visualScene: "p03",
          character: "remerii",
          activities: [{
            id: "dernier-service",
            title: "Ce que le départ change vraiment",
            speaker: "Remerii",
            intro: "Le feu baisse après leur décision. Hylee veut savoir si Remerii l’emmène encore comme une jeune femme à protéger ou déjà comme une apprentie capable de choisir la route.",
            resolution: "La destination ne change pas. La place d’Hylee, elle, devient plus claire : Remerii approfondira son apprentissage, sans prétendre marcher à sa place.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
        {
          id: "chambre",
          icon: "⚑",
          name: "Paquetages",
          description: "Couvertures, vivres et matériel magique doivent tenir dans deux sacs déjà marqués par deux années de voyage.",
          presence: "Remerii vérifie les provisions et essaie de ne pas transformer l’aide en inspection militaire.",
          visualScene: "p03",
          character: "remerii",
          availableFrom: 1,
          activities: [{
            id: "faire-le-sac",
            title: "Ce que l’on emporte",
            speaker: "Hylee",
            intro: "Après deux années sur les routes, Hylee sait faire un sac. Remerii discute pourtant chaque fiole et l’ordre exact des poches.",
            resolution: "Le paquetage devient plus cohérent et la discussion moins technique. Elles reconnaissent les habitudes prises ensemble depuis l’auberge, celles qui font déjà de cette route une vie partagée.",
            relation: "remerii",
            approaches: ["lucidite", "sangfroid", "resonance"],
          }],
        },
        {
          id: "lisiere",
          icon: "⌁",
          name: "Sentier vers Al’Gratal",
          description: "Le chemin disparaît entre les arbres. Hylee connaît désormais le bruit de la forêt, sans prétendre en comprendre tous les avertissements.",
          presence: "Une présence animale tourne à distance du camp sans chercher à approcher.",
          visualScene: "p03",
          character: "hylee",
          activities: [{
            id: "dire-au-revoir",
            title: "La route qu’elle choisit encore",
            speaker: "Narrateur",
            intro: "Hylee marche jusqu’à la première borne. Deux ans plus tôt, quitter l’auberge avait ressemblé à une fuite. Cette fois, elle peut regarder le chemin et décider consciemment de continuer.",
            resolution: "La forêt ne lui promet rien. Hylee revient pourtant vers le camp avec une certitude simple : elle ne va pas à Al’Gratal parce qu’elle n’a nulle part ailleurs où aller.",
            approaches: ["sangfroid", "resonance", "audace"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "algratal-preparatifs",
      anchorScene: "c2_45",
      nextScene: "c3_01",
      chapterGate: "Fin du chapitre II",
      title: "Quelques heures à Al’Gratal",
      subtitle: "La veille des préparatifs pour Mir’Aldas",
      entryLabel: "Explorer Al’Gratal avant les préparatifs",
      location: "Al’Gratal",
      locationNote: "La capitale est accessible, mais les catacombes et les zones militaires restent fermées sans escorte.",
      music: "music_algratal",
      maxActions: 3,
      slots: [
        { id: "fin-apres-midi", label: "Fin d’après-midi", detail: "La réunion vient de se disperser." },
        { id: "soir", label: "Soirée", detail: "Les lanternes remplacent le soleil sur le marbre." },
        { id: "nuit", label: "Début de nuit", detail: "Le palais ralentit sans vraiment dormir." },
      ],
      echo: "Al’Gratal n’est plus seulement la capitale qui écrase Hylee : elle en connaît désormais quelques visages, quelques détours et les conséquences modestes d’une décision prise loin des grandes scènes.",
      spots: [
        {
          id: "marche",
          icon: "◈",
          name: "Grand Marché",
          description: "Étoffes enchantées, cristaux de voyage et provisions changent encore de mains avant la fermeture.",
          presence: "Remerii accompagne Hylee entre les derniers étals.",
          visualScene: "c3_02",
          character: "remerii",
          activities: [{
            id: "provisions",
            title: "Le dernier étal ouvert",
            speaker: "Remerii",
            intro: "Trois nécessaires de voyage paraissent identiques. L’un est solide, l’autre élégant, le troisième réagit faiblement à la magie d’Hylee.",
            resolution: "Le choix cesse d’être une simple dépense : il devient une première manière de préparer la route selon la Hylee que le joueur construit.",
            relation: "remerii",
            items: ["necessaire_de_route"],
            approaches: ["lucidite", "resonance", "audace"],
          }],
        },
        {
          id: "palais",
          icon: "♜",
          name: "Galerie du palais",
          description: "Les requêtes de la cour s’empilent plus vite que les serviteurs ne peuvent les emporter.",
          presence: "Iriana termine le triage de plusieurs dossiers sans secrétaire.",
          visualScene: "c2_41",
          character: "iriana",
          activities: [{
            id: "requetes-introduction",
            kind: "job",
            title: "Trois requêtes, aucune bonne pile",
            speaker: "Iriana",
            intro: "Une citerne fissurée, une livraison médicale bloquée et un noble contrarié par un arbre réclament tous la priorité.",
            resolution: "Iriana reprend l’ordre proposé sans le corriger entièrement. Son silence ressemble pour la première fois à une confiance en construction.",
            relation: "iriana",
            resources: { coins: 5 },
            approaches: ["lucidite", "sangfroid", "audace"],
          }],
        },
        {
          id: "avenues",
          icon: "⌁",
          name: "Avenues impériales",
          description: "Les façades blanches cachent les cuisines, les ateliers de nuit et les passages utilisés par ceux que la cour ne regarde pas.",
          presence: "Hylee peut marcher seule, sans cesser de rester dans le périmètre autorisé.",
          visualScene: "c2_10",
          character: "hylee",
          activities: [{
            id: "ville-vivante",
            title: "Derrière les bannières",
            speaker: "Narrateur",
            intro: "La capitale continue de vivre. Dans ses rues, rien ne trahit la mission secrète décidée sous le palais.",
            resolution: "Al’Gratal redevient une ville faite de personnes, pas seulement le symbole immense d’un Empire.",
            approaches: ["lucidite", "resonance", "sangfroid"],
          }],
        },
        {
          id: "appartements",
          icon: "☾",
          name: "Appartements d’hôtes",
          description: "Les cartes de Mir’Aldas couvrent une table trop petite pour tout ce que Remerii évite de dire.",
          presence: "Remerii vérifie plusieurs fois le même itinéraire.",
          visualScene: "c2_43",
          character: "remerii",
          availableFrom: 1,
          activities: [{
            id: "retour-miraldas",
            title: "Ce que signifie rentrer",
            speaker: "Remerii",
            intro: "Mir’Aldas est une destination pour Hylee et un retour pour Remerii. La différence pèse dans chacun de ses gestes.",
            resolution: "La route ne change pas, mais Remerii n’a plus à porter seule tout ce que le nom de Mir’Aldas réveille.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid", "resonance"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "camp-avant-croisee",
      anchorScene: "c3_55",
      nextScene: "c4_00",
      chapterGate: "Fin du chapitre III",
      title: "Une halte avant Mir’Aldas",
      subtitle: "Le matin après le cauchemar",
      entryLabel: "Prendre le temps de lever le camp",
      location: "Campement de route",
      locationNote: "Le groupe ne s’éloigne pas du camp : Mir’Aldas est proche et la route principale reprend bientôt.",
      music: "music_confessions",
      maxActions: 2,
      slots: [
        { id: "aube", label: "Aube", detail: "Le feu est bas et les traces du cauchemar restent visibles." },
        { id: "matin", label: "Matin", detail: "Le camp doit disparaître avant de reprendre la route." },
      ],
      echo: "La halte a transformé le départ en choix préparé plutôt qu’en fuite après le cauchemar.",
      spots: [
        {
          id: "feu",
          icon: "♨",
          name: "Feu mourant",
          description: "Les braises éclairent encore les couvertures et les visages fatigués.",
          presence: "Remerii est restée éveillée plus longtemps qu’elle ne l’admettra.",
          visualScene: "c3_51",
          character: "remerii",
          activities: [{
            id: "apres-cauchemar",
            title: "Ce que la nuit a laissé",
            speaker: "Remerii",
            intro: "Hylee peut parler du petit frère, de sa magie ou simplement de la peur d’avoir montré trop de choses.",
            resolution: "Le cauchemar ne disparaît pas, mais il cesse d’être une preuve qu’Hylee doit affronter seule.",
            relation: "remerii",
            approaches: ["sangfroid", "lucidite", "resonance"],
          }],
        },
        {
          id: "lisiere",
          icon: "⌁",
          name: "Lisière du camp",
          description: "Les premières lumières du Dôme colorent déjà certaines feuilles au loin.",
          presence: "Medig observe les préparatifs depuis une branche trop basse pour être innocente.",
          visualScene: "c3_55",
          character: "hylee",
          activities: [{
            id: "ecouter-dome",
            title: "La proximité du Dôme",
            speaker: "Narrateur",
            intro: "La magie de Mir’Aldas est encore invisible, mais Hylee la sent peser sur l’horizon.",
            resolution: "Elle apprend à distinguer l’appel du Dôme de sa propre impatience.",
            approaches: ["resonance", "lucidite", "sangfroid"],
          }],
        },
        {
          id: "bagages",
          icon: "⚑",
          name: "Zone des bagages",
          description: "Le camp doit être défait sans laisser de trace ni perdre ce qui vient d’être acheté.",
          presence: "Remerii répartit les charges ; Hylee peut proposer une meilleure organisation.",
          visualScene: "c3_52",
          character: "hylee",
          activities: [{
            id: "lever-camp",
            kind: "job",
            title: "Effacer le passage",
            speaker: "Narrateur",
            intro: "Cordes, couvertures, cendres et traces de magie doivent être traitées avant le départ.",
            resolution: "Le camp disparaît sans précipitation. Le groupe emporte ce dont il a besoin et ne laisse derrière lui aucune faiblesse évidente.",
            resources: { supplies: 1 },
            approaches: ["lucidite", "sangfroid", "audace"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "calciterres-apres-valurn",
      anchorScene: "c4v_61",
      nextScene: "c5_01",
      chapterGate: "Fin de la route Valurn",
      title: "Le retour des Calciterres",
      subtitle: "Une route qui refuse de rendre ses secrets",
      entryLabel: "Prolonger le retour de Valurn",
      location: "Calciterres",
      locationNote: "Valurn reste sur le chemin du retour. Akuhn’Nabad et les territoires interdits demeurent hors d’atteinte.",
      perspective: "Valurn",
      music: "music_bellirith",
      maxActions: 2,
      slots: [
        { id: "crepuscule", label: "Crépuscule", detail: "Les ruines mortelles disparaissent derrière la poussière." },
        { id: "nuit", label: "Nuit", detail: "Une halte discrète s’impose avant de rejoindre l’Empire." },
      ],
      echo: "Valurn rapporte plus que des informations : ses décisions sur le chemin du retour déterminent ce qu’il choisira de taire au groupe.",
      spots: [
        {
          id: "ruines",
          icon: "◇",
          name: "Ruines mortelles",
          description: "La chaleur résiduelle et les pierres fendues gardent la trace des vérités arrachées.",
          presence: "Valurn est seul, du moins en apparence.",
          visualScene: "c4v_60",
          character: "valurn",
          activities: [{
            id: "traces-bellirith",
            title: "Le prix invisible",
            speaker: "Valurn",
            intro: "Bellirith l’a laissé partir trop facilement. Chercher une marque est peut-être prudent ; la trouver serait pire.",
            resolution: "Valurn reconnaît une trace assez discrète pour être volontaire. Bellirith ne l’a pas suivi : elle lui rappelle seulement qu’elle pourrait le faire.",
            relation: "bellirith",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "camp",
          icon: "♨",
          name: "Halte de pierre",
          description: "Un renfoncement protège à peine du vent chargé de cendre.",
          presence: "Valurn doit décider ce qu’il consignera avant que ses souvenirs ne deviennent une version commode.",
          visualScene: "c4v_61",
          character: "valurn",
          activities: [{
            id: "rapport",
            title: "Écrire pour Iriana",
            speaker: "Narrateur",
            intro: "Le rapport peut être exact, utile ou protecteur. Il ne pourra probablement pas être les trois à la fois.",
            resolution: "Le document est scellé. Ce qu’il contient influencera la confiance d’Iriana ; ce qu’il omet restera entre Valurn et les Calciterres.",
            relation: "iriana",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "route",
          icon: "⌁",
          name: "Route de l’Empire",
          description: "Au loin, les premières bornes impériales marquent le retour vers un monde de règles plus visibles.",
          presence: "Personne n’attend Valurn. Cette absence lui offre une liberté rare.",
          visualScene: "c4v_60",
          character: "valurn",
          activities: [{
            id: "detour",
            title: "Un détour sans témoin",
            speaker: "Narrateur",
            intro: "Une ancienne cache des Saël se trouve à quelques minutes du chemin principal.",
            resolution: "Le détour révèle des provisions intactes et une marque récente. Quelqu’un utilise encore les réseaux que Valurn croyait abandonnés.",
            routeOnly: true,
            resources: { supplies: 1 },
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "forthaven-apres-draven",
      anchorScene: "c4d_38",
      nextScene: "c5_01",
      chapterGate: "Fin de la route Draven",
      title: "Une nuit à Forthaven",
      subtitle: "Avant le départ du détachement",
      entryLabel: "Rester quelques heures à Forthaven",
      location: "Forthaven",
      locationNote: "Draven reste entre la citadelle, les remparts et les quais. La ville basse demeure trop dangereuse.",
      perspective: "Draven",
      music: "music_draven_storm",
      maxActions: 2,
      slots: [
        { id: "soir", label: "Relève du soir", detail: "Les équipes quittent les remparts une par une." },
        { id: "nuit", label: "Nuit", detail: "Les cloches du port mesurent un repos qui n’en est pas un." },
      ],
      echo: "Forthaven n’est plus une simple promesse de renfort : les heures passées sur place donnent un visage aux soldats et aux civils que Draven engage dans la mission.",
      spots: [
        {
          id: "quais",
          icon: "≋",
          name: "Quais militaires",
          description: "Caisses, cordages et matériel médical doivent être répartis avant l’appareillage.",
          presence: "Des marins attendent une décision que personne ne veut prendre à leur place.",
          visualScene: "c4d_34",
          character: "draven",
          activities: [{
            id: "chargement",
            kind: "job",
            title: "Un navire trop chargé",
            speaker: "Draven",
            intro: "Le détachement veut emporter plus d’armes, les soigneurs plus de matériel et les marins assez de vivres pour revenir.",
            resolution: "Le chargement devient un compromis assumé plutôt qu’un empilement de peurs concurrentes.",
            relation: "lineva",
            routeOnly: true,
            resources: { supplies: 2 },
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "remparts",
          icon: "⚔",
          name: "Remparts de la ville haute",
          description: "La mer noire et les feux de la ville basse dessinent une frontière impossible à oublier.",
          presence: "Lineva termine elle-même une inspection qu’elle aurait dû déléguer.",
          visualScene: "c4d_37",
          character: "lineva",
          activities: [{
            id: "lineva",
            title: "Ce que le départ coûte",
            speaker: "Lineva",
            intro: "Lineva a accepté de céder des soldats à une mission impériale alors que sa propre ville manque déjà de bras.",
            resolution: "Aucun argument ne rend la décision juste. Draven peut au moins reconnaître clairement la dette qu’il vient de contracter.",
            relation: "lineva",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "salle-guerre",
          icon: "▤",
          name: "Salle de commandement",
          description: "Les cartes portent les marques des attaques récentes et des quartiers déjà perdus.",
          presence: "Draven peut revoir une dernière fois les voies de secours avec l’officier de garde.",
          visualScene: "c4d_38",
          character: "draven",
          activities: [{
            id: "replis",
            title: "Les lignes que l’on dessine pour survivre",
            speaker: "Narrateur",
            intro: "Préparer une victoire est glorieux. Préparer une retraite demande d’admettre que des plans peuvent échouer.",
            resolution: "Deux voies de repli sont ajoutées à la carte. Personne ne les célébrera, mais elles pourraient sauver une section entière.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "miraldas-apres-saidin",
      anchorScene: "c5_47",
      nextScene: "c6_01",
      chapterGate: "Fin du chapitre V",
      title: "Mir’Aldas après l’épreuve",
      subtitle: "Une cité enfin ouverte",
      entryLabel: "Découvrir Mir’Aldas librement",
      location: "Mir’Aldas",
      locationNote: "Le Dôme, la bibliothèque et les quartiers proches sont ouverts. Les zones réservées aux Archimages restent surveillées.",
      music: "music_c5_miraldas",
      maxActions: 3,
      slots: [
        { id: "apres-midi", label: "Fin d’après-midi", detail: "L’épreuve de Saidin vient de s’achever." },
        { id: "soir", label: "Soirée", detail: "Les cristaux de la cité prennent une couleur plus douce." },
        { id: "nuit", label: "Nuit sous le Dôme", detail: "Les rues se vident, mais la magie reste éveillée." },
      ],
      echo: "Hylee entre dans le chapitre suivant avec une Mir’Aldas déjà vécue, pas seulement admirée depuis les scènes imposées.",
      spots: [
        {
          id: "dome",
          icon: "◉",
          name: "Place du Grand Dôme",
          description: "Mages, apprentis et artisans circulent sous la barrière arcanique désormais familière.",
          presence: "Hylee peut enfin observer la ville sans courir vers une audience.",
          visualScene: "c5_01",
          character: "hylee",
          activities: [{
            id: "premiers-reperes",
            title: "Une cité qui n’appartient pas à l’Empire",
            speaker: "Narrateur",
            intro: "Les règles de Mir’Aldas se lisent dans les gestes des habitants plus sûrement que dans les proclamations.",
            resolution: "Hylee reconnaît les signes qui indiquent un atelier libre, un passage réservé et une discussion qu’il vaut mieux ne pas interrompre.",
            approaches: ["lucidite", "resonance", "sangfroid"],
          }],
        },
        {
          id: "bibliotheque",
          icon: "▤",
          name: "Grande Bibliothèque",
          description: "Les rayonnages mouvants continuent leur travail après le départ des visiteurs officiels.",
          presence: "Saidin consulte déjà un texte qu’il prétendait ne pas posséder.",
          visualScene: "c5_20",
          character: "saidin",
          activities: [{
            id: "question-saidin",
            title: "Une réponse hors du temps",
            speaker: "Saidin",
            intro: "Hylee dispose d’une question. Saidin dispose de plusieurs façons de ne pas y répondre complètement.",
            resolution: "La réponse reste oblique, mais Hylee comprend mieux la différence entre ce que Saidin ignore et ce qu’il refuse de dire.",
            relation: "saidin",
            approaches: ["lucidite", "audace", "resonance"],
          }],
        },
        {
          id: "atelier",
          icon: "⚙",
          name: "Atelier arcanique",
          description: "Bâtons, cristaux et matrices de sort occupent chaque surface disponible.",
          presence: "Remerii connaît encore l’emplacement des outils malgré les années.",
          visualScene: "c5_33",
          character: "remerii",
          activities: [{
            id: "ajuster-baton",
            kind: "job",
            title: "Accorder le cerisier noir",
            speaker: "Remerii",
            intro: "Le nouveau bâton d’Hylee réagit au Dôme avec trop d’enthousiasme. Un réglage évitera qu’il amplifie chaque émotion.",
            resolution: "Le bâton ne devient pas plus puissant. Il devient plus honnête : il amplifie moins ce qu’Hylee ne maîtrise pas encore.",
            relation: "remerii",
            approaches: ["lucidite", "resonance", "sangfroid"],
          }],
        },
        {
          id: "residence",
          icon: "☾",
          name: "Résidence des mages",
          description: "Des appartements sobres s’ouvrent sur les lueurs violettes de la cité.",
          presence: "Remerii retrouve des habitudes anciennes et tente de les dissimuler derrière l’hospitalité.",
          visualScene: "c5_47",
          character: "remerii",
          availableFrom: 1,
          activities: [{
            id: "remettre-clefs",
            title: "Une chambre qui se souvient",
            speaker: "Remerii",
            intro: "La clé tourne trop facilement. Remerii n’était manifestement pas aussi absente de Mir’Aldas qu’elle le laissait entendre.",
            resolution: "Hylee ne force aucune confession. Elle apprend simplement à reconnaître les endroits où le passé de Remerii continue de tenir une porte ouverte.",
            relation: "remerii",
            approaches: ["lucidite", "sangfroid", "audace"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "miraldas-matin-libre",
      anchorScene: "c6_32",
      nextScene: "c7_01",
      chapterGate: "Fin du chapitre VI",
      title: "Le matin sous le Dôme",
      subtitle: "Après la parenthèse nocturne",
      entryLabel: "Profiter encore de Mir’Aldas",
      location: "Mir’Aldas",
      locationNote: "Une matinée seulement est disponible avant que le récit ne rejoigne la route de Valurn.",
      music: "music_c6_miraldas_city",
      maxActions: 2,
      slots: [
        { id: "aube", label: "Aube", detail: "La lumière du Dôme revient avant le soleil." },
        { id: "matin", label: "Matin", detail: "Les ateliers ouvrent et les messages de la mission reviennent." },
      ],
      echo: "La parenthèse de Mir’Aldas ne s’achève pas brutalement : le matin laisse à Hylee et Remerii le temps de transformer leur proximité en gestes ordinaires.",
      spots: [
        {
          id: "patisserie",
          icon: "◈",
          name: "Échoppe aux tartelettes",
          description: "L’odeur sucrée précède l’ouverture officielle de la boutique.",
          presence: "Remerii prétend que l’arrêt répond à une nécessité culturelle.",
          visualScene: "c6_04",
          character: "remerii",
          activities: [{
            id: "petit-dejeuner",
            title: "Une dette de tartelette",
            speaker: "Hylee",
            intro: "Cette fois, Hylee veut payer ou au moins rendre l’attention autrement.",
            resolution: "Ce petit déjeuner pourrait devenir une habitude. Cette possibilité trouble Remerii davantage qu’elle ne le montre.",
            relation: "remerii",
            resources: { coins: -2 },
            approaches: ["audace", "lucidite", "sangfroid"],
          }],
        },
        {
          id: "terrasse",
          icon: "⌛",
          name: "Terrasse arcanique",
          description: "La ville se réveille sous une constellation artificielle qui tarde à disparaître.",
          presence: "Hylee peut revenir seule à l’endroit où la nuit a changé de ton.",
          visualScene: "c6_20",
          character: "hylee",
          activities: [{
            id: "apres-proximite",
            title: "Le lendemain d’un moment fragile",
            speaker: "Narrateur",
            intro: "Les gestes de la veille semblent plus simples lorsqu’ils ne sont pas encore commentés.",
            resolution: "Hylee refuse de transformer la tendresse en dette ou en certitude prématurée. Elle garde seulement ce qui a réellement eu lieu.",
            approaches: ["sangfroid", "lucidite", "resonance"],
          }],
        },
        {
          id: "atelier",
          icon: "⚙",
          name: "Atelier des apprentis",
          description: "Une série de cristaux instables attend d’être triée avant les cours du matin.",
          presence: "Un maître d’atelier accepte l’aide d’Hylee si elle suit les règles de sécurité.",
          visualScene: "c6_10",
          character: "hylee",
          activities: [{
            id: "tri-cristaux",
            kind: "job",
            title: "Cristaux capricieux",
            speaker: "Maître d’atelier",
            intro: "Les cristaux doivent être classés selon leur vibration, leur température et le risque de rupture.",
            resolution: "Le tri est assez propre pour que personne ne perde un sourcil à l’ouverture de l’atelier.",
            resources: { coins: 6 },
            approaches: ["lucidite", "resonance", "sangfroid"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "foret-apres-pacte",
      anchorScene: "c7_end",
      nextScene: "c8_01",
      chapterGate: "Fin du chapitre VII",
      title: "Après le pacte de la forêt",
      subtitle: "Valurn et Naïah avant la séparation",
      entryLabel: "Rester un instant dans la Forêt Interdite",
      location: "Forêt Interdite",
      locationNote: "Le pacte stabilise seulement quelques sentiers autour de la clairière de Naïah.",
      perspective: "Valurn",
      music: "music_c7_rencontre_naiah",
      maxActions: 2,
      slots: [
        { id: "apres-pacte", label: "Après le pacte", detail: "La forêt écoute encore la nouvelle alliance." },
        { id: "depart", label: "Avant le départ", detail: "Les chemins commencent déjà à changer de place." },
      ],
      echo: "Le pacte gagne une première épaisseur : Valurn et Naïah se quittent avec autre chose qu’une poignée de main et une menace élégante.",
      spots: [
        {
          id: "clairiere",
          icon: "⌁",
          name: "Clairière de Naïah",
          description: "Le silence du pacte reste suspendu entre les racines.",
          presence: "Naïah n’a pas encore disparu, ce qui constitue déjà une forme d’invitation.",
          visualScene: "c7_success_high",
          character: "naiah",
          activities: [{
            id: "termes-pacte",
            title: "Ce que le pacte n’a pas précisé",
            speaker: "Naïah",
            intro: "Valurn a obtenu un guide. Naïah veut s’assurer qu’il n’a pas confondu guide, servante et garantie.",
            resolution: "Les limites restent dangereuses, mais elles deviennent explicites. Ce pacte pourra être trahi ; il ne pourra pas prétendre avoir été mal compris.",
            relation: "naiah",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "ruines",
          icon: "◇",
          name: "Ruines noyées de brume",
          description: "Des marques anciennes du Chaos affleurent sous les racines sombres.",
          presence: "Valurn peut étudier les pierres ; Naïah le surveille depuis un endroit volontairement introuvable.",
          visualScene: "c7_fragment",
          character: "valurn",
          activities: [{
            id: "marque-chaos",
            title: "Une signature trop ancienne",
            speaker: "Narrateur",
            intro: "La marque n’appartient ni à Valurn ni à son père, mais elle reconnaît pourtant quelque chose dans son sang.",
            resolution: "Il en conserve un relevé sans activer le sceau. Certaines réponses méritent d’attendre un lieu moins désireux de les dévorer.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "lisiere",
          icon: "⌁",
          name: "Sentier de sortie",
          description: "La brume ouvre un chemin étroit vers les terres impériales.",
          presence: "Naïah accompagne Valurn assez loin pour s’assurer que la forêt accepte de le rendre.",
          visualScene: "c7_end",
          character: "valurn",
          activities: [{
            id: "au-revoir",
            title: "Une séparation sans formule",
            speaker: "Valurn",
            intro: "Aucun des deux n’aime assez les adieux pour en prononcer un correctement.",
            resolution: "Ils se quittent sur une provocation dont chacun saisit le sens : ils comptent se revoir.",
            relation: "naiah",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "algratal-avant-expedition",
      anchorScene: "c8_end",
      nextScene: "c9_01",
      chapterGate: "Fin du chapitre VIII",
      title: "Les jours avant l’expédition",
      subtitle: "Le groupe réuni à Al’Gratal",
      entryLabel: "Organiser une journée libre à Al’Gratal",
      location: "Al’Gratal",
      locationNote: "Une journée complète est disponible, mais les déplacements restent limités à la capitale et au camp militaire proche.",
      music: "music_algratal",
      maxActions: 4,
      slots: [
        { id: "aube", label: "Aube", detail: "Le camp de Forthaven se réveille près des murailles." },
        { id: "matin", label: "Matin", detail: "Le palais et le marché ouvrent leurs portes." },
        { id: "apres-midi", label: "Après-midi", detail: "Le groupe se disperse pour les derniers préparatifs." },
        { id: "soir", label: "Soirée", detail: "Chacun mesure ce qu’il emmènera dans la Forêt Interdite." },
      ],
      echo: "La veille du départ porte désormais les réactions de tout le groupe. Les liens tissés pendant cette journée peuvent ouvrir des nuances dans les scènes suivantes.",
      spots: [
        {
          id: "camp-forthaven",
          icon: "⚑",
          name: "Camp du détachement",
          description: "Les soldats de Forthaven montent les tentes, réparent les armes et découvrent la capitale.",
          presence: "Draven inspecte les postes. Lineva n’a pas fait le voyage, pourtant son autorité se lit partout.",
          visualScene: "c8_01",
          character: "draven",
          activities: [{
            id: "aider-camp",
            kind: "job",
            title: "Répartir les fournitures",
            speaker: "Draven",
            intro: "Les caisses impériales ne correspondent pas aux listes de Forthaven. Il faut choisir entre attendre, improviser ou confronter l’intendance.",
            resolution: "Le camp dispose enfin d’un inventaire réel au lieu de deux documents qui se contredisent.",
            relation: "draven",
            resources: { supplies: 2 },
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
        {
          id: "palais",
          icon: "♜",
          name: "Salle des requêtes",
          description: "Les préparatifs de guerre n’ont pas empêché la cour de produire de nouveaux problèmes.",
          presence: "Iriana supervise un triage plus sensible que celui de la première soirée.",
          visualScene: "c8_09",
          character: "iriana",
          activities: [{
            id: "triage-imperial",
            kind: "job",
            title: "Triage des requêtes impériales",
            speaker: "Iriana",
            intro: "Certaines requêtes sont absurdes ; d’autres cachent des conséquences militaires. Iriana ne confie ce bureau qu’à quelqu’un dont elle estime déjà le jugement.",
            resolution: "Les requêtes urgentes atteignent les bons bureaux avant le départ. Iriana n’offre aucun compliment, mais elle remet à Hylee le sceau de la pile suivante.",
            relation: "iriana",
            resources: { coins: 10 },
            requiresRelation: { id: "iriana", min: 2 },
            approaches: ["lucidite", "sangfroid", "audace"],
          }],
        },
        {
          id: "marche",
          icon: "◈",
          name: "Grand Marché",
          description: "Le matériel de route se vend plus cher depuis que les rumeurs d’expédition circulent.",
          presence: "Valurn marchande des informations ; Remerii vérifie les protections magiques.",
          visualScene: "c8_09",
          character: "valurn",
          activities: [{
            id: "dernier-achat",
            title: "Les prix de la peur",
            speaker: "Valurn",
            intro: "Un marchand a doublé le prix des fioles anti-brume depuis l’arrivée du détachement.",
            resolution: "Le groupe obtient ce dont il a besoin sans faire de la peur du vendeur une excuse pour accepter n’importe quel marché.",
            relation: "valurn",
            resources: { coins: -4, supplies: 1 },
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
        {
          id: "appartements",
          icon: "☾",
          name: "Appartements du groupe",
          description: "Les sacs ouverts et les cartes annotées transforment les chambres en quartier général improvisé.",
          presence: "Remerii prépare Hylee ; Naïah apparaît seulement si elle en a envie.",
          visualScene: "c8_13",
          character: "naiah",
          availableFrom: 2,
          activities: [{
            id: "retrouvailles-naiah",
            title: "Une amie revenue avec les ombres",
            speaker: "Naïah",
            intro: "Hylee retrouve une Naïah différente de celle de l’auberge, plus proche de sa forêt et de ses secrets.",
            resolution: "La conversation laisse les absences intactes. Les deux femmes retrouvent toutefois une manière de se parler hors de leurs rôles dans la mission.",
            relation: "naiah",
            approaches: ["lucidite", "audace", "resonance"],
          }],
        },
        {
          id: "toits",
          icon: "⌛",
          name: "Toits du quartier impérial",
          description: "Saidin observe les routes comme s’il pouvait déjà voir plusieurs départs concurrents.",
          presence: "L’archimage accepte la compagnie tant qu’on ne lui demande pas de l’avouer.",
          visualScene: "c8_end",
          character: "saidin",
          availableFrom: 3,
          activities: [{
            id: "parler-temps",
            title: "La route qui pourrait ne pas exister",
            speaker: "Saidin",
            intro: "Saidin laisse entendre que certaines décisions du lendemain ferment davantage de futurs qu’elles n’en ouvrent.",
            resolution: "Hylee n’obtient aucune prédiction. Elle comprend en revanche pourquoi Saidin refuse de confondre connaissance et droit de choisir pour les autres.",
            relation: "saidin",
            approaches: ["lucidite", "sangfroid", "resonance"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "geoles-apres-capture",
      anchorScene: "c9_end",
      nextScene: "c10_route_entry",
      echoScene: "c10_01",
      chapterGate: "Fin du chapitre IX",
      title: "Quelques heures dans les geôles",
      subtitle: "Liberté minimale après la capture",
      entryLabel: "Observer les geôles avant la suite",
      location: "Geôles d’Akuhn’Nabad",
      locationNote: "Le groupe est prisonnier. La liberté consiste à parler, observer et préparer une réaction, pas à visiter artificiellement la cité.",
      music: "music_c9_capture",
      maxActions: 2,
      slots: [
        { id: "apres-capture", label: "Après la capture", detail: "Les gardes viennent de quitter le couloir." },
        { id: "attente", label: "Temps indistinct", detail: "Sans lumière naturelle, les minutes perdent leur forme." },
      ],
      echo: "Les prisonniers n’arrivent pas à la suite dans le même état : les observations et les conversations menées en cellule donnent déjà une direction à leur manière d’affronter Akuhn’Nabad.",
      spots: [
        {
          id: "cellule",
          icon: "▥",
          name: "Cellule du groupe",
          description: "Les murs noirs absorbent une partie des sons et rendent chaque silence plus lourd.",
          presence: "Hylee, Remerii, Draven, Valurn et Saidin partagent un espace trop étroit.",
          visualScene: "c9_end",
          character: "remerii",
          activities: [{
            id: "parler-groupe",
            title: "Empêcher la peur de choisir un coupable",
            speaker: "Narrateur",
            intro: "La capture offre trop de raisons de s’accuser. Une phrase mal placée pourrait fracturer le groupe avant même l’interrogatoire.",
            resolution: "Personne ne se réconcilie avec l’échec. Le groupe accepte seulement de garder ses comptes ouverts jusqu’à disposer de faits.",
            relation: "draven",
            approaches: ["sangfroid", "lucidite", "audace"],
          }],
        },
        {
          id: "barreaux",
          icon: "◇",
          name: "Barrière de la cellule",
          description: "Les runes réagissent différemment au froid, au temps et au Chaos.",
          presence: "Remerii et Saidin testent les limites sans déclencher l’alarme.",
          visualScene: "c9_end",
          character: "saidin",
          activities: [{
            id: "etudier-runes",
            title: "Une serrure qui apprend",
            speaker: "Saidin",
            intro: "La barrière adapte sa réponse à chaque tentative. La forcer maintenant pourrait la rendre plus dangereuse ensuite.",
            resolution: "Hylee mémorise un cycle de faiblesse. La cellule ne pourra plus leur reprendre cette première possibilité de sortie.",
            relation: "saidin",
            approaches: ["lucidite", "resonance", "sangfroid"],
          }],
        },
        {
          id: "couloir",
          icon: "⌁",
          name: "Couloir visible",
          description: "Depuis l’angle des barreaux, quelques portes et mouvements de garde restent observables.",
          presence: "Naïah semble écouter quelque chose que les autres ne perçoivent pas.",
          visualScene: "c9_end",
          character: "naiah",
          activities: [{
            id: "ecouter-cite",
            title: "La ville derrière les murs",
            speaker: "Naïah",
            intro: "Les pas des gardes ne ressemblent pas à ceux d’une armée paniquée. La cité fonctionne, organisée, autour de leur captivité.",
            resolution: "Le premier mensonge impérial se fissure avant même que le groupe voie les rues : ces geôles appartiennent à un État, pas à une bande cachée dans des ruines.",
            relation: "naiah",
            approaches: ["lucidite", "resonance", "sangfroid"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "akuhn-iriana-apres-audience",
      anchorScene: "c10_end",
      nextScene: "c11i_001",
      chapterGate: "Fin du chapitre X-I",
      title: "Akuhn’Nabad après l’audience",
      subtitle: "Iriana entre deux vérités",
      entryLabel: "Parcourir le palais avec Iriana",
      location: "Akuhn’Nabad",
      locationNote: "Iriana est invitée sous surveillance. Le palais et quelques rues escortées sont accessibles, pas l’ensemble du territoire obscurci.",
      perspective: "Iriana",
      music: "music_c10_cite",
      maxActions: 3,
      slots: [
        { id: "fin-audience", label: "Fin d’audience", detail: "Amanea a quitté la terrasse sans clore la discussion." },
        { id: "soir", label: "Soirée", detail: "La Cité Noire continue de vivre sous les feux verts." },
        { id: "nuit", label: "Nuit", detail: "Les appartements prêtés deviennent un espace de réflexion surveillé." },
      ],
      echo: "Iriana arrive dans les quartiers d’Amanea avec des observations concrètes sur la cité et une relation déjà nuancée par les heures qui ont suivi l’audience.",
      spots: [
        {
          id: "terrasse",
          icon: "☾",
          name: "Terrasse des feux verts",
          description: "La capitale obscurcie s’étend sous Iriana comme une contradiction vivante.",
          presence: "Amanea reste à proximité et laisse volontairement Iriana observer seule.",
          visualScene: "c10_23",
          character: "iriana",
          activities: [{
            id: "regarder-ville",
            title: "Un peuple, pas une légende",
            speaker: "Narrateur",
            intro: "Les écoles, les marchés et les rondes de garde refusent de correspondre à l’image d’un chaos criminel.",
            resolution: "Iriana ne transforme pas une soirée en absolution. Elle accepte seulement que les faits observés aient le droit de contredire l’éducation impériale.",
            relation: "amanea",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "rues",
          icon: "⌁",
          name: "Rue escortée du palais",
          description: "Artisans et familles ralentissent en reconnaissant la tenue d’Iriana.",
          presence: "Une garde obscurcie accompagne Iriana sans chercher à guider chacune de ses conclusions.",
          visualScene: "c10_14",
          character: "iriana",
          activities: [{
            id: "incident-marche",
            title: "Une altercation ordinaire",
            speaker: "Narrateur",
            intro: "Deux commerçants se disputent un emplacement tandis qu’un enfant reconnaît ouvertement la princesse ennemie.",
            resolution: "La scène reste banale, presque décevante. C’est précisément ce qui la rend impossible à classer dans la propagande d’Iriana.",
            relation: "amanea",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "archives",
          icon: "▤",
          name: "Antichambre des archives",
          description: "Des registres publics permettent de vérifier certains récits sans entrer dans les fonds interdits.",
          presence: "Un archiviste obscurci répond aux questions littérales et laisse les préjugés se débrouiller seuls.",
          visualScene: "c10_end",
          character: "iriana",
          activities: [{
            id: "registres",
            title: "Compter les absents",
            speaker: "Archiviste",
            intro: "Les registres d’arrivée racontent combien de bannis, de réfugiés et d’anciens prisonniers ont rejoint la cité.",
            resolution: "Iriana relève plusieurs noms que l’Empire classait comme morts. La Cité Noire a parfois été un exil ; elle a aussi été une survie.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "appartements",
          icon: "♜",
          name: "Quartiers prêtés",
          description: "Une chambre trop confortable pour une prison et trop gardée pour être entièrement une invitation.",
          presence: "Amanea fait porter un repas et un seul message : demain, elles parleront sans cour.",
          visualScene: "c10_end",
          character: "amanea",
          availableFrom: 2,
          activities: [{
            id: "message-amanea",
            title: "Répondre ou laisser attendre",
            speaker: "Iriana",
            intro: "Iriana peut envoyer une réponse à Amanea, demander une précision ou refuser que la nuit devienne une négociation de plus.",
            resolution: "La réponse fixe le ton de leur prochaine rencontre sans prétendre résoudre ce qui sépare les deux Farae.",
            relation: "amanea",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "algratal-groupe-retour",
      anchorScene: "c10g_end",
      nextScene: "c11g_001",
      chapterGate: "Fin du chapitre X-G",
      title: "Le retour du groupe à Al’Gratal",
      subtitle: "Après les geôles de la Cité Noire",
      entryLabel: "Laisser le groupe respirer avant le bal",
      location: "Al’Gratal",
      locationNote: "Le groupe revient au palais sous surveillance médicale et politique. Une soirée seulement est disponible.",
      music: "music_confessions",
      maxActions: 2,
      slots: [
        { id: "retour", label: "Retour", detail: "Les portes impériales se referment derrière le convoi." },
        { id: "soir", label: "Soirée", detail: "Les invitations au Bal des Élus arrivent avant le repos." },
      ],
      echo: "Le Bal des Élus commence avec des blessures et des tensions déjà nommées pendant le retour, plutôt qu’avec un groupe artificiellement remis à zéro.",
      spots: [
        {
          id: "infirmerie",
          icon: "✚",
          name: "Infirmerie du palais",
          description: "Les blessures visibles sont traitées plus facilement que les autres.",
          presence: "Draven refuse de rester assis ; Remerii surveille Hylee tout en prétendant examiner sa magie.",
          visualScene: "c10g_end",
          character: "remerii",
          activities: [{
            id: "bilan",
            title: "Ce que les geôles ont changé",
            speaker: "Remerii",
            intro: "Hylee peut parler de la capture, de la colère contre Iriana ou de la façon dont Remerii s’est refermée.",
            resolution: "Le bilan laisse plusieurs blessures ouvertes. Chacun entrera toutefois au bal avec une version commune de ce qui s’est passé.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
        {
          id: "cour",
          icon: "⚔",
          name: "Cour intérieure",
          description: "Le froid du soir laisse assez d’espace pour bouger sans public.",
          presence: "Naïah tourne autour du groupe ; Draven vérifie instinctivement toutes les sorties.",
          visualScene: "c10g_end",
          character: "naiah",
          activities: [{
            id: "retrouver-corps",
            title: "Bouger après l’enfermement",
            speaker: "Narrateur",
            intro: "Un entraînement léger permet de vérifier les limites sans transformer la cour en nouveau combat.",
            resolution: "Le corps d’Hylee cesse progressivement de confondre chaque mur avec une cellule.",
            relation: "naiah",
            approaches: ["sangfroid", "resonance", "audace"],
          }],
        },
        {
          id: "chambres",
          icon: "☾",
          name: "Chambres du groupe",
          description: "Les invitations dorées attendent sur des lits que personne n’a encore utilisés.",
          presence: "Remerii examine chaque ligne de l’invitation. Hylee voit surtout une nouvelle scène où il faudra tenir debout.",
          visualScene: "c11g_001",
          character: "hylee",
          availableFrom: 1,
          activities: [{
            id: "invitation-bal",
            title: "Accepter d’y aller ensemble",
            speaker: "Hylee",
            intro: "Le bal peut devenir une obligation subie, une mission de groupe ou une soirée dont ils refusent de laisser la cour décider entièrement le sens.",
            resolution: "Le groupe n’attend plus du bal qu’il les honore. Il décide seulement de ne pas s’y présenter déjà dispersé.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "akuhn-iriana-coffret",
      anchorScene: "c11i_end",
      nextScene: "c12i_000",
      chapterGate: "Fin du chapitre XI-I",
      title: "Les quartiers d’Amanea",
      subtitle: "Avant que le souvenir ne s’ouvre",
      entryLabel: "Examiner encore les quartiers privés",
      location: "Palais d’Akuhn’Nabad",
      locationNote: "Iriana reste dans les quartiers privés. Le souvenir attend ; la suite ne doit pas être artificiellement retardée.",
      perspective: "Iriana",
      music: "music_c11_complainte_instru",
      maxActions: 2,
      slots: [
        { id: "apres-journal", label: "Après le journal", detail: "Les mots d’Amanea changent encore le silence de la pièce." },
        { id: "avant-souvenir", label: "Avant le souvenir", detail: "La mèche et le coffret réagissent à la magie d’Iriana." },
      ],
      echo: "Iriana entre dans le souvenir avec des ancrages choisis dans la pièce réelle : musique, objets et incohérences du journal peuvent modifier sa lecture de la mémoire.",
      spots: [
        {
          id: "piano",
          icon: "♫",
          name: "Piano noir",
          description: "La dernière note semble encore flotter dans le bois de l’instrument.",
          presence: "Amanea a quitté la pièce, mais sa manière de jouer y reste presque physique.",
          visualScene: "c11i_009",
          character: "iriana",
          activities: [{
            id: "reprendre-melodie",
            title: "Une note sans témoin",
            speaker: "Iriana",
            intro: "Iriana peut rejouer la mélodie, chercher une variation ou refuser d’utiliser la musique comme raccourci vers Amanea.",
            resolution: "Le piano ne livre aucune preuve. Il confirme seulement que leur langage commun existait avant leur rencontre.",
            relation: "amanea",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "bureau",
          icon: "▤",
          name: "Bureau des cartes",
          description: "Plans militaires, rapports et lettres privées se touchent sans appartenir aux mêmes secrets.",
          presence: "Iriana peut regarder ce qui a été laissé visible, sans franchir la limite d’un vol évident.",
          visualScene: "c11i_002",
          character: "iriana",
          activities: [{
            id: "cartes",
            title: "Ce qu’Amanea voulait qu’elle voie",
            speaker: "Narrateur",
            intro: "Certains documents sont trop parfaitement placés pour avoir été oubliés.",
            resolution: "Iriana distingue enfin les informations découvertes de celles qu’Amanea a choisi de lui offrir.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "coffret",
          icon: "◇",
          name: "Coffret de souvenirs",
          description: "La mèche oubliée réagit par pulsations à la présence d’Iriana.",
          presence: "Le reflet magique attend un contact qui pourrait devenir une chute.",
          visualScene: "c11i_end",
          character: "iriana",
          availableFrom: 1,
          activities: [{
            id: "ancrage",
            title: "Préparer un fil vers le présent",
            speaker: "Iriana",
            intro: "Avant de toucher la mémoire, Iriana peut choisir un mot, un objet ou une sensation capable de lui rappeler qui elle est.",
            resolution: "L’ancrage paraît dérisoire face à la puissance du souvenir. Il restera pourtant la seule chose qui lui appartienne entièrement une fois la mémoire ouverte.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "bal-entracte-groupe",
      anchorScene: "c11g_end",
      nextScene: "c12g_001",
      chapterGate: "Fin du chapitre XI-G",
      title: "Un entracte au Bal des Élus",
      subtitle: "La fête continue autour du groupe",
      entryLabel: "Profiter d’un court entracte au bal",
      location: "Palais impérial · Salle des Élus",
      locationNote: "La fête est en cours. Seuls le hall, les alcôves et le balcon attenant sont accessibles.",
      music: "music_c11g_bal",
      maxActions: 1,
      slots: [{ id: "entracte", label: "Entracte", detail: "Les musiciens changent de partition et la cour redistribue ses conversations." }],
      echo: "L’entracte donne au groupe une réaction immédiate aux premières manœuvres de la cour avant que Naïah et Valurn ne reprennent le centre de la soirée.",
      spots: [
        {
          id: "alcove",
          icon: "◒",
          name: "Alcôve latérale",
          description: "Quelques rideaux offrent l’illusion d’une conversation privée.",
          presence: "Hylee et Remerii peuvent comparer ce qu’elles ont compris de la cour.",
          visualScene: "c11g_054",
          character: "remerii",
          partyOutfits: true,
          activities: [{
            id: "pacte-bal",
            title: "Ne pas offrir leur fracture",
            speaker: "Remerii",
            intro: "La cour observe chaque distance entre elles. Hylee peut décider ce qu’elles montrent sans nier ce qui reste blessé.",
            resolution: "Elles ne jouent pas une harmonie parfaite. Elles choisissent simplement de garder leurs désaccords hors des mains de la cour.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
        {
          id: "balcon",
          icon: "☾",
          name: "Balcon du palais",
          description: "L’air frais coupe brièvement la musique et les parfums de la salle.",
          presence: "Naïah observe la fête comme une forêt où les prédateurs portent des bijoux.",
          visualScene: "c11g_end",
          character: "naiah",
          partyOutfits: true,
          activities: [{
            id: "lecture-naiah",
            title: "La cour vue par Naïah",
            speaker: "Naïah",
            intro: "Naïah a déjà repéré qui chasse, qui fuit et qui fait semblant de ne pas avoir peur.",
            resolution: "Sa lecture transforme les groupes mondains en trajectoires de chasse. Hylee saura désormais où ne pas rester isolée.",
            relation: "naiah",
            approaches: ["lucidite", "resonance", "audace"],
          }],
        },
        {
          id: "buffet",
          icon: "◈",
          name: "Buffet des délégations",
          description: "Les plats deviennent une carte politique aussi précise que les places à table.",
          presence: "Valurn prélève des informations avec davantage d’enthousiasme que de nourriture.",
          visualScene: "c11g_024",
          character: "valurn",
          partyOutfits: true,
          activities: [{
            id: "rumeur",
            title: "Une rumeur servie froide",
            speaker: "Valurn",
            intro: "Une remarque sur Forthaven circule parmi les nobles. La corriger, l’exposer ou la détourner produira des effets différents.",
            resolution: "La rumeur ne disparaît pas ; elle change de propriétaire et cesse d’être une arme tenue par une seule personne.",
            relation: "valurn",
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "akuhn-apres-souvenir",
      anchorScene: "c12i_end",
      nextScene: "c13i_001",
      chapterGate: "Fin du chapitre XII-I",
      title: "Revenir du souvenir",
      subtitle: "Quelques minutes pour redevenir Iriana",
      entryLabel: "Reprendre pied dans les quartiers d’Amanea",
      location: "Quartiers privés d’Amanea",
      locationNote: "La transition est urgente et intérieure. Une seule action est possible avant la suite.",
      perspective: "Iriana",
      music: "music_c11_complainte_instru",
      maxActions: 1,
      slots: [{ id: "retour", label: "Retour au présent", detail: "La pièce réelle revient par fragments autour d’Iriana." }],
      echo: "La manière dont Iriana reprend pied colore son attitude lorsqu’elle se retrouve seule face aux traces matérielles d’Amanea.",
      spots: [
        {
          id: "sol",
          icon: "◇",
          name: "Près du coffret",
          description: "Le sol, le bois et la lumière des bougies sont les premières preuves du présent.",
          presence: "Iriana est seule avec une mémoire qui ne lui appartient pas.",
          visualScene: "c12i_end",
          character: "iriana",
          activities: [{
            id: "reprendre-souffle",
            title: "Séparer la mémoire de soi",
            speaker: "Narrateur",
            intro: "Les émotions d’Amanea collent encore à celles d’Iriana. Il faut les reconnaître sans les confondre.",
            resolution: "Iriana garde ce qu’elle a vu sans prétendre avoir vécu à la place d’Amanea.",
            relation: "amanea",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "fenetre",
          icon: "☾",
          name: "Fenêtre du palais",
          description: "Les feux d’Akuhn’Nabad donnent au présent une profondeur impossible à nier.",
          presence: "La ville continue sans savoir ce qu’Iriana vient de traverser.",
          visualScene: "c12i_end",
          character: "iriana",
          activities: [{
            id: "regarder-present",
            title: "Choisir ce qui existe maintenant",
            speaker: "Iriana",
            intro: "Le souvenir explique des blessures ; il ne décide pas automatiquement de ce qu’Amanea est devenue.",
            resolution: "Iriana revient aux faits présents sans effacer la vérité du passé.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "bal-entre-duels",
      anchorScene: "c12g_end",
      nextScene: "c13g_001",
      chapterGate: "Fin du chapitre XII-G",
      title: "Entre deux danses",
      subtitle: "Une respiration avant le dénouement du bal",
      entryLabel: "Choisir un dernier moment libre au bal",
      location: "Bal des Élus",
      locationNote: "Une seule respiration est possible : la soirée doit conserver son élan vers le dénouement.",
      music: "music_c12g_moonlight",
      maxActions: 1,
      slots: [{ id: "pause", label: "Courte pause", detail: "La piste se reforme déjà pour la danse suivante." }],
      echo: "Le dernier duel de danse commence après un choix personnel qui replace Hylee dans la soirée au lieu de la laisser seulement subir son rythme.",
      spots: [
        {
          id: "piste",
          icon: "♫",
          name: "Bord de la piste",
          description: "Les danseurs changent de partenaires sous le regard calculateur de la cour.",
          presence: "Remerii tend déjà une main à Hylee, sans savoir quel ton prendra la prochaine danse.",
          visualScene: "c12g_end",
          character: "remerii",
          partyOutfits: true,
          activities: [{
            id: "choisir-danse",
            title: "Dire ce que cette danse doit être",
            speaker: "Hylee",
            intro: "Une démonstration, un défi, une trêve ou simplement un moment partagé : Hylee peut nommer son intention.",
            resolution: "Remerii reçoit une intention claire plutôt qu’une chorégraphie. Elles entreront sur la piste sans devoir deviner ce que l’autre attend.",
            relation: "remerii",
            approaches: ["audace", "sangfroid", "lucidite"],
          }],
        },
        {
          id: "balcon",
          icon: "☾",
          name: "Balcon d’Al’Gratal",
          description: "La nuit impériale offre quelques secondes loin des regards.",
          presence: "Naïah et Valurn se sont séparés, mais leurs tensions restent visibles.",
          visualScene: "c12g_359",
          character: "naiah",
          partyOutfits: true,
          activities: [{
            id: "verifier-naiah",
            title: "Ce que les souvenirs ont blessé",
            speaker: "Naïah",
            intro: "Hylee peut demander si Naïah va bien sans exiger qu’elle raconte ce que les souvenirs de Valurn ont révélé.",
            resolution: "Naïah ne livre pas le secret. Elle accepte pourtant que la question reste une présence plutôt qu’une intrusion.",
            relation: "naiah",
            approaches: ["lucidite", "sangfroid", "resonance"],
          }],
        },
        {
          id: "couloir",
          icon: "⌁",
          name: "Couloir des invités",
          description: "Les domestiques déplacent les derniers plateaux pendant que la fête prétend ne jamais fatiguer.",
          presence: "Draven cherche une minute de silence avant de retourner affronter les nobles.",
          visualScene: "c12g_end",
          character: "draven",
          partyOutfits: true,
          activities: [{
            id: "draven-repit",
            title: "Une minute sans représentation",
            speaker: "Draven",
            intro: "Draven a supporté la cour, les insultes et les calculs. Il n’a plus besoin d’un conseil, seulement d’un moment qui ne lui demande rien.",
            resolution: "Hylee partage le silence jusqu’à ce que Draven décide lui-même de retourner dans la salle.",
            relation: "draven",
            approaches: ["sangfroid", "lucidite", "audace"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "akuhn-avant-retour-iriana",
      anchorScene: "c13i_end",
      nextScene: "c14_001",
      chapterGate: "Fin du chapitre XIII-I",
      title: "Avant de quitter Akuhn’Nabad",
      subtitle: "Iriana emporte une trahison et une preuve",
      entryLabel: "Préparer le retour d’Iriana",
      location: "Palais d’Akuhn’Nabad",
      locationNote: "Le départ est imminent. Iriana peut agir dans le palais, mais pas lancer une nouvelle exploration de la cité.",
      perspective: "Iriana",
      music: "music_c10_cite",
      maxActions: 2,
      slots: [
        { id: "preparatifs", label: "Préparatifs", detail: "Le portail et les escortes sont en cours de mise en place." },
        { id: "depart", label: "Avant le portail", detail: "Il reste quelques minutes avant le retour à Al’Gratal." },
      ],
      echo: "Iriana revient au Conseil de Guerre avec des choix précis sur ce qu’elle révélera, ce qu’elle protégera et la manière dont elle présentera la rupture avec Amanea.",
      spots: [
        {
          id: "salon-musique",
          icon: "♫",
          name: "Salon nocturne",
          description: "Le piano noir reste derrière elle, avec une touche désormais chargée d’une preuve impossible.",
          presence: "Amanea est absente. Son absence ressemble davantage à une blessure qu’à une victoire.",
          visualScene: "c13i_end",
          character: "iriana",
          activities: [{
            id: "touche",
            title: "Cacher la touche brisée",
            speaker: "Iriana",
            intro: "L’objet doit traverser le portail sans être vu par les gardes ni détecté par la magie du palais.",
            resolution: "La touche disparaît dans une doublure protégée. Elle ne sera ni brandie comme trophée ni abandonnée avec le reste de la vérité.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "antichambre",
          icon: "▤",
          name: "Antichambre du portail",
          description: "Des messagers attendent les dernières consignes diplomatiques.",
          presence: "Iriana peut envoyer un message à Amanea ou laisser le silence porter la rupture.",
          visualScene: "c13i_end",
          character: "iriana",
          activities: [{
            id: "dernier-message",
            title: "Une phrase avant la guerre",
            speaker: "Iriana",
            intro: "Tout message peut devenir une preuve politique. Toute absence de message peut devenir une réponse définitive.",
            resolution: "Iriana choisit une phrase assez exacte pour ne pas promettre la paix ni accepter que la guerre soit déjà la seule issue.",
            relation: "amanea",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
        {
          id: "terrasse",
          icon: "☾",
          name: "Terrasse du palais",
          description: "Les feux verts éclairent une ville qu’Iriana risque de revoir à la tête d’une armée.",
          presence: "Personne ne l’interrompt pendant ces dernières minutes.",
          visualScene: "c13i_end",
          character: "iriana",
          activities: [{
            id: "promesse",
            title: "Définir sa propre limite",
            speaker: "Narrateur",
            intro: "Iriana ne décide pas seule de la guerre. Elle peut toutefois fixer ce qu’elle refusera d’y devenir.",
            resolution: "La limite n’est pas une solution. Elle devient un point auquel revenir lorsque les ordres chercheront à remplacer le jugement.",
            routeOnly: true,
            approaches: ["observer", "agir", "temporiser"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "algratal-matin-apres-bal",
      anchorScene: "c13g_end",
      nextScene: "c14_001",
      chapterGate: "Fin du chapitre XIII-G",
      title: "Le palais au matin",
      subtitle: "Après la nuit du Bal des Élus",
      entryLabel: "Vivre le matin après le bal",
      location: "Palais d’Al’Gratal",
      locationNote: "Le groupe reste dans les quartiers du palais avant le Conseil de Guerre.",
      music: "music_c12g_moonlight",
      maxActions: 2,
      slots: [
        { id: "aube", label: "Aube", detail: "Les derniers invités quittent à peine le palais." },
        { id: "matin", label: "Matin", detail: "Les tenues de fête disparaissent au profit des cartes de guerre." },
      ],
      echo: "Le Conseil de Guerre retrouve un groupe dont les relations ont eu le temps de réagir à la nuit, à ses rapprochements et à ses soupçons.",
      spots: [
        {
          id: "chambres",
          icon: "☾",
          name: "Appartements d’hôtes",
          description: "Les robes, vestes et bijoux du bal attendent d’être rangés pendant que la guerre revient dans les conversations.",
          presence: "Remerii et Hylee se retrouvent selon la forme réellement prise par leur nuit.",
          visualScene: "c13g_end",
          character: "remerii",
          activities: [{
            id: "lendemain-remerii",
            title: "Ne pas laisser la nuit devenir un non-dit",
            speaker: "Remerii",
            intro: "Qu’elle ait été intime, douce ou incomplète, la nuit mérite mieux qu’une fuite embarrassée au matin.",
            resolution: "Elles ne définissent pas tout. Elles accordent simplement la même réalité au matin qu’aux émotions de la nuit.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid", "resonance"],
          }],
        },
        {
          id: "galerie",
          icon: "♜",
          name: "Galerie silencieuse",
          description: "Les serviteurs effacent les dernières traces de fête sous les portraits impériaux.",
          presence: "Draven observe les départs ; Saidin semble attendre une information précise.",
          visualScene: "c13g_end",
          character: "draven",
          activities: [{
            id: "conseiller-masque",
            title: "Comparer ce que chacun a vu",
            speaker: "Draven",
            intro: "La silhouette reconnue près de Tia ne peut plus rester une impression isolée.",
            resolution: "Les détails concordent assez pour devenir une piste, pas encore assez pour devenir une accusation devant le Conseil.",
            relation: "draven",
            approaches: ["lucidite", "sangfroid", "audace"],
          }],
        },
        {
          id: "cuisine",
          icon: "◈",
          name: "Cuisine du palais",
          description: "Les restes du banquet deviennent le petit déjeuner de ceux qui ont travaillé toute la nuit.",
          presence: "Naïah y apparaît sans invitation et refuse de reconnaître qu’elle avait faim.",
          visualScene: "c13g_end",
          character: "naiah",
          activities: [{
            id: "repas-naiah",
            title: "Un repas sans interrogatoire",
            speaker: "Naïah",
            intro: "Naïah porte encore ce qu’elle a vu dans les souvenirs de Valurn. Hylee peut rester sans chercher immédiatement à savoir.",
            resolution: "Le repas garde ses secrets. Il rappelle pourtant à Naïah qu’elle n’est pas seulement utile lorsque sa douleur livre une information.",
            relation: "naiah",
            approaches: ["sangfroid", "lucidite", "resonance"],
          }],
        },
      ],
    }),

    makePeriod({
      id: "algratal-apres-conseil",
      anchorScene: "c14_end",
      nextScene: "c15_001",
      echoScene: "c15_001",
      chapterGate: "Fin du chapitre XIV",
      title: "La nuit avant l’offensive",
      subtitle: "Avant l’aube et le départ de l’armée",
      entryLabel: "Continuer à vivre la nuit avant la guerre",
      location: "Al’Gratal",
      locationNote: "Al’Gratal reste accessible jusqu’au rassemblement des premières colonnes. L’armée partira à l’aube.",
      music: "music_c14_night",
      maxActions: 3,
      slots: [
        { id: "nuit", label: "Nuit", detail: "Le Conseil vient de s’achever." },
        { id: "nuit-profonde", label: "Nuit profonde", detail: "Les casernes et les infirmeries restent éveillées." },
        { id: "avant-aube", label: "Avant l’aube", detail: "Les premières colonnes se préparent au départ." },
      ],
      echo: "Les préparatifs de cette nuit accompagnent Hylee lorsque l’aube rassemble l’armée devant les portes d’Al’Gratal.",
      spots: [
        {
          id: "caserne",
          icon: "⚔",
          name: "Cour des casernes",
          description: "Les armes sont vérifiées une dernière fois sous des lanternes couvertes.",
          presence: "Draven organise des voies de repli tandis que Hylee et Remerii peuvent coordonner leur magie.",
          visualScene: "c14_g_006",
          character: "draven",
          activities: [{
            id: "preparation-combat",
            title: "Préparer ce qui arrive après le premier choc",
            speaker: "Draven",
            intro: "La bataille ne se résumera pas à l’assaut. Blessés, replis et civils réclament déjà une place sur les cartes.",
            resolution: "Le plan gagne des sorties et des points de rassemblement que les discours du Conseil n’avaient pas jugés héroïques.",
            relation: "draven",
            approaches: ["lucidite", "audace", "sangfroid"],
          }],
        },
        {
          id: "infirmerie",
          icon: "✚",
          name: "Infirmerie de campagne",
          description: "Bandages, fioles et brancards sont comptés avant même d’avoir servi.",
          presence: "Des soigneurs acceptent une aide concrète, pas une promesse de victoire.",
          visualScene: "c14_g_006",
          character: "hylee",
          activities: [{
            id: "preparer-soins",
            kind: "job",
            title: "Composer les nécessaires de terrain",
            speaker: "Intendante médicale",
            intro: "Chaque nécessaire doit rester léger tout en couvrant brûlures, magie instable et blessures ordinaires.",
            resolution: "Les sacs sont fermés, marqués et répartis entre les unités. Le travail n’est pas glorieux ; il sera indispensable.",
            resources: { supplies: 2 },
            approaches: ["lucidite", "sangfroid", "resonance"],
          }],
        },
        {
          id: "balcon",
          icon: "☾",
          name: "Balcon du palais",
          description: "La capitale ralentit sous ceux qui savent qu’elle se réveillera au bruit des clairons.",
          presence: "Remerii retrouve Hylee pour une dernière conversation sans stratégie officielle.",
          visualScene: "c14_g_007",
          character: "remerii",
          activities: [{
            id: "avant-guerre",
            title: "Ce qu’elles refusent de remettre à plus tard",
            speaker: "Remerii",
            intro: "La guerre crée l’illusion qu’aucune parole personnelle n’est prioritaire. Elles savent déjà ce que cette illusion peut coûter.",
            resolution: "Aucune promesse ne prétend garantir leur survie. Elles choisissent seulement de ne pas entrer dans la bataille avec une vérité volontairement retenue.",
            relation: "remerii",
            approaches: ["lucidite", "audace", "sangfroid", "resonance"],
          }],
        },
        {
          id: "archives",
          icon: "▤",
          name: "Salle des cartes",
          description: "Les itinéraires officiels et les annotations secrètes d’Iriana ne racontent pas la même offensive.",
          presence: "Saidin étudie les divergences ; Iriana ou Valurn peuvent y revenir selon la route accomplie.",
          visualScene: "c14_i_complete",
          character: "iriana",
          activities: [{
            id: "routes-cachees",
            title: "Deux cartes pour une même guerre",
            speaker: "Narrateur",
            intro: "Comparer les cartes risque d’exposer un mensonge. Ne pas les comparer revient à entrer dans la forêt avec les yeux fermés.",
            resolution: "Une copie discrète conserve les divergences. Le futur chapitre pourra utiliser cette preuve selon la route et la confiance construites.",
            relation: "iriana",
            approaches: ["lucidite", "sangfroid", "audace"],
          }],
        },
      ],
    }),
  ];

  window.SylviniaStoryContent = {
    version: 3,
    approaches: { ...APPROACHES, ...ROUTE_APPROACHES },
    periods,
    byId: Object.fromEntries(periods.map(function byId(period) { return [period.id, period]; })),
    byTarget: Object.fromEntries(periods.map(function byTarget(period) { return [period.target, period]; })),
    relationLabels: {
      remerii: "Remerii",
      iriana: "Iriana",
      valurn: "Valurn",
      naiah: "Naïah",
      draven: "Draven",
      lineva: "Lineva",
      saidin: "Saidin",
      amanea: "Amanea",
      bellirith: "Bellirith",
    },
  };
})();
